Adds Gadpathurian clothes to the loadout.
Aurorastation/Aurora.3 pull request #10045
Opened 2020-09-23 03:24 UTC by TheStryker

![gadpathur stands ii](https://user-images.githubusercontent.com/19821403/93962197-d04a4b00-fd8c-11ea-97f8-a6533773994f.PNG)

![image](https://user-images.githubusercontent.com/19821403/93963273-4b146580-fd8f-11ea-8502-165606bea6dd.png)

Adds clothes (fatigues, overcoat, cadre brassards, sidecap, beret, helmet, rebreather (reskinned breath mask) from Gadpathur, descriptions done by Schwann.

2020-09-23 03:35 UTC, Alberyk requested changes
All items are missing the GEAR_HAS_DESC_SELECTION as their flag.

2020-09-23 07:06 UTC, Chada-1 approved these changes

2020-09-23 13:52 UTC, TheStryker commented
!review

2020-09-23 13:54 UTC, Geevies approved these changes

2020-09-24 23:40 UTC, Chada-1 approved these changes

2020-09-26 18:32 UTC, Alberyk approved these changes

2020-09-27 12:11 UTC, merged