Tech Support Things
Aurorastation/Aurora.3 pull request #10050
Opened 2020-09-23 14:37 UTC by Geevies

* Added a basic circuit kit to Tech Support to tinker with while no one visits the library.
* The Tech Support card no longer bricks devices.

Changed a few visible_messages into audible_messages too.

2020-09-23 14:37 UTC, Geevies commented
!review

2020-09-23 14:46 UTC, Arrow768 requested changes
Since the github app dais "unknown error" when I try to annoyed a specific line let's try to add a review here.


At a first glance that (the removal of the has installed) seems like a bad idea, as this check prevents the repeated installation of the (undetectable) default programs.

It might be fine if there is a check in store_file that prevents the duplicate installation of the same program, but I can't check that atm.

2020-09-23 20:44 UTC, Arrow768 approved these changes

2020-10-03 11:43 UTC, NonQueueingMatt approved these changes

2020-10-23 13:22 UTC, merged