Martial Arts Mastery
Aurorastation/Aurora.3 pull request #10089
Opened 2020-09-26 12:33 UTC by Geevies

* It is now possible to know more than one martial art at the same time, while reaping the benefits of all of them.
* Only the unarmed attacks of your primary martial art will be executed, if you have more than one art, the option to choose will appear in the abilities tab.
* Created a new Martial Arts uplink category, added Sleeping Carp, 12 TC, and Swordsmanship, 5 TC, to it.
* Martial Art projectile deflection has been reflavoured to make it dodging, for the sake of believability. Ha ha ha.

2020-09-26 12:33 UTC, Geevies commented
!review

2020-10-04 15:12 UTC, Alberyk approved these changes

2020-10-07 11:47 UTC, Arrow768 requested changes

2020-10-07 11:47 UTC, Arrow768 commented on code/__defines/misc.dm
> +#define PROJECTILE_DODGED     -3
Add a comment here to explain the difference between continue, force_miss and dodge

2020-10-07 11:47 UTC, Arrow768 commented on code/modules/martial_arts/martial.dm
> +		to_chat(H, SPAN_NOTICE("You can review the combos by recalling the teaches of this art in your abilities tab."))
```suggestion
		to_chat(H, SPAN_NOTICE("You can review the combos by recalling the teachings of this art in your abilities tab."))
```

2020-11-11 20:49 UTC, Geevies commented
!review

2020-11-17 09:19 UTC, NonQueueingMatt approved these changes

2020-11-17 09:28 UTC, merged