Emote Marker
Aurorastation/Aurora.3 pull request #10092
Opened 2020-09-26 14:41 UTC by Geevies

* Vocal emotes made by typing ! in front of the message now gets a blue X as a stand-in for the user's name.

2020-09-26 14:41 UTC, Geevies commented
!review

2020-09-29 20:05 UTC, skull132 approved these changes

2020-10-06 13:50 UTC, NonQueueingMatt requested changes
The X looks bad and out of place. I'm sure a better way would be to just make it italics and make the entire sentence blue.

2020-10-07 11:38 UTC, Arrow768 reviewed
Matt has a valid point.
Blue + Italics should be sufficient.

2020-11-26 10:43 UTC, NonQueueingMatt commented
Stale.

2020-11-26 10:43 UTC, closed without merging