Ghost Role Cancel Fix
Aurorastation/Aurora.3 pull request #10139
Opened 2020-09-30 16:35 UTC by Geevies

* You can now cancel out of joining as a humanoid ghost role by pressing cancel on the species selection screen.

Fixes https://github.com/Aurorastation/Aurora.3/issues/10112

2020-09-30 16:35 UTC, Geevies commented
!bugfix

2020-09-30 16:35 UTC, Geevies commented
!review

2020-10-01 16:14 UTC, NonQueueingMatt commented on code/controllers/subsystems/ghostroles.dm
> +			return
not sure I like this type abuse here, I'd just go with 

```var/result = S.spawn_mob(usr)
if(!ismob(result)) return //or whatever checks
else (continue)...
```

2020-10-01 16:30 UTC, Arrow768 requested changes
Just remove the cancel option instead?

2020-10-02 21:09 UTC, Arrow768 approved these changes

2020-10-03 11:42 UTC, merged