Makes synths not disposable
Aurorastation/Aurora.3 pull request #10169
Opened 2020-10-04 10:08 UTC by LadyFowls

* Please describe the intent of your changes in a clear fashion.
* Please make sure that, in the case of mapping changes, you include images of these changes in the PR's description.
* Please make sure to mark your PR as wip or review required by making a comment with !wip or !review required

### IC changelog
`It is possible and encouraged (for changes that will have a larger impact on players) to write a ic changelog and add it to the PR description.
This changelog will be pushed to the newscasters when the PR is merged`

2020-10-04 10:56 UTC, Arrow768 requested changes

2020-10-04 10:56 UTC, Arrow768 commented on code/modules/recycling/disposal.dm
> +	if(U.isSynthetic())
Same issue as the last time.
This applies to IPCs aswell.

2020-10-06 22:08 UTC, Snakebittenn commented
Again, why?

2020-10-07 07:44 UTC, Arrow768 requested changes

2020-10-07 07:44 UTC, Arrow768 commented on code/modules/recycling/disposal.dm
> +	if(U.isSynthetic() && (!isipc(U)))
This seems overcomplicated.
Is there a reason to do that over a type check of U?

2020-10-16 07:26 UTC, Chada-1 approved these changes

2020-10-19 13:54 UTC, Arrow768 approved these changes

2020-10-23 07:53 UTC, merged