Restricts what accents synthetics can mimic
Aurorastation/Aurora.3 pull request #10178
Opened 2020-10-04 18:56 UTC by Alberyk

What it says in the title.

Todo:

- [ ] consult with the rest of the team

2020-10-04 18:57 UTC, Geevies requested changes
i think it'd be better to define a synth language blacklist

2020-10-05 17:15 UTC, Alberyk commented
A blacklist is not the best way to go because there are more accents than synthetics can't pick than the ones they can.

2020-10-07 10:58 UTC, Arrow768 approved these changes

2020-10-10 11:56 UTC, skull132 approved these changes

2020-10-10 11:57 UTC, skull132 commented
> i think it'd be better to define a synth language blacklist
eh, whitelist is better. Needs explicit approval instead of being the default cause.

2020-10-11 16:33 UTC, merged