Renames Illegal Tech
Aurorastation/Aurora.3 pull request #10174
Opened 2020-10-04 17:15 UTC by Snakebittenn

Just the forward facing bit. Isn't illegal anymore, still hard to get.

2020-10-04 17:16 UTC, Snakebittenn commented
!review

2020-10-04 17:19 UTC, Geevies approved these changes

2020-10-04 18:28 UTC, NonQueueingMatt approved these changes

2020-10-07 13:00 UTC, Arrow768 requested changes

2020-10-07 13:00 UTC, Arrow768 commented on code/modules/research/research.dm
> +	desc = "The study of bleeding-edge, experimental technologies."
```suggestion
	desc = "The study of bleeding-edge, experimental and often restricted technologies."
```
As it covers stuff like hacked AI modules, encryption keys, emags, ...

2020-10-07 14:20 UTC, Arrow768 approved these changes

2020-10-07 17:59 UTC, merged