Vaurca Night Eyes
Aurorastation/Aurora.3 pull request #10179
Opened 2020-10-04 19:26 UTC by Geevies

* Vaurca have gained night eyes similar to Tajara, but receive a blue filter instead of a monochrome one. They remain weak to flashes.

![image](https://user-images.githubusercontent.com/22774890/95025164-2cb04300-0688-11eb-83ba-ed53f6ac6786.png)

2020-10-04 19:26 UTC, Geevies commented
!review

2020-10-06 13:49 UTC, NonQueueingMatt approved these changes

2020-10-07 10:26 UTC, Arrow768 requested changes

2020-10-07 10:26 UTC, Arrow768 commented on code/modules/organs/subtypes/vaurca.dm
> -	owner.Weaken(10)
Undocumented change.
Needs to be restored.

2020-10-07 10:36 UTC, Arrow768 approved these changes
Never mind. 
My local copy was oudated and didnt have the tajara biology.

2020-10-07 21:03 UTC, merged