Small Tesla Links
Aurorastation/Aurora.3 pull request #10191
Opened 2020-10-06 20:38 UTC by Geevies

* Added small tesla links to RnD, under the modular computer catagory. These charge for less, but fit inside smaller computers.
* Command Wristbounds now spawn with small tesla links.

2020-10-06 20:38 UTC, Geevies commented
!review

2020-10-13 00:19 UTC, Alberyk approved these changes

2020-10-17 09:51 UTC, NonQueueingMatt requested changes

2020-10-17 09:51 UTC, NonQueueingMatt commented on code/modules/modular_computers/computers/subtypes/preset_wristbound.dm
> +		tesla_link = new /obj/item/computer_hardware/tesla_link/small(src)
why aren't we just overriding Initiialize() on the command subtype and handling this there? that's a better way of doing it than adding a variable

2020-10-28 00:17 UTC, fernerr requested changes

2020-10-28 00:17 UTC, fernerr commented on code/modules/modular_computers/computers/subtypes/preset_wristbound.dm
> +	command = TRUE
```suggestion
```

2020-11-11 20:47 UTC, closed without merging