Unapologetic Research Buffs: A Rope of Sand
Aurorastation/Aurora.3 pull request #10192
Opened 2020-10-06 21:07 UTC by Snakebittenn

- rscadd: "Adds stasis bags, kinetic analyzers, gas masks, mini extinguishers, extinguisher refills, hoist kits, jetpacks, mobile ladders, heavy flashlights, tethering devices, hand teleporters, tactical masks, NVGs, gravity guns, and ammo displays to the protolathe."
  - rscadd: "Adds brass knuckles to the autolathe's hacked section."

2020-10-06 21:07 UTC, Snakebittenn commented
!review

2020-10-06 22:04 UTC, Snakebittenn commented
Update: Adds maglights and stunrods. Yanks RFDs out of the autolathe, puts them in protolathe.

2020-10-07 08:38 UTC, Arrow768 approved these changes
Technically alright,
but not in favor as all of these things can be ordered via cargo.
There is no need to construct all these things on the station.

Will be discussed between the maintainers.

2020-10-08 17:53 UTC, Geevies approved these changes

2020-10-09 16:17 UTC, NonQueueingMatt requested changes

2020-10-09 16:17 UTC, NonQueueingMatt commented on code/modules/research/designs/protolathe/medical_designs.dm
> +
I'm against these ever being constructible via R&D. Get rid of these.

2020-10-09 16:17 UTC, NonQueueingMatt commented on code/modules/research/designs/protolathe/tool_designs.dm
> +	build_path = /obj/item/tank/jetpack
Too cheap. Should require mining materials and higher tech.

2020-10-09 16:17 UTC, NonQueueingMatt commented on code/modules/research/designs/protolathe/tool_designs.dm
> +	build_path = /obj/item/hand_tele
I'm not a fan of R&D having access to these and printing an asston of them. I want these to be extremely expensive.

2020-10-09 16:17 UTC, NonQueueingMatt commented on code/modules/research/designs/protolathe/weapon_designs.dm
> +	build_path = /obj/item/gun/energy/gravity_gun
Should probably be far more expensive.

2020-10-09 16:37 UTC, Arrow768 submitted a review, later dismissed
Autolathes can and should be used for common items with a very low technology level.
Cargo should be used for items that are reasonably sold by various corporations.
Research should take care of the uncommon high-tech items that arnt sold by corps.

The purpose of research is not to mass manufacture items for the station.

2020-10-09 16:37 UTC, Arrow768 commented on code/modules/research/designs/protolathe/tool_designs.dm
> +	build_path = /obj/item/tethering_device
These are all things that should be ordered via cargo.

2020-10-09 16:37 UTC, Arrow768 commented on code/modules/research/designs/protolathe/weapon_designs.dm
> +	build_path = /obj/item/clothing/glasses/night
Should also be ordered via cargo.

2020-10-09 16:37 UTC, Arrow768 commented on code/modules/research/designs/protolathe/weapon_designs.dm
> +	build_path = /obj/item/device/flashlight/maglight
That is also something for cargo.

2020-10-09 16:37 UTC, Arrow768 commented on code/modules/research/designs/protolathe/weapon_designs.dm
> +	build_path = /obj/item/melee/baton/stunrod
That isnt something we want to have in regular use due to its 80 agony.

2020-10-15 16:24 UTC, NonQueueingMatt approved these changes

2020-10-15 17:00 UTC, Alberyk approved these changes

2020-10-15 23:55 UTC, merged