Odin Ghost Role Update
Aurorastation/Aurora.3 pull request #10220
Opened 2020-10-09 21:00 UTC by Arrow768

* Overhauls Odin Access according to the existing access levels
* Overhauls the get_cetncom_access proc
* Fixes nt ghost roles having complete access to everything (instead of just the station)
* Updates get_cetncom_access with actually used roles
* Updates jobs in get_all_centcom_jobs
* Adds a bartender / chef job to the odin
* Adds a janitor job to the odin
* Adds a medical doctor / pharmacist job to the odin

2020-10-09 22:46 UTC, Arrow768 commented
!review

2020-10-09 22:52 UTC, Geevies approved these changes

2020-10-09 23:20 UTC, fernerr requested changes
Once there's a solution to emergency shuttles being called and then cancelled, opening roles, this'll be good to go.

2020-10-09 23:54 UTC, fernerr approved these changes

2020-10-10 08:54 UTC, Chada-1 approved these changes

2020-10-12 21:06 UTC, merged