Removes old psych treatments
Aurorastation/Aurora.3 pull request #10241
Opened 2020-10-12 21:52 UTC by TheDocOct

Removes the depreciated crystal therapy pod and metronome room from the map, given that the traumas they cure have been removed from standard play for months and even in their admin-only state, are slated for removal.

2020-10-12 22:14 UTC, TheDocOct commented
!review

2020-10-12 22:56 UTC, fernerr requested changes
![psych](https://user-images.githubusercontent.com/35879136/95797021-b4ccc300-0cee-11eb-9acf-b1a6e673628c.PNG)
There's a leftover air alarm and the green edge should go along the window.

2020-10-13 00:06 UTC, TheDocOct commented
augh.......

2020-10-13 01:17 UTC, fernerr approved these changes

2020-10-14 09:45 UTC, furrycactus approved these changes

2020-10-15 02:07 UTC, alsoandanswer commented
Mind removing their code from the game as well?

2020-10-16 19:06 UTC, merged