Trash Piles
Aurorastation/Aurora.3 pull request #10257
Opened 2020-10-14 21:26 UTC by Geevies

* Added various trash piles to maintenance, holding loot for anyone to discover.

2020-10-14 21:26 UTC, Geevies commented
!review

2020-10-15 08:42 UTC, fernerr reviewed
Even if it kind of goes against the spirit of these piles, I feel they ought to be deconstructible somehow. Incase a space gets renovated or changed.
Perhaps if you click a pile on harm intent/(or maybe a matter decompiler) you start picking it apart and after a lengthy timer it goes away generating no useful items, only a bunch of trash?
If someone is hiding in that pile there'd still be a bunch of time to prepare to be found, unlike in a closet.

I also feel they shouldn't be dense, even if it works for some of the sprites, if you get stuck on a small pile of trash on the floor it doesn't feel that good.

2020-10-15 08:42 UTC, fernerr commented on code/game/objects/structures/trash_pile.dm
> +	icon_state = pick("pile1","pile2","pilechair","piletable","pilevending","brtrashpile","microwavepile","rackpile","boxfort","trashbag","brokecomp")
```suggestion
	if(icon_state == initial(icon_state))
		icon_state = pick(icon_states(icon) - icon_state)
```

2020-10-15 08:42 UTC, fernerr commented on code/game/objects/structures/trash_pile.dm
> +	icon_state = pick("pile1","pile2","pilechair","piletable","pilevending","brtrashpile","microwavepile","rackpile","boxfort","trashbag","brokecomp")
Incase if icon state is set to something specific on the map it stays that way.
Also future proofing if more icon states are added or changed.

2020-10-15 09:22 UTC, JohnWildkins requested changes

2020-10-15 09:22 UTC, JohnWildkins commented on aurorastation.dme
> -#include "code\modules\modular_computers\file_system\programs\pai\atmosphere.dm"
i, uh, don't think you meant to delete the atmosphere program in this PR

2020-10-20 14:55 UTC, fernerr approved these changes

2020-10-23 11:49 UTC, JohnWildkins approved these changes

2020-10-23 12:15 UTC, merged