Adds AI, telecomms, bridge consoles and some other misc. things to runtime for easier debugging
Aurorastation/Aurora.3 pull request #10274
Opened 2020-10-17 00:49 UTC by Amunak

* Runtime-2 additions:
  * Telecomms (general and engineering channel should work fully). Includes cooling and consoles.
  * AI core, AI upload with borg spawners and charger, turrets, blast doors.
  * Messaging server room.
* Added cameras all over the place (3 networks total, also added networks to map descriptor).
* Added some intercoms, holopads and displays (both statin and AI status).
* Added some important consoles to bridge.

This means we can now debug radio-related stuff, PDA messaging, anything AI/borg related.

Marked as `backend` in changelog not to scare people about changes to a map they won't ever see. Hope that is fine?

2020-10-17 07:29 UTC, Amunak commented
!review

2020-10-17 07:35 UTC, JohnWildkins commented
while you're at it would you mind mapping in a NTnet relay for modular computers

2020-10-17 08:34 UTC, Amunak commented
> while you're at it would you mind mapping in a NTnet relay for modular computers

Sure, done :)

2020-10-18 10:35 UTC, fernerr requested changes
![flaps](https://user-images.githubusercontent.com/35879136/96365006-0b4a5f00-113e-11eb-9812-fb6cc9e73b62.PNG)
 - The central compartment could use some airflaps too.
 - The turret controller should be moved to be right next to the entrance, so it can be operated from both inside and outside the chamber, else poor bstechs will get stunned all over.

2020-10-18 13:57 UTC, Amunak commented
Fair points, changed. I also fixed badly mapped tcomms area after some last minute changes.

-----

The following additional changes are now reflected in the PR description as well:

Additionally I made the AI chamber smaller, added AI private channel intercoms, requests console, newscaster (and to the bridge, too). I also mapped in air pipes and a new crate with all AI modules.

I also noticed the RTGs could never power the base, so I added in a magical SMES in place of the middle one. Oh and I added some powernet sensors.

2020-10-18 16:40 UTC, fernerr approved these changes

2020-10-20 07:54 UTC, merged