Changes the display case code
Aurorastation/Aurora.3 pull request #10276
Opened 2020-10-17 12:15 UTC by LadyFowls

https://github.com/Aurorastation/Aurora.3/pull/7673 Revisits this PR

2020-10-18 11:02 UTC, mikomyazaki commented
I have a few issues with this PR:

Codewise:
- Changelog, title and PR text _do not explain the change at all_. The change is that you are locking the spare ID behind another ID requirement inside a box. Please make your PRs more descriptive in future, following the [guidelines here](https://github.com/Aurorastation/Aurora.3/blob/master/.github/CONTRIBUTING.md#changelogs).
- I think you're just reinventing closets (an object that contains other objects that can open and close, and have ID locks). This display case should be a closet subtype instead of its own thing. You can make it only accept ID-type items, or instead only items of tiny size or something.

Balance-wise: 
- This greatly affects antagonist gameplay in relation to the spare ID, and defeats the half of the purpose of the spare ID.

2020-11-19 17:37 UTC, mikomyazaki commented on maps/aurora/aurora-4_mainlevel.dmm
> +>>>>>>> master
You've accidentally committed some merge conflict resolution stuff. Need to deal with that. Not sure why that can even pass travis' tests.

2020-11-26 10:45 UTC, NonQueueingMatt requested changes
This isn't something that will pass like this. The spare being stolen isn't something that should be told to everyone at all. It'll just lead to antags getting assblasted far sooner.

2021-01-10 13:38 UTC, skull132 commented
Dead in the water.

2021-01-10 13:38 UTC, closed without merging