Extraction Tweaks
Aurorastation/Aurora.3 pull request #10289
Opened 2020-10-18 20:40 UTC by Geevies

* Knives can now dig out implants as well.
* The knife shrapnel removal menu now requires you to choose the specific external organ you're extracting from as well.
* Implanting someone now visually reports to which organ you'll be doing so.

2020-10-18 20:40 UTC, Geevies commented
!review

2020-10-20 11:45 UTC, NonQueueingMatt requested changes

2020-10-20 11:45 UTC, NonQueueingMatt commented on code/modules/mob/mob_helpers.dm
> +	return "an organ"
I think you're better off just returning organ.name here, honestly, this is too hardcoded for my liking

2020-10-23 10:59 UTC, NonQueueingMatt approved these changes

2020-10-23 10:59 UTC, NonQueueingMatt commented on code/game/objects/items/weapons/implants/implanter.dm
> +		M.visible_message("<span class='warning'>[user] is attempting to implant [M] in the [affected.name].</span>")
```suggestion
		M.visible_message("<span class='warning'>[user] is attempting to implant [M] in \the [affected.name].</span>")
```

2020-10-23 10:59 UTC, NonQueueingMatt commented on code/game/objects/items/weapons/implants/implanter.dm
> +	imp = new /obj/item/implant/explosive( src )
```suggestion
	imp = new /obj/item/implant/explosive(src)
```

2020-10-23 10:59 UTC, NonQueueingMatt commented on code/game/objects/items/weapons/implants/implanter.dm
> +	imp = new /obj/item/implant/mindshield( src )
```suggestion
	imp = new /obj/item/implant/mindshield(src)
```

2020-10-23 11:34 UTC, JohnWildkins approved these changes

2020-10-23 15:20 UTC, merged