Makes spontaneous appendicitis rarer
Aurorastation/Aurora.3 pull request #10336
Opened 2020-10-24 03:26 UTC by Alberyk

What it says in the title.

2020-10-24 10:56 UTC, fernerr requested changes
I feel something like appendicitis isn't severe enough to be listed under the major category, moderate is more appropriate. It'd still have less chance than "communications blackout" of appearing, which feels quite rare enough.

2020-10-25 18:45 UTC, JohnWildkins commented
I'm not sure I even agree with it being in moderate, tbh, but definitely not in major. Bear in mind that an event being in a category means that it's fighting with the others to be picked every cycle, and I don't think one crewmember getting appendicitis should be on the same tier as a blob or meteor wave.

2020-10-26 04:20 UTC, Alberyk commented
It is a moderate event now.

2020-10-26 04:24 UTC, fernerr commented on code/modules/events/event_container.dm
> +		new /datum/event_meta(EVENT_LEVEL_MAJOR, "Appendicitis", 						/datum/event/spontaneous_appendicitis, 		0,		list(ASSIGNMENT_MEDICAL = 5))
```suggestion
		new /datum/event_meta(EVENT_LEVEL_MODERATE, "Appendicitis", 						/datum/event/spontaneous_appendicitis, 		0,		list(ASSIGNMENT_MEDICAL = 5))
```

2020-10-26 05:01 UTC, fernerr approved these changes

2020-10-26 07:49 UTC, NonQueueingMatt approved these changes

2020-10-27 03:44 UTC, merged