Weapon Analysis Printing
Aurorastation/Aurora.3 pull request #10343
Opened 2020-10-24 22:07 UTC by Geevies

* Weapon Analyzers can now print reports about their inserted items via a button at the bottom of the UI.

This also fixes a runtime with an asset of an item that doesn't exist being sent to the UI.

2020-10-24 22:08 UTC, Geevies commented
!review

2020-11-05 18:32 UTC, Amunak approved these changes
I really like this, though I think it would be better to create a proc on item like  `/obj/item/proc/get_print_analysis(var/obj/machinery/printer)` that would gather this kind of information so that it's (1) potentially useful elsewhere and (2) overridable by sub-types. I would also let that proc decide if it want to get analyzed and what / how much information it gives based on the printer argument.

Other than that I really like it.

2020-11-05 18:32 UTC, Amunak commented on code/modules/research/weaponsanalyzer.dm
> +		if(item)
The item check seems duplicate.

2020-11-07 08:54 UTC, Geevies commented
> 
> 
> I really like this, though I think it would be better to create a proc on item like `/obj/item/proc/get_print_analysis(var/obj/machinery/printer)` that would gather this kind of information so that it's (1) potentially useful elsewhere and (2) overridable by sub-types. I would also let that proc decide if it want to get analyzed and what / how much information it gives based on the printer argument.

I think that's doable, but I doooon't think that's really necessary for this. If someone wants to do that for another machine, creating that should be fairly easy.

2020-11-17 09:14 UTC, NonQueueingMatt requested changes
I have to agree with amunak that these kinds of things should start getting offloaded to the object itself rather than a nebulous proc on the machine.

2020-11-17 09:14 UTC, NonQueueingMatt commented on code/modules/research/weaponsanalyzer.dm
> +			dat += "Active Throw Force: [item.force]<br>"
This looks wrong. Throw force is its own var and I'm sure that active damage is not base force.

2020-12-09 09:40 UTC, JohnWildkins approved these changes

2021-01-13 19:36 UTC, NonQueueingMatt requested changes

2021-01-13 19:36 UTC, NonQueueingMatt commented on code/modules/projectiles/guns/energy.dm
> +		. += "Stuns: [initial(P_second.stun) ? "true" : "false"]<br>"
Handle this on the projectile.

2021-01-13 19:36 UTC, NonQueueingMatt commented on code/modules/projectiles/guns/projectile.dm
> +	. += "Stuns: [initial(P.stun) ? "true" : "false"]<br>"
Ditto.

2021-02-01 08:42 UTC, NonQueueingMatt approved these changes

2021-02-01 09:22 UTC, merged