Prevent regular robots from harming living things using their tools
Aurorastation/Aurora.3 pull request #10360
Opened 2020-10-25 16:38 UTC by Amunak

This tries to prevent robots from attacking using their tools (they can't do unarmed attacks and whatnot regardless) unless they are syndicate, emagged or combat without breaking their ability to do surgery and use their tools.

However I have no idea if this is the correct way to do it. It works, but:
* It requires additional code in the attack proc, which is I think a bad place for it.
* Any item can override this check (and probably does), so it's possible some have hardcoded attacks or something and my check won't apply.
* I would've preferred to add the `allow_attack` proc on a more base type, but it'd probably get _very_ complicated with how weird the attack code is.

### Screenshots
#### Regular robot
![dreamseeker_2020-10-25_17-24-35](https://user-images.githubusercontent.com/781546/97113130-9ac8b280-16e8-11eb-965c-287dcfd704c3.png)
#### Combat borg
![dreamseeker_2020-10-25_17-27-08](https://user-images.githubusercontent.com/781546/97113143-a2885700-16e8-11eb-8926-ee18ca4fe644.png)

### IC changelog
All robot chassis have been updated with latest firmware, preventing most occasions of stationbounds accidentally harming living beings.

2020-10-25 16:38 UTC, Amunak commented
!review

2020-10-25 16:43 UTC, Chada-1 approved these changes
Only one change I'd like is to exclude simple mobs from this, since vines, carps, and other stuff would reasonably be attacked by 'borgs/Drones/etc.

I hope this is the dawn of a new era of 'borg play. 🎉

2020-10-25 18:09 UTC, mikomyazaki requested changes

2020-10-25 18:09 UTC, mikomyazaki commented on code/_onclick/item_attack.dm
> +	if(issilicon(user))
I would make it `/mob/proc/allow_attack` and override for silicons & robots. Then you don't need this check or to typecast.

You can make `allow_attack()` return the appropriate message to put in the warning.

2020-10-26 00:17 UTC, Playbahnosh commented
Totally against this.
This would completely gimp all borgs and make them totally defenseless, a free target/punching bag, unable to help the crew/themselves in crisis and unable to fulfill their 4th law. What about situations when borgs do need to use their tools to attack? What about carp, hostile creatures, blob, overgowth or other dangers? What about trying to help a crewman on the other side of a window/wall and no/bolted/broken airlock? What about all the rest of the legit reasons a borg would need/want to take a crack at something? Also, what about the 4th law? This would leave borgs virtually defenseless against any and all dangers, not least of which is antag assholery. I'm sure the fact borgs can no longer defend themselves won't be abused _at all_...

2020-10-26 01:28 UTC, Chada-1 commented
> Totally against this.
> This would completely gimp all borgs and make them totally defenseless, a free target/punching bag, unable to help the crew/themselves in crisis and unable to fulfill their 4th law. What about situations when borgs do need to use their tools to attack? What about carp, hostile creatures, blob, overgowth or other dangers? What about trying to help a crewman on the other side of a window/wall and no/bolted/broken airlock? What about all the rest of the legit reasons a borg would need/want to take a crack at something? Also, what about the 4th law? This would leave borgs virtually defenseless against any and all dangers, not least of which is antag assholery. I'm sure the fact borgs can no longer defend themselves won't be abused _at all_...

Okay so 1, 'borgs will be given new evasive tools like speedboosts. 2, they have flashes which are capable of blinding people who are attacking them. 3. They're completely capable of eliminating vines and other non-sapient creatures.

2020-10-26 04:52 UTC, niennab commented
Since this will significantly change stationbound play, please make a feedback thread.

2020-10-26 12:53 UTC, Amunak commented
Feedback thread: https://forums.aurorastation.org/topic/15072-feedback-preventing-borgs-non-antag-not-hacked-non-combat-from-harming-living-beings/

2020-10-26 16:18 UTC, Amunak commented
Closing for overwhelmingly negative feedback, this is clearly not the way to go.

2020-10-26 16:18 UTC, closed without merging