New poll highlighting, can't open crew manifest before game start.
Aurorastation/Aurora.3 pull request #10368
Opened 2020-10-26 10:33 UTC by NonQueueingMatt

Also converts New to use Initialize().

2020-10-26 10:33 UTC, NonQueueingMatt commented
!review

2020-10-26 17:58 UTC, mikomyazaki requested changes

2020-10-26 17:58 UTC, mikomyazaki commented on code/modules/mob/abstract/new_player/menu.dm
> +			isadmin = 1
```suggestion
		var/isadmin = M.client && M.client.holder
```

Or use TRUE/FALSE at least.

2020-10-26 20:51 UTC, skull132 approved these changes

2020-10-26 20:51 UTC, skull132 commented on code/modules/mob/abstract/new_player/menu.dm
> +			break
```suggestion
		var/newpoll = query.NextRow()
```

2020-10-27 04:21 UTC, mikomyazaki approved these changes

2020-10-27 12:09 UTC, merged