Adds items to the loadout + Himeo voidsuit additions.
Aurorastation/Aurora.3 pull request #10376
Opened 2020-10-27 09:34 UTC by TheStryker

Adds antennas (horn and circle) by NiennaB, as well as a colorable jumpsuit, adapted from the white jumpsuit sprite to the loadout.
Also adds ripped jeans and enables the Himeo voidsuit kit to be used on engineering and atmospheric voidsuits with a unique engineering sprite to boot.
![himeo engineering](https://user-images.githubusercontent.com/19821403/97283319-a6e47980-187a-11eb-9108-9e728c009159.PNG)
![ripped jeans](https://user-images.githubusercontent.com/19821403/97283340-ae0b8780-187a-11eb-917c-81f8b34aa463.PNG)
![image](https://user-images.githubusercontent.com/19821403/97283360-b499ff00-187a-11eb-9541-f12f8998cc2b.png)

2020-10-27 14:18 UTC, TheStryker commented
!review

2020-10-27 15:02 UTC, alsoandanswer approved these changes

2020-10-28 22:40 UTC, fernerr requested changes
Noticed a lot of duplicate code with the numerous istype checks so I made a cleaner version that can also perhaps be used if you do this for other voidsuits/faction kits in the future. 👀 _Maybe a heph kit?_

Also changed the light overlay for the helmets to one that I feel fits better.
Just merge this pr into your branch and it should be good to go: https://github.com/TheStryker/Aurora.3/pull/3

Also this isn't a required change, but I feel the ripped jeans could be more ripped, particularly the back side of them. And the ripped parts of the black pants aren't as noticeable as I feel they should be.

2020-10-29 00:20 UTC, fernerr approved these changes

2020-10-30 10:29 UTC, merged