Point to Malf
Aurorastation/Aurora.3 pull request #10380
Opened 2020-10-27 11:58 UTC by Geevies

* Various late-game malf abilities have been tweaked to point towards the malfunctioning AI.

2020-10-27 11:59 UTC, Geevies commented
!review

2020-10-27 17:36 UTC, mikomyazaki requested changes

2020-10-27 17:36 UTC, mikomyazaki commented on code/game/gamemodes/malfunction/newmalf_ability_trees/HARDWARE.dm
> +		break
This should just be a locate()?

2020-10-27 22:25 UTC, mikomyazaki approved these changes

2020-10-27 23:34 UTC, Amunak approved these changes

2020-10-31 13:50 UTC, Arrow768 requested changes

2020-10-31 13:50 UTC, Arrow768 commented on code/game/gamemodes/malfunction/newmalf_ability_trees/tree_networking.dm
> +			command_announcement.Announce("Warning: Automatic countermeasures ineffective. Breach of primary network firewall imminent. Source of hack traced to [A.name].", "Network Monitoring")
I am against this change as it punishes AIs that dont go the "stealth AI" route and immediately outs them to the entire station as this announces the source of the hack as AI core.

2020-12-08 17:41 UTC, closed without merging