Some Sinta Clothes
Aurorastation/Aurora.3 pull request #10389
Opened 2020-10-28 12:19 UTC by Geevies

* Added new clothes for unathi, wasteland kilts, straw hats, wasteland goggles, standalone hoods.
* Roughspun robes are now recolourable. Mogazali attire is no longer recolourable.
* Added footwraps and caligae to the xeno clothes closet.

I didn't get a picture of everything, since sprites can be reviewed in icondiffbot, but here's one of the roughspun robes.
![image](https://user-images.githubusercontent.com/22774890/97435050-9d194f80-1928-11eb-94e9-15e621f60445.png)

2020-10-28 12:19 UTC, Geevies commented
!review

2020-10-28 13:16 UTC, fernerr approved these changes

2020-10-28 19:25 UTC, Haydizzle requested changes

2020-10-28 19:25 UTC, Haydizzle commented on code/modules/clothing/glasses/glasses.dm
> +	desc = "A pair of old goggles common in the wasteland. Often worn by sailors and fishermen on the sea to keep saltwater out of their eyes before the war, now they take on new life to keep sand out o
A lot of the items here look pretty good. Just looking at the descriptions to be a little less winded;

"A pair of old goggles common in the Wasteland. A few denizens unfortunate enough to not keep this protection on them after the nukes dropped no longer have the ability to see."

2020-10-28 19:25 UTC, Haydizzle commented on code/modules/clothing/suits/alien.dm
> +	desc = "A long tunic made of old banners and other available materials, it acts as a kilt for the poorest or most free-spirited of wastelanders, who aren't afraid to let the sun and sand strike thei
"commoner's kilt"
"A long tunic made of old material that acts as a kilt for the poorest of unathi, who aren't afraid to let the sand and sun strike their scales."

2020-10-28 19:25 UTC, Haydizzle commented on code/modules/clothing/under/accessories/xeno/unathi.dm
> +	desc = "A hood worn commonly by travelers, explorers, and levies. It's main purpose is to block the glare of sun when traveling, and to represent their clan. Often they have the names sewn into the
"A hood worn commonly by unathi away from home. No better way of both representing your clan to foreigners and keeping the sun out of your eyes in style!"

2020-10-28 19:28 UTC, Haydizzle requested changes

2020-10-28 19:28 UTC, Haydizzle commented on code/modules/client/preference_setup/loadout/loadout_xeno/unathi.dm
> +	display_name = "ghazak"
The design is quite literally the flag, and it looks somewhat tacky. I'm opposed to this being added in its current iteration. A better implementation of something like a shoulder pauldron or cape would work well for adding the colors without it being the centerpiece.

2020-10-31 13:37 UTC, Arrow768 approved these changes

2020-11-01 20:00 UTC, Haydizzle approved these changes

2020-11-02 11:31 UTC, merged