Departmental Berets
Aurorastation/Aurora.3 pull request #10391
Opened 2020-10-28 19:56 UTC by alsoandanswer

![dreammaker_Ralah9x79s](https://user-images.githubusercontent.com/42310821/97489617-be1a8880-199a-11eb-94ff-bc48bebb071c.png)

Yeah. Nothing else to say.

2020-10-28 19:56 UTC, alsoandanswer commented
!review

2020-10-28 23:17 UTC, fernerr requested changes
A bunch of these are invisible when worn.

While I admire the work and effort put in here, I don't think going back to the old design of beret is desired by the playerbase at large so this'll need a feedback thread.

What these berets are worn with need to be taken into account too, as I feel some of these were made in a vacuum from their intended outfits.

2020-10-30 16:12 UTC, alsoandanswer commented
!review

2020-10-30 16:50 UTC, JohnWildkins approved these changes

2020-10-30 16:50 UTC, JohnWildkins commented on code/game/objects/random/random.dm
> +/obj/random/softcap
```suggestion
/obj/random/beret
```

You'll also need to add this to the problist in /obj/random/loot

2020-10-30 16:50 UTC, JohnWildkins commented on code/modules/clothing/head/berets.dm
> +	color = get_random_colour(TRUE)
This doesn't appear to set the in-hand sprite's color, jsyk.

2020-10-30 18:20 UTC, alsoandanswer commented
feedback thread created https://forums.aurorastation.org/topic/15081-departmental-berets/

2020-10-30 21:01 UTC, alsoandanswer commented
![Uploading dreammaker_OnfkzvAgAs.png…]()

2020-10-30 21:01 UTC, alsoandanswer commented
![dreammaker_OnfkzvAgAs](https://user-images.githubusercontent.com/42310821/97756614-1f2a9380-1b36-11eb-8fa4-727bd37911b3.png)
![Uploading dreammaker_5mI19sjIQY.png…]()

2020-11-02 02:03 UTC, alsoandanswer commented
its been a while now with no more feedback comments

2020-11-03 16:58 UTC, Amunak approved these changes
It _seems_ to be fine.

2020-11-03 17:14 UTC, Amunak approved these changes

2020-11-03 19:11 UTC, fernerr requested changes
The red tcfl field beret should be returned and added to the outfit of tcfl members.
https://github.com/Aurorastation/Aurora.3/blob/8be7a39c2568ba036b0ddbbcbd46818674ebf4b0/code/datums/outfits/ert/tcfl.dm#L4
I'm in favour of these now that the feedback in the thread has been taken into account.

2020-11-03 19:11 UTC, fernerr commented on code/modules/client/preference_setup/loadout/loadout_head.dm
>  	gear_tweaks += new/datum/gear_tweak/path(tcfl)
Except the dress beret these should not go in the loadout, as they're something worn in the field.

2020-11-04 00:41 UTC, fernerr approved these changes

2020-11-04 07:58 UTC, Amunak approved these changes

2020-11-04 10:22 UTC, merged