Less Log Spam
Aurorastation/Aurora.3 pull request #10403
Opened 2020-10-29 17:30 UTC by Geevies

* Projectiles hitting mobs will now not display an admin log if both the firer and the target has no client connected.

2020-10-29 17:30 UTC, Geevies commented
!review

2020-10-29 18:11 UTC, mikomyazaki requested changes

2020-10-29 18:11 UTC, mikomyazaki commented on code/modules/projectiles/projectile.dm
> +			for(var/mob/M in HV.pilots)
This should only contain mobs.

```suggestion
			for(var/pilot in HV.pilots)
			    var/mob/M = pilot
```

2020-10-29 19:08 UTC, mikomyazaki approved these changes

2020-10-29 22:03 UTC, Amunak requested changes

2020-10-29 22:03 UTC, Amunak commented on code/modules/projectiles/projectile.dm
> +			    var/mob/M = pilot
Travis complains about this (and righgfully so! :P)
```suggestion
				var/mob/M = pilot
```

2020-10-29 22:03 UTC, Amunak commented on code/modules/projectiles/projectile.dm
> +					no_clients = TRUE
As discussed on Discord this constant is wrong.
```suggestion
					no_clients = FALSE
```

2020-10-30 13:06 UTC, Amunak approved these changes

2020-10-31 08:54 UTC, JohnWildkins approved these changes

2020-10-31 13:12 UTC, Arrow768 approved these changes

2020-10-31 13:13 UTC, merged