Maglites in SecTech vendor
Aurorastation/Aurora.3 pull request #10413
Opened 2020-10-30 18:23 UTC by flpfs

What it says on the tin.

2020-10-30 18:23 UTC, flpfs commented
!review

2020-10-30 18:23 UTC, JohnWildkins requested changes

2020-10-30 18:23 UTC, JohnWildkins commented on code/game/machinery/vending_types.dm
>  		/obj/item/device/holowarrant = 5
```suggestion
		/obj/item/device/holowarrant = 5,
```

2020-10-30 18:25 UTC, flpfs commented on code/game/machinery/vending_types.dm
>  		/obj/item/device/holowarrant = 5
whoops

2020-10-30 18:28 UTC, JohnWildkins approved these changes

2020-10-30 20:08 UTC, Chada-1 approved these changes

2020-10-31 13:01 UTC, Arrow768 approved these changes

2020-11-02 18:47 UTC, merged