removes uniform_fat
Aurorastation/Aurora.3 pull request #10435
Opened 2020-11-01 20:46 UTC by alsoandanswer

other than being used for golems which no one even sees anyway

2020-11-01 20:46 UTC, alsoandanswer commented
!review

2020-11-02 08:27 UTC, Geevies requested changes

2020-11-02 08:27 UTC, Geevies commented on html/changelogs/wezzy_trimfat.yml
> +  - rscdel: "Golems can no longer wear uniforms."
```suggestion
  - rscdel: "Larger golems can no longer wear uniforms."
```

2020-11-02 08:27 UTC, Geevies commented on html/changelogs/wezzy_trimfat.yml
> +  - rscdel: "Golems can no longer wear uniforms."
bronze and cloth golems don't have golem bodytypes

2020-11-04 09:58 UTC, Geevies approved these changes

2020-11-04 10:38 UTC, NonQueueingMatt approved these changes

2020-11-04 22:22 UTC, merged