Chem Effects Tweak
Aurorastation/Aurora.3 pull request #10454
Opened 2020-11-04 11:30 UTC by Geevies

* Perconol, mortaphenyl, and oxycomorphine now metabolize three times faster.
* Alkysine can now be used to counteract confused moving chem side effects, while oculine can be used to counteract eyeblur chem side effects.

2020-11-04 11:30 UTC, Geevies commented
!review

2020-11-04 13:44 UTC, Chada-1 commented
Looks good to me and responds to feedback on the Chem rework thread. 👀

2020-11-04 13:44 UTC, Chada-1 approved these changes

2020-11-06 21:57 UTC, Geevies commented on code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Medicine.dm
> +	metabolism = REM / 3.33 // 0.06ish units per tick
```suggestion
	metabolism = REM/10 // same as before when in blood, 0.02 units per tick
```

2020-11-06 21:57 UTC, Geevies commented on html/changelogs/geeves-chem_effects.yml
> +  - tweak: "Perconol, mortaphenyl, and oxycomorphine now metabolize three times faster."
```suggestion
  - tweak: "Mortaphenyl, and oxycomorphine now metabolize three times faster."
```

2020-11-06 22:01 UTC, mikomyazaki requested changes

2020-11-06 22:01 UTC, mikomyazaki commented on code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Medicine.dm
> +	if(!locate(/datum/reagent/oculine) in M.reagents.reagent_list)
I think these things should be chem effects rather than direct typechecks for a certain drug.

2020-11-08 00:20 UTC, mikomyazaki approved these changes

2020-11-10 06:13 UTC, merged