show held item shows icon beside now
Aurorastation/Aurora.3 pull request #10483
Opened 2020-11-07 15:19 UTC by alsoandanswer

yep

2020-11-07 15:19 UTC, alsoandanswer commented
!review

2020-11-11 09:11 UTC, NonQueueingMatt requested changes

2020-11-11 09:11 UTC, NonQueueingMatt commented on code/game/objects/items.dm
> +			M.show_message("<b>[user]</b> holds up [icon2html(src)] [src]. <a HREF=?src=\ref[M];lookitem=\ref[src]>Take a closer look.</a>",1)
This is not proper usage of icon2html. Did you test this? It won't work.

Icon2html needs a second argument, the list of people that would receive the icon. Here that would be `viewers(user)` or similiar.

2020-11-11 18:21 UTC, alsoandanswer commented
![dreamseeker_LNhbxW5cTV](https://user-images.githubusercontent.com/42310821/98849163-bfb17980-248d-11eb-89a8-92a32336bfb8.png)

2020-11-11 18:21 UTC, alsoandanswer commented
Fixed it

2020-11-11 19:44 UTC, NonQueueingMatt approved these changes

2020-11-12 14:42 UTC, Doxxmedearly approved these changes

2020-11-12 15:33 UTC, merged