You can shove all small mobs in the glass jar now
Aurorastation/Aurora.3 pull request #10484
Opened 2020-11-07 15:20 UTC by alsoandanswer

title

2020-11-07 15:20 UTC, alsoandanswer commented
!review

2020-11-08 06:02 UTC, mikomyazaki requested changes

2020-11-08 06:02 UTC, mikomyazaki commented on code/game/objects/items/glassjar.dm
> +			contains = 2
Magic numbers.

2020-11-08 06:02 UTC, mikomyazaki commented on code/game/objects/items/glassjar.dm
> +			to_chat(user, "[L] doesn't fit into \the [src].")
```suggestion
			to_chat(user, "\The [L] doesn't fit into \the [src].")
```

Maybe should also be a warning since you used warning above.

2020-11-08 06:02 UTC, mikomyazaki commented on code/game/objects/items/glassjar.dm
> +		return
```suggestion

```

2020-11-09 11:51 UTC, mikomyazaki requested changes

2020-11-09 11:51 UTC, mikomyazaki commented on code/game/objects/items/glassjar.dm
>  		if(1)
Can use the new defines for the switches now.

```suggestion
		if(MONEY)
```

etc.

2020-11-09 11:51 UTC, mikomyazaki commented on code/game/objects/items/glassjar.dm
>  		if(contains != 1)
And here.

2020-11-12 06:07 UTC, mikomyazaki approved these changes

2020-11-12 14:47 UTC, Doxxmedearly commented on code/game/objects/items/glassjar.dm
> +		user.visible_message(SPAN_NOTICE("[user] scoops [S] into \the [src]."), SPAN_NOTICE("You scoop [S] into \the [src]."))
```suggestion
		user.visible_message(SPAN_NOTICE("\The [user] scoops \the [S] into \the [src]."), SPAN_NOTICE("You scoop \the [S] into \the [src]."))
```

2020-11-12 14:47 UTC, Doxxmedearly commented on code/game/objects/items/glassjar.dm
> +			user.visible_message(SPAN_NOTICE("[user] scoops [L] into \the [src]."), SPAN_NOTICE("You scoop [L] into \the [src]."))
```suggestion
			user.visible_message(SPAN_NOTICE("\The [user] scoops \the [L] into \the [src]."), SPAN_NOTICE("You scoop \the [L] into \the [src]."))
```

2020-11-12 14:47 UTC, Doxxmedearly commented on code/game/objects/items/glassjar.dm
> +				user.visible_message(SPAN_NOTICE("[user] releases [M] from \the [src]."), SPAN_NOTICE("You release [M] from \the [src]."))
```suggestion
				user.visible_message(SPAN_NOTICE("\The [user] releases \the [M] from \the [src]."), SPAN_NOTICE("You release \the [M] from \the [src]."))
```

2020-11-12 14:47 UTC, Doxxmedearly commented on code/game/objects/items/glassjar.dm
> +				user.visible_message(SPAN_NOTICE("[user] releases [S] from \the [src]."), SPAN_NOTICE("You release [S] from \the [src]."))
```suggestion
				user.visible_message(SPAN_NOTICE("\The [user] releases \the [S] from \the [src]."), SPAN_NOTICE("You release \the [S] from \the [src]."))
```

2020-11-12 14:47 UTC, Doxxmedearly commented on code/game/objects/items/glassjar.dm
> +		user.visible_message(SPAN_NOTICE("[user] puts [S.worth] [S.worth > 1 ? "credits" : "credit"] into \the [src]."))
```suggestion
		user.visible_message(SPAN_NOTICE("\The [user] puts [S.worth] [S.worth > 1 ? "credits" : "credit"] into \the [src]."))
```

2020-11-14 13:10 UTC, mikomyazaki approved these changes

2020-11-14 13:10 UTC, mikomyazaki commented on code/game/objects/items/glassjar.dm
> +	if(istype(A, /mob))
```suggestion
	if(ismob(A))
```

2020-11-16 20:54 UTC, Alberyk approved these changes

2020-11-16 20:59 UTC, merged