Converts observation events, posters, and psionics to use decls instead of datums.
Aurorastation/Aurora.3 pull request #10502
Opened 2020-11-09 23:30 UTC by MarinaGryphon

* /datum/observ -> /decl/observ
* /datum/poster -> /decl/poster
* /datum/psionic_faculty -> /decl/psionic_faculty
* /datum/psionic_power -> /decl/psionic_power
* Removes outdated debug code for observation events that's incompatible with decls without some headaches.

2020-11-09 23:34 UTC, MarinaGryphon commented
!review

2020-11-10 06:11 UTC, skull132 requested changes

2020-11-10 06:11 UTC, skull132 commented on code/__defines/misc.dm
> +#define RAISE_EVENT(e, a...) decls_repository.get_decl(/decl/observ/##e).raise_event(##a)
I don't think `##a` is needed here. I used it in the first argument because it acts as a literal paste.

2020-11-11 07:46 UTC, NonQueueingMatt approved these changes
Looks fine other than what Skull said.

2020-12-05 10:23 UTC, JohnWildkins approved these changes

2020-12-16 22:07 UTC, skull132 approved these changes

2020-12-27 15:41 UTC, MarinaGryphon commented
!wip

2021-01-30 14:59 UTC, NonQueueingMatt commented
dead author

2021-01-30 14:59 UTC, closed without merging