Radiator Outpost
Aurorastation/Aurora.3 pull request #10513
Opened 2020-11-11 13:57 UTC by Geevies

* Added a small outpost to the engine radiator area.
* Gave mining and xenoarch access to the engine radiator airlocks, because they keep getting stuck there. Which is hilarious.

2020-11-11 14:04 UTC, Geevies commented
!review

2020-11-11 14:39 UTC, Chada-1 approved these changes

2020-11-13 09:46 UTC, fernerr requested changes
- The piping shouldn't go through a reinforced wall in this instance, leave it open or replace it with a grille or something.
 - Redraw the powercable to use the same way as the scrubber/supply pipes.
 - I don't see the need for another area here, the new room can use the engineering/cooling area too, but change its sound_env if you'd like.

2020-11-13 11:53 UTC, fernerr approved these changes

2020-11-14 14:58 UTC, merged