Updates dmitool
Aurorastation/Aurora.3 pull request #10516
Opened 2020-11-11 16:29 UTC by alsoandanswer

title

2020-11-11 16:30 UTC, alsoandanswer commented
!review

2020-11-13 18:16 UTC, Arrow768 reviewed
Please specify the source of the update.

2020-11-14 03:24 UTC, alsoandanswer commented
I just took it from the latest version of Bay

2020-11-19 22:25 UTC, Arrow768 requested changes

2020-11-19 22:25 UTC, Arrow768 commented on tools/dmitool/dmitool.py
> +""" Python 2.7 wrapper for dmitool.
Python 2.7 is deprecated.
if that´s the latest thing bay has, you should look at tg.

2020-11-21 16:04 UTC, closed without merging