Fixes borg grippers not being able to use drop hotkey (Q) to drop items
Aurorastation/Aurora.3 pull request #10520
Opened 2020-11-11 18:56 UTC by JohnWildkins

title

2020-11-11 18:56 UTC, JohnWildkins commented
!bugfix

2020-11-11 18:57 UTC, JohnWildkins commented
!review

2020-11-11 19:00 UTC, Geevies approved these changes
gamer

2020-11-11 19:44 UTC, NonQueueingMatt approved these changes

2020-11-12 05:04 UTC, mikomyazaki requested changes

2020-11-12 05:04 UTC, mikomyazaki commented on html/changelogs/johnwildkins-gripper.yml
> +  - bugfix: "Drop hotkey (Q) should not properly work to drop things held by robotic grippers."
```suggestion
  - bugfix: "Drop hotkey (Q) should now properly work to drop things held by robotic grippers."
```

2020-11-12 16:08 UTC, NonQueueingMatt commented on html/changelogs/johnwildkins-gripper.yml
> +  - bugfix: "Drop hotkey (Q) should not properly work to drop things held by robotic grippers."
lmao

2020-11-12 18:44 UTC, merged