pAI Encryption Keys
Aurorastation/Aurora.3 pull request #10537
Opened 2020-11-13 16:55 UTC by Geevies

* Clicking on a folded up pAI with an encryption key will now allow the pAI to copy the encryption codes of that key, thus allowing them to speak on those channels.

2020-11-13 16:55 UTC, Geevies commented
!review

2020-11-13 17:54 UTC, Chada-1 approved these changes

2020-11-13 18:02 UTC, Arrow768 submitted a review, later dismissed
Needs to conform to the existing mechanics for encryption keys:

The key needs to be installed physically and may not be "copied"

2020-11-16 15:29 UTC, Geevies commented
!review

2020-11-16 15:43 UTC, mikomyazaki requested changes

2020-11-16 15:43 UTC, mikomyazaki commented on code/game/objects/items/devices/paicard.dm
> +					break
You can do both of these at once like:
```suggestion
		for(var/thing in EK.channels | EK.additional_channels)
			if(!radio.channels[thing])
				added_channels = TRUE
				break
```

If you want to.

2020-11-16 15:43 UTC, mikomyazaki commented on code/game/objects/items/devices/paicard.dm
> +			radio.channels[ch_name] = radio.FREQ_LISTENING
```suggestion
		for(var/ch_name in EK.channels | EK.additional_channels) 
			radio.channels[ch_name] = radio.FREQ_LISTENING
```

Same here.

2020-11-16 15:43 UTC, mikomyazaki commented on code/modules/modular_computers/file_system/programs/pai/radio.dm
> +	VUEUI_SET_CHECK(data["channels"], pai_channels, ., data)
`VUEUI_SET_CHECK` does not work for lists. You must use `VUEUI_SET_CHECK_LIST` instead.

2020-11-17 07:21 UTC, mikomyazaki requested changes

2020-11-17 07:21 UTC, mikomyazaki commented on code/modules/modular_computers/file_system/programs/pai/radio.dm
> +	data["channels"] = pai_channels
If you're going to do this, you need to always return data. It won't return data currently if *only* pai_channels changes.
Recommend removing the VUEUI_SET_CHECKS and just doing `return data` at the end.

Technically we are already always returning data already due to how header data works (which is bad but we've got it *everywhere* now...)

2020-11-17 21:18 UTC, mikomyazaki approved these changes

2020-11-19 11:24 UTC, merged