VueUI Titlebars, Resizing, and Scrolling other edition
Aurorastation/Aurora.3 pull request #10564
Opened 2020-11-16 11:40 UTC by Karolis2011

Thanks to @JohnWildkins for most of work, and his original PR #10528

Modular computers look like: 
![image](https://user-images.githubusercontent.com/11229891/99248158-b23f1b00-2810-11eb-97bc-61ba74786de5.png)![image](https://user-images.githubusercontent.com/11229891/99248309-ea465e00-2810-11eb-8ca4-92262a50272a.png)
![image](https://user-images.githubusercontent.com/11229891/99248390-08ac5980-2811-11eb-86ba-7eaf47dab409.png)
![image](https://user-images.githubusercontent.com/11229891/99248525-4610e700-2811-11eb-9db2-15615fe09a6e.png)

2020-11-17 00:31 UTC, JohnWildkins requested changes
There's nothing super syntactically wrong and the JS code for dragging is solid, which is great. The styling is pretty off, though. Compare your nano-dark header to mine:

![yours](https://cdn.discordapp.com/attachments/131489773268238336/778049023424593920/unknown.png)
![mine](https://cdn.discordapp.com/attachments/131489773268238336/778049001953951774/unknown.png)

I feel that the latter is cleaner; there's no awkward gap between the headers and the spacebar, the computer's header is distinct from the main titlebar, and the elements on the top bar are all centered with respect to each other. (As I said on discord, I'm also not a fan of how thick the X button is, and doubly so that it isn't a hover-over with a changing background).

This PR is also missing the debug button functionality; right now it seems to load the debug menu for everyone(?) which I'm assuming is something WIP. The hacky focusing events I was using to maintain focus on the window are also gone, which is resaonable, but it means that you now lose focus on the window if you resize it. 

It's obviously not my call but I'd prefer if the backend/JS changes here were simply brought onto my PR, rather than the other way around.

2020-11-17 00:31 UTC, JohnWildkins commented on code/modules/vueui/ui.dm
> +	sdata["debug"] = user && check_rights(R_DEV, FALSE, user=user)
```suggestion
```

This is set twice here

2020-12-02 12:07 UTC, Karolis2011 commented
!review

2020-12-06 16:49 UTC, Karolis2011 commented
Focus issues have been addressed.
Ui closing have been handled in a way that allows any UI to be closed.
Now if you have UIDEBUG enabled behavior is same as old, but if you have rights you get debug button that allows to enable debug view.
Also odd gaps have been addressed.
![image](https://user-images.githubusercontent.com/11229891/101286448-41799600-37f3-11eb-8f5a-2ab94a7d46e2.png)
![image](https://user-images.githubusercontent.com/11229891/101286462-548c6600-37f3-11eb-986e-db90bc160cb9.png)

2020-12-06 18:23 UTC, skull132 commented
PR rejected in favour of Wildkins'.

I prefer the look of the other one. Plus, you were non-communicative over the course of handling these matters, ergo, we prefer the side which actually talked.

I think the wonkiness of dragging is the only issue Wildkins' PR doesn't yet fix, so you're free to port an improved JS backend to master.

2020-12-06 18:23 UTC, closed without merging