Adds Golden Deep clothes and other loadout items.
Aurorastation/Aurora.3 pull request #10578
Opened 2020-11-17 08:53 UTC by TheStryker

![golden deep](https://user-images.githubusercontent.com/19821403/99367394-dbd17280-28f4-11eb-9774-534b13d97c31.PNG)
Adds three Golden Deep outfits by Kyres to the loadout.
![golden deep suits](https://user-images.githubusercontent.com/19821403/99367361-d2e0a100-28f4-11eb-97ce-338a45ebd5c5.PNG)
Adds a Golden Deep suit and skirtsuit by NiennaB.
![tcfl armband](https://user-images.githubusercontent.com/19821403/99367796-5d290500-28f5-11eb-8b36-910953c8182e.PNG) ![mars hoodie](https://user-images.githubusercontent.com/19821403/99367799-5dc19b80-28f5-11eb-96a2-7f6ee55f4df8.PNG)
Adds a Tau Ceti and Martian/Gus hoodie.

2020-11-17 11:28 UTC, TheStryker commented
!review

2020-11-19 11:50 UTC, fernerr requested changes
The mars hoodie lacks one icon state, 'hoodie_mars_t' for when the hood is up, else it'll be invisible in the inventory, even if it's visible on the character.

2020-11-19 12:43 UTC, fernerr approved these changes

2020-11-19 15:00 UTC, flpfs commented
Incredibly based...

2020-11-19 22:35 UTC, Arrow768 approved these changes

2020-11-19 22:41 UTC, merged