Overdue wristbound resprite : Death of Retro-futurism
Aurorastation/Aurora.3 pull request #10585
Opened 2020-11-17 19:43 UTC by alsoandanswer

![dreammaker_09cTYlIgFC](https://user-images.githubusercontent.com/42310821/99439453-2b915780-2950-11eb-808b-b1748fb55c17.png)

I'm also changing the colors back, because after reading [https://forums.aurorastation.org/topic/14816-adjust-the-wristbound-computer-sprites](the feedback thread) more closely, a lot of people were fine with the colors, just not the onmobs.

2020-11-17 19:44 UTC, alsoandanswer commented
!review

2020-11-17 19:45 UTC, TheDocOct commented
Feedback thread, please

2020-11-17 20:16 UTC, alsoandanswer commented
i feel the feedback thread above was enough, but if a maintainer asks, sure

2020-11-17 21:51 UTC, Greenjoe12345 commented on code/_helpers/global_lists.dm
> -var/global/list/pdalist = list("Nothing", "Standard PDA", "Classic PDA", "Rugged PDA", "Slate PDA", "Smart PDA", "Tablet", "Wristbound")
is removing the tablet intended?

2020-11-18 08:58 UTC, furrycactus commented on code/_helpers/global_lists.dm
> -var/global/list/pdalist = list("Nothing", "Standard PDA", "Classic PDA", "Rugged PDA", "Slate PDA", "Smart PDA", "Tablet", "Wristbound")
Is removing _any_ of this intended?

2020-11-18 19:52 UTC, alsoandanswer commented on code/_helpers/global_lists.dm
> -var/global/list/pdalist = list("Nothing", "Standard PDA", "Classic PDA", "Rugged PDA", "Slate PDA", "Smart PDA", "Tablet", "Wristbound")
my bad must be a bad merge

2020-11-21 09:17 UTC, Geevies commented
i agree with making a feedback thread

2020-11-27 14:14 UTC, NonQueueingMatt commented
Think this should go up to the forums. I would like to avoid a fiasco like last time.

2020-12-03 19:09 UTC, alsoandanswer commented
https://forums.aurorastation.org/topic/15253-wristbounds-v2/

2020-12-28 10:52 UTC, skull132 approved these changes

2021-04-06 22:25 UTC, JohnWildkins requested changes
needs a couple minor fixes, and additionally: loadout wristbounds do not get icons set properly. i don't think this is a bug with this PR necessarily, but it should be a simple fix. hit me up on discord about it

2021-04-06 22:25 UTC, JohnWildkins commented on code/modules/modular_computers/computers/subtypes/preset_pda.dm
> +	hidden = TRUE
accidental newline save here

2021-04-06 22:25 UTC, JohnWildkins commented on code/datums/outfits/outfit.dm
> +			I.desc_fluff = "For its many years of service, this model has held a virtual monopoly on the PDA market. The secret? A lapel pin affixed to the back."
this needs to go outside the switch or in its own case, right now this doesn't compile

2021-04-18 10:45 UTC, NonQueueingMatt commented
Inactive author.

2021-04-18 10:45 UTC, closed without merging