Updates security processing console
Aurorastation/Aurora.3 pull request #10582
Opened 2020-11-17 13:14 UTC by Aboshedab

1- Added missing regulations from the wiki to processing console.
2- Update and adjust descriptions, names, credit fines and time to match the wiki for the processing console.

For the fines, it raises the minimum to what is on the wiki for the most part. The maximum is then changed to be half more, double or following specific instructions of the wiki.

All this is done in communication with Lancer.

https://wiki.aurorastation.org/index.php?title=User:Aboshedab

Wiki is ready for replacement for when the PR is merged.

2020-11-17 13:27 UTC, Aboshedab commented
!review

2020-11-17 13:35 UTC, mikomyazaki approved these changes

2020-11-18 14:29 UTC, Arrow768 requested changes

2020-11-18 14:29 UTC, Arrow768 commented on code/modules/law/laws/low_severity.dm
> +	name = "i106 - Misuse of Public Radio Channels"
Dont change the id it is used for db statistics.

2020-11-18 14:29 UTC, Arrow768 commented on code/modules/law/laws/low_severity.dm
> +	id = "i106"
same here

2020-11-18 14:29 UTC, Arrow768 commented on code/modules/law/laws/low_severity.dm
> +	name = "i107 - Violation of Injunction"
same here

2020-11-18 14:29 UTC, Arrow768 commented on code/modules/law/laws/low_severity.dm
> +	id = "i107"
same here

2020-11-18 14:29 UTC, Arrow768 commented on code/modules/law/laws/low_severity.dm
> +	name = "i108 - Slandering a Head of Staff"
same here

2020-11-18 14:29 UTC, Arrow768 commented on code/modules/law/laws/low_severity.dm
> +	id = "i108"
same here

2020-11-18 14:29 UTC, Arrow768 commented on code/modules/law/laws/low_severity.dm
> +	name = "i109 - Slander or Verbal Abuse"
same here

2020-11-18 14:29 UTC, Arrow768 commented on code/modules/law/laws/low_severity.dm
> +	id = "i109"
same here

2020-11-18 14:29 UTC, Arrow768 commented on code/modules/law/laws/low_severity.dm
> +	name = "i110 - Failure to Execute an Order"
same here

2020-11-18 14:29 UTC, Arrow768 commented on code/modules/law/laws/low_severity.dm
> +	id = "i110"
same here

2020-11-18 14:29 UTC, Arrow768 commented on code/modules/law/laws/low_severity.dm
> +	name = "i111 - Sexual Harassment"
same here

2020-11-18 14:29 UTC, Arrow768 commented on code/modules/law/laws/low_severity.dm
> +	id = "i111"
same here

2020-11-18 14:29 UTC, Arrow768 commented on code/modules/law/laws/low_severity.dm
> +	name = "i112 - Animal Cruelty"
same here

2020-11-18 14:29 UTC, Arrow768 commented on code/modules/law/laws/low_severity.dm
> +	id = "i112"
same here

2020-11-18 14:29 UTC, Arrow768 commented on code/modules/law/laws/low_severity.dm
> +	name = "i113 - Vandalism"
same here

2020-11-18 14:29 UTC, Arrow768 commented on code/modules/law/laws/low_severity.dm
> +	id = "i113"
same here

2020-11-18 14:29 UTC, Arrow768 commented on code/modules/law/laws/low_severity.dm
> +	name = "i114 - Threat of Murder or Serious Injury"
same here

2020-11-18 14:29 UTC, Arrow768 commented on code/modules/law/laws/low_severity.dm
> +	id = "i114"
same here

2020-11-18 14:29 UTC, Arrow768 commented on code/modules/law/laws/low_severity.dm
> +	name = "i115 - Disrespect to the Dead"
same here

2020-11-18 14:29 UTC, Arrow768 commented on code/modules/law/laws/low_severity.dm
> +	id = "i115"
same here

2020-11-18 14:29 UTC, Arrow768 commented on code/modules/law/laws/low_severity.dm
> +	name = "i116 - Excessive Use of Force in Detainment"
same here

2020-11-18 14:29 UTC, Arrow768 commented on code/modules/law/laws/low_severity.dm
> +	id = "i116"
same here

2020-11-18 14:29 UTC, Arrow768 commented on code/modules/law/laws/low_severity.dm
> +	name = "i117 - Violation of Privacy Laws"
same here

2020-11-18 14:29 UTC, Arrow768 commented on code/modules/law/laws/low_severity.dm
> +	id = "i117"
same here

2020-11-18 14:29 UTC, Arrow768 commented on code/modules/law/laws/low_severity.dm
> +	name = "i118 - Illegal Search"
same here

2020-11-18 14:29 UTC, Arrow768 commented on code/modules/law/laws/low_severity.dm
> +	id = "i118"
same here

2020-11-19 13:38 UTC, Arrow768 approved these changes

2020-11-19 13:44 UTC, merged