Adds an adhomian surgeon garb
Aurorastation/Aurora.3 pull request #10599
Opened 2020-11-19 16:09 UTC by Alberyk

Adds a new item to the Tajara xenoloadout, a surgeon grab that covers most of the body. Works like a hoodie to deploy a mask. Sprites were made by wezzy.

2020-11-19 16:16 UTC, Geevies approved these changes

2020-11-19 19:57 UTC, KasparoVy commented
Looks nice, I dig the sprites

2020-11-19 22:46 UTC, Arrow768 approved these changes

2020-11-21 16:25 UTC, alsoandanswer commented on code/modules/clothing/suits/xeno/tajara.dm
> +	The result was a healthcare revolution where average lifespans increased by over a decade, however many diseases native to Adhomai still remain unknown by medical \
I feel this is a run-on sentence

2020-11-21 16:58 UTC, alsoandanswer requested changes
also you added a priestrobe on accident to tajara_items.dmi, i presume

2020-11-21 18:15 UTC, alsoandanswer approved these changes

2020-11-22 00:19 UTC, Chada-1 approved these changes

2020-11-22 16:12 UTC, merged