A storage for the research department
Aurorastation/Aurora.3 pull request #10614
Opened 2020-11-20 12:08 UTC by FieryTech

![proposition](https://user-images.githubusercontent.com/26222998/99798179-d7919900-2b30-11eb-9732-33e1748cca29.JPG)

A pretty simple addition:
- 5x7 room with scientist access attached to it.
- A showcase, the windoor is locked to RD only.
- A gun cabinet with scientist access, for the prototypes.
- Four crate emplacement, for that sweet storage.
- A exosuit charging pad, where you can hide your combat exosuit.
- The Research Director can lock the room, by pressing the button.
- Camera, air alarm, APC, etc. STUFF, BUTTONS! Everything.

It's my first contribution ever, please be gentle. :b

2020-11-20 12:34 UTC, NonQueueingMatt commented
I think the gun cabinet should have different colors (science colors, specifically) to not be confusing.

2020-11-20 12:48 UTC, Amunak requested changes

2020-11-20 12:48 UTC, Amunak commented on maps/aurora/aurora-4_mainlevel.dmm
>  	},
I believe this should never appear anywhere.
```suggestion
/obj/machinery/vending/snack,
```

2020-11-20 12:48 UTC, Amunak commented on maps/aurora/aurora-4_mainlevel.dmm
> +	step_y = 27
Same here.
```suggestion
	req_access = list(30)
```

2020-11-20 13:38 UTC, FieryTech commented
> 
> 
> I think the gun cabinet should have different colors (science colors, specifically) to not be confusing.

I asked a friend to recolor the sprite, will implement on reception!

2020-11-20 16:19 UTC, fernerr commented
Very well done on your first contribution, props. One thing, rather than having the area be the /area/rnd/lab with the name changed via a manual edit, I'd prefer you define a new area for this room somewhere here: https://github.com/Aurorastation/Aurora.3/blob/a9514e19ed6ce1a854de6aa1602ba871f423fa5c/maps/_common/areas/station/research.dm#L28 
As /area/rnd/storage is already used by toxins, another path name needs to be chosen, perhaps /area/rnd/strongroom

2020-11-20 17:48 UTC, FieryTech commented
![proposition](https://user-images.githubusercontent.com/26222998/99832464-daa47d80-2b60-11eb-9b3d-efefc287b58e.JPG)
- Addition of a Science gun locker with sprites and script, science access lock.
- Addition of a new static area for the storage, and not a manual one.

2020-11-21 14:10 UTC, FieryTech commented
Reintroduced Hydrogen and Holopad PR to resolve version conflicts.

!review

2020-11-21 14:41 UTC, mikomyazaki commented
Fixed some problems with commit history at author's request.

2020-11-21 21:14 UTC, fernerr approved these changes

2020-11-22 11:45 UTC, Amunak commented
Somehow the diff still shows ~~some holopads as removed~~ the science holopad as moved? 🤔

2020-11-22 12:18 UTC, FieryTech commented
Should be fixed, the diff is now perfectly equal to actual state, and shows this PR changes.

2020-11-22 12:26 UTC, FieryTech commented
Fixed, the holopad was one meter too far to the right compared to the current server map.

2020-11-23 09:15 UTC, Geevies approved these changes

2020-11-23 09:46 UTC, Amunak approved these changes

2020-11-23 12:13 UTC, merged