Replaces DMItool with contemporary /tg/station version.
Aurorastation/Aurora.3 pull request #10624
Opened 2020-11-21 16:18 UTC by alsoandanswer

title

2020-11-21 16:28 UTC, alsoandanswer commented
!review

2020-11-27 14:20 UTC, NonQueueingMatt submitted a review, later dismissed

2020-11-27 14:20 UTC, NonQueueingMatt commented on .gitattributes
> +*.dmi merge=dmi
This does not look like something we want to change. Specifically, the eol part.

2020-11-28 00:49 UTC, Amunak approved these changes

2020-12-01 17:55 UTC, Arrow768 requested changes

2020-12-01 17:55 UTC, Arrow768 commented on .gitattributes
> +#*.dmi binary
delete that instead of commenting it out
```suggestion
```

2020-12-01 17:55 UTC, Arrow768 commented on .gitattributes
> +#*.dmm text
delete that instead of commenting it out
```suggestion
```

2020-12-01 17:55 UTC, Arrow768 commented on .gitattributes
> +*.dmm text merge=dmm
```suggestion
*.dmm text merge=dmm eol=crlf
```

2020-12-03 18:02 UTC, Arrow768 approved these changes

2020-12-04 01:21 UTC, merged