Mirage Projectors
Aurorastation/Aurora.3 pull request #10621
Opened 2020-11-21 11:13 UTC by Geevies

* Added mirage projectors, little items that can be activated by using them in-hand or alt-clicking them, which will place them on the floor and create a hardlight copy of you."
* Examining humans no longer brings up an image of them next to their name.

![image](https://user-images.githubusercontent.com/22774890/99875846-518e5480-2bfb-11eb-81b3-1db3884ff179.png)
![image](https://user-images.githubusercontent.com/22774890/99875849-53581800-2bfb-11eb-8c13-36af0794e671.png)

2020-11-21 11:13 UTC, Geevies commented
!review

2020-11-23 10:52 UTC, mikomyazaki requested changes

2020-11-23 10:52 UTC, mikomyazaki commented on code/game/objects/items/devices/chameleonproj.dm
> +	parent.disrupt()
I think this could use some sort of message to the person poking the mirage.

2020-11-23 10:52 UTC, mikomyazaki commented on code/modules/mob/living/carbon/human/human_species.dm
> +/mob/living/carbon/human/dummy/mannequin/proc/copy_appearance(var/mob/living/carbon/human/H)
This should copy the overlays of the source mob, not directly create new items.

Item duplication like this could lead to some problems, I think.

2020-11-23 10:52 UTC, mikomyazaki commented on code/game/objects/items/devices/chameleonproj.dm
> +/obj/item/device/mirage/proc/activate(var/mob/user)
Item needs a cooldown period.

2020-11-27 18:10 UTC, MarinaGryphon commented on code/modules/mob/living/carbon/human/human_species.dm
> +/mob/living/carbon/human/dummy/mannequin/proc/copy_appearance(var/mob/living/carbon/human/H)
I believe this is so you can examine it and see what they're carrying; `H.appearance` includes overlays, which includes the clothes. Copying the overlays for visuals isn't necessary at all, but you CAN examine them separately. May be worth just generating the description text when it's made and saving it for later.

2020-12-08 17:16 UTC, Geevies commented on code/modules/mob/living/carbon/human/human_species.dm
> +/mob/living/carbon/human/dummy/mannequin/proc/copy_appearance(var/mob/living/carbon/human/H)
@mikomyazaki you need to copy these items, otherwise the examine is made. the description text cannot be generated because items can be examined via an examine. i've tried alternatives

2020-12-08 17:39 UTC, Geevies commented
!review

2020-12-09 09:45 UTC, JohnWildkins approved these changes
zany

2020-12-28 10:25 UTC, skull132 requested changes

2020-12-28 10:25 UTC, skull132 commented on code/modules/mob/living/carbon/human/human_species.dm
> +/mob/living/carbon/human/dummy/mannequin/proc/copy_appearance(var/mob/living/carbon/human/H)
I am not sure this is a sane solution at all. For a variety of reasons, but the primary being that not all items are meant to be trivially constructable like this. It'll start runtiming the moment an item expects arguments. What's worse, it could lead to the copying of items which have global side-effects in their constructor.

While I can understand why you'd do this, our examine system effectively necessitates this to pull off the illusion properly, this will lead to yank and exploits.

2021-01-13 19:54 UTC, Geevies commented
too many problems trying to recreate examine, good night sweet prince

2021-01-13 19:54 UTC, closed without merging