Fixes Supermatter Auto-Setup (the Setup-Supermatter debug verb) by mapping it in
Aurorastation/Aurora.3 pull request #10630
Opened 2020-11-22 14:55 UTC by Amunak

* Mapped in SM setup markers to make the verb work.
* Fixed minor codestyle issues, added a check that at least one SM Core marker is mapped.
* Updated rights check.
* Added marker to start freezers.
* Added new "x icon" for this type of markers; it's yellow and half transparent for easier mapping.

2020-11-22 14:57 UTC, Amunak commented
!bugfix

2020-11-22 14:57 UTC, Amunak commented
!review

2020-11-23 09:16 UTC, Geevies approved these changes

2020-11-23 11:12 UTC, fernerr approved these changes

2020-11-23 11:30 UTC, NonQueueingMatt requested changes

2020-11-23 11:30 UTC, NonQueueingMatt commented on code/modules/supermatter/setup_supermatter.dm
>  	for(var/obj/effect/engine_setup/core/C in world)
This should just be using landmarks instead of a world loop.

2020-11-23 11:30 UTC, NonQueueingMatt commented on code/modules/supermatter/setup_supermatter.dm
>  	for(var/obj/effect/engine_setup/filter/F in world)
Same deal.

2020-11-24 09:24 UTC, Amunak commented
oh no

2020-11-24 10:03 UTC, Amunak commented
I need to test this out first, it's possible the landmarks don't get added to the global list.

2020-11-24 20:04 UTC, Amunak commented
Should be fixed. I had to repath the landmarks to be actual landmarks.

While in there I also added other coolant options, improved some of the code and improved filter handling.

'cause why not cool the SM with stupid stuff as the pinnacle of adminabuse, right?

![image](https://user-images.githubusercontent.com/781546/100145414-9387f680-2e98-11eb-9a82-dab56feff3e6.png)

2020-11-25 12:56 UTC, merged