glass jar fixes but its atomic
Aurorastation/Aurora.3 pull request #10642
Opened 2020-11-24 01:51 UTC by alsoandanswer

title

2020-11-24 01:51 UTC, alsoandanswer commented
!bugfix

2020-11-24 01:51 UTC, alsoandanswer commented
!review

2020-11-26 10:28 UTC, NonQueueingMatt requested changes

2020-11-26 10:28 UTC, NonQueueingMatt commented on code/game/objects/items/glassjar.dm
> +	if(istype(A, /mob/living/simple_animal))
Why are we checking specifically for simple animals?

2020-11-26 10:28 UTC, NonQueueingMatt commented on code/game/objects/items/glassjar.dm
> +			playsound(src, pickup_sound, PICKUP_SOUND_VOLUME)
This doesn't look like a bugfix to me.

2020-12-01 07:51 UTC, closed without merging