Headtail Storage
Aurorastation/Aurora.3 pull request #10640
Opened 2020-11-23 13:58 UTC by Geevies

* Skrell can now store a single small item in their headtails via an ability in the top left corner of their screen.

Loosely ported from https://github.com/ParadiseSS13/Paradise/pull/7377. Stunning doesn't make them drop their item here.

2020-11-23 13:58 UTC, Geevies commented
!review

2020-11-23 14:12 UTC, Arrow768 submitted a review, later dismissed

2020-11-23 14:12 UTC, Arrow768 commented on code/modules/mob/living/carbon/human/human.dm
> +	dat += species.handle_strip("\ref[src]")
I am not a fan of that implementation.
Here you use a species proc to determine the text that should be displayed.

2020-11-23 14:12 UTC, Arrow768 commented on code/modules/mob/living/carbon/human/human.dm
> +
And here you hard-code the button that is being pressed.

This should not be hardcoded, but rather handled on a species level.
I.e. with a additional parameter species_specific in the clicked link which then causes a "species handler" to handle that interaction.

2020-11-23 15:38 UTC, Alberyk submitted a review, later dismissed
Need lore writer approval.

2020-11-23 16:41 UTC, mikomyazaki requested changes

2020-11-23 16:41 UTC, mikomyazaki commented on code/modules/organs/subtypes/skrell.dm
> +/obj/item/storage/internal/skrell
Currently this implementation doesn't seem to drop the item when the head (and presumably the tails attached) are destroyed.

I think a better way would be to make the storage be inside their head organ, and have the head organ's destroy handle dropping the item within.

Also, this file `code/modules/organs/subtyles/skrell.dm` is for organs -- This is not an organ.

2020-11-23 16:58 UTC, Geevies commented
gonna reopen this when a skrell maintainer is chosen and they confirm this

2020-12-15 15:26 UTC, Geevies commented
![image](https://user-images.githubusercontent.com/22774890/102235127-b0917180-3efa-11eb-9840-b6f54b126e77.png)

!review

2020-12-22 14:48 UTC, NonQueueingMatt approved these changes

2020-12-28 10:28 UTC, skull132 approved these changes

2020-12-28 12:56 UTC, merged