Garden Biogenerator
Aurorastation/Aurora.3 pull request #10673
Opened 2020-11-27 15:17 UTC by Geevies

* Added a minified biogenerator to the surface garden. It is quite inefficient, but you can move into its tile.

2020-11-27 15:18 UTC, Geevies commented
!review

2020-11-27 17:41 UTC, MarinaGryphon requested changes

2020-11-27 17:41 UTC, MarinaGryphon commented on code/game/machinery/biogenerator.dm
> +/obj/machinery/biogenerator/small
This inherits component_types, meaning it'll *probably* be able to be dismantled and reassembled to get a normal one.

2020-12-05 10:38 UTC, JohnWildkins requested changes
what marina said

good otherwise but unless it's meant to be avant-garde powergamer bait it should probably have fewer and worse components

2020-12-08 17:42 UTC, Geevies commented
> 
> good otherwise but unless it's meant to be avant-garde powergamer bait it should probably have fewer and worse components

the components aren't as effective in the smaller one, so yea

2020-12-09 09:52 UTC, JohnWildkins approved these changes

2020-12-11 16:16 UTC, Alberyk approved these changes

2021-01-16 11:52 UTC, merged