dbcon IsConnected Runtime Fix
Aurorastation/Aurora.3 pull request #10676
Opened 2020-11-27 20:34 UTC by Geevies

2020-11-27 20:34 UTC, Geevies commented
!review

2020-11-27 20:34 UTC, Geevies commented
!bugfix

2020-11-27 20:37 UTC, Arrow768 requested changes

2020-11-27 20:37 UTC, Arrow768 commented on code/modules/admin/verbs/warning.dm
> +	if (!dbcon?.IsConnected())
```suggestion
	if (!establish_db_connection(dbcon))
```

2020-11-27 20:37 UTC, Arrow768 commented on code/modules/mob/abstract/new_player/menu.dm
> +	if(dbcon?.IsConnected())
```suggestion
	if(establish_db_connection(dbcon))
```

2020-11-27 20:37 UTC, Arrow768 commented on code/modules/admin/verbs/warning.dm
>  	establish_db_connection(dbcon)
```suggestion
```

2020-11-28 20:13 UTC, Arrow768 approved these changes

2020-11-28 20:38 UTC, merged