Fair Hades (sic!)
Aurorastation/Aurora.3 pull request #10718
Opened 2020-12-03 17:32 UTC by alsoandanswer

adds hair fades ported from polaris

https://github.com/PolarisSS13/Polaris/pull/7313/files

![image](https://user-images.githubusercontent.com/42310821/101065848-9ee1cd00-35d0-11eb-8655-a37fdcb1f1e5.png)

2020-12-03 18:06 UTC, alsoandanswer commented
!review

2020-12-03 19:00 UTC, alsoandanswer commented
ok wtf its not showing up

2020-12-05 10:46 UTC, JohnWildkins requested changes

2020-12-05 10:46 UTC, JohnWildkins commented on SQL/migrate/V001__Initial_schema.sql
> +  `grad_colour` varchar(7) DEFAULT NULL,
i'm like 97% certain you need a new migration for this

2020-12-28 12:44 UTC, skull132 approved these changes

2020-12-28 13:00 UTC, NonQueueingMatt approved these changes

2020-12-28 13:06 UTC, merged