Goggles Blocking Droppers Fix
Aurorastation/Aurora.3 pull request #10720
Opened 2020-12-03 22:16 UTC by 1Sparky1

Fixes goggles on your forehead blocking people using droppers on your eyes

### IC changelog
- bugfix: "Goggles worn on your forehead no longer block droppers."

2020-12-03 22:21 UTC, 1Sparky1 commented
!review

2020-12-03 22:21 UTC, 1Sparky1 commented
!bugfix

2020-12-04 03:27 UTC, Hockaa approved these changes

2020-12-05 09:17 UTC, Geevies commented on code/modules/reagents/reagent_containers/dropper.dm
> +					if (victim.glasses.body_parts_covered & EYES)
```suggestion
					if (!safe_thing && victim.glasses.body_parts_covered & EYES)
```

2020-12-05 10:51 UTC, JohnWildkins requested changes
do the thing geeves said and it'll be golden

2020-12-05 11:41 UTC, 1Sparky1 commented
It broke again. Time to refork again

2020-12-05 11:41 UTC, closed without merging