Remove Medibot Speech
Aurorastation/Aurora.3 pull request #10730
Opened 2020-12-05 21:17 UTC by 1Sparky1

Removes the medibot speech setting. It's always set to off anyway, and, unless I'm mistaken, essentially a leftover part of the code from lower RP servers. Just doesn't make sense.

### IC changelog
- rscdel: "Removes the medibot speech feature. Nobody needed to know about a medkit's job aspirations."

2020-12-05 21:23 UTC, 1Sparky1 commented
!review

2020-12-05 21:25 UTC, JohnWildkins approved these changes
Personally I think it'd be neat if roboticists/medical could set something for the medbot to say, but eh.

2020-12-05 21:37 UTC, 1Sparky1 commented
> Personally I think it'd be neat if roboticists/medical could set something for the medbot to say, but eh.

I like this idea, and will probably add that.

2020-12-05 21:37 UTC, 1Sparky1 commented
!wip

2020-12-05 23:12 UTC, 1Sparky1 commented
!review

2020-12-06 08:44 UTC, alsoandanswer commented
I'd like the defaults to stay if they just leave it blank.

2020-12-06 12:41 UTC, skull132 requested changes

2020-12-06 12:41 UTC, skull132 commented on code/modules/mob/living/bot/medbot.dm
> +		if(!I)
This needs to be fed through one of the sanitization procs. Otherwise this can be used as a vector for HTML/JS injection and that is very bad juju.

2020-12-07 07:36 UTC, skull132 approved these changes

2020-12-09 09:10 UTC, merged