Partypoggers
Aurorastation/Aurora.3 pull request #10772
Opened 2020-12-09 20:01 UTC by alsoandanswer

The party popper's origin is shrouded in mystery, but a leading theory is after George Washington personally signed the Declaration of Independence, he wanted to celebrate so badly, that he fashioned himself a celebratory device out of a stick of dynamite, a cigarette, and celebration papers (The term for confetti had not been coined yet, because George Washington was too busy personally bullying the nerds at the patent offices.)

The first party popper was originally designed to be smoked as a cigarette to only explode in one's face for a gag, but unfortunate circumstances would cause the user would immediately lose all their teeth. (George Washington personally fixed this problem by owning a pair of replaceable wooden teeth for each use, but his folly was in not realizing that the average American peasant could not afford such luxuries, and his product commercially flopped.)

Celebrate this time honored tradition with this fine piece of Americana (Warning : Not actually made in America.) by using these in office parties, funerals, ship christenings, building openings, and building openings above Native American burial grounds.

![dreamseeker_LHgdA2UMKD](https://user-images.githubusercontent.com/42310821/101680972-69d7ed80-3a9c-11eb-9ae4-ea5f5f10c0fb.png)

2020-12-09 20:02 UTC, alsoandanswer commented
!review

2020-12-12 12:07 UTC, Geevies requested changes

2020-12-12 12:07 UTC, Geevies commented on code/game/objects/effects/decals/Cleanable/misc.dm
> +	if(do_after(60))
shouldn't this have user too

2020-12-12 12:07 UTC, Geevies commented on code/game/objects/items/toys.dm
> +		visible_message(SPAN_NOTICE("You pull on the string, releasing a burst of confetti!"), SPAN_NOTICE("[user] pulls on the string, releasing a burst of confetti!"))
this order of operations is wrong, and it isn't called on user, so the self_message doesn't work

2020-12-15 11:00 UTC, Geevies approved these changes

2020-12-15 21:27 UTC, Alberyk approved these changes

2020-12-16 17:50 UTC, merged