Changeling Combat Tentacle
Aurorastation/Aurora.3 pull request #10784
Opened 2020-12-11 19:45 UTC by Geevies

* Ported Combat Tentacles for Changelings from Paradise station. You can use them to pull items or people towards you.

Ported from https://github.com/ParadiseSS13/Paradise/pull/7519

If you want a detailed write-up of how it works, go check that pull request out.

2020-12-11 19:45 UTC, Geevies commented
!review

2020-12-17 18:37 UTC, Arrow768 requested changes

2020-12-17 18:37 UTC, Arrow768 commented on code/game/gamemodes/changeling/implements/items.dm
> +							return FALSE
I have concerns about that capability, as we removed a lot of the "slap things out of hands" mechanics in the past due to balance issues.

2021-04-19 11:36 UTC, closed without merging

2021-04-19 11:36 UTC, NonQueueingMatt commented
Looks dead.