Desk Toys and Lava Lamps
Aurorastation/Aurora.3 pull request #10804
Opened 2020-12-14 20:04 UTC by alsoandanswer

some useless desk fillers

![dreamseeker_GesrgibNbd](https://user-images.githubusercontent.com/42310821/102129628-a2a40800-3e8a-11eb-8c3a-ff2fa8733a42.png)

2020-12-14 20:08 UTC, alsoandanswer commented
!review

2020-12-14 22:28 UTC, Geevies requested changes

2020-12-14 22:28 UTC, Geevies commented on code/game/objects/items/toys.dm
> +	var/on = 0
```suggestion
	var/on = FALSE
```

2020-12-14 22:28 UTC, Geevies commented on code/game/objects/items/toys.dm
> +		icon_state = "[initial(icon_state)]"
```suggestion
		icon_state = initial(icon_state)
```

2020-12-14 22:28 UTC, Geevies commented on code/game/objects/items/devices/lighting/lamp.dm
> +	overlays.Cut()
```suggestion
	cut_overlays()
```

2020-12-14 22:28 UTC, Geevies commented on code/game/objects/items/devices/lighting/lamp.dm
> +	overlays += I
```suggestion
	add_overlay(I)
```

2020-12-14 22:28 UTC, Geevies commented on code/game/objects/items/devices/lighting/lamp.dm
> +	light_color = COLOR_PURPLE
```suggestion
	light_color = COLOR_PURPLE

```

2020-12-15 01:26 UTC, fernerr reviewed
I personally feel most of these seem rather out of place, the dippy bird especially feeling like a meme. Something like lava lamps I'd rather see reflavored/tweaked to fit in better, like a 'elyran plasma lamp' or something.

2020-12-20 16:04 UTC, Geevies approved these changes

2020-12-28 10:34 UTC, skull132 commented
Agreed with Ferner on this one. Cool idea, but would love some more specific-to-our-setting flavour in it. Also, not enough map integration (read: any) to be relevant.

2021-01-16 11:53 UTC, NonQueueingMatt approved these changes

2021-01-16 11:58 UTC, merged