Custom Record Sighting
Aurorastation/Aurora.3 pull request #10839
Opened 2020-12-20 11:24 UTC by Geevies

* Record programs now display some lines next to the person if they have custom filled records.

![image](https://user-images.githubusercontent.com/22774890/102712013-9c68be00-42c6-11eb-9a02-60a5a4012e0a.png)
![image](https://user-images.githubusercontent.com/22774890/102712015-9e328180-42c6-11eb-8ade-0afe7a0a9b5e.png)
![image](https://user-images.githubusercontent.com/22774890/102712019-9f63ae80-42c6-11eb-8136-0bc749340f2b.png)

2020-12-20 11:24 UTC, Geevies commented
!review

2020-12-21 10:23 UTC, Arrow768 approved these changes

2020-12-22 20:03 UTC, Karolis2011 requested changes

2020-12-22 20:03 UTC, Karolis2011 commented on code/modules/modular_computers/file_system/programs/generic/records.dm
> +			VUEUI_SET_CHECK(data["allrecords"][R.id]["has_notes"], (R.notes != "No notes found.") ? TRUE : FALSE, ., data)
```suggestion
			VUEUI_SET_CHECK(data["allrecords"][R.id]["has_notes"], (R.notes != "No notes found."), ., data)
```

2020-12-22 20:03 UTC, Karolis2011 commented on vueui/src/components/view/records/list.vue
> +      </div>
```suggestion
        <vui-button :params="{ setactive: record.id }" :icon="record.has_notes ? 'align-justify' : null" @click="state.activeview = state.defaultview" push-state>{{ record.id }}: {{ record.name }} ({{ record.rank }})</vui-button>
```
Not sure if this works, but it's better

2021-01-16 11:42 UTC, NonQueueingMatt approved these changes

2021-01-25 19:10 UTC, merged