Antimatter Engine Tweaks
Aurorastation/Aurora.3 pull request #10836
Opened 2020-12-19 22:21 UTC by Geevies

* Cleaned up the antimatter engine's backend.
* Simplified the antimatter engine's power production formula. One unit of injected fuel now equals a megawatt of power produced.
* Fixes antimatter reactor shields sometimes having an invisible sprite.

2020-12-19 22:21 UTC, Geevies commented
!review

2020-12-19 22:49 UTC, Arrow768 requested changes

2020-12-19 22:49 UTC, Arrow768 commented on code/modules/power/antimatter/control.dm
>  	var/core_power = reported_core_efficiency	//Effectively how much fuel we can safely deal with
get rid of core_power and use reported_core_efficiency directly

2020-12-21 10:28 UTC, Arrow768 approved these changes

2020-12-22 14:28 UTC, NonQueueingMatt approved these changes

2020-12-23 03:56 UTC, merged