Hardcore Accounting
Aurorastation/Aurora.3 pull request #10841
Opened 2020-12-20 14:12 UTC by Geevies

* Ported the accounts terminal UI over to VueUI, replaced the accounts terminal with a modular console.

![image](https://user-images.githubusercontent.com/22774890/102715428-06d92880-42de-11eb-801d-d9d3e8971e7e.png)
![image](https://user-images.githubusercontent.com/22774890/102715429-08a2ec00-42de-11eb-9429-d025df306a2f.png)

One issue it has is that clicking on the account numbers doesn't update the UI. When you close and reopen the UI, it works as expected forever.

2020-12-20 14:12 UTC, Geevies commented
!review

2020-12-22 20:18 UTC, Karolis2011 requested changes
Well, this is not great port of said console. DM side is okay for bad port, but VueUI code is awful and bloated.

2020-12-22 20:18 UTC, Karolis2011 commented on code/modules/modular_computers/file_system/programs/command/account_database.dm
>  	data["id_card"] = held_card ? text("[held_card.registered_name], [held_card.assignment]") : "-----"
Just send over id card field with it's title. Or false if non is present
```suggestion
	data["id_card"] = held_card ? text("[held_card.registered_name], [held_card.assignment]") : FALSE
```

2020-12-22 20:18 UTC, Karolis2011 commented on code/modules/modular_computers/file_system/programs/command/account_database.dm
>  			"suspended"=D.suspended ? "SUSPENDED" : "")))
Just send out all data with transactions and don't bother with `detailed_account_view` and switch between witch account is detailed in UI

2020-12-22 20:18 UTC, Karolis2011 commented on code/modules/modular_computers/file_system/programs/command/account_database.dm
>  				var/amount = input("Enter the amount you wish to add", "Silently add funds") as num
Please remove thoes `input` proc calls and replace them with `<input>` fields in UI itself

2020-12-22 20:18 UTC, Karolis2011 commented on vueui/src/components/view/mcomputer/command/accountdb.vue
> +    </div>
Please use `<vui-group-item>` and `<vui-group>`

2020-12-22 20:18 UTC, Karolis2011 commented on vueui/src/components/view/mcomputer/command/accountdb.vue
> +    <div v-if="access_level > 0">
Don't liter DOM with divs use `<template>` where appropriate.

2020-12-22 20:18 UTC, Karolis2011 commented on vueui/src/components/view/mcomputer/command/accountdb.vue
> +        </form>
Use v-model, local variables and `<vui-button>` as final submit

2021-01-04 19:56 UTC, NonQueueingMatt commented
Closed in favour of the other PR.

2021-01-04 19:56 UTC, closed without merging