VueUI 2 Part 2 - Reporting tool
Aurorastation/Aurora.3 pull request #10850
Opened 2020-12-21 16:59 UTC by Karolis2011

This is a tool that makes vueui reports instead of CI server doing same thing. 
![image](https://user-images.githubusercontent.com/11229891/102801877-7fafb180-43be-11eb-9736-9cf936e775fc.png)

2020-12-22 18:46 UTC, Karolis2011 commented
To be clear VueUI 2.0 is currently going to be made up of multiple partially related PRs. This PR is part of VueUI 2.0 a.k.a. #9526

2020-12-25 18:30 UTC, Karolis2011 commented
!review

2021-01-02 12:48 UTC, NonQueueingMatt approved these changes

2021-01-02 12:48 UTC, NonQueueingMatt commented on vueui/tests/manifest.json
> +            "head": 0
Is this meant to be here?

2021-01-04 19:54 UTC, Geevies approved these changes

2021-01-09 17:38 UTC, Arrow768 requested changes
There is no description to explain how to use this tool.

2021-01-09 18:26 UTC, Arrow768 approved these changes

2021-01-09 18:26 UTC, merged