putting down and disposals animation
Aurorastation/Aurora.3 pull request #10873
Opened 2020-12-28 15:21 UTC by alsoandanswer

https://i.imgur.com/22TOxI9.mp4

watch video above for demonstration

2020-12-28 15:21 UTC, alsoandanswer commented
!review

2020-12-28 18:00 UTC, NonQueueingMatt requested changes

2020-12-28 18:00 UTC, NonQueueingMatt commented on code/game/atoms_movable.dm
> +	spawn()
Noooooo. Remove this and have this proc be invoke_async'd.

2021-01-02 12:44 UTC, NonQueueingMatt approved these changes

2021-01-04 20:14 UTC, Geevies approved these changes

2021-01-04 20:21 UTC, merged