Parasite progression adjustment
Aurorastation/Aurora.3 pull request #10889
Opened 2021-01-02 20:26 UTC by Doxxmedearly

Made it so parasites (like k'ois mycosis) have semi-random progress ticking, instead of a flat rate. The time between stages of infection will be more of a ballpark estimate now, instead of an exact, predictable rate.

2021-01-02 21:01 UTC, Doxxmedearly commented
!review

2021-01-02 21:03 UTC, Arrow768 requested changes

2021-01-02 21:03 UTC, Arrow768 commented on code/modules/organs/subtypes/parasite.dm
> +#define INFECTION_SPEED_SLOW 15
I dont see the advantage of using defines here, when two of them are used only once and another one not at all.

2021-01-02 21:14 UTC, Arrow768 approved these changes

2021-01-03 03:12 UTC, Alberyk approved these changes

2021-01-05 21:00 UTC, merged