Skrell Srom Fix
Aurorastation/Aurora.3 pull request #10899
Opened 2021-01-04 18:19 UTC by Geevies

* Skrell no longer enter srom when in cryopods or when on neural suppressor operation tables.

2021-01-04 18:19 UTC, Geevies commented
!bugfix

2021-01-04 18:19 UTC, Geevies commented
!review

2021-01-05 19:53 UTC, NonQueueingMatt requested changes
Not a fan of this solution. We need something more modular for this - this is just begging for more istype(...) snowflake checks to be added in the future.

2021-02-05 22:20 UTC, skull132 commented
> Not a fan of this solution. We need something more modular for this - this is just begging for more istype(...) snowflake checks to be added in the future.

The better solution would be to either add a status effect for shared dream disturbed to mobs that are inside of these things. And have the shared dream entry check for that effect being present.

2021-02-21 00:23 UTC, Arrow768 approved these changes

2021-04-06 22:28 UTC, JohnWildkins approved these changes
something something, works fine but m*intainers must commune on its addition

2021-08-14 12:28 UTC, closed without merging