Wrist Slot (Wear watches with gloves!)
Aurorastation/Aurora.3 pull request #10951
Opened 2021-01-10 22:11 UTC by alsoandanswer

title.

2021-01-10 22:12 UTC, alsoandanswer commented
!review

2021-01-16 11:33 UTC, NonQueueingMatt commented on code/modules/client/preference_setup/loadout/loadout_wrists.dm
> +/datum/gear/wrists
Bracelets should be added to this section too.

2021-01-23 20:54 UTC, skull132 approved these changes

2021-01-25 19:04 UTC, NonQueueingMatt approved these changes
This better not break anything.

2021-02-01 08:42 UTC, NonQueueingMatt requested changes

2021-02-01 08:42 UTC, NonQueueingMatt commented on code/_onclick/hud/hud.dm
> +						if(H.l_ear)		H.l_ear.screen_loc =	hud_data["loc"]
Indent all of these properly below the ifs if you're changing this.

2021-02-01 08:42 UTC, NonQueueingMatt commented on code/modules/mob/living/carbon/human/update_icons.dm
> +		return 1
true/false

2021-02-01 08:42 UTC, NonQueueingMatt commented on code/modules/mob/mob_helpers.dm
> +
```suggestion

```

2021-02-01 10:12 UTC, merged