Ling Space Adaption
Aurorastation/Aurora.3 pull request #10982
Opened 2021-01-13 18:45 UTC by Geevies

* Gave lings the ability to upgrade space adaption for 5 genome points, removing their need to breathe, and nullifying the damage taken from low pressure.

2021-01-13 18:46 UTC, Geevies commented
!review

2021-01-16 11:26 UTC, NonQueueingMatt requested changes

2021-01-16 11:26 UTC, NonQueueingMatt commented on code/game/gamemodes/changeling/implements/powers/resources.dm
> +	var/datum/changeling/changeling = mind.antag_datums[MODE_CHANGELING]
Unsafe usage of mind.

2021-01-16 11:26 UTC, NonQueueingMatt commented on code/game/gamemodes/changeling/implements/powers/resources.dm
> +	var/datum/changeling/changeling = mind.antag_datums[MODE_CHANGELING]
You also have your own proc to use here. `get_antag_datum()`

2021-01-25 19:03 UTC, NonQueueingMatt approved these changes

2021-03-01 14:45 UTC, Doxxmedearly approved these changes

2021-03-01 15:42 UTC, merged