Tesla Grenade + Cavern Dwellers
Aurorastation/Aurora.3 pull request #10991
Opened 2021-01-14 10:29 UTC by Geevies

* Added tesla grenades.
* Cavern Dwellers now throw a bio version of the tesla grenade.

2021-01-14 10:29 UTC, Geevies commented
!review

2021-01-16 11:14 UTC, NonQueueingMatt requested changes

2021-01-16 11:14 UTC, NonQueueingMatt commented on code/modules/mob/living/simple_animal/hostile/retaliate/cavern.dm
> +	butchering_products = list(/obj/item/grenade/tesla/bio = 1)
I think getting a grenade for every mob butchered is a bit too much considering how many dwellers there may be. Also how tf do you get an entire grenade from a dweller?

2021-01-25 19:03 UTC, NonQueueingMatt reviewed
I still think 60% is way too high. Should be like 30 at most.

2021-04-06 22:45 UTC, JohnWildkins reviewed
Seems to work but the grenades are _extremely_ powerful (if somewhat RNG because, tesla). I punched a cavern dweller on runtime and it proceeded to lob tesla grenades at me like a Mark 19 while I sat in perma-crit from the first one nearly instakilling me. I don't like the implication of them being a non-dweller item that could eventually find itself being acquired in any fashion other than by adminbus, because in this state they feel giga-powerful

2021-08-14 12:28 UTC, closed without merging