Add an Option to Recolour the Tajaran Inner Ear
Aurorastation/Aurora.3 pull request #11006
Opened 2021-01-16 23:11 UTC by WickedCybs

This PR adds in two hair gradients (Essentially the same, just had to make another for M'sai due to their longer ears) that act as a way for players to recolour the inner part of the Tajara ear. The ears are tied to the hairstyles, not the body, so this was the best solution.

![image](https://user-images.githubusercontent.com/52309324/104825070-c30e0c00-5814-11eb-8f48-dba256c1a32d.png)

In this picture here it's been coloured white. The usual is a lightened tone to a hair colour you choose, an example will be shown in another photo below.

![image](https://user-images.githubusercontent.com/52309324/104825146-5a735f00-5815-11eb-802f-fc78c71da9dd.png)

2021-01-16 23:11 UTC, WickedCybs commented
!review

2021-01-17 10:53 UTC, alsoandanswer requested changes
Pretty good.

Should probably apply a gradient or something instead of having it be complete white blocks on the ears.

2021-01-17 10:57 UTC, alsoandanswer approved these changes
Actually, disregard that, it's fine.

2021-01-17 14:51 UTC, Chada-1 approved these changes

2021-01-20 13:37 UTC, merged