Revenant Tweaks
Aurorastation/Aurora.3 pull request #11002
Opened 2021-01-16 10:00 UTC by Geevies

* Tau Ceti Basic speakers can now understand 80% of what revenants say.
* Revenants can now universally understand all languages.
* Revenants now spawn between 20 and 30 minutes into the round.

2021-01-16 10:00 UTC, Geevies commented
!review

2021-01-16 11:04 UTC, NonQueueingMatt requested changes

2021-01-16 11:04 UTC, NonQueueingMatt commented on code/modules/mob/living/carbon/human/species/outsider/revenant.dm
> +	universal_understand = TRUE
This isn't the way to do this. This won't work if you spawn a human and then change the species.

2021-01-18 09:05 UTC, NonQueueingMatt approved these changes

2021-01-18 09:25 UTC, skull132 approved these changes
Yessn't.

2021-01-18 18:19 UTC, merged