Adds time restriction to calling an ert
Aurorastation/Aurora.3 pull request #11010
Opened 2021-01-18 06:21 UTC by Alberyk

What it says in the title. Use the same config option used by the shuttle.

2021-01-18 07:26 UTC, fernerr commented on html/changelogs/alberk-erttweak.yml
> +author: ChangeMe
```suggestion
author: Alberyk
```

2021-01-18 07:32 UTC, TheDocOct commented
Feedback thread, please. This seems like a kneejerk reaction to a singluar instance of a very early ERT being called- and in that instance I would argue it was absolutely warranted, and that this PR being a response, isn't. But, that discussion should be in a feedback thread.

2021-01-25 19:02 UTC, NonQueueingMatt approved these changes

2021-01-29 18:07 UTC, Arrow768 requested changes
It is imho preferable to tie this to a different (new) configuration variable.

2021-04-06 22:47 UTC, JohnWildkins requested changes
Agree with arrow, should probably be separately configurable. And feedback needed maybe, as well?

2021-05-12 23:33 UTC, closed without merging