VueUI game board.
Aurorastation/Aurora.3 pull request #11035
Opened 2021-01-20 19:01 UTC by Karolis2011

So this almost completely removes all game board, adds word holo to it and does a neat things.

- [x] Do vueui and dm side
- [ ] Properly handle interactions with board (Now you can't pick it up)
- [ ] Test it

https://user-images.githubusercontent.com/11229891/105221980-8585e780-5b62-11eb-8bb2-e6919c9a0116.mp4

2021-01-20 19:02 UTC, Karolis2011 commented
!review

2021-01-28 09:15 UTC, Geevies requested changes
Tested it a little, found some issues:

- You can't move a piece onto a ghost piece, to undo a mistake or whatever. (It works if you click on the background, but that's a bit obtuse. Maybe pass the click to the background if you click the ghost piece.)
- You can stack an infinite amount of pieces on eachother by clicking on a piece's background with another piece selected.
- Black pieces and their ghosts look exactly the same. If possible, could they be grayed out slightly?

Otherwise, it looks really good! I'd be happy to see this in-game and will absolutely, definitely use this.

2021-01-28 09:15 UTC, Geevies commented on vueui/src/components/view/misc/boardgame.vue
> +  c: "Cheker",
```suggestion
  c: "Checker",
```

2021-01-28 18:25 UTC, Geevies commented
Updated my review with new testing info.

2021-01-29 14:14 UTC, Geevies approved these changes
Tried my best to break it and couldn't. Looks good.

2021-01-29 14:23 UTC, skull132 submitted a review, later dismissed

2021-01-29 14:23 UTC, skull132 commented on code/modules/games/boardgame.dm
> +	. = data = data || list()
```suggestion
	data = data || list()
	. = data
```

The operator precedent on that is painful to read otherwise.

2021-01-29 14:23 UTC, skull132 commented on code/modules/games/boardgame.dm
> +		return
```suggestion
		return FALSE
```

2021-02-02 15:01 UTC, Arrow768 approved these changes

2021-02-15 11:21 UTC, NonQueueingMatt approved these changes

2021-02-15 11:23 UTC, merged