Custom rolls
Aurorastation/Aurora.3 pull request #11059
Opened 2021-01-24 14:17 UTC by 1Sparky1

Allows the creation of custom rolls (and burgers) in the same fashion as sandwiches.

### IC changelog
- rscadd: "Added custom rolls and burgers. Made in the same way as custom sandwiches, but with a bun or burger respectively. Go wild!"

2021-01-24 14:44 UTC, 1Sparky1 commented
!review

2021-01-25 18:55 UTC, NonQueueingMatt requested changes
There is an excessive amount of copypaste with these two items. There has to be a way to use inheritance to not have a mess of repeated code.

2021-02-05 22:04 UTC, skull132 approved these changes

2021-02-05 22:06 UTC, NonQueueingMatt approved these changes

2021-02-06 14:57 UTC, merged