Belt colors
Aurorastation/Aurora.3 pull request #11050
Opened 2021-01-23 18:54 UTC by alsoandanswer

- rscadd: "Adds colorable belts."
  - tweak: "Fannypacks are now recolorable."
  - rscadd: "Belts now have a dedicated loadout section.

2021-01-23 18:58 UTC, alsoandanswer commented
!review

2021-01-28 17:46 UTC, NonQueueingMatt requested changes

2021-01-28 17:46 UTC, NonQueueingMatt commented on code/game/objects/items/weapons/storage/belt.dm
> +	to_chat(usr, "You change \the [src] to be [src.flipped ? "behind" : "in front of"] you.")
```suggestion
	to_chat(usr, SPAN_NOTICE("You change \the [src] to be [src.flipped ? "behind" : "in front of"] you."))
```

2021-01-28 17:46 UTC, NonQueueingMatt commented on code/game/objects/items/weapons/storage/belt.dm
> +			return
What you want here is just:
```
	if(use_check_and_message(user, self ? USE_ALLOW_NON_ADJACENT))
			return
```

2021-02-03 01:32 UTC, Alberyk approved these changes

2021-02-07 14:39 UTC, skull132 approved these changes

2021-02-07 14:45 UTC, merged