Automatic CPR
Aurorastation/Aurora.3 pull request #11069
Opened 2021-01-25 15:19 UTC by 1Sparky1

Makes CPR a self-repeating process. Suggested [here](https://forums.aurorastation.org/topic/15338-make-cpr-an-automatic-process/?tab=comments#comment-143744). It also now required two hands, because CPR isn't something you can do while sipping coffee.

### IC changelog
- tweak: "CPR is now automatic, but required both hands to be empty."

2021-01-25 15:24 UTC, 1Sparky1 commented
!review

2021-01-25 18:53 UTC, NonQueueingMatt requested changes

2021-01-25 18:53 UTC, NonQueueingMatt commented on code/modules/mob/living/carbon/human/human_attackhand.dm
> +					to_chat(H, SPAN_NOTICE("You cannot perform CPR with anything in your hands."))
These checks are redundant. Just don't send a "performing CPR" message here and only send it in the cpr() proc after the checks are completed.

2021-01-25 18:53 UTC, NonQueueingMatt commented on code/modules/mob/living/carbon/human/human_attackhand.dm
> +		cpr = 0
If this is a boolean, it should be TRUE/FALSE.

2021-01-26 00:15 UTC, Chada-1 approved these changes

2021-01-29 10:50 UTC, NonQueueingMatt approved these changes

2021-01-29 10:56 UTC, merged