Cult Rune Op Table
Aurorastation/Aurora.3 pull request #11087
Opened 2021-01-28 22:40 UTC by Geevies

* You can now do surgery on cult runes as if they were operation tables.

2021-01-28 22:40 UTC, Geevies commented
!review

2021-01-29 00:27 UTC, alsoandanswer approved these changes

2021-01-29 00:28 UTC, alsoandanswer commented
You sure there aren't any children of /obj/effect/rune that this can also happen as well?

2021-01-29 10:48 UTC, NonQueueingMatt requested changes
This shouldn't be "any rune". It should be a specific building like the altar.

2021-02-19 12:09 UTC, closed without merging