Gives Dionae a speedbuff
Aurorastation/Aurora.3 pull request #11093
Opened 2021-01-29 21:44 UTC by Yonnimer

What it says in the title. This changes dionae speed from 7 to 5. In full light, this will make them about the speed of a xion, if not a little slower. Given they're usually not in full light, however, they should be closer to a G1's speed as evident by the testing done.

2021-01-29 21:44 UTC, Yonnimer commented
!review

2021-01-29 22:47 UTC, Geevies commented on html/changelogs/yonnimer-speed.yml
> +  - rtweak: "Gives dionae a speedbuff, changing their slowdown from 7 to 5.
```suggestion
  - tweak: "Gives dionae a speedbuff, changing their slowdown from 7 to 5."
```

2021-01-29 22:49 UTC, Yonnimer commented on html/changelogs/yonnimer-speed.yml
> +  - rtweak: "Gives dionae a speedbuff, changing their slowdown from 7 to 5.
fixed

2021-01-29 23:10 UTC, Geevies requested changes

2021-01-29 23:10 UTC, Geevies commented on html/changelogs/yonnimer-speed.yml
> +  - tweak: "Gives dionae a speedbuff, changing their slowdown from 7 to 5.
```suggestion
  - tweak: "Gives dionae a speedbuff, changing their slowdown from 7 to 5."
```

2021-01-29 23:52 UTC, Chada-1 approved these changes

2021-01-30 02:21 UTC, Arrow768 commented
Will be discussed between the maintainers.

2021-02-16 19:42 UTC, Arrow768 commented
Closed as not wanted after discussion with the maintainers.
The reasoning has been explained to the diona lore writers in the staff discord.

2021-02-16 19:42 UTC, closed without merging