More Revenant Tweaks
Aurorastation/Aurora.3 pull request #11146
Opened 2021-02-06 11:24 UTC by Geevies

* Revenants now get a martial art that allows them to bash people away on a three hit combo. This replaces their ability to use guns.
* Revenants are no longer able to operate welderbombs.
* Revenants now absorb 20% of laser fire instead of 30%.
* Moved Revenant spawnpoints into the station.
* Tweaked the rift gameplay, should be easier for the station to stop the revenants now.

2021-02-06 11:24 UTC, Geevies commented
!review

2021-02-06 11:42 UTC, NonQueueingMatt requested changes

2021-02-06 11:42 UTC, NonQueueingMatt commented on code/game/objects/items/weapons/tools.dm
> +			return
This feels hardcoded and icky. I'm not a fan of it. Maybe tie it to advancedtooluser or add a new proc that controls these things.

2021-02-10 14:40 UTC, NonQueueingMatt approved these changes

2021-02-11 20:17 UTC, Doxxmedearly approved these changes

2021-02-11 21:27 UTC, merged