IAC Labcoat
Aurorastation/Aurora.3 pull request #11166
Opened 2021-02-10 01:21 UTC by WilliamMurdoch

Adds a labcoat in the IAC colors.

2021-02-10 01:26 UTC, WilliamMurdoch commented
!review

2021-02-15 11:06 UTC, NonQueueingMatt requested changes

2021-02-15 11:06 UTC, NonQueueingMatt commented on code/modules/client/preference_setup/loadout/loadout_suit.dm
> +	description = "It's a standard medical labcoat designed to be worn by the Instellar Aid Corps."
```suggestion
	description = "It's a standard medical labcoat designed to be worn by the Interstellar Aid Corps."
```

2021-02-15 11:06 UTC, NonQueueingMatt commented on code/modules/clothing/suits/labcoat.dm
> +	armor = list(melee = 0, bullet = 0, laser = 0,energy = 0, bomb = 0, bio = 60, rad = 0)
Update this branch and use the armor defines.

2021-02-15 12:41 UTC, WilliamMurdoch commented
Alright, I messed up when I was pushing the changes. I'm going to close this redo this in a way that won't mess up.

2021-02-15 12:41 UTC, closed without merging