Allows you to tear out vaurca mandibles
Aurorastation/Aurora.3 pull request #11161
Opened 2021-02-09 15:07 UTC by LadyFowls

Allows you to tear out a new organ, vaurca mandibles, preventing them from biting you

2021-02-09 15:09 UTC, LadyFowls commented
!review

2021-02-15 11:09 UTC, NonQueueingMatt requested changes

2021-02-15 11:09 UTC, NonQueueingMatt commented on code/game/objects/items/weapons/vaurca_items.dm
> +
Rogue space.

2021-02-15 11:09 UTC, NonQueueingMatt commented on code/modules/mob/mob_grab_specials.dm
> +
Rogue space.

2021-02-15 11:09 UTC, NonQueueingMatt commented on code/modules/mob/mob_grab_specials.dm
> +			if(1)
Magic numbers, should probably be defines.

2021-02-15 11:09 UTC, NonQueueingMatt commented on code/modules/mob/mob_grab_specials.dm
> +					target.apply_damage(75, PAIN)
You can directly add the pain to the head organ here.

2021-02-15 11:09 UTC, NonQueueingMatt commented on code/modules/mob/mob_grab_specials.dm
> +					target.apply_damage(15, PAIN)
ditto

2021-02-15 11:09 UTC, NonQueueingMatt commented on code/modules/mob/mob_grab_specials.dm
> +					target.apply_damage(75, PAIN)
ditto

2021-02-15 11:09 UTC, NonQueueingMatt commented on code/modules/organs/subtypes/vaurca.dm
> +	edge = 1
booleans

2021-02-15 11:09 UTC, NonQueueingMatt commented on code/modules/organs/subtypes/vaurca.dm
> +	hitsound = 'sound/weapons/bladeslice.ogg'
this is a subtype, you don't need most of these variables to be re-defined

2021-04-18 10:44 UTC, NonQueueingMatt commented
Inactive author.

2021-04-18 10:44 UTC, closed without merging