Shooting Target Refactor
Aurorastation/Aurora.3 pull request #11186
Opened 2021-02-14 13:23 UTC by Geevies

* Refactored shooting targets, they should now work a little more sanely.
* You can now construct shooting targets and target stakes out of steel in the Misc construction category.
* You can now deconstruct target stakes with a wrench.

Ported primarily from https://github.com/Baystation12/Baystation12/pull/22208

2021-02-14 13:24 UTC, Geevies commented
!review

2021-02-15 11:04 UTC, NonQueueingMatt requested changes

2021-02-15 11:04 UTC, NonQueueingMatt commented on code/game/objects/items/shooting_range.dm
> +	var/decaltype = istype(Proj, /obj/item/projectile/bullet) ? DECAL_BULLET : DECAL_SCORCH
Use damage flags here. Check if the projectile has `damage_flags & DAM_BULLET`

2021-02-16 18:36 UTC, NonQueueingMatt approved these changes

2021-04-06 22:56 UTC, JohnWildkins approved these changes

2021-04-07 02:13 UTC, merged