Laser Tag Gear
Aurorastation/Aurora.3 pull request #11193
Opened 2021-02-14 18:03 UTC by Geevies

* Added helmets to the laser tag gear loadout.
* You can now alt-click laser tag armour to be able to set how many hits it will take before flooring you.
* You can now use a multitool on laser tag gear to change which colour it is and works against.
* Lowered the laser tag gun recharge rate to 4 seconds per shot, down from 8 seconds per shot.

2021-02-14 18:04 UTC, Geevies commented
!review

2021-02-15 11:00 UTC, NonQueueingMatt approved these changes

2021-02-15 11:00 UTC, NonQueueingMatt commented on code/modules/clothing/sets/laser_tag.dm
> +			) // still somewhat sturdy, but ultimately not very
this should not be blocking knives, also, newline after the list declaration

2021-02-15 11:00 UTC, NonQueueingMatt commented on code/modules/clothing/sets/laser_tag.dm
> +	armor = list(melee = ARMOR_MELEE_KNIVES,
ditto

2021-02-15 11:00 UTC, NonQueueingMatt requested changes
that was not meant to be an approval

2021-02-17 15:18 UTC, Alberyk approved these changes

2021-03-01 12:45 UTC, NonQueueingMatt approved these changes

2021-03-07 16:14 UTC, merged