Wired Rechargers
Aurorastation/Aurora.3 pull request #11190
Opened 2021-02-14 15:42 UTC by Geevies

* Mapped in three wired rechargers to the engineering sub-level storage. They work off cables instead of APCs.

2021-02-14 15:42 UTC, Geevies commented
!review

2021-02-14 16:18 UTC, Arrow768 requested changes

2021-02-14 16:18 UTC, Arrow768 commented on code/modules/power/wired_recharger.dm
> +	var/charging_efficiency = 1.3 // Entropy. The charge put into the cell is multiplied by this
This value must be smaller than 1

2021-02-15 11:01 UTC, NonQueueingMatt commented
Not really a fan of more chargers being added around honestly but I guess we already have some in the library.

2021-02-15 11:01 UTC, NonQueueingMatt approved these changes

2021-02-15 11:02 UTC, NonQueueingMatt requested changes
Hold on. Most of this code is just copypasted from the charger item. This should definitely be a subtype.

2021-04-18 10:44 UTC, NonQueueingMatt commented
Inactive.

2021-04-18 10:44 UTC, closed without merging