Character Creation Tweak
Aurorastation/Aurora.3 pull request #11207
Opened 2021-02-16 16:19 UTC by Geevies

2021-02-16 16:20 UTC, Geevies commented
!review

2021-02-21 17:23 UTC, Doxxmedearly approved these changes

2021-02-21 18:56 UTC, Alberyk approved these changes

2021-02-21 21:12 UTC, Arrow768 requested changes
Merge master and update the version of the SQL migration

2021-02-24 15:01 UTC, NonQueueingMatt commented
As I said, opposed to match gender being a thing. It should just change with the sex.

2021-03-09 18:06 UTC, Arrow768 requested changes
As discussed on discord:
The appearance editor needs to be updated to receive the pronoun functionality aswell.

2021-03-10 12:18 UTC, Geevies commented
last commit removed the need to send the proc a location or a state, as it'll attach to the vueui_module and use interactive state, otherwise it runtimes because the location it gets assigned to cannot send the vueui data.

it also changes some references from "gender" to "sex", as it'll probably be an issue down the road and it's easier to nip it in the bud right now.

2021-03-10 21:28 UTC, Arrow768 requested changes

2021-03-10 21:28 UTC, Arrow768 commented on code/modules/nano/modules/human_appearance.dm
>  	var/list/valid_languages = list()
Style inconsistency.

2021-03-10 21:28 UTC, Arrow768 commented on code/modules/nano/modules/human_appearance.dm
> +		if(LAZYLEN(valid_pronouns))
Invalid usage of LAZYLEN here

2021-03-10 21:28 UTC, Arrow768 commented on code/game/objects/structures/mirror.dm
> +		var/datum/vueui_module/appearance_changer/AC = ui_users[user]
This looks like oldcode.

Please use the "current" way of interacting with UIs (`ui_interact` proc with `SSvueui-get_open_ui()`)

2021-03-10 21:28 UTC, Arrow768 commented on code/game/objects/structures/mirror.dm
> +		var/datum/vueui_module/appearance_changer/AC = ui_users[user]
Same here

2021-03-10 21:28 UTC, Arrow768 commented on code/game/objects/structures/mirror.dm
> +		var/datum/vueui_module/appearance_changer/AC = ui_users[user]
Same here

2021-03-10 21:28 UTC, Arrow768 commented on code/game/objects/structures/mirror.dm
> +		var/datum/vueui_module/appearance_changer/AC = ui_users[user]
Same here

2021-03-10 21:28 UTC, Arrow768 commented on code/modules/mob/living/carbon/human/appearance.dm
> +/mob/living/carbon/human/proc/change_appearance(var/flags = APPEARANCE_ALL_HAIR, var/mob/user = src, var/check_species_whitelist = 1, var/list/species_whitelist = list(), var/list/species_blacklist =
```suggestion
/mob/living/carbon/human/proc/change_appearance(var/flags = APPEARANCE_ALL_HAIR, var/mob/user = src, var/check_species_whitelist = TRUE, var/list/species_whitelist = list(), var/list/species_blacklist = list())
```

2021-03-10 22:16 UTC, Arrow768 approved these changes

2021-03-12 21:52 UTC, merged