Vendor Throwing
Aurorastation/Aurora.3 pull request #11244
Opened 2021-02-19 19:06 UTC by Geevies

* Tweaked how vending machines act when they throw things at you. Should be a bit more spicy now.

Ported from https://github.com/tgstation/tgstation/pull/27361

2021-02-19 19:07 UTC, Geevies commented
!review

2021-03-01 12:42 UTC, NonQueueingMatt requested changes

2021-03-01 12:42 UTC, NonQueueingMatt commented on code/game/machinery/vending.dm
> +		FL.toggle()
This should be a proc on the object and not a type check.

2021-03-07 16:14 UTC, Arrow768 approved these changes

2021-03-10 12:38 UTC, NonQueueingMatt approved these changes

2021-03-10 13:52 UTC, merged