VueUI part 3 (1?) - The alias of sendToTopic
Aurorastation/Aurora.3 pull request #11259
Opened 2021-02-20 18:42 UTC by Karolis2011

This is half of #10825

Aka ATCs - a short cut to calling sendToTopic without importing utils.

2021-02-20 18:44 UTC, Karolis2011 commented
!review

2021-02-22 22:02 UTC, Arrow768 requested changes

2021-02-22 22:02 UTC, Arrow768 commented on vueui/src/components/vui/item.vue
> +    <!-- DEPRICATED PLEASE USE VUI-GROUP AND VUI-GROUP-ITEM -->
```suggestion
    <!-- DEPRECATED PLEASE USE VUI-GROUP AND VUI-GROUP-ITEM -->
```

2021-02-23 07:44 UTC, Geevies submitted a review, later dismissed
I don't know much about backend code, so I'm reviewing it on merit of having downloaded the branch and testing it on my private server.

- When interacting with the canister, I tried to increase the pressure output, the number jumped up before going back down. It only stayed when I maxed it out.
- I can't exit UIs with the big cross in the top right.
- Various buttons on modular computers at random just don't work.

I would suggest trying to fix these and then hosting your own private server to see if there's anything I missed.

2021-04-07 03:07 UTC, JohnWildkins approved these changes
I was only able to test it somewhat briefly, but it seems to work fine. Wasn't able to induce any out-of-the-ordinary behavior in VUIs.

2021-04-21 19:15 UTC, NonQueueingMatt approved these changes

2021-04-21 19:17 UTC, merged