Ported 3 World Server hair gradients
Aurorastation/Aurora.3 pull request #11308
Opened 2021-02-25 16:41 UTC by listerla

Specifically, the reflected and wavy gradients.

Reflected (Inverse): (Hair 000000, Gradient FF0000, Style Long Hair, Very Long)
![image](https://user-images.githubusercontent.com/57296132/109185686-3e40d700-775e-11eb-8617-b970ec60a50e.png)

Wavy: 
![image](https://user-images.githubusercontent.com/57296132/109185718-4436b800-775e-11eb-82bc-2d43e915840e.png)

Reflected: 
![image](https://user-images.githubusercontent.com/57296132/109185749-4bf65c80-775e-11eb-8f9f-5af4fe8ae2a0.png)

2021-02-25 16:41 UTC, listerla commented
I have no idea why the Reflected sprite has those pixels like that at the bottom. The sprite is uniform white below the gradient.

2021-02-25 16:44 UTC, listerla commented
!review

2021-03-02 08:53 UTC, skull132 approved these changes

2021-03-03 23:52 UTC, carpevenenum commented
The reflected and inverse reflected gradients imply an attempt at custom shading. I wonder if a flag is needed to make them be ignored by the changes in #11333.

2021-03-17 23:46 UTC, Arrow768 requested changes

2021-03-17 23:46 UTC, Arrow768 commented on html/changelogs/listerla-gradients.yml
> +  - imageadd: "Ported 'Reflected', 'Reflected (Inverse), and 'Wavy' hair gradients from World Server."
```suggestion
  - imageadd: "Ported \"Reflected\", \"Reflected (Inverse)\", and \"Wavy\" hair gradients from World Server."
```
The changelog system fails, most likely due to issues with the quotes

2021-04-01 13:22 UTC, closed without merging