Ports directional floodlights from Baystation 12.
Aurorastation/Aurora.3 pull request #11307
Opened 2021-02-25 16:01 UTC by listerla

Given floodlights are now directional, a directional sprite would be appropriate. I'm aware simply porting sprites is looked down upon but it was annoying having them be non-directional but the light was.

2021-02-25 16:44 UTC, listerla commented
!review

2021-03-01 22:22 UTC, Arrow768 approved these changes

2021-03-02 09:10 UTC, skull132 approved these changes

2021-03-02 09:11 UTC, skull132 requested changes

2021-03-02 09:11 UTC, skull132 commented on html/changelogs/listerla-bay12_floodlight_port.yml
> +Useful for PR changelogs that won't get used again.
```suggestion
```

2021-03-02 09:12 UTC, skull132 approved these changes

2021-03-02 10:36 UTC, merged