Adds Dominian consular items to the loadout.
Aurorastation/Aurora.3 pull request #11314
Opened 2021-02-26 01:47 UTC by TheStryker

Honey, it's 4PM, time for your Dominia PR!
![SASH](https://user-images.githubusercontent.com/19821403/109243229-8a038700-7817-11eb-8a53-d5efe759d372.PNG)
![dominian greatcoat](https://user-images.githubusercontent.com/19821403/109243232-8cfe7780-7817-11eb-8931-91395f31e91d.PNG)
![dominian uniforms](https://user-images.githubusercontent.com/19821403/109243241-8ff96800-7817-11eb-9f7f-51f79289a02f.PNG)
![by the holy tribune!](https://user-images.githubusercontent.com/19821403/109243243-9091fe80-7817-11eb-9d22-04d3dcbed8a8.PNG)

Sprites done by DasFox, flavor texts by Schwann.
This PR adds the following items:
- Dominian Great House sashes
Consular Restricted:
- Dominian Consular Greatcoat
- Dominian Consular Uniform (skirt and pants)
- Dominian Consular Hat
- Consular Tribunalist Robe
- Consular Tribunalist Beret
- Consular Tribunalist Cloak

2021-02-26 02:02 UTC, TheStryker commented
!review
I'm not sure what the issue with exodus is.

2021-03-01 12:33 UTC, NonQueueingMatt requested changes

2021-03-01 12:33 UTC, NonQueueingMatt commented on code/modules/client/preference_setup/loadout/loadout_accessories.dm
> +	path = "/obj/item/clothing/accessory/dominia/sash"
```suggestion
	path = /obj/item/clothing/accessory/dominia/sash
```

2021-03-01 22:19 UTC, Arrow768 approved these changes

2021-04-05 12:43 UTC, Geevies approved these changes

2021-04-07 17:20 UTC, JohnWildkins approved these changes
Seems to work fine. I wish the items had in-hands ~~but apparently no factional loadout items do, so I guess it's fine~~

2021-04-10 16:33 UTC, merged