Zeng Hu Augments: 'I Never Asked for This' Edition
Aurorastation/Aurora.3 pull request #11360
Opened 2021-03-03 04:30 UTC by Alberyk

This pr adds some Zeng Hu exclusive augments.

Memory Inhibitor: A Zeng Hu implant that allows one to have control over their memories, allowing you to set a timer and remove any memories developed within it. A RP tool, no mechanical use.

Emotional Manipulator: A Zeng Hu brain implant to manipulate the brain’s chemicals to induce a calming or happy feeling. A RP tool, no mechanical use.

 Vision Enhanced Retinas: Allows the user to zoom at short distances as long they do not move. Always emits lights.

Ocular Installed Sightlights: Designed to assist medical personnel in darker areas or places experiencing periodic power issues, Sightlights will allow one to be able to use their eyes as a flashlight. 

 Zeng-Hu Veterancy Plate:  A clear sign of Zeng-Hu’s best, this plate bearing the company’s symbol is installed on those who prove themselves in the hyper-competitive environment.  Does nothing but look cool.

Waiting for sprites by kyres1.

2021-03-03 11:12 UTC, 1Sparky1 requested changes

2021-03-03 11:12 UTC, 1Sparky1 commented on code/__defines/mobs.dm
> +#defineBP_AUG_SIGHTLIGHTS   "ocular installed sightlights"
```suggestion
#define BP_AUG_SIGHTLIGHTS   "ocular installed sightlights"
```
Missing a space here.

2021-03-03 11:12 UTC, 1Sparky1 commented on code/modules/client/preference_setup/loadout/loadout_augments.dm
> +	display_name = "psionic receiver"
```suggestion
	display_name = "memory inhibitor"
```
wrong name here.

2021-03-16 20:30 UTC, Geevies approved these changes

2021-03-18 11:16 UTC, niennab commented
Just to log it here, I wanted to request IPCs getting the:
Vision Enhanced Retinas, Ocular Installed Sightlights and Zeng-Hu Veterancy Plate (so long as it works in testing)

2021-03-19 21:18 UTC, Arrow768 approved these changes

2021-03-23 12:49 UTC, NonQueueingMatt commented
Bot looks busted here, so I'm just gonna do the following.

2021-03-23 12:49 UTC, NonQueueingMatt approved these changes

2021-03-23 12:51 UTC, merged