Monkey Clothes
Aurorastation/Aurora.3 pull request #11415
Opened 2021-03-10 19:19 UTC by Geevies

* Held monkeys now wear the fancy uniform if they're wearing the fancy uniform.

2021-03-10 19:19 UTC, Geevies commented
!review

2021-03-15 09:25 UTC, NonQueueingMatt requested changes

2021-03-15 09:25 UTC, NonQueueingMatt commented on code/modules/mob/holder.dm
> +		item_state = "monkey_fancy"
This is horribly hardcoded. The better thing to do would be to make a system that decides item_state based on the item the monkey is wearing and only changes the state if it exists.

2021-03-18 11:39 UTC, NonQueueingMatt approved these changes

2021-03-19 19:44 UTC, Alberyk approved these changes

2021-03-19 21:06 UTC, merged