Gustatory Augment
Aurorastation/Aurora.3 pull request #11434
Opened 2021-03-14 12:38 UTC by Geevies

* Added a gustatoral centre augment for IPCs. This will allow them to taste food in their active hand as if they've eaten it. Using it with no food in their hand will let them change how sensitive it is.
* Shell IPCs get an additional gustatoral centre augment variation that goes in their tongue, allowing them to taste food without their finger.

2021-03-14 12:38 UTC, Geevies commented
!review

2021-03-23 12:49 UTC, NonQueueingMatt requested changes

2021-03-23 12:49 UTC, NonQueueingMatt commented on code/modules/organs/subtypes/augment.dm
> +	name = "gustatoral centre"
I've checked the proper spelling for this and it actually seems to be gustatorial: https://www.yourdictionary.com/gustatorial

2021-03-28 11:30 UTC, NonQueueingMatt approved these changes

2021-04-02 22:05 UTC, Doxxmedearly approved these changes

2021-04-03 04:19 UTC, merged