Some Augments
Aurorastation/Aurora.3 pull request #11492
Opened 2021-03-20 18:32 UTC by Geevies

* Added cochlear implants to the augment menu, they function the same as hearing aids.
* Added a retractable lighter to the augment menu, they function like the combitool augment, but for a lighter.
* Added synthetic vocal cords to the augment menu. They make you mute if removed, but remove muteness if implanted.

2021-03-20 18:33 UTC, Geevies commented
!review

2021-03-25 22:01 UTC, Alberyk approved these changes

2021-03-30 10:47 UTC, NonQueueingMatt requested changes

2021-04-07 17:32 UTC, JohnWildkins approved these changes

2021-04-10 17:11 UTC, merged