Sorry CI
Aurorastation/Aurora.3 pull request #11522
Opened 2021-03-22 14:43 UTC by Geevies

i'm smart i promise

2021-03-22 14:43 UTC, Geevies commented
!bugfix

2021-03-22 14:44 UTC, Geevies commented
!review

2021-03-22 14:55 UTC, NonQueueingMatt requested changes

2021-03-22 14:55 UTC, NonQueueingMatt commented on code/modules/mob/living/carbon/human/inventory.dm
> +	if(hud_used) // geeves broke the CI on 22/03/2021
```suggestion
	if(hud_used)
```
no spraypaint

2021-03-22 17:22 UTC, MarinaGryphon requested changes

2021-03-22 17:22 UTC, MarinaGryphon commented on code/modules/mob/living/carbon/human/inventory.dm
> +	if(hud_used) // geeves broke the CI on 22/03/2021
```suggestion
```

2021-03-22 17:22 UTC, MarinaGryphon commented on code/modules/mob/living/carbon/human/inventory.dm
> +		hud_used.hidden_inventory_update()
```suggestion
	hud_used?.hidden_inventory_update()
```
This is easily onelined.

2021-03-22 19:55 UTC, Geevies commented on code/modules/mob/living/carbon/human/inventory.dm
> +	if(hud_used) // geeves broke the CI on 22/03/2021
why not

2021-03-22 19:55 UTC, Geevies commented on code/modules/mob/living/carbon/human/inventory.dm
> +		hud_used.hidden_inventory_update()
that's disgusting

2021-03-23 12:29 UTC, NonQueueingMatt approved these changes

2021-03-23 12:42 UTC, merged