Slide Projectors
Aurorastation/Aurora.3 pull request #11551
Opened 2021-03-26 12:29 UTC by Geevies

* Added slide projectors, capable of projecting an image of any small item onto any turf.

Port of https://github.com/Baystation12/Baystation12/pull/30380 which is a port of https://github.com/NebulaSS13/Nebula/pull/322

2021-03-26 12:29 UTC, Geevies commented
!review

2021-03-28 11:06 UTC, NonQueueingMatt requested changes

2021-03-28 11:06 UTC, NonQueueingMatt commented on code/game/objects/items/devices/slide_projector.dm
> +		project_at(get_turf(projection))
Check the original Baystation PR as it has some good concerns regarding this, e.g setting a slide to null not actually removing or deleting it.

2021-04-07 18:45 UTC, JohnWildkins approved these changes

2021-04-19 12:07 UTC, fernerr approved these changes

2021-04-19 12:12 UTC, merged