Adds preference for seeing LOOC from ghosts
Aurorastation/Aurora.3 pull request #11577
Opened 2021-03-30 22:33 UTC by Doxxmedearly

Adds a toggle for players who do not want to see LOOC messages from observers/ghosts. Added in the preferences tab as well as character setup.

2021-03-30 22:33 UTC, Doxxmedearly commented
!review

2021-03-30 22:59 UTC, Geevies approved these changes

2021-04-05 20:14 UTC, Arrow768 requested changes
You are not accounting for LOOC messages sent by holders that are observing.

2021-04-07 18:59 UTC, JohnWildkins approved these changes

2021-04-10 15:36 UTC, Doxxmedearly commented
Regular LOOC was not accounting for admins, either.
Added admin LOOC as discussed since tying to holders is kinda sketch.

2021-04-12 01:41 UTC, Alberyk approved these changes

2021-04-12 07:19 UTC, Arrow768 commented on code/modules/admin/admin_verbs.dm
> +	msg = process_chat_markup(msg, list("*"))
here is the second time you are calling it

2021-04-13 10:10 UTC, Arrow768 approved these changes

2021-04-14 09:55 UTC, merged