Adds the ringbell and maps it into the boxing simulation
Aurorastation/Aurora.3 pull request #11644
Opened 2021-04-11 12:45 UTC by Casper3667

Ports the ring bell from bay: https://github.com/Baystation12/Baystation12/pull/19995

2021-04-11 12:45 UTC, Casper3667 commented
!review

2021-04-11 13:17 UTC, Geevies requested changes

2021-04-11 13:17 UTC, Geevies commented on code/game/objects/items/toys.dm
> +	icon_state= "ringbell"
```suggestion
	icon_state = "ringbell"
```

2021-04-11 13:17 UTC, Geevies commented on code/game/objects/items/toys.dm
> +	desc = "A bell used to signal the beginning and end of various ring sports."
i would put a desc_info here explaining what the different intents signal

2021-04-11 13:17 UTC, Geevies commented on code/game/objects/items/toys.dm
> +	anchored = 1
```suggestion
	anchored = TRUE
```

2021-04-11 13:17 UTC, Geevies commented on code/game/objects/items/toys.dm
> +/obj/item/toy/ringbell/attack_hand(mob/user as mob)
```suggestion
/obj/item/toy/ringbell/attack_hand(mob/user)
```

2021-04-11 13:17 UTC, Geevies commented on code/game/objects/items/toys.dm
> +	if (user.a_intent == I_HELP)
this can be made into a switch statement

2021-04-11 13:17 UTC, Geevies commented on code/game/objects/items/toys.dm
> +		user.visible_message("<span class='notice'>[user] rings \the [src], signalling the beginning of the contest.</span>")
honestly, add FONT_LARGE to this too, and convert the straight HTML code to SPAN_NOTICE, same for the others

2021-04-11 13:17 UTC, Geevies commented on code/game/objects/items/toys.dm
> +		user.visible_message("<span class='warning'>[user] rings \the [src] repeatedly, signalling a disqualification!</span>")
SPAN_WARNING

2021-04-11 17:02 UTC, Geevies requested changes

2021-04-11 17:02 UTC, Geevies commented on code/game/objects/items/toys.dm
> +			user.visible_message(FONT_LARGE (SPAN_NOTICE("[user] rings \the [src], signalling the beginning of the contest.")))
```suggestion
			user.visible_message(FONT_LARGE(SPAN_NOTICE("[user] rings \the [src], signalling the beginning of the contest.")))
```

2021-04-11 17:02 UTC, Geevies commented on code/game/objects/items/toys.dm
> +			user.visible_message(FONT_LARGE (SPAN_NOTICE("[user] rings \the [src] three times, signalling the end of the contest!")))
```suggestion
			user.visible_message(FONT_LARGE(SPAN_NOTICE("[user] rings \the [src] three times, signalling the end of the contest!")))
```

2021-04-11 17:02 UTC, Geevies commented on code/game/objects/items/toys.dm
> +			user.visible_message(FONT_LARGE (SPAN_WARNING("[user] rings \the [src] repeatedly, signalling a disqualification!")))
```suggestion
			user.visible_message(FONT_LARGE(SPAN_WARNING("[user] rings \the [src] repeatedly, signalling a disqualification!")))
```

2021-04-11 17:02 UTC, Geevies commented on code/game/objects/items/toys.dm
> +			user.visible_message(FONT_LARGE (SPAN_NOTICE("[user] rings \the [src], signalling the beginning of the contest.")))
should also add a line after this like "You ring \the [src], blahblahblah"

2021-04-12 10:19 UTC, Geevies approved these changes

2021-04-19 12:39 UTC, fernerr approved these changes

2021-04-19 16:38 UTC, merged