Plushie Grenades
Aurorastation/Aurora.3 pull request #11646
Opened 2021-04-11 13:59 UTC by Geevies

* You can now hide grenades inside plushies after tearing out their stuffing.

Ported from and inspired by https://github.com/tgstation/tgstation/pull/31986

2021-04-11 14:00 UTC, Geevies commented
!review

2021-04-16 18:52 UTC, crunchypretzels approved these changes

2021-04-19 12:28 UTC, fernerr requested changes
The plushie oughta get deleted when the grenade detonates.

2021-05-25 13:09 UTC, Geevies commented
!review

2021-08-14 12:28 UTC, closed without merging