fixes charge cards on the Quik-pay
Aurorastation/Aurora.3 pull request #11653
Opened 2021-04-13 13:11 UTC by Casper3667

The quik-pay will now accept charge cards for payment.

2021-04-13 13:11 UTC, Casper3667 commented
!bugfix

2021-04-16 18:37 UTC, Geevies requested changes

2021-04-16 18:37 UTC, Geevies commented on code/modules/economy/quikpay.dm
> +	if (istype(O, /obj/item/spacecash/ewallet))
put this bit above the part where you check if it's an ID, and add a return after the `please return to home screen` bit

2021-04-23 19:15 UTC, JohnWildkins approved these changes

2021-04-23 19:15 UTC, JohnWildkins commented on code/modules/economy/quikpay.dm
> +	if (istype(O, /obj/item/spacecash/ewallet))
```suggestion
	if (istype(O, /obj/item/spacecash/ewallet))
```

i will nitpick about this space but otherwise works good

2021-04-24 09:34 UTC, Geevies approved these changes

2021-04-28 15:11 UTC, merged