Adds prescription to loadout
Aurorastation/Aurora.3 pull request #11651
Opened 2021-04-12 09:22 UTC by Casper3667

This adds a set of RP prescription medicines to the loadout. The full list is over at [LINK COMING] where a feedback thread has been made to adjust this appropriate.

- [ ] Decide on dosage
- [ ] Decide on pill amount
- [ ] Randomised amount of pills?
- [ ] Finalise the medicine list

2021-04-12 09:23 UTC, Casper3667 commented
!wip

2021-04-15 11:59 UTC, Casper3667 commented
!review

2021-04-16 18:34 UTC, Geevies approved these changes

2021-04-16 18:34 UTC, Geevies commented on code/modules/client/preference_setup/loadout/loadout_utility.dm
> +	var/pills = list()
```suggestion
	var/list/pills = list()
```

2021-04-16 18:34 UTC, Geevies commented on code/modules/client/preference_setup/loadout/loadout_utility.dm
> +	gear_tweaks += new/datum/gear_tweak/path(pills)
```suggestion
	gear_tweaks += new /datum/gear_tweak/path(pills)
```

2021-04-19 12:46 UTC, fernerr approved these changes

2021-04-19 15:01 UTC, NonQueueingMatt requested changes

2021-04-19 15:01 UTC, NonQueueingMatt commented on code/modules/reagents/reagent_containers/pill.dm
> +	desc = "Used to treat a large variety of disorders including tourette, depression, anxiety and psychoses."
```suggestion
	desc = "Used to treat a large variety of disorders including tourettes, depression, anxiety and psychosis."
```

2021-04-19 15:01 UTC, NonQueueingMatt commented on code/modules/reagents/reagent_containers/pill.dm
> +	desc = "Used to treat a large variety of disorders including tourette, depression, anxiety and psychoses."
```suggestion
	desc = "Used to treat a large variety of disorders including tourettes, depression, anxiety and psychosis."
```

2021-04-19 15:01 UTC, NonQueueingMatt commented on code/modules/reagents/reagent_containers/pill.dm
> +	desc = "Used to treat psychoses and muscle weakness."
```suggestion
	desc = "Used to treat psychosis and muscle weakness."
```

2021-04-21 10:24 UTC, merged