Infiltration Kit & Overpressure Protection
Aurorastation/Aurora.3 pull request #11674
Opened 2021-04-16 10:45 UTC by Geevies

* Added an infiltration kit to the Devices and Tools uplink. It spawns a case containing a mask, a uniform, gloves, and shoes, capable of protecting you from the vacuum of space, as well as two atmospheres of overpressure.
* Ported max and min pressure tolerances for items and clothing, meaning that certain gear will now protect better from overpressure, such as atmos voidsuits, firesuits, bomb suits, and to a lesser extent, engineering voidsuits.

![image](https://user-images.githubusercontent.com/22774890/115013587-86a08980-9eb1-11eb-8522-65940934733e.png)

Infiltrator sprites ported from: https://github.com/tgstation/tgstation/pull/49608
Pressure changes ported from: https://github.com/Baystation12/Baystation12/pull/25576

2021-04-16 10:45 UTC, Geevies commented
!review

2021-04-19 15:48 UTC, fernerr requested changes

2021-04-19 15:48 UTC, fernerr commented on code/modules/clothing/sets/infiltrator.dm
> +	item_flags = THICKMATERIAL | INJECTIONPORT | AIRTIGHT
```suggestion
	item_flags = THICKMATERIAL | INJECTIONPORT | AIRTIGHT
	flags_inv = HIDEFACE|BLOCKHAIR
```

2021-04-19 15:48 UTC, fernerr commented on code/modules/clothing/sets/infiltrator.dm
> +	item_flags = THICKMATERIAL | INJECTIONPORT | AIRTIGHT
Else their identity will remain unhidden.

2021-04-19 17:51 UTC, Geevies commented on code/modules/clothing/sets/infiltrator.dm
> +	item_flags = THICKMATERIAL | INJECTIONPORT | AIRTIGHT
good idea

2021-04-19 18:06 UTC, fernerr approved these changes

2021-04-23 21:57 UTC, JohnWildkins approved these changes

2021-04-24 01:22 UTC, merged