Reflective Mirrors
Aurorastation/Aurora.3 pull request #11677
Opened 2021-04-16 16:06 UTC by Geevies

* Reflections are now visible in mirrors.

Ported from https://github.com/Baystation12/Baystation12/pull/30310

Also, credits to CrimsonShrike for spitballing feature ideas with me in this PR.

2021-04-16 16:07 UTC, Geevies commented
!review

2021-04-19 14:30 UTC, Alberyk approved these changes

2021-04-23 22:02 UTC, JohnWildkins requested changes
effect should be deleted and events unregistered if the mirror is deleted

2021-05-30 13:40 UTC, Casper3667 approved these changes

2021-06-01 20:23 UTC, JohnWildkins approved these changes

2021-06-03 01:19 UTC, merged