[WIP] Adds a Free Solarian Fleets ERT.
Aurorastation/Aurora.3 pull request #11670
Opened 2021-04-15 23:32 UTC by TheDanseMacabre

Highly WIP, balancing needs to be done, playtesting to make sure it works, etc etc. I am highly liable to have fucked stuff up in the course of making this PR.

This PR also reworks the item descriptions for a few pieces of Sol gear.

2021-04-15 23:39 UTC, TheDanseMacabre commented
!wip

2021-04-16 23:17 UTC, TheDanseMacabre commented
!review

2021-04-17 08:05 UTC, Geevies commented on code/datums/ert/outsider.dm
> +	chance = 10
no bias here, but i don't think this is needed, i can review the rest of the PR if this is reverted

2021-04-17 08:43 UTC, Geevies commented on code/datums/outfits/ert/fsf_ert.dm
> +    head = /obj/item/clothing/head/helmet/space/void/sol
if you're giving them a voidsuit, there's a proc i added to lancers that automatically sets up their voidsuits

2021-04-17 08:43 UTC, Geevies commented on code/datums/outfits/ert/fsf_ert.dm
> +    head = /obj/item/clothing/head/helmet/space/void/sol
though it needs you to put an oxygen tank in their suit slot, so i don't think it's needed here

2021-04-17 08:43 UTC, Geevies commented on code/datums/outfits/ert/fsf_ert.dm
> +    belt = /obj/item/storage/belt/utility/full
```suggestion
    belt = /obj/item/storage/belt/utility/very_full
```

2021-04-17 08:43 UTC, Geevies commented on code/datums/outfits/ert/fsf_ert.dm
> +    belt = /obj/item/storage/belt/utility/full
this one comes with all the gear you need

2021-04-17 08:43 UTC, Geevies commented on code/datums/outfits/ert/fsf_ert.dm
> +      /obj/item/device/multitool = 1,
if you do the very_full belt, you can remove this

2021-04-17 08:43 UTC, Geevies commented on code/datums/outfits/ert/fsf_ert.dm
> +      /obj/item/weldingtool/hugetank = 1,
this one too

2021-04-18 12:08 UTC, Arrow768 requested changes

2021-04-18 12:08 UTC, Arrow768 commented on code/datums/outfits/ert/fsf_ert.dm
> +/datum/outfit/admin/ert/fsf_ert
Remove the _ert suffix.
It's already clear that this is a ert from the path.

2021-04-18 12:08 UTC, Arrow768 commented on code/datums/outfits/ert/fsf_ert.dm
> +    id = /obj/item/card/id/syndicate
The syndic card should only be used by "proper" antags as it allows self-modification.
This is not needed/wanted for a ert team.

2021-04-18 12:08 UTC, Arrow768 commented on code/datums/outfits/ert/fsf_ert.dm
> +/datum/outfit/admin/ert/fsf_ert/get_id_access()
Same path issue as above.

2021-04-18 12:08 UTC, Arrow768 commented on code/datums/outfits/ert/fsf_ert.dm
> +/datum/outfit/admin/ert/fsf_ert/medic
Same path issue as above.

2021-04-18 12:08 UTC, Arrow768 commented on code/datums/outfits/ert/fsf_ert.dm
> +/datum/outfit/admin/ert/fsf_ert/sapper
Same path issue as above.

2021-04-18 12:08 UTC, Arrow768 commented on code/datums/outfits/ert/fsf_ert.dm
> +/datum/outfit/admin/ert/fsf_ert/leader
Same path issue as above

2021-04-18 12:08 UTC, Arrow768 commented on code/datums/outfits/ert/fsf_ert.dm
> +/datum/outfit/admin/ert/fsf_ert/synth
Same path issue as above

2021-04-18 12:08 UTC, Arrow768 commented on code/game/objects/items/weapons/cards_ids.dm
> +/obj/item/card/id/distress/fsf_ert
If you set up a I'd card here then use it above aswell.

Also same path issue as above.

2021-04-18 12:08 UTC, Arrow768 commented on code/modules/ghostroles/spawner/human/responseteams/fsf_ert.dm
> +/datum/ghostspawner/human/ert/fsf_ert
Same path issue as above

2021-04-18 12:08 UTC, Arrow768 commented on code/modules/ghostroles/spawner/human/responseteams/fsf_ert.dm
> +/datum/ghostspawner/human/ert/fsf_ert/specialist
Same path issue as above

2021-04-18 12:08 UTC, Arrow768 commented on code/modules/ghostroles/spawner/human/responseteams/fsf_ert.dm
> +/datum/ghostspawner/human/ert/fsf_ert/specialist/med
Same path issue as above

2021-04-18 12:08 UTC, Arrow768 commented on code/modules/ghostroles/spawner/human/responseteams/fsf_ert.dm
> +/datum/ghostspawner/human/ert/fsf_ert/leader
Same path issue as above

2021-04-18 12:08 UTC, Arrow768 commented on code/modules/ghostroles/spawner/human/responseteams/fsf_ert.dm
> +/datum/ghostspawner/human/ert/fsf_ert/synth
Same path issue as above

2021-04-18 23:53 UTC, Arrow768 approved these changes

2021-04-18 23:54 UTC, Arrow768 requested changes
The CI-Tests fail.

2021-04-19 00:06 UTC, Arrow768 approved these changes

2021-04-19 06:04 UTC, WickedCybs approved these changes
Looks good and used this partly to learn how to my EPMC ERT revamp, cool.

2021-04-19 07:28 UTC, Geevies approved these changes

2021-04-19 11:11 UTC, NonQueueingMatt requested changes
The FSF file is entirely space-indented. Use tabs.

2021-04-19 11:11 UTC, NonQueueingMatt commented on code/datums/outfits/ert/fsf.dm
> +                )
This indentation is fucked.

2021-04-20 11:13 UTC, merged