Some More Taj Hairstylyes
Aurorastation/Aurora.3 pull request #11762
Opened 2021-04-25 07:14 UTC by WickedCybs

Sprited by Sue, tweaked a bit by me.

Pics soon.

2021-04-25 07:14 UTC, WickedCybs commented
!review

2021-04-25 16:30 UTC, Alberyk requested changes
the chatname var is used to display the name for when people grab the character's hair. It should be a somewhat accurate description of the hairstyle in character. Stuff like lowsmallbun should be replaced.

2021-04-25 22:42 UTC, WickedCybs commented
Changed the chat names.

2021-04-25 23:13 UTC, Alberyk approved these changes

2021-04-28 01:02 UTC, TheDanseMacabre approved these changes

2021-04-28 14:37 UTC, merged