Simple Mob Immolation Buff
Aurorastation/Aurora.3 pull request #11771
Opened 2021-04-27 16:44 UTC by Geevies

* Buffed the amount of damage that fire does to simplemobs to make it worthwhile using against them.

2021-04-27 16:45 UTC, Geevies commented
!review

2021-04-29 09:46 UTC, NonQueueingMatt approved these changes

2021-04-29 16:30 UTC, JohnWildkins approved these changes

2021-04-29 22:41 UTC, Arrow768 requested changes
This needs a more comprehensive solution than the removal of vsc.fire_firelevel_multipler

2021-06-13 16:57 UTC, closed without merging