Laser and Carbine Dangerous Weapons
Aurorastation/Aurora.3 pull request #11780
Opened 2021-04-28 10:44 UTC by Geevies

* Added laser rifles and energy carbines to the dangerous weapons uplink.

2021-04-28 10:44 UTC, Geevies commented
!review

2021-04-28 15:22 UTC, Arrow768 requested changes
The prices are imho too cheap for rather capable weapons.
I would bump each of them up by 2 TCs.

2021-04-29 16:34 UTC, JohnWildkins approved these changes
is the laser rifle an xcom reference

2021-04-29 21:56 UTC, Arrow768 approved these changes

2021-05-01 14:48 UTC, merged