Removes meme hairstyles
Aurorastation/Aurora.3 pull request #11787
Opened 2021-04-29 01:00 UTC by TheDanseMacabre

This PR removes "broken man", which is a nonsensical LISA reference, and bedhead 4, which is anime hair that is genuinely implausible.

2021-04-29 01:01 UTC, TheDanseMacabre commented
!review

2021-04-30 14:37 UTC, MarinaGryphon commented
i have had `bedhead_4` irl before

2021-05-02 21:29 UTC, Arrow768 requested changes
This has been discussed with the maintainers.
The removal of `facial_brokenman` is alright as thats regularly used to make reference chars and not currently in use by any non-reference char.

However we do not see sufficient reason to remove beadhead4

2021-05-03 01:20 UTC, Arrow768 approved these changes

2021-05-05 20:20 UTC, Alberyk approved these changes

2021-05-05 23:43 UTC, merged