Where No Spaceman Has Gone Before: a space sector system
Aurorastation/Aurora.3 pull request #11801
Opened 2021-05-01 05:05 UTC by Alberyk

This pr adds a space sector system to determine where the station/ship is currently.  It currently affects what erts can be selected, what traders will show up in the merchant console, and what away sites can be chosen.

TODO:
- [ ] get a lore accurate description for the current sectors
- [ ] integrate this somehow in the overmap

This is useless for a station setting, but it will be very useful for nbt.

2021-05-06 11:25 UTC, Geevies approved these changes

2021-05-10 00:52 UTC, Arrow768 requested changes

2021-05-10 00:52 UTC, Arrow768 commented on code/controllers/subsystems/initialization/atlas.dm
> +	current_sector = selected_sector
You need to add error-handling/validation there to handle the case of a invalid sector in the config.current_space_sector.
You should also unit-test the current_map.default sector to ensure that this is a valid sector.

2021-05-23 15:01 UTC, JohnWildkins approved these changes

2021-05-30 22:31 UTC, Arrow768 approved these changes

2021-05-30 22:32 UTC, merged