Species specific blood pressure & pulse
Aurorastation/Aurora.3 pull request #11875
Opened 2021-05-09 15:43 UTC by Casper3667

And body temperature also got changed a little. The numbers shown for the blood pressure & pulse are currently purely fluff without mechanical consequences and medicals various scanners should detect the warning ranges based on the species specific things.
Image of the numbers as decided by the various maints: ![image](https://user-images.githubusercontent.com/8396443/117578296-f0493780-b0ed-11eb-936e-49471e285b1c.png)
Special note: currently diona & unathi are not room temperature. That is saved for a future PR.

2021-05-09 15:43 UTC, Casper3667 commented
!review

2021-05-11 14:38 UTC, Geevies requested changes

2021-05-11 14:38 UTC, Geevies commented on code/modules/mob/living/carbon/human/human.dm
> +/mob/living/carbon/human/get_base_systolic()
alright, instead of using procs here, just use `species.var` directly, since you won't ever have a case where there's a human mob without a species

2021-05-11 14:38 UTC, Geevies commented on code/modules/mob/living/carbon/human/human.dm
> +		else if(blood_pressure_disatolic >= get_ideal_disatolic() && blood_pressure_disatolic <=  get_pre_high_disatolic())
you can save a lit of processing by having the "ideal" rate be the first thing to be checked, one factor off ideal being the second, and then the high one being the last. not very important, but just handy to know

2021-05-11 14:38 UTC, Geevies commented on code/modules/emotes/definitions/_species.dm
> +	// Pulse modifiers
this is the place to define emotes, you would want to put these vars in
![image](https://user-images.githubusercontent.com/22774890/117834199-40073a80-b277-11eb-979d-08970ca891fa.png)

2021-05-11 14:38 UTC, Geevies commented on code/modules/mob/living/carbon/human/human.dm
> +/mob/living/carbon/human/get_base_systolic()
calling procs has a higher overhead than just checking a var on a datum

2021-05-12 10:36 UTC, Geevies approved these changes

2021-05-12 10:37 UTC, Geevies commented on code/modules/mob/living/living.dm
> +/mob/living/proc/get_base_systolic()
remove all these procs

2021-05-21 19:45 UTC, Alberyk approved these changes

2021-05-22 06:18 UTC, merged