Tajara loadout options expansion: literature and badges edition
Aurorastation/Aurora.3 pull request #11981
Opened 2021-05-30 22:47 UTC by Alberyk

-rewrites the hadiist manifesto to don't just be a straight parody of the communist manifesto
-adds the free tajaran council badge, sprites made by canon35
-adds some alas beret, to be likely used in consular/lore stuff, sprites made by wickedcybs
-adds the adhomian tarot to the loadout
-adds the tajaran political books to the loadout
-addss the Din'aak Mountains accent

2021-05-30 23:00 UTC, Casper3667 requested changes

2021-05-30 23:25 UTC, Casper3667 approved these changes

2021-05-30 23:31 UTC, WickedCybs commented on code/modules/client/preference_setup/loadout/loadout_xeno/tajara.dm
> +	card["honorary party member card"] = /obj/item/book/manual/pra_manifesto
```suggestion
	card["hadiist manifesto"] = /obj/item/book/manual/pra_manifesto
```

2021-05-30 23:32 UTC, WickedCybs commented on code/modules/client/preference_setup/loadout/loadout_xeno/tajara.dm
> +	card["honorary party member card"] = /obj/item/book/manual/pra_manifesto
Was listed as a party member card, here.

2021-06-02 11:30 UTC, Geevies approved these changes

2021-06-03 01:18 UTC, merged