Cargo suppliers can now have their prices influenced by the current space sector
Aurorastation/Aurora.3 pull request #12147
Opened 2021-07-03 23:23 UTC by Alberyk

This will add more depth to the space sectors. Should not change anything in game until nbt.

2021-07-04 09:15 UTC, Geevies approved these changes

2021-07-16 11:10 UTC, Arrow768 requested changes

2021-07-16 11:10 UTC, Arrow768 commented on code/datums/cargo.dm
> +			final_coef = SSatlas.current_sector.cargo_price_coef["Name"] * price_modifier
You are checking for the existence of the key with the value `short_name` in `cargo_price_coef`.

To calculate the `final_coef` you are are getting the key with the name "Name" from the array `cargo_price_coef`

The key used to access the cargo_price_coeff should most likely be `short_name`

2021-07-16 11:10 UTC, Arrow768 commented on code/modules/background/space_sectors/tauceti.dm
> +								"Xion Manufacturing Group" = 0.8, "Necropolis Industries" = 0.8)
The keys in that list are most likely incorrect, as `short_name` is used to access them.

I believe that `short_name` for the used vendors is something like nt, iac, ...

That can be check3d in the wi/dB

2021-07-16 18:30 UTC, Arrow768 approved these changes

2021-07-16 18:43 UTC, merged