Grab Resist Cuffing
Aurorastation/Aurora.3 pull request #12198
Opened 2021-07-16 14:47 UTC by Geevies

* Being handcuffed or legcuffed makes it 50% more difficult to break out of grabs, being both handcuffed and legcuffed makes it impossible.
* Attempting to move while restrained will now longer spam your chat.

2021-07-16 14:47 UTC, Geevies commented
!review

2021-07-21 12:03 UTC, NonQueueingMatt requested changes

2021-07-21 12:03 UTC, NonQueueingMatt commented on code/modules/mob/living/living.dm
> +		to_chat(src, SPAN_WARNING("You don't have enough power to resist out of any grabs!"))
```suggestion
		to_chat(src, SPAN_WARNING("You aren't powerful enough to break out of this grab!"))
```
Original sentence is way too gamey.

2021-07-26 19:58 UTC, Casper3667 approved these changes

2021-08-14 12:30 UTC, closed without merging