Skrell accents, religions, and citizenship updates.
Aurorastation/Aurora.3 pull request #12215
Opened 2021-07-20 18:30 UTC by listerla

Sprites by Caelphon, and changes approved by Caelphon.

Adds Homeworld, Qerr'malic, Traverse, Aweiji, and Aliose accents, as well as Suur'ka and Kir'gul religions. Removes some lorebreaking accents, citizenships, and religions.

![image](https://user-images.githubusercontent.com/57296132/126376782-2eaa5995-9f67-41e2-9e53-79e5f486056d.png)
![image](https://user-images.githubusercontent.com/57296132/126376805-fc01256c-dcab-483b-bb81-50b22103ee1c.png)

2021-07-20 18:31 UTC, listerla commented
!review

2021-07-20 18:37 UTC, Geevies requested changes

2021-07-20 18:37 UTC, Geevies commented on code/modules/background/accent/skrell.dm
> +	sound half-finished. "
```suggestion
	sound half-finished."
```

2021-07-20 18:37 UTC, Geevies commented on code/modules/background/accent/skrell.dm
> +	description = "This type of accent emphasizes on a balance ofhighs and lows. It uses the nasal canal to further produce a harmonic pattern of speech. Idols are often found replicating \
```suggestion
	description = "This type of accent emphasizes on a balance of highs and lows. It uses the nasal canal to further produce a harmonic pattern of speech. Idols are often found replicating \
```

2021-07-20 18:38 UTC, Geevies approved these changes

2021-07-20 19:53 UTC, Casper3667 requested changes
Almost fine, except you accidentally deleted the taj din'akk accent tag.

2021-07-20 19:55 UTC, listerla commented
> 
> 
> Almost fine, except you accidentally deleted the taj din'akk accent tag.

ah fuck

2021-07-20 19:59 UTC, Casper3667 approved these changes

2021-07-21 12:06 UTC, NonQueueingMatt approved these changes

2021-07-23 22:51 UTC, merged