Togglable Tajara Coats
Aurorastation/Aurora.3 pull request #12229
Opened 2021-07-24 19:09 UTC by 1Sparky1

The Adhomian Wool Coat and Raakti Shariim Coat are now both toggleable. Also made their on-mob sprites look more like coats (can change back if this was intentional).

2021-07-24 19:10 UTC, 1Sparky1 commented
!review

2021-07-26 13:13 UTC, Geevies approved these changes

2021-07-30 16:17 UTC, Alberyk approved these changes

2021-07-30 16:18 UTC, Alberyk requested changes

2021-07-30 16:18 UTC, Alberyk commented on code/modules/clothing/suits/xeno/tajara.dm
> +/obj/item/clothing/suit/storage/tajaran
This needs contained_sprite to be set to true.

2021-07-31 20:58 UTC, Alberyk approved these changes

2021-08-01 15:11 UTC, merged