lowers emotional manipulator message frequency
Aurorastation/Aurora.3 pull request #12262
Opened 2021-07-28 12:31 UTC by Casper3667

Based on feedback from this morning, the message chance on the emotional manipulator augment was lowered down to be halfway between what it is now and what it was before my change.

2021-07-28 12:36 UTC, Casper3667 commented
!review

2021-08-01 13:04 UTC, Geevies requested changes
add a variable that tracks the world.time at which this fires, set a strict limit to the process where it can only fire every X minutes since world.time has passed

2021-08-06 21:18 UTC, Geevies approved these changes

2021-08-06 23:30 UTC, Alberyk approved these changes

2021-08-07 11:55 UTC, merged