Adds *click and *clack
Aurorastation/Aurora.3 pull request #12273
Opened 2021-07-30 06:52 UTC by flpfs

New vaurcan emotes, requested by the vaurca lore deputy.

Sounds sourced from freesound.

2021-07-30 10:00 UTC, Casper3667 approved these changes

2021-07-30 16:02 UTC, Alberyk requested changes
Where are these sounds from? Some sounds from free sound require some kind of attribution.

2021-07-30 18:28 UTC, flpfs commented
> 
> 
> Where are these sounds from? Some sounds from free sound require some kind of attribution.

Sounds are open domain and have no copyright requirement, no need for attribution
https://freesound.org/people/newagesoup/sounds/364728/
https://freesound.org/people/chaosportal/sounds/137104/

2021-07-30 18:28 UTC, flpfs commented
!review

2021-08-01 01:54 UTC, Alberyk approved these changes

2021-08-02 20:24 UTC, merged