Adds a new mining dungeon
Aurorastation/Aurora.3 pull request #12272
Opened 2021-07-30 05:44 UTC by Alberyk

This pr adds a new dungeon, with content based on this forum topic: https://forums.aurorastation.org/topic/14626-adding-vannatusks-a-strong-hostile-mob-to-the-caverns/

2021-08-02 22:39 UTC, Arrow768 approved these changes

2021-08-05 08:55 UTC, Geevies requested changes

2021-08-05 08:55 UTC, Geevies commented on code/modules/mob/living/simple_animal/hostile/vannatusk.dm
> +	desc = "A sharp piece of bone shapped as small dart."
```suggestion
	desc = "A sharp piece of bone shaped into a small dart."
```

2021-08-05 08:55 UTC, Geevies commented on code/modules/mob/living/simple_animal/hostile/vannatusk.dm
> +	if (stat == DEAD && !crystal_harvested)
if(stat != DEAD)
    return ..()
if(istype(O, /obj/item/surgery/scalpel))
    if(crystal_harvested)
        to_chat(user, SPAN_WARNING("\The [src]'s crystal has already been harvested!"))
    // harvest codeblock here
    return
return ..()

2021-08-05 08:55 UTC, Geevies commented on code/modules/mob/living/simple_animal/hostile/vannatusk.dm
> +	anchored = 1
```suggestion
	anchored = TRUE
```

2021-08-05 08:55 UTC, Geevies commented on code/modules/mob/living/simple_animal/hostile/vannatusk.dm
> +	desc = "An interdimensional creature."
could probably get a spookier description than this

2021-08-05 08:55 UTC, Geevies commented on code/modules/mob/living/simple_animal/hostile/vannatusk.dm
> +	new/mob/living/simple_animal/hostile/vannatusk (get_turf(src))
```suggestion
	new /mob/living/simple_animal/hostile/vannatusk(get_turf(src))
```

2021-08-05 15:15 UTC, Geevies approved these changes

2021-08-05 15:15 UTC, Geevies commented on code/modules/mob/living/simple_animal/hostile/vannatusk.dm
> +		visible_message(SPAN_NOTICE("[user] recovers a bluespace crystal from [src]'s remains!"))
this could probably be a visible_message on the user so they can get a personalized messsage

2021-08-05 16:08 UTC, merged