Removes Random Golems
Aurorastation/Aurora.3 pull request #12287
Opened 2021-08-01 23:33 UTC by 1Sparky1

Basically everyone [here](https://forums.aurorastation.org/topic/16177-disable-random-golems/?tab=comments#comment-149409) seems to agree that random golems do very little to enhance a round, and often a lot to deteriorate it. The ghostspawner code is still in there if wanted, but the rune no longer randomly appears.

2021-08-01 23:33 UTC, 1Sparky1 commented
!review

2021-08-02 00:11 UTC, Casper3667 approved these changes

2021-08-02 22:37 UTC, Arrow768 requested changes
Update the excel file for the calculation of the event probabilities

2021-08-04 14:31 UTC, NonQueueingMatt approved these changes

2021-08-04 23:34 UTC, merged