Dionae organ removal and eating tweak
Aurorastation/Aurora.3 pull request #12281
Opened 2021-08-01 06:37 UTC by Alberyk

-removed all dionae organs except the stomach
-diona can no longer be full, they can eat as much they want

2021-08-01 12:50 UTC, Geevies requested changes

2021-08-01 12:50 UTC, Geevies commented on code/modules/reagents/reagent_containers/food/snacks.dm
> +		if (user.is_diona())
this should be a proc on the species level

2021-08-01 16:23 UTC, Geevies approved these changes

2021-08-05 14:45 UTC, Casper3667 approved these changes

2021-08-05 16:08 UTC, merged