Give me the peac gun
Aurorastation/Aurora.3 pull request #12295
Opened 2021-08-04 00:55 UTC by Alberyk

This pr adds a new var to projectiles: anti_materiel_potential.
anti_materiel_potential is a multiplier of how much damage a projectile in question will do to mechas and structures. This way we can have anti-materiel weapons that is not insanely powerful against regular mobs. Besides adding this to the hand cannon, the unathi slugger, and the anti-materiel rifle, this pr also adds two new weapons:

Point entry anti-materiel cannon (peace): a futuristic weapon that fires anti-materiel missiles. While it holds a single round, it can be reloaded.

Adhomian recoilless rifle: a one use adhomian surplus anti-tank gun.

2021-08-04 10:26 UTC, NonQueueingMatt requested changes

2021-08-04 10:26 UTC, NonQueueingMatt commented on code/modules/mob/living/living_defense.dm
> +		damage = P.damage * P.anti_materiel_potential
Not a fan of this. Override bullet_act on the mech and put it at the top before calling ..().

2021-08-04 18:44 UTC, Geevies approved these changes

2021-08-04 18:44 UTC, Geevies commented on code/modules/projectiles/guns/projectile/cannon.dm
> +		to_chat(user, SPAN_WARNING ("You can't fire without stabilizing \the [src]!"))
```suggestion
		to_chat(user, SPAN_WARNING("You can't fire without stabilizing \the [src]!"))
```

2021-08-04 18:44 UTC, Geevies commented on code/modules/projectiles/guns/projectile/cannon.dm
> +	desc_fluff = "The People's Republic of Adhomai is the first  Adhomian faction able to master the nuclear fission. Atomic weapons were used before in the tajaran civil war, \
```suggestion
	desc_fluff = "The People's Republic of Adhomai is the first Adhomian faction able to master the nuclear fission. Atomic weapons were used before in the tajaran civil war, \
```

2021-08-04 18:44 UTC, Geevies commented on code/modules/projectiles/guns/projectile/cannon.dm
> +		to_chat(user, SPAN_WARNING ("You can't fire without stabilizing \the [src]!"))
```suggestion
		to_chat(user, SPAN_WARNING("You can't fire without stabilizing \the [src]!"))
```

2021-08-04 18:44 UTC, Geevies commented on code/modules/projectiles/guns/projectile/cannon.dm
> +		to_chat(user, SPAN_WARNING ("You can't fire without stabilizing \the [src]!"))
```suggestion
		to_chat(user, SPAN_WARNING("You can't fire without stabilizing \the [src]!"))
```

2021-08-04 18:44 UTC, Geevies commented on code/modules/projectiles/guns/projectile/cannon.dm
> +		to_chat(user, SPAN_WARNING ("You can't fire without stabilizing \the [src]!"))
```suggestion
		to_chat(user, SPAN_WARNING("You can't fire without stabilizing \the [src]!"))
```

2021-08-17 15:04 UTC, NonQueueingMatt approved these changes

2021-08-17 15:08 UTC, merged