Adds a huge warning label to the Phoron Punch
Aurorastation/Aurora.3 pull request #12304
Opened 2021-08-07 06:01 UTC by desvenlafaxine

It's 100% your fault if you get poisoned now.

2021-08-07 06:01 UTC, desvenlafaxine commented
!review

2021-08-07 09:07 UTC, Geevies approved these changes

2021-08-07 12:05 UTC, Casper3667 requested changes

2021-08-07 12:05 UTC, Casper3667 commented on code/modules/reagents/reagent_containers/food/cans.dm
> +	desc = "A radical looking can of <span class='warning'>Phoron Punch!</span> Phoron poisoning has never been more extreme! <span class='danger'>WARNING: Phoron is toxic to humans. Consuming this prod
Generally you should avoid doing `<span class='warning'>` and `<span class='danger'>`. Instead it should be roughly:
`desc = "A radical looking can of " + SPAN_WARNING("Phoron Punch!") + " Phoron poisoning has never been more extreme! " + SPAN_DANGER("WARNING: Phoron is toxic to humans. Consuming this product might lead to death.")`

2021-08-09 02:17 UTC, Casper3667 approved these changes

2021-08-11 21:14 UTC, merged