Adds an SCC logo to paperwork
Aurorastation/Aurora.3 pull request #12317
Opened 2021-08-09 07:27 UTC by desvenlafaxine

Simply write down [scc_logo] while making a letter.

2021-08-09 07:29 UTC, desvenlafaxine commented
!review

2021-08-09 17:02 UTC, Casper3667 requested changes
I also note the logo appears to be about the same size as the small NT logo. Not sure if that is intentional or not.

2021-08-09 17:02 UTC, Casper3667 commented on code/_helpers/text.dm
> +	t = replacetext(t, "\[logo_scc\]", "<img src = scclogo.png")
```suggestion
	t = replacetext(t, "\[logo_scc\]", "<img src = scclogo.png>")
```

2021-08-16 00:59 UTC, Casper3667 approved these changes

2021-08-16 02:56 UTC, Alberyk approved these changes

2021-08-16 04:18 UTC, merged