Wiping Cutlery Clears Food
Aurorastation/Aurora.3 pull request #12334
Opened 2021-08-12 09:21 UTC by 1Sparky1

Title.

2021-08-12 09:22 UTC, 1Sparky1 commented
!review

2021-08-13 15:07 UTC, Casper3667 requested changes
`reagents = null` causes a runtime due to not clearing the reagents properly so try to use `reagents.clear_reagents()` instead.

2021-08-13 15:07 UTC, Casper3667 commented on code/game/objects/items/weapons/material/kitchen.dm
> +		reagents = null
```suggestion
		reagents.clear_reagents()
```

2021-08-17 14:55 UTC, NonQueueingMatt approved these changes

2021-08-17 15:53 UTC, Casper3667 approved these changes

2021-08-17 17:59 UTC, merged