Six new Unathi themed recipes
Aurorastation/Aurora.3 pull request #12342
Opened 2021-08-15 09:03 UTC by blackwolf5505

Small handful of new lizard food recipes. Will require addition to wiki.

Send help, I'm not a coder.
![image](https://user-images.githubusercontent.com/6721662/129473135-c6c7153e-884d-4769-8556-dbda651b18ff.png)

2021-08-15 10:28 UTC, Geevies commented on html/changelogs/50n00b_sintafoods.yml
> +	- rscadd: "Added six recipes inspired by sinta cuisine, as well as the required ingredients to make them. They are: Shreiker Wings, Jelly Stew, Roe Fritters, Stuffed Fish Fillet, Razir Noodles, and
```suggestion
  - rscadd: "Added six recipes inspired by sinta cuisine, as well as the required ingredients to make them. They are: Shreiker Wings, Jelly Stew, Roe Fritters, Stuffed Fish Fillet, Razir Noodles, and Sinta Pudding."
```

2021-08-15 10:31 UTC, Geevies commented on code/modules/reagents/reagent_containers/food/snacks/fish.dm
> +	reagents_to_add = list(/decl/reagent/nutriment/protein/seafood/ = 3)
```suggestion
	reagents_to_add = list(/decl/reagent/nutriment/protein/seafood = 3)
```

2021-08-15 10:31 UTC, Geevies commented on code/modules/reagents/reagent_containers/food/snacks.dm
> +	reagents_to_add = list(/decl/reagent/nutriment = 1, /decl/reagent/nutriment/protein/ = 1, /decl/reagent/blood = 6, /decl/reagent/nutriment/coco = 3)
```suggestion
	reagents_to_add = list(/decl/reagent/nutriment = 1, /decl/reagent/nutriment/protein = 1, /decl/reagent/blood = 6, /decl/reagent/nutriment/coco = 3)
```

2021-08-15 10:31 UTC, Geevies commented on code/modules/reagents/reagent_containers/food/snacks.dm
> +	desc = "A fish fillet stuffed with small eggs and cheese"
```suggestion
	desc = "A fish fillet stuffed with small eggs and cheese."
```

2021-08-15 10:31 UTC, Geevies commented on code/modules/reagents/reagent_containers/food/snacks.dm
> +	desc = "A fish fillet stuffed with small eggs and cheese"
```suggestion
	desc = "A fish fillet stuffed with small eggs and cheese."
```

2021-08-15 10:31 UTC, Geevies commented on code/modules/cooking/recipes/cultural/recipes_unathi.dm
> +	/obj/item/reagent_containers/food/snacks/spreads/butter
```suggestion
		/obj/item/reagent_containers/food/snacks/spreads/butter
```

2021-08-15 10:31 UTC, Geevies commented on code/modules/cooking/recipes/cultural/recipes_unathi.dm
> +	/obj/item/reagent_containers/food/snacks/egg,
```suggestion
		/obj/item/reagent_containers/food/snacks/dwellermeat,
		/obj/item/reagent_containers/food/snacks/egg,
```

2021-08-15 10:31 UTC, Geevies commented on code/modules/cooking/recipes/cultural/recipes_unathi.dm
> +	/obj/item/reagent_containers/food/snacks/cheesewedge,
```suggestion
		/obj/item/reagent_containers/food/snacks/fish/carpmeat,
		/obj/item/reagent_containers/food/snacks/fish/roe,
		/obj/item/reagent_containers/food/snacks/cheesewedge,
```

2021-08-15 10:31 UTC, Geevies commented on code/modules/cooking/recipes/cultural/recipes_unathi.dm
> +	/obj/item/reagent_containers/food/snacks/cheesewedge,
```suggestion
		/obj/item/reagent_containers/food/snacks/fish/fishfillet,
		/obj/item/reagent_containers/food/snacks/fish/roe,
		/obj/item/reagent_containers/food/snacks/cheesewedge,
```

2021-08-15 10:31 UTC, Geevies commented on code/modules/cooking/recipes/cultural/recipes_unathi.dm
> +	/obj/item/reagent_containers/food/snacks/spreads/butter,
```suggestion
		/obj/item/reagent_containers/food/snacks/fish/cosmozoan,
		/obj/item/reagent_containers/food/snacks/cutlet,
		/obj/item/reagent_containers/food/snacks/spreads/butter,
```

2021-08-15 10:31 UTC, Geevies commented on code/modules/cooking/recipes/cultural/recipes_unathi.dm
> +	/obj/item/reagent_containers/food/snacks/spreads/butter,
```suggestion
		/obj/item/reagent_containers/food/snacks/meat/bat,
		/obj/item/reagent_containers/food/snacks/meat/bat,
		/obj/item/reagent_containers/food/snacks/spreads/butter,
```

2021-08-16 05:00 UTC, desvenlafaxine requested changes
Add the bitesizes from #12330 so that there are no more conflicts.

2021-08-18 13:05 UTC, Casper3667 approved these changes
Mostly minor formatting nitpicks.

2021-08-18 13:05 UTC, Casper3667 commented on code/modules/cooking/recipes/cultural/recipes_unathi.dm
> +		/obj/item/reagent_containers/food/snacks/spreads/butter,
```suggestion
		/obj/item/reagent_containers/food/snacks/spreads/butter
```

2021-08-18 13:05 UTC, Casper3667 commented on code/modules/cooking/recipes/cultural/recipes_unathi.dm
> +		/obj/item/reagent_containers/food/snacks/spreads/butter,
```suggestion
		/obj/item/reagent_containers/food/snacks/spreads/butter
```

2021-08-18 13:05 UTC, Casper3667 commented on code/modules/cooking/recipes/cultural/recipes_unathi.dm
> +		/obj/item/reagent_containers/food/snacks/cheesewedge,
```suggestion
		/obj/item/reagent_containers/food/snacks/cheesewedge
```

2021-08-18 13:05 UTC, Casper3667 commented on code/modules/cooking/recipes/cultural/recipes_unathi.dm
> +		/obj/item/reagent_containers/food/snacks/cheesewedge,
```suggestion
		/obj/item/reagent_containers/food/snacks/cheesewedge
```

2021-08-18 13:05 UTC, Casper3667 commented on code/modules/cooking/recipes/cultural/recipes_unathi.dm
> +		/obj/item/reagent_containers/food/snacks/egg,
```suggestion
		/obj/item/reagent_containers/food/snacks/egg
```

2021-08-20 07:19 UTC, blackwolf5505 commented
!review

2021-08-22 16:08 UTC, desvenlafaxine reviewed
Another of my PRs fucked this up, this time being #12351. Please update.

2021-08-23 18:50 UTC, blackwolf5505 commented
can't figure out how to use desktop to fix this. can't be assed to babysit the PR for conflicts waiting for it to be merged. closing.

2021-08-23 18:50 UTC, closed without merging