Adds Citizenship and Religion to the Agent ID
Aurorastation/Aurora.3 pull request #12368
Opened 2021-08-22 16:28 UTC by desvenlafaxine

Now you can change them on the agent ID, as per forum request.

Pictured: nationality change (before religion was added too)
![imagen](https://user-images.githubusercontent.com/45808369/130362721-cbc29e3e-3a06-4263-a1fd-4ca903ab171d.png)
![imagen](https://user-images.githubusercontent.com/45808369/130362724-b4bae831-88a0-4701-8359-faa92f712f89.png)

2021-08-22 16:28 UTC, desvenlafaxine commented
!review

2021-08-23 11:42 UTC, Casper3667 requested changes

2021-08-23 11:42 UTC, Casper3667 commented on code/game/objects/items/weapons/cards_ids_syndicate.dm
> +					to_chat(user, "<span class='notice'>Citizenship changed to '[new_citizenship]'.</span>")
```suggestion
					to_chat(user, SPAN_NOTICE("Citizenship changed to '[new_citizenship]'."))
```

2021-08-23 11:42 UTC, Casper3667 commented on code/game/objects/items/weapons/cards_ids_syndicate.dm
> +					to_chat(user, "<span class='notice'>Religion changed to '[new_religion]'.</span>")
```suggestion
					to_chat(user, SPAN_NOTICE("Religion changed to '[new_religion]'."))
```

2021-09-01 15:58 UTC, Alberyk approved these changes

2021-09-02 15:52 UTC, merged