Skrellmet
Aurorastation/Aurora.3 pull request #12425
Opened 2021-08-31 06:17 UTC by nerocavalier

* Ports Skrell Helmet from Bay
* Skrells should be able to select it in Xenowear - Skrell

2021-08-31 06:18 UTC, nerocavalier commented
!review

2021-08-31 10:51 UTC, NonQueueingMatt commented on code/modules/client/preference_setup/loadout/loadout_xeno/skrell.dm
> +	sort_category = "Xenowear - Skrell"
Should probably allow this for HoP and Captain too since they get helmets in their lockers.

2021-09-03 03:39 UTC, WickedCybs approved these changes

2021-09-04 12:39 UTC, NonQueueingMatt requested changes

2021-09-04 12:39 UTC, NonQueueingMatt commented on code/modules/client/preference_setup/loadout/loadout_xeno/skrell.dm
> +	allowed_roles = list(/datum/job/hos, /datum/job/warden, /datum/job/officer, /datum/job/investigator, /datum/job/hop, /datum/job/captain)
This is invalid. You need to use strings here.
```suggestion
	allowed_roles = list("Head of Security", "Warden", "Security Officer", "Investigator", "Head of Personnel", "Captain")
```

2021-09-05 13:31 UTC, NonQueueingMatt approved these changes

2021-09-05 13:38 UTC, merged