Splits the integrated HUD sensors augment into an integrated security HUD and integrated medical HUD augment.
Aurorastation/Aurora.3 pull request #12446
Opened 2021-09-04 18:42 UTC by Jaraci

See title. Loadout cost for the augments dropped from 3 to 1 to compensate. You couldn't use both augments at once, anyway, _and_ they're restricted via ID access as well, so the old functionality of having both in one was useless except for perhaps heads of staff, who have super limited use for the security HUD in particular anyway.

2021-09-04 18:42 UTC, Jaraci commented
!review

2021-09-04 18:47 UTC, NonQueueingMatt requested changes
Split the parent item into 3:

- the parent item that handles the switching and chat logic;
- the two subtypes that handle the HUD sections.

Basically you'll just need to feed some extra stuff into process() and adjust some procs and variables up a bit.

2021-09-04 21:59 UTC, Jaraci commented
I hope this helps! I combined the switches into one for the parent item but then wound up un-combining them again in case a third HUD ever gets implemented or something. I can easily just stuff them back into the parent again, though, I think.

2021-09-07 17:52 UTC, NonQueueingMatt approved these changes

2021-09-07 17:56 UTC, Geevies approved these changes

2021-09-10 13:07 UTC, merged