Drone Machine Interaction
Aurorastation/Aurora.3 pull request #12473
Opened 2021-09-08 12:13 UTC by Geevies

* All non-basic drones can now interact with ore processing consoles and mining equipment vendors.

2021-09-08 12:13 UTC, Geevies commented
!review

2021-09-08 12:22 UTC, Casper3667 approved these changes

2021-09-17 10:38 UTC, NonQueueingMatt requested changes

2021-09-17 10:38 UTC, NonQueueingMatt commented on code/__defines/_macros.dm
> +#define isStandardDrone(A) (A.type == /mob/living/silicon/robot/drone)
You should use ispath here, though a solution using a boolean proc on the mob is preferred.

2021-09-17 14:05 UTC, NonQueueingMatt approved these changes

2021-09-17 14:08 UTC, merged