Teleportation Tweaks
Aurorastation/Aurora.3 pull request #12487
Opened 2021-09-10 20:03 UTC by Geevies

* You can now clearly unset whatever the teleporter station is locked on to, turning off the telepad.
* The teleportation station hub will now show you its station ID when you examine it.
* Teleportation stations will now go offline and prevent hand-teles from locking on to them when they're depowered.
* Teleportation stations now check whether the hand-tele and beacon is on a Z-level connected to it before locking on.
* Hand-teles can now only support two active portals before having to recharge, making it more difficult to hop around endlessly.

2021-09-10 20:03 UTC, Geevies commented
!review

2021-09-22 20:43 UTC, Alberyk approved these changes

2021-09-25 19:34 UTC, Arrow768 requested changes
You have removed the `isNotStationLevel` check.
This check is important to prevent teleportation on the admin z level.

2021-11-02 16:13 UTC, Casper3667 approved these changes

2021-11-06 11:52 UTC, Arrow768 approved these changes

2021-11-21 20:00 UTC, merged