Updates meat sprites
Aurorastation/Aurora.3 pull request #12483
Opened 2021-09-10 05:14 UTC by desvenlafaxine

Current one is really flat for some reason. I didn't bother with the more exotic meats at the moment because they're rare instances.

2021-09-10 05:14 UTC, desvenlafaxine commented
!review

2021-09-10 07:14 UTC, Arrow768 approved these changes

2021-09-10 07:38 UTC, crunchypretzels requested changes
The rotten meat icon seems to be a gif where it vanishes into the ether.

2021-09-10 16:06 UTC, desvenlafaxine commented
> 
> 
> The rotten meat icon seems to be a gif where it vanishes into the ether.

Looks like a github bug. If you download the dmi it works properly.

2021-09-12 03:21 UTC, crunchypretzels approved these changes

2021-09-13 09:30 UTC, merged