Fixes camera bug
Aurorastation/Aurora.3 pull request #12529
Opened 2021-09-21 02:09 UTC by nerocavalier

* This one specifically
 ![image](https://user-images.githubusercontent.com/61446250/134101333-eb0e9b9a-fef6-4e0d-ac54-44a2c07f0126.png)

2021-09-21 02:10 UTC, nerocavalier commented
!review

2021-09-25 19:03 UTC, Arrow768 approved these changes

2021-11-06 11:54 UTC, Arrow768 requested changes

2021-11-06 11:54 UTC, Arrow768 commented on html/changelogs/nerocavalier-typo fix.yml
> +author: ChangeMe
```suggestion
author: nerocavalier
```

2021-11-06 11:55 UTC, Arrow768 approved these changes

2021-11-06 14:35 UTC, merged