Double Round Rolls
Aurorastation/Aurora.3 pull request #12547
Opened 2021-09-23 10:40 UTC by Geevies

* Players who have played a role the previous round will now be the last in line for candidates chosen for the same role in the current round.

2021-09-23 10:40 UTC, Geevies commented
!review

2021-09-23 15:32 UTC, FayeLovesU commented
Long overdue IMO. This is a great and I'd almost wager necessary change for people who play few-slot roles that are highly contested like Investigator.

2021-09-23 15:34 UTC, Jaraci commented
Does this apply to latejoiners or only people who take the role at roundstart? Just curious.

2021-09-23 16:05 UTC, Geevies commented
> 
> 
> Does this apply to latejoiners or only people who take the role at roundstart? Just curious.

just pushed an update. it counts for roundstart and latejoiners, but latejoining after one hour has passed will not cause it

2021-09-23 17:09 UTC, NonQueueingMatt commented
I personally disagree with latejoiners counting. I don't think it should apply to people who queued for a slot and lost the roll and joined later. At the same time, I don't think it should apply to people who join into a slot that wasn't contested.

2021-09-23 17:16 UTC, AnselmKonrad commented
I dont agree with making this applicable to late joining. but how does this stop someone from exactly stopping someone from playing the role again for the next round? does this just entirely stop someone from selecting that role at all? does it just put them at the end of a queue? do they get a decreased chance instead? I can see this only killing the server pop for people who main a single character which is, frankly, a lot of people.

2021-09-23 17:28 UTC, Geevies commented
> 
> 
> I personally disagree with latejoiners counting. I don't think it should apply to people who queued for a slot and lost the roll and joined later. At the same time, I don't think it should apply to people who join into a slot that wasn't contested.

why?



> 
> 
> I dont agree with making this applicable to late joining. I can understand perhaps somehow reducing it but, the choosing of people getting a role is supposed to be random already. Mainly though, how does this stop someone from exactly stopping someone from playing the role again for the next round? does this just entirely stop someone from selecting that role at all? does it just put them at the end of a queue? do they get a decreased chance instead? I can see this only killing the server pop for people who main a single character which is, frankly, a lot of people.

last in queue

2021-09-23 17:41 UTC, AnselmKonrad commented
> Last in queue

So this stops them from joining next round if anyone contests the role at all?

2021-09-23 17:45 UTC, Geevies commented
> 
> 
> > Last in queue
> 
> So this stops them from joining next round if anyone contests the role at all?

yeah. but it checks high, medium, and low too

2021-11-10 23:56 UTC, Arrow768 requested changes

2021-11-10 23:56 UTC, Arrow768 commented on code/controllers/subsystems/job.dm
>  			Debug("Player: [player] is now Rank: [rank], JCP:[job.current_positions], JPL:[position_limit]")
The time played should be a configuration value.
It should also be possible to disable this system via a special configuration value. i.e. -1

2022-03-03 16:51 UTC, Arrow768 requested changes
It seems like I never actually submitted that review, so here we go

The default should maintain the existing behavior.

2022-03-03 16:56 UTC, Arrow768 approved these changes

2022-04-16 19:37 UTC, JohnWildkins approved these changes

2022-05-22 15:18 UTC, NonQueueingMatt commented
Conflicts. Will get re-discussed if anyone re-opens this.

2022-05-22 15:18 UTC, closed without merging