New skrell emotes
Aurorastation/Aurora.3 pull request #12571
Opened 2021-09-30 21:04 UTC by LocoTokyoFunBus

Adds more funny frog sounds, of my own creation

2021-09-30 21:12 UTC, Alberyk requested changes
The lwarble sound file is named lowarble in the code, while the file itself is named low warble. You can either change it in the code or change the file name.

2021-09-30 21:12 UTC, Alberyk commented on code/modules/emotes/definitions/_species.dm
> +		/decl/emote/audible/croak,
```suggestion
		/decl/emote/audible/croak
```

2021-09-30 21:12 UTC, Alberyk commented on code/modules/emotes/definitions/audible.dm
> +	emote_sound = 'sound/voice/lowarble.ogg'
```suggestion
	emote_sound = 'sound/voice/low warble.ogg'
```

2021-09-30 22:02 UTC, LocoTokyoFunBus commented
!review

2021-10-01 12:32 UTC, Alberyk approved these changes

2021-10-02 11:09 UTC, Casper3667 approved these changes

2021-10-04 01:07 UTC, merged