Adds unique Unathi organ Sprites
Aurorastation/Aurora.3 pull request #12734
Opened 2021-11-06 14:57 UTC by Dekserrrrrr

Approved by the Haydizzle himself. This one was a mini-nightmare to code for me but I knocked it out pretty fast.

Thanks to whoever made the Tajara eye sprites because they look awesome, for Unathi eyes I just re-coloured and moved some stuff around.

![Screenshot_266](https://user-images.githubusercontent.com/92396228/140613989-055d0802-f778-44da-b70a-3153b9b07738.png)

2021-11-07 19:12 UTC, Dekserrrrrr commented
!review

2021-11-08 15:51 UTC, Alberyk requested changes

2021-11-08 15:51 UTC, Alberyk commented on code/modules/mob/living/carbon/human/species/station/unathi/unathi.dm
> +        BP_EYES =    /obj/item/organ/internal/eyes/unathi,
```suggestion
        BP_EYES =    /obj/item/organ/internal/eyes/unathi
```

2021-11-08 20:50 UTC, Alberyk requested changes
You are now removing the vaurca organ sprites.

2021-11-10 22:55 UTC, Alberyk approved these changes

2021-11-12 00:00 UTC, merged