Phoron bounty tweak
Aurorastation/Aurora.3 pull request #12766
Opened 2021-11-16 19:54 UTC by desvenlafaxine

So after some #code_dungeon discussion, it seems the main issue with the bounty is just how much it asks for miners. I lowered the amount of sheets to 40 max.

Didn't touch the canister bounty, sure it's boring but we still need to ship that phoron.

2021-11-16 19:54 UTC, desvenlafaxine commented
!review

2021-11-16 20:36 UTC, Arrow768 requested changes

2021-11-16 20:36 UTC, Arrow768 commented on code/modules/cargo/bounties/special.dm
> +	reward_high = 7000
```suggestion
	reward_low = 2600
	reward_high = 3750
```

The bounties in cargo are already high.
No need to further increase them in relation to the items delivered.

2021-11-16 21:54 UTC, Arrow768 approved these changes

2021-11-17 21:16 UTC, Geevies approved these changes

2021-11-21 19:57 UTC, merged