Colorable Chairs, Stools, and other phoney baloney
Aurorastation/Aurora.3 pull request #12797
Opened 2021-11-28 14:59 UTC by alsoandanswer

Give me a moment while I break everything.

2021-11-29 18:32 UTC, alsoandanswer commented
!review

2021-12-01 14:05 UTC, Casper3667 approved these changes

2021-12-01 14:09 UTC, Casper3667 requested changes
Actually just noticed it appears you're deleting the in-hand sprites for paper bags and scepters.

2021-12-01 18:56 UTC, alsoandanswer commented
> Actually just noticed it appears you're deleting the in-hand sprites for paper bags and scepters.

Adressed

2021-12-01 18:58 UTC, Casper3667 approved these changes

2021-12-02 21:54 UTC, NonQueueingMatt approved these changes

2021-12-02 21:57 UTC, merged