Adds two new Tajaran accents
Aurorastation/Aurora.3 pull request #12791
Opened 2021-11-26 22:51 UTC by Alberyk

This pr adds two new Tajaran accents to the new NKA regions. Also fixes the nka citizenship saying that king Azunja is still alive.

2021-11-26 23:19 UTC, Casper3667 requested changes

2021-11-26 23:19 UTC, Casper3667 commented on code/modules/background/accent/tajara.dm
> +/datum/accent/dinakk
The din'akk accent got copied.

2021-11-27 18:31 UTC, Casper3667 approved these changes

2021-11-29 08:19 UTC, WickedCybs approved these changes

2021-11-29 19:49 UTC, NonQueueingMatt approved these changes

2021-11-30 16:24 UTC, merged