If it rains, you put on a coat. Rack. (Coatrack buffs.)
Aurorastation/Aurora.3 pull request #12829
Opened 2021-12-07 18:14 UTC by alsoandanswer

Basically, adds support for every concievable coat for the coat rack. (and ponchos.)

That means no more hard-sprited coats. They simply recycle the on-mob sprite.

<img width="97" alt="dreamseeker_R7ftEoZcNR" src="https://user-images.githubusercontent.com/42310821/145083700-d95f2bda-b834-430a-ac38-5337397aaae6.png">

2021-12-07 18:16 UTC, alsoandanswer commented
!review

2021-12-08 10:22 UTC, Chada-1 approved these changes
💟

2021-12-14 17:54 UTC, Casper3667 approved these changes

2021-12-19 20:50 UTC, Arrow768 requested changes

2021-12-19 20:50 UTC, Arrow768 commented on code/game/objects/structures/coatrack.dm
> +		return
You should use the use_check / use_check_and_message proc instead possibly with optional flags.

2021-12-19 20:50 UTC, Arrow768 commented on code/game/objects/structures/coatrack.dm
> +/obj/structure/coatrack/attackby(obj/item/W as obj, mob/user as mob)
You should use a use_check / use_check_and_message proc here possibly with optional flags.

2021-12-22 16:03 UTC, Alberyk approved these changes

2021-12-25 15:05 UTC, merged