Adds back TCom scripting
Aurorastation/Aurora.3 pull request #12862
Opened 2021-12-18 16:48 UTC by Karolis2011

Maybe there will be more feaature requests

2021-12-19 20:09 UTC, Arrow768 requested changes

2021-12-19 20:09 UTC, Arrow768 commented on code/controllers/subsystems/processing/ntsl2.dm
> +		connected = FALSE
Wouldnt it be cleaner to call `disconnect()` here instead of just setting connected to false?

2021-12-19 20:09 UTC, Arrow768 commented on code/game/machinery/telecomms/traffic_control copy.dm
> +/obj/machinery/computer/telecomms/traffic
I think that file might have been accidently committed

2021-12-21 21:39 UTC, Karolis2011 commented
![img](https://cdn.discordapp.com/attachments/157531783779319808/921798734566789210/unknown.png)

2021-12-21 21:50 UTC, Karolis2011 commented
Following are currently supported APIs:
- `Com.setSignalHandler(handler)` - sets signal handler function - a function that is called on signal being received. Hander's execution time is limited to 500 ms (half a second)
- `Com.createSignal()` - returns new signal object, said object is not queued for transmission.
- `Com.broadcast(signal)` - queues provided signal for transmission. And returns same signal.
- `Com.broadcast()` - Creates and queues new signal for transmission, returns that signal object.
- `signal.clone()` - Makes almost exact copy of signal.
- `signal.Content` - Property for setting or getting signal's content. Defaults to `"*beep*"`
- `signal.Freq` - Property to alter frequency. Defaults to `1459`
- `signal.Source` - Property to alter Source name. Defaults to `"Telecomms Broadcaster"`
- `signal.Pass` - Should signal pass Tcom systems. Defaults to `true`
- `signal.Verb` - What's the signal's verb. Defaults to `"says"`
- `signal.Language` - Language of said signal. Defaults to `"Ceti Basic"`

2021-12-21 21:50 UTC, Karolis2011 commented
!review

2022-04-19 09:55 UTC, NonQueueingMatt commented
Inactive, DM me if you want this reopened.

2022-04-19 09:55 UTC, closed without merging