Changes how forensic machine reports works
Aurorastation/Aurora.3 pull request #12868
Opened 2021-12-21 02:04 UTC by Casper3667

- Fingerprint & fiber reports now show the location they were gathered from. Particularly useful when combining them.
- Fingerprint cards & fiber bags can now be renamed. This does not affect the source location that is displayed on reports.
- Door names will now appear on the reports if the door had one.
- Generally changed how the reports appear.
- The numbering of the reports is now per type (fiber, fingerprint, GSR, DNA) rather than all of them combined per mahine.
- Gunshot Residue (GSR) now shows all residue on the given item/mob, rather than only the most recent.

![image](https://user-images.githubusercontent.com/8396443/146858367-5347bbd4-3703-4e7a-baa8-7dd8d279fd21.png)

2021-12-21 02:17 UTC, Casper3667 commented
!review

2022-01-03 21:22 UTC, NonQueueingMatt commented on code/modules/detectivework/microscope/dnascanner.dm
> +		info = "<b><font size=\"4\">[src] anaylsis report #[report_num]</font></b><HR>"
```suggestion
		info = "<b><font size=\"4\">[src] analysis report #[report_num]</font></b><HR>"
```

2022-01-03 21:22 UTC, NonQueueingMatt commented on code/modules/detectivework/tools/sample_kits.dm
> +		if(length(tmp_label) > 20)
20 should be MAX_NAME_LEN

2022-01-03 21:22 UTC, NonQueueingMatt commented on code/modules/detectivework/tools/sample_kits.dm
> +			to_chat(user, SPAN_NOTICE("The label can be at most 20 characters long."))
ditto above

2022-01-03 21:22 UTC, NonQueueingMatt commented on code/modules/mob/living/carbon/human/human_defines.dm
> +	var/gunshot_residue = list()
```suggestion
	var/list/gunshot_residue = list()
```

2022-01-12 11:10 UTC, NonQueueingMatt approved these changes

2022-01-16 09:32 UTC, Geevies requested changes

2022-01-16 09:32 UTC, Geevies commented on code/modules/detectivework/microscope/dnascanner.dm
> +			data = "Spectometric analysis on provided sample has determined the presence of [bloodsamp.dna.len] string(s) of DNA.<br><br>"
```suggestion
			data = "Spectometric analysis on provided sample has determined the presence of [length(bloodsamp.dna)] string\s of DNA.<br><br>"
```

2022-01-16 09:32 UTC, Geevies commented on code/modules/detectivework/microscope/microscope.dm
> +				info += "Residue analysis of \the [swab.name] has determined the presence of the following residues.<ul>"
```suggestion
				info += "Residue analysis of the [swab.name] has determined the presence of the following residues.<ul>"
```
\the doesn't work with obj.name

2022-01-16 09:32 UTC, Geevies commented on code/modules/detectivework/microscope/microscope.dm
> +					info += "<li>Residue from a [gsr] bullet detected."
```suggestion
					info += "<li>Residue from a [gsr] bullet detected.</li>"
```

2022-01-16 09:32 UTC, Geevies commented on code/modules/detectivework/microscope/microscope.dm
> +					info += "<li><b>Most likely match for fibers:</b> [fiber]"
```suggestion
					info += "<li><b>Most likely match for fibers:</b> [fiber]</li>"
```

2022-01-16 09:32 UTC, Geevies commented on code/modules/detectivework/microscope/microscope.dm
> +		info = "<b><font size=\"4\">Fingerprint anaylsis report #[report_print_num]</font></b><HR>"
```suggestion
		info = "<b><font size=\"4\">Fingerprint analysis report #[report_print_num]</font></b><HR>"
```

2022-01-16 09:32 UTC, Geevies commented on code/modules/detectivework/microscope/microscope.dm
>  				info += "<br>"
```suggestion
				info += "</li>"
```

2022-01-16 09:32 UTC, Geevies commented on code/modules/detectivework/tools/evidencebag.dm
> +			to_chat(user, "<span class='notice'>The label can be at most [MAX_NAME_LEN] characters long.</span>")
```suggestion
			to_chat(user, SPAN_NOTICE("The label can be at most [MAX_NAME_LEN] characters long."))
```

2022-01-16 09:32 UTC, Geevies commented on code/modules/detectivework/tools/sample_kits.dm
> +	var/list/source = list()
both of these can be lazylists

2022-01-16 09:32 UTC, Geevies commented on code/modules/detectivework/tools/sample_kits.dm
> +			to_chat(user, SPAN_NOTICE("The label can be at most [MAX_NAME_LEN] characters long."))
```suggestion
			to_chat(user, SPAN_WARNING("The label can be at most [MAX_NAME_LEN] characters long."))
```

2022-01-16 09:32 UTC, Geevies commented on code/modules/detectivework/tools/sample_kits.dm
> +		return
```suggestion
		name = initial(name)
```

2022-01-16 09:32 UTC, Geevies commented on code/modules/detectivework/tools/sample_kits.dm
> +/obj/item/sample/New(var/newloc, var/atom/supplied)
use Initialize

2022-01-16 09:32 UTC, Geevies commented on code/modules/mob/living/carbon/human/human_defines.dm
> +	var/list/gunshot_residue = list()
lazylist

2022-01-16 09:32 UTC, Geevies commented on code/modules/projectiles/guns/projectile.dm
> +				H.gunshot_residue |= chambered.caliber
there should be a LAZYDISTINCTADD you can replace both of these lines with

2022-01-16 09:32 UTC, Geevies commented on code/modules/projectiles/guns/projectile.dm
> +				G.gunshot_residue |= chambered.caliber
same as above

2022-01-16 18:25 UTC, Geevies approved these changes

2022-01-17 15:51 UTC, merged