Smooth Wall Fix
Aurorastation/Aurora.3 pull request #12920
Opened 2022-01-17 13:15 UTC by 1Sparky1

Fixes #12896

2022-01-17 13:15 UTC, 1Sparky1 commented
!bugfix

2022-01-17 13:19 UTC, 1Sparky1 commented
!review

2022-01-17 13:28 UTC, alsoandanswer approved these changes

2022-01-18 13:34 UTC, Geevies requested changes

2022-01-18 13:34 UTC, Geevies commented on code/game/turfs/simulated/walls.dm
> +			LAZYADD(canSmoothWith, /turf/simulated/wall/r_wall)
this should probably be a proc on `/turf/simulated/wall`. something like `/turf/simulated/wall/proc/select_wall_smooth()` which gets overridden to add the other wall type. doing istype(src) is never good

2022-01-18 21:18 UTC, Geevies approved these changes

2022-01-22 12:17 UTC, NonQueueingMatt commented
I don't particularly like the type hardchecking. Ideally this is handled in another way.

2022-01-22 22:52 UTC, Arrow768 approved these changes

2022-01-22 22:52 UTC, merged