Exoplanet ruins, away sites, overmap submaps and maploader goodies.
Aurorastation/Aurora.3 pull request #12933
Opened 2022-01-20 17:17 UTC by NonQueueingMatt

Maploader now actually initializes atoms/atmos machinery/cables/etc.
Maploader can now handle multi-z templates and shuttles.

Exoplanet ruins now work.

Away sites now work, same with overmap submaps.

2022-01-20 17:18 UTC, NonQueueingMatt commented
!review

2022-01-29 13:28 UTC, Alberyk approved these changes

2022-02-10 14:25 UTC, mikomyazaki requested changes

2022-02-10 14:25 UTC, mikomyazaki commented on maps/away/README.md
> +BUT HEED MY RUMINATIONS
Speaking of unit tests, is this important to port over aswell?
[Baystation unit_tests/submaps.dm](https://github.com/Baystation12/Baystation12/blob/dev/code/unit_tests/submaps.dm)

2022-02-18 14:20 UTC, NonQueueingMatt commented on maps/away/README.md
> +BUT HEED MY RUMINATIONS
That unit test isn't really useful to us right now - descriptors are more useful on Bay since I think they're used as identifiers for submap jobs?

2022-02-18 14:20 UTC, NonQueueingMatt commented on maps/away/README.md
> +BUT HEED MY RUMINATIONS
> Should we have unit tests for some of this stuff? (under this line) The "Don't re-use area types from other maps" one especially?

Honestly not really sure how to implement this in a sane way.

2022-02-18 14:20 UTC, NonQueueingMatt commented on code/controllers/subsystems/mapping.dm
> +			if (is_banned)
addressed

2022-02-18 14:22 UTC, mikomyazaki approved these changes

2022-02-18 14:34 UTC, merged