New Station Bounced Sprites
Aurorastation/Aurora.3 pull request #12935
Opened 2022-01-20 19:35 UTC by 1Sparky1

Resprites the station bounced radio and adds some new departmental ones. Also, removes the virology uplink from medical reception.

[Forum Thread.](https://forums.aurorastation.org/topic/16865-new-station-bounced-radio-sprites/#comment-154312)

2022-01-20 19:57 UTC, 1Sparky1 commented
!review

2022-01-20 20:13 UTC, alsoandanswer requested changes
1. Reduce their size to be on par, or smaller than the original station bound sprites.
2. Re-use the existing colors used for headsets for the departmental ones. It's for consistency.

2022-01-21 14:11 UTC, 1Sparky1 commented
Sprites have been trimmed to be the same size height wise as the old one (Were already the same width). Also added a white stripe to the medical one to aid in distinguishing it from the security one, as suggested on the forums.

When it comes to the colours, I used the colours from the headsets for the medical and security ones already. The science one I had originally done so as well, but this different shade (taken from the GPS) was requested on the forums, and personally I prefer it. The generic one obviously doesn't have a headset, but I did _try_ the engineering colours on that sprite. It just didn't look right, and in my eyes looked more like it should have been in cargo than engineering, so haven't changed that one either.

2022-03-03 19:49 UTC, Arrow768 approved these changes

2022-03-12 14:05 UTC, NonQueueingMatt approved these changes

2022-03-12 14:08 UTC, merged