Hatches
Aurorastation/Aurora.3 pull request #12986
Opened 2022-01-25 22:32 UTC by 1Sparky1

Changes all the airlocks to be called hatches, on the player-facing end at least. Code side they're still called airlocks for the sake of not breaking everything and for ease of porting stuff.

2022-01-25 22:36 UTC, 1Sparky1 commented
!review

2022-01-25 22:37 UTC, 1Sparky1 commented
!review

2022-01-26 02:14 UTC, alsoandanswer commented
Don't think this is a good idea. We're going against the momentum of several years of them being called airlocks now, and all this does is just make things confusing.

2022-02-09 18:59 UTC, listerla approved these changes

2022-02-15 22:26 UTC, NonQueueingMatt requested changes

2022-02-15 22:26 UTC, NonQueueingMatt commented on code/game/machinery/doors/door.dm
> +		hatchestate = 1
Hatche?

2022-02-15 22:26 UTC, NonQueueingMatt commented on code/game/machinery/doors/door.dm
> +		hatchestate = 1
This error is present in a few more lines too.

2022-03-04 12:17 UTC, 1Sparky1 commented
Having actually paid attention during the game, there are very few places where the name airlock is actually shown to the player. Closing.

2022-03-04 12:17 UTC, closed without merging