IV Drip Blood Injection Stop Quality of Life
Aurorastation/Aurora.3 pull request #12988
Opened 2022-01-26 06:55 UTC by VisVirific

* IV drips that are injecting blood can now automatically and safely detach from patients whose blood volume is fully recovered.
* This automatic stop mode can be deactivated/activated via Toggle Stop (Right Click the IV drip).

**IV drip's automatic stop mode active.**
https://images-ext-2.discordapp.net/external/FB4zLQKXccOTZVOY1TUYzEDrBuOFDWAuC20qa0xQNEw/https/i.imgur.com/36jyE2K.png?width=872&height=473

2022-01-26 06:55 UTC, VisVirific commented
!review

2022-02-06 11:22 UTC, Geevies requested changes

2022-02-06 11:22 UTC, Geevies commented on code/game/machinery/iv_drip.dm
> +	if(!istype(usr, /mob/living))
```suggestion
	if(!isliving(usr))
```

2022-02-06 11:22 UTC, Geevies commented on code/game/machinery/iv_drip.dm
> +		to_chat(usr, "<span class='warning'>You can't do that.</span>")
```suggestion
		to_chat(usr, SPAN_WARNING("You can't do that."))
```

2022-02-06 11:22 UTC, Geevies commented on code/game/machinery/iv_drip.dm
> +	if(usr.stat)
```suggestion
	if(usr.incapacitated())
```

2022-02-06 11:22 UTC, Geevies commented on code/game/machinery/iv_drip.dm
> +	to_chat(usr, "[src]'s automatic stop mode is now [toggle_stop ? "active" : "deactivated"]")
```suggestion
	usr.visible_message("<b>[usr]</b> toggles \the [src]'s automatic stop mode [toggle_stop ? "on" : "off"]", SPAN_NOTICE("You toggle \the [src]'s automatic stop mode [toggle_stop ? "on" : "off"]."))
```

2022-02-06 15:32 UTC, Geevies approved these changes

2022-02-09 17:25 UTC, NonQueueingMatt approved these changes

2022-02-09 17:27 UTC, merged