Library books/ bookbinder
Aurorastation/Aurora.3 pull request #12996
Opened 2022-01-29 13:32 UTC by Xxxxyobdab

- Leather sheets can be used to reskin books
- The bookbinder can now be set to print a book with a specific cover
- Books now retain reference to it's category
- books spawned from only the library bookspawners will gain the category of it.
- books printed from the external archive will fill in the category var
- the barcode scanner's base function will now also tell title, author, category on scan.

Please ensure the code used for database query is correct as I cannot test for it.

2022-01-29 13:39 UTC, Xxxxyobdab commented
!review required

2022-02-02 15:19 UTC, Alberyk requested changes
Do not delete the changelos or replace one with yours. Create a new file for your changelog.

2022-03-03 20:49 UTC, Arrow768 requested changes

2022-03-03 20:49 UTC, Arrow768 commented on code/modules/library/lib_machines.dm
>  			query.Execute()
```suggestion
			var/DBQuery/query = dbcon.NewQuery("SELECT author, title, content, category FROM ss13_library WHERE id=:sqlid:")
			query.Execute(list("sqlid"=sqlid))
```

2022-04-19 09:53 UTC, NonQueueingMatt commented
Inactive, DM me if you want this reopened.

2022-04-19 09:53 UTC, closed without merging