Railing Stuff
Aurorastation/Aurora.3 pull request #13035
Opened 2022-01-30 15:01 UTC by Geevies

* It now takes two seconds to climb railings, down from five.
* When climbing a railing, you always appear on the other side, no more shuffling along it when approached from an angle.
* Middle-clicking a climbable structure now makes you climb it.

2022-01-30 15:01 UTC, Geevies commented
!review

2022-01-30 18:55 UTC, alsoandanswer approved these changes

2022-02-01 12:09 UTC, Casper3667 requested changes

2022-02-01 12:09 UTC, Casper3667 commented on code/game/objects/structures/railing.dm
> +		if(A.density && !(A.flags & ON_BORDER))
This appears to trigger if the turf is shared with another railing, even if it faces another direction.

2022-02-06 19:40 UTC, Casper3667 approved these changes

2022-02-06 21:21 UTC, merged