Fallout New Vegas
Aurorastation/Aurora.3 pull request #13067
Opened 2022-02-02 21:21 UTC by alsoandanswer

- rscadd: "Slot machines now accept credits! Use the multitool to switch between coin mode and credit mode."
  - soundadd: "Slot machines also have sound! Be sure to toggle Arcade SFX to hear it. Also, makes it 87% more addictive."
  (Taken from Freesound. Cheesily recognisable stock sound effects. But damn, it is satisfying to hear.)

2022-02-02 21:54 UTC, alsoandanswer commented
!review

2022-02-02 22:15 UTC, SleepyWolfe commented
will this add a multitool to the bar as well?

2022-02-03 06:53 UTC, Caelphon commented
@SleepyWolfe I believe if it isn't it can be located within the Auxiliary Tool Storage on the surface opposite of the elevators - if I am mistaken, could always bug a engineer.

2022-02-15 22:53 UTC, alsoandanswer commented
!wip need to fix roundstart empty slots

2022-02-22 17:18 UTC, alsoandanswer commented
!review

2022-03-03 15:52 UTC, Casper3667 approved these changes

2022-03-03 20:26 UTC, Arrow768 requested changes

2022-03-03 20:26 UTC, Arrow768 commented on code/game/machinery/computer/slotmachine.dm
> +		if(stat & NOPOWER)
This condition (`stat & NOPOWER`) unless the previous condition is also triggered (`stat & BROKEN`)

Shouldn't be first condition be something like `(stat & BROKEN || stat & NOPOWER)` ?

2022-03-04 11:15 UTC, NonQueueingMatt approved these changes

2022-03-04 11:24 UTC, merged