Beakers, bottles and syringe resprite
Aurorastation/Aurora.3 pull request #13096
Opened 2022-02-05 20:09 UTC by alsoandanswer

Mostly ported from Eris, noreact beaker and bottle variants by yours truly. Also, inhands, again. Because by jove, I made this system, and I'm gonna use the shit out of it.

Removed some unused sprites as well, and some ancient botany garbage.

Rather surprised at the reception this got, apparently people really like to have beakers that they don't have to pixel-hunt to click. Same with syringes.

Also tweaks how the reagent container overlays are handled, shouldn't be too much of a fuss.

2022-02-05 20:10 UTC, alsoandanswer commented
!review

2022-02-05 20:35 UTC, desvenlafaxine commented
Sprite preview won't load, do you have pics? (Think I know how they look but still).

2022-02-23 11:40 UTC, NonQueueingMatt approved these changes

2022-03-01 16:08 UTC, Casper3667 requested changes

2022-03-01 16:08 UTC, Casper3667 commented on code/modules/cooking/machinery/cooking_machines/container.dm
> +/obj/item/reagent_containers/cooking_container/plate/bowl/update_icon()
This isn't called when the bowl reagents are updated.

2022-03-03 18:42 UTC, Casper3667 approved these changes

2022-03-03 20:46 UTC, Arrow768 submitted a review, later dismissed
I am concerned about the large syringes.
It was a very common tactic by medical to rush antags with syringes and stab them on harm intent.

The current implementation of the harm-intent-stabbing does not account for armor.
It should be changed to account for armor and make it impossible to harm-intent stab someone with armor. (i.e. "the needle breaks off")
In addition the flat -5 reduction in volume here should be changed to a /2 reduction.
`var/syringestab_amount_transferred = rand(0, (reagents.total_volume - 5))`

2022-03-04 17:45 UTC, merged