fixes some knitting bugs
Aurorastation/Aurora.3 pull request #13114
Opened 2022-02-06 21:06 UTC by Casper3667

fixes https://github.com/Aurorastation/Aurora.3/issues/13069

Yarn now shows the proper color on the sprite when attached to the knitting needles, can be removed with a verb and updates the sprite properly to be animated when in use.

2022-02-06 21:09 UTC, Casper3667 commented
!review

2022-02-06 21:40 UTC, alsoandanswer commented on code/game/objects/items/knitting.dm
> +		user.update_inv_l_hand()
I think you can use update_held_icons() here

2022-02-10 10:57 UTC, SleepyGemmy requested changes

2022-02-10 10:57 UTC, SleepyGemmy commented on code/game/objects/items/knitting.dm
> +	to_chat(usr, SPAN_NOTICE("You remove \the [ball] from \the [src]"))
```suggestion
	to_chat(usr, SPAN_NOTICE("You remove \the [ball] from \the [src]."))
```

2022-02-10 19:53 UTC, SleepyGemmy approved these changes
Changes addressed.

2022-02-11 21:27 UTC, Alberyk approved these changes

2022-02-13 16:31 UTC, NonQueueingMatt approved these changes

2022-02-13 16:37 UTC, merged