lizard augment egalitarianism
Aurorastation/Aurora.3 pull request #13195
Opened 2022-02-16 03:06 UTC by Aticius

Finally, they can go see the Biomechanical Engineers we fired.

Unlikely to break anything unless i'm criminally bad at spelling.

![image](https://user-images.githubusercontent.com/7741012/154188382-ab253365-af3a-45ee-9da8-c971d56ff6da.png)

2022-02-16 03:58 UTC, Aticius commented
!review

2022-02-16 08:18 UTC, Arrow768 requested changes
Afaik the unauthorised augment restrictions were quite intentional due to the difference between their and other species tech levels.

I'll discuss that with the lore masters, until then it's a dem

2022-02-16 08:18 UTC, Arrow768 commented on html/changelogs/aticius-lizardaugments.yml
> +author: ChangeMe
You need to change that.

2022-03-05 05:51 UTC, Aticius commented
Changes addressed because my head is full of water

2022-03-05 16:46 UTC, Arrow768 approved these changes

2022-03-07 13:58 UTC, NonQueueingMatt approved these changes

2022-03-07 15:47 UTC, merged