Technomancer Chameleon Core
Aurorastation/Aurora.3 pull request #13252
Opened 2022-02-21 19:04 UTC by Geevies

* Technomancer Cores can now be disguised like other chameleon gear.

2022-02-21 19:04 UTC, Geevies commented
!review

2022-02-22 09:21 UTC, ChevyChevron commented
I feel like, with the mechanical changes from wiz to techno, having the ability to disguise the core as a regular backpack could potentially be detrimental to gameplay.

2022-03-03 20:36 UTC, Arrow768 requested changes
Can you throw in the EMP reset from that pr: #12427 

(I prefer your pr since the "whitelist" in the `generate_chameleon_choices` proc is a bit more elegant)

2022-03-12 14:03 UTC, NonQueueingMatt approved these changes

2022-03-13 20:32 UTC, Arrow768 approved these changes

2022-03-13 20:33 UTC, merged