Plates, Bowls and More Plates
Aurorastation/Aurora.3 pull request #13269
Opened 2022-02-24 12:51 UTC by 1Sparky1

Adds dinner plates (For putting food on, intended for use with things that don't have a plate as part of their sprite already, but works for all) and dinner bowls (So you can give someone less than an entire pot of stew). Also added service plates, which work like smaller trays, for serving meals up on. As serving plates were already a thing (For preparing food, rather than serving it) that item has been renamed/sprited as a chopping board. 

Oh, and dinner bowls and plates get messy when used. You can clean them like a normal person with a cloth, or by licking the mess off.

This PR got out of hand real fast, so if there's any obviously unfinished code, just point it out.

2022-02-24 12:51 UTC, 1Sparky1 commented
!review

2022-02-24 20:01 UTC, Aticius commented
I can confirm. I want to lick bowls.

2022-03-03 20:00 UTC, Arrow768 requested changes

2022-03-03 20:00 UTC, Arrow768 commented on code/modules/cooking/machinery/cooking_machines/container.dm
>  /obj/item/reagent_containers/cooking_container/plate
You should change the path to reflect the new name.
Otherwise it can be confusing if you want to search for certain things.

2022-04-09 15:48 UTC, NonQueueingMatt requested changes

2022-04-09 15:48 UTC, NonQueueingMatt commented on code/modules/cooking/plates.dm
> +    var/obj/item/holding
Clear this out on Destroy().

2022-04-09 15:48 UTC, NonQueueingMatt commented on code/modules/cooking/plates.dm
> +    . = ..()
Useless.

2022-04-09 15:48 UTC, NonQueueingMatt commented on code/modules/cooking/plates.dm
> +        to_chat(user, SPAN_NOTICE("You place \the [holding.name] on \the [name]"))
```suggestion
        to_chat(user, SPAN_NOTICE("You place \the [holding.name] on \the [name.]"))
```

2022-04-09 15:48 UTC, NonQueueingMatt commented on code/modules/cooking/plates.dm
> +        to_chat(user, SPAN_NOTICE("You take \the [F.name] from \the [name]"))
```suggestion
        to_chat(user, SPAN_NOTICE("You take \the [F.name] from \the [name]."))
```

2022-04-09 15:48 UTC, NonQueueingMatt commented on code/modules/cooking/plates.dm
> +                grease = TRUE
Condense this into a proc. it's copypasted a few times.

2022-04-09 15:48 UTC, NonQueueingMatt commented on code/modules/cooking/plates.dm
> +    return
No need to return here.

2022-04-09 15:48 UTC, NonQueueingMatt commented on code/modules/cooking/plates.dm
> +/obj/item/reagent_containers/bowl
This is a bit weird - I see that they share some code. Why isn't this a subtype of the other, or viceversa?

2022-04-09 15:48 UTC, NonQueueingMatt commented on code/modules/reagents/Chemistry-Holder.dm
> -
Is the deleting of newlines here intentional? Some of the ones you've deleted make the proc harder to read.

2022-04-09 15:48 UTC, NonQueueingMatt commented on code/modules/reagents/Chemistry-Holder.dm
> -
Like these ones. These kinds of newlines are good, because they segment out parts of a proc. We don't always want everything to be continuous.

2022-04-09 15:48 UTC, NonQueueingMatt commented on code/modules/reagents/Chemistry-Holder.dm
> +	if(!target)
I don't think this should be modified. Pretty sure this causes unusual behaviour. Did you test this?

2022-04-09 15:48 UTC, NonQueueingMatt commented on code/modules/reagents/reagent_containers/food.dm
> +		AfterItem = src
What?

2022-04-19 09:52 UTC, closed without merging

2022-04-19 09:53 UTC, NonQueueingMatt commented
Inactive, DM me if you want this reopened.