Injecting reagent containers sends nearby mobs a warning
Aurorastation/Aurora.3 pull request #13261
Opened 2022-02-23 00:02 UTC by 1Sparky1

Title.

2022-02-23 00:02 UTC, 1Sparky1 commented
!review

2022-02-23 01:17 UTC, NonQueueingMatt requested changes
Use visible_message instead of a manual loop.

2022-02-23 14:52 UTC, NonQueueingMatt requested changes

2022-02-23 14:52 UTC, NonQueueingMatt commented on code/modules/reagents/reagent_containers/syringes.dm
> +			user.visible_message(SPAN_WARNING("[user] injects [target] with the syringe!"),SPAN_NOTICE("You inject [trans] units of the solution. The syringe now contains [src.reagents.total_volume] units."),
Our reagent container might not necessarily be named a syringe. Use `with [src]` instead.

2022-02-23 15:31 UTC, 1Sparky1 commented on code/modules/reagents/reagent_containers/syringes.dm
> +			user.visible_message(SPAN_WARNING("[user] injects [target] with the syringe!"),SPAN_NOTICE("You inject [trans] units of the solution. The syringe now contains [src.reagents.total_volume] units."),
```suggestion
			user.visible_message(SPAN_WARNING("[user] injects [target] with \the [src]!"),SPAN_NOTICE("You inject [trans] units of the solution. \The [src] now contains [src.reagents.total_volume] units."),2)
```

2022-02-25 11:36 UTC, NonQueueingMatt approved these changes

2022-03-01 15:26 UTC, Casper3667 approved these changes

2022-03-01 16:09 UTC, merged