Adds new accessory and beret options to the Tajara loadout
Aurorastation/Aurora.3 pull request #13310
Opened 2022-03-03 16:48 UTC by Alberyk

This pr adds some accessories and berets to represent some tajaran organizations and their supporters.

2022-03-03 16:51 UTC, SleepyGemmy approved these changes
code looks fine. grammar looks fine.

2022-03-03 17:04 UTC, Arrow768 approved these changes

2022-03-03 18:49 UTC, Greenjoe12345 commented on code/modules/clothing/head/xenos/tajara.dm
> +	desc = "A formal black beret with a golden band. This is worn by members of the NKA naval officer corps. These are prised in the New Kingdom thanks to the Navy's popularity."
prised > prized

2022-03-03 19:10 UTC, NonQueueingMatt approved these changes

2022-03-03 19:10 UTC, NonQueueingMatt commented on code/modules/clothing/head/xenos/tajara.dm
> +	desc = "A formal black beret with a golden band. This is worn by members of the NKA naval officer corps. These are prised in the New Kingdom thanks to the Navy's popularity."
```suggestion
	desc = "A formal black beret with a golden band. This is worn by members of the NKA naval officer corps. These are prized in the New Kingdom thanks to the Navy's popularity."
```

2022-03-03 19:10 UTC, NonQueueingMatt commented on code/modules/clothing/under/accessories/xeno/tajara.dm
> +	desc = "Given to all members of the Hro'rammad tank corps is this sun pin. It is considered a symbol of how the tanker corps is the wrath of the God S'rendarr. It's rays are sharp not \
```suggestion
	desc = "Given to all members of the Hro'rammad tank corps is this sun pin. It is considered a symbol of how the tanker corps is the wrath of the God S'rendarr. Its rays are sharp not \
```

2022-03-03 19:10 UTC, NonQueueingMatt commented on code/modules/clothing/under/accessories/xeno/tajara.dm
> +	desc = "A pin of the Adhomaian Blue Party. This symbol is a white hoe on a blue background representing the party's dedication to environmentalism and ruralism."
```suggestion
	desc = "A pin of the Adhomian Blue Party. This symbol is a white hoe on a blue background representing the party's dedication to environmentalism and ruralism."
```

2022-03-03 19:10 UTC, NonQueueingMatt commented on code/modules/clothing/under/accessories/xeno/tajara.dm
> +	desc = "A pin of the Free Tajaran's People Party. The two white rifles represent the party's fervor in crushing the two ideological enemies of the Tajara: Royalism and Hadiism. "
```suggestion
	desc = "A pin of the Free Tajaran's People Party. The two white rifles represent the party's fervor in crushing the two ideological enemies of the Tajara: Royalism and Hadiism."
```

2022-03-04 02:19 UTC, SleepyGemmy requested changes

2022-03-04 02:19 UTC, SleepyGemmy commented on code/modules/client/preference_setup/loadout/loadout_xeno/tajara.dm
> +	card["adhomaian blue party pin"] = /obj/item/clothing/accessory/tajaran/abparty_pin
```suggestion
	card["adhomian blue party pin"] = /obj/item/clothing/accessory/tajaran/abparty_pin
```

2022-03-06 16:52 UTC, merged