The Crate Animatening, A.K.A. I hate Crate Trigonometry
Aurorastation/Aurora.3 pull request #13339
Opened 2022-03-06 18:40 UTC by alsoandanswer

Reliant on Funky Yog Animation PR and Crate Refactening PR.

Also resprites the crates to 3/4, because I hate crate math. See attached.
![dreamseeker_tkdu4DdQU8](https://user-images.githubusercontent.com/42310821/156937310-3e7c3829-d9b9-4e76-8618-1c7a0cb2fe72.gif)

Anyway, here's the real thing.
![dreamseeker_Wafv5IkdP7](https://user-images.githubusercontent.com/42310821/156937320-689ae580-260e-4490-91a3-cff13ec2a161.gif)

Also, fixed up loot crate random icon stuff. Should work better now.

2022-03-07 12:47 UTC, alsoandanswer commented
!review

2022-03-19 13:57 UTC, NonQueueingMatt approved these changes
Has been testmerged for a few weeks now, works fine.

2022-04-16 19:04 UTC, JohnWildkins requested changes
see unit tests

2022-04-17 02:04 UTC, JohnWildkins requested changes

2022-04-17 02:04 UTC, JohnWildkins commented on code/game/objects/structures/crates_lockers/closets/secure/security.dm
>  	name = "wall locker"
no animation

2022-04-17 02:19 UTC, alsoandanswer commented on code/game/objects/structures/crates_lockers/crates.dm
>  /obj/structure/closet/crate/large
intentional

anything with door_anim_time = 0 has no animation

2022-04-17 02:43 UTC, JohnWildkins approved these changes

2022-04-30 05:04 UTC, merged