Autodrobe doesn't remove Vaurca mandible mask from face
Aurorastation/Aurora.3 pull request #13367
Opened 2022-03-10 21:58 UTC by mikomyazaki

Partially fixes #3505 - Swapping to your mandible mask won't be removed by the autodrobe anymore and thus make you start suffocating without you realizing.

Not sure how to make the default mask get swapped out for this one, because the species preequip needs to happen before the job preequip in `/datum/job/proc/pre_equip`.

Vaurca still get a bit poisoned if this isn't done *instantaneously* though.

2022-03-10 21:58 UTC, mikomyazaki commented
!review

2022-03-12 14:04 UTC, NonQueueingMatt requested changes

2022-03-12 14:04 UTC, NonQueueingMatt commented on aurorastation.dme
> +#include "_maps\aurora.dm"
dme moment

2022-03-12 21:17 UTC, NonQueueingMatt approved these changes

2022-03-12 21:23 UTC, merged