Removes Kathira's custom items
Aurorastation/Aurora.3 pull request #13391
Opened 2022-03-15 23:15 UTC by Casper3667

As Kathira is no longer a playable character, the items no longer serve a purpose.

I would like to specifically request for the sprites to **not** be reused by others as they were custom made for her.

2022-03-15 23:18 UTC, Casper3667 commented
!review

2022-03-15 23:21 UTC, alsoandanswer requested changes
I think there's a bunch of unique coat rack sprites you have to remove too, I think.

2022-03-16 01:26 UTC, alsoandanswer approved these changes

2022-03-18 15:35 UTC, NonQueueingMatt approved these changes

2022-03-19 01:39 UTC, merged