Thanos Snapping
Aurorastation/Aurora.3 pull request #13406
Opened 2022-03-19 07:18 UTC by alsoandanswer

Adds new dust animation and effects.
![dreamseeker_qGREm6F8Nl](https://user-images.githubusercontent.com/42310821/159111715-c71c9b6a-5b22-4ffc-a6fc-0d367a075df6.gif)

2022-03-19 08:14 UTC, alsoandanswer commented
!review

2022-03-19 13:40 UTC, NonQueueingMatt requested changes

2022-03-19 13:40 UTC, NonQueueingMatt commented on code/modules/admin/verbs/randomverbs.dm
> +		return
This check should be earlier.

2022-04-16 19:01 UTC, JohnWildkins approved these changes

2022-04-16 19:10 UTC, merged