Adds Yanna Trevidic's custom item
Aurorastation/Aurora.3 pull request #13410
Opened 2022-03-21 08:08 UTC by feartheblackout

adds the custom item approved hither: https://forums.aurorastation.org/topic/17006-yanna-trevidics-techno-conglomerate-cr-dress

definitely shitcode but i was at least able to get it working whenever it can be reviewed :)

2022-03-21 08:09 UTC, feartheblackout commented
!review

2022-03-24 14:47 UTC, NonQueueingMatt approved these changes

2022-03-24 14:47 UTC, NonQueueingMatt commented on code/modules/customitems/item_defines.dm
> +	.=..()
```suggestion
	. = ..()
```

2022-03-24 14:47 UTC, NonQueueingMatt commented on code/modules/customitems/item_defines.dm
> +	choose_setting(usr)
Add an use_check_and_message here.

2022-03-24 14:47 UTC, NonQueueingMatt requested changes
whoops was not meant to be an approval

2022-03-30 13:00 UTC, mikomyazaki commented
The icon file appears to contain one blank icon.

2022-03-30 13:00 UTC, mikomyazaki requested changes
The icon file appears to be blank.

2022-03-30 20:32 UTC, feartheblackout commented
oookay no idea why that keeps happening

2022-04-11 21:25 UTC, feartheblackout commented
haven't forgotten about this. just haven't been motivated to readd the icons after losing them twice sorry

2022-04-18 06:11 UTC, feartheblackout commented
sorry for the wait, ready for review now

2022-04-21 09:02 UTC, NonQueueingMatt approved these changes

2022-04-21 11:47 UTC, mikomyazaki approved these changes

2022-04-23 13:53 UTC, merged