Danse's Third Party Ships: Part 1, the Southern Fleet Administration
Aurorastation/Aurora.3 pull request #13456
Opened 2022-04-11 04:28 UTC by TheDanseMacabre

Cleared with the Human lore team. The idea is that this is a neutral/wildcard SFA ship that escaped destruction by fleeing to Biesel, but now doesn't know what to do.

2022-04-11 04:30 UTC, TheDanseMacabre commented
!review

2022-04-11 14:51 UTC, NonQueueingMatt requested changes

2022-04-11 14:51 UTC, NonQueueingMatt commented on maps/away/ships/sol.dm
> +/obj/effect/shuttle_landmark/sfa_shuttle/hangar
Add `movable_flags = MOVABLE_FLAG_EFFECTMOVE` to this landmark.

2022-04-12 21:35 UTC, TheDanseMacabre commented
100% complete and ready for immediate speedmerge.

2022-04-14 22:04 UTC, Alberyk approved these changes

2022-04-16 13:35 UTC, NonQueueingMatt approved these changes
The EE ship MAY need an antag type assigned to the spawners. We'll see how it goes.

2022-04-16 13:39 UTC, merged