Optimize playsound, starlight, and visualnet generation
Aurorastation/Aurora.3 pull request #13540
Opened 2022-04-16 17:31 UTC by JohnWildkins

should maybe possibly help init time and also maybe possibly kill some lag maybe???
changes:
  - bugfix: "Starlight module no longer attempts to generate lights on turfs that haven't initialized."
  - refactor: "Sounds and messages via sensitive hearing were optimized to no longer rely on expensive recursive checks."
  - refactor: "Visualnets no longer attempt to update their visibility chunks prior to game start."

2022-04-16 17:31 UTC, JohnWildkins commented
!review

2022-04-16 20:50 UTC, NonQueueingMatt approved these changes

2022-04-17 01:08 UTC, alsoandanswer approved these changes

2022-04-17 04:59 UTC, mikomyazaki requested changes
Can we just remove `get_mobs_or_objects_in_view` ? Change `get_mobs_or_objects_in_view_fast` to that proc name and let it be gone forever?

2022-04-17 16:58 UTC, mikomyazaki approved these changes

2022-04-19 17:35 UTC, merged