Nasira custom item
Aurorastation/Aurora.3 pull request #13588
Opened 2022-04-19 22:09 UTC by Jaraci

See title. Forum thread here: [https://forums.aurorastation.org/topic/17030-nasira-nahnikhs-incense-burner/#comment-155664](url)

2022-04-20 19:51 UTC, NonQueueingMatt commented
!review

2022-04-23 03:06 UTC, Alberyk approved these changes

2022-04-29 19:00 UTC, JohnWildkins requested changes

2022-04-29 19:00 UTC, JohnWildkins commented on code/modules/customitems/item_defines.dm
> +/obj/item/fluff/nasira_burner/proc/light(var/lighting_text = "[usr] lights \the [name].")
```suggestion
/obj/item/fluff/nasira_burner/proc/light(var/lighting_text)
```
Just leave this undefined, using [usr] in a place that you don't need to should be avoided

2022-04-29 19:00 UTC, JohnWildkins commented on code/modules/customitems/item_defines.dm
> +		T.visible_message(SPAN_NOTICE(lighting_text))
```suggestion
		if(lighting_text)
			var/turf/T = get_turf(src)
			T.visible_message(SPAN_NOTICE(lighting_text))
```

2022-04-29 19:00 UTC, JohnWildkins commented on code/modules/customitems/item_defines.dm
> +		T.visible_message(SPAN_NOTICE("[usr] extinguishes \the [src]."))
```suggestion
		T.visible_message(SPAN_NOTICE("[user] extinguishes \the [src]."))
```
Don't use `usr` if you can avoid it

2022-04-29 19:26 UTC, JohnWildkins approved these changes

2022-04-30 21:21 UTC, merged