Removes the EE ship.
Aurorastation/Aurora.3 pull request #13581
Opened 2022-04-19 09:28 UTC by NonQueueingMatt

As agreed between Danse and the maintainers, any hostile-leaning offmap ships will have to wait until a better framework is coded and they are integrated into it.

2022-04-19 09:28 UTC, NonQueueingMatt commented
!review

2022-04-19 09:29 UTC, NonQueueingMatt commented
!review

2022-04-19 11:37 UTC, mikomyazaki requested changes
Gotta delete the access datum
```/var/const/access_ee_spy_ship = 205
/datum/access/ee_spy_ship
	id = access_ee_spy_ship
	access_type = ACCESS_TYPE_CENTCOM```
	
	And the stuff in the `map_shuttles` list.

2022-04-19 11:58 UTC, mikomyazaki approved these changes

2022-04-19 21:59 UTC, JohnWildkins approved these changes

2022-04-19 22:01 UTC, JohnWildkins approved these changes

2022-04-19 22:01 UTC, JohnWildkins commented on maps/away/ships/corporate_ship_ghostroles.dm
> -	access = list(access_orion_express_ship, access_external_airlocks)
don't delete this line

2022-04-19 22:32 UTC, Ben10083 commented on maps/away/ships/corporate_ship_ghostroles.dm
> -	access = list(access_orion_express_ship, access_external_airlocks)
did you mean to approve this?

2022-04-22 09:26 UTC, NonQueueingMatt commented
unnecessary

2022-04-22 09:26 UTC, closed without merging