New SFA ship and detailed shiplore.
Aurorastation/Aurora.3 pull request #13596
Opened 2022-04-20 06:09 UTC by TheDanseMacabre

What it says up there.

2022-04-20 06:14 UTC, TheDanseMacabre commented
!review

2022-04-20 07:07 UTC, Caelphon commented
Danse approached me, and I gave my authorisation for these to be merged if there are any worries.

2022-04-20 16:12 UTC, NonQueueingMatt requested changes

2022-04-20 16:12 UTC, NonQueueingMatt commented on maps/away/ships/sol_ship_ghostroles.dm
> +	max_count = 2
Undocumented.

2022-04-20 19:09 UTC, TheDanseMacabre commented on maps/away/ships/sol_ship_ghostroles.dm
> +	max_count = 2
Slipped my mind

2022-04-23 03:06 UTC, Alberyk approved these changes

2022-04-24 14:16 UTC, NonQueueingMatt approved these changes

2022-04-24 14:19 UTC, merged