Adds a way for Skrell to pull non-psionics into the Srom.
Aurorastation/Aurora.3 pull request #13628
Opened 2022-04-23 12:07 UTC by NonQueueingMatt

As per title. Requested by the Skrell team.

2022-04-23 12:07 UTC, NonQueueingMatt commented
!review

2022-04-23 12:42 UTC, SleepyGemmy commented on code/modules/shareddream/dream_entry.dm
> +				adjustBrainLoss(10)
does this heal naturally?

2022-04-23 13:21 UTC, NonQueueingMatt commented on code/modules/shareddream/dream_entry.dm
> +				adjustBrainLoss(10)
yes

2022-04-23 14:02 UTC, RyverStyx approved these changes

2022-05-01 00:45 UTC, JohnWildkins approved these changes

2022-05-04 18:36 UTC, Llywelwyn requested changes
Srom exit announcement was deleted erroneously when fixing a merge conflict, I think.

2022-05-04 18:36 UTC, Llywelwyn commented on code/modules/shareddream/dream_entry.dm
> -				to_chat(psi.owner, SPAN_CULT("You feel the activity of Srom decrease."))
I think these lines were deleted by mistake - should probably be moved to 54 where the admin msg is

2022-05-10 18:16 UTC, mikomyazaki commented on code/modules/shareddream/dream_entry.dm
> +				if(can_commune() || (!can_commune() && srom_pulled_by))
```suggestion
				if(can_commune() || srom_pulled_by)
```

Logically we only get to the second part if can_commune is false, don't need to check it again.

2022-05-10 19:15 UTC, NonQueueingMatt commented on code/modules/shareddream/dream_entry.dm
> +					if(ishuman(victim) && !isSynthetic(victim) && victim.is_psi_pingable())
srom pull shouldn't work on synths even if they have the augment, yeah

2022-05-11 00:41 UTC, mikomyazaki approved these changes

2022-05-11 00:46 UTC, merged