Distinguish Between Service and Civilian on Crew Manifest
Aurorastation/Aurora.3 pull request #13670
Opened 2022-04-25 00:16 UTC by SleepyGemmy

this PR makes a distinguishment between service and civilian, i.e. assistants, off-duty crewmembers and passengers now show up under a "Civilian" tab instead of "Service", where they don't fit since they're not service personnel.

2022-04-25 00:18 UTC, SleepyGemmy commented
!review

2022-04-26 13:04 UTC, SleepyGemmy commented
will have to recompile vue and put it in this PR.

2022-05-01 23:33 UTC, NonQueueingMatt requested changes
Why are there changed colors in banjob.dm? Document that in the cl.

2022-05-06 06:11 UTC, JohnWildkins approved these changes

2022-05-06 12:27 UTC, merged