Small tweak to the thruster piping.
Aurorastation/Aurora.3 pull request #13687
Opened 2022-04-26 18:58 UTC by Leudoberct1

Currently, at roundstart, the port nacelle begins with cold phoron being pumped directly into the thrusters, and the starboard nacelle starts with a regulator open to the thruster, meaning that if you mix it as if using the burn chamber (as is the normal procedure), it is being sent to the starboard thrusters before you can ignite it.

This change will deactivate both regulators on the starboard and port nacelles, and also change the valves present to be predisposed towards using the burn chamber provided for better fuelling of the thrusters.

Pictures of the changes:

Port nacelle - https://i.imgur.com/kyTfgnw.png
Starboard nacelle - https://i.imgur.com/cxolDiO.png

2022-04-26 19:05 UTC, Leudoberct1 commented
!review

2022-04-26 19:10 UTC, mikomyazaki approved these changes
I don't disagree with this PR. But so that maintainers have the full picture:
- When I remapped the thruster piping pre-launch I left one of them filling automatically so that the crew could have at least _some_ ability to move the ship slowly if they had no atmospherics-capable personnel. This PR will mean that the horizon thrusters have zero thrust unless an engineer turns them on (which is probably fine?).

2022-04-26 19:41 UTC, Leudoberct1 commented
To follow up to Myazaki's comment, while it does provide half of the thrusters with a supply of cold phoron, this is an extremely small amount of acceleration for the Horizon- to the point where you'd be having to click at least five times, if not more, to reach even 1 gm/h (Which is like one tile per two minutes. Slow.)

Typically, bridge officers will not move the ship anyways unless there is an Engineer present- the thrusters consume power as well, and if there is no Engineering to have set up the reactor, then the bridge crew are very unlikely to be moving the ship anyways. If Engineering are just failing to turn the thrusters on despite being present, well... that can be resolved IC.

2022-05-01 00:53 UTC, JohnWildkins approved these changes

2022-05-01 19:37 UTC, Arrow768 requested changes
When making changes we also have to account for low-pop when there are few or no engineers.
In these cases the existing setup is useful, as it allows some movement (even if it is very slow).

With that in mind:
* Is it possible to provide the bridge crew with a "button" (be that a physical button or part of the thruster control program) that can remotely enable the relevant pumps/valves to direct gas towards the thrusters?

Marking as DNM until that question is resolved.

2022-05-02 17:19 UTC, Leudoberct1 commented
> 

After testing, it doesn't seem like buttons are capable of altering the state of the digital valve. It does have a frequency value, which I attempted to test with a remote signaler, but also to no effect. So in short, no, it cannot.

However, should a shift come around where there is no Engineering at all to be able to set up the thrusters, it's going to be lowpop, with the engine not even being set up- meaning that the Horizon moving isn't going to be wanted in the first place, due to the power issues that would cause the ship to end up drifting if movement was attempted. In addition to this, the Horizon does not NEED to move at all, really- the mining shuttle and Intrepid can generally get wherever they need to and back with the fuel provided at roundstart. The moving of the Horizon is usually done just to make the journey for said shuttles a little bit smaller. Miners would still be able to function just fine.

2022-05-03 07:11 UTC, merged