Adds long variations of algae, refactors headtail cloths
Aurorastation/Aurora.3 pull request #13717
Opened 2022-04-29 06:40 UTC by Llywelwyn

rscadd: "Added variations to Skrell algae loadout items for longer headtails."
rscadd: "Made Skrell headtail clothes recolourable instead of a set of fixed colours."

made headgear use subtypes properly in the process, and made variations use recolouring instead of having like 58 duplicate sprites for different versions

![image](https://user-images.githubusercontent.com/82828093/165895653-6cc67be9-d467-4075-b28f-4b87ca9cfb08.png)

2022-04-29 06:53 UTC, Llywelwyn commented
!review

2022-04-29 11:50 UTC, RyverStyx approved these changes

2022-04-30 23:08 UTC, Alberyk approved these changes

2022-05-01 01:25 UTC, JohnWildkins approved these changes

2022-05-01 01:29 UTC, SleepyGemmy requested changes

2022-05-01 01:29 UTC, SleepyGemmy commented on code/modules/client/preference_setup/loadout/loadout_xeno/skrell.dm
> +	algae["long glowing algae(dots)"] = /obj/item/clothing/ears/skrell/goop/long
```suggestion
	algae["long glowing algae, dots"] = /obj/item/clothing/ears/skrell/goop/long
```

2022-05-01 01:29 UTC, SleepyGemmy commented on code/modules/client/preference_setup/loadout/loadout_xeno/skrell.dm
>  	algae["glowing algae(dots)"] = /obj/item/clothing/ears/skrell/goop
```suggestion
	algae["glowing algae, dots"] = /obj/item/clothing/ears/skrell/goop
```

2022-05-01 01:29 UTC, SleepyGemmy commented on code/modules/client/preference_setup/loadout/loadout_xeno/skrell.dm
>  	algae["glowing algae(stripes)"] = /obj/item/clothing/ears/skrell/goop/stripes
```suggestion
	algae["glowing algae, stripes"] = /obj/item/clothing/ears/skrell/goop/stripes
```

2022-05-01 01:29 UTC, SleepyGemmy commented on code/modules/client/preference_setup/loadout/loadout_xeno/skrell.dm
> +	algae["long glowing algae(stripes)"] = /obj/item/clothing/ears/skrell/goop/stripes/long
```suggestion
	algae["long glowing algae, stripes"] = /obj/item/clothing/ears/skrell/goop/stripes/long
```

2022-05-01 01:29 UTC, SleepyGemmy commented on code/modules/client/preference_setup/loadout/loadout_xeno/skrell.dm
>  	algae["glowing algae(circles)"] = /obj/item/clothing/ears/skrell/goop/circles
```suggestion
	algae["glowing algae, circles"] = /obj/item/clothing/ears/skrell/goop/circles
```

2022-05-01 01:29 UTC, SleepyGemmy commented on code/modules/client/preference_setup/loadout/loadout_xeno/skrell.dm
> +	algae["long glowing algae(circles)"] = /obj/item/clothing/ears/skrell/goop/circles/long
```suggestion
	algae["long glowing algae, circles"] = /obj/item/clothing/ears/skrell/goop/circles/long
```

2022-05-01 01:48 UTC, Llywelwyn commented
failed test is from recurring bug in master, not from pr, im 99.9% sure. rerunning test should fix

2022-05-02 10:01 UTC, merged