Adds specific heat value to Ambrosia Extract
Aurorastation/Aurora.3 pull request #13729
Opened 2022-04-30 07:33 UTC by Llywelwyn

lord only knows what ambrosia extract is supposed to be irl, but this is close enough to every other value it should be fine. i doubt it matters specifically how fast liquid ambrosia heats up.

fixes #13618

2022-04-30 07:33 UTC, Llywelwyn commented
!review

2022-04-30 07:35 UTC, Llywelwyn commented
!bugfix

2022-04-30 20:32 UTC, Arrow768 requested changes
You need to add a changelog.
(backend or tweak tag should fit)

2022-05-01 00:51 UTC, JohnWildkins approved these changes

2022-05-01 14:38 UTC, Arrow768 approved these changes

2022-05-01 14:39 UTC, merged