Implemented a Pen Augment
Aurorastation/Aurora.3 pull request #13797
Opened 2022-05-06 14:25 UTC by Ben10083

Title

A new pen augment which can change color and use cursive.

2022-05-06 14:25 UTC, Ben10083 commented
!review

2022-05-10 17:11 UTC, mikomyazaki requested changes
Also it is currently possible to change the hand the pen is in, if you click on it with the other hand while the pen is extended.

2022-05-10 17:11 UTC, mikomyazaki commented on code/modules/client/preference_setup/loadout/loadout_augments.dm
> +/datum/gear/augment/tool/pen
To follow the pattern of the other `/datum/gear/augment`s this should be `/datum/gear/augment/pen`.

2022-05-10 17:11 UTC, mikomyazaki commented on code/modules/organs/subtypes/augment.dm
> +/obj/item/organ/internal/augment/tool/pen
This type will have `parent_organ = BP_CHEST` due to not overriding that from `/obj/item/organ/internal/augment`

2022-05-10 17:11 UTC, mikomyazaki commented on code/modules/paperwork/pen.dm
> +	name = "Integrated pen"
```suggestion
	name = "integrated pen"
```

2022-05-10 17:38 UTC, Ben10083 commented
> Also it is currently possible to change the hand the pen is in, if you click on it with the other hand while the pen is extended.

Turns out this issue extends to all relevant augments. An issue report has been made(#13878)

2022-05-10 18:19 UTC, mikomyazaki approved these changes

2022-05-12 09:25 UTC, NonQueueingMatt requested changes

2022-05-12 09:25 UTC, NonQueueingMatt commented on code/modules/paperwork/paper.dm
>  			var/obj/item/pen/fountain/f = i
This is not necessarily a fountain pen anymore.

2022-05-12 19:15 UTC, Arrow768 approved these changes

2022-05-12 19:17 UTC, merged