Changes TCFL active service card to reservist in loadout
Aurorastation/Aurora.3 pull request #13815
Opened 2022-05-07 04:34 UTC by feartheblackout

As discussed in the relay, anyone traveling abroad on the Horizon would be a reservist, not active duty. This adds a reservist card and makes it the default in loadout.

2022-05-07 04:35 UTC, feartheblackout commented
!review

2022-05-07 04:51 UTC, alsoandanswer approved these changes

2022-05-07 16:08 UTC, Ben10083 requested changes
You need a changelog

2022-05-08 12:04 UTC, Arrow768 approved these changes

2022-05-08 12:04 UTC, Arrow768 commented
You still need to add a changelog

2022-05-10 03:55 UTC, Ben10083 approved these changes

2022-05-10 10:58 UTC, merged