New Hair and Neck Bows and Ribbons
Aurorastation/Aurora.3 pull request #13848
Opened 2022-05-09 13:49 UTC by SleepyGemmy

this PR adds an alternative hair bow, a neck bow, and a neck ribbon. it also makes these and the bowtie into contained sprites.

2022-05-09 15:04 UTC, KingOfThePing commented
anime larp

2022-05-09 15:07 UTC, KingOfThePing requested changes

2022-05-09 18:17 UTC, SleepyGemmy commented on code/modules/clothing/head/misc.dm
> +	desc = "You aren't supposed to see this."
parent item.

2022-08-16 19:30 UTC, SleepyGemmy commented
!review

2022-08-27 18:25 UTC, Arrow768 approved these changes

2022-11-01 14:16 UTC, SleepyGemmy commented
PR is waiting for reviews, it is **NOT ABANDONED**.

2022-12-13 16:24 UTC, JohnWildkins approved these changes

2022-12-13 16:28 UTC, merged