Outfit and Access Spring Cleaning
Aurorastation/Aurora.3 pull request #13876
Opened 2022-05-10 17:06 UTC by JohnWildkins

changes:
  - bugfix: "Fixed secure crates starting unlocked."
  - bugfix: "Secure hydroponics crates now require either Hydroponics or Xenobiology access."
  - bugfix: "Xenobotanists now spawn with the correct access and job outfit."
  - bugfix: "Machinists, PMCG medical staff, and Zavod/Zeng-Hu scientists now start with their proper labcoats."
  - bugfix: "Idris gardeners and janitors start with aprons once more."
  - bugfix: "Idris gardener uniform now has proper directional sprites."
  - bugfix: "Security cadets now start with their appropriate hazard vest again."

Fixes #13869
Fixes #11788

2022-05-10 17:06 UTC, JohnWildkins commented
!review

2022-05-10 19:30 UTC, SleepyGemmy requested changes

2022-05-10 19:30 UTC, SleepyGemmy commented on code/modules/clothing/suits/labcoat.dm
> +	name = "PMCG security labcoat"
```suggestion
	name = "\improper PMCG security labcoat"
```

2022-05-10 19:30 UTC, SleepyGemmy commented on code/modules/clothing/suits/labcoat.dm
> +	name = "PMCG medical labcoat"
```suggestion
	name = "\improper PMCG medical labcoat"
```

2022-05-10 19:30 UTC, SleepyGemmy commented on html/changelogs/johnwildkins-zengfix.yml
> +  - bugfix: "Idris gardeners and janitors start with aprons once more."
```suggestion
  - bugfix: "Idris gardeners start with aprons once more."
```
janitors never had aprons.

2022-05-10 22:31 UTC, Alberyk approved these changes

2022-05-11 09:05 UTC, SleepyGemmy approved these changes

2022-05-11 17:14 UTC, merged