Fixes the Brig Communal Chute
Aurorastation/Aurora.3 pull request #13870
Opened 2022-05-10 12:46 UTC by SleepyGemmy

fixes #13865.

2022-05-10 12:50 UTC, SleepyGemmy commented
!review

2022-05-10 12:50 UTC, SleepyGemmy commented
!bugfix

2022-05-10 17:54 UTC, mikomyazaki requested changes
Can we keep the extra tile for the stuff to land on? It's weird for it to come out of the chute and land on top of the chute.

2022-05-10 22:32 UTC, Alberyk approved these changes

2022-05-11 00:40 UTC, mikomyazaki approved these changes

2022-05-11 00:46 UTC, merged