New Perfectly Normal Away Site
Aurorastation/Aurora.3 pull request #13882
Opened 2022-05-10 19:28 UTC by SleepyWolfe

a perfectly normal asteroid with a hangar, and a few mining materials. great place to take a rest on that long ride away from the Horizon, or as a 3rd party ship!
also a first attempt at doing this (thank you danse)

2022-05-10 19:46 UTC, SleepyGemmy requested changes
![image](https://user-images.githubusercontent.com/99297919/167709754-3f327701-15b7-4193-b82c-0a4e3fe17918.png)
cute addition, but i don't think players should leave references to themselves in their maps.

2022-05-10 19:53 UTC, SleepyWolfe commented
> ![image](https://user-images.githubusercontent.com/99297919/167709754-3f327701-15b7-4193-b82c-0a4e3fe17918.png) cute addition, but i don't think players should leave references to themselves in their maps.

it will have a small rock collapse, but won't be forgotten in my eyes...

2022-05-10 19:57 UTC, SleepyWolfe commented
!review

2022-05-15 14:18 UTC, NonQueueingMatt approved these changes

2022-05-19 20:35 UTC, SleepyGemmy approved these changes

2022-05-22 17:24 UTC, JohnWildkins approved these changes

2022-05-22 17:28 UTC, merged