Fixes outdated Consular directives
Aurorastation/Aurora.3 pull request #13916
Opened 2022-05-13 10:45 UTC by connorjg1

Consular directives were outdated and mentioned NanoTrasen/Station as the primary megacorp/location. This fixes that by changing it to the SCC and Horizon respectively.

2022-05-13 10:46 UTC, connorjg1 commented
!review

2022-05-13 11:05 UTC, mikomyazaki requested changes
Would prefer if you could use the `current_map.name`, `current_map.boss_name` etc. Vars instead of writing the names in directly. Check the horizon map definition for these.

2022-05-14 07:27 UTC, connorjg1 commented
I'm sure not why I'm getting an error message for the Vaurca objectives since I can't see anything wrong with it, but I'll try and solve it

2022-05-14 14:47 UTC, mikomyazaki requested changes

2022-05-14 14:47 UTC, mikomyazaki commented on code/modules/background/citizenship/citizenship.dm
> +			rep_objectives = pick("Collect evidence of the Stellar Corporate Conglomerate being unfair or oppressive against employees from [name], to be used as leverage in future diplomatic talks",
Missed a few.

2022-05-22 17:25 UTC, JohnWildkins approved these changes
address myazaki's review and fix conflicts and this is fine

2022-06-05 03:04 UTC, connorjg1 commented on code/modules/background/citizenship/citizenship.dm
> +			rep_objectives = pick("Collect evidence of the Stellar Corporate Conglomerate being unfair or oppressive against employees from [name], to be used as leverage in future diplomatic talks",
Addressed. I think that got them all.

2022-06-09 10:42 UTC, merged