Adds PLAYSOUND_IN
Aurorastation/Aurora.3 pull request #13938
Opened 2022-05-14 04:33 UTC by alsoandanswer

basically playsound after a amount of time has passed. simple 'nuff, i hope.
no need to changelog since this is backend thing

2022-05-14 04:34 UTC, alsoandanswer commented
!review

2022-05-14 12:05 UTC, SleepyGemmy commented on code/__defines/subsystem-defines.dm
> +#define PLAYSOUND_IN(source, soundin, vol, vary, extrarange, falloff, is_global, usepressure, environment, required_preference, required_asfx_toggles, frequency, time) addtimer(CALLBACK(src, /atom/.p
wouldn't it be better to have it be `PLAYSOUND_AFTER`? `PLAYSOUND_IN` sounds like its a input rather than a timer.

2022-05-22 10:40 UTC, NonQueueingMatt approved these changes

2022-05-22 17:30 UTC, JohnWildkins requested changes
please make this a proc instead because being a macro means you have to define every single argument every time which is awful

2022-05-22 22:20 UTC, closed without merging