The Last of the Lockers
Aurorastation/Aurora.3 pull request #13954
Opened 2022-05-15 12:22 UTC by alsoandanswer

- imageadd: "Improves sprites for wall lockers, fire extinguisher cabinets, fireaxe cabinet, critter crate and wall safe."

2022-05-15 12:22 UTC, alsoandanswer commented
!review

2022-05-22 10:40 UTC, NonQueueingMatt approved these changes

2022-05-22 17:40 UTC, JohnWildkins requested changes
Fire axe cabinet has its open/closed sprites switched
The extinguisher cabinet just flat out doesn't work in terms of overlays/animations

2022-05-23 05:21 UTC, alsoandanswer commented
> Fire axe cabinet has its open/closed sprites switched The extinguisher cabinet just flat out doesn't work in terms of overlays/animations

Addressed
![dreamseeker_etJB0JOLyr](https://user-images.githubusercontent.com/42310821/169748492-2d034633-3ed0-49ff-ab16-81fd3e54d83e.gif)

2022-05-24 13:49 UTC, JohnWildkins approved these changes

2022-05-24 16:56 UTC, merged