Implemented a Cyborg Analyzer Augment
Aurorastation/Aurora.3 pull request #13971
Opened 2022-05-16 04:05 UTC by Ben10083

Title

2022-05-16 04:05 UTC, Ben10083 commented
!review

2022-05-22 10:39 UTC, NonQueueingMatt requested changes
`cAnalyzer` is a bad path name because it doesn't actually tell someone what it is. It's an analyzer, yes, but that "c" could mean anything.

2022-05-22 10:39 UTC, NonQueueingMatt commented on code/modules/organs/subtypes/augment.dm
> +/obj/item/organ/internal/augment/tool/cAnalyzer
```suggestion
/obj/item/organ/internal/augment/tool/cyborg_analyzer
```

2022-05-22 10:39 UTC, NonQueueingMatt commented on code/modules/organs/subtypes/augment.dm
> +/obj/item/organ/internal/augment/tool/cAnalyzer/left
```suggestion
/obj/item/organ/internal/augment/tool/cyborg_analyzer/left
```

2022-05-22 10:39 UTC, NonQueueingMatt commented on code/__defines/mobs.dm
> +#define BP_AUG_CANALYZER    "retractable cyborg analyzer"
```suggestion
#define BP_AUG_CYBORG_ANALYZER    "retractable cyborg analyzer"
```

2022-05-22 10:39 UTC, NonQueueingMatt commented on code/modules/client/preference_setup/loadout/loadout_augments.dm
> +	path = /obj/item/organ/internal/augment/tool/cAnalyzer
```suggestion
	path = /obj/item/organ/internal/augment/tool/cyborg_analyzer
```

2022-05-22 10:39 UTC, NonQueueingMatt commented on code/modules/client/preference_setup/loadout/loadout_augments.dm
> +	augs["retractable cyborg analyzer, right hand"] = /obj/item/organ/internal/augment/tool/cAnalyzer
```suggestion
	augs["retractable cyborg analyzer, right hand"] = /obj/item/organ/internal/augment/tool/cyborg_analyzer
```

2022-05-22 10:39 UTC, NonQueueingMatt commented on code/modules/client/preference_setup/loadout/loadout_augments.dm
> +	augs["retractable cyborg analyzer, left hand"] = /obj/item/organ/internal/augment/tool/cAnalyzer/left
```suggestion
	augs["retractable cyborg analyzer, left hand"] = /obj/item/organ/internal/augment/tool/cyborg_analyzer/left
```

2022-05-22 10:39 UTC, NonQueueingMatt commented on code/modules/organs/subtypes/augment.dm
> +	organ_tag = BP_AUG_CANALYZER
```suggestion
	organ_tag = BP_AUG_CYBORG_ANALYZER
```

2022-05-22 15:32 UTC, Ben10083 commented
Requested changes committed and tested to ensure it still works.

2022-05-22 17:43 UTC, JohnWildkins approved these changes

2022-05-22 18:03 UTC, NonQueueingMatt approved these changes

2022-05-23 10:47 UTC, merged