Audioconsole and new music
Aurorastation/Aurora.3 pull request #13986
Opened 2022-05-17 03:47 UTC by TheDanseMacabre

See title. Also renames the jukebox from "space jukebox" to just "jukebox"

2022-05-17 03:50 UTC, TheDanseMacabre commented
!review

2022-05-17 03:50 UTC, SleepyGemmy approved these changes
based.

2022-05-17 03:51 UTC, SleepyGemmy commented on code/game/machinery/jukebox.dm
> +	anchored = 0
```suggestion
	anchored = FALSE
```

2022-05-17 04:07 UTC, alsoandanswer commented on code/game/machinery/jukebox.dm
> +/obj/machinery/media/jukebox/audioconsole/update_icon()
you added broken states, but didnt seem to include them here

2022-05-17 10:33 UTC, NonQueueingMatt requested changes
It looks like there are a bunch of errant white pixels on the top left in the animations? Check them over for me, please.

2022-05-17 10:34 UTC, NonQueueingMatt commented
![immagine](https://user-images.githubusercontent.com/13016572/168792090-ea441552-67e8-4b3a-bccf-461ced4546a6.png)

2022-05-17 20:22 UTC, TheDanseMacabre commented
> ![immagine](https://user-images.githubusercontent.com/13016572/168792090-ea441552-67e8-4b3a-bccf-461ced4546a6.png)
> 
> Same in the other animation.

I'm not really seeing these locally? Not sure why.

2022-05-19 21:25 UTC, Alberyk approved these changes

2022-05-20 09:13 UTC, NonQueueingMatt approved these changes

2022-05-20 09:28 UTC, merged