Skrell Tuux Changes and Additions
Aurorastation/Aurora.3 pull request #13992
Opened 2022-05-17 18:08 UTC by RyverStyx

![image](https://user-images.githubusercontent.com/31362902/168879007-ec4884e3-7af1-47ae-a2cb-65e45dc711fe.png)

2022-05-17 18:11 UTC, RyverStyx commented
!review

2022-05-22 10:35 UTC, NonQueueingMatt requested changes

2022-05-22 10:35 UTC, NonQueueingMatt commented on html/changelogs/tuux.yml
> +  - rscadd: "Adds more styles."
```suggestion
  - rscadd: "Adds more Skrell hair styles."
```

2022-05-22 10:35 UTC, NonQueueingMatt commented on html/changelogs/tuux.yml
> +  - tweak: "Changes names of existing styles to be uniform and descriptive."
```suggestion
  - tweak: "Changes names of existing Skrell styles to be uniform and descriptive."
```

2022-05-22 17:55 UTC, JohnWildkins approved these changes

2022-05-23 10:49 UTC, NonQueueingMatt approved these changes

2022-05-23 11:35 UTC, merged