"Lizard" sprite files renamed to "Unathi"
Aurorastation/Aurora.3 pull request #14002
Opened 2022-05-18 11:25 UTC by WickedCybs

Trying to quickly search up Unathi when I'm doing something for them only to remember the sprites for their appearance were under r_lizard was always annoying. Especially considering most stuff that's Unathi related is labelled as "Unathi."

I also renamed the "Sogtail" files within the Unathi tail dmi to "Unathtail"

2022-05-18 11:25 UTC, WickedCybs commented
!review

2022-05-18 11:55 UTC, SleepyGemmy requested changes

2022-05-18 11:55 UTC, SleepyGemmy commented on html/changelogs/wickedcybs_rename.yml
> +  - tweak: "Renamed the 'Lizard' sprite dmi's to 'Unathi'. This is an under the hood change that should not affect anything."
```suggestion
  - backend: "Renamed the 'Lizard' sprite dmi's to 'Unathi'. This is an under the hood change that should not affect anything."
```

2022-05-18 11:55 UTC, SleepyGemmy commented on code/modules/mob/living/carbon/human/species/station/unathi/unathi.dm
> +	tail = "unathtail"
```suggestion
	tail = "unathitail"
```

2022-05-18 11:55 UTC, SleepyGemmy commented on html/changelogs/wickedcybs_rename.yml
> +  - tweak: "The Unathil tail sprite files don't reference their old name of 'Soghun' anymore."
```suggestion
  - backend: "The Unathi tail sprite files don't reference their old name of 'Soghun' anymore."
```

2022-05-18 14:30 UTC, WickedCybs commented on code/modules/mob/living/carbon/human/species/station/unathi/unathi.dm
> +	tail = "unathtail"
Not really something I plan to do yeah.

2022-05-22 10:56 UTC, NonQueueingMatt approved these changes

2022-05-22 17:56 UTC, JohnWildkins approved these changes

2022-05-22 18:03 UTC, merged