Buffs Firelockers + Adds New Tool: The Rescue Axe
Aurorastation/Aurora.3 pull request #14006
Opened 2022-05-18 14:24 UTC by WickedCybs

I've ported the emergency forcing tool from Baystation, though here it has been renamed to the "rescue axe" as I feel that might be a more innately understandable name. It is a hand axe intended to be used to either pry open stuff or smash your way in via weak points like windows (which it deals its full damage to rather than just half). You can think of it as a crowbar with an axehand and pick at the top of it. 

It's supposed to be a piece of kit mainly used by engineering and those dealing with atmospheric issues like fires, so it has been put into the CE and atmos tech lockers along with fire closets. The engineering lockers also have the clear faced gas mask variants replacing the old classic full gas masks.

For the fire closets I've done a few things. Standard variants will have a small set of inflatables (one door, two walls) and "filled" variants have a slightly bigger set of inflatables (two doors, three walls). Medical's fire closet guarantees a ladder. The re-arrangement of the fire closets also had me take the chance to replace those old "classic" full gas masks in ss13 with the alternate version that has a clear view of the face. It fits the style of a firefighter far more I'd say.

![image](https://user-images.githubusercontent.com/52309324/169064656-bbcf131a-d7ff-47c5-9563-5e26a592ea1d.png)

2022-05-18 14:26 UTC, WickedCybs commented
!review

2022-05-18 14:49 UTC, SleepyGemmy requested changes

2022-05-18 14:54 UTC, SleepyGemmy commented
also, would it be possible to have the axe be red instead of blue? i can perform the necessary sprite changes in that case.

2022-05-19 08:32 UTC, WickedCybs commented
!wip

2022-05-19 08:32 UTC, WickedCybs commented on code/game/objects/structures/crates_lockers/closets/secure/engineering.dm
>  	new /obj/item/clothing/mask/gas(src)
Will consider it. Not entirely sure if I'll get anyone angry I took their masks away.

2022-05-19 08:33 UTC, WickedCybs commented
> also, would it be possible to have the axe be red instead of blue? i can perform the necessary sprite changes in that case.

Was discussed on discord but will say my answer here again. That's fie.

2022-05-19 08:37 UTC, WickedCybs commented
Made the PR a WIP for now, because when I get back to it the FR's need their closet changed so no rescue axe spawns in it. Other spawn points might need to be looked at too. That said, this is to be an uncommon item at best, bit rare at worst. I feel like overall players can be trusted with it and there's more than enough things around that do nearly the same or more than the amount of damage listed on the axe (12 force) which are publicly accessible to the crew.

Another thing is, I want to look into the tool doing double damage to doors too.

2022-05-22 10:57 UTC, NonQueueingMatt approved these changes
Not really sure about this being in every single fire locker, but I guess we can give it a try?

2022-05-22 17:57 UTC, JohnWildkins approved these changes

2022-05-23 12:41 UTC, WickedCybs commented
!review

2022-05-23 13:03 UTC, NonQueueingMatt approved these changes

2022-05-28 23:51 UTC, Arrow768 commented
I am sceptical about this, as it makes it extremely easy to smash down windows/grilles.
But I guess we´ll see how it goes.

2022-05-28 23:51 UTC, merged