Implements the Biesel Constitution
Aurorastation/Aurora.3 pull request #14016
Opened 2022-05-19 15:59 UTC by Ben10083

Title

Used the litanybook code to make a book for Biesel consulars to show around and praise.

WIP until I can get enough lines into the .txt file.

- [ ] Make a super awesome book
- [ ] Steal the tcfl pamphlet sprite and change it up a bit
- [ ] Fill out the .txt

2022-05-19 16:00 UTC, Ben10083 commented
!review

2022-05-19 16:00 UTC, Ben10083 commented
!wip

2022-05-22 10:58 UTC, NonQueueingMatt requested changes

2022-05-22 10:58 UTC, NonQueueingMatt commented on code/game/objects/items/devices/litanybook.dm
> +/obj/item/device/litanybook/biesel
If you are going to borrow litany book code, make the litany book mechanical functions into a generic class called `verse_book` or something, then make the litany book and this constitution into subtypes.

2022-05-22 17:59 UTC, JohnWildkins approved these changes

2022-05-23 13:26 UTC, NonQueueingMatt requested changes

2022-05-23 13:26 UTC, NonQueueingMatt commented on code/game/objects/items/devices/versebook.dm
>  	randomquip = file2list("ingame_manuals/dominia.txt")
This should not be here. It's done below in the tribunal book.

2022-06-02 18:29 UTC, Ben10083 commented
!review

2022-06-07 10:39 UTC, NonQueueingMatt requested changes

2022-06-07 10:39 UTC, NonQueueingMatt commented on code/game/objects/items/devices/versebook.dm
> +		q = quip
This quip variable looks entirely useless...? Why is it there?

2022-06-07 10:39 UTC, NonQueueingMatt commented on code/game/objects/items/devices/versebook.dm
> +	user.setClickCooldown(DEFAULT_ATTACK_COOLDOWN)
Stop the user from reading if randomquip is empty.

2022-06-07 15:27 UTC, NonQueueingMatt commented on code/game/objects/items/devices/versebook.dm
> +		to_chat(usr, SPAN_WARNING("You are already reading this book."))
```suggestion
		to_chat(user, SPAN_WARNING("You are already reading this book."))
```

2022-06-08 14:28 UTC, NonQueueingMatt approved these changes

2022-06-08 15:44 UTC, merged