Uniformity 2 : Electric Boogaloo
Aurorastation/Aurora.3 pull request #14041
Opened 2022-05-21 10:49 UTC by alsoandanswer

changes:
  - tweak: "Idris alt labcoat has big logo again."
<img width="109" alt="dreammaker_Ok2oNMppVD" src="https://user-images.githubusercontent.com/42310821/169648210-09601a06-a123-431d-b8a1-3f072b6227e5.png">
-72d028742fe2.png">
  - tweak: "Zeng-Hu labcoat highlights have been made more vibrant."
 <img width="217" alt="dreammaker_jB4kGCR3nu" src="https://user-images.githubusercontent.com/42310821/169648198-0877d6de-4af2-4cb2-829d
  - rscadd: "Adds surplus security uniforms. They're the old Aurora corporate uniforms, tweaked to match the new uniforms."
<img width="930" alt="dreammaker_iefImuE5ag" src="https://user-images.githubusercontent.com/42310821/169648181-fdefdcca-5312-4956-82e3-b47d1b2dadf8.png">
  - rscadd: "Adds, or re-adds, new hats and berets to match the old Aurora corporate uniforms."
  - tweak: "Collapses the faction hat selections to be neater. Please check your loadouts!"
  - tweak: "Undoes the swapping of officer and warden uniforms, and tweaks the other uniforms accordingly."
  - rscadd: "Zavodskoi scrubs made blacker, original black scrubs renamed to PMCG grey scrubs."

2022-05-21 10:50 UTC, alsoandanswer commented
!review

2022-05-21 14:20 UTC, RyverStyx commented
Why can't the Zeng-Hu lab coat be white instead of off-grey?

2022-05-21 20:46 UTC, alsoandanswer commented
> Why can't the Zeng-Hu lab coat be white instead of off-grey?

....What? All labcoats are the same color of white.

2022-05-21 22:08 UTC, Caelphon commented
It seems the clothes were reverted to Necropolis? Anyway, I’d greatly appreciate if it was instead rename to be Zavod or Zavodskoi. Thanks!

2022-05-22 05:13 UTC, alsoandanswer commented
> It seems the clothes were reverted to Necropolis? Anyway, I’d greatly appreciate if it was instead rename to be Zavod or Zavodskoi. Thanks!

Addressed

2022-05-22 05:16 UTC, alsoandanswer commented
!review

2022-05-23 10:51 UTC, NonQueueingMatt requested changes

2022-05-23 10:51 UTC, NonQueueingMatt commented on code/modules/client/preference_setup/loadout/loadout_factions.dm
> +	surpluspmc["surplus PMCG security uniform"] = /obj/item/clothing/under/surplus/pmc
These are EPMC uniforms, not PMCG. Rename the display name to be EPMC uniforms.

2022-06-09 10:42 UTC, NonQueueingMatt commented
Not relevant anymore because of the new PRs.

2022-06-09 10:42 UTC, closed without merging