Remaps TCFL ship + adds new docking arm
Aurorastation/Aurora.3 pull request #14087
Opened 2022-05-24 02:44 UTC by kyres1

Remaps the TCFL ship entirely. Overhauls a lot of its former sections and redoes the shuttle entirely. Also, adds one more spawn point for legionnaires, while removing the prisoner roles entirely. However, the brig is still there.

This affects the longevity of the shuttle and ship substantially by giving them static atmos containers of carbon dioxide, as well as spares in case an extra injection is needed. I'm willing to adjust these, though I'm not entirely sure why the stockpile was so low to begin with.

Plus, adds a new "docking arm" (seen below) where shuttles that are different shapes than a literal 5x9 rectangle can dock. This is to circumvent the hangars, though I'm sure smaller shuttles can easily still exist. 

![docking arm](https://user-images.githubusercontent.com/36868890/169937744-3c40b1dd-683f-4e93-a0fa-3ddf3c7f910a.png)

To-do : 

- [ ] Decimate the prisoner roles.

- [ ] changelog........................

![shipcomplete](https://user-images.githubusercontent.com/36868890/169936957-35216423-37a6-4186-a595-bf73ccf000c0.png)

2022-05-24 03:00 UTC, kyres1 commented
!review

2022-05-24 03:57 UTC, GrayRachnid commented
How does their new shuttle dock with the horizon? It looks too big for the hanger bays.

2022-05-24 04:51 UTC, kyres1 commented
> How does their new shuttle dock with the horizon? It looks too big for the hanger bays.
> 
> Edit: nevermind I see you added a thing on the horizon just for them. What's wrong with using the pre-existing docking arms? Edit2: You don't need 3 air cans on that docking arm. Two or 1 will suffice.

The pre-existing docking arms are occupied by much more frequent visitors (mercs, raiders etc.) and have awkward angles or are shoved up against a wall, pretty much.

2022-05-24 05:40 UTC, GrayRachnid commented
Deck 2
![image](https://user-images.githubusercontent.com/6613514/169956123-fadc6253-e87d-4b57-b7b6-67d6b336d83a.png)

Deck 3
![image](https://user-images.githubusercontent.com/6613514/169956151-493c6b54-39f6-403a-8aa0-d0360f44f3c7.png)

I feel like all 3 of these can either be widened by 1 tile or the TCFL can be doors can be made smaller by one. Keep in mind, the doors would be wide open on docking so people can just funnel through easily. It'd just be a 1x6 hall instead of 2x6.

I don't think Merc/Burglar docking should be a concern because there's like a total of 9 different entrances, including ones from space. Not to mention their shuttles can appear anywhere around the Horizon while TCFL is forced to dock somewhere. Adding a whole arm for this change feels excessive to me when there's 3 south-facing ones that can already accommodate them.

Also. Don't Merc/Burglar shuttles have their doors on the east? They wouldn't conflict.

2022-05-24 15:06 UTC, Ben10083 reviewed
![image](https://user-images.githubusercontent.com/91219575/170068855-7f377c99-f96e-4025-8e2f-13c718e2c9f9.png)
two mech rechargers but no mechs, it doesn't make too much sense to have two rechargers even if they had a mech however, perhaps replace one of them with something else like a cyborg recharger?

2022-05-24 15:07 UTC, Ben10083 requested changes
![image](https://user-images.githubusercontent.com/91219575/170069036-13f99d38-5dcd-4325-b4e2-746b6abd6d79.png)
These cyropods dont have a console, they won't put them into storage. Orion Express ship has consoles and you can see how they were used so you can add them here

2022-05-24 15:09 UTC, Ben10083 reviewed
![image](https://user-images.githubusercontent.com/91219575/170069590-42ceb62b-99c7-4625-b96b-24614ec9027a.png)
In case of a atmos breach at the airlock , this would vent a decent chunk of the ship, perhaps add a double glass airlock at the two tile wide entrance?

2022-05-24 15:10 UTC, Ben10083 commented
![image](https://user-images.githubusercontent.com/91219575/170070000-62c9307e-739a-47a1-9ff3-5513e7459642.png)
What is this room out of curiosity? what are those consoles for.

2022-05-24 15:15 UTC, Ben10083 requested changes
![image](https://user-images.githubusercontent.com/91219575/170070462-d3a34aec-9b2a-4435-9686-abddfa43be69.png)
I see what is the knife and what I am assuming the webbing, but hard for me to tell.

Prefect and legionnaires use pouches not webbing currently (however if you want to change that if people want that, thats whatever,) and if you want the Prefect's items to be given to them on the rack, you will have to update their backpack contents in the ghostroles.dm

2022-05-24 21:24 UTC, TheDanseMacabre commented
> ![image](https://user-images.githubusercontent.com/91219575/170070462-d3a34aec-9b2a-4435-9686-abddfa43be69.png) I see what is the knife and what I am assuming the webbing, but hard for me to tell.
> 
> Prefect and legionnaires use pouches not webbing currently (however if you want to change that if people want that, thats whatever,) and if you want the Prefect's items to be given to them on the rack, you will have to update their backpack contents in the ghostroles.dm

This is an energy shield.

2022-05-24 21:51 UTC, kyres1 commented
Shuttle changed. The docking arm no longer exists, the nav point was moved to deck 3 and now lands on top of the Horizon. Ben's changes are addressed as well, with exception of giving more guns to the TCFL.

2022-05-24 22:05 UTC, Ben10083 approved these changes

2022-05-24 22:06 UTC, Ben10083 commented on html/changelogs/kyres1-#14087.yml
> +  - maptweak: "Adds a new docking arm outside the Operations Lobby where big shuttles of different shapes can dock."
This has changed now right?

2022-05-24 22:06 UTC, Ben10083 commented on html/changelogs/kyres1-#14087.yml
> +  - maptweak: "Adds a new docking arm outside the Operations Lobby where big shuttles of different shapes can dock."
the docking arm, I mean.

2022-05-25 06:10 UTC, WickedCybs commented
> After reviewing the map the docking arm here ![image](https://user-images.githubusercontent.com/6613514/170089385-1127e49d-4d31-469a-8663-3881593169b8.png)
> 
> The one on the left, is unoccupied by any ship. I think you can either modify it or the TCFL ship. Hell, you can probably leave them both as they are and it'd still function.

The dock to the left is used by the merchant if it spawns.

2022-05-28 23:42 UTC, Arrow768 commented
I am not sure if adding yet another docking location is such a good idea.
Imho it would be better to expand the security checkpoint a bit, so the TCFL also docks "behind" the security checkpoint.

Long term we should reconsider how we handle docking with the horizon.

2022-05-29 01:46 UTC, kyres1 commented
![ILoveDocking](https://user-images.githubusercontent.com/36868890/170848653-d704aa93-3de0-4989-91e0-3e8d0f21c5a8.png)

Docking location adjusted to be here, rather than under cargo

2022-06-04 20:21 UTC, NonQueueingMatt approved these changes

2022-06-05 23:07 UTC, Alberyk approved these changes

2022-06-06 09:50 UTC, merged