Mechs check if unlocked when unlinking
Aurorastation/Aurora.3 pull request #14105
Opened 2022-05-25 04:21 UTC by Afya212

Added a child lock so you can no longer lock yourself out of your mech.
May or maynot done this before.

Mech must be in maintenance mode and unlocked.

2022-05-25 04:24 UTC, Afya212 commented
!review

2022-05-25 14:48 UTC, Ben10083 requested changes

2022-05-25 14:54 UTC, Ben10083 requested changes
This SHOULD allow the exo to say why it won't unlink, however do we really want hatch to be unlocked? If maintenance mode is on, they can just set a new leader.

2022-05-25 14:57 UTC, Ben10083 requested changes
Should work but make sure to check to ensure I properly overriden the old code with this.

2022-05-25 14:57 UTC, Ben10083 commented on code/modules/heavy_vehicle/mech_interaction.dm
>  			// unlink the leader to get a new one
```suggestion
			// unlink the leader to get a new one
			if(findtext(text, "unlink"))
				if(hatch_locked) // Can't lock yourself out
					say("Hatch locked, cannot unlink.")
					return
				if(!maintenance_protocols)
					say("Maintenance protocols must be engaged to unlink.")
					return
```

2022-05-25 15:01 UTC, Ben10083 requested changes
Needs some feedback to say why it doesn't unlink.

2022-05-25 22:51 UTC, Ben10083 approved these changes

2022-05-27 16:49 UTC, NonQueueingMatt approved these changes

2022-05-28 23:31 UTC, Arrow768 approved these changes

2022-05-28 23:46 UTC, merged