Auto-Compressor Buffs and Manual CPR Tweak
Aurorastation/Aurora.3 pull request #14116
Opened 2022-05-27 03:30 UTC by VisVirific

* Separates CPR into: Full CPR (Compressions + Mouth-to-Mouth), Compressions only, and Mouth-to-Mouth only
  * Buffs Mouth-to-Mouth in general so it works if you've Lung Rescued someone with a collapsed lung
* Put in a small helper in the tanks.dm so I don't have to keep copy and pasting the same update_gauge() proc

* Reworked the Auto-Compressor into a Stabilizer Harness since it doesn't ONLY do automated compressions anymore, now fitted with an Emergency Positive Pressure system like how the IVs have
* To make sure this device remains balanced, it'll now use power from a standard 1k cell, which can be swapped out for better (or worse) ones
* Made the Auto-CPR mode and the EPP system toggeable
* The Auto-CPR mode now has a chance to restart the heart of patients in Asystole/Flat Lining, but it also now has a chance to crack their ribs ONLY IF they're Asystole in the first place

**Tweaked the Auto-Compressor sprites**
![](https://i.imgur.com/GPo5DFO.gif)

**New in-hands and worn icons WITH visible indicators**
![](https://i.imgur.com/cWp5IqJ.gif)

**It also has a visible effect for when the Emergency Positive Pressure system is active!**
![](https://i.imgur.com/lVY428P.gif)

**Changing the various items with tools**
![](https://i.imgur.com/BUBbg0V.gif)

2022-05-27 03:30 UTC, VisVirific commented
!review

2022-05-27 16:48 UTC, NonQueueingMatt commented
The autocompressor already allows people to go into a zombie mode where their BA doesn't fall as is. I'm not sure about adding the ability to restart hearts too. This seems like it'd make them a tad too strong.

2022-05-29 11:55 UTC, NonQueueingMatt requested changes
These two changes should be all. I'm still unsure about it, but we'll see how it goes. I think the O2 thing should probably be offloaded to a rescue bag, personally, but that's for another day.

2022-05-29 11:55 UTC, NonQueueingMatt commented on code/game/objects/items/devices/auto_cpr.dm
> +			H.resuscitate()
Lower this probability.

2022-05-29 11:55 UTC, NonQueueingMatt commented on code/game/objects/items/devices/auto_cpr.dm
> +				chest.fracture()
Make this probability higher.

2022-05-30 10:56 UTC, NonQueueingMatt approved these changes

2022-06-06 03:56 UTC, JohnWildkins approved these changes

2022-06-06 06:10 UTC, merged