Minor protolathe removal
Aurorastation/Aurora.3 pull request #14134
Opened 2022-05-28 23:33 UTC by TheDanseMacabre

Removes the bee gun as something research can manufacture, essentially disabling it except as adminspawn.

The beegun is a nonsensical meme weapon designed for LRP servers.

2022-05-28 23:33 UTC, TheDanseMacabre commented
!review

2022-05-28 23:48 UTC, Arrow768 requested changes
If this is indeed the last place where the bee gun is available, then it should be removed completely (code and sprites) and not just patched out from the protolathe

2022-05-28 23:48 UTC, TheDanseMacabre commented
> If this is indeed the last place where the bee gun is available, then it should be removed completely (code and sprites) and not just patched out from the protolathe

And so it shall be done

2022-05-29 02:36 UTC, Arrow768 submitted a review, later dismissed

2022-05-29 02:36 UTC, Arrow768 commented on code/modules/projectiles/guns/energy/special.dm
> -	item_state = "gyrorifle"
From what I can see at a quick glance, this icon / dmi file is only used for the beegun.
If all the code referencing it is removed, the icon/dmi should be removed aswell.

2022-06-06 03:59 UTC, JohnWildkins approved these changes

2022-06-09 10:25 UTC, NonQueueingMatt approved these changes

2022-06-09 10:42 UTC, merged