Fixes Glowbulbs spawning nymphs when you destroy them.
Aurorastation/Aurora.3 pull request #14140
Opened 2022-05-29 17:01 UTC by RisingValiant

I mentioned it to Yonnimer, no this is not intended behaviour.

2022-05-29 17:03 UTC, RisingValiant commented
!bugfix
!review

2022-05-29 17:04 UTC, RisingValiant commented
!review

2022-05-29 17:04 UTC, RisingValiant commented
!bugfix

2022-05-29 17:06 UTC, SleepyGemmy requested changes

2022-05-29 17:06 UTC, SleepyGemmy commented on html/Glowbulbfix.yml
> +  - bugfix: Changed the code for Diona Glow Bulbs so that destroying one no longer spawns a nymph.
wrap this in quotation marks.
the file should also be under `html/changelogs/`.

2022-05-29 18:18 UTC, Arrow768 approved these changes

2022-05-29 18:19 UTC, Arrow768 requested changes
Oh yeah, I oversaw the changelog.
That needs to be in html/changelogs

2022-06-04 20:25 UTC, NonQueueingMatt requested changes
Remove the changelog in the html folder.

2022-07-11 10:32 UTC, closed without merging