Crayon Augment
Aurorastation/Aurora.3 pull request #14217
Opened 2022-06-06 03:14 UTC by Ben10083

Title

Basically took the rainbow crayon and made it a augment.

If anyone who is good with sprites want to help me have it so tip changes with color selected, let me know.

2022-06-06 03:14 UTC, Ben10083 commented
!review

2022-06-06 03:26 UTC, alsoandanswer commented
> If anyone who is good with sprites want to help me have it so tip changes with color selected, let me know.

Make the tip of the crayon a white overlay, re-color it appropriately, and then add the overlay to the crayon.

2022-06-06 09:40 UTC, alsoandanswer approved these changes

2022-06-07 10:35 UTC, NonQueueingMatt requested changes

2022-06-07 10:35 UTC, NonQueueingMatt commented on code/game/objects/items/crayons.dm
> +	return
Redundant return.

2022-06-07 10:35 UTC, NonQueueingMatt commented on code/game/objects/items/crayons.dm
> +/obj/item/pen/crayon/augment/attack_self(mob/living/user as mob)
```suggestion
/obj/item/pen/crayon/augment/attack_self(mob/living/user)
```

2022-06-08 10:43 UTC, NonQueueingMatt approved these changes

2022-06-09 10:03 UTC, merged