Labcoats, Once More, With Screaming
Aurorastation/Aurora.3 pull request #14213
Opened 2022-06-05 08:11 UTC by alsoandanswer

changes:
  - imageadd: "Adds new letterman labcoats. The old Idris labcoat with the giant symbol has returned and falls under this category as well."
  - imageadd: "Re-adds classic vibrant Zeng-Hu labcoat and EPMC labcoat variations."
  - imageadd: "Improves IAC labcoat."

The letterman labcoats are basically the same, except they use the corporation's initials instead of the logo on the back.

Feedback thread :

2022-06-05 08:14 UTC, alsoandanswer commented
!review

2022-06-07 10:43 UTC, NonQueueingMatt approved these changes

2022-06-08 12:04 UTC, NonQueueingMatt requested changes
`zeng/letterman/alt2` is invisible when worn. Buttoned sprite works, unbuttoned doesn't.

2022-06-15 21:54 UTC, Alberyk approved these changes

2022-06-15 22:20 UTC, merged