Exosuit RCD now displays Radial Menu
Aurorastation/Aurora.3 pull request #14220
Opened 2022-06-06 15:54 UTC by Ben10083

Title.
Fixes https://github.com/Aurorastation/Aurora.3/issues/14073

2022-06-06 15:54 UTC, Ben10083 commented
!review

2022-06-06 15:54 UTC, Ben10083 commented
!bugfix

2022-06-09 10:25 UTC, NonQueueingMatt requested changes

2022-06-09 10:25 UTC, NonQueueingMatt commented on code/modules/heavy_vehicle/equipment/engineering.dm
> +				R.mode = 1
Use the defines here.

2022-06-13 15:07 UTC, NonQueueingMatt approved these changes

2022-06-13 16:05 UTC, merged