Security Uniform Tweaks
Aurorastation/Aurora.3 pull request #14229
Opened 2022-06-07 02:00 UTC by alsoandanswer

<img width="1093" alt="dreammaker_ADvl9CmpPy" src="https://user-images.githubusercontent.com/42310821/172279593-81b1b0ca-02f2-4db8-9dbe-221fd1146160.png">
<img width="382" alt="dreammaker_AxoeQGs9hL" src="https://user-images.githubusercontent.com/42310821/172279602-bd3955c4-0dfc-4dd6-be25-0c4d53087bef.png">
<img width="326" alt="dreammaker_BtYoieBVRv" src="https://user-images.githubusercontent.com/42310821/172279603-f1ec6192-3873-4ba1-8909-2738f42c93c3.png">
<img width="1089" alt="dreammaker_C7ZENvKc9z" src="https://user-images.githubusercontent.com/42310821/172279604-6e878f5a-22d9-4aa7-b707-cb25d8972033.png">
<img width="159" alt="dreammaker_dluqWc1kwe" src="https://user-images.githubusercontent.com/42310821/172279605-f2120523-2e25-40b8-86e1-b09767fac5f1.png">
<img width="976" alt="dreammaker_eRhgYCih4M" src="https://user-images.githubusercontent.com/42310821/172279608-01cc5fde-5e0c-4da3-bf9d-9c846870df4a.png">
<img width="219" alt="dreammaker_jqBAGqVbNn" src="https://user-images.githubusercontent.com/42310821/172279611-408cab6d-b21d-4d78-a911-32667fd43d79.png">
<img width="330" alt="dreammaker_v0Lhils6ji" src="https://user-images.githubusercontent.com/42310821/172279614-b43036a2-5c0c-449a-8ade-de19e28cd852.png">
<img width="337" alt="dreammaker_YcSBygrgq2" src="https://user-images.githubusercontent.com/42310821/172279616-75f8d527-7ff3-430f-9fd4-8c5919a058af.png">

2022-06-07 10:50 UTC, NonQueueingMatt requested changes
Don't use necropolis in pathing - use Zavodskoi to be consistent with 1) current naming of the corporation and 2) other paths. Look at the forum thread for my sprite feedback.

The base type `/obj/item/clothing/under/rank/security` does not have a worn sprite. Is this intended?

2022-06-09 15:34 UTC, alsoandanswer commented
!review

2022-06-09 19:08 UTC, anconfuzedrock commented
from loadout, the black zavod cap + beret are both options but they seem to be invisible.

2022-06-10 11:09 UTC, NonQueueingMatt requested changes

2022-06-10 11:09 UTC, NonQueueingMatt commented on code/modules/client/preference_setup/loadout/loadout_factions.dm
> +	description = "A selection of PCMG and EPMC security uniforms."
```suggestion
	description = "A selection of PMCG and EPMC security uniforms."
```

2022-06-10 11:09 UTC, NonQueueingMatt commented on code/modules/client/preference_setup/loadout/loadout_factions.dm
> +/datum/gear/faction/pcmg_headwear
```suggestion
/datum/gear/faction/pmcg_headwear
```

2022-06-10 11:09 UTC, NonQueueingMatt commented on code/modules/client/preference_setup/loadout/loadout_factions.dm
> +	description = "A selection of PCMG and EPMC headwear."
```suggestion
	description = "A selection of PMCG and EPMC headwear."
```

2022-06-10 11:09 UTC, NonQueueingMatt commented on code/modules/client/preference_setup/loadout/loadout_factions.dm
> +	var/list/pcmg_headwear = list()
```suggestion
	var/list/pmcg_headwear = list()
```

2022-06-10 11:09 UTC, NonQueueingMatt commented on code/modules/client/preference_setup/loadout/loadout_factions.dm
> +	pcmg_headwear["PCMG beret"] = /obj/item/clothing/head/beret/corporate/pmc
```suggestion
	pcmg_headwear["PMCG beret"] = /obj/item/clothing/head/beret/corporate/pmc
```

2022-06-10 11:09 UTC, NonQueueingMatt commented on code/modules/client/preference_setup/loadout/loadout_factions.dm
> +	pcmg_headwear["PCMG softcap"] = /obj/item/clothing/head/softcap/pmc
```suggestion
	pcmg_headwear["PMCG softcap"] = /obj/item/clothing/head/softcap/pmc
```

2022-06-10 11:09 UTC, NonQueueingMatt commented on code/modules/client/preference_setup/loadout/loadout_factions.dm
> +	pcmg_headwear["PCMG softcap, alt"] = /obj/item/clothing/head/softcap/pmc/alt
```suggestion
	pcmg_headwear["PMCG softcap, alt"] = /obj/item/clothing/head/softcap/pmc/alt
```

2022-06-10 11:09 UTC, NonQueueingMatt commented on code/modules/client/preference_setup/loadout/loadout_factions.dm
> +	pcmg_headwear["EPMC beret"] = /obj/item/clothing/head/beret/corporate/pmc/epmc
```suggestion
	pmcg_headwear["EPMC beret"] = /obj/item/clothing/head/beret/corporate/pmc/epmc
```

2022-06-10 11:09 UTC, NonQueueingMatt commented on code/modules/client/preference_setup/loadout/loadout_factions.dm
> +	pcmg_headwear["EPMC softcap"] = /obj/item/clothing/head/softcap/pmc/epmc
```suggestion
	pmcg_headwear["EPMC softcap"] = /obj/item/clothing/head/softcap/pmc/epmc
```

2022-06-10 11:09 UTC, NonQueueingMatt commented on code/modules/client/preference_setup/loadout/loadout_factions.dm
> +	gear_tweaks += new /datum/gear_tweak/path(pcmg_headwear)
```suggestion
	gear_tweaks += new /datum/gear_tweak/path(pmcg_headwear)
```

2022-06-13 12:44 UTC, NonQueueingMatt approved these changes

2022-06-20 15:52 UTC, JohnWildkins approved these changes

2022-06-20 16:02 UTC, merged