Mining Drone Tweaks
Aurorastation/Aurora.3 pull request #14238
Opened 2022-06-07 16:20 UTC by Ben10083

Mining Drone can now be dispensed from vender by the vender coin miners get.

Mining Drone can now use their gripper to hold their own upgrade circuit.

2022-06-07 16:20 UTC, Ben10083 commented
!review

2022-06-09 10:48 UTC, NonQueueingMatt requested changes

2022-06-09 10:48 UTC, NonQueueingMatt commented on code/modules/mining/machine_vending.dm
> +		var/choice = input(user, "Which special equipment would you like to dispense from \the [src]?", capitalize_first_letters(name)) as null|anything in list("Enhanced Power Converter", "Hand-held Drill
Remove the empty "" here.

2022-06-09 10:48 UTC, NonQueueingMatt commented on code/modules/mining/machine_vending.dm
> +				dispensed_equipment = new /obj/item/device/orbital_dropper/drill(src)
No. We removed drill technician & drills for a reason. They're OP as fuck.

2022-06-10 11:06 UTC, NonQueueingMatt approved these changes

2022-06-20 15:47 UTC, JohnWildkins approved these changes

2022-06-20 15:52 UTC, merged