Removing Meteors/Debris From the Random Event Rotation
Aurorastation/Aurora.3 pull request #14268
Opened 2022-06-09 14:59 UTC by WickedCybs

It has been some time since the Horizon fully released at this point and it's become quite apparent to me that meteor as a random event is obsolete and not worthwhile to keep. It's essentially just a binary "shields check" that either goes unnoticed as the event can be completely ignored by turning those on or it takes over the round completely when the ship does not have shields because unlike the Aurora, meteors will hit every deck of the Horizon and the damage is always going to range from catastrophic to round-ending. I wouldn't even classify it as busywork given how fire-and-forget it is at the moment.

This does not mean a total meteor removal or the mechanics being lost because meteors and other hazards shields can account for are still present on the overmap, so there is a use there if the Horizon ever needs to cross into a dust cloud or asteroid belt. Additionally, there's room to give shields more meaning beyond being turned on and forgotten about in the future.

Additionally, the thrilling gameplay of having meteors still randomly pelt the ship even if you're not a in an asteroid field can be voted for via the meteor game mode.

2022-06-09 15:00 UTC, WickedCybs commented
!review

2022-06-09 15:20 UTC, Doxxmedearly approved these changes

2022-06-09 16:17 UTC, Arrow768 requested changes
The excel file with the severities in the tools folder needs to be updated.

2022-06-09 17:26 UTC, WickedCybs commented
> The excel file with the severities in the tools folder needs to be updated.

Should be resolved now. I used google sheets to edit the file.

2022-06-20 15:43 UTC, JohnWildkins approved these changes

2022-06-25 20:06 UTC, NonQueueingMatt approved these changes

2022-06-25 20:11 UTC, merged