Adds a second rescue RIG to the First Responder's offiice
Aurorastation/Aurora.3 pull request #14316
Opened 2022-06-13 23:31 UTC by FayeLovesU

There are two responders, and only one RIG. The rig is a ton of fun to use, with a slick sprite and a jetpack, leg actuators, etc. However, since there's only one it leads to one FR usually feeling left out, especially if the other FR isn't the sharing sort. It isn't fun and it sucks to be in the normal voidsuit while your partner is in the rig,- like driving a model T alongside the batmobile. Even when you are the one using it, I find that it's a source of worry that you may be hogging it from another FR. 

Machinists can produce these, yes, but they're prohibitively expensive - the same as the CE's hardsuit and the hazard RIG -, and dependant on a multitude of factors such as whether or not mining is bringing in materials, or if research is installing upgrades to reduce costs. I've tried multiple times to get a spare RIG from the machinists in-round, but have not been successful.

2022-06-14 15:11 UTC, alsoandanswer commented
Add a changelog, please. Here's how.
1. Go into the Aurora/html/changelogs file.
2. Copy + Paste 'example.yml'.
3. Rename it to [username]_[commit name]. This isn't standard, but what I usually do.
4. Edit the contents. Remember to change the author.
5. Stage, push and commit.

2022-06-14 15:50 UTC, SleepyGemmy requested changes
what wezzy said above.

2022-06-14 18:45 UTC, FayeLovesU commented
changelog done : )

2022-06-14 19:08 UTC, Llywelwyn requested changes
the actual changes are all good, but changelog needs to be a new file. right now you've renamed example.yml so it doesn't exist anymore, so there'll probably be some error thrown when the checks are ran

2022-06-15 19:34 UTC, FayeLovesU commented
> the actual changes are all good, but changelog needs to be a new file. right now you've renamed example.yml so it doesn't exist anymore, so there'll probably be some error thrown when the checks are ran
> 
> just need to return example.yml as it was and put your changelog in a new copy

Pretty sure I fixed it

2022-06-15 21:45 UTC, Llywelwyn approved these changes

2022-06-15 22:16 UTC, SleepyGemmy commented on html/changelogs/FayeLovesU - 14316.yml
> +  - rscadd: "Added a second rescue RIG to the first responder's quarters."
```suggestion
  - maptweak: "Added a second rescue RIG to the first responder's quarters."
```

2022-06-19 19:44 UTC, SleepyGemmy approved these changes
changes addressed. mapping looks fine.

2022-06-20 15:41 UTC, JohnWildkins approved these changes

2022-06-26 12:16 UTC, NonQueueingMatt commented
!review

2022-06-26 14:02 UTC, alsoandanswer approved these changes

2022-08-06 01:57 UTC, merged