Adds a wrecked NT ship awaysite.
Aurorastation/Aurora.3 pull request #14321
Opened 2022-06-14 23:42 UTC by Yonnimer

Title^

2022-06-15 00:16 UTC, Yonnimer commented
!review

2022-06-15 00:21 UTC, Yonnimer commented
Currently broken, will fix it soonish

2022-06-15 00:58 UTC, SleepyGemmy requested changes

2022-06-15 01:10 UTC, SleepyGemmy commented on maps/away/generic/wrecked_nt_ship.dm
> +	desc = "A wrecked ship once owend by NanoTrasen."
```suggestion
	desc = "A wrecked ship once owned by NanoTrasen."
```

2022-06-15 03:13 UTC, SleepyGemmy requested changes
![image](https://user-images.githubusercontent.com/99297919/173728941-3bf6d9b1-9e58-4f36-9ce5-aa1ce673b325.png)
this tile on the shown co-ordinates is missing an area. add either one of the near areas to this tile and the unit test should pass.

2022-06-16 04:14 UTC, Yonnimer commented
> ![image](https://user-images.githubusercontent.com/99297919/173728941-3bf6d9b1-9e58-4f36-9ce5-aa1ce673b325.png) this tile on the shown co-ordinates is missing an area. add either one of the near areas to this tile and the unit test should pass.

Should be fixed

2022-06-23 19:29 UTC, NonQueueingMatt approved these changes

2022-06-23 19:38 UTC, merged