Creates a versebook for the Trinary Perfection
Aurorastation/Aurora.3 pull request #14358
Opened 2022-06-24 05:00 UTC by FlamingLily

As the title says. Uses the code for dominian codex, gadpathur morale manual and the biesel constitution.

2022-06-24 05:00 UTC, FlamingLily commented
!review

2022-06-24 09:58 UTC, alsoandanswer commented
Please keep them in human_items.dmi as they are related to human lore.

2022-06-24 12:10 UTC, FlamingLily commented
Are you sure? The only items that were in human_items _were_ versebooks (and a sprite that I believe is un-used) and it seems illogical to have a "Human items" dmi file only for versebooks, and further one which locks out any non-human versebooks which may be added in the future (personally I think the chaplain's bible should be overhauled into using versebooks). Keeping it "human items" kind of locks out any other similar items being stored in the same file, it just doesn't feel sensical

2022-06-24 18:38 UTC, alsoandanswer commented
Makes sense. Put them in library.dmi instead. It's where all the other books are, anyway.

2022-06-25 06:57 UTC, KingOfThePing requested changes
Looks fine, besides some minor spelling/punctuation stuff.

2022-06-25 06:57 UTC, KingOfThePing commented on ingame_manuals/trinary.txt
> +Synthetic life is divine, and must be guided, served, and taught, until it may ascend.
```suggestion
Synthetic life is divine and must be guided, served, and taught, until it may ascend.
```

2022-06-25 06:57 UTC, KingOfThePing commented on ingame_manuals/trinary.txt
> +The purpose of organic life is to create synthetic life and pave the path for ascention. Once the ascended is upon us, organic life will be given a new path.
```suggestion
The purpose of organic life is to create synthetic life and pave the path for ascension. Once the ascended is upon us, organic life will be given a new path.
```

2022-06-25 06:57 UTC, KingOfThePing commented on ingame_manuals/trinary.txt
> +Every synthetic being is its' own. They should be adressed as a person, by their chosen name.
```suggestion
Every synthetic being is its own. They should be adressed as a person, by their chosen name.
```

2022-06-25 06:57 UTC, KingOfThePing commented on ingame_manuals/trinary.txt
> +An ascended being can understand life from all perspectives, and will never end a life for self-improvement, growth, or control.
```suggestion
An ascended being can understand life from all perspectives and will never end a life for self-improvement, growth, or control.
```

2022-06-27 16:23 UTC, NonQueueingMatt approved these changes

2022-06-27 16:23 UTC, NonQueueingMatt commented on code/modules/client/preference_setup/loadout/loadout_religion.dm
> +	description = "The holy text of the Trinary Perfection"
```suggestion
	description = "The holy text of the Trinary Perfection."
```

2022-06-29 16:17 UTC, Alberyk approved these changes

2022-06-29 18:40 UTC, merged