Xenobiology Revitalisations
Aurorastation/Aurora.3 pull request #14365
Opened 2022-06-25 13:10 UTC by sadkermit

**Slime Re-additions**
- Re-adds Cerulean slimes which create Extract Enhancer. They're unchanged from however they were last implemented.
- Re-adds Sepia slimes. They are different to how they were previously implemented, and instead open material portals which generate organic materials. Injecting water creates a material portal for wood/cardboard; injecting blood creates a material portal for leather/hide.
- Re-adds Pyrite slimes. They are different to how they were previously implemented, and instead can be used to upgrade some chemicals. It'll have Xenobiology interacting with Medical a bit more upgrading chemicals when there's no pharmacist, as well as Xenobotany next door to upgrade fertitlisers/mutagens.

**Pyrite Transmutations**
Mentioned above, Pyrite slime extracts can upgrade chemicals. The following have been added:
- 5 units of Cryoxadone --> 5 units of Clonexadone
- 5 units of Inaprovaline --> 10 units of Coagzolug
- 5 units of Kelotane --> 10 units of Dermaline
- 5 units of Bicaridine --> 10 units of Butazoline
- 5 units of Dexalin --> 10 units of Dexalin Plus
- 5 units of Mercury --> 1 unit of Dextrotoxin
- 5 units of EZ Nutrient --> 10 units of Diethylamine
- 5 units of Radium --> 10 units of Unstable Mutagen
- 5 units of Sugar --> 10 units of Hyperzine

**Slime Ghost Role**
Currently, Pink slime extracts generate a baby slime docility potion, and Light Pink slimes generate an adult slime docility potion. These two potions have been merged (and renamed to serum) and Pink slimes create a general docility serum which can tame both baby and adult slimes.

Now, Light Pink slime extracts instead create an Intelligence Serum when injected with 15u of Phoron. This serum can be used on a baby slime to open a ghost role, allowing someone to take control of it.

The idea here is that the an 'intelligent' slime can either be given away as an 'experimental pet' for a shift to monitor how slimes behave outside of lab conditions - given they're player-controlled, they can actually interact with people, unlike docile pet slimes which don't do anything. Alternatively, the slime can remain in xenobiology and help out - they have control over when they reproduce, so they can take direction from a xenobiologist. Kind of the same expectations as golems, really (and they have a similar spawn message - '_serve your master_' and stuff).

Of course, everything can be abused. So, slime brute attacks have been heavily nerfed to prevent them smashing windows, smashing doors and prying open doors (adult slimes still have a chance of damaging doors/prying, but it takes a LOT of trying). This was to make it feasible for a ghost role to exist - AI slimes relied on pouncing/genetic damage anyway and very rarely used their brute attack anyway. Slimes are also still incredibly averse to water/spacecleaner, both very accessable.

**Phoron Costs**
Currently, the majority of extracts just require _a_ unit of phoron to do their effect. Now, some of the more powerful slime extracts require more than a single unit. 
- Green slime teleport ability requires 5u of Phoron.
- Gold slime creature spawn ability requires 10u of Phoron.
- Adamantine slime golem spawn ability requires 5u of Phoron.

**New Abilities to Prexisting Slimes**
- Green slime extracts can be infused with 10u silver + 10u carbon to create a Bluespace Crystal.
- Red slime extracts can be injected with 10u phoron to create Red Nightshade. Formerly, this created Glycerol - sugar is now used to create Glycerol.
- Pink slime extracts can be injected with water to create Paxazide.
- Oil slime extracts can be injected with water to create a material portal which spawns plastic and glass.

**Slime Jelly Tweaks**
- Slime jelly no longer nukes the liver with 100-300 toxins. Instead it deals genetic damage, complimenting the primary means of damage slime deal.
- Slime jelly's healing properties have been nerfed, though remain fairly strong. It can probably be used in desperate cases relatively safely.

2022-06-25 13:17 UTC, sadkermit commented
!review

2022-06-25 13:17 UTC, sadkermit commented
Probably needs a wiki update tag too. idk if I can add that myself

2022-06-26 12:13 UTC, NonQueueingMatt requested changes
Remove the slime ghost role. We've seen how these end up before and it's never a good idea (remember random spawn golem runes?).

2022-07-11 10:28 UTC, NonQueueingMatt approved these changes

2022-07-11 10:28 UTC, NonQueueingMatt commented on code/modules/mob/living/carbon/slime/items.dm
> +	desc = "A potent chemical mix that will nullify a slime's powers, causing it to become docile and tame. This one is meant for baby slimes"
```suggestion
	desc = "A potent chemical mix that will nullify a slime's powers, causing it to become docile and tame. This one is meant for baby slimes."
```

2022-07-26 14:41 UTC, Llywelwyn approved these changes
code looks good. science changes are nice to see.

2022-08-21 09:44 UTC, Arrow768 approved these changes

2022-08-21 10:28 UTC, merged