Tau Ceti Legion Uniform Improvement
Aurorastation/Aurora.3 pull request #14392
Opened 2022-07-03 11:14 UTC by alsoandanswer

Title.

2022-07-03 12:17 UTC, alsoandanswer commented
!review

2022-07-07 01:37 UTC, Alberyk approved these changes

2022-07-07 02:26 UTC, Ben10083 requested changes
With you deleting the older uniforms, you need to modify the TCFL ghost roles so they spawn with the right clothing, and replace some of the legion clothing on their ship.

2022-07-07 09:31 UTC, alsoandanswer commented
> With you deleting the older uniforms, you need to modify the TCFL ghost roles so they spawn with the right clothing, and replace some of the legion clothing on their ship.

I didn't delete anything. I just changed the icon_state.

2022-07-07 09:33 UTC, alsoandanswer commented on code/modules/clothing/under/miscellaneous.dm
> +	worn_state = "tauceti_volunteer"
```suggestion
	worn_state = "tauceti_volunteer"
	contained_sprite = TRUE
```

2022-07-07 09:34 UTC, alsoandanswer commented on code/modules/clothing/under/miscellaneous.dm
>  	item_state = "bl_suit"
```suggestion
```

2022-07-07 10:43 UTC, NonQueueingMatt approved these changes

2022-07-07 10:59 UTC, merged