Allow AI to change alert level (again)
Aurorastation/Aurora.3 pull request #14443
Opened 2022-07-14 10:41 UTC by DreamySkrell

https://forums.aurorastation.org/topic/17251-give-ais-full-access-to-the-command-programmes/#comment-157741

AI can change alert level
borgs cannot

fixes #13102

2022-07-14 10:46 UTC, DreamySkrell commented
!review

2022-07-14 10:50 UTC, NonQueueingMatt requested changes

2022-07-14 10:50 UTC, NonQueueingMatt commented on code/modules/modular_computers/file_system/programs/command/comm.dm
> +			if((is_authenticated(user) && !issilicon(usr) && ntn_cont && ntn_comm) || (is_authenticated(user) && isAI(usr) && ntn_cont && ntn_comm))
```suggestion
			if(is_authenticated(user) && (!issilicon(usr) || isAI(usr)) && ntn_cont && ntn_comm)
```

2022-07-14 10:58 UTC, DreamySkrell commented
fixes #13102

2022-07-14 15:10 UTC, NonQueueingMatt approved these changes

2022-07-14 15:10 UTC, NonQueueingMatt commented on html/changelogs/DreamySkrell-PR-14443.yml
> +  - tweak: " Allow AI to change alert level (again)."
```suggestion
  - tweak: "Allow AI to change alert level (again)."
```

2022-07-24 10:41 UTC, Arrow768 approved these changes

2022-07-24 13:01 UTC, merged