Solarian Army uniform and armor, plus icon fixes
Aurorastation/Aurora.3 pull request #14446
Opened 2022-07-15 07:08 UTC by TheDanseMacabre

Nothing crazy, just adds Sol army stuff for future use and a number of icon fixes.

2022-07-15 07:09 UTC, TheDanseMacabre commented
!review

2022-07-15 10:17 UTC, KingOfThePing commented
You should document, that you change armour values, too.

2022-07-15 10:18 UTC, KingOfThePing requested changes

2022-07-15 10:18 UTC, KingOfThePing commented on html/changelogs/dansemacabre-armystrong2.yml
> +  - bugfix: "Fixed a number of icon errors with Solarian uniforms."
```suggestion
  - bugfix: "Fixed a number of icon errors with Solarian uniforms."
  - tweak: "Buffs the armour values of the sol armour."
```

2022-07-15 18:42 UTC, TheDanseMacabre commented on html/changelogs/dansemacabre-armystrong2.yml
> +  - bugfix: "Fixed a number of icon errors with Solarian uniforms."
Completely forgot I did that, my bad.

2022-07-16 00:44 UTC, KingOfThePing approved these changes

2022-07-16 00:44 UTC, KingOfThePing approved these changes

2022-07-20 20:35 UTC, NonQueueingMatt approved these changes

2022-07-20 21:38 UTC, Alberyk approved these changes

2022-07-20 21:56 UTC, merged