Fixes pickup animation layering and colored chairs
Aurorastation/Aurora.3 pull request #14453
Opened 2022-07-17 03:58 UTC by alsoandanswer

- bugfix: "Fixes pickup animations not applying overlays and not layering over mobs."
  - bugfix: "Fixes colored chairs not re-applying colors when picked up and placed down."

2022-07-17 03:59 UTC, alsoandanswer commented
!bugfix

2022-07-17 03:59 UTC, alsoandanswer commented
!review

2022-07-17 11:25 UTC, NonQueueingMatt requested changes

2022-07-17 11:25 UTC, NonQueueingMatt commented on code/game/objects/items/weapons/material/twohanded.dm
> +//	var/base_icon //moved to items.dm
Delete instead of commenting.

2022-07-17 20:30 UTC, alsoandanswer commented on code/game/objects/items/weapons/material/twohanded.dm
> +//	var/base_icon //moved to items.dm
```suggestion
```

2022-07-18 10:25 UTC, NonQueueingMatt requested changes

2022-07-18 10:25 UTC, NonQueueingMatt commented on code/game/atoms_movable.dm
> +		pickup_animation.overlays = I.overlays
No istype(src, ...) checks. Pass the overlays to the atom/movable proc through an override on the item level.

2022-07-20 20:44 UTC, merged