Adds Grape Jelly and missing Condiment Bottles
Aurorastation/Aurora.3 pull request #14499
Opened 2022-07-26 20:47 UTC by Roostercat12

Adds Grape Jelly as a reagent obtainable by blending grapes with its own condiment bottle sprite to boot. Grape recipes to come later. 

In addition, adds condiment bottle sprites for the following ingredients: Ambrosia/Wulu extract, Psilocybin, Batter, Pumpkin Pulp, Pumpkin Spice, Cocoa Powder, Egg Yolk, Triglyceride.

All sprites made by myself. 

![sick condiment bottles](https://user-images.githubusercontent.com/58752709/181108478-344e0400-b81c-4a57-8558-2c1096606ccc.JPG)

2022-07-26 20:48 UTC, Roostercat12 commented
!review

2022-07-26 20:55 UTC, SleepyGemmy requested changes

2022-07-26 20:55 UTC, SleepyGemmy commented on code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Food-Drinks.dm
> +	condiment_desc = "A jar of jelly derived from grapes. Superior to Cherry Jelly."
```suggestion
	condiment_desc = "A jar of jelly derived from grapes. Superior to cherry jelly."
```

2022-07-26 20:55 UTC, SleepyGemmy commented on code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Food-Drinks.dm
> +	condiment_desc = "An orange jar with a picture of a Pumpkin on its label. Spooky."
```suggestion
	condiment_desc = "An orange jar with a picture of a pumpkin on its label. Spooky."
```

2022-07-26 20:55 UTC, SleepyGemmy commented on code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Food-Drinks.dm
> +	condiment_desc = "Every teenage girl's favorite seasonal ingredient."
```suggestion
	condiment_desc = "Every teenager's favorite seasonal ingredient."
```

2022-07-26 20:55 UTC, SleepyGemmy commented on html/changelogs/Grape Jelly And Condiment Bottles.yml
> +author: ChangeMe
faulty author.

2022-07-26 21:07 UTC, Roostercat12 commented on html/changelogs/Grape Jelly And Condiment Bottles.yml
> +author: ChangeMe
fixed

2022-07-26 21:27 UTC, SleepyGemmy approved these changes
suggested changes addressed.

2022-07-27 07:59 UTC, KingOfThePing approved these changes
Another PR Gem cheats himself into being a co-author, god bless

2022-08-02 15:41 UTC, Alberyk approved these changes

2022-08-06 14:52 UTC, NonQueueingMatt approved these changes

2022-08-06 14:55 UTC, merged