Adds two new kitchen signs
Aurorastation/Aurora.3 pull request #14504
Opened 2022-07-27 13:17 UTC by KingOfThePing

This PR adds two new kitchen signs (so Event Horizon isnt alone anymore). Sprites were done by Lancer. They are also animated. 

Thematically one refers to Silversun, the other one to Eridani I. This PR also updates one of the bar signs to align with recent Eridani lore changes. 

![paradiseSands](https://user-images.githubusercontent.com/43940569/181256475-68cf1d3a-753c-4a2a-8e02-c6e46fb12af0.png)
![cityAlive](https://user-images.githubusercontent.com/43940569/181256485-22619079-92b2-4ac2-a896-58ec65a13ca5.png)

2022-07-27 13:21 UTC, KingOfThePing commented
!review

2022-07-27 13:43 UTC, SleepyGemmy requested changes

2022-07-27 13:43 UTC, SleepyGemmy commented on code/game/objects/structures/barsign.dm
>  /decl/sign/double/bar/whiskey_implant
please add a newline inbetween each decl, if possible.

2022-07-27 13:43 UTC, SleepyGemmy commented on code/game/objects/structures/barsign.dm
> +	desc = "A take on the sign of one of Silversun's most popular cafe & bistro, owned by Idris Incorporated."
```suggestion
	desc = "A take on the sign of one of Silversun's most popular cafe- and bistro owned by Idris Incorporated."
```

2022-07-27 13:43 UTC, SleepyGemmy commented on code/game/objects/structures/barsign.dm
> +	desc_fluff = "Paradise Sands is the name of one of the most popular Cafe & Bistro places on all of Silversun. Located in a seculuded cove, you can brunch, drink and swim at a beach with white sand a
```suggestion
	desc_fluff = "Paradise Sands is the name of one of the most popular cafe- and bistro places on all of Silversun. Located in a secluded cove, you can brunch, drink, and swim at a beach with white sand and a deep, azure ocean; a paradise."
```

2022-07-27 13:43 UTC, SleepyGemmy commented on code/game/objects/structures/barsign.dm
> +	desc = "City Alive is another popular restaurant chain, originating from Eridani I. It is famous for it's light shows."
```suggestion
	desc = "City Alive is another popular restaurant chain, originating from Eridani I. It is famous for its light shows."
```

2022-07-27 13:43 UTC, SleepyGemmy commented on code/game/objects/structures/barsign.dm
> +	desc_fluff = "City Alive is a high class restaurant chain, dotted all over Eridani I and III. Especially on Eridani I they are also famous for their light shows in the evenings. These lights look li
```suggestion
	desc_fluff = "City Alive is a high class restaurant chain, dotted all over Eridani I and III. Especially on Eridani I they are also famous for their light shows in the evenings. These lights look like pulsating veins, making the city seem alive, especially when observed from orbit."
```

2022-07-28 02:59 UTC, Alberyk approved these changes

2022-07-28 14:56 UTC, SleepyGemmy approved these changes

2022-07-28 18:42 UTC, NonQueueingMatt approved these changes

2022-07-31 05:31 UTC, merged