Adds the Ti'Rakqi Freighter
Aurorastation/Aurora.3 pull request #14517
Opened 2022-07-29 03:04 UTC by Alberyk

This pr adds a skrell themed third party ship at the request of the lore team. Most of the mapping was done by butterrobber

2022-07-29 03:11 UTC, TheDanseMacabre requested changes
I would recommend removing some of the guns present. This ship seems over-armed relative to the rest of the third party ships, which tend to have a highly limited armament across the board. I would also recommend removing the pirate coat in the cockpit, and the meme very rare hat built into the wall. Generally speaking, I find these "easter eggs" to be a bad design decision.

2022-07-29 06:55 UTC, DreamySkrell commented
IMO: The layout is really weird. Both like, subjectively, but also "objectively".

The small shuttle can't leave through the hangar doors.

All the rooms are huge, and mostly empty.

They are pirates, but there's no brig to hold any prisoners or etc.

There's no dedicated EVA gear room. Airlock is from outside straight to that warehouse.

2022-07-29 15:24 UTC, Butterrobber202 commented
> IMO: The layout is really weird. Both like, subjectively, but also "objectively".
> 
> The small shuttle can't leave through the hangar doors.
> 
> All the rooms are huge, and mostly empty.
> 
> They are pirates, but there's no brig to hold any prisoners or etc.
> 
> There's no dedicated EVA gear room. Airlock is from outside straight to that warehouse.
> 
> Am I blind? Aren't those guns energy/laser? I see no rechargers.

Small Shuttle can leave.
Rooms have extra space so the crew make can their own modifications to the ship as they please.
This ship is designed for smuggling. (Also, hostage RP is about as fun as smashing your foot with a rock.)
Overkill to have a room that's only purpose is EVA. The Engineer room has the equipment needed.
As for the rechargers. I may have just forgot them.

2022-07-29 16:55 UTC, DreamySkrell commented
Talked this over in the discord. I have other concerns, but, ehhh.

2022-08-06 08:14 UTC, listerla approved these changes

2022-08-21 10:14 UTC, Arrow768 requested changes

2022-08-21 10:14 UTC, Arrow768 commented on maps/away/ships/tirakqi_freighter_ghostroles.dm
> +	desc = "You crew the ship, mop the floors, cook the meals, and shoot whoever gets to close too the goods. Try to show some initiative!"
```suggestion
	desc = "You crew the ship, mop the floors, cook the meals, and shoot whoever gets too close to the goods. Try to show some initiative!"
```

2022-08-22 09:00 UTC, Arrow768 approved these changes

2022-09-05 20:56 UTC, NonQueueingMatt approved these changes

2022-09-06 10:35 UTC, merged