Adds a Callisto accent tag.
Aurorastation/Aurora.3 pull request #14512
Opened 2022-07-28 14:32 UTC by TheStryker

Adds a Callisto accent tag and tweaks the existing Jovian one.
Descriptions done by Schwann.
![image](https://user-images.githubusercontent.com/19821403/181550505-ef6bdf7a-0221-4d43-aea3-36a044dcc5f0.png)
![image](https://user-images.githubusercontent.com/19821403/181550899-262762c5-66b1-4c77-b26a-66f9f835f47f.png)

2022-07-28 14:37 UTC, TheStryker commented
!review

2022-07-28 14:55 UTC, SleepyGemmy requested changes

2022-07-28 14:55 UTC, SleepyGemmy commented on code/modules/background/accent/human.dm
> +	description = "Considered to be one of the most recognizable accents in the Sol System due to its uniquely breathless pace, the stereotypical Callistean accent has its roots in the moon’s \
```suggestion
	description = "Considered to be one of the most recognizable accents in the Sol System due to its uniquely breathless pace, the stereotypical Callistean accent has its roots in the moon's \
```

2022-07-28 14:55 UTC, SleepyGemmy commented on code/modules/background/accent/human.dm
> +	port district of New Valletta. While not all Callisteans speak with the breathless pace of those from New Valletta, the district’s status as a port has led to its accent becoming the moon’s most \
```suggestion
	port district of New Valletta. While not all Callisteans speak with the breathless pace of those from New Valletta, the district's status as a port has led to its accent becoming the moon's most \
```

2022-07-28 14:55 UTC, SleepyGemmy commented on code/modules/background/accent/human.dm
> +	description = "The Jovian accent is an odd mish-mash of accents from Jupiter’s various moons, and has heavy variation on each of the moons. On Europa, the Jovian accent often takes on traces of \
```suggestion
	description = "The Jovian accent is an odd mish-mash of accents from Jupiter's various moons, and has heavy variation on each of the moons. On Europa, the Jovian accent often takes on traces of \
```

2022-07-28 14:55 UTC, SleepyGemmy commented on code/modules/background/accent/human.dm
> +	Tradeband due to the amount of high-income tourism, while the Castillean Jovian accent is known for the rapid, breathless pace at which it is typically spoken. Ganymede is often seen as the 'standar
```suggestion
	Tradeband due to the amount of high-income tourism, while the Castillean Jovian accent is known for the rapid, breathless pace at which it is typically spoken. Ganymede is often seen as the standard \
```

2022-07-28 14:55 UTC, SleepyGemmy commented on code/modules/background/accent/human.dm
> +	Jovian accent, though some on Castillo vehemently believe that the Castillian accent should be the standard."
```suggestion
	Jovian accent, though some on Castillo vehemently believe that the Castillian accent should be considered the standard."
```

2022-07-28 15:11 UTC, KingOfThePing approved these changes

2022-07-28 16:10 UTC, SleepyGemmy commented on code/modules/background/accent/human.dm
> +	Jovian accent, though some on Castillo vehemently believe that the Castillian accent should be considered the standard."
```suggestion
	Jovian accent, though some on Castillo vehemently believe that the Castillean accent should be considered the standard."
```

2022-07-28 17:43 UTC, Jaraci commented
Please consider giving this accent to the Idris Incorporated megacorporate origin too. The Callisto wiki page already supports this from a lore perspective.

2022-07-29 14:42 UTC, SleepyGemmy approved these changes
suggested changes addressed.

2022-08-03 16:36 UTC, NonQueueingMatt approved these changes

2022-08-06 02:02 UTC, Alberyk approved these changes

2022-08-06 16:59 UTC, merged