Adding more Skrell clothes
Aurorastation/Aurora.3 pull request #14539
Opened 2022-08-02 15:55 UTC by WhatsUpBrotendo

Adds a casual wetsuit for Skrell.
Adds tailbands with SCS symbols on them for Skrell.
Adds nation capes for Skrell and Dionae.

Credits to Ryverstyx for the tailband and cape sprites.

![image](https://user-images.githubusercontent.com/52638996/182417544-4fa0b49d-7a09-4bf5-82a4-30d4db9b55a3.png)
![image](https://user-images.githubusercontent.com/52638996/182417568-4a585901-be39-4b43-b954-52531350b104.png)
![image](https://user-images.githubusercontent.com/52638996/182417588-4512535d-f178-4b41-b355-53f281a5180b.png)

While I did test everything, there is an issue with the wetsuit where parts of it will always be on top of accessories put onto the uniform. I think it's something to do with how the dual-colouring code works rather than my implementation of it. It's not game-breaking but if it's an issue that would mean removing it from the PR until fixed please let me know.

2022-08-02 16:19 UTC, WhatsUpBrotendo commented
!review

2022-08-04 19:05 UTC, KingOfThePing approved these changes

2022-08-06 01:38 UTC, Alberyk approved these changes

2022-08-06 08:08 UTC, listerla commented on code/skrell.dm
> +	name = "Worker's Cap"
```suggestion
	name = "worker's cap"
```

2022-08-06 08:08 UTC, listerla commented on code/skrell.dm
> +	name = "Long Worker's Cap"
```suggestion
	name = "long worker's cap"
```

2022-08-06 08:09 UTC, listerla commented on code/skrell.dm
> +	name = "Ox Tailband"
```suggestion
	name = "\improper Ox tailband"
```

2022-08-06 08:09 UTC, listerla commented on code/skrell.dm
> +	name = "Ix Tailband"
```suggestion
	name = "\improper Ix tailband"
```

2022-08-06 08:09 UTC, listerla commented on code/skrell.dm
> +	name = "Oqi Tailband"
```suggestion
	name = "\improper Oqi tailband"
```

2022-08-06 08:09 UTC, listerla commented on code/skrell.dm
> +	name = "Iqi Tailband"
```suggestion
	name = "\improper Iqi tailband"
```

2022-08-06 08:10 UTC, listerla commented
Could also capitalize the national names for the capes and hit them with \improper as well.

2022-08-06 22:46 UTC, listerla commented
You did /improper instead of \improper on the national capes - means they would have the "/improper" show on examine.

2022-08-06 23:07 UTC, Llywelwyn requested changes
looks good. i think some of the code is written to a wrong file by mistake, but what is there is good once copied to the right place. and just commented two pedantic changes to case - for whatever reason, our loadout is always lower case, even for proper nouns. it's only acronyms that are in caps

2022-08-06 23:07 UTC, Llywelwyn commented on code/modules/client/preference_setup/loadout/loadout_xeno/skrell.dm
> +	display_name = "Casual Wetsuit"
```suggestion
	display_name = "casual wetsuit"
```

2022-08-08 12:10 UTC, NonQueueingMatt requested changes
You did not capitalize ox/iqi, so I assume that they are not proper names. Neither is "tailband".

2022-08-08 12:10 UTC, NonQueueingMatt commented on code/modules/client/preference_setup/loadout/loadout_xeno/skrell.dm
> +
```suggestion
```

2022-08-08 12:10 UTC, NonQueueingMatt commented on code/modules/clothing/ears/skrell.dm
> +	name = "Ox Tailband"
```suggestion
	name = "ox tailband"
```

2022-08-08 12:10 UTC, NonQueueingMatt commented on code/modules/clothing/ears/skrell.dm
> +	name = "Ix Tailband"
```suggestion
	name = "ix tailband"
```

2022-08-08 12:10 UTC, NonQueueingMatt commented on code/modules/clothing/ears/skrell.dm
> +	name = "Oqi Tailband"
```suggestion
	name = "oqi tailband"
```

2022-08-08 12:10 UTC, NonQueueingMatt commented on code/modules/clothing/ears/skrell.dm
> +	name = "Iqi Tailband"
```suggestion
	name = "iqi tailband"
```

2022-08-08 21:16 UTC, NonQueueingMatt approved these changes

2022-08-08 21:16 UTC, merged