Adds a Gadpathurian kepi.
Aurorastation/Aurora.3 pull request #14547
Opened 2022-08-04 18:51 UTC by TheStryker

Adds a Gadpathurian patrol cap in the style of a kepi under the gadpathurian headwear section in the loadout tab.
As requested by Schwann.
![image](https://user-images.githubusercontent.com/19821403/182930516-303cbd44-e257-452c-8555-ba2d4ca04860.png)

2022-08-04 18:56 UTC, TheStryker commented
!review

2022-08-05 12:53 UTC, KingOfThePing approved these changes

2022-08-06 08:12 UTC, listerla commented on code/modules/clothing/factions/gadpathur.dm
> +	name = "gadpathurian patrol cap"
```suggestion
	name = "\improper Gadpathurian patrol cap"
```

2022-08-06 12:25 UTC, Arrow768 approved these changes

2022-08-06 14:56 UTC, NonQueueingMatt requested changes

2022-08-06 14:56 UTC, NonQueueingMatt commented on code/modules/clothing/factions/gadpathur.dm
> +		to_chat(user, "You raise the sun shade on the cap.")
```suggestion
		to_chat(user, SPAN_NOTICE("You raise the sun shade on the cap."))
```

2022-08-06 14:56 UTC, NonQueueingMatt commented on code/modules/clothing/factions/gadpathur.dm
> +		to_chat(user, "You lower the sun shade on the cap.")
```suggestion
		to_chat(user, SPAN_NOTICE("You lower the sun shade on the cap."))
```

2022-08-09 10:44 UTC, NonQueueingMatt approved these changes

2022-08-09 10:54 UTC, merged