Psionics firing pin
Aurorastation/Aurora.3 pull request #14545
Opened 2022-08-03 18:09 UTC by DreamySkrell

lets the user fire the gun only if the user is capable of psionics (skrell)
does not work with the psionic implant (from the loadout)
should work with humans/etc with the borer stuff (as it gives psionics as well)

2022-08-03 18:11 UTC, DreamySkrell commented
!review

2022-08-03 20:42 UTC, RyverStyx approved these changes

2022-08-06 08:15 UTC, listerla approved these changes

2022-08-06 12:34 UTC, Arrow768 commented
DNM until the (possibly unintentional) side effects of that are acknowledged and accepted by the skrell lore team.

2022-08-08 12:08 UTC, NonQueueingMatt requested changes

2022-08-08 12:08 UTC, NonQueueingMatt commented on code/modules/projectiles/pins.dm
> +	if(user.can_commune() || user.psi)
```suggestion
	if(user.can_commune())
```
`can_commune` already checks for the presence of psi.

2022-08-09 10:47 UTC, Dreamykass approved these changes

2022-08-21 10:43 UTC, Arrow768 commented
The side-effects have been acknowledged by the skrell lore team via discord.

2022-08-27 18:34 UTC, Arrow768 approved these changes

2022-10-04 17:18 UTC, DreamySkrell commented
This could be merged then.

2022-10-09 15:50 UTC, NonQueueingMatt approved these changes

2022-10-09 15:53 UTC, merged