new safe sprite
Aurorastation/Aurora.3 pull request #14563
Opened 2022-08-07 04:26 UTC by alsoandanswer

- imageadd: "New sprites for safes and floorsafes." ported from /tg/

2022-08-07 10:58 UTC, alsoandanswer commented
!review

2022-08-07 14:41 UTC, SleepyGemmy commented
the spritesheet.

![image](https://user-images.githubusercontent.com/99297919/183296339-1e1bd4a8-66cb-48f7-bde2-5fbe4887b506.png)

2022-08-07 14:41 UTC, SleepyGemmy requested changes
there seems to be some stray pixels in "safe-open" and "safe-open-broken".

2022-08-09 14:12 UTC, Alberyk approved these changes

2022-08-11 14:11 UTC, NonQueueingMatt approved these changes

2022-08-11 14:24 UTC, merged