Fixes Fail2Topic IP Banning
Aurorastation/Aurora.3 pull request #14573
Opened 2022-08-08 12:21 UTC by SleepyGemmy

description in PR.

2022-08-08 12:21 UTC, SleepyGemmy commented
!review

2022-08-08 16:54 UTC, Arrow768 approved these changes

2022-08-08 16:55 UTC, Arrow768 requested changes
Technically it's fine, but the author is not credited in the changelog

2022-08-08 21:27 UTC, SleepyGemmy commented
> Technically it's fine, but the author is not credited in the changelog

addressed.

2022-08-09 10:30 UTC, NonQueueingMatt approved these changes

2022-08-09 14:11 UTC, Alberyk approved these changes

2022-08-10 04:43 UTC, Arrow768 approved these changes

2022-08-10 10:26 UTC, merged