Tweaks Unconsciousness
Aurorastation/Aurora.3 pull request #14626
Opened 2022-08-15 20:18 UTC by SleepyGemmy

description in PR.

2022-08-15 20:20 UTC, SleepyGemmy commented
!review

2022-08-20 19:29 UTC, Alberyk approved these changes

2022-08-21 10:02 UTC, Arrow768 requested changes

2022-08-21 10:02 UTC, Arrow768 commented on code/modules/organs/internal/lungs.dm
> -			owner.Paralyse(3)
The removal should be in the changelog

2022-08-21 17:14 UTC, SleepyGemmy commented on code/modules/organs/internal/lungs.dm
> -			owner.Paralyse(3)
addressed.

2022-08-21 17:42 UTC, Arrow768 approved these changes

2022-08-21 17:44 UTC, merged