Bridge Control APC is Now Critical
Aurorastation/Aurora.3 pull request #14631
Opened 2022-08-16 03:05 UTC by WickedCybs

The bridge control APC (command room, with the piloting consoles and stuff) had a non-critical APC, so during the random event the ship might potentially go out of control when the helm loses power. It's been marked critical due to its extreme important, just like the how the thrusters are marked the same.

2022-08-16 03:05 UTC, WickedCybs commented
!review

2022-08-16 03:05 UTC, WickedCybs commented
!bugfix

2022-08-16 03:19 UTC, SleepyGemmy requested changes

2022-08-16 03:19 UTC, SleepyGemmy commented on maps/sccv_horizon/sccv_horizon-3_deck_3.dmm
>  /obj/machinery/power/apc{
please use the critical subtype.

2022-08-16 05:42 UTC, WickedCybs commented on maps/sccv_horizon/sccv_horizon-3_deck_3.dmm
>  /obj/machinery/power/apc{
ok

2022-08-17 16:49 UTC, NonQueueingMatt approved these changes

2022-08-17 16:58 UTC, merged