Adds the Port Antillia Accent and Origin
Aurorastation/Aurora.3 pull request #14650
Opened 2022-08-18 12:32 UTC by SilvieSZ

Adds a Port Antillia accent and Origin to go with the upcoming lore.

Accent Sprite by Caelphon

2022-08-18 12:32 UTC, SilvieSZ commented
!review

2022-08-18 12:56 UTC, alsoandanswer approved these changes

2022-08-18 17:39 UTC, NonQueueingMatt requested changes

2022-08-18 17:39 UTC, NonQueueingMatt commented on code/modules/background/accent/human.dm
> +	description = "There are two distinct dialects present on the planet, one that sees heavy lifting from Tradeband and the other more influenced by Solarian Common. It is relatively easy to identify t
```suggestion
	description = "There are two distinct dialects present on the planet: one that sees heavy lifting from Tradeband and the other more influenced by Solarian Common. It is relatively easy to identify the differences between the two: Antilleans influenced by Tradeband sound more nasal and rhythmic, whereas those that grew up in regions where Solarian Common is the dominant language are more soft-spoken and enunciated."
```

2022-08-18 17:39 UTC, NonQueueingMatt commented on code/modules/background/origins/origins/human/sol.dm
> +    desc = "A former middle ring Solarian colony annexed into the Corporate Reconstruction Zone following the Solarian Collapse. Port Antillia is an under-developed ocean world with a unique, unstabl
```suggestion
    desc = "A former middle ring Solarian colony annexed into the Corporate Reconstruction Zone following the Solarian Collapse. Port Antillia is an under-developed ocean world with a unique, unstable geological profile and strong tradition of regional governance. Now with the formation of a unified planetary government within the Corporate Reconstruction Zone, Port Antillia looks forward to a hopeful, brighter future."
```

2022-08-18 17:39 UTC, NonQueueingMatt commented on code/modules/background/origins/origins/human/sol.dm
> +    important_information = "Due to the rather insular and unstable history of Port Antillia as the singular colonisation attempt by the Caribbean Federation. <b>Characters born on Port Antillia will
```suggestion
    important_information = "Due to the rather insular and unstable history of Port Antillia as the singular colonisation attempt by the Caribbean Federation, <b>characters born on Port Antillia will have names and appearances consistent with the peoples of the Antilles.</b> Only those native to Port Antillia may take its accent. This is enforceable by server moderators and admins."
```

2022-08-19 13:06 UTC, NonQueueingMatt approved these changes

2022-08-21 14:08 UTC, merged