New and Reworked HUD ID icons
Aurorastation/Aurora.3 pull request #14664
Opened 2022-08-19 12:54 UTC by 1Sparky1

Resprites all the previous ID icons for security HUDs, as well as adding in icons for the new NBT roles that were missing them.

I've deliberately kept the icons simpler than they were before. If that isn't the direction desired I can redo them again.

2022-08-19 12:54 UTC, 1Sparky1 commented
!review

2022-08-19 13:00 UTC, NonQueueingMatt requested changes
Investigator HUD icon needs to be changed, it's way too close to the unknown icon.
The security officer/cadet icons seem kind of weird -- from the icon diffs, they don't look symmetrical?
The Ops icons are a bit weird -- the grey blends into the dark brown a bit too much.

2022-08-20 15:55 UTC, NonQueueingMatt approved these changes

2022-08-20 19:27 UTC, Alberyk approved these changes

2022-08-22 12:59 UTC, merged