Portable Memory Wiper.
Aurorastation/Aurora.3 pull request #14696
Opened 2022-08-22 13:06 UTC by alsoandanswer

Hiya folks, Cave Johnson here.

I can't really think of a bit right now so just imagine reading everything in my voice for a few minutes.

https://user-images.githubusercontent.com/42310821/185928319-645124fe-439c-4a9b-9993-894079395714.mp4

2022-08-22 13:32 UTC, TheStryker commented
Synth team approves.

2022-08-22 13:35 UTC, NonQueueingMatt requested changes

2022-08-22 13:35 UTC, NonQueueingMatt commented on code/game/objects/items/devices/memorywiper.dm
> +			to_chat(attached, "<b>The process finishes, leaving you with nothing beyond your base programming and databases.</b>")
**Strongly** reccomend adding a ghost prompt here. Most people don't want to play non-characters and would rather just go do something else.

2022-08-22 13:51 UTC, NonQueueingMatt requested changes
Put the wiper in the RD's locker and not on the table.

2022-08-22 13:51 UTC, NonQueueingMatt commented on code/game/objects/items/devices/memorywiper.dm
> +	var/mob/living/carbon/human/attached = null
Clean this up in Destroy().

2022-08-22 13:51 UTC, NonQueueingMatt commented on code/game/objects/items/devices/memorywiper.dm
> +		sleep(600-rand(0,75))
This shouldn't be a sleep, but a timer that leads to another proc. We shouldn't sleep in attack_hand as this sleeps the entire proc.

2022-08-22 14:34 UTC, alsoandanswer commented
!review

2022-08-24 14:55 UTC, Snowy1237 commented
Does it work only on IPCs or on borgs too?

2022-08-27 18:05 UTC, Arrow768 approved these changes

2022-08-29 19:59 UTC, NonQueueingMatt approved these changes

2022-08-29 20:02 UTC, merged