TEG resprite
Aurorastation/Aurora.3 pull request #14705
Opened 2022-08-23 09:52 UTC by alsoandanswer

Ported from Bay.

![dreamseeker_njPoLshIAg](https://user-images.githubusercontent.com/42310821/186128808-d439e479-6362-4912-a230-76e1d4f5beda.gif)

2022-08-23 09:53 UTC, alsoandanswer commented
!review

2022-08-23 14:43 UTC, SleepyGemmy requested changes

2022-08-23 14:43 UTC, SleepyGemmy commented on code/modules/atmospherics/components/binary_devices/circulator.dm
> +		return 1
```suggestion
		return TRUE
```

2022-08-23 14:43 UTC, SleepyGemmy commented on code/modules/atmospherics/components/binary_devices/circulator.dm
> +			overlays += image('icons/obj/power.dmi', temperature_overlay)
```suggestion
			add_overlay(temperature_overlay)
```

2022-08-23 14:43 UTC, SleepyGemmy commented on code/modules/atmospherics/components/binary_devices/circulator.dm
> +			overlays += image('icons/obj/power.dmi', "circ-run")
```suggestion
			add_overlay("circ-run")
```

2022-08-23 14:43 UTC, SleepyGemmy commented on code/modules/atmospherics/components/binary_devices/circulator.dm
> +			overlays += image('icons/obj/power.dmi', "circ-slow")
```suggestion
			add_overlay("circ-slow")
```

2022-08-23 14:43 UTC, SleepyGemmy commented on code/modules/atmospherics/components/binary_devices/circulator.dm
> +		overlays += image('icons/obj/power.dmi', "circ-off")
```suggestion
		add_overlay("circ-off")
```

2022-08-23 14:43 UTC, SleepyGemmy commented on code/modules/atmospherics/components/binary_devices/circulator.dm
>  	return 1
```suggestion
	return TRUE
```

2022-08-23 14:43 UTC, SleepyGemmy commented on code/modules/atmospherics/components/binary_devices/circulator.dm
>  					"You hear a ratchet")
```suggestion
					"You hear a ratchet.")
```

2022-08-23 14:43 UTC, SleepyGemmy commented on code/modules/power/generator.dm
> +			overlays += image('icons/obj/power.dmi', "teg-op[lastgenlev]")
```suggestion
			add_overlay("teg-op[lastgenlev]")
```

2022-08-23 14:43 UTC, SleepyGemmy commented on code/modules/power/generator.dm
> +			playsound(src.loc, 'sound/effects/beam.ogg', 25, 0, 10, , required_preferences = ASFX_AMBIENCE)
```suggestion
			playsound(get_turf(src), 'sound/effects/beam.ogg', 25, FALSE, 10, , required_preferences = ASFX_AMBIENCE)
```

2022-08-28 16:26 UTC, SleepyGemmy approved these changes
suggested changes addressed.

2022-08-28 16:38 UTC, SleepyGemmy requested changes

2022-08-28 16:38 UTC, SleepyGemmy commented on code/game/machinery/atmoalter/portable_atmospherics.dm
> +			playsound(src.loc, W.usesound, 50, 1)
```suggestion
			playsound(get_turf(src), W.usesound, 50, 1)
```

2022-08-28 16:38 UTC, SleepyGemmy commented on code/game/machinery/atmoalter/portable_atmospherics.dm
> +					playsound(src.loc, W.usesound, 50, 1)
```suggestion
					playsound(get_turf(src), W.usesound, 50, 1)
```

2022-09-20 20:09 UTC, SleepyGemmy approved these changes
suggested changes addressed.

2022-09-24 10:44 UTC, NonQueueingMatt approved these changes

2022-10-22 20:30 UTC, merged