SecHUD QoL Things
Aurorastation/Aurora.3 pull request #14725
Opened 2022-08-25 12:50 UTC by 1Sparky1

Adds a unique rank for both Surgeon and Passenger, who previously used the Physician and Visitor ("Off-Duty") ranks, so used their ID icons.

Changes get_sec_hud_icon to use GetIdCard like airlocks, so IDs in hand or on a wrist slot are recognised.

2022-08-25 12:50 UTC, 1Sparky1 commented
!review

2022-08-29 20:08 UTC, NonQueueingMatt requested changes

2022-08-29 20:08 UTC, NonQueueingMatt commented on code/modules/mob/living/living.dm
> +		BITSET(hud_updateflag, ID_HUD) //If we drop our ID, update ID HUD
Pretty sure you want to use GetID() here.

2022-08-29 20:08 UTC, NonQueueingMatt commented on code/game/objects/items/weapons/cards_ids.dm
> +
```suggestion
```
extra whitespace

2022-11-01 12:16 UTC, closed without merging