Oh god, he can't hear us, he's got airpods on
Aurorastation/Aurora.3 pull request #14756
Opened 2022-09-01 18:23 UTC by alsoandanswer

"Adds earbuds. Also makes earphones and headphones colorable."

2022-09-01 18:23 UTC, alsoandanswer commented
!review

2022-09-01 19:50 UTC, SleepyGemmy requested changes
make the items you touch into contained sprites, please.

2022-09-20 19:51 UTC, SleepyGemmy approved these changes
suggested changes addressed.

2022-09-25 10:46 UTC, NonQueueingMatt requested changes

2022-09-25 10:46 UTC, NonQueueingMatt commented on code/modules/clothing/ears/earmuffs.dm
> +	desc = "Has a tendency to snag itself on whatever furniture it can find at the most inopportune of times."
Double definition

2022-10-17 19:25 UTC, NonQueueingMatt approved these changes

2022-10-22 20:31 UTC, merged