Makes More Objects Climbable
Aurorastation/Aurora.3 pull request #14750
Opened 2022-08-30 15:49 UTC by SleepyGemmy

this PR makes gas canisters and closets climbable.

2022-08-30 17:16 UTC, SleepyGemmy commented
!review

2022-09-01 02:02 UTC, alsoandanswer reviewed
Could just get rid of the climbable variable. You can combine it with climb_time, by making it so anything with a climb_time of 0 or -1 be unclimbable.

2022-09-01 02:05 UTC, alsoandanswer commented on code/game/objects/objs.dm
> +/obj/proc/can_touch(var/mob/user)
use_check_and_message() can probably be used here instead

2022-09-14 11:07 UTC, NonQueueingMatt requested changes

2022-09-14 11:07 UTC, NonQueueingMatt commented on code/game/objects/objs.dm
> +		shake_object()
this is missing a ..()

2022-12-01 12:17 UTC, SleepyGemmy commented
closing for now.

2022-12-01 12:17 UTC, closed without merging

2024-02-21 00:22 UTC, SleepyGemmy commented
not pursuing this.