Adds prescription safety goggles/glasses
Aurorastation/Aurora.3 pull request #14770
Opened 2022-09-05 20:13 UTC by SapphicOverload

Adds prescription safety goggles and glasses

2022-09-06 08:18 UTC, SapphicOverload commented
!review

2022-09-06 08:44 UTC, alsoandanswer approved these changes

2022-09-06 10:10 UTC, SleepyGemmy requested changes
you need a changelog as well.

2022-09-06 10:10 UTC, SleepyGemmy commented on code/modules/clothing/glasses/glasses.dm
> +/obj/item/clothing/glasses/safety
path.

2022-09-06 10:10 UTC, SleepyGemmy commented on code/modules/clothing/glasses/glasses.dm
> +	desc = "A simple pair of safety glasses. Thinner than their goggle counterparts, and comes with prescription overlay."
```suggestion
	desc = "A simple pair of safety glasses. Thinner than their goggle counterparts and comes with a prescription overlay."
```

2022-09-06 10:10 UTC, SleepyGemmy commented on code/modules/clothing/glasses/glasses.dm
> +	desc = "A simple pair of safety goggles. It's general chemistry all over again. Comes with prescription overlay."
```suggestion
	desc = "A simple pair of safety goggles. It's general chemistry all over again. Comes with a prescription overlay."
```

2022-09-06 10:10 UTC, SleepyGemmy commented on code/modules/client/preference_setup/loadout/loadout_eyes.dm
> +	goggles["goggles, safety, prescription"] = /obj/item/clothing/glasses/safety/goggles/prescription
```suggestion
	goggles["goggles, safety (prescription)"] = /obj/item/clothing/glasses/safety/goggles/prescription
```

2022-09-06 10:10 UTC, SleepyGemmy commented on code/modules/client/preference_setup/loadout/loadout_eyes.dm
> +	glasses["glasses, safety, prescription"] = /obj/item/clothing/glasses/safety/prescription
```suggestion
	glasses["glasses, safety (prescription)"] = /obj/item/clothing/glasses/safety/prescription
```

2022-09-06 20:33 UTC, SleepyGemmy approved these changes

2022-09-07 13:48 UTC, KingOfThePing approved these changes

2022-09-13 10:31 UTC, merged