Bluespace Transit to Space Transit
Aurorastation/Aurora.3 pull request #14788
Opened 2022-09-09 20:51 UTC by WickedCybs

Since the start, we've had all the shuttles go into a bluespace zone when moving to another zlevel, but in-universe they're not actually doing that. They're all mostly sublight shuttles. I wanted to change this, to remove any further confusion. So, what I noticed was that while we did port the bay movement effects we did not actually put them to use on a transition or port that associated code.

Touches a lot of files but this ended up being a pretty easy change, given it was mostly just replacements. The bluespace transit still exists but it is its own subpath now of the "transit" turfs.

![2022SeptemberFriday09144639](https://user-images.githubusercontent.com/52309324/189441667-e5e6af90-b59e-4900-b919-abee0b82d9f4.gif)

2022-09-09 20:51 UTC, WickedCybs commented
!review

2022-09-14 11:08 UTC, NonQueueingMatt approved these changes

2022-11-01 14:24 UTC, SleepyGemmy requested changes
L3199 to L3216 in `maps/away/ships/orion_express_ship.dmm` have dirty variables.
i.e.
`desc = s"A cap worn during showers. Keeps your hair save from horrible water.";`
to
`desc = "A cap worn during showers. Keeps your hair save from horrible water.";`
this can be edited directly in the map's file.

2022-11-01 19:21 UTC, SleepyGemmy approved these changes
never mind. PR looks good.

2022-11-05 21:53 UTC, merged