Deck Two - Extended Fore Hallway Area & Separated Stargazer Area
Aurorastation/Aurora.3 pull request #14797
Opened 2022-09-11 08:01 UTC by WickedCybs

This PR does two things. First of all.

![image](https://user-images.githubusercontent.com/52309324/189517680-200750ea-d5d2-4d45-bbcf-4512e465e8c0.png)

This entire hallway between the kitchen and bar is considered an extension of the bar, so it was linked to its power and switch and thus, started of. I replaced it with the Horizon fore hallway so the lights start on, and honestly It's probably a bit more sensible anyway.

Secondly.

![image](https://user-images.githubusercontent.com/52309324/189517742-b32a5bda-7cf9-43f6-86b0-74ecc54778c2.png)

This single APC has been powering the entire hall all along medical to operations and the entire huge hallway area by the Stargazer. It ended up being a critical fault and became a reason why atmos and power issues really screwed up this central area.

![image](https://user-images.githubusercontent.com/52309324/189517773-cb7b8e34-5537-4824-9d14-fbcae49da74b.png)

I added an APC here and It's considered its own area now, which will help with power management and engineering solutions .

2022-09-11 08:01 UTC, WickedCybs commented
!review

2022-09-11 12:41 UTC, SleepyGemmy requested changes
due to how jukeboxes play music (i.e. it plays to the entire area it is in), extending the fore hallway area down to where the bar area previously was is going to make the wall mounted audioconsole next to the cigarette machine play its music to the entire hallway area. the way it was previously mapped was intentional to avoid this.
removing the audioconsole is probably the easiest solution to avoid this.

2022-09-11 12:41 UTC, SleepyGemmy commented on maps/sccv_horizon/code/sccv_horizon_areas.dm
> +
stray newline.

2022-09-11 20:44 UTC, WickedCybs commented on maps/sccv_horizon/code/sccv_horizon_areas.dm
> +
Resolved.

2022-09-11 20:44 UTC, WickedCybs commented
Removed the audio console in that hall.

2022-09-12 08:38 UTC, SleepyGemmy approved these changes
suggested changes addressed. mapping looks fine.

2022-09-14 11:10 UTC, NonQueueingMatt approved these changes

2022-10-22 20:31 UTC, merged