Long-Range Holopads on the Same Z-Level Can Call Each Other
Aurorastation/Aurora.3 pull request #14819
Opened 2022-09-15 04:05 UTC by WickedCybs

It really salted my onions to suddenly not be able to do holocalls with the bridge or see what's even happening if I was docked at the Horizon at all. Radio doesn't really cut it. It's a voluntary system, lets you see whats up on each end + get emotes and for third parties stuck in their docks it's way easier to just communicate with the bridge like that than just yell on the radio for someone to open up.

2022-09-15 04:05 UTC, WickedCybs commented
!review

2022-09-15 04:09 UTC, Jaraci commented
salted my onions

2022-09-15 04:10 UTC, Jaraci approved these changes

2022-09-15 19:09 UTC, NonQueueingMatt approved these changes

2022-09-18 11:35 UTC, Arrow768 requested changes
The changelog is not correct.
The removed check determines if the holopads are on connected z levels and not if they are on the same z level

2022-09-21 00:46 UTC, WickedCybs commented
> The changelog is not correct. The removed check determines if the holopads are on connected z levels and not if they are on the same z level

Forgot to respond. Fixed the changelog.

2022-09-21 18:14 UTC, Arrow768 approved these changes

2022-09-21 18:23 UTC, merged