Reskins some mapped-in radios to their departmental colours + minor responder bay tweaks
Aurorastation/Aurora.3 pull request #14825
Opened 2022-09-16 21:15 UTC by Jaraci

See title. I offset the rescue RIGs in the responder bay from each other to make it clear there are two and moved FR armbands from the loadout to their lockers.

Furthermore, only the responders' lockers had the medical stationbounceds in them before; now the ones on the table use that skin too. Security had no security-themed stationbounceds either, and now it does.

2022-09-16 21:15 UTC, Jaraci commented
!review

2022-09-17 00:17 UTC, SleepyGemmy approved these changes
looks fine.

2022-09-18 11:37 UTC, Arrow768 requested changes

2022-09-18 11:37 UTC, Arrow768 commented on code/modules/client/preference_setup/loadout/loadout_accessories.dm
> -	armbands["first responder armband"] = /obj/item/clothing/accessory/armband/medgreen
Undocumented change.

2022-11-01 12:17 UTC, closed without merging