Sorts DESC_LORE and DESC_FLUFF
Aurorastation/Aurora.3 pull request #14837
Opened 2022-09-20 17:28 UTC by alsoandanswer

Seperates out the jokes in desc_fluff from actual lore for consistency.

relies on https://github.com/Aurorastation/Aurora.3/pull/14836.

2022-09-20 17:28 UTC, alsoandanswer commented
!review

2022-09-20 17:52 UTC, SleepyGemmy requested changes
(a paste from the previous PR since this does the same thing as 14836.)



jokes don't belong in the descriptions of items, since they're descriptions.
if something is more of a quip or humorous observation, then it could fit in desc_fluff (see the example below).
the reason a cultist description exists is because only cultists can do certain interactions with certain items, not every antagonist.

for reference:
desc is for shorthand descriptions of items. example: "A lightbulb made out of glass."
desc_fluff is for longer descriptions of items, extra information, and/or lore. example: "This particular lightbulb is manufactured by the Idris Incorporation for use in service installations across the galaxy. Commonly thought to be of cheap quality."
desc_antag is for antagonism descriptions.
desc_cult is for cultist related descriptions.

2022-09-20 17:52 UTC, SleepyGemmy commented on code/game/atoms.dm
> +	var/desc_fluff = null // Text about the atom's fluff description, if any exists. Reserved for funny jokes and snarky comments, mostly.
this is not true and is a subjective appropiation of the variable.

2022-09-24 10:42 UTC, NonQueueingMatt requested changes

2022-09-24 10:42 UTC, NonQueueingMatt commented on code/game/atoms.dm
> +	var/desc_lore = null // Purple text (SPAN_CULT()) that gives the atom's lore info, be it species, corporate or whatever.
Not SPAN_CULT anymore.

2022-11-28 22:35 UTC, SleepyGemmy commented
closing as PR 14843 was merged.

2022-11-28 22:35 UTC, closed without merging