Records and ID change
Aurorastation/Aurora.3 pull request #14846
Opened 2022-09-21 20:19 UTC by MortalRed

Records and ID card will no longer show assigned sex at birth. This will allow the player to disclose as much or as little as they want on a record-by-record basis.

2022-09-21 20:23 UTC, MortalRed commented
!review

2022-09-21 20:37 UTC, NonQueueingMatt commented
Wouldn't it make sense to just disclose gender instead? Not everyone has records, and these basic fields are meant to provide the very basic details.

2022-09-21 20:43 UTC, MortalRed commented
That was the original intent, but because the relevant dm files are in completely different locations, I wasn't able to rely on calling get_pronoun() like I was able to last time.

2022-09-22 10:25 UTC, NonQueueingMatt commented
> That was the original intent, but because the relevant dm files are in completely different locations, I wasn't able to rely on calling get_pronoun() like I was able to last time.

I'm not sure I follow the reasoning here, there's no reason you can't use get_pronoun. If you're confused on how to use it I can help you there.

2022-09-24 01:21 UTC, NonQueueingMatt requested changes

2022-09-24 01:21 UTC, NonQueueingMatt commented on code/game/objects/items/weapons/cards_ids.dm
> -	dat += text("Sex: []</A><BR>\n", sex)
Needs gender.

2022-09-24 01:21 UTC, NonQueueingMatt commented on code/modules/paperwork/filingcabinet.dm
> -Sex: [R.sex]<BR>
Needs gender.

2022-09-24 01:21 UTC, NonQueueingMatt commented on code/modules/paperwork/filingcabinet.dm
> -Sex: [R.sex]<BR>
Needs gender.

2022-11-01 21:15 UTC, MortalRed commented
Oh wow it's been how long since I've last looked at this?
Gonna close this one, get an update, clean some thing up, figure out how on Earth I'm supposed to get this to work with IDs, and so on.
It'll be back Soon:tm:

2022-11-01 21:15 UTC, closed without merging