Adds the new health analyser noises to PDA scanners and mech scanners
Aurorastation/Aurora.3 pull request #14860
Opened 2022-09-24 17:50 UTC by Jaraci

See title.

2022-09-24 17:50 UTC, Jaraci commented
!review

2022-09-24 17:51 UTC, NonQueueingMatt approved these changes

2022-09-24 18:28 UTC, alsoandanswer approved these changes

2022-09-24 18:28 UTC, alsoandanswer requested changes
You need to put in the spam limiter.

2022-09-24 20:28 UTC, Jaraci commented
> You need to put in the spam limiter.

That should be it now, unless I'm mistaken!

2022-09-27 02:05 UTC, alsoandanswer commented on code/modules/heavy_vehicle/equipment/medical.dm
> +	if(last_scan <= world.time - 20) //Spam limiter.
```suggestion
	sound_scan = FALSE
	if(last_scan <= world.time - 20) //Spam limiter.
```

2022-10-04 00:22 UTC, alsoandanswer approved these changes

2022-10-04 08:00 UTC, merged