Custom items 12/10/22
Aurorastation/Aurora.3 pull request #14923
Opened 2022-10-13 00:08 UTC by Alberyk

Adds the following custom items:
https://forums.aurorastation.org/topic/17397-ahekes-thermal-coat
https://forums.aurorastation.org/topic/17432-the-ahzi-fleet-kit
https://forums.aurorastation.org/topic/17562-ielias-starfinder

Also removes items from characters that no longer exists or have not been played for over a year

2022-10-18 19:24 UTC, SleepyGemmy requested changes
some sprites in "icons/obj/custom_items/ielia_tarot.dmi" also have uppercase names and spaces instead of underscores.

2022-10-18 19:24 UTC, SleepyGemmy commented on code/modules/customitems/item_defines.dm
> +	desc = "A very heavy, well padded and generally quite large grey overcoat, probably made for an Unathi, made out of a rather stiff, almost leathery type substance. With a brown synthetic fur \
```suggestion
	desc = "A very heavy, well padded, and generally quite large grey overcoat, probably made for an Unathi, made out of a rather stiff, almost leathery type substance. With a brown synthetic fur \
```

2022-10-18 19:24 UTC, SleepyGemmy commented on code/modules/customitems/item_defines.dm
> +	collar and even more fleecing inside. Interestingly enough there does not seem to be an easy way of closing it. Emblazoned on the back in a large red letters is \"K6\""
```suggestion
	collar and even more fleecing inside. Interestingly enough, there does not seem to be an easy way of closing it. Emblazoned on the back in large red letters is \"K6\"."
```

2022-10-18 19:24 UTC, SleepyGemmy commented on code/modules/customitems/item_defines.dm
> +	desc = "A flag bearing the easily recognizable inconography of Unathi fleets, this one depicting a Sinta slain by spears under an omniscient, uncaring eye."
```suggestion
	desc = "A flag bearing the easily recognizable iconography of the Unathi fleets, this one depicting a Sinta slain by spears under an omniscient, uncaring eye."
```

2022-10-18 19:24 UTC, SleepyGemmy commented on code/modules/customitems/item_defines.dm
> +	desc = "A flag bearing the easily recognizable inconography of Unathi fleets, this one depicting a Sinta slain by spears under an omniscient, uncaring eye."
```suggestion
	desc = "A flag bearing the easily recognizable iconography of the Unathi fleets, this one depicting a Sinta slain by spears under an omniscient, uncaring eye."
```

2022-10-18 19:24 UTC, SleepyGemmy commented on code/modules/customitems/item_defines.dm
> +	desc = "An armband bearing the easily recognizable inconography of Unathi fleets, this one depicting a Sinta slain by spears under an omniscient, uncaring eye."
```suggestion
	desc = "An armband bearing the easily recognizable iconography of the Unathi fleets, this one depicting a Sinta slain by spears under an omniscient, uncaring eye."
```

2022-10-18 19:24 UTC, SleepyGemmy commented on code/modules/customitems/item_defines.dm
> +	desc = "A small, bronze ball. It is heavy in the hand, and seems to have no switches or buttons on it. "
```suggestion
	desc = "A small, bronze ball. It is heavy in the hand and seems to have no switches or buttons on it. "
```

2022-10-24 15:16 UTC, SleepyGemmy approved these changes
requested changes addressed.

2022-10-24 17:43 UTC, NonQueueingMatt approved these changes

2022-10-24 22:51 UTC, merged