Consular access to SOME areas in command
Aurorastation/Aurora.3 pull request #14921
Opened 2022-10-12 18:27 UTC by Ben10083

Gives Consular access to command break room and meeting room and NOT bridge (please don't put me in maintainer hell I will be good I swear please)

2022-10-12 18:27 UTC, Ben10083 commented
!review

2022-10-17 19:24 UTC, NonQueueingMatt approved these changes

2022-10-18 19:04 UTC, SleepyGemmy requested changes
missing door.
![image](https://user-images.githubusercontent.com/99297919/196521064-9d4c33a6-2fbb-4d25-b1bf-1c92e26212e8.png)

2022-10-18 19:54 UTC, SleepyGemmy approved these changes

2022-10-20 13:01 UTC, SleepyGemmy approved these changes

2022-10-22 20:32 UTC, merged