Adds a new Gremorian infested away site
Aurorastation/Aurora.3 pull request #14944
Opened 2022-10-19 11:34 UTC by 4000daniel1

An asteroid hideout for a shady group of people who unfortunately found out they aren't alone on the asteroid.

My goal was to make a rather challenging away site, that rewards a properly organized expedition team with an intense experience. Very open to any suggestions or changes!

At the time of posting doesn't actually seem to be visitable from my testing. It spawns, but not on the overmap. Not sure why.

![Screenshot 2022-10-19 133136](https://user-images.githubusercontent.com/95170823/196679264-841d23c4-3a27-4151-8cbd-ce4f19620487.png)

2022-10-19 11:34 UTC, 4000daniel1 commented
!wip

2022-10-19 12:24 UTC, DreamySkrell commented
Cloned it locally to see the mapping. Some thoughts:
1. The loot is way too good. There is lots of weapons, there is at least 20 random loot crates, 6 bluespace crystals, 6 random high value items that can be powerful stuff like a actual breacher rig.
2. Simple NPC mobs are not really all that challenging to fight, and are mostly really just a matter of bringing enough guns and ammunition, and maybe metal for barricades to game the simple AI.
3. We do not really have the syndicate anymore. There are beds with syndicate bedsheets, and also a syndicate beacon that, if I am reading its code correctly, can make any random player a traitor.
4. Lots of phoron sheets scattered around, making it look like a mining station that mines phoron. Phoron is not really supposed to be mineable from any random asteroid in our setting, and only should exist in very specific places.
5. Lots of full phoron canisters there. With the phoron scarcity, these would be the best loot from this site. Consider making them all (or most of them at least) into the phoron_scarce variant.

2022-10-19 18:57 UTC, WickedCybs commented
This should show up on the overmap once the landmark is mapped in. I would reccomend changing the name of the map (as it appears on the overmap) to something other than "Lonely Asteroid" though as we have like three or two other maps using the same name atm. 

The map does work though and it's a good showing for your first PR. I'd suggest making the entry-point a proper airlock (that can cycle) or put some inflatables there to have it look run-down. As it currently is, people risk venting a lot of it, which might be fine still.

That said, you should remove the revolver at the least. That's kind of way too much.

2022-10-19 22:24 UTC, SleepyGemmy reviewed
some minor code typos aside, the PR looks fine.
note that the colossal greimorian can take 1100 damage, if this is what you intended.

## mapping feedback
![image](https://user-images.githubusercontent.com/99297919/196814246-78e787b5-ba70-498a-9dd7-d289b58c38ef.png)
missing corner wall.

2022-10-19 22:24 UTC, SleepyGemmy commented on maps/away/generic/shady.dm
> +
```suggestion
```

2022-10-19 22:24 UTC, SleepyGemmy commented on maps/away/generic/shady.dm
> +	name="hideout outpost"
```suggestion
	name = "hideout outpost"
```

2022-10-19 23:55 UTC, SleepyGemmy approved these changes

2022-10-20 13:26 UTC, 4000daniel1 commented
After a bunch of changes, I feel ready to call this finished.

2022-10-20 13:26 UTC, 4000daniel1 commented
!wip

2022-10-21 03:49 UTC, WickedCybs requested changes
You should replace the shotgun slugs you mapped in with buckshot. Same reason as the .50 here, It's way too much firepower to a site that doesn't need it, as these are unarmoured simple mobs.

2022-10-22 18:37 UTC, NonQueueingMatt approved these changes

2022-10-22 20:32 UTC, merged