Reverts new backpack sprites
Aurorastation/Aurora.3 pull request #14967
Opened 2022-10-22 20:44 UTC by NonQueueingMatt

Main reasons:

1. Alpha masks are broken (normal ones don't apply correctly and need to be raised a pixel or two) and don't cover the entire strap (the top right part specifically).
2. In hand sprites are missing for the new backpacks.
3. Bad community reception of the three-pixel strap.

2022-10-22 21:04 UTC, NonQueueingMatt commented
!review

2022-10-22 21:08 UTC, Alberyk approved these changes

2022-10-22 23:30 UTC, Arrow768 requested changes

2022-10-22 23:30 UTC, Arrow768 commented on SQL/migrate/V074__backbag_colors.sql
> - 	ADD COLUMN `backbag_strap` INT(11) NULL DEFAULT NULL AFTER `backbag_color`;
keep the sql migration or create one that reverts the already applied changes

2022-10-23 01:46 UTC, alsoandanswer requested changes
I put out a fix (#14968), don't merge this.

2022-10-23 08:44 UTC, closed without merging