Removes hats from starting/default uniforms
Aurorastation/Aurora.3 pull request #14976
Opened 2022-10-24 16:29 UTC by DreamySkrell

changes:
  - rscdel: "Removes hats from starting/default uniforms. All the hats can still be selected in the loadout, or found in lockers."
  - rscadd: "Adds uniform hats to relevant jobs' lockers, where missing"

hats begone

2022-10-24 16:29 UTC, DreamySkrell commented
!review

2022-10-24 21:15 UTC, SleepyGemmy commented on code/modules/client/preference_setup/loadout/loadout_head.dm
> +	display_name = "bridge crew cap, san colettish"
```suggestion
	display_name = "bridge crew cap (san colettish)"
```

2022-10-24 21:16 UTC, SleepyGemmy approved these changes
PR looks fine as far as i can see.

2022-10-24 23:30 UTC, alsoandanswer requested changes
Adding them to the lockers is good (and should be moved to a different PR) but won't solve the issue that they will run out after long rounds.

This implementation is rather extreme and I would not like this merged unless it is changed

The goal of this PR, to have default hats not coincide with outfits can be as easily achieved by having a simple loadout toggle rather than the nuclear option of removing ALL the hats from the default uniforms.

2022-10-25 08:18 UTC, DreamySkrell commented
> Adding them to the lockers is good (and should be moved to a different PR) but won't solve the issue that they will run out after long rounds.

The goal of this PR is not to solve the issue of gear running out on long rounds, and it should not be. This PR does not affect this issue, and does not make it worse nor better. All the hats still exist, in lockers and/or the loadout. Same as all the other gear, uniforms, alt-uniforms, and everything else.

> This implementation is rather extreme and I would not like this merged unless it is changed

Changed how. Do not use the "changes requested" tag if you disagree with this PR completely.

> The goal of this PR, to have default hats not coincide with outfits can be as easily achieved by having a simple loadout toggle rather than the nuclear option of removing ALL the hats from the default uniforms.

Disagreed. We do not need more microspecific toggles. This is not the nuclear option. All the hats still exist, in lockers and/or the loadout.

2022-10-25 08:43 UTC, GMR25 commented
A bit unfair for those who already had full loadouts and may not be able to afford the hat to finish their appearance, especially if they latejoined in a round where their slot had been taken before so the clothing in the locker is gone. I truly do not understand the issue with spawning with hats.

2022-10-25 09:35 UTC, DreamySkrell commented
> A bit unfair for those who already had full loadouts and may not be able to afford the hat to finish their appearance, 

You could say the same about the alternative uniforms too, or drip in general. In the current system, there is no way to make everyone happy, unfortunately.

> especially if they latejoined in a round where their slot had been taken before so the clothing in the locker is gone.

They're just hats. They still exist. Most people do not wear hats anyways. The probability that someone was in the round before you, and wore the exact same outfit as you that included the hat, is very slim. People leaving the round with actual gear (tools, weapons, armor, etc) is a far more serious issue than hats.

> I truly do not understand the issue with spawning with hats.

The issue is. If you plan your outfit around not wearing a hat, you still have the hat in the loadout preview and when ghosting. It ruins the drip, and is annoying. You can press "hide job gear", but then you lose everything (uniform, boots, bag, radio, and anything else). People want to preview their loadout for some jobs without hats in the way. Most hats also very badly fit skrell or some robots, or are ugly and get very little use.

2022-10-25 11:11 UTC, Butterrobber202 commented
this not kosher. Esp since Engineers spawn with hats that have mechanical benefits for their job.

2022-10-25 11:14 UTC, DreamySkrell commented
> this not kosher. Esp since Engineers spawn with hats that have mechanical benefits for their job.

Not an issue. Engineers will be able to pick hard hats from the loadout or from the lockers.

2022-10-25 14:10 UTC, SleepyGemmy commented
> Adding them to the lockers is good (and should be moved to a different PR) but won't solve the issue that they will run out after long rounds.

i think that most if not all role-related hats are in the loadout already.

2022-10-25 14:15 UTC, SleepyGemmy requested changes
ensure that role-related hats exist in the loadout for all roles this PR touches and make them cost zero points. i suggest using the loadout "Faction" tab for this.

only exception is hardhats which should remain as they are, since they offer mechanical advantage.

2022-12-13 14:50 UTC, closed without merging