Adds High Visibility Jacket
Aurorastation/Aurora.3 pull request #14970
Opened 2022-10-23 18:40 UTC by KingOfThePing

To feel useful again and to procrastinate on a million other things this PR adds a high visibility jacket:
![2343253456346](https://user-images.githubusercontent.com/43940569/197409660-15978516-cd71-4ae1-a4e5-ae008b409b22.png)

It can be toggled open and closed and has two pocket slots. It covers the upper + lower torso as well as the arms.
Functionality has been tested locally and it works without issue.

### Asset Licenses
The following assets that **have not** been created by myself are included in this PR:

| Path | Original Author | License |
| --- | --- | --- |
| \icons\obj\clothing\suits.dmi (jacket_hazard)| Unknown (Shiptest) | CC0 |

2022-10-23 18:42 UTC, KingOfThePing commented
!review

2022-10-23 18:43 UTC, SleepyGemmy requested changes
contained sprite, please.

2022-10-23 18:45 UTC, KingOfThePing commented
Why? It's just another jacket without any special functionality

2022-10-23 18:56 UTC, SleepyGemmy commented
> Why? It's just another jacket without any special functionality

because contained sprites is the praxis.

2022-10-23 19:15 UTC, KingOfThePing commented
- re-shuffled the sprites into a contained sprite
- made it an alternate version of the existing high vis jacket
- added it to the loadout jacket selection

2022-10-23 19:26 UTC, SleepyGemmy commented on code/modules/clothing/suits/miscellaneous.dm
> -
unintentional (?) newline removal.

2022-10-23 19:26 UTC, SleepyGemmy commented on code/modules/clothing/suits/miscellaneous.dm
> -
unintentional (?) newline removal.

2022-10-23 19:26 UTC, SleepyGemmy commented on code/modules/clothing/suits/miscellaneous.dm
> +	contained_sprite = TRUE
newline below this line.

2022-10-23 19:26 UTC, SleepyGemmy commented on code/modules/clothing/suits/miscellaneous.dm
> +	desc = "A bright yellow jacket with reflective stripes. For use in operations, engineering and sometimes even law enforcement in cold and poor weather or when visibility is low."
```suggestion
	desc = "A bright yellow jacket with reflective stripes. For use in operations, engineering, and sometimes even law enforcement in cold and poor weather or when visibility is low."
```

2022-10-23 19:38 UTC, SleepyGemmy approved these changes
requested changes addressed. PR looks fine.

2022-10-24 18:26 UTC, NonQueueingMatt approved these changes

2022-10-28 00:52 UTC, merged