Fixes turf window alignment
Aurorastation/Aurora.3 pull request #15007
Opened 2022-11-01 07:00 UTC by alsoandanswer

Title.

Also a message to all spriters.

Avoid alpha layers. If you have to do this, use layers.

If you do above, avoid coloring them. Programatically color them.

IF YOU FLATTEN LAYERS INSTEAD OF USING OVERLAYS, IT WILL MAKE IT FUCKING IMPOSSIBLE TO REVERSE ENGINEER.

That is all.

2022-11-01 07:00 UTC, alsoandanswer commented
!review !bugfix

2022-11-01 07:00 UTC, alsoandanswer commented
!bugfix

2022-11-01 12:03 UTC, NonQueueingMatt requested changes

2022-11-01 12:03 UTC, NonQueueingMatt commented on aurorastation.dme
> -#include "code\modules\ghostroles\spawner\atom\combat_robot.dm"
Revert the DME changes

2022-12-10 12:36 UTC, NonQueueingMatt approved these changes

2022-12-10 12:37 UTC, merged