Engineering dept tweaks (plus I fix some mapping stuff I missed last time)
Aurorastation/Aurora.3 pull request #15025
Opened 2022-11-05 04:44 UTC by Jaraci

Fixes/addresses a lot of things that have been irritating about engineering lately:

- Adds an extra voidsuit to engineering's equipment room, for a total of 5.
- Adds 3 extra lockers to engineering's locker room, for a total of 7 (5 engineer slots and 2 apprentice slots)
- Adds some missing floor decals to engineering (oops, my bad)
- Adds two more fire lockers to engineering's main hallway (I just think they're neat...)
- Doubles the amount of airlock electronics in the Engi-Vend from 10 to 20. These can run out surprisingly quickly in some rounds.
- Maxed out the pressure value on the SM pumps by default, making setup less fiddly due to the laggy interface. They still all have to be turned on, though.
- Shuffled some other stuff around to make room for this (the only permanent casualty should be a spare radiation suit closet)

2022-11-05 04:44 UTC, Jaraci commented
!review

2022-11-05 06:52 UTC, companoo commented
> * Maxed out the pressure value on the SM pumps by default, making setup less fiddly due to the laggy interface. They still all have to be turned on, though.

Its so beautiful.

2022-11-05 15:07 UTC, Butterrobber202 commented
while you're here do you mind adding one-way exit access to the atmospherics door

2022-11-05 15:10 UTC, Jaraci commented
> while you're here do you mind adding one-way exit access to the atmospherics door

Sure!

2022-11-05 19:54 UTC, SleepyGemmy requested changes
![image](https://user-images.githubusercontent.com/99297919/200138384-61aa8473-24d9-4143-908a-dc13469a2a31.png)'
stray pump.

![image](https://user-images.githubusercontent.com/99297919/200138391-058e1e78-d950-465d-b715-99de2f9e612a.png)
3 fire lockers in immediate vicinity of eachother is a bit overkill.

![image](https://user-images.githubusercontent.com/99297919/200138473-4198209b-9f0c-49a8-a96f-86ba178ae5fe.png)
stray floor decal and inaccessible corner locker.

2022-11-05 19:54 UTC, SleepyGemmy commented on html/changelogs/omicega-engitweaks.yml
> +  - rscadd: "Tweaked/added various things to engineering. Fixed lowercase area names, added some fire closets, an extra voidsuit, some more lockers to the equipment room, and some other QOL mapping s
```suggestion
  - maptweak: "Tweaked/added various things to engineering. Fixed lowercase area names, added some fire closets, an extra voidsuit, some more lockers to the equipment room, and some other QOL mapping stuff."
```

2022-11-06 04:08 UTC, Jaraci commented
Stray pump gone.

I moved one of the fire lockers a bit further away but still inside engineering. I think that's the one department which can't really complain about having _too much_ fire safety sitting around.

I swapped one locker with a disposal unit to allow them all to be more easily accessible & the floor decal should be cleaned up too.

2022-11-06 04:15 UTC, SleepyGemmy approved these changes
PR looks fine.

2022-11-08 23:20 UTC, NonQueueingMatt approved these changes

2022-11-08 23:23 UTC, merged