Feuer Frei!
Aurorastation/Aurora.3 pull request #15034
Opened 2022-11-06 12:36 UTC by TheDanseMacabre

Gives some third party ships ship to ship weapons, and buffs the small arms of a few more.

2022-11-06 12:37 UTC, TheDanseMacabre commented
!review

2022-11-06 15:46 UTC, Alberyk approved these changes

2022-11-07 08:00 UTC, SleepyGemmy reviewed
![image](https://user-images.githubusercontent.com/99297919/200255291-29c26cdf-d622-443f-9189-3c1992f55524.png)
stairwell goes right into the weapon (both SFA and FSF).

![image](https://user-images.githubusercontent.com/99297919/200255602-fa4b0fb9-f5d1-49f2-a066-057aa810b180.png)
not sure how i feel about the militia ship having a 7.62 assault rifle.

![image](https://user-images.githubusercontent.com/99297919/200255866-4bc3c1f7-a572-488e-8d31-ec12373cc12d.png)
ditto (for both SFA and FSF).

![image](https://user-images.githubusercontent.com/99297919/200256217-1617c540-63f6-4f9d-9927-6ff222e3f1c1.png)
ditto but 5.56.

2022-11-07 08:00 UTC, SleepyGemmy commented on html/changelogs/dansemacabre-feuerfrei.yml
> +  - rscadd: "The Elyran strike craft, FSF and SFA corvettes, and TCFL corvette now all have grauwolf flak batteries. The militia ship has a 40mm rotary cannon. The civilian station has a large amount
```suggestion
  - maptweak: "The Elyran strike craft, FSF and SFA corvettes, and TCFL corvette now all have grauwolf flak batteries. The militia ship has a 40mm rotary cannon. The civilian station has a large amount of ammunition to sell."
```

2022-11-07 14:20 UTC, TheDanseMacabre commented
> stairwell goes right into the weapon (both SFA and FSF).
That's fine
>people have rifles now
The increasing frequency with which other third party ships are equipped with rifles means that these factions need to have rifles of their own in order to have parity with other factions. I don't think it's fair for these factions to run around outgunned, and in any case the fact that rifles are being nerfed across the board and because of how we see third party ships act ingame makes it unlikely this is going to cause any practical problems, combined with the relatively limited quantity of ammunition per rifle.

2022-11-07 15:28 UTC, SleepyGemmy commented
> The increasing frequency with which [...]

fair.

2022-11-07 15:28 UTC, SleepyGemmy requested changes
![image](https://user-images.githubusercontent.com/99297919/200348992-480a70d2-abf3-4c29-9d97-d45990731713.png)
fix the SFA and FSF staircase.

2022-11-09 12:39 UTC, SleepyGemmy approved these changes
requested changes addressed.

2022-11-09 17:07 UTC, merged