[wip] Generic dungeons, random tramp freighter secret cargo hold
Aurorastation/Aurora.3 pull request #15030
Opened 2022-11-05 21:51 UTC by DreamySkrell

![image](https://user-images.githubusercontent.com/107256943/200142528-12e6060d-12d4-41f4-83f7-c142f0c2ddf8.png)
![image](https://user-images.githubusercontent.com/107256943/200142675-29a24114-32fa-4c2e-9057-99408504bd18.png)

# Explanation:
`place_dungeon_spawns_generic()`` called at `Initialize()` of a landmark.
In the tramp freighter, as in the image, the secret cargo hold gets one of the three rooms.

# Checklist:
- [x] first impl
- [ ] make sure this is actually wanted
- [ ] make sure it can't be misused
- [ ] maybe test merge to see the performance impact

2022-11-05 21:51 UTC, DreamySkrell commented
!wip

2022-11-15 22:15 UTC, DreamySkrell commented
!review

2022-11-23 10:47 UTC, NonQueueingMatt requested changes

2022-11-23 11:57 UTC, DreamySkrell commented on code/controllers/subsystems/initialization/map_dungeons_generic.dm
> +var/list/dungeon_generic_initialized = FALSE
These are used in
`/obj/effect/dungeon_generic_landmark/Initialize()`
and
```
proc/place_dungeons_generic()
	if(dungeon_generic_initialized)
		return
    ...
```

2022-12-13 15:09 UTC, JohnWildkins commented
See: Discussion in discord about current code / making this a subsystem

2023-02-03 22:56 UTC, NonQueueingMatt commented
Inactive

2023-02-03 22:56 UTC, closed without merging