Custom items 07/11/22
Aurorastation/Aurora.3 pull request #15048
Opened 2022-11-07 15:09 UTC by Alberyk

Adds this item: https://forums.aurorastation.org/topic/17585-osbornes-coat
-fixes #14984
-makes the starfinder better

2022-11-07 15:38 UTC, SleepyGemmy requested changes

2022-11-07 15:38 UTC, SleepyGemmy commented on code/modules/customitems/item_defines.dm
> +			to_chat(user, "These constelations are displayed on the starfinder: [first_card], [second_card] and [third_card].")
```suggestion
			to_chat(user, "The following constellations are displayed on the starfinder: [first_card], [second_card], and [third_card].")
```

2022-11-07 15:38 UTC, SleepyGemmy commented on code/modules/customitems/item_defines.dm
> +	name = "dominian officers trench coat"
```suggestion
	name = "dominian officer's trench coat"
```

2022-11-07 15:38 UTC, SleepyGemmy commented on code/modules/customitems/item_defines.dm
> +	desc = "An Imperial army trench coat that is used by Dominian officers in colder environments. this one is missing the unit insignia and has the symbol of a military count on its rank collar."
```suggestion
	desc = "An Imperial Army trench coat that is used by Dominian officers in colder environments. This one is missing the unit insignia and has the symbol of a military count on its rank collar."
```

2022-11-07 15:42 UTC, SleepyGemmy approved these changes

2022-11-12 21:58 UTC, NonQueueingMatt approved these changes

2022-11-12 22:02 UTC, merged