Enlarge intrepid helm
Aurorastation/Aurora.3 pull request #15106
Opened 2022-11-14 19:02 UTC by FluffyGhoster

Expanded the Intrepid helm room and moved the sensors console, added a window to allow the sensors console operator to see the people buckled and see the helm, added two softsuit dispensers to fill the space a little, made the window doors towards the cannon station a double window and duplicated it to the right of the sensors/helm area for symmetry.

![image](https://user-images.githubusercontent.com/65877598/201743870-80a59f1b-c9b6-4ea8-a32f-f1d133b7ce2d.png)

2022-11-16 17:13 UTC, FluffyGhoster commented
!review

2022-11-22 16:57 UTC, NonQueueingMatt approved these changes

2022-12-07 22:30 UTC, Alberyk approved these changes

2022-12-07 22:42 UTC, SleepyGemmy requested changes
map corruption.
![image](https://user-images.githubusercontent.com/99297919/206311971-7df84297-32bd-4a58-8e60-c88a35f8da04.png)

this room has vents, but no air alarm.
![image](https://user-images.githubusercontent.com/99297919/206312162-5bbcb077-51de-4a97-9973-aacc9d40cceb.png)

this room has an air alarm, but no vents. the windoors will probably get annoying as well.
the floor decals do not follow praxis.
![image](https://user-images.githubusercontent.com/99297919/206312191-9f2a45eb-c2d9-4d75-b12c-3b98fded1e5f.png)

not sure if these are empty suit storages or voidsuits. we already have some in EVA.
![image](https://user-images.githubusercontent.com/99297919/206312256-9f8a8e8f-d3c1-46cf-aa2e-2c0b4b281165.png)

these radios are the wrong way around.
![image](https://user-images.githubusercontent.com/99297919/206312528-d2c847a9-389b-4483-a697-7f40d7f4d5be.png)

2022-12-07 22:42 UTC, SleepyGemmy commented on html/changelogs/fluffyghost.yml
> +  - rscadd: "Expanded the Intrepid helm room and moved the sensors console, added a window to allow the sensors console operator to see the people buckled and see the helm, added two softsuit dispens
```suggestion
  - maptweak: "Expanded the Intrepid helm room and moved the sensors console, added a window to allow the sensors console operator to see the people buckled and see the helm, added two softsuit dispensers to fill the space a little, made the window doors towards the cannon station a double window and duplicated it to the right of the sensors/helm area for symmetry."
```
the changelog entry is very long. consider making it more succinct, if possible.

2022-12-14 19:20 UTC, SleepyGemmy requested changes
map corruption still there. check the mapdiff.

2022-12-18 21:33 UTC, SleepyGemmy submitted a review, later dismissed
ditto. same as last review.
![image](https://user-images.githubusercontent.com/99297919/208320697-86225f03-e549-41c4-8eac-99079186002b.png)

2023-01-02 13:29 UTC, merged