Floral Somatoray Gene Targeting
Aurorastation/Aurora.3 pull request #15111
Opened 2022-11-15 07:26 UTC by RustingWithYou

Steals Baystation's specific gene firing mode for the floral somatoray. This should make it easier for xenobotany players to get to the interesting part of the job instead of playing at random guesswork and wasting all their disks on learning genes.

2022-11-15 23:43 UTC, RustingWithYou commented
!review

2022-11-22 17:33 UTC, NonQueueingMatt approved these changes

2022-11-23 20:54 UTC, SleepyGemmy requested changes

2022-11-23 20:54 UTC, SleepyGemmy commented on code/modules/projectiles/guns/energy/special.dm
> +	to_chat(usr, "<span class='info'>You set the [src]'s targeted genetic area to [genemask].</span>")
```suggestion
	to_chat(usr, SPAN_INFO("You set \the [src]\s targeted genetic area to [genemask]."))
```

2022-11-23 20:54 UTC, SleepyGemmy commented on code/modules/projectiles/projectile/special.dm
> +	nodamage = 1
```suggestion
	nodamage = TRUE
```

2022-11-23 20:54 UTC, SleepyGemmy commented on code/modules/projectiles/guns/energy/special.dm
> +
```suggestion
```
stray newline.

2022-11-23 21:10 UTC, SleepyGemmy approved these changes

2022-11-23 21:32 UTC, merged