Adds Dominian assault rifle
Aurorastation/Aurora.3 pull request #15126
Opened 2022-11-18 04:57 UTC by BLUNTFORCE420

See above, statistical copy-paste of 762 AR along the lines of other factional rifles, for eventual Dominian ship PR.

![image](https://user-images.githubusercontent.com/65368125/202620234-6073ec02-9567-44d4-b84a-94dbf82fd79e.png)

2022-11-18 04:57 UTC, BLUNTFORCE420 commented
!review

2022-11-18 11:03 UTC, NonQueueingMatt approved these changes

2022-11-18 11:05 UTC, KingOfThePing approved these changes

2022-11-18 17:14 UTC, SleepyGemmy requested changes

2022-11-18 17:14 UTC, SleepyGemmy commented on code/modules/projectiles/guns/projectile/automatic.dm
> +	desc_fluff = "The Moroz Pattern Rifle, Year of 2424 has been the standard-issue rifle of the Imperial Army for decades thanks to its durable construction and ease of use. \
```suggestion
	desc_extended = "The Moroz Pattern Rifle, Year of 2424 has been the standard-issue rifle of the Imperial Army for decades thanks to its durable construction and ease of use. \
```

2022-11-18 17:17 UTC, SleepyGemmy commented on code/modules/projectiles/guns/projectile/automatic.dm
> +	desc = "The standard-issue rifle of the Empire of Dominia’s Imperial Army. With its sleek lines and ruggedized faux-wood furniture, the MPR-24/5 \
```suggestion
	desc = "The standard issue rifle of the Empire of Dominia’s Imperial Army. With its sleek lines and ruggedized faux wood furniture, the MPR-24/5 \
```

2022-11-18 17:17 UTC, SleepyGemmy commented on code/modules/projectiles/guns/projectile/automatic.dm
> +	desc_fluff = "The Moroz Pattern Rifle, Year of 2424 has been the standard-issue rifle of the Imperial Army for decades thanks to its durable construction and ease of use. \
```suggestion
	desc_fluff = "The Moroz Pattern Rifle, Year of 2424 has been the standard issue rifle of the Imperial Army for decades thanks to its durable construction and ease of use. \
```

2022-11-18 17:17 UTC, SleepyGemmy commented on code/modules/projectiles/guns/projectile/automatic.dm
> +	auto_eject = 1
```suggestion
	auto_eject = TRUE
```

2022-11-18 18:54 UTC, SleepyGemmy commented on code/modules/projectiles/guns/projectile/automatic.dm
> +	desc_extended = "The Moroz Pattern Rifle, Year of 2424 has been the standard-issue rifle of the Imperial Army for decades thanks to its durable construction and ease of use. \
```suggestion
	desc_extended = "The Moroz Pattern Rifle, Year of 2424 has been the standard issue rifle of the Imperial Army for decades thanks to its durable construction and ease of use. \
```

2022-11-19 14:34 UTC, SleepyGemmy approved these changes

2022-11-21 23:59 UTC, merged