New Burning Sprite
Aurorastation/Aurora.3 pull request #15132
Opened 2022-11-18 19:36 UTC by SleepyGemmy

this PR adds a new burning sprite.

## video
![click to view](https://user-images.githubusercontent.com/99297919/202787576-f9c72d91-b89a-44ea-96ea-be4e3bc4488d.mp4)

2022-11-18 19:40 UTC, SleepyGemmy commented
!review

2022-11-18 23:47 UTC, Butterrobber202 commented
this is going to make my war crimes so much more immersive.

2022-11-19 03:12 UTC, Alberyk approved these changes

2022-11-19 17:02 UTC, Zelmana commented
Certified Thich Quang Duc moment

2022-11-20 15:24 UTC, NonQueueingMatt requested changes

2022-11-20 15:24 UTC, NonQueueingMatt commented on code/modules/mob/living/carbon/human/species/species.dm
> +	var/light_color = null
these are completely unused, so remove them

2022-11-20 15:33 UTC, SleepyGemmy commented on code/modules/mob/living/carbon/human/species/species.dm
> +	var/light_color = null
done.

2022-11-21 23:34 UTC, SleepyGemmy commented on code/modules/mob/living/carbon/human/species/species.dm
> +	var/light_color = null
they are used by IPCs.

2022-11-22 16:55 UTC, NonQueueingMatt approved these changes

2022-11-22 17:03 UTC, merged