Ports /tg/ spatial grid system, refactors telecomms, destroys lag
Aurorastation/Aurora.3 pull request #15140
Opened 2022-11-20 09:10 UTC by JohnWildkins

Ports tgstation/tgstation#33647
Ports tgstation/tgstation#61422

Spatial grid system made by people smarter than me destroys procs like get_mobs_or_objs_in_view that eats all of our server performance on highpop

This should (hopefully) result in a smoother experience especially with high amounts of players (read: events)

todo: 
 - actually test it lmao
 - get rid of old signal stuff in NTSL

2022-12-03 19:40 UTC, JohnWildkins commented
More or less feature complete at this point, but entirely possible it's horrifically broken in several places since I refactored it about half a dozen times.

2022-12-03 19:40 UTC, JohnWildkins commented
!review

2022-12-03 20:35 UTC, NonQueueingMatt requested changes

2022-12-03 20:35 UTC, NonQueueingMatt commented on maps/away/ships/sol_pirate/sfa_patrol_ship.dm
> +	template_flags = TEMPLATE_FLAG_SPAWN_GUARANTEED
remove

2022-12-03 23:58 UTC, JohnWildkins commented on maps/away/ships/sol_pirate/sfa_patrol_ship.dm
> +	template_flags = TEMPLATE_FLAG_SPAWN_GUARANTEED
tytyty

2022-12-08 11:14 UTC, SleepyGemmy commented on code/game/machinery/telecomms/computers/telemonitor.dm
> +	name = "Telecommunications Monitor"
```suggestion
	name = "telecommunications monitor"
```

2022-12-08 11:14 UTC, SleepyGemmy commented on code/game/machinery/telecomms/computers/traffic_control.dm
> +	name = "Telecommunications Traffic Control"
```suggestion
	name = "telecommunications traffic control"
```

2022-12-08 11:14 UTC, SleepyGemmy commented on code/game/machinery/telecomms/presets.dm
> +		id = "[preset_name] Server"
```suggestion
		id = "[preset_name] server"
```
probably?

2022-12-08 11:14 UTC, SleepyGemmy commented on code/game/machinery/telecomms/presets.dm
> +		id = "[preset_name] Broadcaster"
```suggestion
		id = "[preset_name] broadcaster"
```
probably?

2022-12-08 11:14 UTC, SleepyGemmy commented on code/modules/mining/mine_turfs.dm
> +	if (isStationLevel(z))
```suggestion
	if(isStationLevel(z))
```

2022-12-08 11:14 UTC, SleepyGemmy commented on code/modules/mining/mine_turfs.dm
> +	if (isStationLevel(z))
```suggestion
	if(isStationLevel(z))
```

2022-12-08 11:14 UTC, SleepyGemmy commented on code/modules/mining/mine_turfs.dm
> +	if (isStationLevel(z))
```suggestion
	if(isStationLevel(z))
```

2022-12-08 11:14 UTC, SleepyGemmy commented on code/modules/mob/hear_say.dm
> +	if (ishuman(speaker) && speaker.GetVoice() != real_name)
```suggestion
	if(ishuman(speaker) && speaker.GetVoice() != real_name)
```

2022-12-08 11:14 UTC, SleepyGemmy commented on code/modules/mob/hear_say.dm
> +	if (hard_to_hear)
```suggestion
	if(hard_to_hear)
```

2022-12-09 11:33 UTC, NonQueueingMatt approved these changes

2022-12-09 11:35 UTC, merged