Fixing Access
Aurorastation/Aurora.3 pull request #15158
Opened 2022-11-22 09:27 UTC by Sindorman

While working on PR #15157 I noticed that hangar techs and miners have access to QM specific things. This included Tech Storage, Secure Ammunitions Storage and also QM's office. As I understand that is apparently to allow them to access mainly Secure Ammunition's storage and Flak Weapon. So in this PR:

- Added Ship weapons specific access type. Added such access to hanger technician, all head of staff, engineers, medical rescue tech, lawyer, HR assistant, bridge crew.
- Added ship weapons access to mulebot
- Changed Secure Ammunition's storage and flak gun door's access to ship weapons only

2022-11-22 09:30 UTC, Triogenix commented
Bridge Crew shouldn't get access to the Grauwolf and Secure Ammunition Storage. It was very specifically removed previously from my understanding.

2022-11-22 09:35 UTC, Sindorman commented
> 

Hmmm. I would need to confirm that with developers as I just mirrored access I saw already in code which seems like they did have access to at least Grauwolf, but not secure ammunition's storage

2022-11-22 09:35 UTC, Sindorman commented
!review

2022-11-22 12:15 UTC, NonQueueingMatt commented
> > Bridge Crew shouldn't get access to the Grauwolf and Secure Ammunition Storage. It was very specifically removed previously from my understanding. Then again I could be wrong.
> 
> Hmmm. I would need to confirm that with developers as I just mirrored access I saw already in code which seems like they did have access to at least Grauwolf, but not secure ammunition's storage

They should not have access to the guns themselves.

2022-11-22 14:28 UTC, SleepyGemmy requested changes
![image](https://user-images.githubusercontent.com/99297919/203339431-566597bc-2e09-44d2-b1b2-e8aa8e34eea8.png)
don't change back the floor tiles to plasteel.

2022-11-22 14:28 UTC, SleepyGemmy commented on code/game/jobs/access_datum.dm
> +/var/const/access_ship_weapons = 210
use a free ID from 1-99 since its on-ship access.

2022-11-22 14:28 UTC, SleepyGemmy commented on code/game/jobs/job/medical.dm
> +	minimal_access = list(access_medical, access_medical_equip, access_morgue, access_surgery, access_eva, access_maint_tunnels, access_engine, access_ship_weapons, access_research, access_sec_doors, ac
i don't see why first responders would have access to the ship's weapons.

2022-11-22 14:28 UTC, SleepyGemmy commented on code/game/jobs/job/outsider/representative.dm
> +	access = list(access_lawyer, access_maint_tunnels, access_ship_weapons)
liaisons should definitely not have ship weapons access.

2022-11-22 14:28 UTC, SleepyGemmy commented on code/game/machinery/bots/mulebot.dm
> +	botcard.access = list(access_maint_tunnels, access_mailsorting, access_cargo, access_cargo_bot, access_ship_weapons, access_qm, access_mining, access_mining_station)
mulebots are deprecated as far as i know, but technically fine.

2022-11-22 14:28 UTC, SleepyGemmy commented on html/changelogs/Sindorman-access.yml
> +  - tweak: "Added Ship Weapons access type for flak cannon and Secure Ammunitions Storage. Roles that now have it: hangar technicia, all head of staff, bridge crew, engineers, rescue tech, lawyer, HR
spellcheck and look over the roles.

2022-11-22 14:28 UTC, SleepyGemmy commented on maps/sccv_horizon/sccv_horizon-2_deck_2.dmm
> +	req_access = list(16,47)
this should be `req_one_access`.

2022-11-22 14:28 UTC, SleepyGemmy commented on maps/sccv_horizon/sccv_horizon-2_deck_2.dmm
> +	sensors = list("engine_sensor" = "Engine Core")
?

2022-12-10 07:48 UTC, Sindorman commented
> ![image](https://user-images.githubusercontent.com/99297919/203339431-566597bc-2e09-44d2-b1b2-e8aa8e34eea8.png) don't change back the floor tiles to plasteel.

I did not change any tiles, look at the map diff. There are no changes to the tiles anywhere

2022-12-10 11:29 UTC, Sindorman commented
!review

2022-12-10 11:49 UTC, NonQueueingMatt requested changes

2022-12-10 11:49 UTC, NonQueueingMatt commented on code/game/jobs/job/captain.dm
> +	minimal_access = list(access_heads, access_eva, access_gateway, access_weapons, access_ship_weapons, access_intrepid, access_teleporter)
Bridge crew shouldn't have access.

2022-12-10 14:34 UTC, SleepyGemmy requested changes

2022-12-10 14:34 UTC, SleepyGemmy commented on code/game/jobs/job/captain.dm
> -	minimal_access = list(access_heads, access_eva, access_gateway, access_weapons, access_bridge_crew, access_intrepid, access_teleporter)
restore bridge crew access to bridge crew.

2022-12-10 20:42 UTC, Sindorman commented on code/game/jobs/job/captain.dm
> +	minimal_access = list(access_heads, access_eva, access_gateway, access_weapons, access_ship_weapons, access_intrepid, access_teleporter)
Ah, I removed the wrong access lol

2022-12-10 23:58 UTC, Sindorman commented
!review

2022-12-10 23:58 UTC, Sindorman commented
Common github, it does not let me re-request review from both lol

2022-12-11 00:55 UTC, SleepyGemmy approved these changes

2022-12-13 15:13 UTC, JohnWildkins approved these changes

2022-12-16 11:14 UTC, merged