Tweaks Audible Emote Visual Feedback
Aurorastation/Aurora.3 pull request #15166
Opened 2022-11-23 22:06 UTC by SleepyGemmy

this PR makes overhead text for audible emotes visually separate from regular talking.

2022-11-23 22:06 UTC, SleepyGemmy commented
!review

2022-11-25 23:43 UTC, Sindorman requested changes

2022-11-25 23:43 UTC, Sindorman commented on code/_helpers/text.dm
> +	return copytext_char(t, 1, i) + lowertext(copytext_char(t, i, i + 1)) + copytext_char(t, i + 1)
This whole algorithm can be reduced down to few calls. Also the name is confusing for what it does, sounds generic. You can also do same with `capitalize`
```suggestion
//Returns a string with the first element of the string uncapitalized, ignoring html-tags
/proc/uncapitalize_first_character(t as text)
	var/index = findtext_char(t, ">")
	if(!index)
	    return t
	return copytext_char(t, 1, index + 1) + lowertext(t[index + 1]) + copytext_char(t, index + 2)
```

2022-12-08 20:17 UTC, NonQueueingMatt approved these changes

2022-12-12 02:17 UTC, merged