Dominia Cape Leg Things
Aurorastation/Aurora.3 pull request #15176
Opened 2022-11-25 21:32 UTC by Geevies

Makes the Dominia Cape back thing get hidden by tails / other clothes.

![image](https://user-images.githubusercontent.com/22774890/204057113-6e80c044-1eee-45cf-bc50-1aa6f83cf2d6.png)
![image](https://user-images.githubusercontent.com/22774890/204057119-ef04e8ee-db4d-4fee-a38b-3bc2a115e838.png)
![image](https://user-images.githubusercontent.com/22774890/204057122-0c97eabc-9940-4978-95cd-c9ff1d92456b.png)

2022-11-25 22:29 UTC, alsoandanswer approved these changes

2022-11-25 22:29 UTC, alsoandanswer commented
!review

2022-11-25 22:57 UTC, SleepyGemmy commented on code/modules/clothing/factions/dominia.dm
> +		var/image/legge = image(mob_icon, null, "lil_leg_thing", H ? H.layer - 0.01 : MOB_LAYER - 0.01)
human readable variable names, please.

2022-11-25 22:57 UTC, SleepyGemmy commented on code/modules/clothing/factions/dominia.dm
> +		I.add_overlay(legge)
ditto.

2022-11-25 22:57 UTC, SleepyGemmy commented on code/modules/clothing/factions/dominia.dm
> +	var/image/legge = image(icon, null, "lil_leg_thing", H ? H.layer - 0.01 : MOB_LAYER - 0.01)
ditto.

2022-11-25 22:57 UTC, SleepyGemmy commented on code/modules/clothing/factions/dominia.dm
> +	base.add_overlay(legge)
ditto.

2022-11-26 10:56 UTC, KingOfThePing approved these changes

2022-11-26 18:39 UTC, SleepyGemmy commented on code/modules/clothing/factions/dominia.dm
> +/obj/item/clothing/accessory/poncho/dominia_cape/get_mob_overlay(var/mob/living/carbon/human/human, var/mob_icon, var/mob_state, var/slot)
```suggestion
/obj/item/clothing/accessory/poncho/dominia_cape/get_mob_overlay(var/mob/living/carbon/human/H, var/mob_icon, var/mob_state, var/slot)
```
H is fine.

2022-11-26 18:39 UTC, SleepyGemmy commented on code/modules/clothing/factions/dominia.dm
> +		var/image/cape_backing = image(mob_icon, null, "lil_leg_thing", human ? human.layer - 0.01 : MOB_LAYER - 0.01)
```suggestion
		var/image/cape_backing = image(mob_icon, null, "lil_leg_thing", H? H.layer - 0.01 : MOB_LAYER - 0.01)
```
H is fine.

2022-11-26 18:39 UTC, SleepyGemmy commented on code/modules/clothing/factions/dominia.dm
> +		var/image/cape_backing = image(mob_icon, null, "lil_leg_thing", human ? human.layer - 0.01 : MOB_LAYER - 0.01)
what is "lil_leg_thing"?

2022-11-26 18:39 UTC, SleepyGemmy commented on code/modules/clothing/factions/dominia.dm
> +/obj/item/clothing/accessory/poncho/dominia_cape/get_accessory_mob_overlay(mob/living/carbon/human/human, force)
```suggestion
/obj/item/clothing/accessory/poncho/dominia_cape/get_accessory_mob_overlay(mob/living/carbon/human/H, force)
```
H is fine.

2022-11-26 18:39 UTC, SleepyGemmy commented on code/modules/clothing/factions/dominia.dm
> +	var/image/cape_backing = image(icon, null, "lil_leg_thing", human ? human.layer - 0.01 : MOB_LAYER - 0.01)
```suggestion
	var/image/cape_backing = image(icon, null, "lil_leg_thing", H? H.layer - 0.01 : MOB_LAYER - 0.01)
```
H is fine.

2022-11-26 18:39 UTC, SleepyGemmy commented on code/modules/clothing/factions/dominia.dm
> +	var/image/cape_backing = image(icon, null, "lil_leg_thing", human ? human.layer - 0.01 : MOB_LAYER - 0.01)
what is "lil_leg_thing"?

2022-12-02 11:45 UTC, NonQueueingMatt commented on code/modules/clothing/factions/dominia.dm
> +/obj/item/clothing/accessory/poncho/dominia_cape/get_mob_overlay(var/mob/living/carbon/human/human, var/mob_icon, var/mob_state, var/slot)
not really necessary

2022-12-04 18:35 UTC, Alberyk approved these changes

2022-12-04 18:37 UTC, SleepyGemmy requested changes
see comments above.

2022-12-05 18:27 UTC, SleepyGemmy approved these changes

2022-12-07 20:19 UTC, merged