Adds zavod alt clothes for warden
Aurorastation/Aurora.3 pull request #15182
Opened 2022-11-26 18:28 UTC by LoreCoder

Adds in an alt version of the Zavodskoi warden coat and hat like with most Zavod things, as well as making it actually selectable via the loadout.

![image](https://user-images.githubusercontent.com/63847722/204103454-36cedb99-40fc-4023-9358-0de2accecdac.png)

2022-11-26 18:30 UTC, LoreCoder commented
!review

2022-11-27 00:31 UTC, alsoandanswer requested changes
I hope you followed the palette by using the eyedropper tool.

2022-11-27 00:31 UTC, alsoandanswer commented on code/modules/client/preference_setup/loadout/loadout_head.dm
> +	wardenhead["warden hat"] = /obj/item/clothing/head/warden
This is a parent item, not supposed to be used.

2022-11-27 01:10 UTC, alsoandanswer commented
Looks like you're pulling from your master. You forgot to make a branch.

2022-11-27 12:02 UTC, LoreCoder commented
Closing PR to make a branch real quick and remove the original warden hat as requested.

2022-11-27 12:02 UTC, closed without merging