SFA Remap
Aurorastation/Aurora.3 pull request #15199
Opened 2022-11-30 17:09 UTC by SophieMint

- Remaps the SFA Ship into something more lore fitting. https://imgur.com/a/p8H9Flj
- This gives the shuttle a lathe. The ship is really busted up and ship combat will ruin it further, so it provides a bit more support. It also allows them to print what they need, albeit with a very limited supply of metal. In return this removes the combat shotgun so slugs can't be spammed, and gives them an additional AR instead - bringing them more up to par with more recent ones.
- I have almost certainly made a bunch of mistakes with this PR. It was a bit messy to get working.
- My previous one had a ton of issues, had to close and reopen as I couldn't figure out what was going wrong with my repo. Sorry!

2022-11-30 17:16 UTC, SophieMint commented
!wip

2022-11-30 20:16 UTC, SophieMint commented
!review

2022-12-06 15:45 UTC, SleepyGemmy commented on html/changelogs/PeppermintSFA.yml
> +  - maptweak: "Remaps the SFA away ship"
```suggestion
  - maptweak: "Remaps the SFA away ship."
```

2022-12-06 15:53 UTC, SleepyGemmy requested changes
![image](https://user-images.githubusercontent.com/99297919/205958015-b21637db-33b3-4fd8-8946-b1cce59e2b9a.png)
don't map curtains inside of windows.

![image](https://user-images.githubusercontent.com/99297919/205958120-526c37e3-40b8-4644-9639-e5d38873ac0d.png)
don't map dirt decals on space tiles.

![image](https://user-images.githubusercontent.com/99297919/205958337-0432bc77-9604-45e5-88bc-2a5ce4a772cc.png)
this turf should be passthrough.

![image](https://user-images.githubusercontent.com/99297919/205958630-bf72e3c6-8715-4537-a4e5-a3465522ab53.png)
this tile is going to vent the ship. since the room to the north of it is.

![image](https://user-images.githubusercontent.com/99297919/205958725-e7195bd5-1958-40eb-b54c-bee662ff42bf.png)
random surgery holosigns.

![image](https://user-images.githubusercontent.com/99297919/205958769-74ab6e47-5016-43da-a335-020220d47485.png)
the "white" tiles in this room should be `/turf/space/dynamic`.

![image](https://user-images.githubusercontent.com/99297919/205959009-facfbafe-b327-4506-934b-7f4bc5b6b135.png)
theres a floor decal under this window.

![image](https://user-images.githubusercontent.com/99297919/205959072-c23aba9d-cc0c-4cf5-9a29-008da76af595.png)
floor decals misaligned.

![image](https://user-images.githubusercontent.com/99297919/205959120-b3b4789e-767a-4e4c-996e-6373d26b74bf.png)
turfs underneath the girders should be `/turf/space/dynamic`.

![image](https://user-images.githubusercontent.com/99297919/205959240-5b71773d-bd86-459f-90c0-2d936dc23c39.png)
windows on corners like this is bad praxis.

![image](https://user-images.githubusercontent.com/99297919/205959477-efe90175-c944-463c-bc20-189e62bec2ed.png)
missing turf.

![image](https://user-images.githubusercontent.com/99297919/205959531-48d1a4ac-dc44-4ed0-b926-0558207eab8c.png)
?

2022-12-10 04:57 UTC, SophieMint commented
> don't map curtains inside of windows. ![image](https://user-images.githubusercontent.com/99297919/205958015-b21637db-33b3-4fd8-8946-b1cce59e2b9a.png)

I think I got most of 'em

2022-12-10 16:25 UTC, Alberyk approved these changes

2022-12-11 18:03 UTC, SleepyGemmy requested changes
generally, if a turf has nothing on it and its in space, use the passthrough turf.
if a turf has something on it and its in space, use `/turf/space/dynamic`.

something under this window.
![image](https://user-images.githubusercontent.com/99297919/206920451-7357409e-a2b7-4354-aaae-f49c4606f711.png)

holosign still here.
![image](https://user-images.githubusercontent.com/99297919/206920493-f5392d5a-830f-4711-af7c-5fe3f2a83b7e.png)

turf still missing.
![image](https://user-images.githubusercontent.com/99297919/206920539-f117a020-eaa3-4ff1-a337-9eaa1cdf0413.png)

2022-12-16 11:28 UTC, NonQueueingMatt approved these changes

2022-12-16 14:08 UTC, SleepyGemmy reviewed
no tile underneath.
![image](https://user-images.githubusercontent.com/99297919/208115966-8aff0d77-9372-44a6-a120-7f8f74b19e4c.png)

2022-12-16 14:29 UTC, SleepyGemmy commented on maps/away/ships/sol_pirate/sfa_patrol_ship.dm
> +	name = "SFA Suit Storage"
paths should be lowercase.

2022-12-16 14:30 UTC, SleepyGemmy commented on maps/away/ships/sol_pirate/sfa_patrol_ship.dm
> +	name = "SFA Suit Storage"
```suggestion
/area/ship/sfa_patrol_ship/sfa_armory
	name = "SFA Armory"

/area/ship/sfa_patrol_ship/engineering
	name = "SFA Engineering"

/area/ship/sfa_patrol_ship/telecoms
	name = "SFA Telecoms"

/area/ship/sfa_patrol_ship/treasureroom
	name = "SFA Treasure Room"

/area/ship/sfa_patrol_ship/bridge
	name = "SFA Corvette Bridge"

/area/ship/sfa_patrol_ship/ammo_closet
	name = "SFA Ammo Closet"

/area/ship/sfa_patrol_ship/quarters
	name = "SFA Crew Quarters"

/area/ship/sfa_patrol_ship/officer
	name = "SFA Officer Quarters"

/area/ship/sfa_patrol_ship/brig
	name = "SFA Brig"

/area/ship/sfa_patrol_ship/engine1
	name = "SFA Engine One"

/area/ship/sfa_patrol_ship/engine2
	name = "SFA Engine Two"

/area/ship/sfa_patrol_ship/suit_storage
	name = "SFA Suit Storage"
```

2022-12-16 15:38 UTC, SleepyGemmy approved these changes

2022-12-16 16:02 UTC, SleepyGemmy commented on maps/away/ships/sol_pirate/sfa_patrol_ship.dm
> +	name = "SFA Suit Storage"
```suggestion
/area/ship/sfa_patrol_ship/SFA_Armory
	name = "SFA Armory"

/area/ship/sfa_patrol_ship/Engineering
	name = "SFA Engineering"

/area/ship/sfa_patrol_ship/Telecoms
	name = "SFA Telecoms"

/area/ship/sfa_patrol_ship/TreasureRoom
	name = "SFA Treasure Room"

/area/ship/sfa_patrol_ship/Bridge
	name = "SFA Corvette Bridge"

/area/ship/sfa_patrol_ship/Ammo_Closet
	name = "SFA Ammo Closet"

/area/ship/sfa_patrol_ship/Quarters
	name = "SFA Crew Quarters"

/area/ship/sfa_patrol_ship/Officer
	name = "SFA Officer Quarters"

/area/ship/sfa_patrol_ship/Brig
	name = "SFA Brig"

/area/ship/sfa_patrol_ship/Engine1
	name = "SFA Engine One"

/area/ship/sfa_patrol_ship/Engine2
	name = "SFA Engine Two"

/area/ship/sfa_patrol_ship/Suit_Storage
	name = "SFA Suit Storage"
```

2022-12-17 14:02 UTC, merged