Resprites the kimono
Aurorastation/Aurora.3 pull request #15197
Opened 2022-11-30 06:29 UTC by atteria

Not exactly a high priority resprite, but this one bothered me in particular.

This improves on just about every element of the old kimono sprite, silhouette, shading, level of contrast, everything. Maybe it will actually be used now.

![kimono showcase](https://user-images.githubusercontent.com/86520558/204723039-0e229575-8e21-4934-ae1e-49156b465174.png)

Tested locally.

2022-11-30 07:10 UTC, atteria commented
!review

2022-11-30 07:58 UTC, SleepyGemmy approved these changes

2022-11-30 07:59 UTC, SleepyGemmy requested changes
please turn it into a contained sprite.

2022-11-30 10:35 UTC, alsoandanswer approved these changes

2022-12-01 11:47 UTC, SleepyGemmy commented on code/modules/clothing/under/miscellaneous.dm
> +	contained_sprite = TRUE
```suggestion
	contained_sprite = TRUE

```

2022-12-02 00:21 UTC, SleepyGemmy approved these changes

2022-12-02 03:14 UTC, Alberyk approved these changes

2022-12-03 11:37 UTC, merged