SSMD Recon Corvette
Aurorastation/Aurora.3 pull request #15218
Opened 2022-12-03 07:16 UTC by TheDanseMacabre

WIP. Description to come. tldr new ship also some minor fixes to other ships

2022-12-03 07:17 UTC, TheDanseMacabre commented
!wip

2022-12-03 11:05 UTC, Dreamykass commented
Please, I beg you, more airlocks, or even a proper docking port.

Currently, as in the mapdiffs, this has only two single-tile airlocks, that are effectively in a single spot (aft, near the hangar). This makes anything EVA related super miserable. You can't cycle with a piece of machinery or a canister or similar things (that you can't climb on top) if it's a single tile airlock. Not to mention interacting with other third parties, trying to visit each other, or board in combat.

2022-12-03 11:05 UTC, DreamySkrell commented
Please, I beg you, more airlocks, or even a proper docking port.

Currently, as in the mapdiffs, this has only two single-tile airlocks, that are effectively in a single spot (aft, near the hangar). This makes anything EVA related super miserable. You can't cycle with a piece of machinery or a canister or similar things (that you can't climb on top) if it's a single tile airlock. Not to mention interacting with other third parties, trying to visit each other, or board in combat.

2022-12-04 08:46 UTC, TheDanseMacabre commented
!review

2022-12-06 15:10 UTC, SleepyGemmy requested changes
consider a PR description.

2022-12-06 15:10 UTC, SleepyGemmy commented on maps/away/ships/sol_ssmd/ssmd_ship.dm
> +	descriptor = "A long-range reconnaissance corvette design in use by the Solarian Navy, the Uhlan-class is a relatively costly and somewhat uncommon ship to be seen in the Alliance’s fleets, and is t
```suggestion
	descriptor = "A long-range reconnaissance corvette design in use by the Solarian Navy, the Uhlan-class is a relatively costly and somewhat uncommon ship to be seen in the Alliance's fleets, and is typically reserved for more elite (or at least better equipped and trained) units. Designed to operate alone or as part of a small task force with minimal support in unfriendly space, it is most commonly seen assigned to probing, surveillance, harassment, and strike operations. \
```

2022-12-06 15:10 UTC, SleepyGemmy commented on maps/away/ships/sol_ssmd/ssmd_ship.dm
> +	desc = "A modestly-sized shuttle design used by the Solarian armed forces, the Destrier is well-armored but somewhat slow, and was explicitly designed to be as survivable as possible for operations
```suggestion
	desc = "A modestly sized shuttle design used by the Solarian armed forces, the Destrier is well-armored but somewhat slow, and was explicitly designed to be as survivable as possible for operations during combat. Notably features a fast-deployment exosuit catapult."
```

2022-12-06 15:10 UTC, SleepyGemmy commented on maps/away/ships/sol_ssmd/ssmd_ship_ghostroles.dm
> +	name = "ssmd patrol ship id"
```suggestion
	name = "\improper SSMD patrol ship identification card"
```

2022-12-07 09:47 UTC, SleepyGemmy approved these changes

2022-12-07 16:57 UTC, NonQueueingMatt approved these changes

2022-12-07 17:07 UTC, merged