Tweaks EVA Gear
Aurorastation/Aurora.3 pull request #15290
Opened 2022-12-11 23:50 UTC by SleepyGemmy

this PR tweaks the gear in EVA to make it more fitting for expeditions, as well as the safety of the crew, both on ship and on expeditions.

2022-12-11 23:50 UTC, SleepyGemmy commented
!review

2022-12-13 11:14 UTC, NonQueueingMatt approved these changes

2022-12-13 15:18 UTC, JohnWildkins requested changes
mapped in vars causing runtimes

2024-02-21 00:38 UTC, SleepyGemmy commented
PR repurposed. doesn't change EVA mapping anymore.

2024-03-24 18:56 UTC, Arrow768 approved these changes

2024-03-26 09:09 UTC, NonQueueingMatt approved these changes

2024-03-26 09:54 UTC, merged