Primum Non Nocere: The IAC Rescue Ship
Aurorastation/Aurora.3 pull request #15302
Opened 2022-12-12 20:48 UTC by LoreCoder

Adds in a ship of the IAC dedicated to providing medical response to areas in distress, plus a small info pamphlet for it to distribute.

2022-12-12 20:48 UTC, LoreCoder commented
!review

2022-12-12 22:58 UTC, WickedCybs requested changes
You need to do a few more things for this.

- Add shuttle navpoints to the fore, aft and starboard sides of the ship.
- Add atmospherics and make sure every room has a vent and scrubber. Windows and airlocks should have emergency shutters mapped in
- Add power. Look at other ships like the headmaster or SSMD patrol vessel to see how that's done if you aren't sure.

2022-12-13 01:02 UTC, listerla commented on maps/away/ships/iac/iac_rescue_ship.dm
> +	sectors = list(SECTOR_CORP_ZONE, SECTOR_VALLEY_HALE, SECTOR_BADLANDS, SECTOR_NEW_ANKARA, SECTOR_AEMAQ, SECTOR_SRANDMARR, SECTOR_NRRAHRAHUL)
```suggestion
	sectors = list(SECTOR_CORP_ZONE, SECTOR_VALLEY_HALE, SECTOR_BADLANDS, SECTOR_SRANDMARR, SECTOR_NRRAHRAHUL)
```
Lore explicitly says they don't operate in Elyra.

2022-12-13 21:02 UTC, WickedCybs approved these changes
Changes look fine.

2022-12-15 03:14 UTC, Alberyk approved these changes

2022-12-16 10:40 UTC, connorjg1 requested changes
Tested on a test branch:

The IAC ID's do not appear to work on the IAC vessel doors. You can't open them. Same applies probably to the cabinets and chem storage, but definitely to the Nanomed.

Shuttle control console doesn't work. 

Less important notes:

The bedroom could use another light, the TV is covered in darkness.

Coordinators airlock is unnamed.

Shouldn't the money go in a coordinator safe or cupboard? Having donation money laying with the pamphlets in the open seems like poor money-handling. 

Only one advanced medical kit? If there is serious medical trouble a single one will be used up on two people, could probably use one or two more. 

Giving the coordinator an Advanced Zeng-hu scanner in the office is probably not a bad idea since they're a medical vessel. 

Technician description could probably say they act as either engineering or security. IAC ERT had an armed security role for the medics.

2022-12-16 21:17 UTC, LoreCoder commented
> Tested on a test branch:
> 
> Main bugs:
> 
> The IAC ID's do not appear to work on the IAC vessel doors. You can't open them. Not sure if this is something to do with the testing branch hosting? Same applies probably to the cabinets and chem storage, but definitely to the Nanomed.
> 
> Shuttle control console doesn't work.
> 
> Less important notes:
> 
> snip

IAC ID access to everything should be remedied now; minor bugs have all been alleviated as well, +1 AFAK +1 Med voidsuit plus a buff to Coord's gear. As for O- blood, that's stored within the surgery blood locker (which should also be accessible now); right now only issue remaining is the helm/shuttle controls being non-functional. Will fix it as soon as I realize what's up with that.

2022-12-17 22:05 UTC, JohnWildkins requested changes

2022-12-17 22:05 UTC, JohnWildkins commented on maps/away/ships/iac/iac_rescue_ship.dm
> +	shuttles_to_initialise = list(/datum/shuttle/autodock/overmap/IAC_shuttle)
```suggestion
	shuttles_to_initialise = list(/datum/shuttle/autodock/overmap/iac_shuttle)

```
In general all-lowercase path names are strongly preferred

2022-12-17 22:05 UTC, JohnWildkins commented on maps/away/ships/iac/iac_rescue_ship.dm
> +		"IAC Ambulance Shuttle" = list("nav_hangar_IAC")
```suggestion
		"IAC Ambulance Shuttle" = list("nav_hangar_iac")

```
ditto

2022-12-17 22:05 UTC, JohnWildkins commented on maps/away/ships/iac/iac_rescue_ship.dm
> +		"nav_IAC_rescue_ship_2"
```suggestion
	initial_generic_waypoints = list(
		"nav_iac_rescue_ship_1",
		"nav_iac_rescue_ship_2"

```
ditto

2022-12-17 22:05 UTC, JohnWildkins commented on maps/away/ships/iac/iac_rescue_ship.dm
> +	current_location = "nav_hangar_IAC"
```suggestion
	current_location = "nav_hangar_iac"

```

2022-12-17 22:05 UTC, JohnWildkins commented on maps/away/ships/iac/iac_rescue_ship.dm
> +	landmark_transition = "nav_transit_IAC_shuttle"
```suggestion
	landmark_transition = "nav_transit_iac_shuttle"

```

2022-12-17 22:05 UTC, JohnWildkins commented on maps/away/ships/iac/iac_rescue_ship.dm
> +	logging_home_tag = "nav_hangar_IAC"
```suggestion
	logging_home_tag = "nav_hangar_iac"

```

2022-12-17 22:05 UTC, JohnWildkins commented on maps/away/ships/iac/iac_rescue_ship.dm
> +	landmark_tag = "nav_hangar_IAC"
```suggestion
	landmark_tag = "nav_hangar_iac"

```

2022-12-17 22:05 UTC, JohnWildkins commented on maps/away/ships/iac/iac_rescue_ship.dm
> +	docking_controller = "IAC_shuttle_dock"
```suggestion
	docking_controller = "iac_shuttle_dock"

```

2022-12-17 22:05 UTC, JohnWildkins commented on maps/away/ships/iac/iac_rescue_ship.dm
> +	landmark_tag = "nav_transit_IAC_shuttle"
```suggestion
	landmark_tag = "nav_transit_iac_shuttle"

```

2022-12-17 22:05 UTC, JohnWildkins commented on maps/sccv_horizon/code/sccv_horizon.dm
> +		/datum/shuttle/autodock/overmap/IAC_shuttle
```suggestion
		/datum/shuttle/autodock/overmap/iac_shuttle
```

2022-12-17 22:05 UTC, JohnWildkins commented on maps/away/ships/iac/iac_rescue_ship.dm
> +/obj/effect/shuttle_landmark/IAC_shuttle/hangar
```suggestion
/obj/effect/shuttle_landmark/iac_shuttle/hangar

```

2022-12-17 22:05 UTC, JohnWildkins commented on maps/away/ships/iac/iac_rescue_ship.dm
> +/obj/effect/shuttle_landmark/IAC_shuttle/transit
```suggestion
/obj/effect/shuttle_landmark/iac_shuttle/transit

```

2022-12-17 22:05 UTC, JohnWildkins commented on maps/away/ships/iac/iac_rescue_ship.dm
> +/datum/shuttle/autodock/overmap/IAC_shuttle
```suggestion
/datum/shuttle/autodock/overmap/iac_shuttle

```

2022-12-17 22:05 UTC, JohnWildkins commented on maps/away/ships/iac/iac_rescue_ship.dm
> +/obj/machinery/computer/shuttle_control/explore/IAC_shuttle
```suggestion
/obj/machinery/computer/shuttle_control/explore/iac_shuttle

```

2022-12-17 22:05 UTC, JohnWildkins commented on maps/away/ships/iac/iac_rescue_ship.dm
> +/obj/effect/overmap/visitable/ship/landable/IAC_shuttle
```suggestion
/obj/effect/overmap/visitable/ship/landable/iac_shuttle

```

2022-12-18 02:22 UTC, WickedCybs commented on maps/away/ships/iac/iac_rescue_ship.dm
> +	icon_state = "shuttle"
Don't use the shuttle icon state for the main ship. Use ship.

2022-12-18 02:22 UTC, WickedCybs commented on maps/away/ships/iac/iac_rescue_ship.dm
> +	moving_state = "shuttle_moving"
Don't use the shuttle icon state for the main ship. Use ship.

2022-12-18 20:47 UTC, SleepyGemmy commented on maps/away/ships/iac/iac_rescue_ship.dm
> +
```suggestion

```

2022-12-18 20:47 UTC, SleepyGemmy commented on maps/away/ships/iac/iac_rescue_ship.dm
> +
```suggestion

```

2022-12-18 20:47 UTC, SleepyGemmy commented on maps/away/ships/iac/iac_rescue_ship.dm
> +
```suggestion

```

2022-12-18 20:47 UTC, SleepyGemmy commented on maps/away/ships/iac/iac_rescue_ship.dm
> +
```suggestion

```

2022-12-18 20:47 UTC, SleepyGemmy commented on maps/away/ships/iac/iac_rescue_ship.dm
> +
```suggestion

```

2022-12-18 20:47 UTC, SleepyGemmy commented on maps/away/ships/iac/iac_rescue_ship.dm
> +
```suggestion

```

2022-12-18 20:47 UTC, SleepyGemmy commented on maps/away/ships/iac/iac_rescue_ship.dm
> +
```suggestion

```

2022-12-18 20:52 UTC, SleepyGemmy requested changes
pharmacy windoor has access 33 instead of 211.
consider setting the ship and shuttle control consoles to require access 211.

2022-12-18 21:50 UTC, SleepyGemmy approved these changes

2022-12-20 07:10 UTC, JohnWildkins approved these changes

2022-12-20 16:07 UTC, merged