Status Icons
Aurorastation/Aurora.3 pull request #15301
Opened 2022-12-12 20:30 UTC by Geevies

* Added status indicators to the top right of the screen that indicate when you're bleeding or drunk, or both.

![image](https://user-images.githubusercontent.com/22774890/207146963-00cbc98c-859f-4dc2-ad4b-f3cf9245cb49.png)

Code partially ported from [CM-SS13](https://github.com/cmss13-devs/cmss13) (specifically `get_status_loc`), though a substantial chunk of it is my own.

### Asset Licenses
The following assets that **have not** been created by myself are included in this PR:

| Path | Original Author | License |
| --- | --- | --- |
| icons/mob/screen/hud_status.dmi : bleeding | [CM Dev Team](https://github.com/cmss13-devs/cmss13#readme) ([CM-SS13](https://github.com/cmss13-devs/cmss13)) | CC BY-SA 3.0 |

idk if i should also add it above, but i copied one of the drinks in drinks.dmi and slammed it into hud_status.dmi. it's from Aurora

2022-12-12 20:30 UTC, Geevies commented
!review

2022-12-12 20:31 UTC, Geevies commented
i think a testmerge for this one would be good to make sure the code doesn't detonate itself

2022-12-12 20:40 UTC, JohnWildkins requested changes

2022-12-13 16:23 UTC, JohnWildkins requested changes
![image](https://user-images.githubusercontent.com/6022823/207387977-18ee34d9-850b-4d8d-9b1b-dcdf96f42dcc.png)
drunk status icon appeared empty

2022-12-13 17:02 UTC, SleepyGemmy commented on code/modules/mob/living/carbon/human/life.dm
> +#define DRUNK_STRING "string"
look again.

2022-12-13 18:55 UTC, Geevies commented
i dont even know how i managed that, it's fixed now, tested in-game too to confirm

2022-12-13 22:00 UTC, JohnWildkins approved these changes
lol lmao

2022-12-13 22:07 UTC, SleepyGemmy approved these changes

2022-12-16 11:11 UTC, merged