Adds Sani'Orios as an away site
Aurorastation/Aurora.3 pull request #15307
Opened 2022-12-13 04:58 UTC by Alberyk

This pr adds the asteroid belt of one of the Tajaran planets as a visitable away site. This is content for the next sector we are moving in.

2022-12-13 15:22 UTC, JohnWildkins requested changes
roundstart active atmos processing

```## UNIT_TEST ##: !!! FAILURE !!! [ZAS: Roundstart Active Edges]: 3 edges active at round-start!
## UNIT_TEST ##: ---- Zone 1718 and space (164, 226, 20) have mismatched gas mixtures!
## UNIT_TEST ##: -------- Problem turfs: The plating (164, 225, 20) 
## UNIT_TEST ##: ---- Zone 1718 and ash (163, 225, 20) have mismatched gas mixtures!
## UNIT_TEST ##: -------- Problem turfs: The plating (164, 225, 20) 
## UNIT_TEST ##: ---- Zone 1722 and space (168, 226, 20) have mismatched gas mixtures!
## UNIT_TEST ##: -------- Problem turfs: The plating (168, 225, 20) ```

2023-01-29 19:31 UTC, SleepyGemmy commented on maps/away/away_site/tajara/saniorios_smuggler/saniorios_smuggler.dm
> +	description = "A gas giant composed of ammonia, Its planetary ring is home to several spaceship wrecks and hidden smuggler bases."
```suggestion
	description = "A gas giant composed of ammonia. Its planetary ring is home to several spaceship wrecks and hidden smuggler bases."
```

2023-01-29 19:31 UTC, SleepyGemmy commented on maps/away/away_site/tajara/saniorios_smuggler/saniorios_smuggler.dm
> +	descriptor = "A gas giant composed of ammonia, Its planetary ring is home to several spaceship wrecks and hidden smuggler bases."
```suggestion
	descriptor = "A gas giant composed of ammonia. Its planetary ring is home to several spaceship wrecks and hidden smuggler bases."
```

2023-01-29 19:31 UTC, SleepyGemmy commented on maps/away/away_site/tajara/saniorios_smuggler/saniorios_smuggler.dm
> +	desc = "A gas giant composed of ammonia, Its planetary ring is home to several spaceship wrecks and hidden smuggler bases."
```suggestion
	desc = "A gas giant composed of ammonia. Its planetary ring is home to several spaceship wrecks and hidden smuggler bases."
```

2023-01-29 19:31 UTC, SleepyGemmy commented on maps/away/away_site/tajara/saniorios_smuggler/saniorios_smuggler.dm
> +
```suggestion
```

2023-01-29 19:32 UTC, SleepyGemmy approved these changes

2023-01-29 22:17 UTC, merged