New Corporate Coats
Aurorastation/Aurora.3 pull request #15315
Opened 2022-12-13 16:37 UTC by 1Sparky1

Adds new corporate variants of the departmental jackets and winter coats. Also created a NanoTrasen and Orion coat selection in the loadout, with these and their labcoats.

Fixed a few missed cargo references in the loadout.

2022-12-13 16:44 UTC, alsoandanswer commented on code/modules/clothing/suits/storage.dm
> +	icon_state "idris_corp_jacket_alt"
```suggestion
	icon_state = "idris_corp_jacket_alt"
```

2022-12-13 16:44 UTC, Greenjoe12345 commented
Could you add the Orion beret to the loadout, too? I noticed it's a thing in the code but not in the loadout.

2022-12-13 16:46 UTC, 1Sparky1 commented
> Could you add the Orion beret to the loadout, too? I noticed it's a thing in the code but not in the loadout.

I was probably going to add other Orion drip in another PR. I happened to be on a coat spree so I did those here.

2022-12-13 18:10 UTC, alsoandanswer requested changes
Right, some issues.

Stray pixels on zeng_corp_jacket_open, west-facing.

epmc_corp_jacket, zeng_corp_jacket_alt, orion_corp_jacket all have off-palette colors.
Please fix this, thanks. A good way to check (in dreammaker) is using the colors in use section on the right.

2022-12-14 23:30 UTC, GMR25 commented on code/modules/client/preference_setup/loadout/loadout_factions.dm
> +	description = "A seclection of SCC coats"
Typo on selection.

2022-12-25 09:59 UTC, alsoandanswer approved these changes
Checks :
Winter Coats : All good. Unfortunate the "hood fluff" isn't part of the palette, but it's fine.
Department Jackets : All good.
Labcoats : All good.

You've done some absolutely stellar work here.
Apologies for the delay, it's been a busy month.

2022-12-25 10:00 UTC, alsoandanswer commented
!review

2023-01-03 15:37 UTC, Alberyk approved these changes

2023-01-03 15:38 UTC, SleepyGemmy requested changes
contained sprite paths.
don't add sprites to `icons/obj/clothing/suits.dmi` nor `icons/mob/suit.dmi`.

2023-01-04 14:23 UTC, SleepyGemmy requested changes
corp jackets are still in the last review's mentioned DMI files.

2023-01-04 18:59 UTC, SleepyGemmy approved these changes

2023-01-07 19:02 UTC, merged