Scarf Changes
Aurorastation/Aurora.3 pull request #15326
Opened 2022-12-14 17:59 UTC by 1Sparky1

Adds new sprites for scarves, which can be cycled between by using in hand. The zebra scarf is now also recolourable.

![image](https://user-images.githubusercontent.com/26849270/207672763-09425bd6-a620-4da3-af9c-9b593e131121.png)

2022-12-14 18:02 UTC, 1Sparky1 commented
!review

2022-12-14 18:48 UTC, SleepyGemmy requested changes
please keep the current scarf sprite as an option.

2022-12-14 18:50 UTC, SleepyGemmy reviewed
i suggest utilizing the radial menu system for selecting the sprites.

2022-12-14 19:26 UTC, 1Sparky1 commented
!wip

2022-12-15 22:34 UTC, 1Sparky1 commented
!review

2022-12-15 22:35 UTC, 1Sparky1 commented
Old sprites are back and switched the style change to a radial menu.

2022-12-15 23:09 UTC, SleepyGemmy commented on code/modules/clothing/under/accessories/accessory.dm
> +								"parisian" = "scarf3")
```suggestion
	var/list/alternatives = list(
		"drape" = "scarf0",
		"drape, flipped" = "scarf0_f",
		"single wrap" = "scarf1",
		"double wrap" = "scarf2",
		"parisian" = "scarf3"
	)
```

2022-12-15 23:09 UTC, SleepyGemmy commented on code/modules/clothing/under/accessories/accessory.dm
> +		for (var/i in alternatives)
```suggestion
		for(var/i in alternatives)
```

2022-12-16 17:05 UTC, SleepyGemmy approved these changes

2022-12-18 14:58 UTC, SleepyGemmy approved these changes
DMIs look fine after the master merge.

2022-12-19 14:29 UTC, merged