Dominian Naval Ship
Aurorastation/Aurora.3 pull request #15333
Opened 2022-12-16 09:02 UTC by TheDanseMacabre

WIP. Adds a Dominian naval third party ship.

2022-12-16 09:02 UTC, TheDanseMacabre commented
!review

2022-12-16 09:03 UTC, TheDanseMacabre commented
!wip

2022-12-18 02:20 UTC, WickedCybs commented on maps/away/ships/dominia/dominian_corvette.dm
> +	icon_state = "shuttle"
Make sure you use ship, not shuttle. There's colours you can choose from in the dmi if any seem appropriate.

2022-12-18 02:20 UTC, WickedCybs commented on maps/away/ships/dominia/dominian_corvette.dm
> +	moving_state = "shuttle_moving"
Ditto.

2022-12-31 10:25 UTC, TheDanseMacabre commented
!review

2023-01-01 00:18 UTC, WickedCybs commented
Check if you have any repeated navpoints. That might be the problem behind the error.

2023-01-01 04:25 UTC, TheDanseMacabre commented
> Check if you have any repeated navpoints. That might be the problem behind the error.

I don't think I do.

2023-01-01 16:51 UTC, WickedCybs approved these changes
It works fine so I approved it. Think we should make sure the error doesn't show up on any other PRs if this is merged though.

2023-01-01 18:11 UTC, WickedCybs requested changes
actuall you need Weapon Entry points (not navpoints) a,sko j i figured this ouit not wildkins lol your welcome

2023-01-02 18:27 UTC, TheDanseMacabre commented
Thabnjks Cybs and NOTTT wildkins.

2023-01-04 17:26 UTC, NonQueueingMatt approved these changes

2023-01-04 23:02 UTC, WickedCybs approved these changes

2023-01-06 00:33 UTC, Alberyk approved these changes

2023-01-07 11:38 UTC, merged