Custodial Holster Sprite Fix
Aurorastation/Aurora.3 pull request #15351
Opened 2022-12-17 17:44 UTC by SleepyGemmy

this PR restores the custodial holster sprites.

2022-12-17 17:44 UTC, SleepyGemmy commented
!review

2022-12-17 21:39 UTC, Alberyk approved these changes

2022-12-18 18:04 UTC, alsoandanswer requested changes
The only difference is moving the mob sprite by one pixel, I don't think this warrants having an entirely different state

2022-12-18 18:41 UTC, SleepyGemmy commented
i only want the sprite tweaks for the custodial holster.

2022-12-18 19:19 UTC, merged