Exosuit weapon refactor
Aurorastation/Aurora.3 pull request #15416
Opened 2022-12-23 00:36 UTC by Ben10083

Exosuit laser now considered heavy, damage set to 35 (10 increase from old, 10 less than usual heavy laser)
Exosuit smg now can switch to 3-shot burst with alt click
Exosuit smg ammo count increased to 30 shots.

2022-12-23 04:19 UTC, TheDanseMacabre commented
The exosuit SMG can already swap to three and five round burst by using the firemode command.

2022-12-23 04:26 UTC, Ben10083 commented
> The exosuit SMG can already swap to three and five round burst by using the firemode command.

With the relation of exosuit and wearer, I don't think that is intended.

2023-01-01 20:00 UTC, Alberyk requested changes

2023-01-01 20:00 UTC, Alberyk commented on code/modules/heavy_vehicle/equipment/combat.dm
> +		list(mode_name = "3-round burst",  burst = 3, fire_delay = null, move_delay = 4,    burst_accuracy = list(0,-1,-1),       dispersion=list(0, 15, 15)),
```suggestion
		list(mode_name = "3-round burst",  burst = 3, fire_delay = null, move_delay = 4,    burst_accuracy = list(0,-1,-1),       dispersion=list(0, 15, 15))
```

2023-03-26 01:50 UTC, Alberyk approved these changes

2023-04-15 20:12 UTC, NonQueueingMatt commented
!review

2023-04-15 20:12 UTC, NonQueueingMatt approved these changes

2023-04-15 20:51 UTC, merged