Added ability to see sensors scan info in UI without printing
Aurorastation/Aurora.3 pull request #15451
Opened 2022-12-27 15:23 UTC by FluffyGhoster

Added ability to see sensor scan info in UI before / in lieu of printing it.

The UI will need some work, whoever adds/push template edits will get approved no questions asked, don't break the functionality.
Can be done before the merge in this PR or after in new PRs, it works as is, despite the un-prettyness.

2022-12-27 16:24 UTC, FluffyGhoster commented
!review

2023-01-13 11:29 UTC, NonQueueingMatt approved these changes

2023-03-01 17:29 UTC, Arrow768 requested changes

2023-03-01 17:29 UTC, Arrow768 commented on nano/templates/shipsensors.tmpl
> +	{{:helper.link('Clear', 'refresh', { 'scan' : 'clear' })}}
I am not really a fan of re-using the scan parameter here with "special" values for print/clear.
Instead that should be separate parameters.

2023-03-01 18:08 UTC, Arrow768 approved these changes

2023-03-04 22:27 UTC, merged