Cargo tug new sprite and fixes vehicles.
Aurorastation/Aurora.3 pull request #15474
Opened 2022-12-30 18:40 UTC by alsoandanswer

What was supposed to be a 5 minute resprite has turned into a 5 day vehicle fix and overhaul.

- fixes vehicle latching
- clarifies vehicle mechanics
- fixes crate and closet sprites being loaded onto trolleys
- clarifies vehicle mechanics
- refactors janicart and some cleanup

2022-12-30 20:13 UTC, Greenjoe12345 commented
The north/south sprites of the new cargo tug seem a bit odd to be still facing left/right
It somehow didn't feel as bad with the old isometric style sprite of them

2022-12-31 02:14 UTC, atteria commented
The tug's wagons _can't_ rotate because crates don't rotate.
And the 'somehow not as bad' feeling of the old cabinet projection sprites is just familiarity.

2023-01-02 13:43 UTC, NonQueueingMatt requested changes
Control clicking a cargo tug engine and then clicking "toggle latching" runtimes.

The cargo tug that spawns in Operations can't move at all. I suspect it has to do with something wonky in the way it latches things to itself when it spawns in, because spawning a new one works fine.

2023-01-02 13:43 UTC, NonQueueingMatt commented on code/modules/vehicles/bike.dm
> +		visible_message("\The kickstand prevents the bike from moving!") // This nearly tricked me into thinking bikes were broken. Fuck me. -Wezzy
```suggestion
		visible_message("The kickstand prevents the bike from moving!") // This nearly tricked me into thinking bikes were broken. Fuck me. -Wezzy
```

\The does not work if you don't have a var right next to it

2023-01-02 13:43 UTC, NonQueueingMatt commented on code/modules/vehicles/cargo_train.dm
> +		to_chat(usr, SPAN_WARNING("You can't remove \the [key] from \the [src] while its in use."))
```suggestion
		to_chat(usr, SPAN_WARNING("You can't remove \the [key] from \the [src] while it's in use."))
```

2023-01-05 11:50 UTC, NonQueueingMatt approved these changes

2023-01-07 21:06 UTC, Alberyk approved these changes

2023-01-07 21:35 UTC, SleepyGemmy requested changes

2023-01-07 21:35 UTC, SleepyGemmy commented on code/modules/vehicles/bike.dm
> +		visible_message("The kickstand prevents the bike from moving!") // This nearly tricked me into thinking bikes were broken. Fuck me. -Wezzy
```suggestion
		visible_message("The kickstand prevents the bike from moving!")
```

2023-01-07 21:35 UTC, SleepyGemmy commented on code/modules/vehicles/cargo_train.dm
> +			to_chat(user, SPAN_NOTICE("You slide \the [W] into \the [src]'s ignition."))
```suggestion
			to_chat(user, SPAN_NOTICE("You slide \the [W] into \the [src]\s ignition."))
```

2023-01-07 21:35 UTC, SleepyGemmy commented on code/modules/vehicles/cargo_train.dm
> +			to_chat(user, SPAN_NOTICE("There is already a key in [src]'s ignition."))
```suggestion
			to_chat(user, SPAN_NOTICE("There is already a key in \the [src]\s ignition."))
```

2023-01-07 21:35 UTC, SleepyGemmy commented on code/modules/vehicles/cargo_train.dm
> +		to_chat(user, SPAN_NOTICE("You turn on \the [src]'s ignition."))
```suggestion
		to_chat(user, SPAN_NOTICE("You turn on \the [src]\s ignition."))
```

2023-01-07 21:35 UTC, SleepyGemmy commented on code/modules/vehicles/cargo_train.dm
> +	to_chat(user, SPAN_NOTICE("You turn off \the [src]'s ignition."))
```suggestion
	to_chat(user, SPAN_NOTICE("You turn off \the [src]\s ignition."))
```

2023-01-07 21:35 UTC, SleepyGemmy commented on code/modules/vehicles/cargo_train.dm
> +		to_chat(user, SPAN_WARNING("You can't interact with \the [src] while its in use."))
```suggestion
		to_chat(user, SPAN_WARNING("You can't interact with \the [src] while it's in use."))
```

2023-01-07 21:35 UTC, SleepyGemmy commented on code/modules/vehicles/cargo_train.dm
> +	to_chat(user, SPAN_NOTICE("You take out \the [key] out of \the [src]'s ignition."))
```suggestion
	to_chat(user, SPAN_NOTICE("You take out \the [key] out of \the [src]\s ignition."))
```

2023-01-07 21:35 UTC, SleepyGemmy commented on code/modules/vehicles/train.dm
> +		latch(C, user) //BANDAID FIX MOMENT. GEEEEVES!!! ALSO GEM YOU DONT NEED TO MAKE A COMMENT TO REMOVE THIS. IT'S NOT LIKE ANYONE'S GOING TO SEE IT ANYWAY. I MEAN. NON PLAYER FACING CHANGES.
```suggestion
		latch(C, user)
```

2023-01-07 21:35 UTC, SleepyGemmy commented on code/modules/vehicles/train.dm
> +			to_chat(user, SPAN_WARNING("You were unable to load [C] on [src]."))
```suggestion
			to_chat(user, SPAN_WARNING("You were unable to load \the [C] on \the [src]."))
```

2023-01-07 21:35 UTC, SleepyGemmy commented on code/modules/vehicles/train.dm
> +		to_chat(user, SPAN_WARNING("[src] is too far away from [T] to hitch them together."))
```suggestion
		to_chat(user, SPAN_WARNING("\The [src] is too far away from \the [T] to hitch them together."))
```

2023-01-07 21:35 UTC, SleepyGemmy commented on code/modules/vehicles/train.dm
> +		to_chat(user, SPAN_WARNING("[src] is already hitched to something."))
```suggestion
		to_chat(user, SPAN_WARNING("\The [src] is already hitched to something."))
```

2023-01-07 21:35 UTC, SleepyGemmy commented on code/modules/vehicles/train.dm
> +		to_chat(user, SPAN_WARNING("[T] is already towing something."))
```suggestion
		to_chat(user, SPAN_WARNING("\The [T] is already towing something."))
```

2023-01-07 21:35 UTC, SleepyGemmy commented on code/modules/vehicles/train.dm
> +	to_chat(user, SPAN_NOTICE("You hitch [src] to [T]."))
```suggestion
	to_chat(user, SPAN_NOTICE("You hitch \the [src] to \the [T]."))
```

2023-01-07 21:35 UTC, SleepyGemmy commented on code/modules/vehicles/train.dm
> +		to_chat(user, SPAN_WARNING("[src] is not hitched to anything."))
```suggestion
		to_chat(user, SPAN_WARNING("\The [src] is not hitched to anything."))
```

2023-01-07 21:35 UTC, SleepyGemmy commented on code/modules/vehicles/train.dm
> +	to_chat(user, SPAN_NOTICE("You unhitch [src] from [lead]."))
```suggestion
	to_chat(user, SPAN_NOTICE("You unhitch \the [src] from \the [lead]."))
```

2023-01-07 22:16 UTC, SleepyGemmy approved these changes

2023-01-07 23:06 UTC, merged