Singletons + refactor of /datum/observ
Aurorastation/Aurora.3 pull request #15487
Opened 2023-01-02 16:47 UTC by FluffyGhoster

Refactored /datum/observ into /singleton/observ, added singleton base class and abstract meta-propriety as dependencies

2023-01-02 18:05 UTC, FluffyGhoster commented
!review

2023-01-02 22:55 UTC, alsoandanswer approved these changes

2023-01-03 15:03 UTC, NonQueueingMatt requested changes
Either make datum/observ into /decl/observ and ditch the singleton stuff, or replace all /decl/ with /singleton/, as they are the same thing.

2023-01-05 11:51 UTC, NonQueueingMatt approved these changes

2023-01-05 17:41 UTC, merged