Adds Medpouches (and other Bay Stuff)
Aurorastation/Aurora.3 pull request #15505
Opened 2023-01-04 09:07 UTC by alsoandanswer

For WickedCybs

Adds medpouches and adjusts first-aid kits to their Bay equivalents.

Q&A
- The health analysers are removed!
They'll still be in the Nanomed Plus (a.k.a, the Big One), which most of medical uses anyway.
This mostly removes them from first-aid kits and the small wall mounted ones.
(which face it, people rarely use, and the ones who need it, medical, already have it. Unless you're a powergamer.)
- The Autoinjectors/pills are missing!
Each medpouch comes with a pill and autoinjector. Technically this is a buff across the board.

Also : Renames cough syrup's chemical name to antidexafen. To match Bay counterpart. Most references are still cough syrup.
Adds radiation first aid kits to radiation closets. Not like anyone has trouble with radiation, but...

2023-01-04 09:48 UTC, DreamySkrell commented
> The health analysers are removed!
They'll still be in the Nanomed Plus (a.k.a, the Big One), which most of medical uses anyway.
This mostly removes them from first-aid kits and the small wall mounted ones.
(which face it, people rarely use, and the ones who need it, medical, already have it. Unless you're a powergamer.)

This is going to hurt third party ships, antags, and the like. Especially third party ships who do not have full medbays, and might need to rely on things like random crate supplies (first aid kits are pretty common there in my experience), or even just mapped in first aid kits.

> (which face it, people rarely use, and the ones who need it, medical, already have it. Unless you're a powergamer.)

Carrying and using a health analyzer is not powergaming. It's basic equipment that anyone can use. We even have an internal health analyzer augment that anyone can pick.

2023-01-04 14:35 UTC, SleepyGemmy commented
i second what dreamy wrote.

2023-01-04 18:09 UTC, TheDanseMacabre commented
I don't see any reason to make health analyzers less common/harder to attain. They should definitely still be in the wall-mounted nanomeds and I still think they should spawn in FAKs.

2023-01-05 00:02 UTC, alsoandanswer commented
!review

2023-01-05 02:51 UTC, alsoandanswer commented
I guess I'll have to elaborate.
**On Health Analyzers : It shoudn't be basic equipment.**
I believe the current examine is sufficient; you already can check pulse, bleeding, brute, burn without health analyzers.
Which is sufficient to *stabilize* anyone. You shouldn't be _anal-retentive_ about getting the guy to 100% health.
You shouldn't be able to save someone from the brink of death.
_That's medical's job. In my opinion, it is absolutely powergaming._ 

As for blood oxygenation, brain activity, toxins etc., if you aren't medical, 
most likely your character will not know this information, nor how to use it in any way.

On augments : This is an entirely different can of worms on balance and as such should not be used as a baseline.
In my honest opinion, really only medical should have access to health analysers.
(even then, they don't need it since it comes pre-loaded in their PDAs.)

2023-01-05 13:43 UTC, SleepyGemmy commented
i would recommend making a seperate atomic PR removing health analyzers.

2023-01-13 11:26 UTC, NonQueueingMatt requested changes
Health analyzers should stay in normal medkits for now. Split that removal into a different PR.

When you do make the PR to remove them, make sure to keep them in first aid kits used for third party ships.

2023-01-19 16:33 UTC, alsoandanswer commented
!review

2023-01-19 17:53 UTC, SleepyGemmy submitted a review, later dismissed
previous [review](https://github.com/Aurorastation/Aurora.3/pull/15505#pullrequestreview-1247480455) not addressed.

2023-01-21 11:45 UTC, NonQueueingMatt requested changes
Health analyzers will stay in medkits in this PR. Re-add them.

Reason being that health analyzers are not actually specialised equipment - see the health analyzer augment that anyone can take.

2023-01-21 18:34 UTC, SleepyGemmy requested changes
ditto my last review.

2023-02-07 14:34 UTC, NonQueueingMatt approved these changes

2023-02-07 20:54 UTC, SleepyGemmy requested changes

2023-02-07 20:54 UTC, SleepyGemmy commented on code/game/machinery/vending_types.dm
> +		/obj/item/storage/box/fancy/med_pouch/toxin,
```suggestion
		/obj/item/storage/box/fancy/med_pouch/trauma = 1,
		/obj/item/storage/box/fancy/med_pouch/burn = 1,
		/obj/item/storage/box/fancy/med_pouch/oxyloss = 1,
		/obj/item/storage/box/fancy/med_pouch/toxin = 1,
```

2023-02-07 20:54 UTC, SleepyGemmy commented on code/game/machinery/vending_types.dm
> +		/obj/item/storage/box/fancy/med_pouch/radiation,
```suggestion
		/obj/item/storage/box/fancy/med_pouch/trauma = 1,
		/obj/item/storage/box/fancy/med_pouch/burn = 1,
		/obj/item/storage/box/fancy/med_pouch/oxyloss = 1,
		/obj/item/storage/box/fancy/med_pouch/toxin = 1,
		/obj/item/storage/box/fancy/med_pouch/radiation = 1,
```

2023-02-07 20:54 UTC, SleepyGemmy commented on code/game/machinery/vending_types.dm
> +		/obj/item/device/breath_analyzer  = 1
```suggestion
		/obj/item/device/breath_analyzer = 1
```

2023-02-07 20:54 UTC, SleepyGemmy commented on code/game/objects/items/weapons/storage/firstaid.dm
> +		/obj/item/device/healthanalyzer
```suggestion
		/obj/item/device/healthanalyzer = 1
```

2023-02-07 20:54 UTC, SleepyGemmy commented on code/game/objects/items/weapons/storage/firstaid.dm
> +		/obj/item/device/healthanalyzer
```suggestion
		/obj/item/device/healthanalyzer = 1
```

2023-02-07 20:54 UTC, SleepyGemmy commented on code/game/objects/items/weapons/storage/firstaid.dm
> +		/obj/item/device/healthanalyzer
```suggestion
		/obj/item/device/healthanalyzer = 1
```

2023-02-07 20:54 UTC, SleepyGemmy commented on code/game/objects/items/weapons/storage/firstaid.dm
> +		/obj/item/device/healthanalyzer
```suggestion
		/obj/item/device/healthanalyzer = 1
```

2023-02-07 20:54 UTC, SleepyGemmy commented on code/game/objects/items/weapons/storage/firstaid.dm
> +		/obj/item/device/healthanalyzer
```suggestion
		/obj/item/device/healthanalyzer = 1
```

2023-02-07 20:54 UTC, SleepyGemmy commented on code/game/objects/items/weapons/storage/med_pouch.dm
> +	6) Use ointment on any burns if required<br>\
```suggestion
	6) Use ointment on any burns if required.<br>\
```

2023-02-07 20:54 UTC, SleepyGemmy commented on code/game/objects/items/weapons/storage/med_pouch.dm
> +	/obj/item/stack/medical/bruise_pack = 2
```suggestion
		/obj/item/reagent_containers/hypospray/autoinjector/pouch_auto/inaprovaline = 1,
		/obj/item/reagent_containers/pill/pouch_pill/inaprovaline = 1,
		/obj/item/reagent_containers/pill/pouch_pill/perconol = 1,
		/obj/item/stack/medical/bruise_pack = 2
```

2023-02-07 20:54 UTC, SleepyGemmy commented on code/game/objects/items/weapons/storage/med_pouch.dm
> +	/obj/item/stack/medical/ointment = 2
```suggestion
		/obj/item/reagent_containers/hypospray/autoinjector/pouch_auto/inaprovaline = 1,
		/obj/item/reagent_containers/hypospray/autoinjector/pouch_auto/mortaphenyl = 1,
		/obj/item/reagent_containers/hypospray/autoinjector/pouch_auto/adrenaline = 1,
		/obj/item/reagent_containers/pill/pouch_pill/perconol = 1,
		/obj/item/stack/medical/ointment = 2
```

2023-02-07 20:54 UTC, SleepyGemmy commented on code/game/objects/items/weapons/storage/med_pouch.dm
> +	/obj/item/reagent_containers/pill/pouch_pill/dexalin = 1
```suggestion
		/obj/item/reagent_containers/hypospray/autoinjector/pouch_auto/inaprovaline = 1,
		/obj/item/reagent_containers/hypospray/autoinjector/pouch_auto/dexalin = 1,
		/obj/item/reagent_containers/hypospray/autoinjector/pouch_auto/adrenaline = 1,
		/obj/item/reagent_containers/pill/pouch_pill/inaprovaline = 1,
		/obj/item/reagent_containers/pill/pouch_pill/dexalin = 1
```

2023-02-07 20:54 UTC, SleepyGemmy commented on code/game/objects/items/weapons/storage/med_pouch.dm
> +	/obj/item/reagent_containers/pill/pouch_pill/dylovene = 1
```suggestion
		/obj/item/reagent_containers/hypospray/autoinjector/pouch_auto/dylovene = 1,
		/obj/item/reagent_containers/pill/pouch_pill/dylovene = 1
```

2023-02-07 20:54 UTC, SleepyGemmy commented on code/game/objects/items/weapons/storage/med_pouch.dm
> +	/obj/item/reagent_containers/pill/pouch_pill/dylovene = 1
```suggestion
		/obj/item/reagent_containers/hypospray/autoinjector/hyronalin = 1,
		/obj/item/reagent_containers/pill/pouch_pill/dylovene = 1
```

2023-02-08 02:15 UTC, SleepyGemmy approved these changes

2023-02-08 10:27 UTC, merged