Changes the NT AI core to an SCC AI core.
Aurorastation/Aurora.3 pull request #15528
Opened 2023-01-06 15:54 UTC by 1Sparky1

Title.

2023-01-06 16:21 UTC, 1Sparky1 commented
!review

2023-01-06 16:25 UTC, SleepyGemmy requested changes
keep the NT icon as an alternative to the SCC default.

2023-01-06 18:24 UTC, SleepyGemmy approved these changes

2023-01-07 13:04 UTC, FluffyGhoster approved these changes

2023-01-07 21:07 UTC, Alberyk approved these changes

2023-01-09 16:22 UTC, merged