Security Goon Equipment
Aurorastation/Aurora.3 pull request #15548
Opened 2023-01-08 12:39 UTC by Geevies

* Added tactical coifs and goggles to the loadout for Security roles.

All sprites by HappyFox.

![image](https://user-images.githubusercontent.com/22774890/211196476-39ccc682-13a3-41b3-8a41-fd02b465188b.png)
![image](https://user-images.githubusercontent.com/22774890/211196481-67df12c7-c866-4fbf-ae36-9329f66fb85a.png)

2023-01-08 12:41 UTC, NonQueueingMatt requested changes
Goggles are fine, but coifs go to the armoury.

2023-01-14 07:58 UTC, Geevies commented
added secHUD and flash protection to the goggles by request

2023-01-20 16:48 UTC, alsoandanswer approved these changes

2023-01-20 16:48 UTC, alsoandanswer commented
!review

2023-01-21 11:33 UTC, NonQueueingMatt approved these changes

2023-01-21 12:21 UTC, merged