Hidden Offships
Aurorastation/Aurora.3 pull request #15544
Opened 2023-01-07 20:56 UTC by Geevies

* Ghostspawner ships now only spawn into the game area once its first crewmember wakes up.

2023-01-07 20:57 UTC, Geevies commented
!review

2023-01-07 20:57 UTC, Geevies commented
testmerge if possible cuz this might have unintended consequences

2023-01-08 02:12 UTC, WickedCybs commented
Would it be possible to have it be a toggle? Some sites in the future will likely have ghostspawns that activate once visitors arrive instead of being permanently on. There might also be situations where we still want the site accessible at all times if it's something like an exoplanet ruin or site.

2023-01-09 06:05 UTC, 4000daniel1 commented
Good change, but I have to second what Cybs said. I'm currently working on an away site that will function exactly how they described.

2023-01-15 18:43 UTC, Geevies commented
@WickedCybs @4000daniel1 yeah, if you want it to spawn into the play area without requiring a ghost role, just keep has_ghostroles_to_spawn set to false

2023-01-21 11:38 UTC, NonQueueingMatt requested changes

2023-01-21 11:38 UTC, NonQueueingMatt commented on code/modules/ghostroles/spawner/human/human.dm
> +			if(istype(map_sectors[z_level], visitable_overmap_type))
Instead of doing this, can't you just get the sector from the mob that just spawned? It'd also handle duplicates better.

2023-02-03 11:32 UTC, NonQueueingMatt approved these changes

2023-02-12 11:53 UTC, Geevies commented
!review

2023-02-12 15:04 UTC, alsoandanswer approved these changes

2023-02-12 17:57 UTC, merged