Tail Overhaul 2
Aurorastation/Aurora.3 pull request #15577
Opened 2023-01-15 16:46 UTC by Spookat

Updated Geeves' original Tail Overhaul #12785 with fixes that caused the SQL to break.

Adds a short tail variant for Tajara, and cloth accessories that can be attached to regular tails. More sprites will come if it gets merged.

Playtested, everything appears to be working correctly. Tail storage can be accessed under the Abilities tab.

As this PR is quite old, please let me know if there's anything wonky that could be changed.

2023-01-15 16:51 UTC, Spookat commented
!review

2023-01-21 11:29 UTC, NonQueueingMatt requested changes

2023-01-21 11:29 UTC, NonQueueingMatt commented on code/modules/organs/subtypes/standard.dm
> +
It seems a bit suspect that this doesn't check if the species actually has a tail.

2023-01-26 22:39 UTC, NonQueueingMatt approved these changes

2023-01-27 03:13 UTC, Alberyk approved these changes

2023-01-27 03:39 UTC, SleepyGemmy commented on SQL/migrate/V076__tail_overhaul.sql
> +-- Implemented in PR #numberhere.
```suggestion
-- Implemented in PR #15577.
```

2023-01-27 03:39 UTC, SleepyGemmy commented on code/game/objects/items/weapons/storage/internal.dm
> +
```suggestion
```

2023-01-27 03:42 UTC, SleepyGemmy commented on code/modules/clothing/tail_accessory.dm
> +	desc = "If you're seeing this, something went wrong! Please report it on Github."
```suggestion
	desc = DESC_PARENT
```

2023-01-27 03:43 UTC, SleepyGemmy commented on code/modules/mob/living/carbon/human/human_powers.dm
> +		to_chat(usr, SPAN_WARNING("Something went wrong with your tail storage, it's missing! (Report this on Github)"))
```suggestion
		to_chat(usr, SPAN_WARNING("Your tail storage is missing!"))
```

2023-02-05 19:22 UTC, merged