Helmet Storage Framework
Aurorastation/Aurora.3 pull request #15615
Opened 2023-01-21 14:54 UTC by Geevies

* You can now store cigarette packets in helmets.

![image](https://user-images.githubusercontent.com/22774890/213872442-042e25c0-4226-4737-9f00-2851c5bc51c9.png)
![image](https://user-images.githubusercontent.com/22774890/213872445-5cd280e7-de6d-4247-8a93-c5b220263d0f.png)
![image](https://user-images.githubusercontent.com/22774890/213872451-b1a98bd5-9440-4374-b338-e8afcf8d23e8.png)

2023-01-21 14:54 UTC, Geevies commented
!review

2023-01-21 18:37 UTC, SleepyGemmy submitted a review, later dismissed

2023-01-23 13:40 UTC, NonQueueingMatt requested changes

2023-01-23 13:40 UTC, NonQueueingMatt commented on code/modules/clothing/head/helmet.dm
> +/obj/item/clothing/head/helmet/attackby(obj/item/W as obj, mob/user as mob)
```suggestion
/obj/item/clothing/head/helmet/attackby(obj/item/W, mob/user)
```

2023-01-23 13:40 UTC, NonQueueingMatt commented on code/modules/clothing/head/helmet.dm
> +/obj/item/clothing/head/helmet/MouseDrop(obj/over_object as obj)
```suggestion
/obj/item/clothing/head/helmet/MouseDrop(obj/over_object)
```

2023-01-23 13:40 UTC, NonQueueingMatt commented on code/modules/clothing/head/helmet.dm
> +/obj/item/clothing/head/helmet/attack_hand(mob/user as mob)
```suggestion
/obj/item/clothing/head/helmet/attack_hand(mob/user)
```

2023-01-23 13:40 UTC, NonQueueingMatt commented on code/modules/clothing/head/helmet.dm
> +		for(var/obj/item/thing as anything in hold.contents)
```suggestion
		for(var/obj/item/thing in hold.contents)
```

2023-01-28 20:30 UTC, SleepyGemmy approved these changes

2023-01-29 11:31 UTC, NonQueueingMatt approved these changes

2023-01-29 11:46 UTC, merged