Musical instruments
Aurorastation/Aurora.3 pull request #15616
Opened 2023-01-21 17:46 UTC by FluffyGhoster

The final run for the implementation of musical instruments.

This PR implements the musical instruments using (mostly) a sound synthesizer, as ported from Baystation 12, capitalizing on the sound tokens and player from my previous PRs.

The guitar, violin and trumpeth can spawn in maintenance loots and be found from traders.

The piano and synthesizer (the actual instrument/object) will be orderable from cargo after the DB is updated accordingly to allow as such, we can eventually put one near the bar at roundstart like it was on Aurora (the station).

The old piano and violin implementations, along with their sounds, are removed from the game as requested by Matt.

### Asset Licenses
The following assets that have not been created by myself are included in this PR:

All the assets that were added are, to my knowledge, unmodified copy from Baystation12 which is released under the GNU Affero license as described in the Baystation 12 repository.

2023-01-21 18:19 UTC, FluffyGhoster commented
Cargo items when merged/testmerged to add (I hope I did everything correctly):

`name;supplier;description;categories;price;items;item_mul;access;container_type;groupable;order_by;error_message
polyguitar;nt;A polyguitar, better than a plain guitar.;"[""supply"",""hospitality""]";200;"{""PolyGuitar Instrument"":{""path"":""/obj/item/device/synthesized_instrument/guitar/multi"",""vars"":[]}}";1;0;box;1;\N;\N
violin;nt;An old violin.;"[""supply"",""hospitality""]";250;"{""Violin Instrument"":{""path"":""/obj/item/device/synthesized_instrument/violin"",""vars"":[]}}";1;0;box;1;\N;\N
trumpet;nt;An old trumpet.;"[""supply"",""hospitality""]";300;"{""Trumpet Instrument"":{""path"":""/obj/item/device/synthesized_instrument/trumpet"",""vars"":[]}}";1;0;box;1;\N;\N
piano;nt;A piano;"[""hospitality""]";1200;"{""Piano Instrument"":{""path"":""/obj/structure/synthesized_instrument/synthesizer/piano"",""vars"":[]}}";1;0;crate;0;\N;\N
sound synthesizer;nt;A sound synthesizer;"[""hospitality""]";1900;"{""Sound Synthesizer Instrument"":{""path"":""/obj/structure/synthesized_instrument/synthesizer"",""vars"":[]}}";1;0;crate;0;\N;\N`

2023-01-21 18:32 UTC, FluffyGhoster commented
!review

2023-01-23 13:37 UTC, NonQueueingMatt requested changes

2023-01-23 13:37 UTC, NonQueueingMatt commented on code/_helpers/maths.dm
> +
this is equivalent to Ceiling()

2023-01-23 13:37 UTC, NonQueueingMatt commented on code/modules/synthesized_instruments/real_instruments/Piano/piano.dm
> +// 	item_path = /obj/structure/synthesized_instrument/synthesizer/piano
commented code

2023-01-24 12:51 UTC, NonQueueingMatt requested changes

2023-01-24 12:51 UTC, NonQueueingMatt commented on code/__defines/_macros.dm
> +#define SPAN_CLASS(class, X) "<span class='[class]'>[X]</span>"
this is a duplicate of span(class, text) above

2023-01-29 11:22 UTC, NonQueueingMatt approved these changes

2023-02-03 22:42 UTC, Alberyk approved these changes

2023-02-03 22:46 UTC, merged