adds gpses to literally every ghostrole ship + sfa powerloader
Aurorastation/Aurora.3 pull request #15622
Opened 2023-01-22 05:07 UTC by RustingWithYou

Most ghost role ships now have GPSes, to make exoplanet navigation easier.

The SFA now has a new variant of the solarian powerloader, missing one of its clamps due to damage. In addition, the power loader aboard the FSF corvette has been replaced with a solarian power loader.

2023-01-22 05:08 UTC, RustingWithYou commented
!review

2023-01-22 16:15 UTC, SleepyGemmy requested changes

2023-01-22 16:15 UTC, SleepyGemmy commented on code/modules/heavy_vehicle/premade/powerloader.dm
> +/mob/living/heavy_vehicle/premade/ripley/loader/sol/fucked
```suggestion
/mob/living/heavy_vehicle/premade/ripley/loader/sol/damaged
```
non-descriptive path.

2023-01-22 16:15 UTC, SleepyGemmy commented on html/changelogs/rustingwithyou - offshipgps.yml
> +  - maptweak: "all ghost ships now have GPS units"
```suggestion
  - maptweak: "All ghost ships now have GPSes."
```

2023-01-22 16:15 UTC, SleepyGemmy commented on html/changelogs/rustingwithyou - offshipgps.yml
> +  - maptweak: "adds a amaged solarian powerloader and adds it to the sfa ship"
```suggestion
  - maptweak: "Adds a damaged Solarian powerloader and adds it to the SFA away ship."
```

2023-01-22 16:15 UTC, SleepyGemmy commented on maps/away/ships/sol_pirate/sfa_patrol_ship.dmm
> +/mob/living/heavy_vehicle/premade/ripley/loader/sol/fucked,
```suggestion
/mob/living/heavy_vehicle/premade/ripley/loader/sol/damaged,
```

2023-01-22 16:15 UTC, SleepyGemmy commented on html/changelogs/rustingwithyou - offshipgps.yml
> +  - maptweak: "replaces the FSF corvette's powerloader with a solarian powerloader"
```suggestion
  - maptweak: "Replaces the FSF corvette's powerloader with a Solarian powerloader."
```

2023-01-22 19:46 UTC, SleepyGemmy approved these changes

2023-01-23 13:34 UTC, NonQueueingMatt approved these changes

2023-01-23 19:25 UTC, Alberyk approved these changes

2023-01-25 11:35 UTC, merged