Give Machinists medical records again
Aurorastation/Aurora.3 pull request #15633
Opened 2023-01-23 05:26 UTC by FlamingLily

As the title says. Also included are some other science sort of stuff which they used to have, and seeing as they're still expected to do RnD judging by the RnD section of their workshop, I think it's not that radical.

2023-01-23 05:55 UTC, FlamingLily commented
!review

2023-01-23 06:34 UTC, alsoandanswer approved these changes

2023-01-23 13:33 UTC, NonQueueingMatt requested changes

2023-01-23 13:33 UTC, NonQueueingMatt commented on code/modules/modular_computers/file_system/programs/app_presets.dm
> +	display_name = "Operations - Robotics"
This all needs renaming to machinist.

2023-01-23 13:59 UTC, FlamingLily commented on code/modules/modular_computers/file_system/programs/app_presets.dm
> +	display_name = "Operations - Robotics"
including paths or just the names?

2023-01-23 14:02 UTC, FlamingLily reviewed
changed names to machinist

2023-01-29 11:31 UTC, NonQueueingMatt approved these changes

2023-01-29 11:46 UTC, merged