Heat Packs & Discomfort Tweaks
Aurorastation/Aurora.3 pull request #15659
Opened 2023-01-26 18:03 UTC by Geevies

* Added temperature pack accessories to the loadout menu, with heat and cold cooling/warming by 5 degrees celsius, and volcano and blizzard cooling/warming by 10 degrees celsius.
* Temperature discomfort messages are now based off body temperature instead of the temperature of the air your breath.
* Humans now sweat to get rid of heat.

2023-01-26 18:03 UTC, Geevies commented
!review

2023-01-26 21:03 UTC, SleepyGemmy requested changes

2023-01-26 21:03 UTC, SleepyGemmy commented on code/modules/clothing/under/accessories/temperature.dm
> +	icon = 'icons/obj/item/clothing/accessory/sweaters.dmi'
```suggestion
	icon = 'icons/obj/item/clothing/accessory/temperature.dmi'
```

2023-01-28 01:05 UTC, SleepyGemmy approved these changes

2023-02-03 11:30 UTC, NonQueueingMatt approved these changes

2023-02-03 11:33 UTC, merged