Overmap sensors overhaul
Aurorastation/Aurora.3 pull request #15666
Opened 2023-01-27 17:41 UTC by FluffyGhoster

The ship sensors now work as a sonar or radar, obscuring the view when the first object is pinged, otherwise the things not in range will not be seen.

The ships now need to be scanned before they appear and are identified, which takes a little of time.

### Asset Licenses
The following assets that **have not** been created by myself are included in this PR:

Everything added comes from Nebula, which is released as far as I'm aware under the Affero license

2023-01-27 17:51 UTC, NonQueueingMatt requested changes

2023-01-27 17:51 UTC, NonQueueingMatt commented on code/modules/overmap/ships/computers/sensors.dm
> +
commented code

2023-01-27 17:56 UTC, NonQueueingMatt requested changes

2023-01-27 17:56 UTC, NonQueueingMatt commented on code/modules/overmap/contacts/_contacts.dm
> +// /datum/overmap_contact/proc/check_effect_shield()
commented code

2023-01-27 19:58 UTC, FluffyGhoster commented
!review

2023-01-28 11:12 UTC, NonQueueingMatt requested changes

2023-01-28 11:12 UTC, NonQueueingMatt commented on code/modules/overmap/sectors.dm
> +		LAZYDISTINCTADD(associated_machinery[base_type], WEAKREF(machine))
All of this is assorted machinery stuff is unused now, so get rid of it

2023-01-28 11:12 UTC, NonQueueingMatt commented on code/modules/overmap/contacts/tracker.dm
> +	// icon_state = "disabled"
Port the icon for this

2023-01-28 11:12 UTC, NonQueueingMatt commented on code/modules/overmap/contacts/tracker.dm
> +	// set_extension(src, /datum/extension/interactive/multitool/store)
commented code

2023-01-28 11:12 UTC, NonQueueingMatt commented on code/modules/overmap/sectors.dm
> +	var/list/associated_machinery
remove this too

2023-01-28 11:12 UTC, NonQueueingMatt commented on code/modules/overmap/ships/computers/ship.dm
> +		linked = null
this bit needs to be removed since unregister_machine doesn't work

2023-01-29 11:23 UTC, NonQueueingMatt approved these changes

2023-02-03 22:37 UTC, Alberyk approved these changes

2023-02-03 22:39 UTC, merged