InUs Game-Helm Upgrade
Aurorastation/Aurora.3 pull request #15684
Opened 2023-01-29 18:52 UTC by Geevies

* It should now be a bit more obvious when people are playing with their InUs Game-Helm.

2023-01-29 18:52 UTC, Geevies commented
!review

2023-01-29 18:56 UTC, alsoandanswer commented on code/modules/games/gamehelm.dm
> +	playsound(user, 'sound/items/penclick.ogg', 25)
i think 'sound/weapons/blade_open.ogg' would sound better here

2023-01-29 19:17 UTC, SleepyGemmy requested changes

2023-01-29 19:17 UTC, SleepyGemmy commented on code/modules/games/gamehelm.dm
> +	)
this and anywhere else its used should respect custom item names.

2023-01-29 19:17 UTC, SleepyGemmy commented on code/modules/games/gamehelm.dm
> +	)
```suggestion
	)

```

2023-01-29 19:17 UTC, SleepyGemmy commented on code/modules/games/gamehelm.dm
> +			loc.quick_jitter(5)
not wanted if this vibrates the mob.

2023-01-29 19:17 UTC, SleepyGemmy commented on code/modules/games/gamehelm.dm
> +		playsound(loc, /singleton/sound_category/quick_arcade, 45)
a mute variable and a context menu or attack_self toggle would be appreciated.

2023-01-29 19:17 UTC, SleepyGemmy commented on code/modules/games/gamehelm.dm
> +			loc.visible_message("<b>[loc]</b> [picked_action]!", SPAN_NOTICE("You [self_action]!"), range = 3)
this will get spammy very quick for the player and anyone nearby. make it a toggle and/or do something with world.time so it happens once in a while.

2023-03-19 12:57 UTC, Geevies commented
too lazy to continue with this one, but should be easy enough for a contrib to fix up, feel free to take it

2023-09-16 12:13 UTC, Geevies commented
!review

2023-09-16 12:40 UTC, alsoandanswer approved these changes

2023-09-16 21:42 UTC, SleepyGemmy approved these changes
all requested changes addressed.

2023-09-23 11:36 UTC, merged