Replaces Lame Captain Laser With Badass Gigarevolver
Aurorastation/Aurora.3 pull request #15707
Opened 2023-02-02 05:22 UTC by TheDanseMacabre

This PR replaces the captain's antique laser with a child object of the autorevolver, which has slightly worse stats compared to its parent but is still very lethal. Sprite taken from Eris, potentially pending an original Auroran sprite.

2023-02-02 05:31 UTC, TheDanseMacabre commented
!review

2023-02-02 08:53 UTC, alsoandanswer commented
Hard no from me. This isn't much of an improvement to our current sprite, and changing it to a ballistic weapon seems like a pretty odd and arbritrary reason.

2023-02-02 12:21 UTC, TheDanseMacabre commented
> Hard no from me. This isn't much of an improvement to our current sprite, and changing it to a ballistic weapon seems like a pretty odd and arbritrary reason.

While I'm sorry you don't like the sprite, the captain's antique laser is an extremely ugly and outdated sprite for 2010~, with a nonsensical meme description and pitiful ingame performance. The odd and arbitrary reason is pretty straightforward: this is supposed to give the captain an impressive and powerful sidearm with limited uses. It is supposed to be an intimidating weapon for the highest ranking character on the ship, and achieves this. The fact it is a ballistic weapon is irrelevant.

2023-02-02 13:09 UTC, Generalcamo commented
> This isn't much of an improvement to our current sprite
Can you please elaborate on this, so that the sprite creator may make any needed modifications?

2023-02-02 13:25 UTC, alsoandanswer commented
For the sprite being old, a better alternative would've been just to port the /tg/ sprite rather than go through all this trouble.

As for the weapon performance, there could've just been a buff and tweak.

As for it being changed for a ballistic weapon, I'd still prefer it remaining as an energy weapon.

2023-02-02 14:36 UTC, SleepyGemmy requested changes

2023-02-02 14:36 UTC, SleepyGemmy commented on code/game/objects/structures/displaycase.dm
> +	spawn_contained_type = /obj/item/gun/projectile/revolver/mateba/captain_revolver
```suggestion
	spawn_contained_type = /obj/item/gun/projectile/revolver/mateba/captain
```

2023-02-02 14:36 UTC, SleepyGemmy commented on code/modules/projectiles/guns/projectile/revolver.dm
> +/obj/item/gun/projectile/revolver/mateba/captain_revolver
```suggestion
/obj/item/gun/projectile/revolver/mateba/captain
```

2023-02-02 14:36 UTC, SleepyGemmy commented on code/modules/projectiles/guns/projectile/revolver.dm
> +	name = "SCC command revolver"
```suggestion
	name = "\improper SCC command revolver"
```

2023-02-02 14:36 UTC, SleepyGemmy commented on code/modules/projectiles/guns/projectile/revolver.dm
> +	desc = "A ludicrously powerful .454 revolver with equally ludicrous recoil which is issued by the Conglomerate to the administrators of critical facilities and vessels. While revolvers may be a thin
```suggestion
	desc = "A ludicrously powerful .454 revolver with equally ludicrous recoil which is issued by the SCC to the administrators of critical facilities and vessels. While revolvers may be a thing of the past, the stopping power displayed by this weapon is second to none."
```

2023-02-02 14:36 UTC, SleepyGemmy commented on code/modules/projectiles/guns/projectile/revolver.dm
> +	desc_extended = "A Zavodskoi Interstellar design from the mid-2450s intended for export to the Eridani Corporate Federation and Republic of Biesel, the Protektor \
```suggestion
	desc_extended = "A Zavodskoi Interstellar design from the mid 2450s intended for export to the Eridani Corporate Federation and the Republic of Biesel, the Protektor \
```

2023-02-02 14:36 UTC, SleepyGemmy commented on code/modules/projectiles/guns/projectile/revolver.dm
> +	Revolver was never designed with practicality in mind. The .454 rounds fired from this weapon are liable to snap the wrist of an unprepared shooter and \
```suggestion
	revolver was never designed with practicality in mind. The .454 rounds fired from this weapon are liable to snap the wrist of an unprepared shooter and \
```

2023-02-02 14:36 UTC, SleepyGemmy commented on code/modules/projectiles/guns/projectile/revolver.dm
> +	practicality: they buy it due to having too much money and wanting a revolver large enough for their ego. Isn't that why you're holding it right now, captain?"
```suggestion
	practicality: they buy it due to having too much money and wanting a revolver large enough for their ego."
```

2023-02-02 16:25 UTC, SleepyGemmy approved these changes

2023-02-02 22:58 UTC, TheDanseMacabre commented
I don't really think a /tg/ port is an improvement by any means.

2023-02-03 17:14 UTC, FluffyGhoster approved these changes

2023-02-03 17:14 UTC, FluffyGhoster commented on code/modules/projectiles/guns/projectile/revolver.dm
> +	desc = "A ludicrously powerful .454 autorevolver with equally ludicrous recoil which is issued by the SCC to the administrators of critical facilities and vessels. While revolvers may be a thing of
I'm not an english expect by any means, but the "which is issued" part feels like it should be preceded by a comma, or the "which" be a "that"

2023-02-03 17:14 UTC, FluffyGhoster commented on code/modules/projectiles/guns/projectile/revolver.dm
> +	any following shots will be difficult to place onto a human-sized target due to the recoil, let alone a skrell. But nobody buys a Protektor for the purpose of \
The "But nobody" part could sound better if it was after a comma, or the "but" a "however,"

2023-02-03 22:58 UTC, NonQueueingMatt approved these changes
Fine with it, but the ammo needs to remain unattainable.

2023-02-03 23:05 UTC, TheDanseMacabre commented
> Fine with it, but the ammo needs to remain unattainable.

No problem with that on my end.

2023-02-07 06:00 UTC, alsoandanswer commented
said in discord, reiterating here there should be a feature to choose whether you want a ballistic or the old laser weapon like how polaris allows you to choose your weapon.

2023-02-11 11:06 UTC, NonQueueingMatt commented
> said in discord, reiterating here there should be a feature to choose whether you want a ballistic or the old laser weapon like how polaris allows you to choose your weapon.

Unwanted feature at the moment.

2023-02-11 20:23 UTC, merged