Adds a power knot to xenoarch
Aurorastation/Aurora.3 pull request #15703
Opened 2023-02-01 20:27 UTC by LoreCoder

Used for powering emitters, which are needed for certain anomalies. (see below)
![image](https://user-images.githubusercontent.com/63847722/216155863-20558e74-2b9d-4f1a-8005-389695c37e49.png)

2023-02-01 20:35 UTC, listerla commented on html/changelogs/researchpowerknot.yml
> +  - rscadd: "Adds a power knot to Xenoarcheology for powering emitters."
```suggestion
  - rscadd: "Adds a power knot to Xenoarchaeology for powering emitters."
```

2023-02-02 15:50 UTC, LoreCoder commented
!review

2023-02-02 16:01 UTC, SleepyGemmy requested changes
huge diff, see if you can fix it somehow.

2023-02-03 17:14 UTC, LoreCoder commented
closing to fix diff issues

2023-02-03 17:14 UTC, closed without merging