bigger notification for black kois lobotomy
Aurorastation/Aurora.3 pull request #15726
Opened 2023-02-04 05:44 UTC by Sniblet

Instead of two normal-sized lines using red and white font, which you're already getting a lot of in this stage of your lii'draic journey, the final, mind-shattering stage of black k'ois mycosis now gives you three lines of flavor text, one of which is span_good, and one of which is SPAN_HIGHDANGER.
HIGHDANGER looks the same as serious pain notifications:
![image](https://user-images.githubusercontent.com/36427443/216751073-eece8dd1-b2d1-4629-bef1-b1fde9c36654.png)
!review

2023-02-04 12:59 UTC, Generalcamo requested changes

2023-02-04 12:59 UTC, Generalcamo commented on code/modules/organs/subtypes/parasite.dm
> +			to_chat(owner, "<span class='good'>As the K'ois consumes your mind, you feel your past self, your memories, your very being slip away... only slavery to the swarm remains...</span>")
```suggestion
			to_chat(owner, SPAN_GOOD("As the K'ois consumes your mind, you feel your past self, your memories, your very being slip away... only slavery to the swarm remains..."))
```

2023-02-04 12:59 UTC, Generalcamo commented on code/modules/organs/subtypes/parasite.dm
> +			to_chat(owner, "<span class='highdanger'>You have been lobotomized by K'ois infection.</span>")
Add `SPAN_HIGHDANGER` to `_macros.dm`

2023-02-04 12:59 UTC, Generalcamo commented on code/modules/organs/subtypes/parasite.dm
> +			to_chat(owner, "<span class='notice'><b>All of your previous memories up until this point are gone, and all of your ambitions are nothing. You live for only one purpose; to serve the Lii'dra hive.
```suggestion
			to_chat(owner, SPAN_NOTICE("All of your previous memories up until this point are gone, and all of your ambitions are nothing. You live for only one purpose; to serve the Lii'dra hive."))
```

2023-02-04 20:27 UTC, Sniblet commented
updated screenshots to actually compare, and it now complies
!review

2023-02-06 00:27 UTC, desvenlafaxine commented
I would use different wording. Perhaps “Your brain has been consumed by...” Lobotomy just sounds odd.

2023-02-07 03:39 UTC, Alberyk approved these changes

2023-02-07 11:58 UTC, NonQueueingMatt approved these changes

2023-02-07 12:04 UTC, merged