Aut'akh Origins and Cultures + Accent Goodies
Aurorastation/Aurora.3 pull request #15729
Opened 2023-02-04 09:42 UTC by Geevies

* Added a culture for Aut'akh, as well as an origin for the various communes. Additionally, added a unique accent for Aut'akh, and Sinta dregs living in the Eridani underbelly.

# ! THIS HAS NOT BEEN CLEARED WITH THE LORE TEAM !

this is just something I thought was cool and would like to propose. we can add and remove stuff or bin this all-together if the lore team doesn't want it

anyway here's the stuff

| Culture & Origins |
 - Aut'akh
   - Aut'akh Valley
   - Undercity Communes
   - Eridani Underworld Commune
   - Razortail Enclave
   - Unknown Aut'akh Commune (headcanon commune)

descriptions ripped from the wiki, unknown commune still needs a description (i'm a better coder than a writer)

| Accents |

- Aut'akh Dialect
  - A mix of all the unathi accents + a little techno spice
![image](https://user-images.githubusercontent.com/22774890/216760290-d9492aa6-0927-4694-b97c-e30cda7c2113.png)

- Sintese Eridanian Dreg
  - Unathi Dregs, pretty much (this will need human lore approval too) (and probably a spriter)
![image](https://user-images.githubusercontent.com/22774890/216760307-f4aec20e-ea51-4003-a07b-3066258baa61.png)

both of these need descriptions

2023-02-07 06:06 UTC, alsoandanswer commented
!review

2023-02-07 06:07 UTC, alsoandanswer approved these changes
Code looks fine to me. Just needs to be cleared with lore team

2023-02-07 11:57 UTC, NonQueueingMatt requested changes

2023-02-07 11:57 UTC, NonQueueingMatt commented on code/modules/background/accent/unathi.dm
> +	description = "TO-DO get an actual writer to expand on this A crude mix of Hegemonic, Traditionalist and Wastelander dialects owing to Sinta from all walks of life living in a commune together."
Edit this.

2023-02-07 11:57 UTC, NonQueueingMatt commented on code/modules/background/accent/unathi.dm
> +	description = "TO-DO get an actual writer to do this"
Edit this.

2023-04-03 20:12 UTC, CaptainGecko commented
Speaking for the lore team here!

We won't take the Eri-Dreg accent, but the standard Aut'akh accent is good to go! As far as the accent desc goes, here's a slightly modified version:
"_Incorporating both Hegemonic and Traditionalist elements, the Aut'akh accent is recognisable for its lack of accentuation and intonations, both owing to the occasional implants of questionable quality having some influence on speech, and the general isolation of most Aut'akh communes._"

2023-04-04 16:27 UTC, CaptainGecko commented
It's me again! Because I can't use or read Git like the dumbass I am I forgot about the description for the "Unknown Aut'akh Commune", so here it is.

"Either due to their fellow Unathi rejecting them and their way of life, or life among other species and cultures feeling too alien when away from Hegemonic space, most Aut'akh inevitably end up forming communes and living among each other in these. Aside from the few notable, larger communes, many more minor communes exist across the Spur."

Also, just talked to Geeves about this so it's probably already going to be handled, but the "Unknown Aut'akh Commune" needs the Solarian citizenship option removed, as they cannot speak Sol Common, and knowledge of the solarian tongue is required to obtain said citizenship.

2023-04-04 16:48 UTC, Geevies commented
!review

2023-04-05 16:02 UTC, NonQueueingMatt approved these changes

2023-04-05 16:25 UTC, merged