Machinery Resprite
Aurorastation/Aurora.3 pull request #15763
Opened 2023-02-07 10:05 UTC by alsoandanswer

Sorts objects.dmi and stationobjs.dmi

Ports machinery sprites from /tg/ and bay. Updates old codersprites.

For Danse and Desven.

2023-02-07 10:36 UTC, alsoandanswer commented
!review

2023-02-07 11:56 UTC, NonQueueingMatt requested changes
The weapons analyzer places an overlay of the weapon over itself, which is now unaligned with the new sprite:
![immagine](https://user-images.githubusercontent.com/13016572/217237565-9acbc20c-a5dd-40a7-8df3-f70165a1fb24.png)

2023-02-07 11:56 UTC, NonQueueingMatt commented on code/game/machinery/autolathe/autolathe.dm
> +	//	 mat_colour = eating.matter[material].icon_color
Commented code.

2023-02-07 17:10 UTC, ScheveningenZonn commented
![image](https://user-images.githubusercontent.com/11053780/217313465-28b9cc40-9fed-4cd4-8699-4b485ffa9917.png)

The images on the right for the RND machinery appear to lack design consistency between various pieces of machinery (silver-colored to deep carbon black to silver-colored again). The machinery as we have now are Aurora-unique. The RND machinery in your proposal very clearly have TG's spriting design philosophy in mind and not one of an aesthetic unique to Aurora. I see no reason to go backward to what we had before.

The current pipe dispenser and shield generators are very ugly and would be welcome to have new sprites, but I think you are making a mistake overwriting the RND machinery.

2023-02-07 21:18 UTC, SleepyGemmy submitted a review, later dismissed

2023-02-07 21:18 UTC, SleepyGemmy commented on html/changelogs/wezzy_machinery_scenery.yml
> +  - imageadd: "Ports machinery sprites from /tg/."
```suggestion
  - imageadd: "Ports machinery sprites from /tg/."
  - rscdel: "Removes some unused objects and sprites."
```

2023-02-07 22:26 UTC, alsoandanswer commented
!wip

2023-02-07 22:26 UTC, alsoandanswer commented
Putting on hold while discussing with other spriters

2023-04-15 20:13 UTC, NonQueueingMatt commented
reopen when ready

2023-04-15 20:13 UTC, closed without merging