A Brief Case For Briefcases (the funny exploit fix)
Aurorastation/Aurora.3 pull request #15769
Opened 2023-02-07 17:31 UTC by alsoandanswer

yeah this should hopefully fix it

i have no idea how gear spawning works

2023-02-07 17:31 UTC, alsoandanswer commented
!bugfix

2023-02-07 17:32 UTC, alsoandanswer commented
!review

2023-02-07 17:34 UTC, UponASeaOfStars commented
the briefcase bandit has been brought to bear!

2023-02-07 17:44 UTC, alsoandanswer commented
> Undocumented change: Makes all the non-secure briefcases 2 points as well. Currently secure is 2 points, others in the selection 1.
> 
> Which is lame. Please no merge of secure and non-secure briefcases.

I wish I could, but it turns out that if you select both in the loadout it'll force one into your backpack anyway (because you already have a briefcase in your hand)

2023-02-07 17:56 UTC, UponASeaOfStars commented
This bug has ravaged our community and destroyed countless lives, and I know of at least one nefarious ne'er-do-well who even used it to powergame by putting things in the briefcase! The scourge of Aurora has been removed, and for that, you have my eternal gratitude. May you be blessed as I am blessed to have seen this PR. Godspeedmerge to you, good coder.

in all seriousness though this is a good pr i don't want anyone else getting clowned on

2023-02-07 23:17 UTC, Arrow768 submitted a review, later dismissed

2023-02-08 10:47 UTC, DreamySkrell commented on html/changelogs/wezzy_la_exploit.yml
> +  - bugfix: "Fixes recursive loadout storage items."
Undocumented change of all briefcases now costing 2 points. Previously they were 1 points, with only the secure briefcase being 2 points.

2023-02-08 11:22 UTC, UponASeaOfStars commented
> > Undocumented change: Makes all the non-secure briefcases 2 points as well. Currently secure is 2 points, others in the selection 1.
> > Which is lame. Please no merge of secure and non-secure briefcases.
> 
> I wish I could, but it turns out that if you select both in the loadout it'll force one into your backpack anyway (because you already have a briefcase in your hand)

Regarding this-- would it be possible to have a secure briefcase spawn in your _other_ hand? Left hand for regular, right hand for secure? Or are there already job items that spawn in the hand, which would then cause the briefcase to go into the backpack?

2023-02-09 04:42 UTC, SleepyGemmy requested changes
document the briefcase point increase in the changelog (and preferably PR description too.)
document the secure briefcase being merged into the briefcase selection.

2023-02-09 04:43 UTC, SleepyGemmy commented
this is not really a fix.
a better solution would be to try and spawn huge items in hands first and if not possible, spawn them on the ground.

2023-02-09 04:45 UTC, SleepyGemmy commented
not a bugfix PR as it changes the briefcase selection cost.

2023-02-09 04:51 UTC, SleepyGemmy commented
this is not really a fix.
a better solution would be to try and spawn huge items in hands first and if not possible, spawn them on the ground, i.e. by checking if the hands are full and if they are, spawning the items on the ground.

2023-02-09 05:30 UTC, alsoandanswer commented
> > > Undocumented change: Makes all the non-secure briefcases 2 points as well. Currently secure is 2 points, others in the selection 1.
> > > Which is lame. Please no merge of secure and non-secure briefcases.
> > 
> > 
> > I wish I could, but it turns out that if you select both in the loadout it'll force one into your backpack anyway (because you already have a briefcase in your hand)
> 
> Regarding this-- would it be possible to have a secure briefcase spawn in your _other_ hand? Left hand for regular, right hand for secure? Or are there already job items that spawn in the hand, which would then cause the briefcase to go into the backpack?

Yes, that's the purse

2023-02-09 05:34 UTC, alsoandanswer commented
> this is not really a fix. a better solution would be to try and spawn huge items in hands first and if not possible, spawn them on the ground, i.e. by checking if the hands are full and if they are, spawning the items on the ground.

if someone is able and willing to implement this feature, then they are free to revert the changes in this PR

but at the moment, in my opinion, a slightly more expensive loadout item is better than a exploit left in a game.

2023-04-15 20:14 UTC, closed without merging