Better sensors range input - buttons for each setting
Aurorastation/Aurora.3 pull request #15770
Opened 2023-02-07 19:02 UTC by DreamySkrell

![image](https://user-images.githubusercontent.com/107256943/217340625-832292b7-f42a-4445-ab08-6c038a0f06e6.png)
![image](https://user-images.githubusercontent.com/107256943/217340647-bc2cbdea-2b8a-4c03-bc48-ac9b61bb19fb.png)

2023-02-07 19:03 UTC, DreamySkrell commented
all my homies hate input()

2023-02-07 20:57 UTC, SleepyGemmy commented on code/modules/overmap/ships/computers/sensors.dm
> +		if (href_list["range_choice"])
```suggestion
		if(href_list["range_choice"])
```

2023-02-07 20:57 UTC, SleepyGemmy commented on code/modules/overmap/ships/computers/sensors.dm
> +			if (nrange)
```suggestion
			if(nrange)
```

2023-02-07 20:57 UTC, SleepyGemmy commented on html/changelogs/DreamySkrell-sensors-436357547.yml
> +  - rscadd: "Changes the sensors console range input to a button select like [1][2][3][4][5][6][7]."
```suggestion
  - tweak: "Changes the sensors console range input to a button selection ranging from 1 to 7."
```

2023-02-07 23:05 UTC, SleepyGemmy approved these changes

2023-02-09 21:14 UTC, NonQueueingMatt approved these changes

2023-02-10 05:39 UTC, runecap commented
This prevents you from using decimals and that removes the very common "1.5" sensor range people use. It lets you see 2 tiles without gaining heat; change this without touching heat efficiency in sensors and piloting would become more frustrating, not less.

2023-02-10 05:43 UTC, Caelphon commented
> This prevents you from using decimals and that removes the very common "1.5" sensor range people use. It lets you see 2 tiles without gaining heat; change this without touching heat efficiency in sensors and piloting would become more frustrating, not less.

This just sounds like an exploit? You're putting in a number that isn't 2, and getting the same result.

2023-02-10 21:12 UTC, runecap commented
> This just sounds like an exploit? You're putting in a number that isn't 2, and getting the same result.

It is, but 1.5 for sensors is so common for piloting that removing it would still be a nerf. I think this is also resolvable through small mapping changes, though. The only ships and shuttles that rely on 1.5 range use the 'weak' variant of ship sensors.
Mapping is probably out of the scope of this PR, however.

2023-02-12 12:08 UTC, DreamySkrell commented
> This prevents you from using decimals and that removes the very common "1.5" sensor range people use. It lets you see 2 tiles without gaining heat; change this without touching heat efficiency in sensors and piloting would become more frustrating, not less.

I'd say that's an exploit/oversight, and unintentional, yeah.

Also like, imo, currently heat is way too fast/high, and range way too small, so like feel free to change that if you'd like.

2023-02-12 17:56 UTC, NonQueueingMatt requested changes
Tweak the heat formula to allow for 3 sensor range without heating up.

2023-02-12 20:35 UTC, DreamySkrell commented
![image](https://user-images.githubusercontent.com/107256943/218335665-763c6d11-7ea9-4637-93d7-586920e87098.png)

2023-02-12 21:28 UTC, DreamySkrell commented
@NonQueueingMatt Changes addressed I think.

2023-02-13 11:13 UTC, merged