Grauwolf Sensor Probe Projectile
Aurorastation/Aurora.3 pull request #15817
Opened 2023-02-13 18:24 UTC by FluffyGhoster

Added a grauwolf probe projectile, can reveal things in a radius, does not hit anything and possess no damage, basically a minigame to extend sensor range.

WIP, sprites wished

2023-02-13 18:24 UTC, FluffyGhoster commented
!wip

2023-02-14 00:31 UTC, Generalcamo requested changes

2023-02-14 00:31 UTC, Generalcamo commented on code/modules/overmap/ship_weaponry/weaponry/grauwolf_probe.dm
> +	desc = "A sensor probe, used to illuminate the area ahead using the dataling."
```suggestion
	desc = "A gun-launched sensor probe, used to scan the area ahead using the datalink."
```

2023-02-15 15:04 UTC, FluffyGhoster commented
should be good, so !review

2023-03-03 01:25 UTC, Alberyk approved these changes

2023-04-09 10:30 UTC, NonQueueingMatt requested changes

2023-04-09 10:30 UTC, NonQueueingMatt commented on code/modules/overmap/ship_weaponry/weaponry/grauwolf_probe.dm
> +	return TRUE
Don't really like this copypaste here. Whatever changes here should just be integrated into the parent proc if possible.

2023-04-09 10:30 UTC, NonQueueingMatt commented on code/modules/overmap/ship_weaponry/weaponry/grauwolf_probe.dm
> +	remove_contacts:
Origin needs to be nulled out here.

2023-04-09 10:30 UTC, NonQueueingMatt commented on code/modules/overmap/ship_weaponry/weaponry/grauwolf_probe.dm
> +	var/obj/effect/overmap/visitable/origin = null
You don't need to redefine this. Already present in `ammunition.origin`

2023-04-15 20:08 UTC, NonQueueingMatt approved these changes

2023-04-15 21:08 UTC, merged