Adds a necklace to the loadout
Aurorastation/Aurora.3 pull request #15870
Opened 2023-02-20 21:00 UTC by feartheblackout

Title. I'm surprised we didn't have this sooner.

Sprites obtained from Baystation 12's code repository.

2023-02-20 21:00 UTC, feartheblackout commented
!review

2023-02-20 21:17 UTC, SleepyGemmy requested changes
utilize contained sprites.
i.e. `icons/obj/item/clothing/accessory/necklace.dmi` instead of `icons/mob/ties.dmi` and `icons/obj/clothing/ties.dmi`.

2023-02-20 21:17 UTC, SleepyGemmy commented on code/modules/clothing/under/accessories/accessory.dm
> +	item_state = "necklace"
```suggestion
/obj/item/clothing/accessory/necklace
	name = "necklace"
	desc = "A piece of jewelry that goes around your neck."
	icon = 'icons/obj/item/clothing/accessory/necklace.dmi'
	icon_state = "necklace"
	item_state = "necklace"
	contained_sprite = TRUE
```

2023-02-22 19:52 UTC, SleepyGemmy approved these changes

2023-02-27 02:53 UTC, Arrow768 approved these changes

2023-02-27 15:27 UTC, merged