The Circus is Here
Aurorastation/Aurora.3 pull request #15874
Opened 2023-02-21 15:41 UTC by Alberyk

This pr revives #14882.

It is now complete and ready to be reviewed.

2023-02-22 02:22 UTC, alsoandanswer approved these changes

2023-02-22 10:32 UTC, WickedCybs requested changes
The exterior of the ship should have entry points mapped in each cardinal direction.

I'd suggest having the shuttle not share the rectangle design and lack of systems other old away sites had. Since this is an old map being revived though I suppose you can skip that for now if needed.

Also, one other thing. The transit area doesn't need to be as big as it is. You can delete the bigger square and transit navpoint as I'm assuming the mothership isn't going to be making any overmap transitions and it wouldn't fit that space anyway. It only needs to be big enough to accommodate the shuttle's transit area. So the red area I outlined could be removed and you could make that area of your map far smaller and avoid people hitting the transition early.

![image](https://user-images.githubusercontent.com/52309324/220594107-49ce9211-ccdb-4847-b0c4-10378b0b59af.png)

2023-02-25 14:07 UTC, DreamySkrell commented
The ship has no airlocks to go EVA, and has no navpoints on the outside. It should have both.

The main stage in the center is very big, and people at the edge, on the stairs/seating, would not be able to see the whole stage (with default view size and no binoculars).

Personally, in general I think the whole ship is unnecessarily big and has lots and lots of wasted space. Like at the bar, with the default view size, and standing right in the center of the tables, the bartender can *just barely* see everyone sitting at the bar stools.

Everything is way too big, and is set up for like 50 visitors, where in reality that number is going to be closer to 5. It also has 7 ghost roles, which is a lot.

Also this uses `spawn_cost` instead of `ship_cost`. It's a ship with ghost roles, so it should use the ship away site generation pool.

2023-04-21 22:54 UTC, Alberyk commented
All concerns should be handled now.

2023-04-28 00:48 UTC, WickedCybs approved these changes

2023-04-30 21:10 UTC, NonQueueingMatt approved these changes

2023-04-30 21:24 UTC, merged