Visegradi Clothes PR
Aurorastation/Aurora.3 pull request #15872
Opened 2023-02-21 05:29 UTC by TheDanseMacabre

WIP. Two of three are fucking BROKEN. Credits to Wezzy for nyakas and ponczo sprites.

2023-02-21 05:30 UTC, TheDanseMacabre commented
!wip

2023-03-14 06:45 UTC, TheDanseMacabre commented
!review

2023-03-14 07:43 UTC, FluffyGhoster approved these changes

2023-03-14 20:30 UTC, Alberyk approved these changes

2023-03-16 21:00 UTC, SleepyGemmy requested changes
the nyakas will need to be made into a contained sprite.

2023-03-17 00:58 UTC, TheDanseMacabre commented
> the nyakas will need to be made into a contained sprite.

done

2023-03-17 00:59 UTC, SleepyGemmy commented on code/modules/clothing/head/misc_special.dm
> +
```suggestion
```

2023-03-17 17:24 UTC, merged