Fixes psi-ping sprites lingering
Aurorastation/Aurora.3 pull request #15928
Opened 2023-03-02 03:45 UTC by meep109

Right now, psi ping circles stay on the screen until you restart the client. This should fix it. My first PR please tell me if I messed up

2023-03-02 03:48 UTC, meep109 commented
!review

2023-03-02 03:49 UTC, SleepyGemmy approved these changes

2023-03-02 08:01 UTC, NonQueueingMatt requested changes
Have you tested these changes? I remember doing this exact same thing to try and fix this bug but it didn't work

2023-03-04 22:46 UTC, meep109 commented
> Have you tested these changes? I remember doing this exact same thing to try and fix this bug but it didn't work

I tested it. Works fine on my server

2023-03-11 11:05 UTC, Arrow768 approved these changes

2023-03-11 16:41 UTC, merged