LARP Expansion Pack DLC - Tactical lying down
Aurorastation/Aurora.3 pull request #15952
Opened 2023-03-05 07:56 UTC by FluffyGhoster

Added the Ability to lie down intentionally, tactical lying down is now toggable with a middle mouse button on the walk/run icon.

Lying down tactically let you retain your weapons and items in hand, and operate them, while lying down tactically AND wielding, you get a 10% bonus on precision, recoil and fire speed, but a large movement speed penalty.

You have to unwield any weapon you might have in hand before tactically lying down or standing up from a tactical lying down.

Human and playable species mobs now change orientation, while lying down, depending on the direction they're facing, indifferently if they are lying down intentionally or not.

Added tactical lying down HUD icons, made by myself, probably not looking as nice, feel free to supply better quality icons.

Testmerge is recommended.

2023-03-05 08:11 UTC, FluffyGhoster commented
!review

2023-03-05 12:27 UTC, SleepyGemmy commented
would probably be better to just make this innate of regular resting.

2023-03-27 16:16 UTC, NonQueueingMatt requested changes

2023-03-27 16:16 UTC, NonQueueingMatt commented on code/_onclick/hud/screen_objects.dm
> +				to_chat(C, "You cannot wield and lie down!")
```suggestion
				to_chat(C, SPAN_WARNING("You cannot wield and lie down!"))
```

2023-04-17 04:35 UTC, FlamingLily commented
> would probably be better to just make this innate of regular resting.

Agreed, but that being said, still add a hud icon

2023-04-30 01:36 UTC, feartheblackout commented
Just an oversight, but this is presently unusable by Dionae because they don't have the walk/run icon.

2023-04-30 14:14 UTC, FluffyGhoster commented
> Just an oversight, but this is presently unusable by Dionae because they don't have the walk/run icon.

Last commit should fix that, gave the hud icon back and it's prevented from running in the FSM

2023-05-13 01:45 UTC, listerla commented
Minor thing; due to people being oriented based on direction, blankets will often cover people's heads when they're buckled to a bed.

2023-05-13 03:30 UTC, FluffyGhoster commented
> Minor thing; due to people being oriented based on direction, blankets will often cover people's heads when they're buckled to a bed.

Fixed in commit [a7df806](https://github.com/Aurorastation/Aurora.3/pull/15952/commits/a7df8065924ef994243facdd00ccb77c4be470c0)

2023-05-20 15:27 UTC, NonQueueingMatt approved these changes

2023-09-03 12:50 UTC, Arrow768 approved these changes

2023-09-03 14:14 UTC, merged