Removes Non-Fed Citizenships for Skrell Federation Origin Selection
Aurorastation/Aurora.3 pull request #15970
Opened 2023-03-07 20:03 UTC by RyverStyx

2023-03-07 20:06 UTC, RyverStyx commented
!review

2023-03-07 20:18 UTC, Generalcamo requested changes

2023-03-07 20:18 UTC, Generalcamo commented on html/changelogs/fedcit.yml
> +  - tweak: "Removes Non-Fed citizenship options from Federation Origins."
```suggestion
  - rscdel: "Removes Non-Fed citizenship options from Federation Origins."
```

2023-03-08 00:08 UTC, Alberyk approved these changes

2023-03-11 11:45 UTC, merged