Minor Antagonist Tweaks
Aurorastation/Aurora.3 pull request #15993
Opened 2023-03-09 05:04 UTC by TheDanseMacabre

Minor antagonist tweaks to changeling (minor)

2023-03-09 05:07 UTC, TheDanseMacabre commented
!wip

2023-03-11 03:48 UTC, TheDanseMacabre commented
!review

2023-03-11 03:50 UTC, Alberyk approved these changes

2023-03-11 11:21 UTC, Arrow768 approved these changes
I guess we’ll see how that goes

2023-03-12 05:21 UTC, SleepyGemmy requested changes
changelog required.

2023-03-12 11:02 UTC, Arrow768 commented
> changelog required.

Good catch

2023-03-12 21:40 UTC, SleepyGemmy commented on html/changelogs/dansemacabre-horrorform.yml
> +  - balance: "Changeling horror form has been improved."
```suggestion
  - balance: "Changeling horror form has been tweaked. It is now irreversible. Chem cost increased from 40 to 50. Health increased from 750 to 1250. Damage increased from 30 to 45. 30 AP added to attacks. Minimum oxygen changed from 0 to 5."
```

2023-03-12 21:44 UTC, SleepyGemmy requested changes

2023-03-12 21:44 UTC, SleepyGemmy commented on html/changelogs/dansemacabre-horrorform.yml
> +  - balance: "Changeling horror form has been improved."
```suggestion
  - balance: "Changeling horror form has been tweaked. It is now irreversible. Genome cost decreased from 15 to 10. Chem cost increased from 40 to 50. Health increased from 750 to 1250. Damage increased from 30 to 45. 30 AP added to its melee attacks. Minimum oxygen required changed from 0 to 5."
```

2023-03-12 22:03 UTC, SleepyGemmy approved these changes

2023-03-19 11:52 UTC, merged