Fix a bunch of hostile mob problems
Aurorastation/Aurora.3 pull request #15994
Opened 2023-03-09 12:48 UTC by JohnWildkins

I'm a good coder I swear

  - bugfix: "Fixed hostile mobs aggroing on players they couldn't see, i.e. through walls and across z-levels."
  - bugfix: "Fixed hostile mobs sometimes not attacking full window frames."
  - bugfix: "Fixed hostile mobs ignoring their attack cooldown and attacking structures/objects incredibly quickly."
  - bugfix: "Fixed retaliate mobs (e.g. goats) starting hostile by default."

2023-03-09 12:48 UTC, JohnWildkins commented
!bugfix

2023-03-09 12:48 UTC, JohnWildkins commented
!review

2023-03-09 13:37 UTC, Alberyk approved these changes

2023-03-09 13:47 UTC, mikomyazaki requested changes

2023-03-09 13:47 UTC, mikomyazaki commented on code/modules/mob/living/simple_animal/hostile/hostile.dm
> +			for(var/obj/structure/S in get_step(src, dir))
If we are immediately istyping for some very specific types below, we don't need to typecheck here aswell.

2023-03-10 02:30 UTC, mikomyazaki approved these changes

2023-03-10 14:02 UTC, merged