Additional Service QOL fixes
Aurorastation/Aurora.3 pull request #16023
Opened 2023-03-13 01:39 UTC by Hunttark

Further QOL fixes per https://forums.aurorastation.org/topic/18084-feedback-thread-for-service-remap/page/3/#comment-163651 and the Aurora code_dungeon discord.

- Added a piano to the bar lounge stage
- Brought the dinnerware vendor to the main bar area
- Added meat to the kitchen
- Resolved chickens not spawning (was using placeholder not simplemob)
- Moved the bar requests console
- The bar backroom currently has one airlock that goes to the main bar area instead of two due to area constraints.

2023-03-13 05:38 UTC, alsoandanswer approved these changes

2023-03-13 15:27 UTC, SleepyGemmy requested changes
the meat freezer already spawns 8 meat slabs. more can be ordered from cargo or obtained from slaughtering the cow.

2023-03-13 15:28 UTC, SleepyGemmy commented
preferably, the piano would remain something orderable by cargo so that cargo at least have some niché.

2023-03-14 20:34 UTC, SleepyGemmy approved these changes

2023-03-14 20:39 UTC, SleepyGemmy commented
!review

2023-03-14 21:45 UTC, merged