Bridge Re-mapped
Aurorastation/Aurora.3 pull request #16055
Opened 2023-03-18 23:32 UTC by AuroraBirdie

Moved the weapons console forward
Moved Sensors and Thrust Consoles to a side bay.
More table space (for that office feel)
Added a Captain's workstation where the pillar use to be Moved cameras to side pillars
Intercomms given to each workstation
Medical/Security consoles moved to back left
Message monitoring and alerts moved by doors leading onto bridge
![image](https://user-images.githubusercontent.com/128264105/226145362-57a69ba6-14ec-43a8-88ff-a5b383def895.png)
!review required

2023-03-18 23:43 UTC, AuroraBirdie commented
![image](https://user-images.githubusercontent.com/128264105/226145708-1324fe38-d457-4370-9882-14305a9dba28.png)
Forgot about the two plants I put by the walls

2023-03-19 00:51 UTC, Greenjoe12345 commented
Not all that keen on the main control consoles being separated

2023-03-19 01:31 UTC, AuroraBirdie commented
[AuroraBirdie-Bridge-Remap](https://github.com/AuroraBirdie/Aurora.3/tree/AuroraBirdie-Bridge-Remap)

Took feedback from [This post](https://forums.aurorastation.org/topic/18142-bridge-helm-re-map/?do=findComment&comment=163925) removed tables, moved shredder, put medical, cam, and alert console together. Put Messaging console by itself. Added table to Gunner station, moved sensor console over.

2023-03-19 01:53 UTC, Eyeveri commented
> Not all that keen on the main control consoles being separated

I agree with this. Secondary consoles would be fine but, I do not like that the Sensors, Engine control and nav console is all separate.

2023-03-19 09:22 UTC, FluffyGhoster commented
> Not all that keen on the main control consoles being separated


> > Not all that keen on the main control consoles being separated
> 
> I agree with this. Secondary consoles would be fine but, I do not like that the Sensors, Engine control and nav console is all separate.

Feedback thread is in https://forums.aurorastation.org/topic/18142-bridge-helm-re-map/
Please remember that Github is only about the code (or the map, in this case) itself

2023-03-19 15:34 UTC, AuroraBirdie commented
Helm/Sensors/Thrusters moved all back together. See below and changelog.
![image](https://user-images.githubusercontent.com/128264105/226186856-4e4a70df-d6f7-4abe-8af2-aab940f2b849.png)

2023-03-19 16:12 UTC, AuroraBirdie commented
![image](https://user-images.githubusercontent.com/128264105/226189101-4d2c93fe-5740-4d76-aeff-3a5205db89a7.png)
Fixed 'ssssss' ref. var. issue, moved things for 'flavor' which does not change the changelog

2023-03-20 20:28 UTC, AuroraBirdie commented
![image](https://user-images.githubusercontent.com/128264105/226458339-9ff0ab47-af5d-4f0a-9e49-c24cd8efc8da.png)
Consoles couldn't be rotated, no sprites to change with. Removed Intercom in bottom picture.

![image](https://user-images.githubusercontent.com/128264105/226458462-b2af5993-8007-4159-a1cf-1ffdb14880d4.png)
https://discord.com/channels/157516682288562176/302201161044328450/1087442344657305660

2023-03-21 00:37 UTC, AuroraBirdie commented
![image](https://user-images.githubusercontent.com/128264105/226494221-0a7c6402-e5ce-4746-bce7-3ea4958400b8.png)
Alright last time I plan to touch it for a while. Will gather some feedback for it and hopefully it makes it's way onto the horizon.

2023-03-21 00:37 UTC, AuroraBirdie commented
!review required

2023-03-24 19:33 UTC, AuroraBirdie commented
Map keeps breaking. I can't fix it. Read can't seem to fix it, this is so wild, honestly. So moving my thing to a suggestion instead :/ I don't know how to fix this, even when redoing it by hand with the most recent map.

2023-03-25 21:03 UTC, SleepyGemmy requested changes

2023-03-25 21:03 UTC, SleepyGemmy commented on html/changelogs/AuroraBirdie-PR-#16055.yml
> +  - maptweak: "added naviation console to the Captain's seat- made it more symmerical"
```suggestion
  - maptweak: "Remapped the bridge."
```
no. please shorten this changelog to a single entry.

2023-03-28 13:54 UTC, SleepyGemmy requested changes
PR is reverting some map changes, specifically on the hull. refer to the [mapdiff](https://github.com/Aurorastation/Aurora.3/pull/16055/checks?check_run_id=12276918104).

2023-03-28 18:14 UTC, AuroraBirdie commented
![image](https://user-images.githubusercontent.com/128264105/228330203-4e3474b5-1236-457e-a98d-c2ddb414bf27.png)
Fixed the hull back as that was never the point of this PR. Moved conference console back. Should be all good now, right?

2023-03-28 20:44 UTC, SleepyGemmy approved these changes

2023-03-29 19:00 UTC, merged