[WIP] Adds a flavour only height system
Aurorastation/Aurora.3 pull request #16067
Opened 2023-03-21 13:48 UTC by FlamingLily

Adds a new height field to the character creator, for height in CM. Adds flavour text to describe height differences between the examinee and examinor. Height values are restricted to limits, lore input will almost certainly be needed to verify that the inputs are correct and not too restrictive/freeing.

What this PR does NOT do:

- Sprite size changes.
- Mechanical benefits (Speed, health, whatever) to height.

ToDo:
- [X] Establish Height Framework and flavour text on examine
- [X] Establish height values in preferences and allow change on customisation
- [ ] Fix the grammar of the flavour text when I'm not overtired
- [ ] Ensure changelings mimic their target's height when changing their form
- [ ] Ensure antagonist character customiser can alter height values
- [ ] Get Lore approval of height restrictions

2023-03-25 05:38 UTC, Sniblet commented
kornelija rigo is now officially too small to exist

2023-03-30 07:25 UTC, FlamingLily commented
!review

2023-03-30 08:08 UTC, WhatsUpBrotendo commented
Skrell height restrictions are fine.

2023-03-30 11:32 UTC, Eyeveri commented
Is there any way you could add a alternate Ft/Inch measurement?

2023-04-03 02:24 UTC, FlamingLily commented on code/modules/mob/living/carbon/human/species/station/vaurca/vaurca_subspecies.dm
> +	height_max = 320
```suggestion
	height_max = 335
```
bigger...

2023-04-03 02:40 UTC, FlamingLily reviewed
Human heights via Schwann

2023-04-03 02:40 UTC, FlamingLily commented on code/modules/mob/living/carbon/human/species/station/human/human.dm
> +	height_max = 210
```suggestion
	height_min = 140
	height_max = 203 //6'8", ugly number.
```

2023-04-03 02:40 UTC, FlamingLily commented on code/modules/mob/living/carbon/human/species/station/human/human_subspecies.dm
> +	height_min = 150
```suggestion
	height_min = 180
```

2023-04-03 02:40 UTC, FlamingLily commented on code/modules/mob/living/carbon/human/species/station/ipc/ipc_subspecies.dm
> +	height_min = 120
```suggestion
	height_min = 140
```

2023-04-03 04:47 UTC, FlamingLily reviewed
Wasn't happy with how distant the "about the same" height thing was so I narrowed it.

2023-04-03 04:47 UTC, FlamingLily commented on code/modules/mob/mob.dm
> +				if(21 to 50)
```suggestion
				if(-49 to -11)
					descriptor = "small"
				if(-10 to 10)
					descriptor = "about average height"
				if(11 to 50)
```

2023-04-03 04:47 UTC, FlamingLily commented on code/modules/mob/mob.dm
> +		if(21 to 50)
```suggestion
		if(-49 to -11)
			descriptor = "shorter than"
		if(-10 to 10)
			descriptor = "around about the same height"
		if(11 to 50)
```

2023-04-03 09:26 UTC, FlamingLily commented on code/modules/mob/living/carbon/human/species/station/unathi/unathi.dm
> +	height_max = 220
```suggestion
	height_min = 175
	height_max = 215
```

2023-04-03 09:26 UTC, FlamingLily commented
All heights confirmed by respective lore teams

2023-04-03 10:41 UTC, NonQueueingMatt requested changes

2023-04-03 10:41 UTC, NonQueueingMatt commented on code/game/atoms.dm
> +			to_chat(user, SPAN_NOTICE(M.assembleHeightString(user)))
`istype(src, ...)` checks should be avoided. In this case, ismob(src).

2023-04-03 10:41 UTC, NonQueueingMatt commented on code/modules/mob/mob.dm
> +	if(ishuman(src))
As above, avoid `istype(src, ...) checks. This part can easily be a different proc that is overridden on different subtypes of /mob/.

2023-04-03 10:47 UTC, FlamingLily commented on code/modules/mob/living/carbon/human/species/station/human/human.dm
> +	height_min = 140
```suggestion
	height_min = 145
```

2023-04-03 11:01 UTC, NonQueueingMatt commented on code/modules/mob/living/carbon/human/species/station/ipc/ipc_subspecies.dm
> +	height_max = 230 // If for whatever reason you wanted a shell that was ~~pretending to be geneboosted~~ SCHLOSSER
```suggestion
	height_max = 230
```
No references to characters in the code, please.

2023-04-08 12:39 UTC, Arrow768 requested changes

2023-04-08 12:39 UTC, Arrow768 commented on SQL/migrate/V078__char_heights.sql
> +ALTER TABLE `ss13_characters` ADD COLUMN `char_height` INT(3) NOT NULL DEFAULT 0 AFTER `species`
We are in the ss13_characters table, so the prefix char_ is superfluous.

2023-04-08 12:39 UTC, Arrow768 commented on code/modules/client/preferences.dm
> +	var/char_height						//character's height
Same here.
We are already in the char preferences.

2023-04-15 20:27 UTC, Arrow768 approved these changes

2023-04-15 20:53 UTC, NonQueueingMatt approved these changes

2023-05-01 17:23 UTC, merged