Adds some new EUM-centric things
Aurorastation/Aurora.3 pull request #16076
Opened 2023-03-22 07:32 UTC by Yonnimer

Adds origins, accents, religions, clothing, and a consular role for Dionae revolving around EUM

Also adds some options for Skrell from EUM

WIP, do not merge for the time being, still haven't added the clothing.

2023-03-22 07:32 UTC, Yonnimer commented
!wip

2023-04-01 04:50 UTC, Yonnimer commented
!wip

2023-04-01 04:51 UTC, Yonnimer commented
!review

2023-04-01 04:52 UTC, Yonnimer commented
Went through and tested everything, looks to be working fine

2023-04-07 23:43 UTC, Alberyk requested changes

2023-04-07 23:43 UTC, Alberyk commented on code/modules/background/origins/origins/diona/eum.dm
> +	desc = "Playing host to the vast majority of the planet’s non-dionae population, Nral’Daaq is a city-state under the CT-EUM that is known for being the planet’s hub of off-world trading, as well as
```suggestion
	desc = "Playing host to the vast majority of the planet's non-dionae population, Nral'Daaq is a city-state under the CT-EUM that is known for being the planet's hub of off-world trading, as well as for its quite diverse majority-skrell population, with both Pro-Federation and Anti-Federation Skrell calling the city home. Due to the city's border with the sea, Nral'Daaq is also a quite popular trading spot for the Ekane, with the vast majority of their goods ending up in the city to be later resold off-world. "
```

2023-04-07 23:43 UTC, Alberyk commented on code/modules/background/origins/origins/diona/eum.dm
> +	desc = "Widely considered the capital of the CT-EUM, the city-state of United is the newest independent nation, formed alongside the formation of the CT-EUM, to act as a neutral meeting place for th
```suggestion
	desc = "Widely considered the capital of the CT-EUM, the city-state of United is the newest independent nation, formed alongside the formation of the CT-EUM, to act as a neutral meeting place for the Council of Delegates, and to represent the central governing body, as well as acting as a mediator between the two other city-states should a conflict arise. United is the second most-visited city on EUM after Nral'Daaq, and has influence from both off-world and the other city-states in its structure, and operation."
```

2023-04-08 23:40 UTC, Alberyk approved these changes

2023-04-09 10:33 UTC, NonQueueingMatt approved these changes

2023-04-09 11:31 UTC, merged