Cyclops Mining Vessel
Aurorastation/Aurora.3 pull request #16071
Opened 2023-03-21 18:59 UTC by Eyeveri

This creates a specific vessel for Hephaestus Industries. This is one of several that will be PR'd. Do not merge until the lore team says to.

2023-03-21 18:59 UTC, Eyeveri commented
!wip

2023-03-21 18:59 UTC, Eyeveri commented
!do not merge

2023-04-13 03:14 UTC, Eyeveri commented
Reopening with a different PR. I did a lot that broke a lot and i honestly am not sure what it all was. So, to avoid that I am just taking the four main files and the uniform code, then making a new branch to add.

2023-05-15 04:25 UTC, RustingWithYou requested changes

2023-05-15 04:25 UTC, RustingWithYou commented on code/modules/clothing/under/jobs/security.dm
> +    icon = 'icons/clothing/under/uniforms/heph.dmi'
```suggestion
    icon = 'icons/clothing/under/uniforms/heph_security.dmi'
```
should fix the unit test failure

2023-05-15 04:25 UTC, RustingWithYou commented on code/modules/clothing/under/jobs/civilian.dm
> +    contained_sprite = TRUE
```suggestion
```
already defined in security.dm

2023-07-16 03:29 UTC, closed without merging