Turf wars
Aurorastation/Aurora.3 pull request #16104
Opened 2023-03-26 07:06 UTC by alsoandanswer

Majority of sprites by Atteria.

Mainly ports over Bay's tile smoothing and updates our old code. Funnily enough, both coded by Lohikar.
changes:
  - imageadd: "Adds new sprites for turfs, by Atteria."
  - bugfix: "Fixes paint colors being ultra desaturated when painted on tiles."
  - rscadd: "You can now paint linoleum, freezer tiles, reinforced tiles and wooden tiles."
  - rscadd: "Tile paint decals are now modularised, meaning they adapt to the tile they are on."
  - rscadd: "Adds decal blending modes, allowing decals to adapt to the type of tile they're painted on."
  - rscadd: "Ports Bay/Eris carpet/grass smoothing and edges."
  - rscdel: "Removes depreciated tiles. Maps have been tweaked to reflect this."
  - rscadd: "Updates character preview background to match the new tiles."

Disclaimer for reviewers : Large number of lines are mostly search and replace in maps and removal of hardcoded tiles, which shouldn't be there anyway.

Gallery :
<img width="218" alt="dreamseeker_j0AcRNgmEY" src="https://user-images.githubusercontent.com/42310821/227760765-c2ab899f-734e-4e11-8816-dbde40ec7520.png">
<img width="387" alt="dreamseeker_IJX3YR6ou3" src="https://user-images.githubusercontent.com/4231082
<img width="171" alt="dreamseeker_51Znq2bVv4" src="https://user-images.githubusercontent.com/4231082
<img width="533" alt="dreamseeker_txb24MaSdL" src="https://user-images.githubusercontent.com/42310821/227760766-166c752c-d399-4429-9169-883a946b9ce2.png">
1/227760751-2d5e4ab6-c0c0-47db-bd2f-d83efef6d71d.png">
1/227760746-1e671ff5-7880-48a0-94f7-427bb3ef9c3d.png">
<img width="321" alt="dreamseeker_Y9b36nUFTS" src="https://user-images.githubusercontent.com/4231082
<img width="301" alt="dreamseeker_FJiKCLvtIY" src="https://user-images.githubusercontent.com/42310821/227760750-ce3dadbf-83c6-40bd-a34c-71b941f31814.png">
1/227760748-05a1a217-e2fb-4166-b3b9-3dd488acbb9e.png">

2023-03-26 07:09 UTC, alsoandanswer commented
!wip

2023-03-26 12:03 UTC, alsoandanswer commented
!review

2023-03-26 17:27 UTC, Greenjoe12345 commented
Would this allow for the different types of wood flooring Bay has? (Different types of wooden planks)

2023-03-26 19:04 UTC, alsoandanswer commented
> Would this allow for the different types of wood flooring Bay has? (Different types of wooden planks)

I think we already have them. They're just not implemented properly, nor mapped in.

2023-03-26 20:20 UTC, Generalcamo requested changes

2023-03-26 20:20 UTC, Generalcamo commented on code/game/objects/items/devices/floor_painter.dm
> +		to_chat(user, "<span class='warning'>\The [src] cannot paint this type of flooring.</span>")
```suggestion
		to_chat(user, SPAN_WARNING("\The [src] cannot paint this type of flooring."))
```

2023-03-26 20:20 UTC, Generalcamo commented on code/game/objects/items/devices/floor_painter.dm
> +		to_chat(user, "<span class='warning'>\The [src] cannot paint damaged or missing tiles.</span>")
```suggestion
		to_chat(user, SPAN_WARNING("\The [src] cannot paint damaged or missing tiles."))
```

2023-03-26 20:20 UTC, Generalcamo commented on code/game/objects/structures/lattice.dm
> +			to_chat(user, SPAN_NOTICE("You slice apart the [src] leaving nothing useful behind."))
```suggestion
			user.visible_message(
				SPAN_NOTICE("\The user slices apart \the [src], leaving nothing useful behind."),
				SPAN_NOTICE("You slice apart \the [src], leaving nothing useful behind."),
				SPAN_NOTICE("You hear the sound of a welder, slicing apart metal.")
			)
```

2023-04-04 22:49 UTC, remona-minett commented
Personally I'm not a fan of the way the floor tiles look, they are a little visually busy. I wonder if a poll on before and after on some of the larger changes would be good.

2023-04-04 23:05 UTC, alsoandanswer commented
https://forums.aurorastation.org/topic/18188-project-exorcism-episode-1-turf-wars-feedback-thread/

2023-06-17 20:25 UTC, NonQueueingMatt commented
merged into other PR

2023-06-17 20:25 UTC, closed without merging