Asymmetrical shirt tweaks
Aurorastation/Aurora.3 pull request #16157
Opened 2023-04-03 04:40 UTC by TheDanseMacabre

Just some edits to improve shading and overall look.

2023-04-03 05:23 UTC, TheDanseMacabre commented
!review

2023-04-03 06:23 UTC, FluffyGhoster approved these changes

2023-04-04 08:05 UTC, niennab requested changes
Pushing the outline as well as over shading the top most portion has given the sprite pillow shading.

![crossedtop](https://user-images.githubusercontent.com/56227386/229728235-8da0a8d6-e37c-4a5c-840a-6b542e0db72e.png)

2023-04-07 02:15 UTC, alsoandanswer approved these changes

2023-04-07 06:20 UTC, niennab approved these changes
Great changes, thanks!

2023-04-09 10:26 UTC, NonQueueingMatt approved these changes

2023-04-09 11:15 UTC, merged