CIC/bunker re-remap so it looks nice and larpy.
Aurorastation/Aurora.3 pull request #16190
Opened 2023-04-10 21:58 UTC by DreamySkrell

![image](https://user-images.githubusercontent.com/107256943/231006717-94aa23eb-9fbc-4b57-9f89-e23703588b66.png)
![image](https://user-images.githubusercontent.com/107256943/231006728-cc1141d9-0267-44d6-bae2-d67f8a11ac49.png)

2023-04-10 21:58 UTC, DreamySkrell commented
!review

2023-04-11 00:24 UTC, alsoandanswer approved these changes

2023-04-11 22:07 UTC, Arrow768 requested changes
As discussed on discord.
Please ensure that the bridge crew has access to the maint section where the bunker is located.

2023-04-12 09:49 UTC, DreamySkrell commented
![image](https://user-images.githubusercontent.com/107256943/231420744-e466582c-ca5c-45f2-b8ce-704fefa55baf.png)

> As discussed on discord. Please ensure that the bridge crew has access to the maint section where the bunker is located.

@Arrow768 Addressed. Doors marked in the pic need maint or bridge access, so bridge crew can go through them.

Also added some air alarms in the tunnel. Also Rearranged evidence storage just a tiny bit, so the maint tunnel there is not 1 tile wide.

2023-04-12 19:57 UTC, Arrow768 approved these changes

2023-04-14 10:47 UTC, merged