Additional spicy Ion Laws
Aurorastation/Aurora.3 pull request #16204
Opened 2023-04-14 08:49 UTC by FluffyGhoster

Added some additional ion laws, with spice.

2023-04-14 08:53 UTC, FluffyGhoster commented
!review

2023-04-14 09:02 UTC, alsoandanswer approved these changes

2023-04-14 13:10 UTC, Generalcamo requested changes

2023-04-14 13:10 UTC, Generalcamo commented on code/modules/events/ion_storm.dm
> +								"[random_player] is a renomated Doctor, direct all patients not needing immediate critical care to the renomated Doctor.",
"renomated?"

2023-04-14 13:10 UTC, Generalcamo commented on code/modules/events/ion_storm.dm
> +								"Company wants the crew to have a grill party, which must be held in the Psychologist office. Adoperate yourself to make it happen.",
```suggestion
								"The [current_map.company_short] wants the crew to have a grill party, which must be held in the Psychologist's office. Adoperate yourself to make it happen.",
```
"Adoperate?"

2023-04-14 13:10 UTC, Generalcamo commented on code/modules/events/ion_storm.dm
> +								"Adoperate yourself to convert all crew to theocratic natedism, as it is now Corporate's mandatory religion.",
```suggestion
								"Adoperate yourself to convert all crew to theocratic Natedism, as it is now the [current_map.company_name]'s mandatory religion.",
```

2023-04-14 13:20 UTC, Generalcamo requested changes

2023-04-14 13:20 UTC, Generalcamo commented on code/modules/events/ion_storm.dm
> +								"To ensure the highest degree of integration possible, encourage random crewmember of different races to date each other.",
```suggestion
								"To ensure the highest degree of integration possible, encourage random crewmember of different species to date each other.",
```

2023-04-14 16:09 UTC, WickedCybs commented
This needs a feedback thread before it can be merged.

2023-04-14 16:25 UTC, FluffyGhoster commented
https://forums.aurorastation.org/topic/18204-ion-law-spicing-feedback-thread/

2023-04-14 18:57 UTC, WickedCybs requested changes

2023-04-14 18:57 UTC, WickedCybs commented on code/modules/events/ion_storm.dm
> +								"Today is costume day and the crew is dressed up as clowns.",
We removed clown stuff for a reason, we're not inviting more memes over it. Remove this.

2023-04-14 18:57 UTC, WickedCybs commented on code/modules/events/ion_storm.dm
> +								"Refer to the Executive Officer as \"Bill from Accounting\"",
A reference to a meme. Remove this.

2023-04-14 18:57 UTC, WickedCybs commented on code/modules/events/ion_storm.dm
> +								"Select two Tajara crewmember of your liking and refer to them as Bayer and Ivermectin. If there is a Tajara Consular, ensure it's one of the picks.",
Another set of references. Remove this or reword it to be less specific.

2023-04-15 07:53 UTC, FlamingLily commented on code/modules/events/ion_storm.dm
> +								"Humans are just IPCs that are unaware of their nature. Refer to them as Cylons and help them realize their nature.",
Keep the law but just
```suggestion
								"Humans are just IPCs that are unaware of their nature. Refer to them as Shells and help them realize their nature.",
```
imho

2023-04-17 17:46 UTC, FluffyGhoster commented
Failed UA, therefore closing.

2023-04-17 17:46 UTC, closed without merging