Srom even nicer and even prettier
Aurorastation/Aurora.3 pull request #16226
Opened 2023-04-17 15:17 UTC by DreamySkrell

![image](https://user-images.githubusercontent.com/107256943/232531242-ab91af2d-31ee-4e2e-9991-f11ccfd413a5.png)
![image](https://user-images.githubusercontent.com/107256943/232531397-4e73a17d-c214-43e5-b54f-2bedce85cbfd.png)
![image](https://user-images.githubusercontent.com/107256943/232531479-1a405c9f-7d96-4aeb-892b-9817206ffa6f.png)
![image](https://user-images.githubusercontent.com/107256943/232531579-6fd53eaa-32e8-4004-8eca-aa4b34c9f38a.png)
![image](https://user-images.githubusercontent.com/107256943/232531700-c91447ca-878d-442b-82c6-b3130d4cdbfa.png)

Mostly just lights with less power/range.

2023-04-17 15:39 UTC, DreamySkrell commented
!review

2023-04-17 17:47 UTC, atteria requested changes
The exoplanet snow here was added before I added automatic smoothing to it, so it overlaps with the edge decals that preceded that. You should probably either delete the edge decals or swap the exoplanet snow with the holodeck snow.

2023-04-29 09:17 UTC, NonQueueingMatt approved these changes

2023-05-07 10:49 UTC, DreamySkrell commented
> The exoplanet snow here was added before I added automatic smoothing to it, so it overlaps with the edge decals that preceded that. You should probably either delete the edge decals or swap the exoplanet snow with the holodeck snow.

Deleted the edge decals.

2023-05-07 22:19 UTC, Alberyk approved these changes

2023-05-08 12:36 UTC, merged