Dionae Ship Improvements
Aurorastation/Aurora.3 pull request #16240
Opened 2023-04-20 05:16 UTC by Yonnimer

Changes the layout of both ships slightly to make them less of a pain for slowbois to get around, as well as adds netguns to both ships.

Also fixes both ship icons being invisible

2023-04-20 05:23 UTC, Yonnimer commented
!review

2023-04-29 09:18 UTC, NonQueueingMatt approved these changes

2023-05-20 18:56 UTC, Yonnimer commented
As far as i'm aware, the conflict is something to do with the checker, not something wrong with the pr itself, so it should still be fine to review/merge

2023-05-30 09:33 UTC, alsoandanswer approved these changes

2023-06-10 12:36 UTC, Arrow768 requested changes

2023-06-10 12:36 UTC, Arrow768 commented on maps/away/ships/dionae/diona_serz_ship/diona_serz_ship_ghostroles.dm
> -	max_count = 2
Undocumented change

2023-06-10 12:36 UTC, Arrow768 commented on maps/away/ships/dionae/diona_rokz_ship/diona_rokz_ship_ghostroles.dm
> -	max_count = 2
undocumented change

2023-06-11 15:36 UTC, Yonnimer commented on maps/away/ships/dionae/diona_serz_ship/diona_serz_ship_ghostroles.dm
> -	max_count = 2
Changelog has been updated

2023-06-11 15:36 UTC, Yonnimer commented on maps/away/ships/dionae/diona_rokz_ship/diona_rokz_ship_ghostroles.dm
> -	max_count = 2
Changelog has been updated

2023-06-17 21:28 UTC, merged