Clickable Storage Backgrounds
Aurorastation/Aurora.3 pull request #16249
Opened 2023-04-22 12:38 UTC by Geevies

* You can now click on the background of an item inside a box/backpack to pick it up. This only affects storages that don't use the square slots for now.

https://user-images.githubusercontent.com/22774890/233785108-65314af5-5fb4-4268-b1ab-d000c4a8a262.mp4

2023-04-22 12:38 UTC, Geevies commented
!review

2023-04-22 15:14 UTC, alsoandanswer approved these changes
oh my god finally

maybe that weird thin one pixel line is fixed maybe? just me? my dad?

2023-04-22 15:28 UTC, RyverStyx approved these changes

2023-04-25 13:48 UTC, NonQueueingMatt requested changes

2023-04-25 13:48 UTC, NonQueueingMatt commented on code/_onclick/hud/screen_objects.dm
> +		return TRUE
incapacitated() should do the trick here

2023-04-30 21:56 UTC, merged