Weeping Stars
Aurorastation/Aurora.3 pull request #16247
Opened 2023-04-22 05:39 UTC by Caelphon

Added the region weeping stars. Needs a stargazer, and skybox.

2023-04-22 05:39 UTC, Caelphon commented
!review

2023-04-23 19:16 UTC, TheDanseMacabre commented
The FSF shouldn't be active in this sector, if you ask me

2023-04-29 09:19 UTC, NonQueueingMatt requested changes

2023-04-29 09:19 UTC, NonQueueingMatt commented on maps/away/ships/sol_merc/fsf_patrol_ship.dm
> +	sectors = list(SECTOR_TAU_CETI, SECTOR_ROMANOVICH, SECTOR_CORP_ZONE, SECTOR_VALLEY_HALE, SECTOR_WEEPING_STARS)
```suggestion
	sectors = list(SECTOR_TAU_CETI, SECTOR_ROMANOVICH, SECTOR_CORP_ZONE, SECTOR_VALLEY_HALE)
```

2023-05-27 01:44 UTC, Alberyk commented
Added in another pr.

2023-05-27 01:44 UTC, closed without merging