Fixes #16245 - Returns stabilizer harnesses to their former glory
Aurorastation/Aurora.3 pull request #16257
Opened 2023-04-25 20:40 UTC by sheeplets

Replaces the 100w device cells with standard 1000w's.

2023-04-25 20:40 UTC, sheeplets commented
!bugfix

2023-04-25 20:42 UTC, Generalcamo commented
Can confirm the bugfix. This was not intentional, and the description of the device cell (both old and new) did not lend itself to this usage.

2023-04-25 20:42 UTC, Generalcamo requested changes

2023-04-25 20:42 UTC, Generalcamo commented on code/game/objects/items/devices/auto_cpr.dm
> +	battery = new /obj/item/cell/(src)
```suggestion
	battery = new /obj/item/cell(src)
```

2023-04-25 20:43 UTC, sheeplets commented on code/game/objects/items/devices/auto_cpr.dm
> +	battery = new /obj/item/cell/(src)
![businessmen-handshake-handshake](https://user-images.githubusercontent.com/44004468/234399111-c2a21be3-34f1-443f-a7fb-698319ac3b1c.gif)

2023-04-26 14:50 UTC, Alberyk approved these changes

2023-04-27 03:44 UTC, merged