The Pumped Up Kicks Update
Aurorastation/Aurora.3 pull request #16265
Opened 2023-04-28 19:01 UTC by alsoandanswer

Shoes. New shoes. Look at them. Ported (mostly) from /tg/. With some modifications by yours truly.

2023-04-28 19:09 UTC, alsoandanswer commented
!review

2023-04-29 12:24 UTC, Alberyk approved these changes

2023-04-29 13:23 UTC, alsoandanswer commented on code/modules/client/preference_setup/loadout/loadout_shoes.dm
> +	shoes["jackboots, cavalry"] = /obj/item/clothing/shoes/jackboots/thigh
```suggestion
	shoes["jackboots, cavalry"] = /obj/item/clothing/shoes/jackboots/cavalry
```

2023-04-30 01:05 UTC, Generalcamo requested changes

2023-04-30 01:05 UTC, Generalcamo commented on code/modules/clothing/shoes/oxfords.dm
> +	name = "steel-toed  shoes"
```suggestion
	name = "steel-toed oxford shoes"
```
Weird space in the middle

2023-09-06 12:12 UTC, alsoandanswer commented
!review

2023-09-07 20:57 UTC, NonQueueingMatt approved these changes

2023-09-08 17:35 UTC, Geevies commented
Feedback thread please.

Many toeless boots aren't actually toeless.

Will put this in feedback thread also (as an opinion), but don't remove the short/knee/thigh boots. I quite like them. The shorter jackboots look like puddlestompers.

2023-09-08 17:51 UTC, NonQueueingMatt commented
Cavalry boots are invisible

2023-09-08 23:41 UTC, alsoandanswer commented
> Feedback thread please.
> 
> Many toeless boots aren't actually toeless.
> 
> Will put this in feedback thread also (as an opinion), but don't remove the short/knee/thigh boots. I quite like them. The shorter jackboots look like puddlestompers.

I'm only removing the thighboots, because they're the most egregious of the three, and is unused by most people -
I've asked around, and people only typically use the kneeboots instead.

> Cavalry boots are invisible

Fixed.

2023-09-09 08:08 UTC, Geevies commented
> 
> I'm only removing the thighboots, because they're the most egregious of the three, and is unused by most people - I've asked around, and people only typically use the kneeboots instead.
> 

I'd love to tackle this on the forum instead of on github, but since there doesn't appear to be a thread going up, I'll do it here.

Asked around where, and who's "people"? Egregious how? I use it. I like it.

I'm fairly sure unused by most people isn't a valid excuse for removal, otherwise we'd be clearing out 99% of the loadout, such as the aurora miniature. At the very least the toeless variants don't seem to be resprited at all, as picture below, so there's no real reason to remove them other than... opinion, I guess.

(yes i know the fit is shit i just wanted a quick comparison of sprites on an unathi)
![image](https://github.com/Aurorastation/Aurora.3/assets/22774890/c079e8ff-eb94-45ec-a686-922cc338a571)

2023-09-09 15:17 UTC, Geevies commented
Thank you! I appreciate getting the riding boots added.

One thing I noticed while playing- if I lie down my boots seem to get a different rotation applied to them, causing them to float off into the aether. I'm just not sure if it's related to this testmerge or something else alongside this one.

2023-09-13 13:53 UTC, merged