Grab Stuff
Aurorastation/Aurora.3 pull request #16337
Opened 2023-05-13 16:36 UTC by Geevies

* Tweaked movement code's interaction with grabs. You can no longer walk out of grabs.
* It's more difficult to break out of aggressive grabs now (base 50% reduced to 30%).
* You can now only break out of one grab at a time, and resisting a grab will now add a 0.5 second movement delay.
* When you have someone grabbed, clicking on a tile will now move them there.
* You can now pass through people that are pulling or grabbing you.
* You will now instantly cover someone's eyes or mouth upon going to an aggressive grab, or changing your selected attack zone.
* You can no longer crawl around if you get weakened, such as by a disarm shove or certain other stunning effects.

This is going to need a testmerge and a lot of Dominian sparring.

2023-05-13 16:36 UTC, Geevies commented
!review

2023-05-20 15:23 UTC, NonQueueingMatt requested changes
Two main things:
1) Not a fan of decreasing the chance to break out of an aggressive grab. Those are basically instant to get as you can just hit Z as soon as you get a yellow grab to make it aggressive.
2) Not a fan of adding movement delay after breaking out of grabs. This makes a grab extremely strong in combat, since you can just spam grabs to stack movement delay on people, and they're essentially permastunned.

Get rid of those two things.

2023-06-23 16:38 UTC, NonQueueingMatt approved these changes
seems alright

2023-09-22 21:41 UTC, DreamySkrell approved these changes

2023-09-22 22:18 UTC, merged