Adds 3 new flags/banners: Port Antillia, San Colette, Mictlan (mk. II)
Aurorastation/Aurora.3 pull request #16342
Opened 2023-05-13 20:22 UTC by feartheblackout

![image](https://github.com/Aurorastation/Aurora.3/assets/59633984/605767aa-1f32-48e0-ad70-a6d243c6973c)

Was iffy on the San Colettish stars so I made them smaller but still not sure. Let me know if you have any advice for how to spruce them up.

PR remade because I am new to Smartgit.

2023-05-13 20:22 UTC, feartheblackout commented
!review

2023-05-13 21:42 UTC, Llywelwyn requested changes

2023-05-13 21:42 UTC, Llywelwyn commented on code/game/objects/structures/flags_banners.dm
> +	name = "\improper Mictlan"
```suggestion
	name = "\improper Mictlan flag"
```

2023-05-14 04:54 UTC, niennab commented
These look great! Could you add a curve to the flags and banners like the others? I've made an example below with the San Colette flag. Also, I recommend using this altered Elyran star for the banner and the Fisanduh star for the flag. Stars are a nightmare in pixels.
![flagfeedback1](https://github.com/Aurorastation/Aurora.3/assets/56227386/2c974b52-b3a9-4864-aafd-403d30fa8615)
And the zoom in:
![flagfeedback2](https://github.com/Aurorastation/Aurora.3/assets/56227386/5b6ab2f2-63c3-4797-bd87-43688a0c19c0)

2023-05-14 21:31 UTC, feartheblackout commented
> These look great! Could you add a curve to the flags and banners like the others? I've made an example below with the San Colette flag. Also, I recommend using this altered Elyran star for the banner and the Fisanduh star for the flag. Stars are a nightmare in pixels. ![flagfeedback1](https://user-images.githubusercontent.com/56227386/238168288-2c974b52-b3a9-4864-aafd-403d30fa8615.png) And the zoom in: ![flagfeedback2](https://user-images.githubusercontent.com/56227386/238168294-5b6ab2f2-63c3-4797-bd87-43688a0c19c0.png)

Thanks for the compliment and the suggestions! Will get to them soon.

2023-05-14 21:50 UTC, Llywelwyn approved these changes
One thing worth saying about using the existing Elyra/Fisanduh stars is that they're 5-pointed - the San Colette star is supposed to be 7-pointed. Not sure if that's lore relevant or just because it looks cooler though, so doubt it's a dealbreaker either way.

2023-05-15 10:05 UTC, NonQueueingMatt approved these changes

2023-05-16 10:02 UTC, niennab commented
> One thing worth saying about using the existing Elyra/Fisanduh stars is that they're 5-pointed - the San Colette star is supposed to be 7-pointed. Not sure if that's lore relevant or just because it looks cooler though, so doubt it's a dealbreaker either way.

Ah gotcha. Due to the limited fidelity of sprites, sometimes it's better to have something that is emblematic of the design over trying to force the precise number of points. Alternatively a star like this this could also work in it's place instead. 
![flagfeedback3](https://github.com/Aurorastation/Aurora.3/assets/56227386/88ea0994-629c-400d-8d65-41ee60f921ae)

2023-05-18 20:41 UTC, closed without merging