Brings back crew transfer
Aurorastation/Aurora.3 pull request #16402
Opened 2023-05-28 20:49 UTC by Alberyk

This pr adds another way to end the round: crew transfer

Since the horizon has no shuttle, it works like a bluespace jump without the blue overlay.

The crew can now start a bluespace jump instead of an evacuation as well.

It implements the suggestion from this pr: https://forums.aurorastation.org/topic/17710-make-bluespace-jumping-mechanically-supportedround-ending

2023-05-29 04:58 UTC, TheDanseMacabre commented
Might be better to call it "shift change"/"crew change" instead of "crew transfer". The latter implies the crew leaving the ship, if you ask me.

2023-06-06 17:57 UTC, NonQueueingMatt requested changes

2023-06-06 17:57 UTC, NonQueueingMatt commented on code/controllers/subsystems/evacuation/evacuation_shuttle.dm
> +	if (evacuation_type == "emergency")
these should be defines, but other than that the PR is good to go

2023-06-09 10:11 UTC, NonQueueingMatt approved these changes

2023-06-22 20:23 UTC, Arrow768 requested changes

2023-06-22 20:23 UTC, Arrow768 commented on code/game/machinery/case_button.dm
> +			to_chat(user, "The button is set to start a bluespace jump.")
Repurposing the button is imho not very intuitive and will lead to situations where the wrong action is performed.

As you suggested on discord, moving the evacuation to the swiper is a better option.

2023-06-27 13:53 UTC, Arrow768 approved these changes

2023-06-27 16:49 UTC, SleepyGemmy commented on code/controllers/subsystems/evacuation/evacuation_pods.dm
> +	if (evacuation_type == TRANSFER_EMERGENCY)
```suggestion
	if(evacuation_type == TRANSFER_EMERGENCY)
```

2023-06-27 16:49 UTC, SleepyGemmy commented on code/controllers/subsystems/evacuation/evacuation_pods.dm
> +				if (!pod.arming_controller || pod.arming_controller.armed)
```suggestion
		if("evacuation")
			// Abandon Ship
			for(var/datum/shuttle/autodock/ferry/escape_pod/pod in escape_pods) // Launch the pods!
				if(!pod.arming_controller || pod.arming_controller.armed)
```

2023-06-27 16:49 UTC, SleepyGemmy commented on code/controllers/subsystems/evacuation/evacuation_pods.dm
> +			if (TRANSFER_EMERGENCY)
```suggestion
			if(TRANSFER_EMERGENCY)
```

2023-06-27 16:49 UTC, SleepyGemmy commented on code/controllers/subsystems/evacuation/evacuation_pods.dm
> +	if (evacuation_controller.call_evacuation(user, 0))
```suggestion
	if(!evacuation_controller)
		return
	if(evacuation_controller.deny)
		to_chat(user, "Unable to initiate crew transfer preparation.")
		return
	if(evacuation_controller.is_on_cooldown())
		to_chat(user, evacuation_controller.get_cooldown_message())
		return
	if(evacuation_controller.is_evacuating())
		to_chat(user, "Crew transfer preparation already in progress.")
		return
	if(evacuation_controller.call_evacuation(user, 0))
```

2023-06-27 16:49 UTC, SleepyGemmy commented on code/controllers/subsystems/evacuation/evacuation_pods.dm
> +	if (evacuation_controller && evacuation_controller.cancel_evacuation())
```suggestion
	if(evacuation_controller && evacuation_controller.cancel_evacuation())
```

2023-06-27 16:49 UTC, SleepyGemmy commented on code/controllers/subsystems/evacuation/evacuation_shuttle.dm
> +		if (TRANSFER_EMERGENCY)
```suggestion
		if(TRANSFER_EMERGENCY)
```

2023-06-27 16:49 UTC, SleepyGemmy commented on code/controllers/subsystems/evacuation/evacuation_shuttle.dm
> +	if (evacuation_type == TRANSFER_EMERGENCY)
```suggestion
	if(evacuation_type == TRANSFER_EMERGENCY)
```

2023-06-27 16:49 UTC, SleepyGemmy commented on code/datums/discord/webhook.dm
> +	if (evacuation_controller.evacuation_type == TRANSFER_EMERGENCY)
```suggestion
	if(evacuation_controller.evacuation_type == TRANSFER_EMERGENCY)
```

2023-06-27 16:49 UTC, SleepyGemmy commented on code/datums/late_choices.dm
> +			if (evacuation_controller.evacuation_type == TRANSFER_EMERGENCY) // Emergency shuttle is past the point of no recall
```suggestion
			if(evacuation_controller.evacuation_type == TRANSFER_EMERGENCY) // Emergency shuttle is past the point of no recall
```

2023-06-27 16:49 UTC, SleepyGemmy commented on code/game/gamemodes/game_mode.dm
> +	if (evacuation_controller.evacuation_type == TRANSFER_EMERGENCY)
```suggestion
	if(evacuation_controller.evacuation_type == TRANSFER_EMERGENCY)
```

2023-06-27 16:49 UTC, SleepyGemmy commented on code/game/machinery/case_button.dm
> +	name = "\improper Bluespace Jump Button"
```suggestion
	name = "bluespace jump button"
```

2023-06-27 16:49 UTC, SleepyGemmy commented on code/modules/admin/verbs/randomverbs.dm
> +	var/choice = input("Is this an emergency evacuation, bluespace jump or a crew transfer?") in list(TRANSFER_EMERGENCY, TRANSFER_CREW, TRANSFER_JUMP)
```suggestion
	var/choice = input("Is this an emergency evacuation, bluespace jump, or a crew transfer?") in list(TRANSFER_EMERGENCY, TRANSFER_CREW, TRANSFER_JUMP)
```

2023-06-28 18:37 UTC, merged