Biogenerator Additions
Aurorastation/Aurora.3 pull request #16416
Opened 2023-05-30 21:35 UTC by Spookat

Adds a few additional options to be made with the biogenerator - chicken eggs, ice tunneler eggs and lard. I figured since you can already make monkeys and other species equivalents, some eggs wouldn't be too far off to make.

I am unsure of the point cost, so if you have better values, let me know.

2023-05-30 21:36 UTC, Spookat commented
!review

2023-05-31 01:16 UTC, Alberyk approved these changes

2023-05-31 01:42 UTC, alsoandanswer requested changes
Should probably make the egg a whole carton instead, it'll be tedious to keep manually printing singular eggs.

2023-05-31 06:12 UTC, alsoandanswer approved these changes

2023-05-31 08:55 UTC, niennab approved these changes

2023-05-31 13:39 UTC, FluffyGhoster approved these changes

2023-06-03 10:41 UTC, merged