Canary Tweaks
Aurorastation/Aurora.3 pull request #16417
Opened 2023-05-30 22:13 UTC by TheDanseMacabre

The Canary now has two unequipped EVA hardsuits (which are probably the weakest hardsuits in existence), a box of inflatables, and two interior handrails. The general idea is that the Canary can be used to very quickly get a small number of people to a location (or back from one), in a pinch. The EVA hardsuits are mostly for loading ammunition, but also for a cool pilot aesthetic.

2023-05-30 22:13 UTC, TheDanseMacabre commented
!review

2023-05-31 05:25 UTC, CyberSpyX requested changes
The EVA suits don't really fit the aesthetic of the canary in the least, so those need to go.

2023-06-04 17:29 UTC, FluffyGhoster approved these changes

2023-06-25 19:12 UTC, CyberSpyX approved these changes

2023-06-25 22:00 UTC, Alberyk approved these changes

2023-06-26 17:44 UTC, NonQueueingMatt commented
!review

2023-06-26 19:15 UTC, merged