Adds 2 new flags/banners: Orion Express, Imperial Frontier
Aurorastation/Aurora.3 pull request #16423
Opened 2023-05-31 19:17 UTC by feartheblackout

Probably more on the way eventually, but have these until I gain more steam:

![image](https://github.com/Aurorastation/Aurora.3/assets/59633984/343709ed-9fe4-41eb-81ab-14111d5c2ce0)

Original flag and descriptions for the Imperial Frontier provided by @NotSchwann

2023-05-31 19:17 UTC, feartheblackout commented
!review

2023-06-01 02:35 UTC, Llywelwyn approved these changes

2023-06-03 06:56 UTC, alsoandanswer requested changes
Imperial standard looks fine, orion logo needs to be smaller

2023-07-10 23:35 UTC, feartheblackout commented
Made the Orion Express logo smaller on the banner.

![image](https://github.com/Aurorastation/Aurora.3/assets/59633984/5868b9ae-633c-499f-8183-f08848548034)

2023-07-17 12:02 UTC, NonQueueingMatt approved these changes

2023-08-07 22:01 UTC, DreamySkrell approved these changes

2023-08-08 00:03 UTC, FluffyGhoster approved these changes

2023-08-12 13:02 UTC, merged