Adds Silversun Flag/Banner
Aurorastation/Aurora.3 pull request #16459
Opened 2023-06-10 16:32 UTC by CampinKiller24

Adds the flag/banner/loadout option.

![485c15979f12c2ad37ab812e2e4702aa](https://github.com/Aurorastation/Aurora.3/assets/136183573/109de51b-ef75-41a7-a7f2-0fd614652d37)

Thanks atteria for letting me use the sol canton from the NHP flag

2023-06-10 16:35 UTC, CampinKiller24 commented
!review

2023-06-11 09:09 UTC, niennab requested changes
The flag needs the same curvature found in the other flags. Since the design is very central, I'd do something like this: 
![flagfix](https://github.com/Aurorastation/Aurora.3/assets/56227386/9ba21a20-7208-41d7-9bb2-b08f50f2a0eb)

2023-06-11 21:17 UTC, CampinKiller24 commented
Most recent change changed the flag to this, inline with what nienna suggested above:

![f2f1fd95de265b674b68d0dfc6e10b59](https://github.com/Aurorastation/Aurora.3/assets/136183573/fdb15f64-e2ca-4d21-888a-fc44cacb07ed)

2023-06-12 13:25 UTC, niennab approved these changes

2023-06-13 00:11 UTC, alsoandanswer approved these changes

2023-06-14 01:55 UTC, Llywelwyn approved these changes

2023-06-16 10:42 UTC, NonQueueingMatt approved these changes

2023-06-22 20:12 UTC, Arrow768 approved these changes

2023-06-22 20:29 UTC, merged