Overmap Announcements
Aurorastation/Aurora.3 pull request #16460
Opened 2023-06-10 18:13 UTC by Geevies

* Shuttles flying through overmap events now get a sensor console message about it.

https://github.com/Aurorastation/Aurora.3/assets/22774890/b7b80308-e944-4ac3-9d8c-02a3c65b69e1

2023-06-10 18:13 UTC, Geevies commented
!review

2023-06-13 15:16 UTC, FluffyGhoster requested changes

2023-06-16 10:41 UTC, NonQueueingMatt approved these changes

2023-06-16 10:42 UTC, NonQueueingMatt submitted a review, later dismissed

2023-06-16 10:42 UTC, NonQueueingMatt commented on code/modules/events/electrical_storm.dm
> +		return
Why not just do `Entering [name]` on the parent? You're using affecting_shuttle here anyway

2023-12-21 22:27 UTC, FluffyGhoster commented
Reopening per author request

2023-12-21 22:31 UTC, Geevies commented
!review

2023-12-21 22:31 UTC, Geevies commented
this will need a testmerge, too, to make sure i got everything

2023-12-22 22:00 UTC, Arrow768 submitted a review, later dismissed

2023-12-22 22:00 UTC, Arrow768 commented on code/modules/overmap/ships/computers/sensors.dm
> +	if(NOT_FLAG(stat, NOPOWER))
You should check for INOPERABLE instead

2024-01-01 11:52 UTC, NonQueueingMatt approved these changes

2024-01-09 01:18 UTC, ondrej008 commented
When calling a distress signal, it uses the name of the Horizon instead of the current ship as the announcement.

2024-01-09 16:36 UTC, FluffyGhoster approved these changes

2024-01-09 17:34 UTC, merged