OpenDream linting
Aurorastation/Aurora.3 pull request #16468
Opened 2023-06-12 18:10 UTC by FluffyGhoster

### No, we are not switching to OpenDream, put the pitchforks down

Added OpenDream as a linter in the CI, with all the pragmas active, to better help spot errors and bad coding styles.
Adjusted the CI to accomodate for OpenDream linting.
Refactored all OpenDream found bad.

**For the love of all that is holy, testmerge this before merging, I had to edit a lot of pieces, most of them with spaghetti shitcode, that makes up systems I am not familiar with. Do not make Hadii proud, testmerge to check that nothing got nuked!**

2023-06-12 18:33 UTC, FluffyGhoster commented
!review

2023-06-12 18:33 UTC, FluffyGhoster commented
!high risk

2023-06-22 20:09 UTC, Arrow768 requested changes

2023-06-22 20:09 UTC, Arrow768 commented on .github/workflows/byond.yml
> -          python3 tools/TagMatcher/tag-matcher.py ../..
Tagmatcher should be deleted if its no longer needed

2023-06-25 22:45 UTC, Arrow768 approved these changes

2023-06-26 14:03 UTC, Arrow768 approved these changes

2023-06-26 14:18 UTC, NonQueueingMatt approved these changes

2023-06-26 15:05 UTC, merged