Destroys SS13 culture: Gibber rename
Aurorastation/Aurora.3 pull request #16466
Opened 2023-06-11 21:08 UTC by TheDanseMacabre

The gibber now has a more sensible name

2023-06-11 21:08 UTC, TheDanseMacabre commented
!review

2023-06-11 23:22 UTC, NonQueueingMatt approved these changes

2023-06-12 04:02 UTC, FluffyGhoster approved these changes

2023-06-12 21:05 UTC, Llywelwyn approved these changes

2023-06-14 06:33 UTC, Llywelwyn commented on html/changelogs/dansemacabre-lrpname.yml
> +  - tweak: "The gibber is now called the automatic butchery machine."
```suggestion
  - tweak: "The gibber is now called the autobutcher."
```

2023-06-22 20:10 UTC, Arrow768 requested changes
The path needs to be updated to reflect the new name

2023-07-17 12:02 UTC, closed without merging