Nerfs KAs in Atmosphere
Aurorastation/Aurora.3 pull request #16496
Opened 2023-06-19 18:46 UTC by CampinKiller24

KAs have long been considered a strong weapon in low/no atmosphere only, despite this not being the case, especially with the right upgrades. A "properly" upgraded KA can instantly crit someone in heavy armor in a single shot in atmosphere currently. This nerfs KAs in atmosphere (>~40 kPA), but keeps them strong in low atmosphere/void conditions, as was intended. Also nerfs a couple components that allow straight shredding of people in armor.

2023-06-19 18:46 UTC, CampinKiller24 commented
!review

2023-06-26 13:45 UTC, NonQueueingMatt approved these changes

2023-06-26 13:46 UTC, NonQueueingMatt requested changes

2023-06-26 13:46 UTC, NonQueueingMatt commented on code/modules/custom_ka/core.dm
> +			if(ispath(installed_barrel.projectile_type, /obj/item/projectile/kinetic))
istype

2023-06-26 13:46 UTC, NonQueueingMatt commented on code/modules/custom_ka/core.dm
> +			if(ispath(installed_barrel.projectile_type, /obj/item/projectile/beam))
istype

2023-06-26 13:46 UTC, NonQueueingMatt commented on code/modules/custom_ka/core.dm
> +				shot_projectile.range = range_increase
this is a lot of copypaste, do this on a generic projectile typecast, then edit the  other types as needed

2023-07-17 12:02 UTC, closed without merging