Hardsuit underwear shown through cracks
Aurorastation/Aurora.3 pull request #16605
Opened 2023-07-01 08:17 UTC by FluffyGhoster

![image](https://github.com/Aurorastation/Aurora.3/assets/65877598/24864137-1296-48e6-b5f1-3f5c85143de1)

Added the ability for the underwear (uniform) to be seen through the cracks of hardsuits (rigs).

![image](https://github.com/Aurorastation/Aurora.3/assets/65877598/64ebda40-ca48-47d0-a2e6-44de1f235be6)
![image](https://github.com/Aurorastation/Aurora.3/assets/65877598/ef814db2-a527-4208-80d0-15e598c4a6b7)
![image](https://github.com/Aurorastation/Aurora.3/assets/65877598/5a8bcb0a-f8f8-4afb-b91b-9297a833f4d3)

2023-07-01 08:20 UTC, FluffyGhoster commented
PS: I have next to no idea of how the rendering engine works, test it plenty.

!review

2023-07-05 10:14 UTC, NonQueueingMatt requested changes
Why does the uniform actually not show up? This looks very hacky to me, there has to be a better solution

2023-07-05 13:53 UTC, FluffyGhoster commented
> Why does the uniform actually not show up? This looks very hacky to me, there has to be a better solution

Because (IIRC) the chest piece (not only of the RIG, but in general) removes the uniform layer from the rendering, which is normally fine since it's covered anyways, but not in this case where the chestpiece has see-through holes in the sprite

2023-07-17 12:07 UTC, NonQueueingMatt approved these changes

2023-07-23 18:15 UTC, Arrow768 approved these changes

2023-07-23 21:01 UTC, merged