Re-adds Patience, replaces a holodeck with a garden and pool
Aurorastation/Aurora.3 pull request #16650
Opened 2023-07-07 20:13 UTC by lavillastrangiato

This PR (is my first please be nice teehee) replaces the top holodeck with a large, authentic green space, and puts Patience in the center of the garden. There is also a shallow pool that people can splash around in. No smoking!

Also included in this PR:
* An athletic locker in the D3 bathroom.
* A stealthy change of adding a cabinet to the D3 cafe, containing some grenadine syrup, toothpaste, dyn juice, mint syrup, and fatshouter milk, to make setting up shop at the cafe less annoying for a bartender.

Misc.:
* I figured since the changing room is right next to this area it's kind of unnecessary to connect them directly, and not connecting them directly gives me valuable wall space. 
* There are two air alarms in this entire area; one is in the garden area, and the other is in the entryway. The one in the entryway is there so that it can turn off the vent and scrubber in case that area is breached. This was recommended to me by ShakyJake, atmos Jesus.

![image](https://github.com/Aurorastation/Aurora.3/assets/63124803/f62af52a-1289-4a73-aff4-8fa2ff08dada)

2023-07-07 20:13 UTC, lavillastrangiato commented
!review

2023-07-09 16:46 UTC, SleepyGemmy requested changes
PR is fine but you need a changelog.

2023-07-10 01:08 UTC, Arrow768 commented
Why not add a new holodeck with that functionality?

2023-07-10 01:51 UTC, Greenjoe12345 commented
I had ideas of putting the tree in another location that would looknicer then this square corner it's in in this pr

2023-07-10 20:23 UTC, lavillastrangiato commented
> Why not add a new holodeck with that functionality?

Because people preferred an actual physical green space rather than a holodeck copy, and several people commented that they thought two holodecks was pointless.

2023-07-10 20:42 UTC, SleepyGemmy commented on html/changelogs/example copy.yml
consider filename, but should be fine.

2023-07-10 20:42 UTC, SleepyGemmy commented on html/changelogs/example copy.yml
> +  - rscadd: "Adds small closet to D3 cafe containing non-alcoholic drink ingredients."
```suggestion
  - maptweak: "Replaces the top holodeck with a physical green space and small pool."
  - maptweak: "Adds a athletic locker to the changing room."
  - maptweak: "Adds a small closet to the D3 cafe containing non-alcoholic drink ingredients."
```

2023-07-17 16:56 UTC, SleepyGemmy commented on html/changelogs/example copy.yml
> +  - maptweak: "Adds a athletic locker to the changing room."
```suggestion
  - maptweak: "Adds an athletic locker to the changing room."
```
whoops i forgot the AEIOU.

2023-07-23 17:13 UTC, Arrow768 requested changes
The purpose of the holodeck is to provide the crew with their personal preference for a "relaxation space" without having to map out every single personal preference there is.
This can quite easily be a holodeck (see the other new holodeck layouts we got recently) and as such it should be mapped as a holodeck if you want to pursue this option.

2023-07-23 18:32 UTC, Arrow768 commented
Closed in favour of the central tree remap

2023-07-23 18:32 UTC, closed without merging