Removes fragmentation ammo from the sec armory
Aurorastation/Aurora.3 pull request #16681
Opened 2023-07-10 04:10 UTC by TheDanseMacabre

Like the now-removed PEAC HE ammo, it's a one-hit kill weapon. Sec doesn't need this.

2023-07-10 04:10 UTC, TheDanseMacabre commented
!review

2023-07-10 04:42 UTC, FluffyGhoster commented
Tuning the damage of the projectile instead of removing options is preferable IMHO (improve don't remove)

2023-07-10 04:46 UTC, TheDanseMacabre commented
> Tuning the damage of the projectile instead of removing options is preferable IMHO (improve don't remove)

Security doesn't need any more weapons at all.

2023-07-10 05:03 UTC, FluffyGhoster commented
> Security doesn't need any more weapons at all. Nerfing this will just make it not worth using for antagonists, which is even less desirable.

I do not agree with the former on the basis that weapons diversity is good; for the later, a subclass of the same projectile can be made with different stats, and replace the one in the armory lockers

2023-07-10 05:04 UTC, FluffyGhoster requested changes

2023-07-10 05:04 UTC, FluffyGhoster commented on code/game/objects/structures/crates_lockers/closets/secure/guncabinet.dm
> +	for(var/i = 3)
```suggestion
	for(var/i = 1 to 3)
```

To fix the CI error

2023-07-12 05:21 UTC, CyberSpyXD commented
I can approve this once the checks succeed.

2023-07-12 23:51 UTC, Alberyk approved these changes

2023-07-15 09:33 UTC, NonQueueingMatt approved these changes

2023-07-15 09:34 UTC, NonQueueingMatt commented on code/game/objects/structures/crates_lockers/closets/secure/guncabinet.dm
> +	for(var/i = 3)
```suggestion
	for(var/i = 1 to 3)
```

2023-07-15 10:36 UTC, merged