Adds Capybaras
Aurorastation/Aurora.3 pull request #16734
Opened 2023-07-15 18:35 UTC by KingOfThePing

Adds Capybaras. Not mapped in anywhere right now. Simple mobs you can pet (with some chat outputs in return). Walks around. Has a rest sprite. No sounds (couldnt find good ones). 

Chillaxes a lot. Sprites by kyres.

2023-07-15 18:36 UTC, KingOfThePing commented
!review

2023-07-15 18:39 UTC, NonQueueingMatt requested changes

2023-07-15 18:39 UTC, NonQueueingMatt commented on code/modules/mob/living/simple_animal/friendly/capybara.dm
> +											"[src] is not disturbed in it's relaxation.",
```suggestion
											"[src] is not disturbed in its relaxation.",
```

2023-07-15 18:39 UTC, NonQueueingMatt commented on code/modules/mob/living/simple_animal/friendly/capybara.dm
> +											"[src] accepted it's fate to receive pets.")
```suggestion
											"[src] has accepted its fate to receive pets.")
```

2023-07-15 19:22 UTC, FluffyGhoster requested changes

2023-07-15 19:22 UTC, FluffyGhoster commented on code/modules/mob/living/simple_animal/friendly/capybara.dm
> +	icon = 'icons/mob/npc/coconut_dog.dmi'
If the typepath is capybara, it would be optimal for the icon file to be called capybara too

2023-07-15 19:22 UTC, FluffyGhoster commented on code/modules/mob/living/simple_animal/friendly/capybara.dm
> +		M.visible_message("<span class='warning'>[M] pets [src].</span>","<span class='notice'>You eagerly pet [src].</span>")
```suggestion
		M.visible_message(SPAN_WARNING("[M] pets [src]."), SPAN_NOTICE("You eagerly pet [src]."))
```

2023-07-15 19:22 UTC, FluffyGhoster commented on code/modules/mob/living/simple_animal/friendly/capybara.dm
> +		spawn(rand(20,50))
spawn is terrible for performance, I would suggest to make the below code a separate function, and register a timer (addtimer) to call it instead

2023-07-15 19:23 UTC, KingOfThePing commented on code/modules/mob/living/simple_animal/friendly/capybara.dm
> +		M.visible_message("<span class='warning'>[M] pets [src].</span>","<span class='notice'>You eagerly pet [src].</span>")
I forgor

2023-07-17 12:18 UTC, NonQueueingMatt approved these changes

2023-07-17 16:06 UTC, SleepyGemmy requested changes

2023-07-17 16:06 UTC, SleepyGemmy commented on code/modules/mob/living/simple_animal/friendly/capybara.dm
> +		..()
```suggestion
		addtimer(CALLBACK(src, PROC_REF(pet_response)), rand(2 SECONDS, 5 SECONDS))
```
should work, but please test it.

2023-07-17 16:06 UTC, SleepyGemmy commented on code/modules/mob/living/simple_animal/friendly/capybara.dm
> +		to_chat(user, "How can someone kill such a friendly creature?")
```suggestion
		to_chat(user, "How can someone kill such a friendly creature?")

/mob/living/simple_animal/capybara/examine(mob/user)
	..()
	if(stat == DEAD)
		to_chat(user, "How can someone kill such a friendly creature?")

/mob/living/simple_animal/capybara/pet_response()
	if(!stat && M)
				icon_state = icon_living
				var/list/responses = list(
					"\The [src] looks content.",
					"\The [src] is not disturbed in its relaxation.",
					"\The [src] looks at you with a satisfied look.",
					"\The [src] has accepted its fate to receive pets."
				)
				to_chat(M, pick(responses))
	else
		..()
```

2023-07-20 19:06 UTC, SleepyGemmy commented on code/modules/mob/living/simple_animal/friendly/capybara.dm
> +/mob/living/simple_animal/capybara/attack_hand(mob/living/carbon/M as mob)
```suggestion
/mob/living/simple_animal/capybara/attack_hand(mob/living/carbon/M)
```

2023-07-20 19:06 UTC, SleepyGemmy commented on code/modules/mob/living/simple_animal/friendly/capybara.dm
> +		addtimer(CALLBACK(src, PROC_REF(PetResponse)), rand(2 SECONDS, 5 SECONDS))
```suggestion
		addtimer(CALLBACK(src, PROC_REF(pet_response)), rand(2 SECONDS, 5 SECONDS))
```

2023-07-20 19:06 UTC, SleepyGemmy commented on code/modules/mob/living/simple_animal/friendly/capybara.dm
> +/mob/living/simple_animal/capybara/proc/PetResponse(mob/M)
```suggestion
/mob/living/simple_animal/capybara/proc/pet_response(mob/M)
```

2023-07-21 15:41 UTC, SleepyGemmy approved these changes

2023-07-22 13:14 UTC, SleepyGemmy commented on code/modules/mob/living/simple_animal/friendly/capybara.dm
> +
```suggestion
```

2023-07-23 14:30 UTC, merged