Cyclops Mining Vessel - Second Take
Aurorastation/Aurora.3 pull request #16738
Opened 2023-07-16 04:38 UTC by Alberyk

This pr revives #16071 while fixing its issues.

2023-07-17 12:16 UTC, NonQueueingMatt approved these changes

2023-08-08 09:34 UTC, FluffyGhoster approved these changes

2023-08-09 17:00 UTC, DreamySkrell commented on maps/away/ships/heph/cyclops/cyclops_ghostroles.dm
> +	tags = list("External")
`welcome_message` should be set on all new ghostspawners as discussed here <https://github.com/Aurorastation/Aurora.3/pull/16248#issuecomment-1521304132>

2023-08-09 17:05 UTC, DreamySkrell commented on maps/away/ships/heph/cyclops/cyclops_mining_ship.dm
> +        "Cyclops Shuttle" = list("nav_hangar_cyclops")
Please add RP fluff fields like `designer`, `weapons`, `shiptype`, as described in `code\modules\overmap\overmap_object.dm`

2023-08-22 23:23 UTC, RustingWithYou commented on maps/away/ships/heph/cyclops/cyclops_ghostroles.dm
> +	possible_species = list(SPECIES_HUMAN, SPECIES_HUMAN_OFFWORLD, SPECIES_TAJARA, SPECIES_TAJARA_MSAI, SPECIES_TAJARA_ZHAN, SPECIES_SKRELL, SPECIES_SKRELL_AXIORI, SPECIES_UNATHI)
I can't speak for Tajara, but given the close ties between Hephaestus and Unathi I think that Unathi being allowed as captains is fine from a lore POV.

2023-09-06 14:49 UTC, DreamySkrell requested changes
Code and mapping looks fine now I think. If changes below are addressed, just ping me and I'll approve.

Though the ship should have a second external airlock on the west side, as right now it has just one on the east side. Multiple airlocks make EVA less of a pain, and at least two are needed so if some shuttle is docked to one, you can still use the other. I'd put the second external airlock near the ore processors - it can be one of the automatic external airlock spawners.

This is optional, but: I'd also add some catwalks/lattices on the exterior, so the ship looks a bit more industrial, and to make moving around in EVA a bit easier.

2023-09-07 21:00 UTC, DreamySkrell approved these changes

2023-09-07 21:00 UTC, NonQueueingMatt approved these changes

2023-09-07 23:56 UTC, merged