ChemMaster UI tweaks
Aurorastation/Aurora.3 pull request #16733
Opened 2023-07-15 18:08 UTC by FluffyGhoster

Tweaked the new chemmaster UI and added some sounds to its operations
The UI fonts are now smaller, the tabulations takes less space from the margins, and some sounds for the various buttons and operations are added

![image](https://github.com/Aurorastation/Aurora.3/assets/65877598/6de33e51-43ff-4434-b107-a6f89f085395)

https://www.youtube.com/watch?v=k375NYDG0_c

Thanks to Ramke for the feedbacks on it

2023-07-15 19:15 UTC, FluffyGhoster commented
!review

2023-07-17 12:12 UTC, NonQueueingMatt approved these changes

2023-07-23 16:59 UTC, Arrow768 requested changes

2023-07-23 16:59 UTC, Arrow768 commented on code/modules/reagents/Chemistry-Machinery.dm
> +
The defines should be placed at the top unless there is a good reason not to do so.

2023-07-23 16:59 UTC, Arrow768 commented on code/modules/reagents/Chemistry-Machinery.dm
> +#define CHEMMASTER_SWITCH_SOUND playsound(src, 'sound/machines/switch1.ogg', 75, 1)
The defines should be placed at the top unless there is a good reason not to do so.

2023-07-23 16:59 UTC, Arrow768 commented on code/modules/reagents/Chemistry-Machinery.dm
> +#undef CHEMMASTER_BOTTLE_SOUND
The undefs should be placed at the bottom of the file unless there is a good reason not to do so.

2023-07-24 21:18 UTC, Arrow768 approved these changes

2023-07-24 22:37 UTC, merged