New medkit and trauma pouch sprites
Aurorastation/Aurora.3 pull request #16744
Opened 2023-07-16 13:59 UTC by nauticall

Gives the medkits and trauma pouches yet another fresh coat of paint. They now look sleek and nice and have this cool stripe on them that tells you what they are.

But it's not only the outside -- the pouches inside several of the kits now look nicer too! Subjectively speaking.

Thirdly, the Horizon's medical bay storage room has been mapped to accommodate the new medkits and stack them all in a lovely, tidy, perfectionist-pleasing manner. You're welcome, doctors. 

## Screenshots
![image](https://github.com/Aurorastation/Aurora.3/assets/55491249/0b22c7a5-fb23-4599-a6b7-4a89df4dee7b)
_Not pictured ingame: the combat kit, because I forgot to update it in this instance and am too lazy to reboot the server just for that._

![image](https://github.com/Aurorastation/Aurora.3/assets/55491249/85b19f83-ddce-4cd4-9b92-940437aa9268)
_DMI file stuff. Inhands included._

![image](https://github.com/Aurorastation/Aurora.3/assets/55491249/16b45b3f-d00d-4004-8212-94a403d471ed)
_What can I say except you're welcome? For the kits, the sprites, the... sky._

![image](https://github.com/Aurorastation/Aurora.3/assets/55491249/8d9bd862-b805-42c3-a6d5-38420b12c59d)
_The rainbow of new pouches. Yes, I tore one open to show that too. Not sorry._

2023-07-16 13:59 UTC, nauticall commented
!review

2023-07-16 14:01 UTC, NonQueueingMatt requested changes

2023-07-16 14:01 UTC, NonQueueingMatt commented on code/game/objects/items/weapons/storage/firstaid.dm
>  /obj/item/storage/firstaid/radiation/Initialize()
need to delete these Initialize() procs altogether if all they do is call `..()`

2023-07-16 14:01 UTC, NonQueueingMatt commented on code/game/objects/items/weapons/storage/firstaid.dm
>  /obj/item/storage/firstaid/trauma/fill()
need to delete these fill() procs altogether if all they do is call `..()`

2023-07-16 14:01 UTC, NonQueueingMatt commented on code/game/objects/items/weapons/storage/firstaid.dm
>  	. = ..()
need to delete these fill() procs altogether if all they do is call `..()`

2023-07-16 14:01 UTC, NonQueueingMatt commented on code/game/objects/items/weapons/storage/firstaid.dm
>  	. = ..()
need to delete these fill() procs altogether if all they do is call `..()`

2023-07-16 14:01 UTC, NonQueueingMatt commented on code/game/objects/items/weapons/storage/firstaid.dm
>  	. = ..()
need to delete these fill() procs altogether if all they do is call `..()`

2023-07-16 14:26 UTC, NonQueueingMatt approved these changes

2023-07-16 14:46 UTC, niennab approved these changes

2023-07-16 18:51 UTC, alsoandanswer reviewed
Sorry, this resprite isn't really needed. 

I *just* resprited these medkits not too long ago. 

Please check if the .dmi file has been edited recently and if so, ask them
(especially if they're part of the active developer team!)

This also breaks Medbots, since they rely on the boxy sprite as their base icon.

2023-07-17 03:29 UTC, Generalcamo commented
I'd recommend splitting out the medpouches to a new PR. Those were a direct port from Bay, and the resprite would be accepted quickly.

2023-07-17 03:43 UTC, nauticall commented
ah well! was good practice anyway, gonna PR the pouches/descs separately then

2023-07-18 08:19 UTC, nauticall commented
![image](https://github.com/Aurorastation/Aurora.3/assets/55491249/81eda7bc-d3f8-4252-bf03-00624d0f6c0d)
New-new kits! I've been asked to keep the existing ones' silhouette and shape consistent so that they don't screw up the medbots/map placements and have also repurposed the existing ones into "large" first-aid kits with _lots_ of treatments and more advanced medication than the standard model.

Mapping these large kits in is a biiit out of scope for this PR so that'll come later, both to avoid conflicts and so I don't end up having this PR stuck in merge hell because of the mapping stuff.

2023-07-18 10:17 UTC, NonQueueingMatt approved these changes

2023-07-18 13:19 UTC, alsoandanswer approved these changes

2023-07-19 14:52 UTC, merged