Adrenaline sac nerfs
Aurorastation/Aurora.3 pull request #16755
Opened 2023-07-16 21:36 UTC by OolongCow

Changeling should not be dominated by an all-consuming, must-take power that drastically warps the entire antagonist and discourages doing anything else because it's simply too powerful. Which is exactly what adrenaline sacs does.

Oxycomorphine is an incredibly powerful painkiller that is so combat-warping it _requires_ you use another chemical to remove the debilitating side-effects. It is meant to be difficult to acquire without an uplink and be a reward for humanoid antagonists in do-or-die situations to prevent paincrit and escape to heal / win a fight, and is priced accordingly. You have to purchase synaptizine separately to effectively use it in combat situations. And those uses are limited by how many you're willing to buy.

Changeling's adrenaline sacs ability costs the bare minimum of genome points, uses a low chemical costs, instantly removes all stuns, instantly makes you all but immune to pain, and makes you in practical terms immune to anything but hardcoded stun/weaken effects while making you so fast that it is a guaranteed get-out-of-jail-free card for an antagonist that already regularly comes back to life two or three times a round. In a gamemode where multiple often spawn. Something about the ability has to go, and the fairest option is probably the "fight until braindeath" chemical that no other antag has such easy access to.

2023-07-16 21:37 UTC, OolongCow commented
!review

2023-07-17 12:15 UTC, NonQueueingMatt requested changes

2023-07-17 12:15 UTC, NonQueueingMatt commented on code/game/gamemodes/changeling/implements/powers/body.dm
> +	C.reagents.add_reagent(/singleton/reagent/synaptizine, 3) //To counter oxycomorphine's side-effects.
```suggestion
	C.reagents.add_reagent(/singleton/reagent/synaptizine, 3) //To counter mortaphenyl's side-effects.
```

2023-07-17 15:39 UTC, SleepyGemmy approved these changes

2023-07-30 10:03 UTC, closed without merging