Unapologetic claw buffs - Allows unarmed attacks against vines.
Aurorastation/Aurora.3 pull request #16750
Opened 2023-07-16 14:44 UTC by 1Sparky1

Title.

2023-07-16 14:44 UTC, 1Sparky1 commented
!review

2023-07-16 14:57 UTC, NonQueueingMatt requested changes

2023-07-16 14:57 UTC, NonQueueingMatt commented on code/modules/hydroponics/spreading/spreading.dm
> +		return 0
```suggestion
		return FALSE
```

2023-07-16 16:54 UTC, NonQueueingMatt approved these changes

2023-07-16 18:43 UTC, alsoandanswer approved these changes

2023-07-18 07:12 UTC, FluffyGhoster approved these changes

2023-07-22 10:50 UTC, merged