More HUDs
Aurorastation/Aurora.3 pull request #16751
Opened 2023-07-16 15:52 UTC by 1Sparky1

Adds a bunch of new faction specific HUDs for both security (Variants of the non-glasses HUD) and medical (variants of the aviator and non-glasses HUD). These all should be coloured with their faction's palette (but I am really bad for messing that up somewhere).

2023-07-16 15:53 UTC, 1Sparky1 commented
!review

2023-07-17 12:15 UTC, NonQueueingMatt approved these changes

2023-07-17 16:14 UTC, SleepyGemmy requested changes
look over all items and their name variable added in this PR and make sure `\The` is prefixed, so that it reads as "X throws the Zeng-Hu health scanner HUD!" and not "X throws Zeng-Hu health scanner HUD!".

2023-07-17 16:32 UTC, SleepyGemmy requested changes

2023-07-17 16:32 UTC, SleepyGemmy commented on code/modules/clothing/glasses/glasses.dm
>  	name = "PMCG HUD aviators"
```suggestion
	name = "\improper PMCG HUD aviators"
```

2023-07-17 16:32 UTC, SleepyGemmy commented on code/modules/clothing/glasses/hud.dm
> +	name = "PMCG health scanner HUD"
```suggestion
	name = "\improper PMCG health scanner HUD"
```

2023-07-17 16:32 UTC, SleepyGemmy commented on code/modules/clothing/glasses/hud.dm
> +	name = "EPMC health scanner HUD"
```suggestion
	name = "\improper EPMC health scanner HUD"
```

2023-07-17 16:32 UTC, SleepyGemmy commented on code/modules/clothing/glasses/hud.dm
> +	name = "NanoTrasen health scanner HUD"
```suggestion
	name = "\improper NanoTrasen health scanner HUD"
```

2023-07-17 16:32 UTC, SleepyGemmy commented on code/modules/clothing/glasses/hud.dm
> +	name = "Zeng-Hu health scanner HUD"
```suggestion
	name = "\improper Zeng-Hu health scanner HUD"
```

2023-07-17 16:32 UTC, SleepyGemmy commented on code/modules/clothing/glasses/hud.dm
> +	name = "Zavodskoi security HUD"
```suggestion
	name = "\improper Zavodskoi security HUD"
```

2023-07-17 16:32 UTC, SleepyGemmy commented on code/modules/clothing/glasses/hud.dm
> +	name = "PMCG security HUD"
```suggestion
	name = "\improper PMCG security HUD"
```

2023-07-17 16:32 UTC, SleepyGemmy commented on code/modules/clothing/glasses/hud.dm
> +	name = "EPMC security HUD"
```suggestion
	name = "\improper EPMC security HUD"
```

2023-07-17 16:32 UTC, SleepyGemmy commented on code/modules/clothing/glasses/hud.dm
> +	name = "Idris security HUD"
```suggestion
	name = "\improper Idris security HUD"
```

2023-07-17 16:32 UTC, SleepyGemmy commented on code/modules/clothing/glasses/glasses.dm
> +	desc = "Sunglasses in the colours of the Private Military Contracting Group. They come with a blue-tinted HUD and a chrome finish."
```suggestion
	desc = "Sunglasses in Private Military Contracting Group colours. They come with a blue-tinted HUD and a chrome finish."
```

2023-07-17 16:32 UTC, SleepyGemmy commented on code/modules/clothing/glasses/glasses.dm
> +	desc = "Sunglasses in the colours of the NanoTrasen Corporation. They come with a blue-tinted HUD and a chrome finish."
```suggestion
	desc = "Sunglasses in NanoTrasen colours. They come with a blue-tinted HUD and a chrome finish."
```

2023-07-17 16:32 UTC, SleepyGemmy commented on code/modules/clothing/glasses/glasses.dm
> +	desc = "Sunglasses in the colours of Zeng-Hu Pharmaceuticals. They come with a purple-tinted HUD and a chrome finish."
```suggestion
	desc = "Sunglasses in Zeng-Hu Pharmaceuticals colours. They come with a purple-tinted HUD and a chrome finish."
```

2023-07-17 16:32 UTC, SleepyGemmy commented on code/modules/clothing/glasses/glasses.dm
>  	desc = "Sunglasses in the colours of the Private Military Contracting Group. They come with a blue-tinted HUD and a chrome finish."
```suggestion
	desc = "Sunglasses in Private Military Contracting Group colours. They come with a blue-tinted HUD and a chrome finish."
```

2023-07-17 16:32 UTC, SleepyGemmy commented on code/modules/clothing/glasses/glasses.dm
>  	desc = "Fat sunglasses in the colours of the Private Military Contracting Group. They come with a blue-tinted HUD and a chrome finish."
```suggestion
	desc = "Fat sunglasses in Private Military Contracting Group colours. They come with a blue-tinted HUD and a chrome finish."
```

2023-07-17 16:32 UTC, SleepyGemmy commented on code/modules/clothing/glasses/hud.dm
> +	desc = "A heads-up display in the colours of the Private Military Contracting Group."
```suggestion
	desc = "A heads-up display in Private Military Contracting Group colours."
```

2023-07-17 16:32 UTC, SleepyGemmy commented on code/modules/clothing/glasses/hud.dm
> +	desc = "A heads-up display in the colours of the NanoTrasen Corporation."
```suggestion
	desc = "A heads-up display in NanoTrasen colours."
```

2023-07-17 16:32 UTC, SleepyGemmy commented on code/modules/clothing/glasses/hud.dm
> +	desc = "A heads-up display in the colours of Zeng-Hu Pharmaceuticals."
```suggestion
	desc = "A heads-up display in Zeng-Hu Pharmaceuticals colours."
```

2023-07-17 16:32 UTC, SleepyGemmy commented on code/modules/clothing/glasses/hud.dm
> +	desc = "A heads-up display in the colours of the Private Military Contracting Group."
```suggestion
	desc = "A heads-up display in Private Military Contracting Group colours."
```

2023-07-17 16:32 UTC, SleepyGemmy commented on code/modules/clothing/glasses/hud.dm
> +	desc = "A heads-up display in the colours of the Idris Incorporated."
```suggestion
	desc = "A heads-up display in Idris Incorporated colours."
```

2023-07-19 18:43 UTC, SleepyGemmy approved these changes

2023-07-22 11:21 UTC, merged