AAUUURRGHHHHH!!!!
Aurorastation/Aurora.3 pull request #16765
Opened 2023-07-17 16:42 UTC by kyres1

What the title says. As you can suspect, nobody has realized this until a couple weeks ago, and thus we have had a miraculous and sudden case of IFF beacons falling off of shuttles. Crazy. This fixes that.

2023-07-17 16:45 UTC, SleepyGemmy requested changes

2023-07-17 16:45 UTC, SleepyGemmy commented on code/modules/overmap/ships/identification.dm
> +	anchored = 1
```suggestion
	anchored = TRUE
```

2023-07-17 18:58 UTC, Arrow768 approved these changes

2023-07-17 19:01 UTC, alsoandanswer approved these changes

2023-07-17 20:26 UTC, SleepyGemmy approved these changes

2023-07-19 18:42 UTC, SleepyGemmy approved these changes

2023-07-21 03:24 UTC, merged