backpack visual tweaks + one hairstyle adjusted
Aurorastation/Aurora.3 pull request #16782
Opened 2023-07-18 23:32 UTC by crunchypretzels

Removed the clasp from all back items that had one, as far as I could tell. Unpopular enough to warrant it.

fixes #16462

This also adds a few pixels to the Fade - Clean Low hairstyle, to avoid it looking like a hairpiece or something.

2023-07-18 23:33 UTC, crunchypretzels commented
!review

2023-07-19 00:04 UTC, alsoandanswer approved these changes
Should probably seperate the hair change to a different PR

2023-07-19 00:05 UTC, atteria commented on icons/obj/storage/duffelbag.dmi
Looks like there's a rogue pixel on `duffel-emt_ba`

2023-07-19 00:10 UTC, alsoandanswer reviewed
You need to edit the mask (bright pink strap) in the dmi to fix the masking bug.

2023-07-19 00:36 UTC, crunchypretzels commented on icons/obj/storage/duffelbag.dmi
Resolution Forthcoming

2023-07-19 00:37 UTC, alsoandanswer requested changes
Should probably get a feedback thread on the clasps

2023-07-19 00:59 UTC, crunchypretzels commented
!wip

2023-07-19 00:59 UTC, crunchypretzels commented
https://forums.aurorastation.org/topic/18582-clasp-removal-from-satchels-duffels-etc/

2023-07-19 01:37 UTC, atteria approved these changes

2023-09-07 21:02 UTC, NonQueueingMatt commented
Stale

2023-09-07 21:02 UTC, closed without merging