Chlorine gas canisters
Aurorastation/Aurora.3 pull request #16827
Opened 2023-07-22 12:02 UTC by FluffyGhoster

Added a chlorine gas tank (canister), and added it to the uplink.
Added a canister icon for poisonous gasses.

![image](https://github.com/Aurorastation/Aurora.3/assets/65877598/3f14b10d-83bb-4b8b-8907-df090ff620de)

2023-07-22 12:57 UTC, FluffyGhoster commented
!review

2023-07-25 19:57 UTC, atteria commented
The skull may be a little *too* good. It looks very three dimensional, which would be great if it wasn't supposed to be a decal.

2023-07-26 05:15 UTC, FluffyGhoster commented
> The skull may be a little _too_ good. It looks very three dimensional, which would be great if it wasn't supposed to be a decal.

I have just reduced the skull of the image for poisonous gasses:
![image](https://github.com/Aurorastation/Aurora.3/assets/65877598/23bacec8-0a0f-4ae7-a263-ea46914d2cba)
If you can produce a better icon for the tank, I am happy to include it

2023-07-27 17:27 UTC, NonQueueingMatt requested changes

2023-07-27 17:27 UTC, NonQueueingMatt commented on code/datums/uplink/bioweapons.dm
> +	bluecrystal_cost = 5
```suggestion
```
Not exactlyy a support item.

2023-08-12 17:35 UTC, NonQueueingMatt approved these changes

2023-08-21 11:44 UTC, DreamySkrell approved these changes

2023-08-21 14:38 UTC, merged