Vaurca Integrated Magclaws
Aurorastation/Aurora.3 pull request #16886
Opened 2023-07-27 02:46 UTC by RustingWithYou

This adds a loadout augment for a set of deployable magboots, available to Vaurca. 

Reasoning: Magboots look dumb on Vaurca, especially Bulwarks, which don't even have sprites for them. Instead of adding the Vaurca-specific magboots all over the place, now the funny bugs can get them in loadout.

I can job-restrict this if required, but I don't feel that magboots are rare enough to be particularly unbalanced.

2023-07-27 02:46 UTC, RustingWithYou commented
!review

2023-07-30 21:35 UTC, Arrow768 requested changes
This needs to be job restricted to engineering/mining.

2023-07-30 22:19 UTC, RustingWithYou commented
> This needs to be job restricted to engineering/mining.

Job restrictions have been added

2023-08-04 14:30 UTC, NonQueueingMatt commented
!review

2023-08-04 14:31 UTC, NonQueueingMatt requested changes

2023-08-04 14:31 UTC, NonQueueingMatt commented on code/game/objects/items/weapons/vaurca_items.dm
> +	loc = null
this is already handled by qdel

2023-08-04 14:31 UTC, NonQueueingMatt commented on code/game/objects/items/weapons/vaurca_items.dm
> +	return 1
```suggestion
	return TRUE
```

2023-08-06 14:14 UTC, Arrow768 approved these changes

2023-08-08 02:24 UTC, FluffyGhoster commented on code/game/objects/items/weapons/vaurca_items.dm
> +	species_restricted = list(BODYTYPE_VAURCA,BODYTYPE_VAURCA_WARFORM, BODYTYPE_VAURCA_BULWARK)
```suggestion
	species_restricted = list(BODYTYPE_VAURCA, BODYTYPE_VAURCA_WARFORM, BODYTYPE_VAURCA_BULWARK)
```

2023-09-07 21:04 UTC, NonQueueingMatt approved these changes

2023-09-07 22:31 UTC, merged