Miners now have access to the flight room
Aurorastation/Aurora.3 pull request #16919
Opened 2023-07-30 04:00 UTC by RustingWithYou

Like it says in the title, miners now get access to the flight room. 

Why? They fly a shuttle, and it's the only place they can get the sensor readings in rounds without command or bridge crew.

2023-07-30 04:00 UTC, RustingWithYou commented
!review

2023-07-30 06:11 UTC, NonQueueingMatt approved these changes

2023-07-30 14:38 UTC, SleepyGemmy requested changes
this will give them access to the Canary since the shutter button is unrestricted. consider adding a navigations console to their refinery room instead, i.e.:
![image](https://github.com/Aurorastation/Aurora.3/assets/99297919/9327af9d-8cee-42d7-9229-2cdb5fe1c890)

otherwise, replace the shutters with an access restricted airlock, i.e.:
![image](https://github.com/Aurorastation/Aurora.3/assets/99297919/b8594b73-f2cb-4e7e-97cd-455ccea5bf39)

2023-07-30 22:26 UTC, RustingWithYou commented
The shutters have been replaced.

2023-07-31 18:51 UTC, SleepyGemmy approved these changes

2023-08-04 01:15 UTC, merged