Makes IV tank valves automatically open when strapping masks
Aurorastation/Aurora.3 pull request #16914
Opened 2023-07-29 16:26 UTC by nauticall

Currently, when putting an IV on a person in medical, you strap the mask onto them and _then_ turn on the valve as a second step. The problem is, in high-stress situations people might not immediately turn on the valve (or don't realize it's not on), _or_ inexperienced medical players don't realize they have to turn on said valve in order for it to function properly.

This PR makes it so putting a breath mask on a person (assuming it's connected to an IV drip) _automatically_ opens the associated tank. Sure, there can be some edge cases where you wouldn't want this to happen, but generally speaking this should save time, double-checks, and even lives.

2023-07-30 14:32 UTC, SleepyGemmy commented
!review

2023-07-30 19:02 UTC, NonQueueingMatt approved these changes

2023-07-30 19:16 UTC, SleepyGemmy requested changes

2023-07-30 19:16 UTC, SleepyGemmy commented on code/game/machinery/iv_drip.dm
> +	playsound(src, 'sound/effects/internals.ogg', 100)
this does not match the behaviour of back-worn internals, where turning off internals does not play a sound, iirc.
change it for the aforementioned or remove this addition.

2023-07-31 18:50 UTC, SleepyGemmy approved these changes

2023-08-01 18:02 UTC, merged