Potassium Chloride/Chlorophoride Adjustments
Aurorastation/Aurora.3 pull request #16938
Opened 2023-07-30 15:41 UTC by Doxxmedearly

Fixes #16910

CE_NOPULSE was not stopping the heart, it was lumped in with FAKEDEATH. Probably because Zombie Powder had CE_NOPULSE and was intended to fake death. Buuut since it gives the FAKEDEATH flag as it is... I just made sure that CE_NOPULSE stops the heart properly and removed it from zombie powder. It now actually stops the heart.

Someone mixed up the OD threshold vars for Sodium Chloride, so it would take 25u minimum and only affect after 20u was metabolized... at .02 a tick. Adjusted the values and made it metabolize faster, which means it takes a minute or two to affect the target and also will leave the body faster.

Also both of the toxins were causing damage. Given how serious stopping the heart is, this feels no longer necessary.

2023-07-30 15:41 UTC, Doxxmedearly commented
!review

2023-07-30 15:51 UTC, SleepyGemmy approved these changes

2023-07-30 15:53 UTC, NonQueueingMatt requested changes

2023-07-30 15:53 UTC, NonQueueingMatt commented on code/modules/organs/internal/heart.dm
> +		should_stop = owner.chem_effects[CE_NOPULSE]
```suggestion
		should_stop = should_stop || owner.chem_effects[CE_NOPULSE]
```

2023-07-31 18:18 UTC, NonQueueingMatt approved these changes

2023-08-04 00:41 UTC, merged