Adds Cytophenolate, a new immunosuppressant
Aurorastation/Aurora.3 pull request #16958
Opened 2023-07-31 15:23 UTC by nauticall

Adds cytophenolate to the game.

Cytophenolate (shorthand "cyto" or "cytoph") is a new immunosuppressant drug designed for mitigating rejection effects from organ transplantations.

It has several effects:

- If the organ donor and recipient are of the **same species but different blood types**, cytophenolate will gradually reduce the severity of organ rejection. Once near 0, it cures organ rejection entirely, switching the donated organ's blood type to that of the recipient.
- If the donor and recipient are of **different species**, cytophenolate will **never fully cure** the organ rejection. It will instead work to prevent symptoms of rejection from worsening and keep them at bay only while the drug is in their system. A patient receiving a foreign species organ will have to **permanently be on a cytophenolate prescription** until they can receive proper organs.
- **Cytophenolate is an actual immunosuppressant**. While in a patient's system, cytophenolate will **actively hinder any antibiotics**, like thetamycin, that are present. This makes fighting infections far harder while both cytophenolate and thetamycin are in the bloodstream.
- Overdoses cause weakness, dizziness and vomiting.

Cytophenolate can be mixed in chemistry with the following recipe:

**1u Ethanol, 1u Fluvectionem, 1u Sugar = 3 Units Cytophenolate**

2023-07-31 15:33 UTC, nauticall commented
!review

2023-08-01 16:38 UTC, SleepyGemmy approved these changes

2023-08-04 14:25 UTC, NonQueueingMatt requested changes

2023-08-04 14:25 UTC, NonQueueingMatt commented on code/modules/organs/organ.dm
> +		return
This shouldn't run if there's no rejection either

2023-08-04 14:26 UTC, NonQueueingMatt requested changes

2023-08-04 14:26 UTC, NonQueueingMatt commented on code/modules/organs/organ.dm
> +	if(!owner || !(CE_ANTIIMMUNE in owner.chem_effects))
```suggestion
	if(!owner || !(CE_ANTIIMMUNE in owner.chem_effects) || !rejecting)
```

2023-08-04 16:07 UTC, merged