Fixes Manifest Bulbs Showing White
Aurorastation/Aurora.3 pull request #17011
Opened 2023-08-03 19:26 UTC by 1Sparky1

Title.

2023-08-03 19:27 UTC, 1Sparky1 commented
!bugfix

2023-08-03 19:27 UTC, 1Sparky1 commented
!review

2023-08-03 19:29 UTC, NonQueueingMatt requested changes

2023-08-03 19:29 UTC, NonQueueingMatt commented on tgui/packages/tgui/interfaces/common/ManifestSection.tsx
> +                              .replace(/\s/g, '-')
sanitize this in the byond side (i think just doing `ckey()` is enough)

2023-08-03 19:31 UTC, NonQueueingMatt commented on tgui/packages/tgui/interfaces/common/ManifestSection.tsx
> +                              .replace(/\s/g, '-')
actually nevermind you use it later in the ui

2023-08-03 19:31 UTC, NonQueueingMatt approved these changes

2023-08-04 09:27 UTC, alsoandanswer approved these changes

2023-08-04 16:39 UTC, merged