Adds alt-click removal to chemistry machines
Aurorastation/Aurora.3 pull request #17052
Opened 2023-08-09 14:42 UTC by nauticall

What it says on the tin. Machines that handle or dispense reagents, like chemicals or drinks, such as ChemMasters, chem dispensers, soda/booze/coffee machines, etc, can now have their containers ejected from the machines using a simple **alt+click**. No more button-hunting on the GUI if you wanna be nice and :sparkles:efficient:sparkles:.

2023-08-09 15:02 UTC, SleepyGemmy commented
!review

2023-08-09 15:27 UTC, alsoandanswer approved these changes

2023-08-09 15:27 UTC, SleepyGemmy requested changes

2023-08-09 15:27 UTC, SleepyGemmy commented on code/modules/reagents/Chemistry-Machinery.dm
> +			beaker:loc = get_turf(src)
```suggestion
			beaker.loc = get_turf(src)
```

2023-08-09 22:50 UTC, SleepyGemmy approved these changes

2023-08-09 23:18 UTC, alsoandanswer approved these changes

2023-08-12 18:24 UTC, SleepyGemmy requested changes

2023-08-12 18:24 UTC, SleepyGemmy commented on code/modules/reagents/Chemistry-Machinery.dm
> +		if(Adjacent(usr))
```suggestion
		if(use_check_and_message(usr))
```

2023-08-12 18:24 UTC, SleepyGemmy commented on code/modules/reagents/Chemistry-Machinery.dm
> +	if(usr.Adjacent(src))
```suggestion
	if(use_check_and_message(usr))
```

2023-08-12 18:24 UTC, SleepyGemmy commented on code/modules/reagents/dispenser/dispenser2.dm
> +	if(usr.Adjacent(src))
```suggestion
	if(use_check_and_message(usr))
```

2023-08-12 18:25 UTC, SleepyGemmy commented on code/modules/reagents/dispenser/dispenser2.dm
> +		return TRUE
shouldn't this have an adjacency check like the chem master does?

2023-08-13 17:54 UTC, SleepyGemmy approved these changes

2023-08-14 16:45 UTC, merged