Body scanner bugfixes and alt clicking
Aurorastation/Aurora.3 pull request #17062
Opened 2023-08-11 14:40 UTC by nauticall

Fixes two bugs with body scanner print outs:
1. Body scanners displaying body temperature wrong (and showing something like -240 degrees C). Doesn't show Kelvin anymore because the Kelvin readout is useless and can confuse people.
2. Body scanners not showing shrapnel (or _any_ implant for that matter) on the printouts. Turns out the code saves all the implants/shrapnel to a list and then just... never printed out that list. Weird.

In addition, also tweaks some wording so that the paper printouts from the body scanners will mimic the GUI scans more accurately.

Also added alt-click functionality to the body scanner and sleeper, because we're on this path so we might as well double down.

2023-08-11 14:40 UTC, nauticall commented
!review

2023-08-11 17:56 UTC, SleepyGemmy commented on code/game/machinery/body_scanner.dm
> +				wounds += "has unknown object(s) present"
```suggestion
				wounds += "has unknown objects present"
```
plural as default here is fine.

2023-08-11 17:56 UTC, SleepyGemmy commented on code/game/machinery/body_scanner.dm
> +			for (var/atom/movable/I in e.implants)
```suggestion
			for(var/atom/movable/I in e.implants)
```

2023-08-11 17:56 UTC, SleepyGemmy commented on code/game/machinery/body_scanner.dm
> +			if (unk)
```suggestion
			if(unk)
```

2023-08-11 17:56 UTC, SleepyGemmy commented on code/game/machinery/body_scanner.dm
> +				wounds += "has unknown object(s) present:"
```suggestion
				wounds += "has unknown objects present:"
```
plural as default here is fine.

2023-08-12 07:26 UTC, nauticall commented
!bugfix

2023-08-12 11:28 UTC, alsoandanswer approved these changes

2023-08-12 13:14 UTC, SleepyGemmy approved these changes

2023-08-12 13:36 UTC, FluffyGhoster approved these changes

2023-08-12 17:36 UTC, NonQueueingMatt requested changes

2023-08-12 17:36 UTC, NonQueueingMatt commented on code/game/machinery/Sleeper.dm
> +	if(usr.Adjacent(src))
use_check_and_message

2023-08-12 17:36 UTC, NonQueueingMatt commented on code/game/machinery/body_scanner.dm
> +	if(usr.Adjacent(src))
use_check_and_message

2023-08-13 17:52 UTC, SleepyGemmy commented on code/game/machinery/Sleeper.dm
> +	if(usr.use_check_and_message(src))
```suggestion
	if(use_check_and_message(usr))
```

2023-08-13 17:52 UTC, SleepyGemmy commented on code/game/machinery/body_scanner.dm
> +	if(usr.use_check_and_message(src))
```suggestion
	if(use_check_and_message(usr))
```

2023-08-14 11:41 UTC, SleepyGemmy approved these changes

2023-08-14 17:41 UTC, merged