Medical Organisation Pack - Roller Bed Racks
Aurorastation/Aurora.3 pull request #17075
Opened 2023-08-14 14:12 UTC by 1Sparky1

Adds a storage rack structure for roller beds. Each rack can hold up to four beds.

WIP until mapping freeze is over. Reliant on #17074 anyway for colour scheme.

2023-08-14 14:13 UTC, 1Sparky1 commented
!wip

2023-09-08 20:29 UTC, 1Sparky1 commented
!review

2023-12-02 14:58 UTC, Arrow768 approved these changes

2023-12-05 11:44 UTC, NonQueueingMatt requested changes

2023-12-05 11:44 UTC, NonQueueingMatt commented on code/game/objects/structures/stool_bed_chair_nest/bed.dm
> +		LAZYADD(held, RB)
Held is not a lazylist

2023-12-05 11:44 UTC, NonQueueingMatt commented on code/game/objects/structures/stool_bed_chair_nest/bed.dm
> +/obj/structure/roller_rack/New()
Initialize()

2023-12-05 11:44 UTC, NonQueueingMatt commented on code/game/objects/structures/stool_bed_chair_nest/bed.dm
> +	var/list/held = list()
This list needs to be cleared and the contents qdeled in destroy()

2023-12-05 11:44 UTC, NonQueueingMatt commented on code/game/objects/structures/stool_bed_chair_nest/bed.dm
> +		LAZYADD(held, RB)
Held is not a lazylist

2023-12-05 11:44 UTC, NonQueueingMatt commented on code/game/objects/structures/stool_bed_chair_nest/bed.dm
> +	LAZYREMOVE(held, RB)
Held is not a lazylist

2023-12-05 11:44 UTC, NonQueueingMatt commented on code/game/objects/structures/stool_bed_chair_nest/bed.dm
> +	var/obj/item/roller/RB = held[LAZYLEN(held)]
Held is not a lazylist

2023-12-05 11:44 UTC, NonQueueingMatt commented on code/game/objects/structures/stool_bed_chair_nest/bed.dm
> +	if(!LAZYLEN(held))
Held is not a lazylist

2023-12-05 11:44 UTC, NonQueueingMatt commented on code/game/objects/structures/stool_bed_chair_nest/bed.dm
> +	desc = "[initial(desc)] \nIt is holding [LAZYLEN(held)] beds."
Held is not a lazylist

2023-12-26 17:06 UTC, NonQueueingMatt commented
Reopen when ready.

2023-12-26 17:06 UTC, closed without merging