Shuttle Manifest Program
Aurorastation/Aurora.3 pull request #17077
Opened 2023-08-14 16:52 UTC by CampinKiller24

Adds a program that shows the flight manifests of the Horizon's shuttles. Can be downloaded by all crew, but only those with Mining/Research/Command access can edit the entries. Entries can be easily moved between shuttles if people go from the Intrepid to the Spark, for example.

![image](https://github.com/Aurorastation/Aurora.3/assets/136183573/1e43e31e-723d-43a6-abd6-ba5132c6cb01)

![image](https://github.com/Aurorastation/Aurora.3/assets/136183573/ba6f874f-71b8-4ad9-b7c2-e3b6df1ca380)

![image](https://github.com/Aurorastation/Aurora.3/assets/136183573/36a10a66-f2c5-407e-9806-d42e1cf7d3a3)

2023-08-14 17:36 UTC, SleepyGemmy approved these changes

2023-08-19 20:44 UTC, NonQueueingMatt requested changes

2023-08-19 20:44 UTC, NonQueueingMatt commented on code/modules/modular_computers/file_system/programs/command/away_manifest.dm
> +			SStgui.update_uis(computer)
All you need to do is `return TRUE` here

2023-08-19 20:44 UTC, NonQueueingMatt commented on code/modules/modular_computers/file_system/programs/command/away_manifest.dm
> +			SStgui.update_uis(computer)
`return TRUE`

2023-08-19 20:44 UTC, NonQueueingMatt commented on code/modules/modular_computers/file_system/programs/command/away_manifest.dm
> +	var/mob/user = usr
Unnecessary, `usr` is already a mob

2023-08-19 20:44 UTC, NonQueueingMatt commented on code/modules/modular_computers/file_system/programs/command/away_manifest.dm
> +			SStgui.update_uis(computer)
`return TRUE`

2023-08-19 20:44 UTC, NonQueueingMatt commented on code/modules/modular_computers/file_system/programs/command/away_manifest.dm
> +			SStgui.update_uis(computer)
`return TRUE`

2023-08-19 20:44 UTC, NonQueueingMatt commented on code/modules/modular_computers/file_system/programs/command/away_manifest.dm
> +			SStgui.update_uis(computer)
Alternatively, if you don't need to return (like I think you do in some places), do `. = TRUE`

2023-08-19 20:44 UTC, NonQueueingMatt commented on tgui/packages/tgui/interfaces/AwayShuttleManifest.tsx
> +            <Button content="Add Entry" onClick={() => act('addentry')} />
You can just make this a green button with `icon="plus"` and remove the content, it would look better

2023-08-22 18:07 UTC, CampinKiller24 commented
!review

2023-08-24 19:06 UTC, NonQueueingMatt approved these changes

2023-09-02 00:05 UTC, merged