Bulwark punch knockback bugfix and attack message tweaks
Aurorastation/Aurora.3 pull request #17093
Opened 2023-08-15 23:38 UTC by Herpetophilia

The bulwark punch knockback has been fixed to actually apply the WEAKEN status effect as was originally intended. The code used for this was old and did not work properly. The knockback also now only applies to things smaller than a Bulwark, meaning you can no longer rocket-punch yourself and other Bulwarks. 

Some attack messages and descriptions have also been changed to make more sense.

This is my first PR, please don't be mean

2023-08-15 23:40 UTC, Herpetophilia commented
!review

2023-08-15 23:57 UTC, Generalcamo requested changes

2023-08-15 23:57 UTC, Generalcamo commented on code/modules/mob/living/carbon/human/species/species_attack.dm
> +			user.visible_message(SPAN_DANGER("[user] sends [target] flying with the impact!"))
```suggestion
			user.visible_message(SPAN_DANGER("[user] sends \the [target] flying with the impact!"))
```

2023-08-16 03:02 UTC, Generalcamo approved these changes

2023-08-16 19:04 UTC, Herpetophilia commented
!bugfix

2023-08-16 20:41 UTC, SleepyGemmy commented on html/changelogs/Herpetophilia-bulwarkfix.yml
> +  - bugfix: "Makes the bulwark punch knockback apply the WEAKEN effect as intended"
```suggestion
  - bugfix: "Makes the bulwark punch knockback apply the WEAKEN effect as intended."
```

2023-08-16 20:41 UTC, SleepyGemmy commented on html/changelogs/Herpetophilia-bulwarkfix.yml
> +  - tweak: "Adjusts the attack messages of the bulwark punch"
```suggestion
  - tweak: "Adjusts the attack messages of the bulwark punch".
```

2023-08-16 20:43 UTC, SleepyGemmy approved these changes

2023-08-17 10:19 UTC, Generalcamo requested changes

2023-08-17 10:19 UTC, Generalcamo commented on html/changelogs/Herpetophilia-bulwarkfix.yml
> +  - tweak: "Adjusts the attack messages of the bulwark punch".
```suggestion
  - tweak: "Adjusts the attack messages of the bulwark punch."

```

2023-08-17 17:38 UTC, SleepyGemmy approved these changes

2023-08-20 19:09 UTC, merged