Ve'katak Phalanx Uniforms (feat. EPMC)
Aurorastation/Aurora.3 pull request #17114
Opened 2023-08-19 03:28 UTC by RustingWithYou

Adds a new security uniform for the Ve'katak Phalanx, at the request of the Vaurca lore team. Recolors of the various medical uniforms in both Ve'katak and EPMC colors (for those that didn't already have them) have also been added and made available in loadout.
![image](https://github.com/Aurorastation/Aurora.3/assets/63625389/a6173cb4-a97f-4fd0-8909-868c1a314405)
_Left to right: Ve'katak medical intern, psychiatrist, pharmacist, surgeon, physician and security officer/first responder_

![image](https://github.com/Aurorastation/Aurora.3/assets/63625389/b777c247-d6af-442b-96fa-d53101400f58)
_Left to right: EPMC medical intern, psychiatrist, pharmacist, surgeon and physician_

2023-08-19 03:29 UTC, RustingWithYou commented
!review

2023-08-19 03:58 UTC, alsoandanswer requested changes
I need you to change the colors for the Ve'katak uniforms. They look identical to Zavodskoi.

2023-08-19 05:26 UTC, kyres1 commented
Remove the camouflaged uniform please. As explained on discord, there is no reason for a corporation to possess camouflaged uniformed security in all technicality. It's too adjacent to military use cases that ultimately security does not fall under nor represent.

2023-08-19 05:27 UTC, kyres1 requested changes
Remove the camouflaged uniform please. As explained on discord, there is no reason for a corporation to possess camouflaged uniformed security in all technicality. It's too adjacent to military use cases that ultimately security does not fall under nor represent.

2023-08-19 10:35 UTC, SleepyGemmy commented on code/modules/clothing/factions/pmcg.dm
> +	desc = "A uniform worn by medical staff of the Ve'katak Phalanx, a Vaurca-run PMCG subsidiary. It is simple and utilitarian in its design, with the only embellishment being two red stripes on the sh
```suggestion
	name = "\improper Ve'katak Phalanx uniform"
	desc = "A uniform worn by medical staff of the Ve'katak Phalanx, a Vaurca-run PMCG subsidiary. It is simple and utilitarian in its design, with the only embellishment being two red stripes on the shoulders."
	icon_state = "phalanx_medical"
	item_state = "phalanx_medical"
```

2023-08-20 05:42 UTC, RustingWithYou commented
> I need you to change the colors for the Ve'katak uniforms. They look identical to Zavodskoi.

The sprites have been changed to be more distinct from other corporations, as well as being identifiably PMCG.

2023-08-20 09:42 UTC, alsoandanswer approved these changes

2023-08-20 11:43 UTC, SleepyGemmy commented on code/modules/client/preference_setup/loadout/items/factions.dm
> +
```suggestion
```

2023-08-20 11:43 UTC, SleepyGemmy approved these changes

2023-08-20 13:05 UTC, alsoandanswer requested changes
medical is missing the PMCG highlights as on the sec uniform as according to icondiffbot

2023-08-20 23:26 UTC, RustingWithYou commented
> medical is missing the PMCG highlights as on the sec uniform as according to icondiffbot

whoops, forgot to add them back when doing the color switch. should be fixed now

2023-08-21 01:19 UTC, alsoandanswer commented
Both medical and security uniforms missing leg cuffs, please fix, thanks.

2023-08-21 06:12 UTC, alsoandanswer approved these changes
Thank you, fine work.

2023-08-22 15:04 UTC, merged