Elevator Lift Panel TGUI
Aurorastation/Aurora.3 pull request #17157
Opened 2023-08-27 12:54 UTC by Geevies

* Converted the elevator lift panel to TGUI.

![image](https://github.com/Aurorastation/Aurora.3/assets/22774890/58aa3abf-320b-4d3f-9bfb-4d04d08a4aa8)

https://github.com/Aurorastation/Aurora.3/assets/22774890/93ed5f80-a8cb-4343-b054-b7d21586e589

2023-08-27 12:54 UTC, Geevies commented
!review

2023-08-27 14:54 UTC, NonQueueingMatt requested changes

2023-08-27 14:54 UTC, NonQueueingMatt commented on code/modules/turbolift/turbolift_console.dm
> +		pressed(usr)
return TRUE on a successful click

2023-09-02 00:51 UTC, alsoandanswer approved these changes

2023-09-02 10:16 UTC, NonQueueingMatt approved these changes

2023-09-02 12:14 UTC, merged