Vaurca Augments & Aut'akh Loadout Tweaks
Aurorastation/Aurora.3 pull request #17193
Opened 2023-08-31 05:45 UTC by RustingWithYou

Adds two new augments for Vaurca, ~~shamelessly copying~~ based on existing Aut'akh augments - a stun weapon for security Warriors and a health analyser for medical.

Tweaks the cost of some species-locked augments to be more in line with the cheaper Aut'akh ones. Aut'akh augments are now culture restricted to Aut'akh now that it's an actual culture. 

The Vaurca combitool is now restricted to engineering and machinist, and is available to warriors in those roles. I wanted to replace it with a mechanical limb similar to the Aut'akh ones, but Bulwarks don't have mechanical limbs.

2023-08-31 05:45 UTC, RustingWithYou commented
!review

2023-09-01 18:35 UTC, Arrow768 requested changes

2023-09-01 18:35 UTC, Arrow768 commented on code/modules/client/preference_setup/loadout/items/xeno/vaurca.dm
> -	cost = 5
Undocumented change. Revert that.

2023-09-01 18:35 UTC, Arrow768 commented on code/modules/client/preference_setup/loadout/items/augments.dm
> -	cost = 5
Undocumented change. Revert it.

2023-09-09 12:21 UTC, NonQueueingMatt approved these changes

2023-09-09 12:21 UTC, NonQueueingMatt commented on code/modules/organs/subtypes/vaurca.dm
> +	action_button_name = "ACtivate Integrated Biological Analyser"
```suggestion
	action_button_name = "Activate Integrated Biological Analyser"
```

2023-09-12 22:14 UTC, DreamySkrell approved these changes

2023-09-13 15:19 UTC, merged