Button overlay
Aurorastation/Aurora.3 pull request #17239
Opened 2023-09-05 01:52 UTC by Eyeveri

Adds accented buttons to the Suit jacket, blazer and long blazer, to add more depth to the loadout option(s).

2023-09-05 01:54 UTC, Eyeveri commented
!wip

2023-09-05 01:55 UTC, Eyeveri commented
There is a small bug that @1Sparky1 will have to help me with, before this can be merged/finished. But the work is 90% done.

2023-09-05 10:47 UTC, Generalcamo requested changes
You should remove the old, now outdated icons, rather than keeping orphaned unused icons in the files.

2023-09-05 19:00 UTC, Eyeveri commented
> 

I don't follow, the only icons being used are the ones that are being overlayed. Wezzy and I manually built the file for it.

2023-09-07 21:03 UTC, Eyeveri commented
@1Sparky1 fixed the bug! Yay!

!review

2023-09-07 21:04 UTC, Generalcamo approved these changes
Code looks fine, old icons are gone.

2023-09-07 21:04 UTC, Generalcamo commented on html/changelogs/EyeveriChangelog.yml
> +  - rscadd: "Adds"
You missed this though.

2023-09-07 21:04 UTC, Eyeveri commented on html/changelogs/EyeveriChangelog.yml
> +  - rscadd: "Adds"
Yeahhhh... Just saw that lmao

2023-09-07 21:05 UTC, Eyeveri commented on html/changelogs/EyeveriChangelog.yml
> +  - rscadd: "Adds"
I got a little excited. Pushed the fix!

2023-09-07 21:29 UTC, NonQueueingMatt approved these changes

2023-09-10 03:20 UTC, FluffyGhoster approved these changes

2023-09-10 22:06 UTC, merged