Removes computer idle & airlock 'failure-to-close' sounds
Aurorastation/Aurora.3 pull request #17261
Opened 2023-09-07 16:24 UTC by nauticall

Soul crushing. Removes the idle sound from computers (that annoying buzzing white noise that plays) and the beeping noise that plays when standing in an airlock for too long. Oh the humanity!

Sounds themselves are still in the files, in case they want to be reimplemented for some other malicious reason.

2023-09-07 16:24 UTC, nauticall commented
!review

2023-09-07 16:29 UTC, Greenjoe12345 commented
IMO maybe the airlock failure to close sound could be kept, but make the time between them quite a bit longer?

2023-09-07 17:14 UTC, NonQueueingMatt requested changes

2023-09-07 17:14 UTC, NonQueueingMatt commented on code/datums/looping_sounds/machinery_sounds.dm
>  	mid_length = 1.8 SECONDS
this needs to go too, and so do the sounds if you're removing their only usage

2023-09-07 17:39 UTC, SleepyGemmy commented on code/game/machinery/doors/airlock.dm
> -						next_beep_at = world.time + SecondsToTicks(10)
why? this is only used for secure airlocks.

2023-09-07 17:51 UTC, alsoandanswer commented
I think these sounds are fine, dont need to remove them

2023-09-07 18:55 UTC, atteria commented
> I think these sounds are fine, dont need to remove them

imo, both sounds are annoying and deserve, at minimum, replacement with tweaks to how they're played. I think removal is also a good option.

2023-09-07 21:22 UTC, DreamySkrell commented
I don't care about computer sounds, but.

I think airlock sounds should stay. They are supposed to be annoying - like the whole point of airlocks is to keep air in, and they can't do that if they are open. We are on a ship, so the sound is a reminder to keep the airlocks closed. I'm fine with the delay or whatever being changed though.

2023-09-08 09:10 UTC, nauticall commented
changes addressed. readded the airlock failure-to-close but made it take 20(ish) seconds to beep rather than 10, doubling it

2023-09-08 10:01 UTC, NonQueueingMatt approved these changes

2023-09-08 13:00 UTC, DreamySkrell approved these changes

2023-09-08 20:15 UTC, SleepyGemmy approved these changes

2023-09-10 03:19 UTC, FluffyGhoster approved these changes

2023-09-10 17:08 UTC, merged