Tajara loadout expansion: far from home edition
Aurorastation/Aurora.3 pull request #17270
Opened 2023-09-08 00:59 UTC by Alberyk

This pr adds some new loadout and chaplain stuff:
-ma'ta'ke clothing, altar and banners in the loadout
-new nullrod options for chaplains
-tajaran earrings, new accessories, a ring, and wrist watches

2023-09-08 01:26 UTC, Generalcamo reviewed
Primarily grammar, though one possible code improvement is noted.

2023-09-08 01:26 UTC, Generalcamo commented on code/game/objects/items/weapons/chaplain_items.dm
> +/obj/item/nullrod/azubarre
It may be a good idea to have `isFlameSource()` return lit for this item, so it can light stuff on fire.

2023-09-08 01:26 UTC, Generalcamo commented on code/modules/clothing/rings/xeno/tajara.dm
> +	desc = "A cheap, popular metal ring commonly used by female Tajara.."
```suggestion
	desc = "A cheap, popular metal ring commonly used by female Tajara."
```

2023-09-08 01:26 UTC, Generalcamo commented on code/modules/clothing/under/accessories/xeno/tajara.dm
> +	name = "president hadii badge"
```suggestion
	name = "president Hadii badge"
```

2023-09-08 01:26 UTC, Generalcamo commented on code/modules/clothing/under/accessories/xeno/tajara.dm
> +	desc = "A badge with the image of President Hadii. This one is a mudane one, likely issued during a public event or to celebrate a holiday."
```suggestion
	desc = "A badge with the image of President Hadii. This is a mudane one, likely issued during a public event or to celebrate a holiday."
```

2023-09-08 01:26 UTC, Generalcamo commented on code/modules/clothing/under/accessories/xeno/tajara.dm
> +	desc = "A badge with the image of President Hadii. This one is a very common one, likely sold to tourists and in newsstands."
```suggestion
	desc = "A badge with the image of President Hadii. This is a very common one, likely sold to tourists and in newsstands."
```
Redundant "one"

2023-09-08 01:26 UTC, Generalcamo commented on code/modules/clothing/under/accessories/xeno/tajara.dm
> +	desc = "A necklace made of Ras'val clams's pearls."
```suggestion
	desc = "A necklace made of Ras'val clam pearls."
```

2023-09-08 01:35 UTC, Generalcamo approved these changes

2023-09-08 19:54 UTC, NonQueueingMatt submitted a review, later dismissed

2023-09-08 19:54 UTC, NonQueueingMatt commented on code/game/objects/items/weapons/chaplain_items.dm
> +	if((user == usr && (!use_check(user))) && (user.contents.Find(src) || in_range(src, user)))
User here can't really not be the proc user, I think. Should also use_check_and_message this

2023-09-08 19:54 UTC, NonQueueingMatt commented on code/game/objects/items/weapons/chaplain_items.dm
> +		return TRUE
use_check_and_message

2023-09-15 19:00 UTC, alsoandanswer requested changes
New sprite additions should be in contained sprites either in tajara_items.dmi or in their own files instead. For example the new accessories should be in a new file called '/icons/obj/clothing/accessory/tajara.dmi'

2023-09-15 19:02 UTC, alsoandanswer commented
Also you need to fix [13:54:05]Invalid type in map. /obj/item/nullrod/obsidianshards

2023-09-21 06:17 UTC, alsoandanswer approved these changes
Yeah, looks good. Thanks for making them contained sprites

2023-09-21 06:22 UTC, FluffyGhoster approved these changes

2023-09-21 10:58 UTC, merged