Kitchen Resprites
Aurorastation/Aurora.3 pull request #17311
Opened 2023-09-10 21:22 UTC by alsoandanswer

![dreamseeker_qiQE9bs2i4](https://github.com/Aurorastation/Aurora.3/assets/42310821/f8755ddb-9de9-4df8-a795-1c95e7fe07c4)
![dreamseeker_xN1dibd6DI](https://github.com/Aurorastation/Aurora.3/assets/42310821/3f2e51e9-0aeb-4979-8c94-914737521238)

2023-09-10 21:23 UTC, alsoandanswer commented
!review

2023-09-11 00:23 UTC, atteria commented
The chopping board resprite no longer looks like a chopping board, and instead is just the ugly tg wood texture stretched out, which Aurora doesn't need more of. This is the opposite of a sprite that clearly communicates what it is supposed to be.

The grill resprite is using the plastic palette for some reason, when it's a grill. The pasted tg kitchen dials look clumsy, inconsistent with the kitchen resprite from this year, and not like an actual grill. If you want to paste dials, use the knobs on my stove sprites.

Please reference what a thing is intended to look like rather than tg 50s retrofuture sprites.

2023-09-11 14:27 UTC, alsoandanswer commented
Alright, I've made some changes, hopefully this will fix them

> The chopping board resprite no longer looks like a chopping board, and instead is just the ugly tg wood texture stretched out, which Aurora doesn't need more of. This is the opposite of a sprite that clearly communicates what it is supposed to be.

<img width="53" alt="dreammaker_6buM2cQNaz" src="https://github.com/Aurorastation/Aurora.3/assets/42310821/ade2ac26-7f17-4f4c-ae5a-7746634a973b">

> The grill resprite is using the plastic palette for some reason, when it's a grill. The pasted tg kitchen dials look clumsy, inconsistent with the kitchen resprite from this year, and not like an actual grill. If you want to paste dials, use the knobs on my stove sprites.

<img width="331" alt="dreammaker_jTuVFUwWvn" src="https://github.com/Aurorastation/Aurora.3/assets/42310821/748e69cd-09a2-439b-871d-ef4f07c63b9e">
Here's the new kitchen appliance sprites - I've tweaked them accordingly.
Only real point of contention for me is the knobs, which I've changed, the current ones are too unreadable.
(ironically, using the current knobs is closer to what /tg/ uses currently)
<img width="328" alt="dreammaker_0nmC5QBh67" src="https://github.com/Aurorastation/Aurora.3/assets/42310821/e750fd4f-8202-4a3a-9cc2-b661f5bdc723">

> The oven dish no longer looks like a commercial bread pan, and confusingly like a tray.
>

<img width="53" alt="dreammaker_FtGYRsbHMl" src="https://github.com/Aurorastation/Aurora.3/assets/42310821/7db42578-5ac1-4323-9c41-bd6e4a2cf512">

2023-09-11 17:56 UTC, niennab commented
Didn't we already talk about no wholesale respriting of recent assets based on TG sprites?

2023-09-12 03:05 UTC, alsoandanswer commented
They've been redone again.

2023-09-12 15:45 UTC, Zelmana commented
I like some of these. My only complaint is the huge wine bottle. It's as tall as a character sprite! The largest bottles, Imperials, are pretty huge but IDK if they're that big....

2023-09-12 16:10 UTC, alsoandanswer commented
> I like some of these. My only complaint is the huge wine bottle. It's as tall as a character sprite! The largest bottles, Imperials, are pretty huge but IDK if they're that big....

The champagne bottle was resprited in a different PR that was already merged

2023-09-12 16:27 UTC, FluffyGhoster commented on code/modules/cooking/machinery/cooking_machines/container.dm
> +	..()
```suggestion
	. = ..()
```

2023-09-12 16:27 UTC, FluffyGhoster commented on code/modules/cooking/machinery/cooking_machines/container.dm
> +	..()
```suggestion
	. = ..()
```

2023-09-12 16:27 UTC, FluffyGhoster commented on code/modules/cooking/machinery/cooking_machines/container.dm
> +	..()
```suggestion
	. = ..()
```

2023-09-12 16:27 UTC, FluffyGhoster commented on code/modules/cooking/machinery/cooking_machines/container.dm
> +	..()
```suggestion
	. = ..()
```

2023-09-13 19:49 UTC, niennab requested changes
grill_on and cereal_on have frames of other appliances. Refer to IconDiffBot2: icons/obj/cooking_machines.dmi (0)

I still don't agree with overhauling and downgrading atteria's work but can we at least get rid of the weirdly huge dials?

2023-09-14 10:26 UTC, NonQueueingMatt submitted a review, later dismissed
I don't like this tendency towards retrofuture beige for appliance colour - we're not retrofuture. Remove it from the machines that use it, use pure white or black or whatever else doesn't look like a 50s appliance.

2023-09-15 13:43 UTC, alsoandanswer commented
> I don't like this tendency towards retrofuture beige for appliance colour - we're not retrofuture. Remove it from the machines that use it, use pure white or black or whatever else doesn't look like a 50s appliance.

Addressed, they all are using a metallic shine. There is no longer any beige at all

2023-09-19 09:57 UTC, NonQueueingMatt approved these changes

2023-09-19 12:18 UTC, merged