Tarwa Conglomerate Diona Limbs
Aurorastation/Aurora.3 pull request #17316
Opened 2023-09-11 04:43 UTC by RustingWithYou

Tarwa Conglomerate pirates now have a chance to spawn with nymph limbs.

Sometimes when an arm or leg nymphizes, the child limb doesn't nymphize correctly and just disappears. I couldn't find a way to prevent this from happening, but the player can detach and reattach the limb to fix it, which has been mentioned in the welcome message.

2023-09-11 04:43 UTC, RustingWithYou commented
!review

2023-09-11 07:27 UTC, DreamySkrell commented
I do not think it should be done like this / at all. It means consistent characters sometimes spawn with the diona limbs, sometimes not, with no control if they should/shouldn't.

The best way would be to allow picking diona (or robotic) limbs to the character creator thingy you see when spawning as off-ship char. But that would be a big addition that would not affect just this Tarwa ship.

2023-09-13 10:38 UTC, NonQueueingMatt requested changes

2023-09-13 10:38 UTC, NonQueueingMatt commented on maps/away/away_site/unathi_pirate/tarwa/unathi_pirate_tarwa_ghostroles.dm
> +			continue
You have an issue here with the loop variable `name` overlapping with the ghostspawner `name` variable.

2023-09-14 00:49 UTC, RustingWithYou commented
> I do not think it should be done like this / at all. It means consistent characters sometimes spawn with the diona limbs, sometimes not, with no control if they should/shouldn't.
> 
> The best way would be to allow picking diona (or robotic) limbs to the character creator thingy you see when spawning as off-ship char. But that would be a big addition that would not affect just this Tarwa ship.

I agree, but that is a lot more work and I don't know how to do it. Overall it's a fairly minor blow to consistency while adding some more of the faction's specific thing to its ghostrole IMO.

2023-09-19 10:40 UTC, NonQueueingMatt approved these changes

2023-09-26 04:34 UTC, FluffyGhoster approved these changes

2023-09-26 19:36 UTC, merged