Much Ado About the Bagginses
Aurorastation/Aurora.3 pull request #17329
Opened 2023-09-12 16:12 UTC by alsoandanswer

![dreamseeker_uSLitMhe1a](https://github.com/Aurorastation/Aurora.3/assets/42310821/d169cb52-14a1-47d5-a332-45e384ad2357)

  - imageadd: "Adds a new animation for using storage objects."
  - rscadd: "Sorts generic bags, new sprites (plant bag, sheet bag, mining satchel, chem bag)."
  - tweak: "Removes self message for putting things into storage. (You put the X into Y message)."

2023-09-12 16:22 UTC, FluffyGhoster commented on code/game/objects/items/weapons/storage/storage.dm
> +	var/animated = TRUE /// whether or not we should have those cute little animations
```suggestion
	///Boolean, whether or not we should have those cute little animations
	var/animated = TRUE
```

2023-09-12 22:09 UTC, DreamySkrell requested changes

2023-09-12 22:09 UTC, DreamySkrell commented on code/game/objects/items/weapons/storage/bags.dm
> +	desc = "For storing your stems, seeds, buds, and any other euphemism for marijuana."
Should references Ambrosia or whatever instead.

2023-09-12 22:09 UTC, DreamySkrell commented on code/game/objects/items/weapons/storage/storage.dm
> +	///Boolean, whether or not we should have those cute little animations
What animations? This should explain what is the "animation" in this context. That being the item taking-out or putting-in animation (?).

2023-09-12 22:10 UTC, DreamySkrell commented
Also, I think the PR title should have an actually descriptive name. I read "Much Ado About the Bagginses" and I thought we're adding Lord of the Rings or whatever.

Should be titled "Storage object animation" or something, idk.

2023-09-12 23:29 UTC, Generalcamo commented on code/game/objects/items/weapons/storage/storage.dm
> +					M.show_message(SPAN_NOTICE("\The [user] puts [W] into [src]."))
```suggestion
					M.show_message(SPAN_NOTICE("\The [user] puts [W] into [src]."))
```
This feels like it should be a visible message sent to everyone. Then we can have blind and self-checking.

2023-09-13 03:28 UTC, Generalcamo requested changes

2023-09-13 03:28 UTC, Generalcamo commented on code/game/objects/items/weapons/storage/bags.dm
> +	desc = "For storing your stems, seeds, buds, and any other euphemism illicit substances."
```suggestion
	desc = "For storing your stems, seeds, buds, and any other illicit substances."
```

2023-09-13 16:59 UTC, FluffyGhoster approved these changes

2023-09-13 18:49 UTC, SleepyGemmy approved these changes

2023-09-16 11:01 UTC, merged