crisp expansion
Aurorastation/Aurora.3 pull request #17343
Opened 2023-09-14 23:52 UTC by Greenjoe12345

This adds a number of types of crisp flavours, along with multipack bags containing multiple packets of crisps.
The other types are not yet in vending machines, as I've heard about a rework of vending machines that will split out things a bit, and they could be added there.
The multipacks I would want to be added to the trader/warehouse/third party cargo hold loot, (along with stores on planetside places like Konyang when we are visiting those), as well as orderable from cargo? but that's config stuff so I can't touch that.
The flavours are:
Salted (red)
Cucumber (green)
Chicken (blue)
Dirtberry (brown)
and Phoron (actually shrimp cocktail, in a pink packet)
each of these has a multipack, and there is a special variety multipack containing salted, cucumber and chicken flavours.
![image](https://github.com/Aurorastation/Aurora.3/assets/33647525/c55ecf4a-ccff-46b5-a290-469fc8130e60)

2023-09-14 23:52 UTC, Greenjoe12345 commented
!review

2023-09-15 03:19 UTC, Generalcamo commented on code/modules/reagents/reagent_containers/food/snacks.dm
> +	desc = "Getmore potato crisps. Not actually crisps, these are instead flash-fried wafers of potato paste. Delicious!"
Quick note: In American English, this is the definition of crisps.

2023-09-16 02:04 UTC, alsoandanswer requested changes
Please, just keep them called chips. This feels like a "changing them for the sake of changing them" They are already called chips in the files.

2023-09-16 02:14 UTC, Generalcamo requested changes
If you are going to rename them, change the paths too. Otherwise this will cause needless confusion for mappers, coders, and administrators.

2023-09-21 17:04 UTC, Greenjoe12345 commented
> Please, just keep them called chips. This feels like a "changing them for the sake of changing them" They are already called chips in the files.

As generalcamo said, they are seemingly actually crisps

> If you are going to rename them, change the paths too. Otherwise this will cause needless confusion for mappers, coders, and administrators.

The paths are far too much of a complex thing for me to change

2023-09-21 18:12 UTC, Greenjoe12345 commented
adjusting it now

2023-09-22 06:31 UTC, DreamySkrell approved these changes

2023-09-24 23:27 UTC, Greenjoe12345 commented
fixing this AGAIN. that fucking sorting pr

2023-09-24 23:57 UTC, Greenjoe12345 commented
a

2023-09-24 23:59 UTC, Greenjoe12345 commented
Fixed again.

2023-09-28 11:14 UTC, alsoandanswer approved these changes

2023-10-01 15:53 UTC, merged