Adds C'thuric psionic receiver at no loadout cost
Aurorastation/Aurora.3 pull request #17380
Opened 2023-09-20 03:35 UTC by feartheblackout

Title. I asked Connor over Discord about adding a variation of the receiver that wouldn't cost anything for C'thur and he was okay with it.

2023-09-20 03:35 UTC, feartheblackout commented
!review

2023-09-20 08:14 UTC, DreamySkrell approved these changes

2023-09-20 11:38 UTC, NonQueueingMatt approved these changes

2023-09-20 18:51 UTC, SleepyGemmy approved these changes

2023-09-21 01:58 UTC, FluffyGhoster approved these changes

2023-09-22 20:21 UTC, Arrow768 requested changes

2023-09-22 20:21 UTC, Arrow768 commented on code/modules/client/preference_setup/loadout/items/xeno/vaurca.dm
> +	cost = 0
Items must have a loadout cost

2023-09-22 21:23 UTC, closed without merging