HoS skrellmet
Aurorastation/Aurora.3 pull request #17472
Opened 2023-09-28 15:51 UTC by Snowy1237

Adds a Head of Security version of the skrellmet to the loadout.

I am atrocious at this, I hope I did not break anything.

2023-09-29 13:41 UTC, alsoandanswer requested changes
Needs to be species restricted to skrell-only

2023-09-29 13:42 UTC, Alberyk approved these changes

2023-09-29 15:03 UTC, Snowy1237 commented
> Needs to be species restricted to skrell-only

The original skrellmet is not restricted to be worn only by skrell, and the loadout entry is already restricted to skrell only.

2023-09-29 17:08 UTC, alsoandanswer approved these changes

2023-10-02 04:42 UTC, FluffyGhoster approved these changes

2023-10-03 20:49 UTC, merged