Adds TGUI say and TGUI input.
Aurorastation/Aurora.3 pull request #17471
Opened 2023-09-28 13:46 UTC by NonQueueingMatt

opening for diff

2023-09-29 04:45 UTC, alsoandanswer commented
holy mother of based

2023-09-29 20:23 UTC, NonQueueingMatt commented
!review

2023-09-29 21:30 UTC, Generalcamo requested changes
First pass review

2023-09-29 21:30 UTC, Generalcamo commented on code/_helpers/text.dm
> +	* * allow_numbers - allows numbers and common special characters - used for silicon/other weird things names
I don't believe DMDoc allows tabs here

2023-09-29 21:30 UTC, Generalcamo commented on code/datums/mind.dm
> +		var/sure = tgui_input_list(usr, "Limitless is INTENTIONALLY STUPIDLY OVERPOWERED! YOU SHOULD NOT BE USING THIS WITHOUT KNOWING EXACTLY WHAT YOU'RE DOING!", \
This should probably be `tgui_alert`

2023-09-29 21:30 UTC, Generalcamo commented on code/game/objects/structures/watercloset.dm
> +	var/N = tgui_input_list(usr, "Set thmount to transfer from this.", "[src]", possible_transfer_amounts)
```suggestion
	var/N = tgui_input_list(usr, "Set the amount to transfer from this.", "[src]", possible_transfer_amounts)
```

2023-09-29 21:31 UTC, Arrow768 commented on code/modules/mob/living/carbon/human/species/species.dm
> +	var/list/possible_speech_bubble_types = list("default")
SQL query to update that?

2023-09-29 21:48 UTC, NonQueueingMatt commented on code/_helpers/text.dm
> +	* * allow_numbers - allows numbers and common special characters - used for silicon/other weird things names
the linter disagrees

2023-10-01 13:03 UTC, alsoandanswer approved these changes

2023-10-02 00:24 UTC, Generalcamo approved these changes

2023-10-02 06:50 UTC, DreamySkrell approved these changes

2023-10-09 21:00 UTC, Forktress commented
Prosthesis selection currently asks which limb to change then once selected, no further options appear meaning amputations and prosthesis cannot be added to characters.

2023-10-10 09:29 UTC, NonQueueingMatt commented
> Prosthesis selection currently asks which limb to change then once selected, no further options appear meaning amputations and prosthesis cannot be added to characters.

Fixed

2023-10-11 21:22 UTC, Arrow768 approved these changes

2023-10-11 21:26 UTC, merged