freebooter kitchen additions
Aurorastation/Aurora.3 pull request #17482
Opened 2023-09-29 23:59 UTC by RustingWithYou

The Freebooter ship kitchen now has salt, pepper and space spice so they can do more cooking. Also fixes some broken turf icon states because they bugged me.

2023-09-30 00:00 UTC, RustingWithYou commented
!review

2023-09-30 00:00 UTC, RustingWithYou commented
!review

2023-10-02 06:46 UTC, DreamySkrell requested changes

2023-10-02 06:46 UTC, DreamySkrell commented on maps/away/ships/freebooter/freebooter_ship.dmm
> -	icon_state = "dmg2"
![image](https://github.com/Aurorastation/Aurora.3/assets/107256943/996279bb-64df-4774-935b-cdaa74079554)

Floor damage was changed from being icon_states to decals - use the decals above to add back the damaged feel to the floors that had it before.

2023-12-05 11:47 UTC, NonQueueingMatt commented
Reopen when changes required are resolved

2023-12-05 11:47 UTC, closed without merging