Ruined COC Relay Station
Aurorastation/Aurora.3 pull request #17485
Opened 2023-09-30 08:59 UTC by RustingWithYou

Adds a new asteroid ruin. It's a COC relay station. Map done by steviii so if there are any issues it's their fault.

2023-09-30 09:00 UTC, RustingWithYou commented
!review

2023-10-02 06:32 UTC, DreamySkrell commented
The mapdiffbot2 is really dumb lately - please show some screenshots of this map.

2023-10-03 04:04 UTC, RustingWithYou commented
> The mapdiffbot2 is really dumb lately - please show some screenshots of this map.

![image](https://github.com/Aurorastation/Aurora.3/assets/63625389/4028d6a1-8115-4d49-9806-1d613904c1a7)

2023-10-03 12:55 UTC, DreamySkrell requested changes

2023-10-03 12:55 UTC, DreamySkrell commented on maps/random_ruins/exoplanets/asteroid/coalition_base/coalition_base.dm
> +    description = "hehehe cock base"
hehehe cock base

2023-10-03 23:50 UTC, RustingWithYou commented on maps/random_ruins/exoplanets/asteroid/coalition_base/coalition_base.dm
> +    description = "hehehe cock base"
fuck i forgot to change this

2023-10-04 21:59 UTC, TheDanseMacabre commented
could be worth using random gun spawners instead of spawning the same guns every time, the civilian gun spawner could be a good option

2023-10-05 07:35 UTC, DreamySkrell approved these changes

2023-10-05 10:14 UTC, NonQueueingMatt approved these changes

2023-10-05 21:08 UTC, merged