Konyang: Point Verdant Sake Brewery
Aurorastation/Aurora.3 pull request #17502
Opened 2023-10-02 18:22 UTC by DreamySkrell

![image](https://github.com/Aurorastation/Aurora.3/assets/107256943/13944266-df31-4f25-8dbb-a6aead60e3a0)

![image](https://github.com/Aurorastation/Aurora.3/assets/107256943/b296d39c-cb64-4549-b2c9-a1398d759517)

2023-10-02 18:22 UTC, DreamySkrell commented
!review

2023-10-03 02:49 UTC, FluffyGhoster approved these changes

2023-10-05 03:02 UTC, Alberyk requested changes

2023-10-05 03:02 UTC, Alberyk commented on code/game/objects/random/food.dm
> +		/obj/structure/reagent_dispensers/keg/sake = 0.5,
```suggestion
		/obj/structure/reagent_dispensers/keg/sake = 0.5
```

2023-10-05 14:50 UTC, merged