tweaks mindshield text
Aurorastation/Aurora.3 pull request #17528
Opened 2023-10-05 08:30 UTC by alsoandanswer

should be in line with the old loyalty implant now

2023-10-05 08:30 UTC, alsoandanswer commented
!review

2023-10-07 21:30 UTC, Arrow768 requested changes
You need to fix the build errors

2023-10-08 01:14 UTC, alsoandanswer commented
!review

2023-10-09 17:34 UTC, Alberyk approved these changes

2023-10-10 18:12 UTC, FluffyGhoster approved these changes

2023-10-12 16:33 UTC, merged