Add support for Bay-style terminals
Aurorastation/Aurora.3 pull request #17522
Opened 2023-10-04 21:25 UTC by Generalcamo

I'm planning on a vessel featuring Gadpathur's navy. The holoconsoles however would clash with the general theme I am trying to go for here, and several people have requested a non-holographic console for their own projects.

This ports Bay's current consoles, which feature support for connected states among other things:
![image](https://github.com/Aurorastation/Aurora.3/assets/1779662/d1cbb9be-d3ea-431d-a4a2-2270d42bfd4f)
These originate from Hestia, however the original PR with this has been purged, so I've been forced to scrounge information for this and use Bay's code.

I'm fully expecting this to get replaced in the future, but for now this should work. This also updates the code to remove some assumptions of holographic terminals, and add support for the connected states.

### Asset Licenses
The following assets that **have not** been created by myself are included in this PR:

| Path | Original Author | License |
| --- | --- | --- |
| icons/obj/machinery/modular_terminal.dmi | Chaoko99 (Hestia) | CC-BY-SA |

2023-10-04 21:27 UTC, Generalcamo commented
!review

2023-10-04 22:16 UTC, alsoandanswer approved these changes

2023-10-05 07:37 UTC, DreamySkrell approved these changes

2023-10-07 21:35 UTC, Arrow768 requested changes

2023-10-07 21:35 UTC, Arrow768 commented on code/game/machinery/computer/Operating.dm
> +	QDEL_NULL(table.computer)
You need to fix the CI errors

2023-10-08 11:45 UTC, Arrow768 approved these changes

2023-10-08 22:02 UTC, merged