Better Coffee Recipes
Aurorastation/Aurora.3 pull request #17546
Opened 2023-10-07 19:56 UTC by WilliamMurdoch

Removes mocaccino as it's the same drink as a Mocha Latte
Renames Latte to Caffe Latte
Renames Cafe Latte (not to be confused with Caffe Latte) to Caffe Misto
Changes some recipes to better match reality

I may return one day to add in steamed milk foam and other coffee related things to make these recipes better reflect reality, but this is it for now.

2023-10-08 01:25 UTC, alsoandanswer requested changes
I suggest you'd add the features of steamed milk and other things *alongside* these renames.

These just functionally give more busywork to wiki developers and confuse people with no actual concrete changes.

2023-10-11 04:45 UTC, alsoandanswer approved these changes

2023-10-11 04:45 UTC, alsoandanswer commented
!review

2023-10-14 10:27 UTC, NonQueueingMatt approved these changes

2023-10-14 11:33 UTC, merged