Konyang: Air Konyang Vessel
Aurorastation/Aurora.3 pull request #17540
Opened 2023-10-07 01:08 UTC by RustingWithYou

Adds a new away site to the Haneunim sector, an Air Konyang passenger vessel with ghostroles for the pilot, crew and passengers.

2023-10-07 01:08 UTC, RustingWithYou commented
!review

2023-10-07 12:22 UTC, DreamySkrell commented on maps/away/ships/konyang/air_konyang/air_konyang.dm
> +	designation = "[pick("John Ship, CEO of Ships")]"
.

2023-10-07 12:26 UTC, DreamySkrell commented
![image](https://github.com/Aurorastation/Aurora.3/assets/107256943/04f58085-5b7a-4b70-844c-18098fb10de4)

Grates should be used to hide pipes/wires/vents/etc (but still show they are there) in like the "public" areas like hallways or department rooms, or in this case the passenger cabin.

Avoid overusing grates like this in like the "engineering"/"maintenance" areas, cause they make it harder to see how pipes and wires connect and are laid out, and make it annoying to repair or rearrange them (ofc in this case that probably won't be done, but it still good to establish and follow some standards).

2023-10-07 12:29 UTC, DreamySkrell commented
![image](https://github.com/Aurorastation/Aurora.3/assets/107256943/3b3958f4-1c01-429c-9eff-06a72890a405)
I don't think this is good (lights under grates) - it makes it hard to follow the pipes and wires.

2023-10-07 12:31 UTC, DreamySkrell commented
![image](https://github.com/Aurorastation/Aurora.3/assets/107256943/06ab0883-615b-4086-a85d-5edd39c0185f)
Make that airlock three tiles wide like this ^ so it is easier to leave/enter the ship when docked.

2023-10-07 12:33 UTC, DreamySkrell commented
![image](https://github.com/Aurorastation/Aurora.3/assets/107256943/131dc5e0-6843-42bf-8346-c8096116012e)
Windows on engines is a bit of a old mapping style, and personally I do not like it. It's... weird to see the engine working from inside the ship/shuttle.

2023-10-07 12:36 UTC, DreamySkrell requested changes
see previous comments

2023-10-08 12:28 UTC, DreamySkrell commented
sync/merge from master to get fixed mapdiffbot preview

2023-10-08 13:00 UTC, DreamySkrell approved these changes
![image](https://github.com/Aurorastation/Aurora.3/assets/107256943/87586c96-5928-4c7e-b71b-fcecef40db9c)
broken flag

otherwise looks fine

2023-10-17 20:58 UTC, NonQueueingMatt approved these changes

2023-12-04 21:13 UTC, merged