Removes scrubber surge from event rotation
Aurorastation/Aurora.3 pull request #17563
Opened 2023-10-09 15:58 UTC by nauticall

What it says on the tin. Scrubber surge was one of the most egregiously LRP events inn the game and provides no benefit or gameplay at all to anyone, besides choking on drugs or pepperspray.

The code and event itself is still there, just with the weight set to 0. If there's a better way to do this then lemme know.

2023-10-09 15:58 UTC, nauticall commented
!review

2023-10-09 16:12 UTC, DreamySkrell commented
I think it's fine. It gives the crew something to talk about, and sometimes causes people to get up from their chairRP and run into other people. It also gives janitors something to do sometimes, when it spews out dirt.

Just maybe the dangerous chemicals could be removed from spawning with the event.

2023-10-09 16:18 UTC, Roostercat12 commented
Its something to happen during the round, which can be nice if there isn't anything going on. That and the chemicals they dump out are really mild. Like, you really don't even have to go to medbay for any of them aside from maybe capsaicin.

2023-10-09 16:45 UTC, alsoandanswer commented
While well intentioned on paper, taking another event out of rotation will compound the issue of other events happening too frequently

There's already complaints about radiation storms and hivebots - removing another event from rotation will make them happen even **more** often

2023-10-09 17:29 UTC, FluffyGhoster commented
This will need a feedback thread to properly evaluate the pros and cons about the proposed change, if you wish to go through with it

2023-10-09 17:41 UTC, Jaraci commented
Another knee-jerk feature removal PR courtesy of #relay-ooc I take it

2023-10-10 16:49 UTC, SleepyGemmy requested changes

2023-10-10 16:49 UTC, SleepyGemmy commented on code/modules/events/event_container.dm
> +		new /datum/event_meta(EVENT_LEVEL_MUNDANE, "Clogged Vents",					/datum/event/vent_clog, 			0),
if you want to remove this event you will need to remove this, the code itself, and update the probabilities Excel sheet (`tools/Event Probabilities/Event Probabilities.xlsx`) to reflect the removal.

2023-11-07 06:17 UTC, closed without merging