Added Jerry the baby reaver
Aurorastation/Aurora.3 pull request #17602
Opened 2023-10-14 12:38 UTC by Generalcamo

Adds Jerry, the baby reaver. The winner of a poll conducted on the #scc_bulletin on the relay.

Also adds sprites for the eel, the runner up.

### Asset Licenses
The following assets that **have not** been created by myself are included in this PR:

| Path | Original Author | License |
| --- | --- | --- |
| icons/mob/npc/pets.dmi | Yonnimer (Aurorastation) | CC-BY-SA |

2023-10-14 12:41 UTC, Greenjoe12345 commented on code/modules/mob/living/simple_animal/friendly/reaver.dm
> +	response_help = "pets the"
Wouldn't this lead to "pets the the baby reaver"?

2023-10-14 12:42 UTC, Generalcamo commented on code/modules/mob/living/simple_animal/friendly/reaver.dm
> +	response_help = "pets the"
This is the exact phrase used for space carp, including the enemy reaver. I do not believe this is proper/improper aware

2023-10-14 13:24 UTC, SleepyGemmy requested changes
add a 1 tile cage for Jerry. refer to the other pets' cages for inspiration.

2023-10-14 19:47 UTC, DreamySkrell commented
> add a 1 tile cage for Jerry. refer to the other pets' cages for inspiration.

I don't think a 1 tile cage is necessary. They kinda look bad now with 3/4. I have intentionally removed Ian's cage during the 3/4 remaps (third deck was my assignment).

Currently half of the pets do not have cages (Ian, Chauncey, Crusher).
And those that do have cages (Ginny, Ives, Columbo) are "docile" variants of dangerous beasts (space carp, hivebot... and, uh, dog).

2023-10-14 19:52 UTC, DreamySkrell commented
I think a baby reaver would be an extra lame pet for cargo.
It's just a meme cause it kills miners often. Reavers have have zero lore - even hivebots (Ives) have actual lore, as little as they do.
Personally, I don't think we need more pets, and definitely not memes like this.

2023-12-05 11:48 UTC, NonQueueingMatt commented
Reavers are a naturally hostile animal, we don't need people pretending that they're cute and misunderstood

2023-12-05 11:48 UTC, closed without merging