Konyang: More Existing Sites
Aurorastation/Aurora.3 pull request #17638
Opened 2023-10-19 21:41 UTC by RustingWithYou

Allows several ships and away sites to spawn in Haneunim. Right now these are the tramp freighter, freebooter ship, Orion station, space bar and civilian station.

2023-10-19 21:41 UTC, RustingWithYou commented
!review

2023-10-20 08:12 UTC, DreamySkrell commented
![image](https://github.com/Aurorastation/Aurora.3/assets/107256943/e38107f0-462d-40f6-ac6b-fb8b786d455a)
![image](https://github.com/Aurorastation/Aurora.3/assets/107256943/6d4b214b-ff4a-461f-ae74-793e6b66b2e4)

2023-10-20 08:16 UTC, DreamySkrell requested changes
Do not add civ station and space bar to spawn in konyang sector, as they are much lower quality both functionally and visually, compared to more recent sites and ships. They are also a bit broken in some places cause they were never looked at after 3/4.

They're also stations with no shuttles - no one is going to visit them while Konyang and Point Verdant is around to explore.

2023-10-20 21:27 UTC, DreamySkrell approved these changes

2023-10-26 14:22 UTC, NonQueueingMatt approved these changes

2023-10-26 21:48 UTC, merged