Patient Monitoring Console Overhaul
Aurorastation/Aurora.3 pull request #17633
Opened 2023-10-18 19:23 UTC by Geevies

* Added an embedded bodyscanner to the patient monitoring console, the caveat being that this scanner needs a printed scan from a real bodyscanner to prime the data before it can work.

https://github.com/Aurorastation/Aurora.3/assets/22774890/8564ba07-3294-462a-a433-c197d5a0fa9b

2023-10-20 16:46 UTC, Geevies commented
!review

2023-10-21 06:00 UTC, alsoandanswer requested changes
the surgical console should only be limited to organ, missing organs, limb and limb missing limb status, it should not supersede the full body scanner in function

2023-10-22 19:13 UTC, Geevies commented
![image](https://github.com/Aurorastation/Aurora.3/assets/22774890/363dfe24-3ae3-4d3d-80b9-8674081fd3d0)
![image](https://github.com/Aurorastation/Aurora.3/assets/22774890/230bff6d-1650-4ca3-afe4-69d8a13cb3ba)

2023-10-23 00:09 UTC, alsoandanswer approved these changes

2023-10-26 14:20 UTC, NonQueueingMatt approved these changes

2023-10-26 18:57 UTC, merged