Updates the Ranger Corvette to Mapping Standards
Aurorastation/Aurora.3 pull request #17795
Opened 2023-11-15 21:44 UTC by lavillastrangiato

* Makes the shuttle no longer a box shuttle (sort of). Gives it power and atmos.
* Adds a nuclear reactor to the ranger corvette, and adds APCs.
* Shuffles some flags around (Xanu gets a flag!) and puts Assunzionii miscellany in the ready room.
* Updates the airlocks to have @DreamySkrell's docking 
* This PR should be considered a test of a new shuttle template. Please bug-report judiciously!

![image](https://github.com/Aurorastation/Aurora.3/assets/63124803/86b7173f-4dc7-43d1-a409-bcd79d7a5bec)

(No idea why a bunch of other changelogs got caught in the changelog folder that I had to delete, BTW. Assuming it is GitKraken fuckery.)

2023-11-15 21:45 UTC, lavillastrangiato commented
!review

2023-11-16 20:57 UTC, Jasorn commented
does this fix the shower glass door access? if not, might as well throw that in too

2023-11-16 21:05 UTC, lavillastrangiato commented
> does this fix the shower glass door access? if not, might as well throw that in too

Yes, it does, this is mentioned in the changelog.

2023-11-17 10:06 UTC, DreamySkrell approved these changes

2023-11-18 01:28 UTC, SleepyGemmy requested changes

2023-11-18 01:28 UTC, SleepyGemmy commented on html/changelogs/Lavillastrangiato - shuttlerefactor.yml
double check that this isn't a renamed changelog.

2023-11-18 20:40 UTC, lavillastrangiato commented on html/changelogs/Lavillastrangiato - shuttlerefactor.yml
it's not

2023-11-22 07:11 UTC, FluffyGhoster approved these changes

2023-11-22 16:48 UTC, merged