Adds a framework for airlocks changing access depending on security level.
Aurorastation/Aurora.3 pull request #17849
Opened 2023-11-27 23:10 UTC by NonQueueingMatt

This allows you to have a door that opens with no access req at code green but locks to another access on other security levels.

2023-11-27 23:10 UTC, NonQueueingMatt commented
!review

2023-11-29 18:20 UTC, FluffyGhoster commented on code/game/machinery/doors/airlock.dm
> +		to_chat(user, SPAN_NOTICE("This airlock changes access requirement depending on the level."))
```suggestion
		to_chat(user, SPAN_NOTICE("This airlock changes access requirements depending on the alert level."))
```

2023-11-29 18:22 UTC, FluffyGhoster commented on code/modules/effects/map_effects/door_helper.dm
> +	/// Example of an appropriate way to set this: list("red" = list(1, 2))
```suggestion

	/// Example of an appropriate way to set this: list("red" = list(1, 2))
```
Should also say what the var does, before showing examples on how to set it

2023-12-02 15:23 UTC, Arrow768 requested changes
This needs to work with req_one_access as well.

2023-12-07 12:16 UTC, Arrow768 approved these changes

2023-12-07 12:27 UTC, merged