Fixes consulars not having sensors
Aurorastation/Aurora.3 pull request #17923
Opened 2023-12-10 12:39 UTC by alsoandanswer

Title.

2023-12-10 12:39 UTC, alsoandanswer commented
!bugfix

2023-12-10 12:39 UTC, alsoandanswer commented
!review

2023-12-10 13:51 UTC, DreamySkrell commented on code/modules/clothing/under/miscellaneous.dm
> +	has_sensor = SUIT_HAS_SENSORS
anyone can take this, not just consulars

2023-12-10 13:52 UTC, DreamySkrell commented on code/modules/clothing/under/miscellaneous.dm
> +	has_sensor = SUIT_HAS_SENSORS
same here

2023-12-10 14:00 UTC, DreamySkrell requested changes
These two are generic items that anyone can take, and shouldn't have suit sensors (if only uniforms are supposed to have them).

I am also against `thing/consular` subtypes where the only difference from their parent `thing` type, is that they have sensors.

I do not think consulars should really have suit sensors in the first place - they're not SCC crew, they are guests here. They are not wearing SCC or corporate uniforms, but they just bring their clothes from their parent nation.

2023-12-11 12:03 UTC, lavillastrangiato commented
> I do not think consulars should really have suit sensors in the first place - they're not SCC crew, they are guests here. They are not wearing SCC or corporate uniforms, but they just bring their clothes from their parent nation.
They are diplomats to the SCC's flagship. It would reflect very poorly on the SCC if a reason that diplomatic consul died was because they were not allowed to have vitals tracking, for some reason.

2023-12-11 12:49 UTC, DreamySkrell commented
> > I do not think consulars should really have suit sensors in the first place - they're not SCC crew, they are guests here. They are not wearing SCC or corporate uniforms, but they just bring their clothes from their parent nation.
> 
> They are diplomats to the SCC's flagship. It would reflect very poorly on the SCC if a reason that diplomatic consul died was because they were not allowed to have vitals tracking, for some reason.

Also, not all consulars even really have uniforms, or makes sense for them to have uniforms - like Biesel consulars for example. If you want all consulars to have sensors, it should be via a system that is different from clothes.

2024-01-06 12:31 UTC, NonQueueingMatt commented
#17898 will be merged instead

2024-01-06 12:31 UTC, closed without merging