Hammertail Gear
Aurorastation/Aurora.3 pull request #17960
Opened 2023-12-14 21:40 UTC by 1Sparky1

Adds a Hammertail Smiths jumsuit, as well as adding themed gear crates to the uplink.

2023-12-14 21:54 UTC, 1Sparky1 commented
!review

2023-12-14 21:54 UTC, 1Sparky1 commented
!review

2023-12-15 13:10 UTC, FluffyGhoster requested changes

2023-12-15 13:10 UTC, FluffyGhoster commented on code/game/objects/structures/crates_lockers/crates/gear_loadout.dm
> +	new /obj/item/ammo_magazine/c762(src)
Use loops to add multiple things of the same type, instead of repeating the same lines

2023-12-17 14:46 UTC, NonQueueingMatt approved these changes

2023-12-17 14:54 UTC, FluffyGhoster approved these changes

2023-12-17 21:54 UTC, merged