Energy Weapon Recharging: The Future Is Now
Aurorastation/Aurora.3 pull request #17969
Opened 2023-12-16 04:31 UTC by RustingWithYou

Adds two new methods for recharging energy weapons - a hardsuit module which will drain the hardsuit's power cell to charge a weapon and a recharger backpack which requires power cells.

These can be made by science/machinist with sufficient tech and materials, and are also available in the antag uplink. ERT suits, as well as relevant hardsuits for factions which primarily use energy weapons (TCFL, Skrell, Vaurca and Hegemony), have had the recharge modules added to them.

2023-12-16 04:31 UTC, RustingWithYou commented
!review

2023-12-16 05:11 UTC, FluffyGhoster commented on code/game/objects/items/recharger_backpack.dm
> +		return
```suggestion
	//If there caller isn't an human, early return
	if(!ishuman(usr))
		return

	user = usr
```

2023-12-16 05:11 UTC, FluffyGhoster commented on code/game/objects/items/recharger_backpack.dm
> +	connected.disconnect()
```suggestion

	connected.disconnect()
```

2023-12-16 05:11 UTC, FluffyGhoster commented on code/game/objects/items/recharger_backpack.dm
> +		QDEL_NULL(powersupply)
```suggestion
	if(connected)
		connected.disconnect()

	if(powersupply)
		QDEL_NULL(powersupply)
	
	. = ..()
```

2023-12-16 05:11 UTC, FluffyGhoster commented on code/modules/clothing/spacesuits/rig/modules/utility.dm
> +	var/obj/item/gun/energy/connected //the gun charging off our hardsuit
```suggestion

	///The gun charging off our hardsuit
	var/obj/item/gun/energy/connected
```

2023-12-16 05:11 UTC, FluffyGhoster commented on code/modules/clothing/spacesuits/rig/modules/utility.dm
> +	if(!connected)
```suggestion

	if(!connected)
```

2023-12-16 05:11 UTC, FluffyGhoster commented on code/modules/clothing/spacesuits/rig/modules/utility.dm
> +	to_chat(user, SPAN_NOTICE("\The [connected] is now connected to your hardsuit power supply. Deactivate this module to disconnect it."))
```suggestion

	to_chat(user, SPAN_NOTICE("\The [connected] is now connected to your hardsuit power supply. Deactivate this module to disconnect it."))
```

2023-12-16 05:11 UTC, FluffyGhoster commented on code/modules/clothing/spacesuits/rig/modules/utility.dm
> +	if(connected)
```suggestion

	if(connected)
```

2023-12-16 05:11 UTC, FluffyGhoster commented on code/modules/clothing/spacesuits/rig/modules/utility.dm
> +	return TRUE
```suggestion

	return TRUE
```

2023-12-16 05:11 UTC, FluffyGhoster commented on code/modules/projectiles/guns/energy.dm
> +	if(istype(recharger, /obj/item/recharger_backpack))
```suggestion

	else if(istype(recharger, /obj/item/recharger_backpack))
```

2023-12-16 05:11 UTC, FluffyGhoster commented on code/modules/projectiles/guns/energy.dm
> +		if(rigcharger)
```suggestion

		if(rigcharger)
```

2023-12-16 05:11 UTC, FluffyGhoster commented on code/modules/projectiles/guns/energy.dm
> +		if(!ismob(loc))
```suggestion

		if(!ismob(loc))
```

2023-12-16 05:11 UTC, FluffyGhoster commented on code/modules/projectiles/guns/energy.dm
> +		to_chat(usr, SPAN_NOTICE("You neatly plug \the [src] into \the [recharger]."))
```suggestion

		to_chat(usr, SPAN_NOTICE("You neatly plug \the [src] into \the [recharger]."))
```

2023-12-16 05:11 UTC, FluffyGhoster commented on code/modules/projectiles/guns/energy.dm
> +	if(backcharger)
```suggestion

	if(backcharger)
```

2023-12-16 05:11 UTC, FluffyGhoster commented on code/modules/projectiles/guns/energy.dm
> +	if(istype(over, /obj/item/rig))
```suggestion

	if(istype(over, /obj/item/rig))
```

2023-12-16 05:11 UTC, FluffyGhoster commented on code/modules/projectiles/guns/energy.dm
> +		var/obj/item/rig_module/recharger/recharger = locate() in rig.installed_modules
```suggestion

		var/obj/item/rig_module/recharger/recharger = locate() in rig.installed_modules
```

2023-12-16 05:11 UTC, FluffyGhoster commented on code/modules/projectiles/guns/energy.dm
> +	if(istype(over, /obj/item/recharger_backpack))
```suggestion

	if(istype(over, /obj/item/recharger_backpack))
```

2023-12-16 05:11 UTC, FluffyGhoster commented on code/modules/projectiles/guns/energy.dm
> +	if(rigcharger || backcharger)
```suggestion

	if(rigcharger || backcharger)
```

2023-12-16 05:11 UTC, FluffyGhoster commented on code/game/objects/items/recharger_backpack.dm
> +	if(powersupply)
```suggestion

	if(powersupply)
```

2023-12-16 05:11 UTC, FluffyGhoster commented on code/game/objects/items/recharger_backpack.dm
> +	update_icon()
```suggestion

	//To update the icon based on the power cell charge that we spawn with
	update_icon()
```

2023-12-16 05:11 UTC, FluffyGhoster commented on code/modules/projectiles/guns/energy.dm
> +	var/obj/item/recharger_backpack/backcharger
DMdoc them

2023-12-16 05:11 UTC, FluffyGhoster commented on code/modules/projectiles/guns/energy.dm
> +	if(backcharger)
```suggestion

	if(backcharger)
```

2023-12-16 05:11 UTC, FluffyGhoster commented on code/modules/projectiles/guns/energy.dm
> +	if(rigcharger && rigcharger.holder)
```suggestion

	if(rigcharger && rigcharger.holder)
```

2023-12-16 05:11 UTC, FluffyGhoster commented on code/game/objects/items/recharger_backpack.dm
> +	var/obj/item/gun/energy/connected
DMdoc them

2023-12-16 05:11 UTC, FluffyGhoster commented on code/game/objects/items/recharger_backpack.dm
> +	connected = newgun
```suggestion

	connected = newgun
```

2023-12-17 14:44 UTC, NonQueueingMatt requested changes

2023-12-17 14:44 UTC, NonQueueingMatt commented on code/game/objects/items/recharger_backpack.dm
> +
```suggestion
```

2023-12-17 14:44 UTC, NonQueueingMatt commented on code/modules/projectiles/guns/energy.dm
> +	var/obj/item/recharger_backpack/backcharger
You don't need these two to be separate - either unify these variables as a single item then use get_cell() to get the cell from it, or make the rigcharger just be a backpack charger but in the rig.

2023-12-24 23:32 UTC, NonQueueingMatt approved these changes

2023-12-24 23:46 UTC, Alberyk approved these changes

2023-12-26 02:41 UTC, merged