Unified Sadar Fleet Ship
Aurorastation/Aurora.3 pull request #17970
Opened 2023-12-16 05:50 UTC by shaky-jake

Adds a Unified Sadar Fleet ship to all Coalition sectors except for Haneunim and Burzsia. Has five player slots. Yarr

Also added because I needed it for the ship:
- Mirrored version of the francisca and it's loader (for mounting on the shuttle)
- Red circuit tile (floor sprite existed, but the tile itself wasn't a thing for some reason)

2023-12-16 05:50 UTC, shaky-jake commented
!review

2023-12-17 14:40 UTC, NonQueueingMatt requested changes
The flipped francisca feels like giga shitcode, can't it just have different directions...?

2023-12-17 21:02 UTC, shaky-jake commented
I wasn't aware of how to add directions before as I've never messed with sprites before - now I do.
Requested change addressed.

2023-12-19 15:20 UTC, NonQueueingMatt approved these changes

2023-12-19 18:42 UTC, DreamySkrell approved these changes

2023-12-19 20:53 UTC, merged