Scarab Ship Fixes
Aurorastation/Aurora.3 pull request #17983
Opened 2023-12-18 01:09 UTC by RustingWithYou

Makes several bug and QOL fixes to the Scarab ship.

2023-12-18 01:09 UTC, RustingWithYou commented
!review

2023-12-18 01:09 UTC, RustingWithYou commented
!bugfix

2023-12-18 01:12 UTC, FluffyGhoster requested changes

2023-12-18 01:12 UTC, FluffyGhoster commented on html/changelogs/RustingWithYou - thegravityofthesituation.yml
> +  - bugfix: "Fixes a number of bugs with the Scarab ship."
Need to list what is fixed

2023-12-18 16:06 UTC, NonQueueingMatt approved these changes

2023-12-18 16:06 UTC, NonQueueingMatt commented on maps/away/ships/coc/coc_scarab/coc_scarab_ghostroles.dm
> +	desc = "Command a salvage ship. Harvest valuable resources to take back to the wider Scarab Fleet. OOC Note: Characters must have names and backgrounds consistent with the Scarab Fleet. This is enfo
```suggestion
	desc = "Command a salvage ship. Harvest valuable resources to take back to the wider Scarab Fleet. OOC Note: Characters must have names and backgrounds consistent with the Scarab Fleet. This is enforcable by admin action."
```

2023-12-20 10:22 UTC, DreamySkrell approved these changes

2023-12-21 02:16 UTC, FluffyGhoster approved these changes

2023-12-21 12:24 UTC, merged