He Has Covered Wars, They Know
Aurorastation/Aurora.3 pull request #17999
Opened 2023-12-20 02:54 UTC by Alberyk

-adds an adhomai typewriter to the loadout
-adds an adhomian camera to the loadout

Sprites made by sue

2023-12-20 10:19 UTC, DreamySkrell approved these changes

2023-12-20 18:55 UTC, FluffyGhoster requested changes

2023-12-20 18:55 UTC, FluffyGhoster commented on code/modules/paperwork/typewriter.dm
> +	var/obj/item/portable_typewriter/machine
This reference needs to be removed in Destroy()

2023-12-20 18:55 UTC, FluffyGhoster commented on code/modules/paperwork/typewriter.dm
> +/obj/item/typewriter_case/New()
Should use Initialize over New

2023-12-20 18:55 UTC, FluffyGhoster commented on code/modules/paperwork/typewriter.dm
> +	var/obj/item/paper/stored_paper = null
The reference should be cleared in Destroy()

2023-12-20 18:55 UTC, FluffyGhoster commented on code/modules/paperwork/typewriter.dm
> +	var/obj/item/pen/pen
The reference should be cleared in Destroy()

2023-12-21 01:54 UTC, FluffyGhoster commented on code/modules/paperwork/typewriter.dm
> +		pen = null
```suggestion
	QDEL_NULL(stored_paper)
	QDEL_NULL(pen)
```

2023-12-21 01:54 UTC, FluffyGhoster commented on code/modules/paperwork/typewriter.dm
> +		machine = null
```suggestion
	QDEL_NULL(machine)
```

2023-12-21 01:54 UTC, FluffyGhoster commented on code/modules/paperwork/typewriter.dm
> +		update_icon()
```suggestion
	opened = !opened
	update_icon()
```

2023-12-21 01:54 UTC, FluffyGhoster commented on code/modules/paperwork/typewriter.dm
> +		to_chat(user, SPAN_ALERT ("\The [src] has no paper fed for typing!"))
```suggestion
		to_chat(user, SPAN_ALERT("\The [src] has no paper fed for typing!"))
```

2023-12-21 01:54 UTC, FluffyGhoster commented on code/modules/paperwork/typewriter.dm
> +			to_chat(user, SPAN_ALERT ("\The [src] has no paper fed for typing!"))
```suggestion
			to_chat(user, SPAN_ALERT("\The [src] has no paper fed for typing!"))
```

2023-12-21 01:54 UTC, FluffyGhoster commented on code/modules/paperwork/typewriter.dm
> +		else if (!opened)
```suggestion
		else
```

2023-12-21 01:54 UTC, FluffyGhoster commented on code/modules/paperwork/typewriter.dm
> +			user.visible_message(SPAN_ALERT ("[user] places \the [W] into \the [src]."), SPAN_ALERT ("You store \the [W] in \the [src]."))
```suggestion
			user.visible_message(SPAN_ALERT("[user] places \the [W] into \the [src]."), SPAN_ALERT ("You store \the [W] in \the [src]."))
```

2023-12-21 01:54 UTC, FluffyGhoster commented on code/modules/paperwork/typewriter.dm
> +	to_chat(user, SPAN_ALERT ("\The [src] ejects \the [stored_paper]."))
```suggestion

	to_chat(user, SPAN_ALERT ("\The [src] ejects \the [stored_paper]."))
```

2023-12-21 01:54 UTC, FluffyGhoster commented on code/modules/paperwork/typewriter.dm
> +	if(((user.contents.Find(src) || in_range(src, user))))
```suggestion

	if(((user.contents.Find(src) || in_range(src, user))))
```

2023-12-21 01:54 UTC, FluffyGhoster commented on code/modules/paperwork/typewriter.dm
> +	if(!pen)
```suggestion

	if(!pen)
```

2023-12-22 18:29 UTC, FluffyGhoster approved these changes
Forgot to remove the space in the previous suggestion, otherwise LGTM

2023-12-22 18:29 UTC, FluffyGhoster commented on code/modules/paperwork/typewriter.dm
> +	to_chat(user, SPAN_ALERT ("\The [src] ejects \the [stored_paper]."))
```suggestion
	to_chat(user, SPAN_ALERT("\The [src] ejects \the [stored_paper]."))
```

2023-12-22 22:29 UTC, Arrow768 approved these changes

2023-12-24 03:46 UTC, merged