CCIA HRA makeover
Aurorastation/Aurora.3 pull request #18029
Opened 2023-12-21 16:22 UTC by nauticall

Overhauls the look of HRAs from CCIA; rather than using the stock SCC liaison outfit, they now come with a proper coat and tie. Subjectively, this makes them look twice as intimidating and five times more likely for people to take them seriously.

Additionally, this PR gives HRA agents a baton, an energy pistol (and holster), and a laptop. Gotta be prepared.

Pics below.

![image](https://github.com/Aurorastation/Aurora.3/assets/55491249/1f7413bd-075f-4568-a9f8-4fd72f52c1d3)![image](https://github.com/Aurorastation/Aurora.3/assets/55491249/b2dc0b7c-f9dd-48fc-a0af-2bb4f2704a07)![image](https://github.com/Aurorastation/Aurora.3/assets/55491249/37723fa3-0cb3-409b-ae2c-7cea4091ade9)![image](https://github.com/Aurorastation/Aurora.3/assets/55491249/1a75c8e7-6581-4618-a54e-f01cf90bbb59)

_Loadout._
![image](https://github.com/Aurorastation/Aurora.3/assets/55491249/fc487539-c200-4cbb-8b21-2ac8ed29e967)

If there's a way to make people spawn with both ties _and_ holsters, please let me know. But putting the gun in the backpack's the next best thing.

2023-12-21 16:22 UTC, nauticall commented
!review

2023-12-21 16:41 UTC, Generalcamo requested changes

2023-12-21 16:41 UTC, Generalcamo commented on config/example/admins.txt
> +# Nauticall - Head Admin/Dev
Seems this was accidentally left in?

2023-12-21 16:41 UTC, Generalcamo commented on code/modules/clothing/factions/scc.dm
> +/obj/item/clothing/suit/storage/toggle/armor/ccia
Wouldn't it be better to make this into a subset of `suit/storage`? You're not using the functionality of `toggle` at all, and indeed you remove it below.

2023-12-22 22:12 UTC, Arrow768 approved these changes

2023-12-23 16:26 UTC, alsoandanswer commented
wouldn't it be better for the holster to come auto-attached?

2023-12-24 17:15 UTC, nauticall commented
> wouldn't it be better for the holster to come auto-attached?

Fixed in last commit https://github.com/Aurorastation/Aurora.3/pull/18029/commits/61e9fea8891921a6bb916a2be38d61b5834274f9

2023-12-24 23:28 UTC, NonQueueingMatt approved these changes

2023-12-25 00:59 UTC, merged