Psi Grip Tweak
Aurorastation/Aurora.3 pull request #18027
Opened 2023-12-21 11:38 UTC by Geevies

* You now need a direct line of sight to establish and use the Psi Grip (crush) ability. You do not have to maintain line of sight to keep the grip active, however.

https://forums.aurorastation.org/topic/19554-add-a-cooldown-remove-or-alter-psionic-head-crush

2023-12-21 11:39 UTC, Geevies commented
!review

2023-12-21 12:22 UTC, NonQueueingMatt requested changes

2023-12-21 12:22 UTC, NonQueueingMatt commented on code/modules/psionics/abilities/grip.dm
> +	if(!(victim in view(7, get_turf(user))))
Use SPATIAL_CHECK_LOS

2023-12-21 18:08 UTC, FluffyGhoster commented on code/modules/psionics/abilities/grip.dm
> +	var/has_line_of_sight = null
```suggestion
	var/has_line_of_sight = FALSE
```

2023-12-21 18:08 UTC, FluffyGhoster commented on code/modules/psionics/abilities/grip.dm
> +	var/has_line_of_sight = null
```suggestion
	var/has_line_of_sight = FALSE
```

2023-12-21 19:18 UTC, FluffyGhoster approved these changes

2023-12-24 23:28 UTC, NonQueueingMatt approved these changes

2023-12-25 01:18 UTC, merged