Overhauls the Orion ship
Aurorastation/Aurora.3 pull request #18043
Opened 2023-12-22 07:33 UTC by meep109

Improves orion ship by adding actual power to it and makes the shuttle bigger/better

2023-12-22 07:46 UTC, meep109 commented
!review

2023-12-22 15:02 UTC, FluffyGhoster requested changes

2023-12-22 15:02 UTC, FluffyGhoster commented on html/changelogs/meep109_orionship.yml
> +author: ChangeMe
```suggestion
author: meep109
```

2023-12-22 17:48 UTC, meep109 commented on html/changelogs/meep109_orionship.yml
> +author: ChangeMe
Fixed

2023-12-23 17:05 UTC, FluffyGhoster approved these changes
Code LGTM

2023-12-27 09:30 UTC, DreamySkrell approved these changes

2023-12-28 14:47 UTC, merged