Adds a k'ois freezer subtype and places it in the kitchen
Aurorastation/Aurora.3 pull request #18087
Opened 2023-12-28 20:43 UTC by lavillastrangiato

Title. The fridge also has some very obvious markers around it.
![image](https://github.com/Aurorastation/Aurora.3/assets/63124803/32858a3c-2c0b-4e0c-9d70-be5900c5d219)

I am not sure why edits to some syntax in the INDRA and supermatter are showing up.

2023-12-28 20:43 UTC, lavillastrangiato commented
!review

2023-12-29 13:40 UTC, Geevies requested changes

2023-12-29 13:40 UTC, Geevies commented on maps/sccv_horizon/sccv_horizon-2_deck_2.dmm
> +	sensors = list("supermatter_sensor"="Supermatter  Core")
```suggestion
	sensors = list("supermatter_sensor"="Supermatter Core")
```

2023-12-29 13:40 UTC, Geevies commented on maps/sccv_horizon/sccv_horizon-2_deck_2.dmm
> +	sensors = list("fusion_sensor"="INDRA    Chamber")
```suggestion
	sensors = list("fusion_sensor"="INDRA  Chamber")
```

2023-12-29 13:40 UTC, Geevies commented on code/game/objects/structures/crates_lockers/closets/secure/freezer.dm
> +/obj/structure/closet/secure_closet/freezer/kois
```suggestion

/obj/structure/closet/secure_closet/freezer/kois
```

2023-12-29 13:40 UTC, Geevies commented on code/game/objects/structures/crates_lockers/closets/secure/freezer.dm
> +	..()
```suggestion
```

2023-12-30 21:11 UTC, lavillastrangiato commented on code/game/objects/structures/crates_lockers/closets/secure/freezer.dm
> +/obj/structure/closet/secure_closet/freezer/kois
should be good?

2023-12-31 12:43 UTC, Geevies approved these changes

2023-12-31 18:05 UTC, NonQueueingMatt approved these changes

2023-12-31 19:03 UTC, merged