Warrant Fix & More
Aurorastation/Aurora.3 pull request #18085
Opened 2023-12-28 14:01 UTC by Geevies

* Fixed not being able to load warrants on the warrant projector.
* The warrant projector will now alert you if a new warrant was loaded, and will alert you if the currently active warrant is modified or deleted.
* Tweaked how warrant projectors work, you now use it in-hand to load or unload warrants, and then click on the target to display it. Shift-clicking no longer opens the warrant.
* Fixed the digital warrant assistant not having an icon on the PDA.

2023-12-28 16:45 UTC, Geevies commented
force pushed to remove content that i decided to split off into another PR because the changes weren't related to the PR at all https://github.com/Aurorastation/Aurora.3/pull/18086

2023-12-29 13:34 UTC, Geevies commented
!review

2023-12-30 04:01 UTC, DreamySkrell approved these changes

2023-12-30 05:40 UTC, FluffyGhoster requested changes

2023-12-30 05:40 UTC, FluffyGhoster commented on code/__defines/dcs/signals.dm
> +
They need to go in their own file under code\__defines\dcs\signals\signals_warrants.dm (or whatever you want to call it)

2023-12-31 13:41 UTC, FluffyGhoster approved these changes

2023-12-31 18:32 UTC, merged