Ti'rakqi Smuggler Freighter (Remap)
Aurorastation/Aurora.3 pull request #18083
Opened 2023-12-28 00:12 UTC by shaky-jake

Replaces the outdated Ti'rakqi Smuggler Freighter with a new one that satisfies current mapping standards, and holds a more distinct style from human ships. Has five player slots.

It will probably be a while before this ship is actually seen, so this ship will likely be due for a touch up if any new skrell assets ever get added in the future.

2023-12-28 00:12 UTC, shaky-jake commented
!review

2023-12-29 13:38 UTC, Geevies requested changes

2023-12-29 13:38 UTC, Geevies commented on maps/away/ships/tirakqi_smuggler/tirakqi_smuggler.dm
> +	desc = "Made to complement the Xroquv-class freighter, the Jloqup-class shuttle is a cargo transport designed to neatly into the aft shuttle bay of its parent ship. While faster than most shuttles o
```suggestion
	desc = "Made to complement the Xroquv-class freighter, the Jloqup-class shuttle is a cargo transport designed to fit neatly into the aft shuttle bay of its parent ship. While faster than most shuttles of similar class, it finds a shortcoming in fuel efficiency, meaning it usually can't go far on its own. This one's transponder identifies it as belonging to an independent freighter."
```

2023-12-29 18:07 UTC, Geevies approved these changes

2023-12-30 04:03 UTC, DreamySkrell approved these changes
very nice

2023-12-30 05:34 UTC, FluffyGhoster approved these changes

2023-12-31 02:53 UTC, merged