Keep Our Light Of Liberty Shining - The TCAF Corvette
Aurorastation/Aurora.3 pull request #18091
Opened 2023-12-29 06:22 UTC by RustingWithYou

Adds a Republican Fleet patrol corvette, finally making use of all @NobleRow's excellent TCAF drip. This vessel can spawn in Tau Ceti, the CRZ, Valley Hale, or the Badlands, and is mutually exclusive with the TCFL ship.

Also adds TCAF gear crates to the antag uplink, as well as a new burst-fire blaster rifle commonly used by Dorn's most expendable soldiers.

2023-12-29 06:22 UTC, RustingWithYou commented
!review

2023-12-29 13:47 UTC, Geevies requested changes

2023-12-29 13:47 UTC, Geevies commented on code/game/objects/structures/crates_lockers/crates/gear_loadout.dm
> +
```suggestion
```

2023-12-29 13:47 UTC, Geevies commented on code/modules/projectiles/guns/energy/blaster.dm
> +	desc = "Developed by Zavodskoi Interstellar, the Z.I. Guardian is a burst-fire blaster rifle designed for the armed forces of the Republic of Biesel. Cheap, reliable and easy to mass-produce, these
```suggestion
	desc = "Developed by Zavodskoi Interstellar, the Z.I. Guardian is a burst-fire blaster rifle designed for the armed forces of the Republic of Biesel. Cheap, reliable and easy to mass-produce, these weapons can be seen across the branches of the TCAF."
```

2023-12-30 03:58 UTC, DreamySkrell requested changes
![image](https://github.com/Aurorastation/Aurora.3/assets/107256943/a55db89d-283e-432c-b892-8edaf0d18843)

since mapdiffbot2 is currently dead...

assuming this is the up to date screenshot posted on maincord:
- make the airlock marked with red into a docking airlock
- add an external access airlock at the front of the ship - I think would be easiest to fit at the area marked with orange
- remove the exterior doors/shutters on the shuttle, marked with yellow (reasoning is that they are easy to forget to close when undocking, leading to venting the shuttle)
- add a docking airlock at the green area, should be easy to fit by moving the shuttle one tile over in either direction (ping me on discord if not sure how to do it)

2023-12-31 01:47 UTC, RustingWithYou commented
> ![image](https://private-user-images.githubusercontent.com/107256943/293442031-a55db89d-283e-432c-b892-8edaf0d18843.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM5ODY0NzcsIm5iZiI6MTcwMzk4NjE3NywicGF0aCI6Ii8xMDcyNTY5NDMvMjkzNDQyMDMxLWE1NWRiODlkLTI4M2UtNDMyYy1iODkyLThlZGFmMGQxODg0My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjMxMjMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIzMVQwMTI5MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNjI4NTYwMmQwODFiMDUyODA2NjU5NzNlMDVlYzE1OWQ3OTQ0Yjg2ODZjZjZjZTM0NmQ0Yzk5OTJhMTNmZWFmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._sfbWhMJ_YLHVMReY2mtsJ2-rlDMTIdQr-5aaqVCzD0)
> 
> since mapdiffbot2 is currently dead...
> 
> assuming this is the up to date screenshot posted on maincord:
> 
> * make the airlock marked with red into a docking airlock
> * add an external access airlock at the front of the ship - I think would be easiest to fit at the area marked with orange
> * remove the exterior doors/shutters on the shuttle, marked with yellow (reasoning is that they are easy to forget to close when undocking, leading to venting the shuttle)
> * add a docking airlock at the green area, should be easy to fit by moving the shuttle one tile over in either direction (ping me on discord if not sure how to do it)

addressed

2023-12-31 11:04 UTC, Geevies approved these changes
code lgtm

2024-01-02 08:46 UTC, DreamySkrell approved these changes

2024-01-03 07:53 UTC, shaky-jake requested changes
First things first, air alarms are missing in the port thruster, all four sections of the holding cells area, and the docking port access next to them. You also need emergency shutters. Window spawners handle this automatically of course, but all the reinforced cockpit windows you're using need them to be manually placed. All the doors are missing emergency shutters under them too.

In the same line of thought - Since this is a military ship, exterior windows should really have blast doors to seal them off during combat. Preferably lessen up on them too, 60% of the front facing side of the ship is windows currently.

There's a few piping/wiring issues:
- Missing wire connection between the SMES and the hangar APC.
- There's a bent pipe instead of a straight pipe that cuts the fuel line off to the port thruster. Located just in front of the shuttle's sensor suite.
- Scrubber line for ship is hooked up to CO2 canisters through universal adapter. Same goes for the shuttle. 

As for the shuttle, it's missing an aft targeting entry point. And it can't dock properly. From looking over it briefly, I noticed it's missing interior and exterior sensors. Also, the outside vent should have an ext marker, not an out marker. Reference other shuttles that have functioning automatic docking and mess around with it until it works in a test server.

There's some minor optional stuff too - One being a missing grate over the SMES's terminal. Also, while the shortened railings you used by the grauwolf look nice in StrongDMM, those are unwrenched variants and show up like this in game.
![grauwolf_railing_issue](https://github.com/Aurorastation/Aurora.3/assets/137534368/5acfeafe-cab2-4c51-9bde-0e5312dff11d)

Last couple things would be one, to bump the shuttle transit marker north by 3-4 tiles as currently during transit there's a sudden cutoff to black from the skybox a few tiles out from the cockpit. Two, fix the portside docking port interior access button to not be floating in the air.

2024-01-09 16:28 UTC, NonQueueingMatt approved these changes

2024-01-09 16:40 UTC, merged