Fixes gadpathurian ship access issues + general tweaks
Aurorastation/Aurora.3 pull request #18107
Opened 2023-12-31 04:28 UTC by meep109

I also added a cryo pod console and an additional power loader to the francisca gun.

2023-12-31 04:30 UTC, meep109 commented
!review

2023-12-31 04:31 UTC, meep109 commented
!bugfix

2023-12-31 06:50 UTC, Generalcamo approved these changes
I had originally intentionally removed the power loader for balance concerns. In hindsight however, making things inconvenient isn't a good way to balance things, so I approve of these changes. 

Thank you for this.

2024-01-01 18:22 UTC, Geevies requested changes

2024-01-01 18:22 UTC, Geevies commented on maps/away/ships/coc/gadpathur_patrol/gadpathur_patrol.dmm
> +	req_one_access = ssssss;
```suggestion
	req_one_access = list(223,224);
```

2024-01-02 08:41 UTC, DreamySkrell approved these changes

2024-01-02 12:54 UTC, merged