Courier’s Konyang Ruins
Aurorastation/Aurora.3 pull request #18128
Opened 2024-01-02 23:27 UTC by shaky-jake

Implements and polishes up a set of ruins made by CourierBravo for Konyang.

2024-01-02 23:27 UTC, shaky-jake commented
!review

2024-01-03 09:46 UTC, DreamySkrell approved these changes

2024-01-06 12:37 UTC, Arrow768 approved these changes

2024-01-06 12:43 UTC, NonQueueingMatt requested changes
the maps look to be dmm format and not tgm

2024-01-09 17:34 UTC, merged