ATM charge card fix
Aurorastation/Aurora.3 pull request #18129
Opened 2024-01-02 23:31 UTC by feartheblackout

Title. Being able to withdraw charge cards was not included with the implementation of TGUI, so this returns that.

2024-01-02 23:31 UTC, feartheblackout commented
!review

2024-01-02 23:31 UTC, feartheblackout commented
!bugfix

2024-01-02 23:37 UTC, NonQueueingMatt requested changes

2024-01-02 23:37 UTC, NonQueueingMatt commented on tgui/packages/tgui/interfaces/ATM.tsx
> +            content="Withdraw Cash"
```suggestion
            tooltip="Cash"
```

2024-01-02 23:37 UTC, NonQueueingMatt commented on tgui/packages/tgui/interfaces/ATM.tsx
> +            content="Withdraw Charge Card"
```suggestion
            tooltip="Charge Card"
```

2024-01-02 23:37 UTC, NonQueueingMatt commented on tgui/packages/tgui/interfaces/ATM.tsx
> +            icon="check"
change this icon to something else, you can find all the icons in the font awesome website

2024-01-03 12:08 UTC, NonQueueingMatt approved these changes

2024-01-04 14:34 UTC, merged