Adds follow button to hivenet broadcasts, fixes follow button falling off observer manifest
Aurorastation/Aurora.3 pull request #18200
Opened 2024-01-11 10:00 UTC by AlaunusLux

Title. Follow on broadcast not strictly necessary since it's on the emote of their antennae, but for consistency I thought I would add it.

Fixes #18190

2024-01-11 10:02 UTC, AlaunusLux commented
!bugfix

2024-01-11 11:49 UTC, NonQueueingMatt requested changes

2024-01-11 11:49 UTC, NonQueueingMatt commented on code/modules/mob/language/station.dm
> +			player.show_message("[ghost_follow_link(speaker, player)] [msg]", 1)
```suggestion
			to_chat(player, "[ghost_follow_link(speaker, player)] [msg]")
```

2024-01-12 23:26 UTC, AlaunusLux commented
!review

2024-01-14 19:34 UTC, NonQueueingMatt approved these changes

2024-01-15 14:05 UTC, merged