Corporate Journalist changes
Aurorastation/Aurora.3 pull request #18279
Opened 2024-01-21 19:10 UTC by Greenjoe12345

Ports the Corporate Journalist changes from https://github.com/Aurorastation/Aurora.3/pull/17836 into their own PR. They can now be in all megacorps.
### Asset Licenses
The following assets that **have not** been created by myself are included in this PR:

| Path | Original Author | License |
| civilian.dmi | Wezzy (Aurora) | AGPL 3.0 |
| icons/example.dmi | ExamplePerson (Example Station) | CC0 |

2024-01-21 19:10 UTC, Greenjoe12345 commented
!review

2024-01-23 11:13 UTC, alsoandanswer requested changes

2024-01-23 11:13 UTC, alsoandanswer commented on code/__DEFINES/jobs.dm
> +#define NT_ROLES list(SCIENCE_ROLES, MEDICAL_ROLES, SERVICE_ROLES, CIVILIAN_ROLES, REPRESENTATIVE_ROLE, JOURNALIST_ROLE)
Don't do this, move the JOURNALIST_ROLE definition to be under CIVILIAN_ROLES.

2024-01-23 15:24 UTC, alsoandanswer approved these changes

2024-01-25 22:06 UTC, FluffyGhoster approved these changes
LGTM

2024-01-30 12:25 UTC, merged