More floors and decals
Aurorastation/Aurora.3 pull request #18328
Opened 2024-01-30 23:39 UTC by DreamySkrell

wip

2024-01-30 23:40 UTC, DreamySkrell commented
!wip

2024-02-15 18:54 UTC, Arrow768 requested changes

2024-02-15 18:54 UTC, Arrow768 commented on code/game/turfs/flooring/flooring_premade_.dm
> +	color = COLOR_GRAY40
Not defined, apparently

2024-03-12 18:15 UTC, DreamySkrell commented
!review

2024-03-13 11:04 UTC, alsoandanswer approved these changes
I hope these have proper construction/crafting recipes

2024-03-17 22:01 UTC, NonQueueingMatt approved these changes

2024-03-18 01:01 UTC, merged