Prevents ghosts from calling elevators
Aurorastation/Aurora.3 pull request #18334
Opened 2024-01-31 20:09 UTC by hazelrat

Prevents ghosts from calling elevators using elevator buttons.

I assume there's way better ways to handle this. Notably, this prevents admin ghosts from using elevator buttons as well as regular ghosts. Elevator panels, like the ones in operations, have a TGUI interface that can't be opened by ghosts at all, but can be used by admins.

Resolves https://github.com/Aurorastation/Aurora.3/issues/18330

2024-01-31 20:10 UTC, hazelrat commented
!bugfix

2024-01-31 20:10 UTC, hazelrat commented
!review

2024-02-01 15:59 UTC, alsoandanswer approved these changes

2024-02-01 18:57 UTC, FluffyGhoster commented on code/modules/turbolift/turbolift_console.dm
> +		return
```suggestion
```

2024-02-01 18:57 UTC, FluffyGhoster commented on code/modules/turbolift/turbolift_console.dm
> +
```suggestion
```

2024-02-01 23:17 UTC, NonQueueingMatt requested changes

2024-02-01 23:17 UTC, NonQueueingMatt commented on code/modules/turbolift/turbolift_console.dm
> +	if(check_rights(R_ADMIN))
```suggestion
	if(check_rights(R_ADMIN, FALSE, user))
```

2024-02-05 21:15 UTC, merged