Adds new Golden Deep Energy Pistol and gives it to Consular and Representative
Aurorastation/Aurora.3 pull request #18343
Opened 2024-02-02 22:28 UTC by Ben10083

New Golden Deep Energy Pistol with one unique mode: Disorient
Disorient: weaker stun but applies effects such as slurring and dizzy

TODO:
- [ ] Name/desc/lore misc. For item
- [ ] Disorient Projectile sprite
- [ ] Weapon Sprite
- [ ] Disorient projectile sound (maybe)
- [ ] Add confusion?

* Please describe the intent of your changes in a clear fashion.
* Please make sure that, in the case of mapping changes, you include images of these changes in the PR's description.
* Please make sure to mark your PR as wip or review required by making a comment with !wip or !review required
* If you include sprites/sounds/... (assets) that you have not created yourself specify the license and original author below.
  * Ensure that you also credit them in the appropriate location / changelog as specified in the contributor guidelines

### Asset Licenses
The following assets that **have not** been created by myself are included in this PR:

| Path | Original Author | License |
| --- | --- | --- |
| icons/example.dmi | ExamplePerson (Example Station) | CC0 |

2024-02-02 22:28 UTC, Ben10083 commented
!wip

2024-02-03 01:16 UTC, Ben10083 commented
Going to have the SCC beam used for disorient. A dedicated projectile sprite may be made in the future if my comrade is able to.

2024-02-03 01:16 UTC, Ben10083 commented
!review

2024-02-03 01:18 UTC, Ben10083 commented
![image](https://github.com/Aurorastation/Aurora.3/assets/91219575/22bbf5de-7d86-4f7e-b5dc-792d0f9eb643)

2024-02-06 22:19 UTC, DreamySkrell commented
Should not be using the SCC projectile sprite

2024-02-06 22:22 UTC, DreamySkrell commented
Does the disorienting work on both humans and IPCs? Reading the code it applies the effects to `/mob/living/carbon/human` which includes IPCs. I don't think the effects would make sense to apply to IPCs (if they do).

2024-02-08 12:41 UTC, NonQueueingMatt requested changes

2024-02-08 12:41 UTC, NonQueueingMatt commented on code/modules/projectiles/projectile/beams.dm
> +			H.druggy += 15
this should be capped at 75
`H.druggy = min(H.druggy + 15, 75)`

2024-02-08 12:41 UTC, NonQueueingMatt commented on code/modules/projectiles/projectile/beams.dm
> +			H.make_dizzy(50)
as above, check that it doesn't go over 250

2024-02-08 12:41 UTC, NonQueueingMatt commented on code/modules/projectiles/projectile/beams.dm
> +			H.slurring += 15
as above

2024-02-15 03:43 UTC, FluffyGhoster commented on code/modules/projectiles/guns/energy/nuclear.dm
> +	item_state = "golden_deep_ornatepistolstun100"
The file already says it's golden deep, there's no point in the icon state repeating this info

2024-02-15 03:43 UTC, FluffyGhoster commented on code/modules/projectiles/guns/energy/nuclear.dm
> +	modifystate = "golden_deep_ornatepistolstun"
As above

2024-02-15 17:29 UTC, FluffyGhoster approved these changes

2024-02-15 17:31 UTC, NonQueueingMatt approved these changes

2024-02-15 17:43 UTC, merged