Adds new foods, fixed food bug and 1 food tweak
Aurorastation/Aurora.3 pull request #18356
Opened 2024-02-04 07:15 UTC by tomixcomics

Adds the following foods:
-Fries Olympia
-Fries Olympia with cheese
-Custard
-Creme Brulee (Thanks Sue and Girdo for helping out with this one!)
-Angry Bread
-Eggs Benedict

Corrects the missing Eggpop icon

Nerfs how often Praline Boxes show up in maintenance

2024-02-04 07:26 UTC, tomixcomics commented
!review

2024-02-06 22:18 UTC, DreamySkrell requested changes
code looks fine
ping me on discord when issues are solved and I'll approve

2024-02-06 22:18 UTC, DreamySkrell commented on code/modules/cooking/recipes/recipes_breads.dm
> +		var/obj/item/XMG = thing
No all-uppercase variable names (like `XMG` here). Reason is consistency, vars should have all-lowercase names, and all-uppercase names are reserved for macros.

2024-02-06 22:18 UTC, DreamySkrell commented on code/modules/cooking/recipes/recipes_breads.dm
> +		var/obj/item/XMG = thing
Though, I'm pretty sure this XMG var could just be removed and the loop defined like `for(var/obj/item/thing in results)`

2024-02-08 10:56 UTC, DreamySkrell approved these changes

2024-02-08 12:30 UTC, NonQueueingMatt approved these changes

2024-02-08 14:14 UTC, merged