Makes journals recolourable, and adds them to the loadout so they're accessible to anyone
Aurorastation/Aurora.3 pull request #18366
Opened 2024-02-07 15:14 UTC by Llywelwyn

![image](https://github.com/Aurorastation/Aurora.3/assets/82828093/49bb0939-5bbf-4a22-8279-bf844c8a32b5)

this item has existed for 2 years as an almost objectively nicer to use folder/clipboard, after being made as a base item for a custom player item back in the day for a player that no longer plays (to my knowledge). the custom item itself (with a custom sprite, etc.) still exists how it was and has been unchanged

the changes here just make the base journal support recolouring and add it to the loadout so anyone can access it

2024-02-07 15:37 UTC, alsoandanswer requested changes
put the sprite in library.dmi please

2024-02-07 15:52 UTC, Llywelwyn commented
should be what you were after[?], sprites are wizardry to me

2024-02-07 16:21 UTC, DreamySkrell commented
I think the sprite is way too big - it's (almost?) bigger than a table, so it's going to be very awkward to use.

2024-02-08 10:17 UTC, alsoandanswer approved these changes

2024-02-08 10:54 UTC, DreamySkrell approved these changes

2024-02-11 20:22 UTC, merged