Adds a handheld microphone for Journalists
Aurorastation/Aurora.3 pull request #18380
Opened 2024-02-09 06:16 UTC by feartheblackout

Resprited from the stage microphone to not have an animation and have the head be black.

2024-02-09 06:16 UTC, feartheblackout commented
!review

2024-02-11 13:51 UTC, Arrow768 requested changes
See CI Output -> Changes required

2024-02-15 18:50 UTC, Arrow768 approved these changes

2024-02-17 11:38 UTC, NonQueueingMatt approved these changes

2024-02-17 11:58 UTC, merged