Point Verdant last minute bugfixes (chapter 1)
Aurorastation/Aurora.3 pull request #18403
Opened 2024-02-12 10:25 UTC by kyres1

- bugfix: "Fixed invisible shelving on Point Verdant."
  - bugfix: "Fixed nonfunctioning animations on the Haneunim title screen."
  - tweak: "Disabled Point Verdant's rain due to missing functionality."

2024-02-12 10:25 UTC, kyres1 commented
!bugfix

2024-02-12 11:22 UTC, NonQueueingMatt requested changes

2024-02-12 11:22 UTC, NonQueueingMatt commented on maps/away/away_site/konyang/point_verdant/point_verdant_areas.dm
> +//	add_overlay(image("icon"='icons/effects/rain_effects.dmi',"icon_state"="rain","layer"=MOB_LAYER+0.1))
remove, don't comment

2024-02-12 11:22 UTC, NonQueueingMatt commented on maps/away/away_site/konyang/point_verdant/point_verdant_areas.dm
> +//	add_overlay(image("icon"='icons/effects/rain_effects.dmi',"icon_state"="rain","layer"=MOB_LAYER+0.1))
remove, don't comment

2024-02-12 17:21 UTC, Greenjoe12345 commented on code/modules/tables/rack.dm
> +	icon_state = "shelf_alt"
Shouldn't this be on a subtype of the shelves, so both types of shelf icon are usable?

2024-02-14 12:52 UTC, NonQueueingMatt approved these changes

2024-02-14 12:52 UTC, NonQueueingMatt commented
!review

2024-02-15 18:48 UTC, Arrow768 approved these changes

2024-02-16 03:08 UTC, merged