password-locked ghostroles
Aurorastation/Aurora.3 pull request #18414
Opened 2024-02-14 20:48 UTC by RustingWithYou

Ghostroles can now have a password set, which is required to join as them. This is largely intended for allowing event ghostroles to be restricted to volunteers as was done in the recent Exclusionist event.

2024-02-14 20:48 UTC, RustingWithYou commented
!review

2024-02-15 00:01 UTC, NonQueueingMatt requested changes

2024-02-15 00:01 UTC, NonQueueingMatt commented on code/controllers/subsystems/ghostroles.dm
> +				var/password = input(usr, "Input Password:", "Ghost Spawner")
tgui_input

2024-02-15 03:51 UTC, FluffyGhoster commented on code/modules/ghostroles/spawner/base.dm
> +	var/password = null
The issue here is, event maps are submitted in the repo then testmerged; as this password is defined in the code itself, anyone who can see the repo (so everyone) see this, which makes it kind of the equivalent of this:

![image](https://github.com/Aurorastation/Aurora.3/assets/65877598/72e2043a-8876-4661-83ba-8c6bfab42ee2)

If ghost roles needs passwords for events, it should have some sort of UI element visible only to admins where you can input the password before starting the round, or load them from some config file that the host sets (the former is probably preferrable), or something of the likes, I think

2024-02-15 12:30 UTC, Arrow768 requested changes
This needs to be implemented in a secure way.

The current implementation with the password committed in the repo is not.

Preferably a config file that can be used to PW restrict a ghost role.

But I question if a different implementation wouldn't be better.
-> Add a button to the ghost role gui that allows someone with appropriate permissions to select a specific ghost to be spawned.

2024-02-16 08:38 UTC, RustingWithYou commented
Closing until I can figure out a more secure implementation

2024-02-16 08:38 UTC, closed without merging