Buffs Jeweler Cockatoo's HP to 300
Aurorastation/Aurora.3 pull request #18460
Opened 2024-02-19 00:31 UTC by lavillastrangiato

Title. Another day, another banger.

2024-02-19 00:31 UTC, lavillastrangiato commented
!review

2024-02-19 01:03 UTC, FluffyGhoster commented on html/changelogs/Lavillastrangiato - rules of nature.yml
> +  - Tweak: "Buffs jeweler cockatoo's HP to 300."
```suggestion
  - tweak: "Buffs jeweler cockatoo's HP to 300."
```

2024-02-19 01:44 UTC, SleepyGemmy requested changes

2024-02-19 01:44 UTC, SleepyGemmy commented on html/changelogs/SleepyGemmy-bridge_maint_apc.yml
don't touch this file.

2024-02-19 07:48 UTC, NonQueueingMatt approved these changes

2024-02-23 02:56 UTC, SleepyGemmy approved these changes

2024-02-23 15:54 UTC, merged