Rental bike mechanics
Aurorastation/Aurora.3 pull request #18466
Opened 2024-02-19 18:55 UTC by DreamySkrell

![image](https://github.com/Aurorastation/Aurora.3/assets/107256943/de27d491-040e-4ebe-abc5-f5d34fa18744)

- needs https://github.com/Aurorastation/Aurora.3/pull/18457 to be merged first
- can "buy" a bike key - actually rent it for a day
- 50cr for a moped, 200cr for a sports bike

2024-02-19 18:55 UTC, DreamySkrell commented
!wip

2024-02-19 19:16 UTC, GMR25 commented
Is there any risk of shenanigans if the round occurs during an IC day change? It might be helped by a receipt that includes the time of purchase and ID of the buyer.

2024-02-19 19:39 UTC, DreamySkrell commented
> Is there any risk of shenanigans if the round occurs during an IC day change? It might be helped by a receipt that includes the time of purchase and ID of the buyer.

![image](https://github.com/Aurorastation/Aurora.3/assets/107256943/08064c5e-65ef-4f04-b8e2-de3ad8e61701)

it expires in 24 hours from purchase

2024-02-21 17:54 UTC, DreamySkrell commented
!review

2024-02-21 18:07 UTC, FluffyGhoster requested changes

2024-02-21 18:07 UTC, FluffyGhoster commented on code/modules/modular_computers/hardware/hard_drive.dm
> +		file.hard_drive = null
This isn't correct, if the hard drive is deleted, the programs it contains should be cleanly deleted too, not left hanging unlinked

2024-02-22 14:12 UTC, DreamySkrell commented on code/game/machinery/vending.dm
> +/obj/machinery/vending/proc/build_products()
should not sleep
doesn't have to be pure

2024-02-22 14:16 UTC, DreamySkrell commented on code/game/machinery/vending.dm
> +/// To be overriden if vended out products need any post-processing.
done

2024-02-22 14:16 UTC, DreamySkrell commented on code/game/machinery/vending.dm
> +/obj/machinery/vending/proc/vended_product_post(var/obj/vended)
done

2024-02-22 14:16 UTC, DreamySkrell commented on code/game/machinery/vending_types.dm
> +	var/list/key_data_sports = list()
done

2024-02-22 14:17 UTC, DreamySkrell commented on code/game/machinery/vending_types.dm
> +	products[/obj/item/key/bike/sport] = key_data_sports.len
done

2024-02-22 14:17 UTC, DreamySkrell commented on code/game/machinery/vending_types.dm
> +	// expires the next day
done

2024-02-22 14:17 UTC, DreamySkrell commented on code/game/machinery/vending_types.dm
> +	if(key_data_mopeds && istype(key, /obj/item/key/bike/moped))
done

2024-02-22 18:08 UTC, NonQueueingMatt approved these changes

2024-02-22 20:05 UTC, FluffyGhoster approved these changes

2024-02-22 20:36 UTC, Arrow768 approved these changes

2024-02-22 20:48 UTC, merged