The Xanu Frigate
Aurorastation/Aurora.3 pull request #18516
Opened 2024-02-24 04:13 UTC by nauticall

WIP.

Adds the All-Xanu Spacefleet Shrike-class frigate, a comparatively colossal warship in service with Xanu Prime's navy. Built for combat, it has a myriad of features designed to make it stand toe-to-toe against most enemy combatants.

It features:

- Separate navigation bridge and CIC, a la the Horizon's command bunker. The CIC has its own air and power supply.
- Redundant thruster nacelles; even if one nacelle is destroyed, the ship can continue operating on a single one.
- Two fusion reactors. The power required by this thing is just that huge.
- Thiccccc armor plating and whipple shields made of grating to protect against meteor and dust strikes.
- A Longbow and Grauwolf.
- A fightercraft shuttle, with a Francisca.
- A boarding shuttle.
- Fully-stocked medbay with operating room.
- A brig.

The ghostrole capacity for this is 7 (6 crew + 1 captain), but has capacity for all the way up to 15 (14 crew + 1 captain) during events.

The intended purpose of this frigate is twofold: a reduced-power "patrol" configuration for light skirmishes, and a full-armament "battle" configuration so that the frigate can act as an offship ERT in case the Horizon gets into trouble, either against another party or against the Coalition. If used in its battle configuration it can support 15 crew at full capacity.
<details>
<summary>Screenshots</summary>

![image](https://github.com/Aurorastation/Aurora.3/assets/55491249/8c8ade90-947e-49c8-b710-0997fcf1cb0f)
![image](https://github.com/Aurorastation/Aurora.3/assets/55491249/c105e515-abf4-42b1-8f8d-d8de5d6692fc)
![image](https://github.com/Aurorastation/Aurora.3/assets/55491249/e165eb14-6976-472a-b6ab-e243eca9d4ec)
![image](https://github.com/Aurorastation/Aurora.3/assets/55491249/b811e586-cb75-467b-ba38-2c737221d69e)
![image](https://github.com/Aurorastation/Aurora.3/assets/55491249/b198b50c-7753-4aaa-839e-eb57a6bcedec)
![image](https://github.com/Aurorastation/Aurora.3/assets/55491249/00029766-664c-41d0-b075-05cdca325dff)
![image](https://github.com/Aurorastation/Aurora.3/assets/55491249/bf552c19-7c3d-4d5d-b713-916e3e0b2de3)
![image](https://github.com/Aurorastation/Aurora.3/assets/55491249/3d92a57d-bb72-4c53-86de-fe218c5fe439)

</details>

2024-03-27 12:59 UTC, nauticall commented
!review

2024-03-28 16:07 UTC, Eyeveri requested changes
Hello! 

I went through the ship and it looks phenomenal. The code looks great to me as well, I didn't find any errors when I was testing it. 

However there are a few things that need to be adjusted. 

First - 
Ignore what I said about lockers, but I agree with dreamy. This is too powerful of a loadout for a third party ship. I would rather see this be in an ERT/Event type vessel. 
![code into lockers please](https://github.com/Aurorastation/Aurora.3/assets/98699252/e9de6900-92f6-41d6-8bc8-f15ca7b6b7e5)
![CodeIntoLockers](https://github.com/Aurorastation/Aurora.3/assets/98699252/68cab9fe-6695-4fce-abd1-68b8ccca02de)

Second - I did not see an IPC recharger anywhere. I might have missed it, but if there isn't one, please add one. 

Third - 
A lot of decals are missing under the doors. I did not see a single caution decal under the airlocks around the ship. Please add those. 
![decals](https://github.com/Aurorastation/Aurora.3/assets/98699252/3cf948d3-1916-4b0c-a18a-5bd5263924b0)
![NeedsDecals](https://github.com/Aurorastation/Aurora.3/assets/98699252/23f00afa-dec1-4300-9e6a-9c7be2e11508)

Fourth - This is minor, but the surgical console in the medical bay is backwards so you can see the wiring. Please flip it to face north. 
![FlipConsole](https://github.com/Aurorastation/Aurora.3/assets/98699252/6306c8ce-cdce-47ab-a714-8064c8b2213e)

Fifth - The Security vendor needs to have it's access updated so that the crew can use it. Also, I forgot to check the suit modifying machines, but please make sure your ghost roles can use those too. 
![needs access](https://github.com/Aurorastation/Aurora.3/assets/98699252/44d01dd1-fa6d-4f4d-8eb6-bdd688554d4f)

Lastly, and this one isn't required, but consider putting the "gold" CE border around the wood tiles on the ship, like here for example. 
![ConsiderWoodBorders](https://github.com/Aurorastation/Aurora.3/assets/98699252/824637e6-788f-4bde-a9e2-30e080ff10f4)

All in all, great work. Address these and I'll approve them afterwards.

2024-03-28 16:10 UTC, DreamySkrell commented on maps/away/ships/xanu/xanu_frigate.dm
> +	template_flags = TEMPLATE_FLAG_SPAWN_GUARANTEED
.

2024-03-28 16:13 UTC, DreamySkrell commented on code/game/objects/structures/window.dm
> +/obj/structure/window/full/reinforced/ultra
remove this definition, not really needed, and definitely for use ONLY by this xanu ship and not any other

2024-03-28 16:14 UTC, DreamySkrell commented on code/game/objects/structures/full_window_frame.dm
> +/obj/structure/window_frame/shuttle/coalition
remove, and use new system of `/obj/effect/map_effect/window_spawner/full/shuttle`, more on this below

2024-03-28 16:16 UTC, DreamySkrell commented on code/modules/effects/map_effects/window_spawner.dm
> +/obj/effect/map_effect/window_spawner/full/reinforced/coalition
these should all be a subtype of `/obj/effect/map_effect/window_spawner/full/shuttle`
icon states and grille/firedoor/etc subtypes are fine to keep for ease of use
`frame_path` should be normal window frames
`frame_color` set to `COLOR_COALITION`
`window_path` should be either normal reinforced or borosilicate, but I would prefer normal

2024-03-28 16:17 UTC, DreamySkrell commented
![image](https://github.com/Aurorastation/Aurora.3/assets/107256943/1de842d7-d0fc-4ce1-9753-85c3f223adca)
these already are MRE rations crates, why map in even more MREs into them?

2024-03-28 16:24 UTC, DreamySkrell commented
![image](https://github.com/Aurorastation/Aurora.3/assets/107256943/7e0e0fa0-8349-4cf1-9ad3-c82e0d4da940)
way too powerful ammo for the longbow - normal primers, lots of HE warheads, bunker busters
compare to gadpathur ship with only 4 low power primers and HE/AP warheads

2024-03-28 16:27 UTC, DreamySkrell commented
![image](https://github.com/Aurorastation/Aurora.3/assets/107256943/a6d6ebdb-c29b-458c-a6c8-4ed57c6139ec)

2024-03-28 16:29 UTC, DreamySkrell commented
![image](https://github.com/Aurorastation/Aurora.3/assets/107256943/d742628a-f46a-4dc4-97d9-baab631ae907)
do not route wires to EVERY window
the ship should

2024-03-28 16:33 UTC, DreamySkrell commented
`/obj/machinery/shipsensors/strong` should be reserved for SCC ships, or survey or the like ships
use the normal sensors

2024-03-28 16:40 UTC, DreamySkrell commented
![image](https://github.com/Aurorastation/Aurora.3/assets/107256943/faa6bc03-bbed-4378-b60c-f99e77d032ba)
remove the turrets - same thing as about the wires under windows

2024-03-31 01:07 UTC, Eyeveri approved these changes
All changes that were requested have been met. 

I think this ship is going to be a great addition, good work!

2024-04-04 09:19 UTC, DreamySkrell approved these changes

2024-04-08 16:09 UTC, Eyeveri approved these changes

2024-04-08 16:14 UTC, alsoandanswer approved these changes
Sprites look fine

2024-04-14 12:21 UTC, merged