Point Verdant Delivery Points
Aurorastation/Aurora.3 pull request #18531
Opened 2024-02-26 01:52 UTC by Ben10083

Additional Point Verdant Cargo Delivery Points added

- Hotel
- Up!Burger
- Corporate Docks

2024-02-26 01:52 UTC, Ben10083 commented
!review

2024-02-26 12:34 UTC, NonQueueingMatt approved these changes

2024-02-26 13:02 UTC, DreamySkrell requested changes
Did you test this in game? Are the different delivery points actually functional? Do they show as different delivery points on the packages? Or can a package be delivered to any point?

2024-02-26 13:44 UTC, DreamySkrell requested changes
The packages should show which delivery point they are for, not just by coords. A package to the hotel or whatever should show it is for the hotel, and not for the spaceport (with hotel coords).

This should be done with a var like `override_name` on the delivery point (and if it is null, it should use the default name of the ship or away site).

2024-02-26 14:32 UTC, Ben10083 commented
![image](https://github.com/Aurorastation/Aurora.3/assets/91219575/fe0863c3-4241-46d6-9bff-40d7e6d65d9a)
new functionality for names and payment modifier

2024-02-26 19:24 UTC, Ben10083 commented on code/modules/cargo/delivery/package.dm
> +	var/delivery_site = "Unknown"
no

2024-02-27 22:43 UTC, DreamySkrell commented on code/modules/cargo/delivery/package.dm
> +	var/delivery_site = "Unknown"
How does this affect packages outside of konyang? They shouldn't just always say "Unknown" or whatever. This should be documented too.

2024-02-27 23:27 UTC, Ben10083 commented on code/modules/cargo/delivery/package.dm
> +	var/delivery_site = "Unknown"
Added extra documentation for clarification. Receptacle can replace the delivery_site, and it falls back on away site name if override_name isnt set in receptacle.

This is similar to how it works before, minus the override_name option

![image](https://github.com/Aurorastation/Aurora.3/assets/91219575/e473dcb5-dfa4-452f-aa3d-4a4d85bd9419)

2024-02-28 19:15 UTC, DreamySkrell approved these changes

2024-02-29 02:05 UTC, alsoandanswer approved these changes

2024-02-29 19:15 UTC, merged