Dominian Corvette Remap
Aurorastation/Aurora.3 pull request #18546
Opened 2024-02-26 17:28 UTC by lavillastrangiato

Remapping the Dominian corvette. PR is a WIP and will be updated as it progresses.

To do:
- Get all the rooms filled in
- APCs, alarms
- Pipes
- Wires
- Add a reactor
- Areas
- Add all the new Dominian guns
- Add ship weapons
- No CIC, we die like men
- Trim some of the ghostrole descriptions

2024-02-27 04:34 UTC, lavillastrangiato commented
!wip

2024-03-01 03:04 UTC, lavillastrangiato commented
!review

2024-03-02 17:17 UTC, DreamySkrell commented
![image](https://github.com/Aurorastation/Aurora.3/assets/107256943/9715b1d7-e84d-4a42-926a-db4cd5d63efe)
don't put APCs or air alarms on top of shutters / blast doors / firedoors
also don't put APCs / air alarms on top of / under signs

2024-03-02 17:22 UTC, DreamySkrell commented
![image](https://github.com/Aurorastation/Aurora.3/assets/107256943/523cf158-3d28-48f4-b61e-d654032c4b05)
![image](https://github.com/Aurorastation/Aurora.3/assets/107256943/b0aa56f4-ece5-484a-84f2-81a8b3a26056)
Windows on thrusters, or thrusters being visible from inside of the ship, is a very old mapping style. It looks bad, and makes no sense.

2024-03-02 17:24 UTC, DreamySkrell commented
![image](https://github.com/Aurorastation/Aurora.3/assets/107256943/c0de1d9a-24e3-4e97-b12b-6611a72b8890)
scrubbers are routing waste air into a full air canister and tank
scrubbers should put waste air into empty canisters

2024-03-02 17:26 UTC, DreamySkrell commented
![image](https://github.com/Aurorastation/Aurora.3/assets/107256943/98b78861-592a-48c2-a8ae-98184de426fd)
this dock is not compliant with the docks standards

2024-03-02 17:29 UTC, DreamySkrell commented
![image](https://github.com/Aurorastation/Aurora.3/assets/107256943/2e7f674e-2791-4bc6-9d23-2b2c96cfe77b)
fax machine should have `department` var set (example from horizon)

2024-03-02 17:30 UTC, DreamySkrell requested changes
ping me when ready for review

2024-03-03 00:16 UTC, lavillastrangiato commented
![image](https://github.com/Aurorastation/Aurora.3/assets/63124803/cfaff4d5-33b2-4220-9d95-930479932376)
The pressure tank connected to the scrubbers starts with 2500kpa and is copied from the Elyran corvette, but I have edited the starting pressure to be 0kpa so it can fill properly.

Otherwise it is fine to be reviewed. @DreamySkrell

2024-03-03 16:00 UTC, DreamySkrell commented
![image](https://github.com/Aurorastation/Aurora.3/assets/107256943/8a596dbf-8854-4269-9152-f84e8f9ca31e)
tests fail here

2024-03-03 16:05 UTC, DreamySkrell commented
![image](https://github.com/Aurorastation/Aurora.3/assets/107256943/e326dcd8-f50a-45c2-a934-4cc83103878e)
the transit area thingy is only necessary for the shuttle, not the ship
it is used when a shuttle is jumping between two landmarks

![image](https://github.com/Aurorastation/Aurora.3/assets/107256943/f8fc51be-8879-4782-ab75-0a34bb13fc6e)
the shuttle transit area is too small for the shuttle

2024-03-03 16:09 UTC, DreamySkrell commented
![image](https://github.com/Aurorastation/Aurora.3/assets/107256943/162e6e88-ada3-4014-89a1-4074a23af7ca)
do not use the `/obj/machinery/atmospherics/pipe/tank` type, it does not initialize correctly
and do not edit the pressure in the map, create a new `/obj/machinery/atmospherics/pipe/tank/air/empty` subtype and use that instead

![image](https://github.com/Aurorastation/Aurora.3/assets/107256943/4e615dbd-25c2-462c-986d-48d0ba32ecf1)
I do not see any vars changed on this canister. It should be the empty yellow canister instead.

2024-03-03 16:15 UTC, DreamySkrell commented
![image](https://github.com/Aurorastation/Aurora.3/assets/107256943/808de57e-84a2-4aeb-ac3a-a9e35ff84191)
![image](https://github.com/Aurorastation/Aurora.3/assets/107256943/be3a321b-0d29-40f7-bf33-8b006e76abeb)
![image](https://github.com/Aurorastation/Aurora.3/assets/107256943/a1e8c579-4bfc-4851-bad7-abc4947664ae)
![image](https://github.com/Aurorastation/Aurora.3/assets/107256943/ba2eafa4-7a58-4dab-9d9d-b64350495bea)

there is a lot of wall-mounted things overlapping

2024-03-03 16:18 UTC, DreamySkrell commented
![image](https://github.com/Aurorastation/Aurora.3/assets/107256943/1fc1c3d2-d400-40b2-bfed-134005b6757c)
this airlock sensor is placed on the door (1), so it's not going to work properly, and sense the door atmosphere (which is static if the door is closed)
it should be on the exterior tile (2)

2024-03-03 16:19 UTC, DreamySkrell commented
![image](https://github.com/Aurorastation/Aurora.3/assets/107256943/7a10537c-3bd4-47af-a967-c4a174d3d9aa)
these should all be airless tiles

2024-03-03 16:19 UTC, DreamySkrell commented
all the plating tiles are `/turf/simulated/floor`
they should be `/turf/simulated/floor/plating` instead

2024-03-03 16:22 UTC, DreamySkrell commented
![image](https://github.com/Aurorastation/Aurora.3/assets/107256943/f8c06a5f-49b9-4916-a4c6-34a49bf8d4bf)
entry points on the shuttle are wrong, and it does not have an aft entry point

the ship itself does not have any entry points at all

2024-03-03 16:24 UTC, DreamySkrell commented
![image](https://github.com/Aurorastation/Aurora.3/assets/107256943/0f3ea851-d980-4e5b-a083-7d5a541488a2)

from: <https://forums.aurorastation.org/topic/19916-dreamys-mapping-tips-and-guidelines/#comment-172873>

> Avoid "fake objects", and generally avoid changing vars like icons or icon_states. It may be fine at first, but if the icon paths or icon states change in the future, these fake objects will be broken. Prefer creating new types for things like fake props.

2024-03-03 16:28 UTC, DreamySkrell commented
ensign's bathroom has access list(203) while all the other doors have list(212) or none

2024-03-03 16:32 UTC, DreamySkrell commented
![image](https://github.com/Aurorastation/Aurora.3/assets/107256943/3d14b447-296c-4b86-9644-798831e7e165)
space tiles under windows

2024-03-03 16:34 UTC, DreamySkrell commented
![image](https://github.com/Aurorastation/Aurora.3/assets/107256943/67d17048-fccb-41e7-a3d6-2696f60ae26b)
there are 7 ghostroles in total, but I see only 4 spawns on the map - can all of the roles spawn and not run out of spawn points?

2024-03-03 16:36 UTC, DreamySkrell commented
![image](https://github.com/Aurorastation/Aurora.3/assets/107256943/0b1d565f-2d0a-42dc-9455-ed8064d759c2)
apc on top of a shutter
also not connected to wire net

2024-03-03 16:39 UTC, DreamySkrell commented
![image](https://github.com/Aurorastation/Aurora.3/assets/107256943/2ff0c522-076a-4c9b-96d3-e0db8efcf2ba)
a lot of the lights have icon state set for no reason

![image](https://github.com/Aurorastation/Aurora.3/assets/107256943/9d0ac28d-0d89-4081-a076-a508d820f92a)
some lights have icon state set AND inserted light
`/obj/machinery/light/colored/blue` should be used instead

2024-03-03 16:39 UTC, DreamySkrell commented
the fax machine still needs to be fixed

2024-03-04 00:15 UTC, lavillastrangiato commented
@DreamySkrell All of the fixes except the spawnpoints have been addressed. As people never immediately use all spawns at once, I'm not concerned about "blocked" spawns. If someone happened to be occupying a spawnpoint anyway, the next person would just spawn on top of them.

The only problem seems to be an issue with the Lammergeier but I have no idea what could be going on with it.

2024-03-04 01:18 UTC, DreamySkrell commented
> @DreamySkrell All of the fixes except the spawnpoints have been addressed. As people never immediately use all spawns at once, I'm not concerned about "blocked" spawns. If someone happened to be occupying a spawnpoint anyway, the next person would just spawn on top of them.
> 
> The only problem seems to be an issue with the Lammergeier but I have no idea what could be going on with it.

I didn't mean if they can be blocked

I meant do they get "used up"

I don't remember and forgot to check it today, if spawn points get "used up" and removed, if someone uses the ghost spawners that use these spawn points

idk now that I think of it, I don't think they get used up

2024-03-07 00:05 UTC, lavillastrangiato commented
> idk now that I think of it, I don't think they get used up

They don't, I've mapped in the same spawnpoints on the HICS Etna before and people spawned in those on the same tiles.

Pls take off changes required or LMK what's wrong with the cannon @DreamySkrell

2024-03-08 15:00 UTC, DreamySkrell commented
![image](https://github.com/Aurorastation/Aurora.3/assets/107256943/1f4d5ddf-8e92-4db7-ba00-06234f31efd3)

entry points still wrong on the shuttle
for example on this one it is named `fore, cockpit`, but the type is `/aft`

2024-03-08 15:06 UTC, DreamySkrell commented
![image](https://github.com/Aurorastation/Aurora.3/assets/107256943/ddaa9cee-7873-400d-b7df-2cedd248c588)
the transit area way too big, it should only be big enough for the shuttle and ~7 tiles to the edge of it from the shuttle

![image](https://github.com/Aurorastation/Aurora.3/assets/107256943/2e409c88-1fee-4b82-887a-c30b3a5d82c9)
like for example here

2024-03-12 00:58 UTC, lavillastrangiato commented
@DreamySkrell please review my pr when convenient

2024-03-13 22:59 UTC, DreamySkrell commented
![image](https://github.com/Aurorastation/Aurora.3/assets/107256943/bf232943-edbd-43a1-b1d9-35b75a3f5a12)
missing pipe here

2024-03-13 23:06 UTC, DreamySkrell commented on maps/away/ships/dominia/dominian_corvette/dominian_corvette_ghostroles.dm
> +	accessory = /obj/item/clothing/accessory/dominia
member var can be set only once
only the second one will be used here

2024-03-13 23:14 UTC, DreamySkrell commented
![image](https://github.com/Aurorastation/Aurora.3/assets/107256943/b992b4ec-d4d0-474e-b41b-2b5984b40cd1)
this locker has too many items, it's going to lag a bit when right clicking it

![image](https://github.com/Aurorastation/Aurora.3/assets/107256943/75dc2f4d-739e-424c-a565-ce7de5b3cf11)
could add a second locker for example here, and split the items between them

also add some spare uniforms, boots, hats, whatever else the ghostroles get

2024-03-13 23:14 UTC, DreamySkrell commented
fix the above, ping me on discord, and I'll approve

2024-03-14 04:39 UTC, SleepyGemmy approved these changes

2024-03-18 16:52 UTC, DreamySkrell commented
still need spare uniforms

2024-03-18 18:04 UTC, DreamySkrell commented
![image](https://github.com/Aurorastation/Aurora.3/assets/107256943/7fcba1bb-fd37-4b03-8285-ae5b9c2d070f)
missing pipe here still

2024-03-21 20:58 UTC, DreamySkrell approved these changes

2024-03-24 22:21 UTC, merged