Refactored MouseDrop_T
Aurorastation/Aurora.3 pull request #18549
Opened 2024-02-26 21:47 UTC by FluffyGhoster

Refactored MouseDrop_T to not be inside a spawn async and respect the function header.

2024-02-26 22:01 UTC, FluffyGhoster commented
!review

2024-02-26 23:35 UTC, NonQueueingMatt requested changes

2024-02-26 23:35 UTC, NonQueueingMatt commented on code/game/gamemodes/cult/structures/pylon.dm
> +	if(istype(, /mob/living))
i think you meant istype(dropping) here

2024-02-27 11:59 UTC, alsoandanswer approved these changes

2024-02-29 22:10 UTC, merged