Ire of the Betrayed - The Hiskyn Revanchist Ship
Aurorastation/Aurora.3 pull request #18550
Opened 2024-02-26 22:00 UTC by RustingWithYou

Adds a [Hiskyn's Revanchists](https://wiki.aurorastation.org/index.php?title=Unathi_Piracy#Hiskyn's_Revanchists) pirate ship, complete with ghostroles. Also moves the Izharshan and Tarwa pirate ships from the away sites to ships folder.

2024-02-26 22:00 UTC, RustingWithYou commented
!review

2024-02-29 17:35 UTC, NonQueueingMatt approved these changes

2024-02-29 22:07 UTC, DreamySkrell commented
![image](https://github.com/Aurorastation/Aurora.3/assets/107256943/282041f0-b9a1-4e9b-b546-cc98bb8e626a)
![image](https://github.com/Aurorastation/Aurora.3/assets/107256943/ab849ca0-49df-4bd0-ab98-4fe65edd5a2e)
![image](https://github.com/Aurorastation/Aurora.3/assets/107256943/e3daad17-43ce-4578-b0ee-f7dfb4ad011e)

shuttle is not compliant with dock/shuttle standards

also the two air tanks on the shuttle don't seem to be connected to anything

2024-02-29 22:08 UTC, DreamySkrell commented
![image](https://github.com/Aurorastation/Aurora.3/assets/107256943/6abd06e3-c025-4f4b-8d02-cb864d5066f9)

the center hallway should have some firedoors dividing it into parts

2024-02-29 22:10 UTC, DreamySkrell commented
![image](https://github.com/Aurorastation/Aurora.3/assets/107256943/3c2c5345-7ce3-4b1c-9400-dbc5589d3c98)
the landmarks should have types and names that are more informative

instead of:
```
/obj/effect/shuttle_landmark/hiskyn/dock4
	name = "Aft Port Dock"
	landmark_tag = "nav_hiskyn_dock4"
```
should be:
```
/obj/effect/shuttle_landmark/hiskyn/dock/aft_port
	name = "Aft Port Dock"
	landmark_tag = "nav_hiskyn_dock_aft_port"
```

2024-02-29 22:11 UTC, DreamySkrell commented
![image](https://github.com/Aurorastation/Aurora.3/assets/107256943/0f24eac9-0610-40f7-86d1-8ee50884b2ee)
the engine nacelles are sad and empty
put some trash, empty crates, materials, supplies, a tool on a table, etc

2024-02-29 22:12 UTC, DreamySkrell commented
![image](https://github.com/Aurorastation/Aurora.3/assets/107256943/749ad1ec-ac63-4720-bb72-21798201a0f8)
![image](https://github.com/Aurorastation/Aurora.3/assets/107256943/e7c82019-a668-47a9-9c10-683f95f68d59)
thrusters should be separated by a wall from the interior

2024-02-29 22:14 UTC, DreamySkrell commented
![image](https://github.com/Aurorastation/Aurora.3/assets/107256943/0a8f4ba7-07f2-4eba-bfb0-15a898899018)
I could be blind and tired but I see only 2 spawn points for the crew, while the limit is 4

2024-02-29 22:23 UTC, DreamySkrell commented
![image](https://github.com/Aurorastation/Aurora.3/assets/107256943/c9d99166-d890-4abe-b0a7-2837580b9539)
In general though, the ship lacks basically any kind of decorations. Like I get the intention is that it's like a patchwork ship fused together from multiple separate ships or shuttles, but it just looks kinda bland and uninteresting honestly. Like the core of the ship is a super long 3-tile-wide hallway. 

Should fix the other things, but I'm not going to stop this from being merged cause of lack of decorations.

2024-02-29 22:25 UTC, DreamySkrell commented
![image](https://github.com/Aurorastation/Aurora.3/assets/107256943/a53080e2-ee7a-4a15-8ec5-0502a1996acf)
The ship does not seem to be centered on the map. Not sure if this is just mapdiffbot or if it's actually like that.

2024-02-29 22:26 UTC, DreamySkrell commented
![image](https://github.com/Aurorastation/Aurora.3/assets/107256943/49e38c44-89a2-48c8-af27-cab208536317)
optional, but would not be hard to add a dock here, by just moving atmos to one of the thruster rooms

2024-02-29 22:28 UTC, DreamySkrell commented
![image](https://github.com/Aurorastation/Aurora.3/assets/107256943/288e9fd1-ff4d-47a2-887d-20c7aa5e7e12)
there is no way to fill this big CO2 tank

there should also be some designated storage for empty/filled canisters, could use one of the thruster rooms for that

2024-02-29 22:30 UTC, DreamySkrell commented
![image](https://github.com/Aurorastation/Aurora.3/assets/107256943/4c5d020e-5422-4e88-bee1-20d42d9096d6)
captains office room could use some decorations, chair(s) for the vistitor(s), a pen, a locker or cabinet, a plant maybe (iirc there's a moghes potted plant)

2024-02-29 22:30 UTC, DreamySkrell commented
![image](https://github.com/Aurorastation/Aurora.3/assets/107256943/191ab49d-0f31-4a1a-ae5c-4b2f79e83197)
not sure if there's cooking tools there, like bowls or rolling thingies or kitchen knife

2024-02-29 22:47 UTC, DreamySkrell requested changes
as above

2024-02-29 22:48 UTC, DreamySkrell commented on maps/away/ships/unathi_pirate/hiskyn/unathi_pirate_hiskyn_ghostroles.dm
> +	desc = "Serve aboard a ship of the pirate fleet Hiskyn's Revanchists - former Kazhkz-Han'san Unathi who refused to join the Empire of Dominia. Obey your captain, defend your ship and crew, and keep
all ghost spawners should have separate desc and welcome_message
see goon base for an example

2024-02-29 22:49 UTC, DreamySkrell commented on maps/away/ships/unathi_pirate/hiskyn/unathi_pirate_hiskyn.dm
> +	movable_flags = MOVABLE_FLAG_EFFECTMOVE
why?

2024-02-29 22:50 UTC, DreamySkrell commented on maps/away/ships/unathi_pirate/hiskyn/unathi_pirate_hiskyn_areas.dm
> +/area/hiskyn_ship/hallC
all types should be all lowercase
hall_c instead of hallC

2024-02-29 22:51 UTC, DreamySkrell requested changes
as above

2024-03-01 01:10 UTC, RustingWithYou commented
> ![image](https://private-user-images.githubusercontent.com/107256943/309089080-0a8f4ba7-07f2-4eba-bfb0-15a898899018.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyNTU3MjMsIm5iZiI6MTcwOTI1NTQyMywicGF0aCI6Ii8xMDcyNTY5NDMvMzA5MDg5MDgwLTBhOGY0YmE3LTA3ZjItNGViYS1iZmIwLTE1YTg5ODg5OTAxOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwMVQwMTEwMjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NGEzZmU4MDVjYWM2NTVmODY2NDA5N2NmNGZlMzU5ZDk4MzZhNTdkNGI4YTg5MjMxZmY4ZmY5MjczODY1ZDA4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CImuepAXQouMnJ2ZY3L3qcWdGvJG6nnTTI7yNcpdFP4) I could be blind and tired but I see only 2 spawn points for the crew, while the max count in the code is 4

there are two more in the beds

2024-03-01 01:11 UTC, RustingWithYou commented
> ![image](https://private-user-images.githubusercontent.com/107256943/309086899-282041f0-b9a1-4e9b-b546-cc98bb8e626a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyNTU3MjMsIm5iZiI6MTcwOTI1NTQyMywicGF0aCI6Ii8xMDcyNTY5NDMvMzA5MDg2ODk5LTI4MjA0MWYwLWI5YTEtNGU5Yi1iNTQ2LWNjOThiYjhlNjI2YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwMVQwMTEwMjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYmE4OGQ4MDI4ZGI3ODlmNTUzNjQ4NmI5ZjE0OTMzYWU1YjhiZGY3NzI4NDM1YmZmZWUzZDBkNWMyY2JmMmNlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.dfA2d0CrygoQMxcHcYi1p4SGeC4H1HFtrDaqunehOrs) ![image](https://private-user-images.githubusercontent.com/107256943/309086709-ab849ca0-49df-4bd0-ab98-4fe65edd5a2e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyNTU3MjMsIm5iZiI6MTcwOTI1NTQyMywicGF0aCI6Ii8xMDcyNTY5NDMvMzA5MDg2NzA5LWFiODQ5Y2EwLTQ5ZGYtNGJkMC1hYjk4LTRmZTY1ZWRkNWEyZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwMVQwMTEwMjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZmE3NDNiNmRiYWJjYjliNjcxYTg1ODlmMDUwMjQxYjYyMTI2MjdhMzJlYjE4NWU4ZDA2ZDBjYWY0MTBlZjYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7_jIkEIGnAwljpeJWRML731rUYxmNu4N-5k6EXyGZb4) ![image](https://private-user-images.githubusercontent.com/107256943/309086798-e3daad17-43ce-4578-b0ee-f7dfb4ad011e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyNTU3MjMsIm5iZiI6MTcwOTI1NTQyMywicGF0aCI6Ii8xMDcyNTY5NDMvMzA5MDg2Nzk4LWUzZGFhZDE3LTQzY2UtNDU3OC1iMGVlLWY3ZGZiNGFkMDExZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwMVQwMTEwMjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yM2U3ZjIwZDc5ZGQyMTQyYjlhYTM1NTBjM2U4MTcxNDAwZDI2NWU2NjdiMDkxZDU5YjM0ZmZiYzNiMmI1ZGY3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.SazXQP70H572k7fTpuH_-Ui0eg_ILxb3itJr4rZQgjE)
> 
> shuttle is not compliant with dock/shuttle standards
> 
> also the two air tanks on the shuttle don't seem to be connected to anything

this is a restricted dock for the hiskyn shuttle, does being able to fit the max shuttle size really matter here when this is the only shuttle that will ever dock with it?

2024-03-01 13:50 UTC, DreamySkrell commented
![image](https://github.com/Aurorastation/Aurora.3/assets/107256943/ca744336-0d71-45c6-ad2b-fe34a65b8c1f)
same thing about about the ship thrusters applies to the shuttle as well

![image](https://github.com/Aurorastation/Aurora.3/assets/107256943/dc9807f7-c770-4284-a051-311af0c98918)
also should be some kind of floor under ship thrusters

2024-03-01 13:55 UTC, DreamySkrell commented
![image](https://github.com/Aurorastation/Aurora.3/assets/107256943/7d5137d0-82be-42e3-b708-3462dec74080)
why is the scrubber pipe net connected like this? It would pump waste air to a (full) air tank, should be empty canister instead like on many other shuttles

2024-03-01 13:58 UTC, DreamySkrell commented
> the air tank thing is true though, autopiper must not connect to pipe adapters

Also for the future, the autopiper does not connect to the universal pipe adapters, cause there isn't really a way to know when/if it should add the connection.

Like in this case, there is no way to know if you want red pipes connected to the adapter above, or that the blue pipes should be connected to the adapter below. It could always connect both blue and red to every adapter, but that would be even more wrong than not connecting at all.

2024-03-02 03:42 UTC, RustingWithYou commented
> > > ![image](https://private-user-images.githubusercontent.com/107256943/309086899-282041f0-b9a1-4e9b-b546-cc98bb8e626a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyNTU3MjMsIm5iZiI6MTcwOTI1NTQyMywicGF0aCI6Ii8xMDcyNTY5NDMvMzA5MDg2ODk5LTI4MjA0MWYwLWI5YTEtNGU5Yi1iNTQ2LWNjOThiYjhlNjI2YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwMVQwMTEwMjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYmE4OGQ4MDI4ZGI3ODlmNTUzNjQ4NmI5ZjE0OTMzYWU1YjhiZGY3NzI4NDM1YmZmZWUzZDBkNWMyY2JmMmNlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.dfA2d0CrygoQMxcHcYi1p4SGeC4H1HFtrDaqunehOrs) ![image](https://private-user-images.githubusercontent.com/107256943/309086709-ab849ca0-49df-4bd0-ab98-4fe65edd5a2e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyNTU3MjMsIm5iZiI6MTcwOTI1NTQyMywicGF0aCI6Ii8xMDcyNTY5NDMvMzA5MDg2NzA5LWFiODQ5Y2EwLTQ5ZGYtNGJkMC1hYjk4LTRmZTY1ZWRkNWEyZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwMVQwMTEwMjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZmE3NDNiNmRiYWJjYjliNjcxYTg1ODlmMDUwMjQxYjYyMTI2MjdhMzJlYjE4NWU4ZDA2ZDBjYWY0MTBlZjYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7_jIkEIGnAwljpeJWRML731rUYxmNu4N-5k6EXyGZb4) ![image](https://private-user-images.githubusercontent.com/107256943/309086798-e3daad17-43ce-4578-b0ee-f7dfb4ad011e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyNTU3MjMsIm5iZiI6MTcwOTI1NTQyMywicGF0aCI6Ii8xMDcyNTY5NDMvMzA5MDg2Nzk4LWUzZGFhZDE3LTQzY2UtNDU3OC1iMGVlLWY3ZGZiNGFkMDExZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwMVQwMTEwMjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yM2U3ZjIwZDc5ZGQyMTQyYjlhYTM1NTBjM2U4MTcxNDAwZDI2NWU2NjdiMDkxZDU5YjM0ZmZiYzNiMmI1ZGY3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.SazXQP70H572k7fTpuH_-Ui0eg_ILxb3itJr4rZQgjE)
> > > shuttle is not compliant with dock/shuttle standards
> > > also the two air tanks on the shuttle don't seem to be connected to anything
> > 
> > 
> > this is a restricted dock for the hiskyn shuttle, does being able to fit the max shuttle size really matter here when this is the only shuttle that will ever dock with it?
> > the air tank thing is true though, autopiper must not connect to pipe adapters
> 
> ![image](https://private-user-images.githubusercontent.com/107256943/309279756-0da61d19-d124-437d-8de6-fa3018fe0a03.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkzNTA5MzgsIm5iZiI6MTcwOTM1MDYzOCwicGF0aCI6Ii8xMDcyNTY5NDMvMzA5Mjc5NzU2LTBkYTYxZDE5LWQxMjQtNDM3ZC04ZGU2LWZhMzAxOGZlMGEwMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwMlQwMzM3MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNDUwZTFiZTU0MjEzODRhNWFkYTUyN2MwMWVlYTZiNjMzMGFmYWRiY2QzMjBhMDAwZjE4NTc2ZThhN2QxYmU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.LOVuEq2UNP_4RTR195hxVH-Xzig9k5jz3R4SDYnzNss)
> 
> the problem isn't with the dock but with the shuttle, it does not fit inside the shuttle size rectangle

My bad, addressed.

2024-03-02 10:55 UTC, DreamySkrell approved these changes

2024-03-02 11:37 UTC, merged