Hard deletes fun from Konyang (Point Verdant Radio Changes)
Aurorastation/Aurora.3 pull request #18560
Opened 2024-02-27 17:03 UTC by Ben10083

- Refactoring of radio code to fix bounced radio map presets, and adds them to police loadout with own channel
- Maps can now set a frequency name to name the radio channel for extra snowflaking
- Point Verdant should now only have access to hailing frequency (no more common and entertainment), other Konyang ghostroles should probably be looked into
- new bounced radio subtype that only has hailing frequency

2024-02-27 17:03 UTC, Ben10083 commented
!review

2024-02-29 17:36 UTC, NonQueueingMatt approved these changes

2024-03-03 07:51 UTC, FluffyGhoster requested changes

2024-03-03 07:51 UTC, FluffyGhoster commented on code/game/objects/items/devices/radio/radio.dm
> +	return ..()
Internal channels are initialized in /obj/item/device/radio/Initialize(), which would override whatever you set here, you should call the parent init before whatever you do unless there's a very good reason not to (also for signals handling and other reasons

2024-03-05 17:38 UTC, FluffyGhoster approved these changes

2024-03-05 19:44 UTC, merged