Adds Norinori the Onigiri Costume
Aurorastation/Aurora.3 pull request #18583
Opened 2024-03-02 00:58 UTC by Ben10083

Adds Norinori, the mascot of Up!Burger, costume

Sprites by Nautical 
![image](https://github.com/Aurorastation/Aurora.3/assets/91219575/261015f1-3da3-4a27-b5b2-a8c0769d7d17)

2024-03-02 00:58 UTC, Ben10083 commented
!review

2024-03-02 00:59 UTC, Ben10083 commented
@NobleRow stated that plans are for this to be available before the event Sunday, if possible

2024-03-03 01:14 UTC, Generalcamo requested changes

2024-03-03 01:14 UTC, Generalcamo commented on code/modules/holidays/halloween/costumes.dm
> +	name = "UP!Burger mascot costume"
```suggestion
	name = "\improper UP!Burger mascot costume"
```

2024-03-03 01:14 UTC, Generalcamo commented on code/modules/holidays/halloween/costumes.dm
> +	desc = "A costume of of Norinori the Onigiri, popular mascot of Up!Burger. Some poor high school student's worst part time job."
```suggestion
	desc = "A costume of Norinori the Onigiri, popular mascot of Up!Burger. Some poor high school student's worst part time job."
```

2024-03-03 15:23 UTC, SleepyGemmy approved these changes

2024-03-03 18:37 UTC, Generalcamo approved these changes

2024-03-04 09:17 UTC, NonQueueingMatt approved these changes

2024-03-04 19:37 UTC, FluffyGhoster approved these changes

2024-03-05 19:27 UTC, merged