schlorrgo plush go ough
Aurorastation/Aurora.3 pull request #18591
Opened 2024-03-03 19:44 UTC by Greenjoe12345

schlorrgo plushies now go ough when thrown or poked.

2024-03-03 19:44 UTC, Greenjoe12345 commented
!review

2024-03-03 19:51 UTC, alsoandanswer approved these changes

2024-03-03 20:32 UTC, SleepyGemmy commented on code/game/objects/items/toys.dm
> +	var/pokesound = 'sound/items/drop/plushie.ogg'
```suggestion
	var/poke_sound = 'sound/items/drop/plushie.ogg'
```
and where its used.

2024-03-04 09:20 UTC, NonQueueingMatt requested changes

2024-03-04 09:20 UTC, NonQueueingMatt commented on code/game/objects/items/toys.dm
> +		playsound(src, poke_sound, 25, 0)
add a spam prevention system, please

2024-03-04 09:22 UTC, NonQueueingMatt commented on code/game/objects/items/toys.dm
> +		playsound(src, poke_sound, 25, 0)
```
var/poke_cooldown = 0

/obj/item/plushie/attack_self()
	if(poke_cooldown > world.time)
		return
	poke_cooldown = world.time
```
as an example

2024-03-04 18:28 UTC, FluffyGhoster requested changes

2024-03-04 18:28 UTC, FluffyGhoster commented on code/game/objects/items/toys.dm
> +	var/poke_sound = 'sound/items/drop/plushie.ogg'
DMDoc what this var does

2024-03-05 15:45 UTC, FluffyGhoster commented on code/game/objects/items/toys.dm
> +/// defines what sound is played when poking the plushie (using it inhand on disarm intent).
Wrong indentation

2024-03-06 04:39 UTC, FluffyGhoster approved these changes

2024-03-07 02:37 UTC, SleepyGemmy requested changes

2024-03-07 02:37 UTC, SleepyGemmy commented on code/game/objects/items/toys.dm
poke cooldown should be under `attack_self` before any of the intent checks, otherwise you can spam the other messages but not the poke one, which feels unintuitive.

2024-03-11 09:36 UTC, NonQueueingMatt approved these changes

2024-03-11 10:51 UTC, merged