Coalition of Snackolonies II: Fetch Harder Edition
Aurorastation/Aurora.3 pull request #18626
Opened 2024-03-10 02:40 UTC by crunchypretzels

The ghola of my previous PR, which was killed by a series of merge conflicts and programming errors.

This PR adds a number of new lore-related foods from the Coalition.

-Three new alcoholic drinks, two from Xanu Prime and one from Gadpathur, as well as a new cocktail and some canned beer brands.
-Several new non-alcoholic drinks, such as a Galatean 'energy drink', several brands of Xanan refreshment, mushroom kvass, and some Vysokan... ichor soda.
-Several new cooking recipes for Xanu Prime and Himeo, as well as the much-awaited chicken parm hero.
-More than a dozen new snack foods from across the Coalition of Colonies, as well as a vending machine that holds them all in it. This will be mapped onto the Horizon in the near future, as well as related awaysites.
-Two new mugs; Galatea and the All-Xanu Republic, which can be found in the loadout.
-Hakhma meat; butcher a hakhma.

All lore comes from the Human Lore Team. The sprites are by me, or are modified versions of sprites provided by our esteemed playerbase.

A thousand thanks to the half-dozen people who put this together, especially Lain, who came up with all the Xanan food and drinks, Schwann, who came up with the Himean and Galatean contributions, and Wiggles, who came up with all the Vysokan content.

![image](https://github.com/Aurorastation/Aurora.3/assets/70682905/0f98d1cf-1f06-4e0b-b3c5-39529fc847c8)

2024-03-10 02:41 UTC, crunchypretzels commented
!review

2024-03-10 19:28 UTC, DreamySkrell approved these changes

2024-03-11 09:34 UTC, NonQueueingMatt requested changes

2024-03-11 09:34 UTC, NonQueueingMatt commented on code/game/machinery/vending_types.dm
> +	//product_ads = "Kill Solarians.;Behead Solarians.;Roundhouse kick a Solarian into the concrete.;Slam-dunk Solarians into the trashcan.;Launch Solarians into the sun."
remove this commented code if it's not implemented

2024-03-11 09:34 UTC, NonQueueingMatt commented on code/game/machinery/vending_types.dm
> +	//	/obj/item/storage/box/fancy/yoke/earthmover = 2 // guys rocked a little too hard for the GC but we will never forget the cold ones we cracked
remove commented code if not implemented

2024-03-11 09:34 UTC, NonQueueingMatt commented on code/game/machinery/vending_types.dm
> +
extra space

2024-03-17 21:56 UTC, NonQueueingMatt approved these changes

2024-03-18 01:01 UTC, merged