Trophy of Battle - Secondary Transmitter Drone Core
Aurorastation/Aurora.3 pull request #18623
Opened 2024-03-09 23:42 UTC by RustingWithYou

Adds the Secondary Transmitter Drone Core from today's event to the Horizon for science to poke. It spawns in one of the xenoarchaeology cells, which has been modified to use general science access

2024-03-09 23:42 UTC, RustingWithYou commented
!review

2024-03-09 23:45 UTC, SleepyGemmy commented on code/game/objects/structures/hivebot_head.dm
> +	name = "Secondary Transmitter Drone Core"
```suggestion
	name = "\improper Secondary Transmitter Drone core"
```

2024-03-09 23:53 UTC, FluffyGhoster requested changes

2024-03-09 23:53 UTC, FluffyGhoster commented on code/game/objects/structures/hivebot_head.dm
> +		sleep(16)
No sleeping, use a timer

2024-03-10 04:19 UTC, FluffyGhoster approved these changes

2024-03-10 10:53 UTC, Arrow768 approved these changes

2024-03-11 23:44 UTC, SleepyGemmy commented on code/game/objects/structures/hivebot_head.dm
> +
```suggestion
```

2024-03-11 23:45 UTC, SleepyGemmy approved these changes

2024-03-13 22:17 UTC, merged