Pocket Pouches
Aurorastation/Aurora.3 pull request #18629
Opened 2024-03-10 16:25 UTC by Geevies

* Ported pouches from CM, these are storage items that fit in your pockets. A bunch have been mapped into the cargo warehouse.

This screenshot is mostly accurate, the items on the top right rack have changed however.
![image](https://github.com/Aurorastation/Aurora.3/assets/22774890/ad1e1e00-d484-44b2-beb5-f61791da1ca7)

### Asset Licenses
The following assets that **have not** been created by myself are included in this PR:

| Path | Original Author | License |
| --- | --- | --- |
| icons/obj/clothing/pouches.dmi | CM-SS13 | [Creative Commons 3.0 BY-SA](https://creativecommons.org/licenses/by-sa/3.0/) |

2024-03-10 17:59 UTC, Geevies commented
!review

2024-03-10 19:17 UTC, DreamySkrell commented
![image](https://github.com/Aurorastation/Aurora.3/assets/107256943/b787294a-f31e-4442-a3ee-c681a7bc39a1)

The pouches are cool, but as is I don't really see the point/purpose of these honestly:

- If these are supposed to be standard equipment, then they should spawn in crew's lockers, equipment vendors, maybe give them these on spawn. Otherwise, why do they spawn in the warehouse? Are people supposed to go to the warehouse every shift to get these?

- If these are not supposed to be standard equipment, then they should be orderable from cargo instead, and not be put in the warehouse.

2024-03-10 19:20 UTC, DreamySkrell commented
![image](https://github.com/Aurorastation/Aurora.3/assets/107256943/be87177a-caa6-4951-978f-7a9aabc371a7)
This file is huge. Code for the pouches should be put in their own folder, and with different pouches types in their own files

2024-03-10 19:22 UTC, DreamySkrell commented on code/game/objects/items/weapons/storage/pouch.dm
> +	storage_slots = 1
I feel this is really "gamey" and makes no sense. 

Pouches hold a few small items, and you can put them in your pocket... but you can't put them in your backpack? So how big are they exactly? Belts are bigger than these surely, but can be put in your backpack.

2024-03-10 19:24 UTC, DreamySkrell commented
![image](https://github.com/Aurorastation/Aurora.3/assets/107256943/b1724319-6ac8-49c3-944f-17e5563cd0c0)

I do not think these fit stylistically and palette-wise on Horizon. We do not use these colors like, anywhere. 
At the very least these should be recolored (not necessarily resprited) to corporate colors (blue-ish/gray-ish). There could be green variants for other factions, but I think these do not fit on Horizon to be crew equipment.

2024-03-10 19:27 UTC, DreamySkrell requested changes
as above

2024-03-11 16:48 UTC, FluffyGhoster requested changes

2024-03-11 16:48 UTC, FluffyGhoster commented on code/modules/mob/inventory.dm
> +		return
This signal goes in /atom/movable/proc/throw_at

2024-03-11 16:48 UTC, FluffyGhoster commented on code/game/objects/items/weapons/storage/pouch.dm
> +	name = "abstract pouch"
If this is an abstract, it needs to be marked as such with `abstract_type`

2024-03-11 16:48 UTC, FluffyGhoster commented on code/game/objects/items/weapons/storage/pouch.dm
> +	current_gun = null
you need to either QDEL_NULL it or move it out of the pouch if the pouch is deleted, with a strong preference to the former

2024-03-11 16:48 UTC, FluffyGhoster commented on code/game/atoms.dm
> +/atom/proc/on_stored_atom_del(atom/movable/AM)
Meaningfully name the proc parameter(s)

2024-03-11 16:48 UTC, FluffyGhoster commented on code/game/objects/items/weapons/storage/pouch.dm
> +				to_chat(usr, SPAN_WARNING("[src] already holds a gun."))
```suggestion
				to_chat(user, SPAN_WARNING("[src] already holds a gun."))
```

Do not rely on the usr var, especially when you can pass in the correct user and are already doing that

2024-03-12 00:04 UTC, SleepyGemmy requested changes
seconding Dreamy. balance and effects on gameplay should also be considered. other than that, i'm not sure why this is needed when we already have many ways to expand your inventory.

2024-03-18 09:19 UTC, NonQueueingMatt commented
A few things:
- In concept this is fine but storage absolutely needs to be nerfed as a whole if you're adding pocket pouches.
- It needs new sprites, because CM's are totally unfitting. Sammy can probably help you with that.

2024-03-28 15:25 UTC, Eyeveri commented
Just going to throw this in too - instead of mapping them onto racks and such, please code them into a locker or a crate. 

I also agree with Dreamy's comments.

2024-04-20 13:52 UTC, Geevies commented
this one will need a little more effort and love than i'm capable of giving it right now, but if someone wants to take it over with the good feedback provided above, feel free

2024-04-20 13:52 UTC, closed without merging