Added more fantasy drugs to the game
Aurorastation/Aurora.3 pull request #18628
Opened 2024-03-10 12:55 UTC by Generalcamo

This ports a few drugs from Polaris, as additional fantasy drugs. This was originally intended for #16773, but that PR quickly grew too massive for these to be reasonably reviewed.

In addition, Adhomian cigarettes now use a special subtype of tobacco, which is a sweeter and stronger variety. This was originally also intended for #16773, and has the blessing of the tajaran team (the taste description comes from them), but I honestly forgot to do it.

2024-03-10 12:55 UTC, Generalcamo commented
!review

2024-03-11 09:38 UTC, NonQueueingMatt requested changes

2024-03-11 09:38 UTC, NonQueueingMatt commented on code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Drugs.dm
> +	..()
this is going to kill people in like 20 seconds, remove the toxloss maybe

2024-03-11 09:38 UTC, NonQueueingMatt commented on code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Drugs.dm
> +	M.hallucination = max(M.hallucination, drug_strength)
this seems like a shitload of hallucination strength at first? maybe excessive?

2024-03-18 10:12 UTC, NonQueueingMatt approved these changes

2024-03-19 16:21 UTC, FluffyGhoster approved these changes

2024-03-19 16:58 UTC, merged