Voidsuit Icon Repaths
Aurorastation/Aurora.3 pull request #18651
Opened 2024-03-13 04:39 UTC by RustingWithYou

Moves the icons of several factional voidsuits into a single folder for the sake of general consistency, as well as making several suits which were previously not contained sprites now contained - namely the Coalition, Elyra and Sol voidsuits. Voidsuits are now generally organised by faction, with all of the Solarian voidsuits in sol.dmi and all of the Coalition voidsuits in coalition.dmi.

Several voidsuit sprites that we had previously were all over the place, with little consistency in where the icons actually went - some were in obj/item/clothing/voidsuits, others were in obj/clothing/voidsuits, and others were scattered about. Hopefully this will make finding or adding new voidsuit sprites easier in future.

The voidsuits affected which had species-specific versions or used the refitting system now use icon species tags. This may be less immersive, but it's generally more convenient for in-game use until someone wants to change refitting to work with contained sprites.

2024-03-13 04:39 UTC, RustingWithYou commented
!review

2024-03-13 07:00 UTC, alsoandanswer requested changes
the new standard is icons/obj/clothing, **not** icons/clothing

2024-03-13 08:09 UTC, alsoandanswer approved these changes
thanks

2024-03-14 03:32 UTC, SleepyGemmy approved these changes

2024-03-17 22:52 UTC, merged