Point Verdant now only spawns when today is a Port of Call
Aurorastation/Aurora.3 pull request #18670
Opened 2024-03-15 15:33 UTC by Ben10083

title

As it says above, unless it is a port of call day, PV will no longer spawn (it will always spawn and ignore budget if it is a Port day though)

New template flag was made to handle this and any future maps that would use this port of call system.

2024-03-15 15:34 UTC, Triogenix commented
As I said in discord, this is currently being discussed internally by the lore team.

2024-03-15 15:37 UTC, Ben10083 commented
> As I said in discord, this is currently being discussed internally by the lore team.

Yep, making this PR so once the discussion is complete, this PR can move forward or adapt (if PV doesn't want to use this system, will likely just remove the flag from PV but leave the system in place)

2024-03-17 00:45 UTC, Triogenix commented
We ended up deciding that we'll be moving the port of call days to Saturday-Sunday, and have PV able to spawn on those days as well. IDK how that fits with the PR you had, but if it could be updated to reflect that, it'll be good to be merged in terms of lore discussion stuff.

2024-03-17 02:10 UTC, Ben10083 commented
attempting to fix a bug that is making it not spawn when it should

2024-03-17 04:10 UTC, Ben10083 commented
I think it works now

2024-03-17 11:28 UTC, Triogenix commented
👍 This is fine with the lore team then.

2024-03-21 19:02 UTC, NonQueueingMatt requested changes

2024-03-21 19:02 UTC, NonQueueingMatt commented on code/datums/ruins.dm
> +/datum/map_template/ruin/proc/port_of_call_check()
this shouldn't be a ruin proc, this should either be on SSatlas, on the mapdatum, or on the sector - probably on SSatlas

2024-03-22 01:44 UTC, FluffyGhoster commented on code/modules/maps/ruins.dm
> +		if((ruin.template_flags & TEMPLATE_FLAG_PORT_SPAWN) && (ruin.spawns_in_current_sector()))
The check below already handles the spawns_in_current_sector(), what is the point of processing it here too, over moving this block below it and just cycle the potential ruins that it already filtered?

2024-03-23 23:39 UTC, NonQueueingMatt approved these changes

2024-03-23 23:55 UTC, FluffyGhoster approved these changes

2024-03-24 16:37 UTC, merged