Slimes can't eat cleanbots
Aurorastation/Aurora.3 pull request #18673
Opened 2024-03-16 05:31 UTC by AlaunusLux

Slimes will no longer target cleanbots. 

As it was, slimes spammed the chat with attack logs when they came near Dr. Clean B. Ot.

2024-03-16 05:33 UTC, AlaunusLux commented
!review

2024-03-16 05:35 UTC, alsoandanswer approved these changes

2024-03-16 05:39 UTC, FluffyGhoster approved these changes

2024-03-18 20:36 UTC, SleepyGemmy approved these changes

2024-03-19 06:23 UTC, FluffyGhoster requested changes

2024-03-19 06:23 UTC, FluffyGhoster commented on html/changelogs/AlaunusLux - slimes-cant-eat-cleanbots.yml
> +  - tweak: "Slimes will no longer target cleanbots."
This will need to be updated, if they can't eat bots at all now

2024-03-19 08:31 UTC, FluffyGhoster approved these changes

2024-03-19 11:54 UTC, merged