OOC notes rewrite and examine boxes in HUD's output
Aurorastation/Aurora.3 pull request #18688
Opened 2024-03-18 16:02 UTC by SidVeld

# OOC notes rewrite and examine boxes in HUD's output

This pull request contains two changes.

## OCC Notes: return

Gives you the ability to view OOC notes when examining a character. Requires `ALLOW_METADATA` to be enabled in the config.

![изображение](https://github.com/Aurorastation/Aurora.3/assets/22749671/c8221dde-669a-429a-ae38-bbe40db48ba2)

## Examine boxes in Huds

I liked the examine boxes so much I wanted to use them somewhere else. I created three new subclasses of examine boxes and use them in med/sec hud's messages. I hope you enjoy it.

### Security

![изображение](https://github.com/Aurorastation/Aurora.3/assets/22749671/47aa6ea0-c71f-4d11-acba-ff6817fb6dc7)

### Medical

![изображение](https://github.com/Aurorastation/Aurora.3/assets/22749671/b7b59cd8-f619-465c-959b-57019164bee9)

2024-03-18 20:14 UTC, SleepyGemmy commented
!review

2024-03-18 20:27 UTC, SleepyGemmy requested changes

2024-03-18 20:27 UTC, SleepyGemmy commented on code/modules/client/preference_setup/general/01_basic.dm
> +				"Enter any information you'd like others to see, such as Roleplay-preferences:",
```suggestion
				"Enter any information you'd like others to see, such as roleplay preferences.",
```

2024-03-18 20:27 UTC, SleepyGemmy commented on code/modules/client/preference_setup/general/01_basic.dm
> +				"Clear OOC notes Confirmation",
```suggestion
				"Are you sure you wish to clear this character's OOC notes?",
				"Clear OOC Notes Confirmation",
```

2024-03-18 20:27 UTC, SleepyGemmy commented on code/modules/mob/living/carbon/human/human.dm
> +				)
```suggestion
				to_chat(usr, EXAMINE_BLOCK_RED(SPAN_WARNING("Unable to locate a data core entry for this person.")))
```

2024-03-18 20:27 UTC, SleepyGemmy commented on code/modules/mob/living/carbon/human/human.dm
> +				)
```suggestion
				to_chat(usr, EXAMINE_BLOCK_RED(SPAN_WARNING("Unable to locate a data core entry for this person.")))
```

2024-03-18 20:27 UTC, SleepyGemmy commented on code/modules/mob/living/carbon/human/human.dm
> +				)
```suggestion
				to_chat(usr, EXAMINE_BLOCK_RED(SPAN_WARNING("Unable to locate a data core entry for this person.")))
```

2024-03-18 20:27 UTC, SleepyGemmy commented on code/modules/mob/living/carbon/human/human.dm
> +				)
```suggestion
				to_chat(usr, EXAMINE_BLOCK_DEEP_CYAN(SPAN_WARNING("Unable to locate a data core entry for this person.")))
```

2024-03-18 20:27 UTC, SleepyGemmy commented on code/modules/mob/living/carbon/human/human.dm
> +				)
```suggestion
				to_chat(usr, EXAMINE_BLOCK_DEEP_CYAN(SPAN_WARNING("Unable to locate a data core entry for this person.")))
```

2024-03-18 20:27 UTC, SleepyGemmy commented on code/modules/mob/living/carbon/human/human.dm
> +					var/message = "<b>Medical comments: [name]</b>\n\n"
```suggestion
					var/message = "<b>Medical Record Comments: [name]</b>\n\n"
```

2024-03-18 20:27 UTC, SleepyGemmy commented on code/modules/mob/living/carbon/human/human.dm
> +					message += "<a href='?src=\ref[src];secrecordadd=`'>\[Add comment\]</a>"
```suggestion
					message += "<a href='?src=\ref[src];secrecordadd=`'>\[Add Comment\]</a>"
```

2024-03-18 20:27 UTC, SleepyGemmy commented on code/modules/mob/living/carbon/human/human.dm
> +					message += "<a href='?src=\ref[src];medrecordadd=`'>\[Add comment\]</a>"
```suggestion
					message += "<a href='?src=\ref[src];medrecordadd=`'>\[Add Comment\]</a>"
```

2024-03-18 20:27 UTC, SleepyGemmy commented on code/modules/mob/living/carbon/human/human.dm
> +				)
```suggestion
				to_chat(usr, EXAMINE_BLOCK_DEEP_CYAN(SPAN_WARNING("Unable to locate a data core entry for this person.")))
```

2024-03-18 20:27 UTC, SleepyGemmy commented on code/modules/mob/living/carbon/human/human.dm
> +			+ SPAN_WARNING("Remember, this is ooc information.")
```suggestion
		var/message = "<b>OOC Notes: [name]</b>" \
			+ "\n\n" \
			+ client.prefs.metadata \
			+ "\n\n" \
			+ SPAN_WARNING("Remember, this is OOC information.")
```

2024-03-18 20:27 UTC, SleepyGemmy commented on code/modules/mob/living/carbon/human/examine.dm
> +		msg += "<span class='deadsay'>OOC notes:</span> <a href='?src=\ref[src];metadata=1'>\[View\]</a>\n"
```suggestion
		msg += "<span class='deadsay'>OOC Notes:</span> <a href='?src=\ref[src];metadata=1'>\[View\]</a>\n"
```

2024-03-18 20:27 UTC, SleepyGemmy commented on code/modules/mob/living/carbon/human/human.dm
> +					var/message = "<b>Information</b>\n\n" \
```suggestion
					var/message = "<b>Security Records: [R.name]</b>\n\n" \
```

2024-03-18 20:27 UTC, SleepyGemmy commented on code/modules/mob/living/carbon/human/human.dm
> +					var/message = "<b>Medical information</b>\n\n" \
```suggestion
					var/message = "<b>Medical Records: [R.name]</b>\n\n" \
```

2024-03-18 20:27 UTC, SleepyGemmy commented on code/modules/mob/living/carbon/human/human.dm
> +					var/message = "<b>Comments: [name]</b>\n\n"
```suggestion
					var/message = "<b>Security Record Comments: [name]</b>\n\n"
```

2024-03-20 03:35 UTC, SleepyGemmy approved these changes

2024-03-21 09:03 UTC, Geevies approved these changes
the examine blocks with those borders look really cool

2024-03-21 19:36 UTC, merged