maps in the new snack vendors + beer closet
Aurorastation/Aurora.3 pull request #18686
Opened 2024-03-18 05:38 UTC by crunchypretzels

As title. Adds four FrontierVend machines to the Horizon.

This PR also adds a closet of beer to the Horizon's bar backroom, filled with canned beer. Crack open a cold one with the lads after that shootout.

2024-03-18 05:38 UTC, crunchypretzels commented
!review

2024-03-18 17:56 UTC, DreamySkrell commented
![image](https://github.com/Aurorastation/Aurora.3/assets/107256943/9922d02c-d515-4354-8c3a-60a0e1668d37)
you put the new vendor here, replacing a guest pass terminal and a potted plant
do not do that
revert that change and put the new vendor near the docks there

2024-03-18 17:57 UTC, DreamySkrell commented
![image](https://github.com/Aurorastation/Aurora.3/assets/107256943/090d9b40-aa3f-4723-8880-384f53cab381)
You put a coffee machine there. Why? There is one just below it already.

2024-03-18 17:59 UTC, DreamySkrell commented
![image](https://github.com/Aurorastation/Aurora.3/assets/107256943/647d9959-c209-4450-8908-e32d228f37d8)
put yellow hatching under the new vendor here so it is consistent with other vendors in the area

2024-03-18 17:59 UTC, DreamySkrell requested changes
as above

2024-03-18 20:12 UTC, SleepyGemmy requested changes
hatching should be layered under the spline.

2024-03-18 20:12 UTC, SleepyGemmy commented on maps/sccv_horizon/sccv_horizon-2_deck_2.dmm
> +	},
misplaced rename?

2024-03-18 20:12 UTC, SleepyGemmy commented on maps/sccv_horizon/sccv_horizon-2_deck_2.dmm
> +/obj/item/storage/box/fancy/yoke/whistlingforest,
add a subtype (e.g. `/obj/structure/closet/cabinet/beer`), add the items to the subtype, and map in the subtype instead.

2024-03-18 22:27 UTC, crunchypretzels commented on maps/sccv_horizon/sccv_horizon-2_deck_2.dmm
> +	},
misplaced rename!

2024-03-18 23:19 UTC, DreamySkrell commented on code/game/objects/structures/crates_lockers/closets/secure/bar.dm
> +	req_access = list(ACCESS_BAR)
default access should be null / no access required

2024-03-18 23:21 UTC, DreamySkrell commented on code/game/objects/structures/crates_lockers/closets/secure/bar.dm
> +/obj/structure/closet/secure_closet/cabinet/beer/unlocked //for awaysites
should be /horizon subtype specifically for horizon

What you did here was the standard for a long time, but I would like us from now on to move towards the opposite - default no access, and subtypes for horizon. This is cause we have so much more offships and away sites that use everything more than horizon.

2024-03-19 02:36 UTC, SleepyGemmy commented on code/game/objects/structures/crates_lockers/closets/secure/bar.dm
> +	new /obj/item/storage/box/fancy/yoke/whistlingforest( src )
```suggestion
	new /obj/item/storage/box/fancy/yoke/beer(src)
	new /obj/item/storage/box/fancy/yoke/beer(src)
	new /obj/item/storage/box/fancy/yoke/ebisu(src)
	new /obj/item/storage/box/fancy/yoke/ebisu(src)
	new /obj/item/storage/box/fancy/yoke/shimauma(src)
	new /obj/item/storage/box/fancy/yoke/shimauma(src)
	new /obj/item/storage/box/fancy/yoke/moonlabor(src)
	new /obj/item/storage/box/fancy/yoke/moonlabor(src)
	new /obj/item/storage/box/fancy/yoke/earthmover(src)
	new /obj/item/storage/box/fancy/yoke/earthmover(src)
	new /obj/item/storage/box/fancy/yoke/whistlingforest(src)
	new /obj/item/storage/box/fancy/yoke/whistlingforest(src)
```
i assume that you followed the booze closet example. if you could fix that as well i'd appreciate it, but you don't have to of course.

2024-03-19 10:59 UTC, DreamySkrell approved these changes

2024-03-20 02:49 UTC, SleepyGemmy approved these changes

2024-03-21 12:19 UTC, merged