Condensed laser scalpels into a single version
Aurorastation/Aurora.3 pull request #18697
Opened 2024-03-19 21:46 UTC by Nalarac

Partially revives #16717 

Replaces the three versions of laser scalpels with a single one that works 100% of the time. It uses the most advanced laser scalpel sprite.

It's been given a material cost of (DEFAULT_WALL_MATERIAL = 12500, MATERIAL_GLASS = 7500) and research requirement of (TECH_BIO = 3, TECH_MATERIAL = 4, TECH_MAGNET = 4) to make in the protolathe.
This splits the difference of tool progression as science is needed (all techs start at 3) but not materials from mining (if you have materials, you can just build an Incision Management System).

2024-03-20 02:37 UTC, SleepyGemmy commented
!review

2024-03-20 02:41 UTC, SleepyGemmy requested changes
remove the unused versions' sprites and rename the used sprite to `scalpel_laser` or similarly.

2024-03-20 22:27 UTC, SleepyGemmy approved these changes

2024-03-21 09:06 UTC, Geevies approved these changes

2024-03-23 18:09 UTC, merged