Adjusts the force of all items to be multiplied.
Aurorastation/Aurora.3 pull request #18708
Opened 2024-03-20 22:41 UTC by NonQueueingMatt

Melee weapons in our codebase have a problem with generally not being useful, barring like 2-3 melee weapons. The aim of this PR is to fix that and to make even basic melee tools threatening to use, instead of feeling like a crowbar is about as effective as a wet newspaper.

The dogma being followed is the following:
```
    switch(force)
        if(5 to 10)
            force *= 2.25
        if(10 to 20)
            force *= 1.5
        if(20 to 30)
            force *= 1.25
        if(30 to 40)
            force *= 1.1
```
Melee armour values will likely be updated too.

2024-03-21 08:58 UTC, Geevies approved these changes
works on my machine

2024-03-23 15:19 UTC, Generalcamo requested changes

2024-03-23 15:19 UTC, Generalcamo commented on code/game/objects/items/weapons/melee/energy.dm
This entire file should probably be given another look. Right now you're multiplying the effects of the unactivated energy weapons, rather than the activated weapons.

2024-03-24 14:08 UTC, NonQueueingMatt commented
!review

2024-03-24 17:00 UTC, DreamySkrell approved these changes

2024-03-24 18:44 UTC, merged