Ports the weather system from Nebula.
Aurorastation/Aurora.3 pull request #18706
Opened 2024-03-20 18:25 UTC by NonQueueingMatt

todo:

- [ ] backport abstract markers from raccoon city
- [ ] backport the umbrella stuff
- [ ] test if it works on exoplanets

2024-03-20 22:47 UTC, NonQueueingMatt commented
!review

2024-03-21 11:54 UTC, Geevies approved these changes

2024-03-21 11:54 UTC, Geevies commented on code/datums/state_machine/state.dm
> +// An individual state, defined as a `/decl` to save memory.
```suggestion
// An individual state, defined as a `/singleton` to save memory.
```

2024-03-24 00:30 UTC, SleepyGemmy approved these changes

2024-03-24 15:21 UTC, Arrow768 requested changes

2024-03-24 15:21 UTC, Arrow768 commented on code/game/objects/items.dm
> +	return FALSE
Imho this should include the weather it is protecting from as a parameter.
i.e. a umbrella might protect you during a "normal" rainshower, but when you get to a actual (snow-)storm the umbrella becomes useless.

2024-03-24 15:21 UTC, Arrow768 commented on code/modules/mob/living/life.dm
> +			weather_state.handle_exposure(src, get_weather_exposure(weather), weather)
You are already passing the weather as a parameter here

2024-03-24 15:21 UTC, Arrow768 commented on code/modules/mob/mob.dm
> +/mob/proc/get_weather_exposure()
But you dont evaluate the weather parameter you are passing here

2024-03-24 16:31 UTC, merged