Revisits old system contents
Aurorastation/Aurora.3 pull request #18703
Opened 2024-03-20 16:07 UTC by Alberyk

This pr fixes and updates some old space systems contents.

2024-03-20 16:24 UTC, Greenjoe12345 commented on code/modules/overmap/exoplanets/decor/_areas.dm
> +	area_blurb = "The dark surface of the moon is quite. You feel a strange presence nearby."
```suggestion
	area_blurb = "The dark surface of the moon is quiet. You feel a strange presence nearby."
```

2024-03-21 17:40 UTC, Eyeveri approved these changes
The maps and added "code" look good to me.

2024-03-22 15:01 UTC, SleepyGemmy requested changes

2024-03-24 15:13 UTC, Arrow768 approved these changes

2024-03-25 10:59 UTC, DreamySkrell approved these changes
looks good-ish
Gem's requested changes should be implemented though

2024-03-25 19:16 UTC, DreamySkrell commented
# nka_merchant.dmm

![image](https://github.com/Aurorastation/Aurora.3/assets/107256943/66b3c8ca-64ba-427d-a108-53b0a6c0fcbe)
wrong vent types, won't connect to these pipes
area should extend to cover the airlock

![image](https://github.com/Aurorastation/Aurora.3/assets/107256943/d5f3f952-ea6c-4379-b6ab-5d9333c08434)
wrong dir on connector

![image](https://github.com/Aurorastation/Aurora.3/assets/107256943/1dac0e8c-182d-458f-a735-e4671ed51fd8)
should be the new window spawners

![image](https://github.com/Aurorastation/Aurora.3/assets/107256943/fd78813f-f744-4dea-ae66-a21d9e26fa63)
windows on engines is old mapping style, exterior should not be visible through engines from the inside 

![image](https://github.com/Aurorastation/Aurora.3/assets/107256943/b5a249e2-6202-47f1-8e38-2879c133501c)
airlocks look correct, both in mapping and code

2024-03-29 14:40 UTC, SleepyGemmy commented on aurorastation.dme
> -#include "interface\skin.dmf"
don't forget to undo this manually before the PR is merged.

2024-04-02 01:55 UTC, merged