Planes & Layers part 2: Plane Masters
Aurorastation/Aurora.3 pull request #18749
Opened 2024-03-25 14:03 UTC by Generalcamo

Part 2 of the PR series to bring /tg/'s and bay's plane masters to Aurora, the lack of which is blocking several features we want.

This ports over the easier to understand Bay version of plane masters, which is detailed in the relevant readme file in the code. Example effect code for a warp effect is also in, which has been implemented for gravity catapults.

Relies on #18741

2024-03-25 20:02 UTC, Generalcamo commented
!review

2024-03-25 20:09 UTC, NonQueueingMatt approved these changes

2024-03-25 21:13 UTC, FluffyGhoster requested changes

2024-03-25 21:13 UTC, FluffyGhoster commented on code/__DEFINES/__initialization.dm
> +}
Leave them in their file where they were, which is aligned with TG's version

2024-03-25 21:13 UTC, FluffyGhoster commented on code/__DEFINES/_macros.dm
> +#define QDEL_LIST_ASSOC_VAL(L) if(L) { for(var/I in L) qdel(L[I]); L.Cut(); }
Same, leave them where they were

2024-04-03 00:43 UTC, FluffyGhoster commented
It looks like this/the previous PR is/are so far causing these issues I noticed:

- Space is white, lacking the icon
- Character preview is black, without the character nor background
- Windows are rendered above shutters
- There's a newscaster in the middle of the central hall, D2 for some reason
- There's also a part of it in D3, or at least it's visible through the floor
- Air alarm in D3 too, on the other side
- Zmimic does not seem to shade the lower layers properly
- People seem to be masked below floorlights
- Skrells seems to go below the railings in D2, for some reason; it doesn't seem to do that with humans - Same with the bluespace beacon outside security in D2
- Sensors and starmap seems to have issues too, though I was only told so, so I'm not sure if it actually is true

2024-04-03 01:14 UTC, RustingWithYou commented
> Sensors and starmap seems to have issues too, though I was only told so, so I'm not sure if it actually is true

Can confirm - overmap effects are layered below the overmap space turfs for some reason, meaning that navigation is effectively impossible.

This has also caused some bugs with mapping - pipes are now layered under all turfs in StrongDMM, making atmos mapping very difficult

2024-04-13 17:44 UTC, DreamySkrell approved these changes

2024-04-13 17:58 UTC, NonQueueingMatt commented on html/changelogs/GeneralCamo - Plane Masters.yml
> +  - bugfix: "Floor lights no longer render under floor decals."
```suggestion
  - refactor: "Ported plane masters from Bay."
  - refactor: "Ported some Z-Mimic changes/improvements/bugfixes from Nebula/Bay."
  - bugfix: "Floor lights no longer render under floor decals."
```

2024-04-13 18:18 UTC, merged