Headmaster Remap
Aurorastation/Aurora.3 pull request #18752
Opened 2024-03-25 19:19 UTC by lavillastrangiato

* Title. Remaps the PRA Headmaster ship and updates it to mapping standards.

<img width="723" alt="headmaster" src="https://github.com/Aurorastation/Aurora.3/assets/63124803/0adbd090-14d1-45b5-b043-097871a963d3">

2024-03-25 19:19 UTC, lavillastrangiato commented
!review

2024-03-26 18:12 UTC, DreamySkrell commented
all of floors of the `/turf/simulated/floor` type should be `/turf/simulated/floor/plating` instead

2024-03-26 18:16 UTC, DreamySkrell commented
![image](https://github.com/Aurorastation/Aurora.3/assets/107256943/769da4d3-ee40-49ef-aed6-68f34bd58560)

not requesting to change this, this is just to keep in mind for the future

in the past (and in this PR), docking and shuttle airlocks were defined in the map, using `/obj/effect/map_effect/marker/airlock/docking` and manually setting the vars

but I think it is much better to define them in code, like in screenshot above (and less error-prone, and easier to review or see what's wrong if they don't work)

2024-03-26 18:20 UTC, DreamySkrell commented
![image](https://github.com/Aurorastation/Aurora.3/assets/107256943/09bbe744-f69a-4b12-9adf-890e43b8f5d8)
![image](https://github.com/Aurorastation/Aurora.3/assets/107256943/e340c44f-421c-4f4b-8f0a-74c4e21ecbab)

not requesting to change this, but the ship would look a ton nicer if it had windows with matching window frames

use `/obj/effect/map_effect/window_spawner/full/shuttle` with vars changed like in the second screenshot

the window is colored only in map preview - the window should be normal in game, only the frame colored

for convenience you could also add a specific type for the window spawner like `/obj/effect/map_effect/window_spawner/full/shuttle/raider`

2024-03-26 18:25 UTC, DreamySkrell commented
![image](https://github.com/Aurorastation/Aurora.3/assets/107256943/0ae3d1e2-39a3-4b0c-94df-5832c6e5bffa)
space turf under door

2024-03-26 18:26 UTC, DreamySkrell commented
![image](https://github.com/Aurorastation/Aurora.3/assets/107256943/2b4adc4f-e068-416b-8b8d-0d4e074e93c5)
two APCs in one area

2024-03-26 18:29 UTC, DreamySkrell commented
hangar blast doors are using `/turf/unsimulated/wall/fakepdoor`
unsimulated walls cannot be destroyed or the like
should just be blast doors without an id or a connected button instead

2024-03-26 18:30 UTC, DreamySkrell commented
ship SMES is using `/obj/machinery/power/smes/buildable/horizon_shuttle` type
should be `/obj/machinery/power/smes/buildable/third_party_shuttle` instead

2024-03-26 18:31 UTC, DreamySkrell commented
body scanner without a console

2024-03-26 18:34 UTC, DreamySkrell commented
![image](https://github.com/Aurorastation/Aurora.3/assets/107256943/8db80424-22ed-412e-acc0-8bc543832344)
this tile with the light is kinda not connected to the rest of the ship

2024-03-26 18:37 UTC, DreamySkrell commented
![image](https://github.com/Aurorastation/Aurora.3/assets/107256943/44d197a3-3f7d-437f-bb51-6d48a50ec2a5)
all away site/ship maps should be 255x255

2024-03-28 15:44 UTC, DreamySkrell commented
![image](https://github.com/Aurorastation/Aurora.3/assets/107256943/9fd28471-10e8-4f7c-8a4e-c7412cc39f16)
shuttle can't actually fit in transit area

2024-03-28 15:56 UTC, DreamySkrell commented
![image](https://github.com/Aurorastation/Aurora.3/assets/107256943/d1893d74-1e76-40e8-b63d-e4e2088aa423)
also the tags are wrong on the injectors and vents for the CO2 tanks
injector has "_out_" tag, but it should be "_in_" as it is used to put has into the tank
vent is the same issue, has "_in_", but should be "_out_" as it is used to get gas out of the tank

2024-03-28 16:03 UTC, DreamySkrell commented on maps/away/ships/pra/headmaster/headmaster_ship.dm
>  /obj/machinery/computer/shuttle_control/explore/headmaster_shuttle
instead of making this console subtype of `/explore` and setting all the terminal vare, base it on `/explore/terminal`

2024-03-28 16:05 UTC, DreamySkrell commented
please play test your maps, some of these issues (shuttle, CO2 tanks, space tile under door) could've been easily found by just taking like 10 minutes to walk around the ship, and try fly it or the shuttle

2024-03-29 01:07 UTC, lavillastrangiato commented
> please play test your maps, some of these issues (shuttle, CO2 tanks, space tile under door) could've been easily found by just taking like 10 minutes to walk around the ship, and try to fly it or the shuttle

I do play-test the maps (multiple times), and I do spawn as the ghost-role to walk around the ship. I took off in the shuttle multiple times to test the airlock as well, and I never clued in to the transit area because there were no visual bugs or errors while I ran the test server.

The changes have been made.

2024-03-29 04:22 UTC, Eyeveri requested changes
Hey there. Great mapping overall. 

I found a few things that are minor, but matter for the overall unity of ships/maps. I make these mistakes too. 


First, you have some missing turfs. Nothing crazy. There should be tiles under the blast doors. 
![wrong turf](https://github.com/Aurorastation/Aurora.3/assets/98699252/6518fd6c-f577-4c29-be1f-2786570bde7c)

![missingplating](https://github.com/Aurorastation/Aurora.3/assets/98699252/dda9bae5-b5a2-4dbb-b886-4a40b9293473)

Second, just some decal issues. In the github mapping guides it says you should put hatched marks under doors and fire doors.
![MissingDecals](https://github.com/Aurorastation/Aurora.3/assets/98699252/148675c0-e9e6-40a4-afe5-24588f73252e)
Every door on the ship needs these markers. Please add them :) 

Lastly, very minor, but you have some decals being covered by the floor paint. 
![ovrlapdecals](https://github.com/Aurorastation/Aurora.3/assets/98699252/b70e0cb2-48b8-40f9-832c-79ef2705b34c)
It is just these two, nothing else that I can see. 

Atmos looks good, power looks good, areas look fine, etc. Great job on modernizing it, all in all.

2024-03-30 08:02 UTC, lavillastrangiato commented
@Eyeveri So, I added some hatched markings under the blast doors, and in the doors to the CIC and midship hall. The mapping guide says to place hatched markings under doors _if it fits the area_; personally, I felt the aesthetic of hatched markings under every door was a little excessive, so I placed them under majorly-trafficked doors or doors that have blast doors on them.

2024-04-01 21:03 UTC, DreamySkrell commented
![image](https://github.com/Aurorastation/Aurora.3/assets/107256943/1aedf616-e7c8-4ff7-ba7b-9a3a7bc750a6)
non-colored windows here, while all the other windows are the nice shuttle windows with window frames that match walls

2024-04-01 21:04 UTC, DreamySkrell approved these changes

2024-04-01 21:06 UTC, DreamySkrell commented on maps/away/ships/pra/headmaster/headmaster_ship.dm
> +	light_power_on = 1
some of these vars are already defined on `/obj/machinery/computer/shuttle_control/explore/terminal`
remove the re-definitions

2024-04-01 21:26 UTC, Eyeveri approved these changes

2024-04-01 21:28 UTC, Eyeveri approved these changes

2024-04-04 11:38 UTC, merged