Adds Golden Deep loadout items.
Aurorastation/Aurora.3 pull request #18767
Opened 2024-03-26 17:30 UTC by TheStryker

Adds 19 new Golden Deep loadout items by Noble Row.

![lisan al gaib](https://github.com/Aurorastation/Aurora.3/assets/19821403/27579fb9-8bc7-42c7-bb72-5bb9365a4b6e)
![the peasantry](https://github.com/Aurorastation/Aurora.3/assets/19821403/3cfeb12f-579b-485a-a480-5966ae85a782)

2024-03-27 01:26 UTC, TheStryker commented
!review

2024-03-27 03:22 UTC, Sniblet commented
underscores in player-facing item names
![image](https://github.com/Aurorastation/Aurora.3/assets/36427443/c0bdaebc-6e10-48f1-8c0c-1a099ad61436)
eccentric coat has the same thing

2024-03-27 21:04 UTC, Ben10083 requested changes

2024-03-27 21:04 UTC, Ben10083 commented on code/modules/clothing/factions/goldendeep.dm
> +	name = "valiant_tabbard"
```suggestion
	name = "valiant tabbard"
```

2024-03-27 21:04 UTC, Ben10083 commented on code/modules/clothing/factions/goldendeep.dm
> +	name = "eccentric_coat"
```suggestion
	name = "eccentric coat"
```

2024-03-29 14:55 UTC, SleepyGemmy reviewed
**general**
- underscores in paths (i.e. `golden_deep` instead of `goldendeep`) is preferable.
- icon definition should preferably go before icon and item states.

2024-03-29 14:55 UTC, SleepyGemmy commented on code/modules/clothing/factions/goldendeep.dm
> +	desc = " What. Is. That? This coat is long with reinforcement to make someone look like an angel of old, or a clown."
```suggestion
	desc = "This coat is long with reinforcement to make someone look like an angel of old, or a clown."
```

2024-03-29 14:55 UTC, SleepyGemmy commented on code/modules/clothing/factions/goldendeep.dm
> +	desc = "Viewed as ostentatious by outsiders (and perhaps insiders, for that matter,) capes nonetheless remain as a means of quickly broadcasting one's status (or pretentions of status)."
```suggestion
	desc = "Viewed as ostentatious by outsiders (and perhaps insiders, for that matter) capes nonetheless remain as a means of quickly broadcasting one's status (or pretentions of status)."
```

2024-03-29 14:55 UTC, SleepyGemmy commented on code/modules/clothing/factions/goldendeep.dm
> +	desc = " Billowing fabric for all classes with a regal clasp that hints at its original merchant designers."
```suggestion
	desc = "Billowing fabric for all classes with a regal clasp that hints at its original merchant designers."
```

2024-03-29 14:55 UTC, SleepyGemmy commented on code/modules/clothing/factions/goldendeep.dm
> +	desc = "The fur of an animal, soft and fluffy, now repurposed as a decorative neck wrap. "
```suggestion
	desc = "The fur of an animal, soft and fluffy, now repurposed as a decorative neck wrap."
```

2024-03-29 14:55 UTC, SleepyGemmy commented on code/modules/clothing/factions/goldendeep.dm
> +	desc = "Like a true monarch, has a metal rim capped with a cloth top piece. Peaked in a ornate point. "
```suggestion
	desc = "Like a true monarch, has a metal rim capped with a cloth top piece. Peaked in a ornate point."
```

2024-03-29 14:55 UTC, SleepyGemmy commented on code/modules/clothing/factions/goldendeep.dm
> +	slot_flags = SLOT_EARS  | SLOT_HEAD
```suggestion
	slot_flags = SLOT_EARS | SLOT_HEAD
```

2024-03-29 14:55 UTC, SleepyGemmy commented on code/modules/clothing/factions/goldendeep.dm
> +	slot_flags = SLOT_EARS  | SLOT_HEAD | SLOT_MASK
```suggestion
	slot_flags = SLOT_EARS | SLOT_HEAD | SLOT_MASK
```

2024-03-29 14:55 UTC, SleepyGemmy commented on code/modules/clothing/factions/goldendeep.dm
> +	desc = " For the hard working Thesian of the Golden Deep. Able to carry tools and withstand the rigors of work within the collective."
```suggestion
	desc = "For the hard working Thesian of the Golden Deep. Able to carry tools and withstand the rigors of work within the collective."
```

2024-03-30 15:00 UTC, Geevies approved these changes
code looks good

2024-04-04 10:25 UTC, NonQueueingMatt approved these changes

2024-04-04 10:35 UTC, merged