Tweaked the sounds to dampen the volume
Aurorastation/Aurora.3 pull request #18773
Opened 2024-03-26 23:25 UTC by FluffyGhoster

Tweaked the sounds to dampen the volume depending on what is present between the source and the destination, accounts for walls/doors/windows

Testmerge as I am not sure how expensive doing this would be

Based on feedback and inputs from Read

2024-03-26 23:42 UTC, FluffyGhoster commented
!review

2024-03-28 11:35 UTC, NonQueueingMatt requested changes

2024-03-28 11:35 UTC, NonQueueingMatt commented on code/game/sound.dm
> +/proc/aurora_snowflake_sound_calculation(mob/listening_mob, turf/turf_source, soundin, vol, vary, frequency, falloff_exponent, channel, pressure_affected, S, maxdistance, falloff_distance, use_reverb
even if funny, change the name to something more sensible please

2024-03-29 19:53 UTC, Arrow768 approved these changes

2024-04-04 10:43 UTC, NonQueueingMatt approved these changes

2024-04-04 12:53 UTC, merged