Fixed machine processing for ores going in the negatives for alloying
Aurorastation/Aurora.3 pull request #18781
Opened 2024-03-27 04:23 UTC by FluffyGhoster

Fixed a runtime found on mechs.
Fixed machine processing for ores going in the negatives for alloying.
Some more optimizations, DMdocs, turned a var into a global one, some defines added and made into bitflags, yada yada you know the usual deal.

2024-03-27 04:23 UTC, FluffyGhoster commented
!bugfix

2024-03-27 05:02 UTC, FluffyGhoster commented
!review

2024-03-27 09:02 UTC, NonQueueingMatt approved these changes

2024-03-29 19:48 UTC, Arrow768 requested changes

2024-03-29 19:48 UTC, Arrow768 commented on code/modules/heavy_vehicle/mech_interaction.dm
> +			use_cell_power(legs.power_use * CELLRATE)
Why did you change that? -> That way the mech legs only use power if they have a step sound?

2024-04-04 13:13 UTC, merged