Reduced simple animal emote sounds to short range
Aurorastation/Aurora.3 pull request #18806
Opened 2024-03-29 04:56 UTC by FluffyGhoster

Reduced simple animal emote sounds to short range.
Turned the var that hold those sounds into a lazylist, saving memory (as most simple animals don't have emote sounds).

2024-03-29 05:15 UTC, FluffyGhoster commented
!review

2024-03-29 13:40 UTC, alsoandanswer approved these changes

2024-03-29 19:34 UTC, Arrow768 approved these changes

2024-04-01 14:44 UTC, Arrow768 requested changes

2024-04-01 14:44 UTC, Arrow768 commented on code/modules/mob/living/simple_animal/simple_animal.dm
> +		playsound(src, pick(emote_sounds), 75, TRUE, SHORT_RANGE_SOUND_EXTRARANGE)
use LAZYPICK instead.

2024-04-04 12:53 UTC, merged