Atmospheric Meters now change color based on their current temperature reading
Aurorastation/Aurora.3 pull request #18819
Opened 2024-03-30 22:52 UTC by Generalcamo

Inspired by /tg/station, but sprites are my own.
![image](https://github.com/Aurorastation/Aurora.3/assets/1779662/d62c4fa5-bce5-44e2-9e2e-d8cda1524f21)

The bars in the meter now change color based on the measured temperature. This also splits up the meter icon in preparation for emissives.

2024-03-30 22:53 UTC, Generalcamo commented
!review

2024-04-04 10:42 UTC, NonQueueingMatt approved these changes

2024-04-05 03:13 UTC, nauticall requested changes

2024-04-13 17:46 UTC, Generalcamo commented on code/game/machinery/atmoalter/meter.dm
> +				temp_color = COLOR_VIOLET
This is with parity with /tg/station. I prefer not to modify pared sprites without a good reason.

2024-04-18 22:06 UTC, DreamySkrell approved these changes
I think the colors are fine

2024-04-26 08:59 UTC, NonQueueingMatt approved these changes

2024-04-26 09:34 UTC, merged