adds some new coalition weapons
Aurorastation/Aurora.3 pull request #18812
Opened 2024-03-29 23:31 UTC by crunchypretzels

![image](https://github.com/Aurorastation/Aurora.3/assets/70682905/55b43203-b627-49c2-af2d-db5bc6d87892)

Adds four new weapons from the United Syndicates and the Federal Technocracy.

Himeo has received two new guns based on the plasma cutter; the Ablett assault blaster and the Sabo-Tabby heavy blaster pistol. Both use a hydrogen cell 'magazine' to mimic the more advanced, more accurate Zavodskoi blasters on the market.

Galatea, likewise, has received the O61-B laser rifle pack set, an export model of their own O61 Infantry Laser Rifle, and a gauss 'nitro express' rifle, which fires tungsten slugs. Attempting to fire the O61 without a Galatean implant will result in consequences.

All sprites are my own handiwork, and all credit for the laser pack goes to Alberyk for his work on the gatling gun. Matt and Schwann also provided a great deal of help.

2024-03-29 23:31 UTC, crunchypretzels commented
!wip

2024-03-30 02:04 UTC, crunchypretzels commented
!review

2024-04-04 10:41 UTC, NonQueueingMatt requested changes

2024-04-04 10:41 UTC, NonQueueingMatt commented on code/game/objects/items/weapons/implants/implants/galatean.dm
> +	if(istype(M, /mob/living/carbon/human))
use ishuman

2024-04-04 10:41 UTC, NonQueueingMatt commented on code/modules/projectiles/guns/energy/special.dm
> +		gun = null
QDEL_NULL(gun)

2024-04-04 10:41 UTC, NonQueueingMatt commented on code/modules/projectiles/guns/energy/special.dm
> +/obj/item/galatealaserpack
use a clearer path name, 3 words with no spacing is quite a lot

2024-04-04 10:41 UTC, NonQueueingMatt commented on code/modules/projectiles/guns/energy/special.dm
> +		user = usr
ishuman

2024-04-04 10:41 UTC, NonQueueingMatt commented on code/modules/projectiles/guns/energy/special.dm
> +		to_chat(user, "<span class='warning'>\The [src] must be worn to deploy \the [gun]!</span>")
use the SPAN_X macros, needs to be done throughout this file

2024-04-04 10:41 UTC, NonQueueingMatt commented on code/modules/projectiles/guns/energy/special.dm
> +	if(attacking_item == gun)
use_check_and_message this as well

2024-04-04 10:41 UTC, NonQueueingMatt commented on code/modules/projectiles/guns/energy/special.dm
> +		return 1
```suggestion
		return TRUE
```

2024-04-26 08:59 UTC, NonQueueingMatt approved these changes

2024-05-02 22:01 UTC, FluffyGhoster approved these changes

2024-05-05 14:06 UTC, merged