Merchant Traders now have greetings for Species
Aurorastation/Aurora.3 pull request #18825
Opened 2024-03-31 19:33 UTC by Ben10083

Traders used to only do greetings based on each subspecies, due to significant overlap for some (ie, IPCs), functionality added for traders to greet based on general species, if a specific subspecies is not found.

Adds new defines for each species that is a list that has all subspecies for them (ALL_IPC covers all frames for examples)

2024-03-31 19:35 UTC, Ben10083 commented
Going to look into adding racism to the traders (this isnt a joke)

2024-03-31 19:36 UTC, Ben10083 commented
!wip

2024-03-31 21:35 UTC, DreamySkrell commented on code/__DEFINES/species.dm
> +	)
All of these should have names like `ALL_HUMAN_SPECIES` to be a bit more consistent with other defines

2024-04-01 00:13 UTC, Ben10083 commented
!review

2024-04-01 00:13 UTC, Ben10083 commented
It is done.

2024-04-04 10:33 UTC, NonQueueingMatt requested changes

2024-04-04 10:33 UTC, NonQueueingMatt commented on code/datums/trading/trade.dm
> +					return result
```
if(species in flatten_list(item))
    return result
```

2024-04-04 10:33 UTC, NonQueueingMatt commented on code/datums/trading/trade.dm
> +				general = "IPC"
use a keyed list here instead of a massive if chain

2024-04-05 16:35 UTC, Generalcamo requested changes

2024-04-05 16:35 UTC, Generalcamo commented on code/datums/trading/weaponry.dm
> +		SPECIES_TAJARA_ZHAN = TRADER_BIAS_DISCOUNT,
You're contradicting the comment above.

2024-04-05 16:39 UTC, Generalcamo approved these changes

2024-04-18 01:12 UTC, Alberyk approved these changes

2024-04-18 22:08 UTC, DreamySkrell approved these changes

2024-05-01 23:54 UTC, merged