Hadiism Versebook
Aurorastation/Aurora.3 pull request #18852
Opened 2024-04-03 16:01 UTC by Ben10083

- [ ] Code
- [ ] LORE (desc and .txt file verses
- [ ] Sprite

New versebook: Hadiist Manifesto. Replacing the old book

2024-04-03 16:02 UTC, Ben10083 commented
!wip

2024-04-03 17:30 UTC, Generalcamo requested changes

2024-04-03 17:30 UTC, Generalcamo commented on code/game/objects/items/devices/versebook.dm
> +	desc = "A compact red book that is commonly considerd required reading for PRA citizens. This book can be found anywhere the PRA is, with the party commonly providing free copies of the Manifesto to
```suggestion
	desc = "A compact red book that is commonly considered required reading for PRA citizens. This book can be found anywhere the PRA is, with the party commonly providing free copies of the Manifesto to tourists."
```

2024-04-03 17:30 UTC, Generalcamo commented on code/game/objects/items/devices/versebook.dm
> +	name = "\improper Constitution of The Federal Republic of Biesel (abdridged)"
```suggestion
	name = "\improper Constitution of The Federal Republic of Biesel (abridged)"
```

2024-04-03 17:30 UTC, Generalcamo commented on code/game/objects/items/devices/versebook.dm
> +	desc_extended = "HE/SHE LOVES HADII."
This is unlikely to be accepted.

2024-04-03 17:35 UTC, Ben10083 commented on code/game/objects/items/devices/versebook.dm
> +	desc_extended = "HE/SHE LOVES HADII."
It would

2024-04-03 21:17 UTC, FluffyGhoster commented
Merge master to fix the CI

2024-04-03 21:46 UTC, Ben10083 commented
Didn't mean to mark it. Oops

2024-09-04 19:02 UTC, Ben10083 commented
This will be closed in favor of a newer version with a wider scope and less conflicts.

2024-09-04 20:28 UTC, Ben10083 commented
https://github.com/Aurorastation/Aurora.3/pull/19870

2024-09-04 20:28 UTC, closed without merging