Hailstorm fixes and console updates
Aurorastation/Aurora.3 pull request #18863
Opened 2024-04-04 20:06 UTC by Alberyk

-fixes the hailstorm shuttle not docking
-fixes the hailstorm pipes not connecting to the vents
-added primitive versions for the ship computers using sprites we had but were never implemented

2024-04-04 20:13 UTC, FluffyGhoster requested changes

2024-04-04 20:13 UTC, FluffyGhoster commented on maps/away/ships/dpra/hailstorm/hailstorm_ship.dm
> +	template_flags = TEMPLATE_FLAG_SPAWN_GUARANTEED
Probably forgot the flag here

2024-04-04 20:42 UTC, FluffyGhoster approved these changes
Code LGTM

2024-04-05 07:24 UTC, Arrow768 approved these changes

2024-04-06 19:33 UTC, alsoandanswer requested changes
Don't use these sprites. They should be deleted

Use the modular_terminal.dmi sprites

2024-04-07 16:02 UTC, alsoandanswer approved these changes

2024-04-08 09:01 UTC, merged