Makes prosthetics editable in appearance editor
Aurorastation/Aurora.3 pull request #18879
Opened 2024-04-06 05:04 UTC by RustingWithYou

The appearance editor can now change organs and limbs into prosthetic/nymph/amputated versions.
As ghostroles can now edit their own limbs, the Tarwa Conglomerate ghostroles no longer have random nymph limbs.

2024-04-06 05:05 UTC, RustingWithYou commented
!review

2024-04-06 08:42 UTC, dessysalta commented
> The appearance editor can now change organs and limbs into prosthetic/nymph/amputated versions.

i love you

2024-04-06 20:27 UTC, Sniblet commented
One step closer to offships being real people

2024-04-07 08:46 UTC, RustingWithYou commented
> One step closer to outsiders being real people I've noticed that only antags got the ability to edit height, and not ghostspawns. I guess they have separate appearance editors? I can't read so I don't know why this happens. I hope this works for both!

The reason for this is that height is in the species window which only shows up if the appearance editor lets you change your species. I might see about changing that in this PR too, actually

2024-04-08 08:31 UTC, NonQueueingMatt requested changes

2024-04-08 09:57 UTC, RustingWithYou commented on code/modules/mob/living/carbon/human/appearance.dm
> +	return valid_prosthetics
Moved to species level

2024-04-13 19:50 UTC, NonQueueingMatt approved these changes

2024-04-18 22:16 UTC, DreamySkrell approved these changes

2024-04-18 23:09 UTC, merged