Diona now have a verb that lets them use magboot-like functionality.
Aurorastation/Aurora.3 pull request #18875
Opened 2024-04-05 22:26 UTC by NonQueueingMatt

title

2024-04-05 22:26 UTC, NonQueueingMatt commented
!review

2024-04-06 19:32 UTC, alsoandanswer commented on code/modules/mob/living/carbon/human/diona_gestalt.dm
> +		REMOVE_TRAIT(src, TRAIT_SHOE_GRIP)
```suggestion
		REMOVE_TRAIT(src, TRAIT_SHOE_GRIP, INNATE_TRAIT)
```

2024-04-06 19:32 UTC, alsoandanswer commented on code/modules/mob/living/carbon/human/diona_gestalt.dm
> +		ADD_TRAIT(src, TRAIT_SHOE_GRIP)
```suggestion
		ADD_TRAIT(src, TRAIT_SHOE_GRIP, INNATE_TRAIT)
```

2024-04-10 02:02 UTC, FluffyGhoster commented on code/modules/mob/living/carbon/human/diona_gestalt.dm
> +/mob/living/carbon/human/proc/root_to_ground()
DMDoc this (the name doesn't make readily apparent what this does)

2024-04-10 02:02 UTC, FluffyGhoster commented on code/modules/mob/living/carbon/human/diona_gestalt.dm
> +		playsound(src, 'sound/species/diona/gestalt_split.ogg', 20)
Set an appropriate range using one of the defines

2024-04-10 02:02 UTC, FluffyGhoster commented on code/modules/mob/living/carbon/human/diona_gestalt.dm
> +		playsound(src, 'sound/species/diona/gestalt_grow.ogg', 30)
Set an appropriate range using one of the defines

2024-04-18 01:13 UTC, Alberyk approved these changes

2024-06-28 05:36 UTC, Arrow768 requested changes

2024-06-28 05:36 UTC, Arrow768 commented on code/modules/mob/living/carbon/human/diona_gestalt.dm
> +		return
I currently only have my phone available, so searching through the code is rather complicated.

It seems that all these checks are only performed once.

However if these checks are required to enable the function, they should also be performed regularly while using it.

There should also be some cost to using the "magboot" function, either in the form of decreased movement speed or increased hunger (or something else?)
Is that already handled somewhere else (by the trait?)?

2024-09-21 12:02 UTC, closed without merging