Wrist Layer Toggling
Aurorastation/Aurora.3 pull request #18889
Opened 2024-04-07 13:37 UTC by Geevies

* You can now set wristwear to layer under your uniform, over your uniform, or over your suit.

2024-04-07 13:37 UTC, Geevies commented
!review

2024-04-07 18:20 UTC, DreamySkrell commented
does this not allow wearing wristwear on top of voidsuits for example
kind of silly
probably not worth the effort to not allow that

2024-04-10 02:07 UTC, FluffyGhoster requested changes

2024-04-10 02:07 UTC, FluffyGhoster commented on code/modules/client/preference_setup/loadout/items/wrists.dm
> +var/datum/gear_tweak/wrist_layer/gear_tweak_wrist_layer = new()
Make this a GLOB var if you need a global variable

2024-04-14 11:48 UTC, Geevies commented
> does this not allow wearing wristwear on top of voidsuits for example kind of silly

addressed this here: https://github.com/Aurorastation/Aurora.3/pull/18949

2024-04-18 22:17 UTC, DreamySkrell approved these changes

2024-04-26 09:39 UTC, merged