Sleeveless Crop Top Hoodies
Aurorastation/Aurora.3 pull request #18890
Opened 2024-04-07 14:23 UTC by Geevies

* Added a sleeveless crop top hoodie.

2024-04-07 14:23 UTC, Geevies commented
!review

2024-04-08 12:16 UTC, nauticall requested changes
![image](https://github.com/Aurorastation/Aurora.3/assets/55491249/f3ea3ccd-e831-4346-92fb-e01a4cda3539)
![image](https://github.com/Aurorastation/Aurora.3/assets/55491249/7a899513-698f-40f9-b157-a9b7dcd5d489)

Rogue pixels on these sprites (`hoodie_sleeveless_crop_open_su` & `hoodie_sleeveless_crop_t_su`).

2024-04-22 06:40 UTC, nauticall approved these changes
you did it!!! 👏👏👏👏

2024-04-26 09:00 UTC, NonQueueingMatt approved these changes

2024-04-26 09:34 UTC, merged