Adds Biesel as an exoplanet
Aurorastation/Aurora.3 pull request #18902
Opened 2024-04-09 00:59 UTC by Alberyk

This pr adds biesel as a visitable exoplanet.

To do:

- [ ] Maybe add animals

2024-04-12 19:13 UTC, Geevies requested changes

2024-04-12 19:13 UTC, Geevies commented on code/modules/maps/planet_types/lore/tauceti.dm
> +	initial_weather_state = /singleton/state/weather/calm/snow_planet
update this bit to not be snow planet weather

2024-04-12 19:13 UTC, Geevies commented on code/modules/maps/planet_types/lore/tauceti.dm
> +	has_trees = FALSE
i'm not exactly sure what flora_diversity and has_trees does, but i figure Biesel would have some. if you have a reason for it being set like this (like the biesel theme handling it) just comment that here please

2024-04-12 19:13 UTC, Geevies commented on code/modules/maps/planet_types/lore/tauceti.dm
> +	ruin_type_whitelist = list ()
```suggestion
	ruin_type_whitelist = list()
```

2024-04-14 09:50 UTC, Geevies approved these changes

2024-04-15 08:39 UTC, NonQueueingMatt approved these changes

2024-04-15 09:31 UTC, merged