Luceian stuff
Aurorastation/Aurora.3 pull request #18906
Opened 2024-04-09 09:55 UTC by nauticall

Adds a lot of Luceian stuff for Assunzionis and brings them up to speed as a contender religion.

- Added several items relating to Luceism, the religion of Assunzione.
- Added chaplain items for Luceism: robes, a cassock, and a new null rod, the Luminous Sceptre.
- Added a new versebook, the Luceian Book of Scripture, available to Assunzionii characters. It's a versebook with various texts from Luceism.
- Added a new origin and accent for Dionae, Luceborn, with them originating from Assunzione and being faithful to Luceism.
- Resprited the Luceian amulet, Luceian Book of Scripture, and the Assunzione cloak.
- Compressed the loadout warding sphere and warding sphere case into just one loadout item that already comes with a case.
- Religions with unique religious books (versebooks) now have their chaplains spawn with the versebook in question, rather than a generic black tome.

![image](https://github.com/Aurorastation/Aurora.3/assets/55491249/e477d9c7-cbfb-4976-a905-1bda0cd99820)
![image](https://github.com/Aurorastation/Aurora.3/assets/55491249/7523e3c8-04ee-4146-ae9f-93702020adda)
![image](https://github.com/Aurorastation/Aurora.3/assets/55491249/68a69aa5-a346-4c38-b891-73516a877615)

2024-04-09 09:56 UTC, nauticall commented
!review

2024-04-10 13:47 UTC, sadkermit commented
The dionae lore team aren't fond of the Luceborn origin and accent currently, as there is no explicit lore or named community for dionae on Assunzionii beyond their views on Luceism. That'll have to be gutted from the PR, pretty please.

2024-04-13 18:48 UTC, listerla commented on code/modules/background/origins/origins/diona/coalition.dm
> +		/singleton/origin_item/origin/assunzione_dionae ,
This should probably be cut out.

2024-04-13 18:48 UTC, listerla commented on html/changelogs/nauticall-luceism_stuff.yml
> +  - rscadd: "Added a new origin and accent for Dionae, Luceborn, with them originating from Assunzione and being faithful to Luceism."
This too.

2024-04-15 09:07 UTC, NonQueueingMatt requested changes

2024-04-15 09:07 UTC, NonQueueingMatt commented on aurorastation.dme
> -#include "interface\skin.dmf"
?

2024-04-15 09:07 UTC, NonQueueingMatt commented on code/modules/clothing/factions/assunzione.dm
> +	name = "\improper Luceian Pyramidical keeper robe"
lowercase this

2024-04-20 10:25 UTC, NonQueueingMatt approved these changes

2024-04-20 13:46 UTC, Geevies approved these changes

2024-04-23 12:31 UTC, merged