Update changelog generation
Aurorastation/Aurora.3 pull request #18915
Opened 2024-04-10 16:39 UTC by FluffyGhoster

Updated the changelog system

2024-04-10 16:54 UTC, FluffyGhoster commented
This also fixes #17730

2024-04-10 17:33 UTC, FluffyGhoster commented
!review

2024-04-10 17:51 UTC, alsoandanswer approved these changes

2024-04-10 19:15 UTC, NonQueueingMatt approved these changes

2024-04-10 19:22 UTC, Alberyk approved these changes

2024-04-11 20:48 UTC, Arrow768 requested changes

2024-04-11 20:48 UTC, Arrow768 commented on tgui/packages/tgui/interfaces/Changelog.js
> +        <h1>Traditional Games Space Station 13</h1>
This is Aurora Station.
Not TG Station

2024-04-11 20:48 UTC, Arrow768 commented on tgui/packages/tgui/interfaces/Changelog.js
> +          Baystation 12, /vg/station, NTstation, CDK Station devs,
Tgstation, baystation should be added

2024-04-11 21:23 UTC, Arrow768 approved these changes

2024-04-11 21:34 UTC, merged