Adds two Konyanger medals.
Aurorastation/Aurora.3 pull request #18914
Opened 2024-04-10 14:15 UTC by TheStryker

Adds two Konyanger decorations, the Foreign Loyalty Medal and the Spilled Blood medal, for use in lore events or whenever admins want to spawn it.
![image](https://github.com/Aurorastation/Aurora.3/assets/19821403/bbfd0364-b780-463a-b206-08b86709ed61)

2024-04-10 14:17 UTC, TheStryker commented
!review

2024-04-10 16:56 UTC, FluffyGhoster approved these changes

2024-04-12 18:49 UTC, Geevies requested changes

2024-04-12 18:49 UTC, Geevies commented on code/modules/clothing/under/accessories/medal.dm
> +	desc = "A medal awared by the Republic of Konyang for unconditional service rendered to the nation that greatly supports its values, institutions, and sovereignty."
```suggestion
	desc = "A medal awarded by the Republic of Konyang for unconditional service rendered to the nation that greatly supports its values, institutions, and sovereignty."
```

2024-04-13 15:34 UTC, Geevies approved these changes

2024-04-13 16:23 UTC, merged