Makes the Sani'Orios away site more interesting
Aurorastation/Aurora.3 pull request #18928
Opened 2024-04-12 01:41 UTC by Alberyk

The Sani'Orios away site now has a dpra asteroid outpost with a small crew and some defenses.

2024-04-18 22:20 UTC, DreamySkrell commented
![image](https://github.com/Aurorastation/Aurora.3/assets/107256943/d1f9585e-20b7-47e4-affc-d826ea7ed55e)
missing wire

2024-04-18 22:22 UTC, DreamySkrell commented
![image](https://github.com/Aurorastation/Aurora.3/assets/107256943/7d2c88c6-db11-4c3e-9120-2f2e8454f3c0)
wrong turf here (space)

2024-04-18 22:54 UTC, DreamySkrell requested changes
.

2024-04-18 22:56 UTC, DreamySkrell commented on maps/away/away_site/tajara/saniorios_outpost/saniorios_outpost_ghostroles.dm
> +	desc = "Crew a Democratic People's Republic of Adhomai's asteroid outpost in Sani'Orios."
desc should explain more about this role - like what do they do?
there should also be welcome_text or whatever, that shows on spawn, and explains things more in detail

2024-04-26 09:00 UTC, NonQueueingMatt approved these changes

2024-04-26 09:34 UTC, merged