Adds Offship Lathe Materials
Aurorastation/Aurora.3 pull request #18935
Opened 2024-04-13 00:26 UTC by courierbravo

Adds aluminum, lead, and plastic to every ship with a lathe.

2024-04-13 00:27 UTC, courierbravo commented
!review

2024-04-13 01:19 UTC, courierbravo commented
note: Changes to the peacekeeper ship are for the kitchen. I was going to make this PR a bit broader in scope and just fix things as I found them. But I feel like if I'm gonna do those kinds of things, they should be their own separate PR or series of PR's

2024-04-13 10:40 UTC, Arrow768 requested changes

2024-04-13 10:40 UTC, Arrow768 commented on html/changelogs/CourierBravo - Lathe_Mats.yml
> +author: ChangeMe
ChangeMe

2024-04-13 15:37 UTC, courierbravo commented on html/changelogs/CourierBravo - Lathe_Mats.yml
> +author: ChangeMe
Fixed the changelog

2024-04-13 17:09 UTC, DreamySkrell approved these changes

2024-04-16 20:04 UTC, NonQueueingMatt approved these changes

2024-04-16 20:22 UTC, merged