Uueoa-Esa, Part 1: Sector & Planets
Aurorastation/Aurora.3 pull request #18941
Opened 2024-04-13 22:54 UTC by RustingWithYou

Adds the Uueoa-Esa system, its skybox and stargazer, and its lore planets, currently without ruins for ease of review.

2024-04-13 22:54 UTC, RustingWithYou commented
!review

2024-04-15 22:07 UTC, Alberyk approved these changes

2024-04-16 09:34 UTC, DreamySkrell requested changes

2024-04-16 09:34 UTC, DreamySkrell commented on maps/away/away_site/crystal_planet_outpost/crystal_planet_outpost_.dm
> +	sectors_blacklist = list(SECTOR_BURZSIA, SECTOR_HANEUNIM, SECTOR_SRANDMARR, SECTOR_TAU_CETI, SECTOR_UUEOAESA) //it's a whole planet, shouldn't have it in predefined sectors
at this point there should be a a list of sectors named like `ALL_SPECIFIC_SECTORS` or something, documented to mean `/// all non-generic, named and specific sectors, where generic planets or the like should not spawn`

instead blacklisting specific sites every time one is added

2024-04-16 09:34 UTC, DreamySkrell commented on maps/away/ships/freebooter/freebooter_ship.dm
> +	sectors = list(SECTOR_TAU_CETI, SECTOR_ROMANOVICH, SECTOR_CORP_ZONE, SECTOR_VALLEY_HALE, SECTOR_NEW_ANKARA, SECTOR_BADLANDS, SECTOR_AEMAQ, SECTOR_SRANDMARR, ALL_COALITION_SECTORS, SECTOR_UUEOAESA)
this should use the `ALL_...` lists instead of adding new sectors to it manually

and anyways the freebooter should just be `ALL_POSSIBLE_SECTORS`

2024-04-16 09:34 UTC, DreamySkrell commented on maps/away/ships/tajara/taj_smuggler/tajaran_smuggler.dm
> +	sectors = list(SECTOR_ROMANOVICH, SECTOR_CORP_ZONE, SECTOR_VALLEY_HALE, SECTOR_BADLANDS, SECTOR_SRANDMARR, SECTOR_NRRAHRAHUL, SECTOR_GAKAL, SECTOR_WEEPING_STARS, SECTOR_UUEOAESA)
replace the badlands sectors with just `ALL_BADLAND_SECTORS`

2024-04-16 09:34 UTC, DreamySkrell commented on maps/away/ships/tramp_freighter/tramp_freighter.dm
> +	sectors = list(SECTOR_TAU_CETI, SECTOR_ROMANOVICH, SECTOR_CORP_ZONE, SECTOR_VALLEY_HALE, SECTOR_NEW_ANKARA, SECTOR_BADLANDS, SECTOR_AEMAQ, SECTOR_SRANDMARR, ALL_COALITION_SECTORS, SECTOR_UUEOAESA)
same as freebooter, this should just be `ALL_POSSIBLE_SECTORS`

2024-04-16 09:35 UTC, DreamySkrell commented
I'll approve when above is fixed, ping me if I forget

2024-04-16 09:37 UTC, DreamySkrell commented on code/modules/maps/planet_types/lore/uueoaesa.dm
> +/obj/effect/overmap/visitable/sector/exoplanet/moghes
none of the new planets have `generate_ground_survey_result()` defined

2024-04-17 10:30 UTC, DreamySkrell commented on code/modules/maps/planet_types/lore/uueoaesa.dm
> +				ground_survey_result += "<br>Soft clays detected, composed of quartz and calcites"
ground survey for moghes looks wrong
should not be random still
and it includes stuff like low contaminants in soil - wasn't it like, nuked
so it looks like just copied from parent or something

2024-04-17 10:30 UTC, DreamySkrell commented on code/modules/maps/planet_types/lore/uueoaesa.dm
> +		ground_survey_result += "<br>Muddy dirt rich in organic material"
same as about moghes

2024-04-18 14:02 UTC, NonQueueingMatt approved these changes

2024-04-18 14:55 UTC, merged