Adds preset mineral walls for mappers.
Aurorastation/Aurora.3 pull request #18958
Opened 2024-04-15 12:44 UTC by NonQueueingMatt

Icons for these would be helpful if anyone were to provide them, otherwise I'll have to shitsprite something up.

2024-04-15 12:44 UTC, NonQueueingMatt commented
!review

2024-04-15 22:06 UTC, Alberyk approved these changes

2024-04-18 23:00 UTC, DreamySkrell requested changes

2024-04-18 23:00 UTC, DreamySkrell commented on code/modules/mining/mine_turfs.dm
> +	var/preset_mineral_name
should be documented what is this used for and what values it should take

2024-04-21 15:27 UTC, Eyeveri approved these changes

2024-04-22 18:14 UTC, DreamySkrell approved these changes

2024-04-22 21:36 UTC, merged