Adds radio stations to Tau Ceti
Aurorastation/Aurora.3 pull request #18963
Opened 2024-04-15 18:54 UTC by Alberyk

This pr adds some lore radio stations to Tau Ceti.

TODO:

- [ ] get all the stuff the lore team wrote

2024-04-18 22:59 UTC, DreamySkrell approved these changes

2024-04-20 13:33 UTC, Geevies requested changes

2024-04-20 13:33 UTC, Geevies commented on code/modules/background/space_sectors/tauceti.dm
> +		"28.1 D6 Citizen Radio" = "config/lore_radio/tau_ceti//28.1_D6_Citizen_Radio.txt",
```suggestion
		"28.1 D6 Citizen Radio" = "config/lore_radio/tau_ceti/28.1_D6_Citizen_Radio.txt",
```

2024-04-25 19:12 UTC, Geevies submitted a review, later dismissed

2024-04-26 09:01 UTC, NonQueueingMatt approved these changes

2024-04-26 20:10 UTC, Geevies approved these changes

2024-04-27 01:54 UTC, merged