Uueoa-Esa, Part 4: Untouched Lands
Aurorastation/Aurora.3 pull request #18985
Opened 2024-04-18 23:34 UTC by RustingWithYou

Adds several ruins for the Untouched Lands of Moghes

2024-04-18 23:34 UTC, RustingWithYou commented
!review

2024-04-18 23:35 UTC, RustingWithYou commented
!review

2024-04-19 05:25 UTC, FluffyGhoster commented on maps/random_ruins/exoplanets/moghes/moghes_bar.dm
> +		H.shoes.color = "#423509"
Might aswell return early if no human is passed in as parameter, also useless var

2024-04-19 05:25 UTC, FluffyGhoster commented on maps/random_ruins/exoplanets/moghes/moghes_bar.dm
> +		H.shoes.color = "#423509"
As above

2024-04-19 05:25 UTC, FluffyGhoster commented on maps/random_ruins/exoplanets/moghes/moghes_bar.dm
> +		H.shoes.color = "#423509"
As above

2024-04-19 05:25 UTC, FluffyGhoster commented on maps/random_ruins/exoplanets/moghes/moghes_diona_traders.dm
> +		H.wear_suit.color = "#42330f"
As above minus the var

2024-04-19 05:25 UTC, FluffyGhoster commented on maps/random_ruins/exoplanets/moghes/moghes_heph_mining.dm
> +	H.update_body()
Return early if the parameter is not specified

2024-04-19 05:25 UTC, FluffyGhoster commented on maps/random_ruins/exoplanets/moghes/moghes_thakh.dm
> +		H.shoes.color = "#423509"
Etc. etc. as above

2024-04-20 14:45 UTC, Eyeveri requested changes
Is this intentional? The left and right pews being inverted.
![image](https://github.com/Aurorastation/Aurora.3/assets/98699252/248a433f-c032-43b5-bb82-b6436d31da32)

All maps look great! Can't find any other reasons to not approve aside from the pews. 

The code looks fine to me on all of this, but again, I'm still learning the code side of this so Dreamy or Fluffy should take another look at them.

2024-04-22 00:11 UTC, RustingWithYou commented
> Is this intentional? The left and right pews being inverted. ![image](https://private-user-images.githubusercontent.com/98699252/324184492-248a433f-c032-43b5-bb82-b6436d31da32.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3NDQ5NjMsIm5iZiI6MTcxMzc0NDY2MywicGF0aCI6Ii85ODY5OTI1Mi8zMjQxODQ0OTItMjQ4YTQzM2YtYzAzMi00M2I1LWJiODItYjY0MzZkMzFkYTMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIyVDAwMTEwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlYTA4ZjZhYWYyMzg1YmVkNjM1MTJiZWUxNjc5OWY2ZmQ0MTI2NjMyODU0NWZlZTBhZWZiY2RhMjYwODQ4MmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vLi89YAWkX-SczkwCIK2iTGATBN4WRNk1NyJq3sgmr8)
> 
> All maps look great! Can't find any other reasons to not approve aside from the pews.
> 
> The code looks fine to me on all of this, but again, I'm still learning the code side of this so Dreamy or Fluffy should take another look at them.

Addressed and replaced with actual pews

2024-04-22 00:12 UTC, Eyeveri approved these changes

2024-04-22 12:10 UTC, merged