Adds Blueprints to Overmap Sites
Aurorastation/Aurora.3 pull request #18991
Opened 2024-04-20 03:07 UTC by RustingWithYou

Adds blueprints to most ships, as well as several away sites and ruins.
The only ships not to get blueprints were ones that still don't have proper power/atmospherics setups as new areas created by blueprints will be unpowered.

2024-04-20 03:07 UTC, RustingWithYou commented
!review

2024-04-20 10:28 UTC, Arrow768 requested changes
The blueprints need to be limited to the vessel/site they spawn at.

So you can't (for example) take the blueprints of an away site and update/edit the rooms the horizon.

2024-04-22 00:05 UTC, RustingWithYou commented
> The blueprints need to be limited to the vessel/site they spawn at.
> 
> So you can't (for example) take the blueprints of an away site and update/edit the rooms the horizon.

This mechanic was already implemented in #18947

2024-04-22 18:47 UTC, DreamySkrell approved these changes

2024-06-03 13:31 UTC, NonQueueingMatt approved these changes

2024-06-03 15:05 UTC, merged