Basic Reagent Allergen System
Aurorastation/Aurora.3 pull request #19039
Opened 2024-04-27 13:31 UTC by Geevies

* Added a minor and major blueberry allergy to the disability tab. This will add Anaphylactic Cocktail to your bloodstream, and is counteracted with adrenalin.

2024-04-27 13:32 UTC, Geevies commented
!review

2024-04-27 18:50 UTC, Acetrea commented
I really like this and I'd love to see more things added than just blueberries!

2024-05-01 16:01 UTC, FluffyGhoster commented on code/__HELPERS/global_lists.dm
> +		if(T.abstract_type == path)
Use the appropriate proc instead

2024-05-05 18:18 UTC, Arrow768 requested changes
As discussed on discord this is too simplistic.

* A allergen implementation should implement all (or most) currently known allergens that are relevant and not just blueberries 
* A reagent needs to be able to contain more than one allergen
* Chemical reactions should (by default) pass the allergens present in all their `required_reagents` along to the `result`
* It must be possible to override this behaviour in the /datum/chemical_reaction.
* (opt) Ideally it should be possible to have different allergens with different effects.
* (opt) Allergens should be identified by the chemistry analyzer

2024-08-25 08:21 UTC, Geevies commented
don't have the time or energy to work on this one again at the moment, feel free to take over if you're interested, i might some time in the future...............

2024-08-25 08:21 UTC, closed without merging