Roller Bed Racks - Revivial
Aurorastation/Aurora.3 pull request #19057
Opened 2024-04-28 18:51 UTC by 1Sparky1

Revival of #17075. Adds roller bed racks which can hold 4 collapsed beds for organisation. Replaces the beds that spawn on the medical bay tables with racks of the corresponding amounts.

2024-04-28 18:52 UTC, 1Sparky1 commented
!review

2024-05-02 22:08 UTC, FluffyGhoster requested changes

2024-05-02 22:08 UTC, FluffyGhoster commented on code/game/objects/structures/stool_bed_chair_nest/bed.dm
> +	var/list/held
Give the list a type, based on what it will contain
Also, DMDoc this

2024-05-02 22:08 UTC, FluffyGhoster commented on code/game/objects/structures/stool_bed_chair_nest/bed.dm
> +	LAZYINITLIST(held)
There's no point in it being a lazylist if you initialize it at Initialize, it might aswell be a normal list

2024-05-02 22:08 UTC, FluffyGhoster commented on code/game/objects/structures/stool_bed_chair_nest/bed.dm
> +	var/initial_beds = 4
DMDoc this

2024-05-02 22:08 UTC, FluffyGhoster commented on code/game/objects/structures/stool_bed_chair_nest/bed.dm
> +	for(i=1, i<=initial_beds, i++)
No

Use `for(var/_ in 1 to initial_beds)` instead

2024-05-02 22:08 UTC, FluffyGhoster commented on code/game/objects/structures/stool_bed_chair_nest/bed.dm
> +		qdel(O)
QDEL_LIST

2024-05-02 22:08 UTC, FluffyGhoster commented on code/game/objects/structures/stool_bed_chair_nest/bed.dm
> +/obj/structure/roller_rack/attackby(W, mob/user)
No, use the appropriate and correct proc header

`/attackby(obj/item/attacking_item, mob/user)`

2024-05-03 16:57 UTC, 1Sparky1 commented on code/game/objects/structures/stool_bed_chair_nest/bed.dm
> +	var/initial_beds = 4 // The number of beds the rack will spawn with
Thank you for bearing with me on this - I think I've got it this time?

2024-05-03 17:58 UTC, FluffyGhoster commented on code/game/objects/structures/stool_bed_chair_nest/bed.dm
> +	var/initial_beds = 4 // The number of beds the rack will spawn with
Seems like so, yes

2024-05-03 18:22 UTC, 1Sparky1 commented on code/game/objects/structures/stool_bed_chair_nest/bed.dm
> +	var/initial_beds = 4 // The number of beds the rack will spawn with
I understand what you mean now, ty.

2024-05-03 20:07 UTC, FluffyGhoster approved these changes

2024-05-05 14:13 UTC, Arrow768 reviewed
It looks like there is something unusual going on with your map changes.
16+k lines changed for a few new objects is not normal

2024-05-06 10:40 UTC, DreamySkrell approved these changes

2024-05-06 12:12 UTC, merged