Tret Industrial Complex
Aurorastation/Aurora.3 pull request #19054
Opened 2024-04-28 10:28 UTC by DreamySkrell

wip

2024-04-28 10:28 UTC, DreamySkrell commented
!wip

2024-05-27 20:22 UTC, DreamySkrell commented
!review

2024-05-27 21:02 UTC, FluffyGhoster requested changes

2024-05-27 21:02 UTC, FluffyGhoster commented on maps/_common/mapsystem/map.dm
> +		if (template.load_new_z(themes=exoplanet_themes))
As above

2024-05-30 22:13 UTC, DreamySkrell commented on code/modules/maps/map_template.dm
> +/datum/map_template/proc/load_new_z(var/no_changeturf = TRUE, var/list/themes = null)
fixed mmmaybe

2024-05-30 22:13 UTC, DreamySkrell commented on maps/_common/mapsystem/map.dm
> +		if (template.load_new_z(themes=exoplanet_themes))
as above

2024-05-30 22:13 UTC, DreamySkrell commented on code/modules/maps/map_template.dm
> +			exoplanet_theme.generate_map(initial_z, 1, 1, 254, 254, marker_turf_type)
as above

2024-05-31 19:24 UTC, Arrow768 approved these changes

2024-06-01 23:44 UTC, Alberyk approved these changes

2024-06-02 02:03 UTC, merged