Zavod shuttle destroyed
Aurorastation/Aurora.3 pull request #19071
Opened 2024-04-30 14:57 UTC by CactusMouth

Adds a new Awaysite - **The Zavod Shuttle.**

![StrongDMM-2024-04-30 15 49 00](https://github.com/Aurorastation/Aurora.3/assets/112383634/4d76f3de-0ba1-4033-a837-a87651e482b2)

FEATURING ALL NEW:

- Drones and turrets! 
- Decent loot other than just Phoron.
- A cool new place to explore.
- Uses Danger:Reward ratio so you can't just stumble upon an automatic shotgun without a challenge!

Changelog will be added in a few minutes, thanks.

2024-04-30 15:49 UTC, CactusMouth commented
!review

2024-05-02 13:10 UTC, DreamySkrell commented on maps/away/away_site/zavod_shuttle_destroyed/zavod_shuttle_destroyed.dm
> +	spawn_cost = 2
should be = 1

2024-05-02 13:12 UTC, DreamySkrell commented
![image](https://github.com/Aurorastation/Aurora.3/assets/107256943/37a7ca9b-adc3-4954-967b-bea4f5e44b45)
wrong exterior space turf
is `/turf/space`
should be `/turf/template_noop`

2024-05-02 13:14 UTC, DreamySkrell commented
![image](https://github.com/Aurorastation/Aurora.3/assets/107256943/715c4a02-49ef-429e-aedf-3376d83dac2b)
atmos test fail here
this room has air and is exposed to space

2024-05-02 13:20 UTC, DreamySkrell requested changes
as above

2024-05-02 16:39 UTC, CactusMouth commented
I'll get it fixed in a moment

2024-05-02 16:52 UTC, CactusMouth commented
> as above

Fixed.

2024-05-06 08:57 UTC, DreamySkrell approved these changes

2024-05-12 18:59 UTC, NonQueueingMatt approved these changes

2024-05-12 20:07 UTC, merged