Improves Vaurca Magboot Augment
Aurorastation/Aurora.3 pull request #19137
Opened 2024-05-10 10:14 UTC by RustingWithYou

The Vaurca integrated mag-claw augment now mimics magboot functionality (not slipping, etc) rather than deploying an entire pair of magboots onto the user. Inspired by #18875

2024-05-10 10:14 UTC, RustingWithYou commented
!review

2024-05-12 18:53 UTC, NonQueueingMatt requested changes

2024-05-12 18:53 UTC, NonQueueingMatt commented on code/modules/organs/subtypes/vaurca.dm
> +		return
use_check_and_message

2024-06-08 16:51 UTC, NonQueueingMatt approved these changes

2024-06-09 16:46 UTC, Geevies approved these changes

2024-06-09 17:44 UTC, merged