Ports status display smooth scrolling, icon, and font from /tg/station
Aurorastation/Aurora.3 pull request #19143
Opened 2024-05-11 18:11 UTC by Generalcamo

This ports smooth scrolling, the new icon, and the new font for status displays from /tg/station.
### Asset Licenses
The following assets that **have not** been created by myself are included in this PR:

| Path | Original Author | License |
| --- | --- | --- |
| icons/obj/status_display.dmi | [DrDiasyl](https://github.com/DrDiasyl) /tg/station) | CC-BY-SA |

2024-05-11 18:11 UTC, Generalcamo commented
!review

2024-05-11 19:19 UTC, desvenlafaxine commented
I feel like the biohazard screen doesn't fit our setting, as it has a news anchor reporting on the situation.

Also, I don't know if the default screen should be that bright, isn't it meant to be when the screen is off? On a note, maybe it should also have a SCC logo.

2024-05-11 19:25 UTC, Generalcamo commented
Ignore icondiffbot, it's broken and is not showing the animations correctly. The news anchor is for the untouched "entertainer" state.

2024-05-12 18:52 UTC, NonQueueingMatt approved these changes

2024-05-16 14:39 UTC, FluffyGhoster commented
This is failing the SDMM linter

2024-05-19 15:54 UTC, Arrow768 requested changes

2024-05-19 15:54 UTC, Arrow768 commented on code/game/machinery/status_display.dm
> +					message2 = "Test"
Is that intentional or a leftover?

2024-05-21 04:13 UTC, Generalcamo commented on code/game/machinery/status_display.dm
> +					message2 = "Test"
```suggestion
```

2024-05-21 04:13 UTC, Generalcamo commented on code/game/machinery/status_display.dm
> +					message2 = "Test"
Leftover from /tg/

2024-05-23 17:43 UTC, Geevies approved these changes

2024-05-31 06:12 UTC, Arrow768 approved these changes

2024-06-01 03:28 UTC, merged