Zeng-Hu Hoverbeds
Aurorastation/Aurora.3 pull request #19152
Opened 2024-05-13 10:04 UTC by 1Sparky1

Adds Zeng-Hu Hoverbeds, which are now less of a novelty and more practically helpful due to the stairs changes. They can be sourced from R&D, and the First Responders start with two to share between themselves.

2024-05-13 10:12 UTC, 1Sparky1 commented
!review

2024-05-13 14:06 UTC, Greenjoe12345 commented on code/modules/research/designs/protolathe/medical_designs.dm
> +	desc = "A medical hoverbed, designed by Zeng-Hu Pharmaceuticals in conjunction with the Nralakk Federation."
Maybe this description should be added to the bed item itself too?

2024-05-14 14:49 UTC, FluffyGhoster commented
I think the FRs starting with them basically circumvents the whole added mechanic

If you want to make them buildable eg. by science that's fine, but them being present at roundstart is a no from me

2024-05-14 14:51 UTC, FluffyGhoster requested changes

2024-05-14 14:51 UTC, FluffyGhoster commented on code/game/objects/structures/stool_bed_chair_nest/bed.dm
> +	var/hover_color = LIGHT_COLOR_CYAN
As above, and also this variable needs a DMDoc

2024-05-14 15:49 UTC, 1Sparky1 commented
I don't think 2 beds circumvents the whole mechanic - Most FRs carry at least 2 to my knowledge, and these would be split between them. And anyone doing medical retrieval to fill in for a missing FR would have to deal with the stairs still.

I also don't think making them exclusively research is beneficial to anyone - Just printing things isn't in itself a particularly satisfying experience, and it would mean a science- and/or mining-less medical would suffer heavily (i.e. low pop would almost never get to use them)

2024-05-14 16:01 UTC, FluffyGhoster commented
> I don't think 2 beds circumvents the whole mechanic - Most FRs carry at least 2 to my knowledge, and these would be split between them. And anyone doing medical retrieval to fill in for a missing FR would have to deal with the stairs still.

You can only transport a single patient at a time, so yes in essence it bypasses the mechanic, when you reach the GTR you unload the patient on another bed and go back out, thus bypassing the need to account for the stairs/elevators

> I also don't think making them exclusively research is beneficial to anyone - Just printing things isn't in itself a particularly satisfying experience, and it would mean a science- and/or mining-less medical would suffer heavily (i.e. low pop would almost never get to use them)

We have various things exclusively research [sic], the IMS for surgeons for example; R&D is supposed to make and give improvements and QoL things, if people have fancy things by default, that reduces the utility of having R&D, thus lowering the amount of people that want to play it, and the loop continues

2024-05-14 16:04 UTC, 1Sparky1 commented
While I'm still of two minds, I'd rather see the item in game soon and have the debate over starting beds or not at another time, so I've removed the initial ones.

2024-05-14 16:05 UTC, FluffyGhoster approved these changes

2024-05-15 08:41 UTC, DreamySkrell approved these changes

2024-05-19 15:51 UTC, Arrow768 requested changes
Given that they (obviously) use power, they should have inbuilt powercells and all the mechanics that come with it:
- Adding/Removing the powercell
- EMP-able -> Discharges the powercell
- Hover function shutting down (ideally abruptly) if power runs out
- A warning before the power runs out

2024-06-05 00:16 UTC, FluffyGhoster commented on code/game/objects/structures/stool_bed_chair_nest/bed.dm
> +/obj/structure/bed/roller/hover/Destroy()
Need to STOP_PROCESSING(SSprocessing, src) here, probably

2024-06-05 00:16 UTC, FluffyGhoster commented on code/game/objects/structures/stool_bed_chair_nest/bed.dm
> +/obj/structure/bed/roller/hover/process()
You need to respect the `ticks_per_second` parameter that it gives you, and use it for anything that works on time

2024-06-05 00:16 UTC, FluffyGhoster commented on code/game/objects/structures/stool_bed_chair_nest/bed.dm
> +		cell.use(power_draw)
Like here, you need to multiply the power draw by the ticks_per_second

2024-06-05 00:16 UTC, FluffyGhoster commented on code/game/objects/structures/stool_bed_chair_nest/bed.dm
> +		visible_message(SPAN_WARNING("\The [src] falls the the floor as its hover thrusters cut out."))
Wouldn't this keep spamming out that it's out of charge? You are not stopping the processing below?

2024-06-05 00:16 UTC, FluffyGhoster commented on code/game/objects/structures/stool_bed_chair_nest/bed.dm
> +		update_icon()
Likewise, wouldn't this keep refreshing the icon?

2024-06-19 16:57 UTC, FluffyGhoster approved these changes
Looks good enough

2024-11-15 19:42 UTC, closed without merging