Alien Sleep Updates - Allows upright standing, and indefinite sleep.
Aurorastation/Aurora.3 pull request #19178
Opened 2024-05-16 08:45 UTC by 1Sparky1

This allows certain alien species (Currently Vaurcae, IPCs and Dionae) to sleep while standing, and gives them a verb to let them choose to sleep indefinitely. 

It also adds custom messages for enter sleep and examining, as well as changing the snoring emote for the above aliens too.

2024-05-16 08:45 UTC, 1Sparky1 commented
!review

2024-05-17 10:51 UTC, Llywelwyn requested changes

2024-05-17 10:51 UTC, Llywelwyn commented on code/modules/mob/living/carbon/human/species/station/vaurca/vaurca.dm
> +	return SPAN_NOTICE("[M.get_pronoun("He")] has locked [M.get_pronoun("his")] carrapace in place, and is standing completely still.\n")
```suggestion
	M.visible_message(SPAN_NOTICE("\The [M] locks [M.get_pronoun("his")] carapace in place, becoming completely still."))
	to_chat(M, SPAN_NOTICE("You lock your carapace into place, becoming completely still."))

/datum/species/bug/sleep_examine_msg(var/mob/M)
	return SPAN_NOTICE("[M.get_pronoun("He")] has locked [M.get_pronoun("his")] carapace in place, and is standing completely still.\n")
```
carrapace -> carapace

2024-05-19 16:39 UTC, Arrow768 approved these changes

2024-05-19 18:46 UTC, Geevies approved these changes

2024-05-22 09:41 UTC, merged