Ported radiation collector arrays from baystation12
Aurorastation/Aurora.3 pull request #19174
Opened 2024-05-15 22:50 UTC by Generalcamo

These are intended to be available in the cargo list, so marking as draft until that can be confirmed.

This ports radiation collectors from baystation12. These use the ssradiation system that we have, to generate power from phoron and radiation. This is contrasted with the prior iteration of these units, which solely generated power from the singularity. These could be used to generate power around a supermatter reactor, or a fusion reactor, or any number of things that the playerbase can think of. The only thing is that these cost precious phoron; you do not want to use these as the sole source of power aboard anything.

### Asset Licenses
The following assets that **have not** been created by myself are included in this PR:

| Path | Original Author | License |
| --- | --- | --- |
| icons/obj/machinery/rad_collector.dmi | Chinsky (Baystation12) | CC-BY-SA |

2024-06-16 15:36 UTC, Arrow768 commented
These are intended to be available in the cargo list, so marking as draft until that can be confirmed.

Items in the cargo list that arnt ingame are automatically disabled.

2024-06-16 15:37 UTC, Arrow768 approved these changes

2024-06-16 15:39 UTC, Generalcamo commented
!review

2024-06-19 16:54 UTC, FluffyGhoster requested changes

2024-06-19 16:54 UTC, FluffyGhoster commented on code/modules/power/collector.dm
> +	var/alert_delay = 10 SECONDS
DMDoc those vars

2024-06-19 16:54 UTC, FluffyGhoster commented on code/modules/power/collector.dm
> +/obj/machinery/power/rad_collector/process()
Make this proc time constant, you receive a seconds_per_tick parameter and everything relevant have to be multiplied by it, as outlined in the proc header

2024-06-19 16:54 UTC, FluffyGhoster commented on code/modules/power/collector.dm
> +/obj/machinery/power/rad_collector/attackby(obj/item/W, mob/living/user)
Respect the function header, and no single letter variables

2024-06-19 16:54 UTC, FluffyGhoster commented on code/modules/power/collector.dm
> +/obj/machinery/power/rad_collector/proc/receive_pulse(pulse_strength)
DMDoc

2025-01-29 06:36 UTC, FluffyGhoster approved these changes
Looks good enough to me

2025-03-17 22:15 UTC, merged