Ported Supermatter improvements from Baystation
Aurorastation/Aurora.3 pull request #19175
Opened 2024-05-15 23:27 UTC by Generalcamo

`  - rscadd: "The supermatter reactor now produces radiation via SSRadiation. Better wear your suit!"
  - rscadd: "The supermatter reactor now has a ray effect and color shifts if it is damaged."`

2024-05-15 23:27 UTC, Generalcamo commented
!review

2024-05-16 07:35 UTC, Arrow768 approved these changes

2024-05-16 14:35 UTC, FluffyGhoster requested changes

2024-05-16 14:35 UTC, FluffyGhoster commented on code/__HELPERS/matrices.dm
> +** Do make sure your lists actually have this many elements **/
Restructure this DMDoc to match how it's expected to be, it looks mangled

2024-05-18 03:39 UTC, FluffyGhoster approved these changes
Looks good enough, i'm not sold on that matrix multiplication proc when there's https://secure.byond.com/docs/ref/index.html#/matrix/proc/Multiply that is done in engine, but i'm not math-y enough to understand if it archieves anything meaningfully different so ¯\\\_(ツ)_/¯

2024-05-22 09:31 UTC, merged