Autolathe Stuff
Aurorastation/Aurora.3 pull request #19194
Opened 2024-05-19 12:54 UTC by Geevies

* Certain autolathe items can now be printed at Code Red without needing to be hacked. (though hacking allows you to access them without the level)
* Certain autolathe items have had their hacking restrictions removed, such as the industrial welder. They are now printable by default.
* Reorganized the autolathe, drastically reduced the size of the General tab, and introduced new tabs, such as Dinnerware and Armaments.
* Shotgun shells now print in piles, instead of one shell at a time. The resource cost has been increased to compensate.

https://github.com/Aurorastation/Aurora.3/assets/22774890/b17b567b-e1a8-429c-a823-14ff4f47fb00

2024-05-19 18:36 UTC, Geevies commented
!review

2024-05-23 13:43 UTC, FluffyGhoster commented
The CI tests didn't run on this PR for whatever reason, give them a kick with a commit

2024-05-31 19:26 UTC, Arrow768 requested changes

2024-05-31 19:26 UTC, Arrow768 commented on code/game/machinery/autolathe/autolathe.dm
> +
Fluffy is correct, the topic action also needs to be checked.

2024-06-09 16:20 UTC, Geevies commented
!review

2024-06-10 12:15 UTC, NonQueueingMatt requested changes

2024-06-10 12:15 UTC, NonQueueingMatt commented on code/game/machinery/autolathe/autolathe.dm
> +				is_enabled = FALSE
this is copypasted code now, just make it into a proc

2024-06-16 14:35 UTC, Geevies commented
!review

2024-06-20 10:23 UTC, NonQueueingMatt approved these changes

2024-06-25 09:27 UTC, Arrow768 commented on code/game/machinery/autolathe/autolathe.dm
> +			CRASH("Someone tried to print an un-enabled recipe! [R], param is [params["recipe"]].")
You should print who that someone is (ckey)

2024-06-25 09:27 UTC, Arrow768 commented on code/game/machinery/autolathe/autolathe.dm
> +		recipe_data["hidden"] = R.hack_only
You should update the name of that car so ui and dm code are consistent

2024-07-06 13:50 UTC, Geevies commented
!review

2024-08-23 17:29 UTC, FluffyGhoster requested changes

2024-08-23 17:29 UTC, FluffyGhoster commented on code/game/machinery/autolathe/autolathe.dm
> +		if(R.IsAbstract())
Use the world proc

`is_abstract(R)`

2024-08-23 17:29 UTC, FluffyGhoster commented on code/game/machinery/autolathe/designs/ammunition.dm
> +	abstract_type = /singleton/autolathe_recipe/ammunition
`ABSTRACT_TYPE(/singleton/autolathe_recipe/ammunition)`

2024-08-23 17:29 UTC, FluffyGhoster commented on code/game/machinery/autolathe/designs/components.dm
> +	abstract_type = /singleton/autolathe_recipe/components
`ABSTRACT_TYPE(/singleton/autolathe_recipe/components)`

2024-08-23 17:29 UTC, FluffyGhoster commented on code/game/machinery/autolathe/designs/dinnerware.dm
> +	abstract_type = /singleton/autolathe_recipe/dinnerware
`ABSTRACT_TYPE(/singleton/autolathe_recipe/dinnerware)`

2024-08-23 17:29 UTC, FluffyGhoster commented on code/game/machinery/autolathe/designs/engineering.dm
> +	abstract_type = /singleton/autolathe_recipe/engineering
etc

2024-08-23 17:29 UTC, FluffyGhoster commented on code/game/machinery/autolathe/designs/general.dm
> +	abstract_type = /singleton/autolathe_recipe/general
etc

2024-08-23 17:29 UTC, FluffyGhoster commented on code/game/machinery/autolathe/designs/materials.dm
> +	abstract_type = /singleton/autolathe_recipe/materials
etc

2024-08-23 17:29 UTC, FluffyGhoster commented on code/game/machinery/autolathe/designs/medical.dm
> +	abstract_type = /singleton/autolathe_recipe/medical
etc

2024-08-23 17:29 UTC, FluffyGhoster commented on code/game/machinery/autolathe/designs/tools.dm
> +	abstract_type = /singleton/autolathe_recipe/tools
etc

2024-08-25 13:03 UTC, Geevies commented
!review

2024-08-25 19:52 UTC, DreamySkrell approved these changes

2024-08-25 19:56 UTC, FluffyGhoster approved these changes

2024-08-25 20:45 UTC, merged