Fix flat-file BYOND-Tracy autostart not working
Aurorastation/Aurora.3 pull request #19220
Opened 2024-05-22 01:25 UTC by out-of-phaze

Fixes flat-file BYOND-Tracy autostart not working. It passed `"tracy-disk"` instead of `DISK_VERSION` to `prof_init()`. Also adds a `CRASH()` to make these incorrect cases more obvious in the future.

### Asset Licenses
The following assets that **have not** been created by myself are included in this PR:

**N/A**

2024-05-22 08:26 UTC, DreamySkrell approved these changes

2024-05-22 09:13 UTC, Arrow768 approved these changes

2024-05-23 05:22 UTC, FluffyGhoster requested changes
This needs the changelog file added, apart from that it's good to go

2024-05-23 14:10 UTC, out-of-phaze commented
> This needs the changelog file added, apart from that it's good to go

are those really needed for non-user-facing changes?

2024-05-23 14:30 UTC, FluffyGhoster approved these changes
Apparently they aren't, my bad

2024-05-23 14:31 UTC, FluffyGhoster commented
!bugfix

2024-05-23 19:43 UTC, merged