Shuttle manifest update
Aurorastation/Aurora.3 pull request #19345
Opened 2024-06-04 16:20 UTC by 1Sparky1

Adds some new fields to the shuttle manifest:
- Destination (Per shuttle)
- Heading (Per shuttle)
- Mission (Per shuttle)
- Departure Time (Per Shuttle)
- Return Time (Per Shuttle)
- Expedition/Mission Leader (One per shuttle)
- Shuttle Pilot (One per shuttle)

Also adds the shuttle manifest to Bridge Crew PDAs by default.

2024-06-04 16:31 UTC, 1Sparky1 commented
!review

2024-06-08 16:43 UTC, NonQueueingMatt requested changes

2024-06-08 16:43 UTC, NonQueueingMatt commented on code/__DEFINES/shuttle.dm
> +#define SHUTTLE_MISSIONS list("Exploration", "Research", "Prospecting", "Transport", "Combat", "Rescue", "Training")
these should be variables on the map, not defines

2024-06-08 16:43 UTC, NonQueueingMatt commented on code/controllers/subsystems/records.dm
> +	for(var/shuttle in HORIZON_SHUTTLES)
use a map variable

2024-06-09 22:48 UTC, Arrow768 approved these changes

2024-06-26 10:16 UTC, NonQueueingMatt approved these changes

2024-06-26 11:10 UTC, merged