Tramp Freighter remap
Aurorastation/Aurora.3 pull request #19353
Opened 2024-06-05 01:24 UTC by hazelrat

This is a full remap for the Tramp Freighter offship that intends to bring the ship into closer alignment with newer mapping standards, while playing the same role as the original map. It'll be WIP until the last few kinks are ironed out.

- I want to merge this because, although the old Catspaw-class freighter is nostalgic, I don't think the layout is really tenable now without changing it so much that it might as well have been a full remap anyways. The tramp freighter plays a very important role as the one universal offship - every whitelist, every sector, any reason you can RP up for why you're doing anything you're doing. I intend to find a new name and identity for this redesigned ship to distance itself from the Catspaw, since it's so obviously different. 
- The layout is very different, primarily to accommodate full docking arms. The idea is that the freighter should always be able to move cargo to and from other parties without having to traipse through space. With this design, even if the other party doesn't have docking ports, they can still just go over to the tramp freighter to conduct their business in person. You can even just cater to people if you like, it has a hydroponics bay and bartending equipment.
- All references to the ship that show up on IC mediums have been renamed to 'Independent Freighter'.
- The cargo bay of the ship has been expanded. Four crates in the middle of the room contain particularly valuable randomised items. The shuttle is also designed to accommodate loading racks with merchandise like you would on the merchant's shuttle.
- The guns in the armoury are now static, but you also get randomised weapons in one of the crates. The spawner used for the randomised weapons tends nicely towards weird and exotic types, which I hope is fun roleplay.
- The ship generally is *full* of contraband, even outside of the smuggling compartments. Don't get pulled over by a patrol ship, and if you are, take a lot of care to clean up shop. 
- In terms of ship combat balance, this ship is deliberately weak. It has relatively little fuel and very punishing entry points - you can hit the bridge from any direction but the aft, and doing so also cuts the gunnery. In my view, the tramp should be the 'small fry' in ship combat, any pirate offship should have a relatively easy time with it.
- In terms of contraband, they have a lot of RNG spawners, in addition to the crate full of passports and another crate full of everything from restricted prescription medicines to stronger narcotics. I want the contraband side of the ship to be able to cater to more characters, so the diversity in the severity of contraband should help.

BUGS:

- Currently, the rotary gun doesn't seem to fire any projectiles. It can be 'fired' with the targeting console and the animation does play, but no projectiles are actually fired out of the gun, and similarly none enter the overmap. I've tested this with a grauwolf too and got the same result, so I assume it's a problem somewhere in the .dm. A second pair of eyes on why that's happening could help.

2024-06-05 01:25 UTC, hazelrat commented
!wip

2024-06-09 04:10 UTC, hazelrat commented
!review

2024-06-12 08:30 UTC, DreamySkrell commented
![image](https://github.com/Aurorastation/Aurora.3/assets/107256943/851a021b-0181-4548-861e-bec1eb189af3)
the shuttle overmap object should be on the holopad, just to be consistent with most other maps, and possibly more easily noticed when mapping

2024-06-12 08:34 UTC, DreamySkrell commented
![image](https://github.com/Aurorastation/Aurora.3/assets/107256943/37ea11af-06d2-44cc-81d8-356c77b6d074)
this is a merchant shuttle with very little storage space for crates or the like

![image](https://github.com/Aurorastation/Aurora.3/assets/107256943/2616242d-f7e4-426a-bb03-ae1fbd395018)
I'd widen it a bit like this, provide some free tiles for storing anything in the middle, and behind the passenger seats

2024-06-12 08:35 UTC, DreamySkrell commented
![image](https://github.com/Aurorastation/Aurora.3/assets/107256943/6028e5e2-8704-4db9-a023-896b6a678c8c)![image](https://github.com/Aurorastation/Aurora.3/assets/107256943/3f38e221-ca53-449f-8bb8-11c163bcd7ef)
do not change the layer var of things

2024-06-12 08:38 UTC, DreamySkrell commented
![image](https://github.com/Aurorastation/Aurora.3/assets/107256943/a7fb3897-3a54-49c8-8f19-97babfa1103e)
new docking/shuttle airlocks should be defined in code, not in the map
see scc scout or sol yacht for an example
external access airlocks are fine to be defined in the map

2024-06-12 08:41 UTC, DreamySkrell commented
![image](https://github.com/Aurorastation/Aurora.3/assets/107256943/89059b28-b789-4ac1-96c0-951649a59364)
do not use fake objects
add a indoor lattice like that into code, like `/obj/structure/lattice/catwalk/indoor/lattice`
but also I am really not a fan of a decorative lattice, that look exactly the same as actual functional lattices

2024-06-12 08:47 UTC, DreamySkrell commented
![image](https://github.com/Aurorastation/Aurora.3/assets/107256943/a4cd77c3-dfca-43e7-ad02-9b0d915a3665)
these docks are not complaint with the dock/shuttle standards, cannot fit max size shuttles
this is a merchant ship so it should be fully compliant in this aspect

2024-06-12 08:51 UTC, DreamySkrell commented
![image](https://github.com/Aurorastation/Aurora.3/assets/107256943/631cd298-d4c4-4ff8-a822-460e397efd71)
this is the antag gun spawner, that can spawn crazy powerful stuff including like pulse rifles
replace with civ gun spawners or something else, in smaller number too, cause they already do have a armory on the ship

2024-06-12 08:52 UTC, DreamySkrell commented
![image](https://github.com/Aurorastation/Aurora.3/assets/107256943/a81ca5b5-28e0-47ad-a440-8bfb70d3ec9e)
replace with `/obj/machinery/iff_beacon` to allow them to change both designation and class (ICV/etc)

2024-06-12 08:54 UTC, DreamySkrell commented
![image](https://github.com/Aurorastation/Aurora.3/assets/107256943/b4172067-5524-4eca-b86d-9e58e5a6f30c)
do not have to change it here, but in future maps use large tank markers, example on scc scout or sol yacht

2024-06-12 08:55 UTC, DreamySkrell commented
![image](https://github.com/Aurorastation/Aurora.3/assets/107256943/6cd13b1d-246c-4146-80a5-43b16dd3aa8e)
this is radioactive goo that irradiates whoever tries to clean it
replace it with vomit or something

2024-06-12 08:55 UTC, DreamySkrell commented
![image](https://github.com/Aurorastation/Aurora.3/assets/107256943/858d6c4f-4c84-41df-bb1e-5b15b0341d88)
eepy

2024-06-12 08:56 UTC, DreamySkrell commented
![image](https://github.com/Aurorastation/Aurora.3/assets/107256943/17bf321e-c1e1-4b59-af89-457061f65787)
glass door to the armory?

2024-06-12 08:59 UTC, DreamySkrell commented on maps/away/ships/tramp_freighter/tramp_freighter.dm
>  /obj/effect/shuttle_landmark/tramp_freighter/nav1
Split all the landmarks into their own file like `tramp_freighter_landmarks.dm`

2024-06-12 09:00 UTC, DreamySkrell commented
![image](https://github.com/Aurorastation/Aurora.3/assets/107256943/31d5fc0f-55da-4a8c-9014-1cd263cde4a6)
mining mecha here? should it not be a loader to load the ship gun?

2024-06-12 09:01 UTC, DreamySkrell requested changes
.

2024-06-17 08:30 UTC, hazelrat commented
Implemented all changes, plus an addition of disposals and some smaller tweaks.

2024-06-17 21:15 UTC, DreamySkrell commented
![image](https://github.com/Aurorastation/Aurora.3/assets/107256943/88e4104e-9c49-4df4-8d39-32ef7e0c678e)
still see a lot of objects with changed layers on the map

2024-06-18 08:23 UTC, DreamySkrell approved these changes

2024-06-21 12:10 UTC, NonQueueingMatt approved these changes

2024-06-21 12:22 UTC, merged