Expedition Fluff Expansion - Hull Surveyor & New Survey Probes
Aurorastation/Aurora.3 pull request #19364
Opened 2024-06-05 17:13 UTC by 1Sparky1

Adds a hull surveyor tool, which generates a report of wrecked away sites regarding their age and the cause of wreckage.

Splits the current survey probes into two types: Atmosphere and Ground, as well as adding a Geomagnetic variant. Replaces some of the currently mapped in atmosphere probes with the two other types.

2024-06-05 17:14 UTC, 1Sparky1 commented
!review

2024-06-06 15:43 UTC, DreamySkrell commented on code/modules/overmap/sectors.dm
> +		wreck_details[WRECK_DAMAGE] = "Reconstruction indicates the damage was most likely cause by [cause]."
Honestly really not a fan of a hull probe like that. There's no way to figure out any of that information with a probe just sampling some metal.

This information should be up to actual players and their chars to figure out, by exploring the away site or ship.

Like how would the probe even know if it's sampling a wreck or not? At what point does a ship or station become a wreck? It sounds really arbitrary.

2024-06-06 15:46 UTC, DreamySkrell requested changes
as above

2024-06-07 00:15 UTC, Triogenix commented
Hi, having discussed this with my deputy, the LTA is also in agreement with what dreamy said above, and would like to see the hull probe removed from this PR before it is merged.

2024-06-19 07:57 UTC, DreamySkrell approved these changes

2024-06-20 10:23 UTC, NonQueueingMatt requested changes

2024-06-20 10:23 UTC, NonQueueingMatt commented on code/game/objects/structures/survey_probe.dm
> +	if(air.total_moles>0)
this runtimes if there's no air

2024-06-26 10:26 UTC, NonQueueingMatt approved these changes

2024-06-26 11:24 UTC, merged