Tyrant tweaks
Aurorastation/Aurora.3 pull request #19371
Opened 2024-06-06 04:07 UTC by FluffyGhoster

Added some notifications of proximity to the plains tyrant.
Reduced health and auto-brute-healing of the plains tyrant.
Fixed traps pathing so that mobs should now pass in them.
Optimized SA_attackable proc.
Mechs are no longer opaque, this fixes the simplemobs not attacking them (because the line of sight check fails as the turf they stand on is opaque if they are opaque too) as well as avoid lighting recomputing on every step.

2024-06-06 04:17 UTC, FluffyGhoster commented
!review

2024-06-07 09:54 UTC, NonQueueingMatt requested changes

2024-06-07 09:54 UTC, NonQueueingMatt commented on code/modules/mob/living/simple_animal/hostile/moghes.dm
> +				message = SPAN_HIGHDANGER(SPAN_BOLD("YOU HEAR LOUD STOMPING NEARBY, SOMETHING TERRIFYINGLY LARGE IS NEARBY!"))
```suggestion
				message = SPAN_HIGHDANGER(SPAN_BOLD("You hear loud stomping nearby!"))
```
let players draw their own conclusions generally, it's more immersive

2024-06-08 16:33 UTC, NonQueueingMatt approved these changes

2024-06-09 16:58 UTC, Geevies approved these changes

2024-06-09 17:34 UTC, merged