Better staff who verb window
Aurorastation/Aurora.3 pull request #19379
Opened 2024-06-06 18:06 UTC by DreamySkrell

![image](https://github.com/Aurorastation/Aurora.3/assets/107256943/d0297548-801c-48d4-8b58-d37bfd7fe142)
![image](https://github.com/Aurorastation/Aurora.3/assets/107256943/e0d24b7a-1b0a-45cf-9114-5eb79fb8d6d1)

2024-06-06 18:06 UTC, DreamySkrell commented
!review

2024-06-06 18:59 UTC, FluffyGhoster requested changes

2024-06-06 18:59 UTC, FluffyGhoster commented on code/game/verbs/who.dm
> +			msg += "<td><A HREF='?_src_=holder;adminmoreinfo=\ref[client.mob]'>?</A></td>"
REF() over \ref

2024-06-06 18:59 UTC, FluffyGhoster commented on code/game/verbs/who.dm
> +				msg += "<td><span class='warning'>Antagonist</span></b></td>"
SPAN_WARNING

2024-06-08 12:26 UTC, DreamySkrell commented on code/game/verbs/who.dm
> +				msg += "<td><span class='warning'>Antagonist</span></b></td>"
fixed

2024-06-08 12:30 UTC, DreamySkrell commented on code/game/verbs/who.dm
> +			msg += "<td><A HREF='?_src_=holder;adminmoreinfo=\ref[client.mob]'>?</A></td>"
fixed

2024-06-08 16:29 UTC, NonQueueingMatt approved these changes

2024-06-10 12:11 UTC, merged