White blood
Aurorastation/Aurora.3 pull request #19381
Opened 2024-06-06 19:55 UTC by DreamySkrell

changes:
  - rscadd: "Shell IPCs now have white blood."
  - rscadd: "Adds synthetic blood substitute character trait."

```
desc = "\
		Normal blood produced by your body is not enough for you, and you require a synthetic blood substitute, \
		that can carry more oxygen, cool you better, or has whatever other improved characteristics.\
	"
```

2024-06-06 20:55 UTC, DreamySkrell commented
!review

2024-06-06 22:17 UTC, alsoandanswer approved these changes
You should probably put in the in-game description that it isn't any mechanically different from regular blood

2024-06-06 22:41 UTC, NobleRow commented
I'd like a Lore discussion tag on this until the team has seen it.

2024-06-07 00:38 UTC, NobleRow commented
The IPC team would like the white blood be removed from Shells and kept with the black oil. We're still putting together a medical rework for IPCs and this change might be in conflict with our vision, in addition there is not currently lore to back the change for white blood over standard coolant. For the future please do ask the lore team so we don't dash hopes after it's too late. Thank you for your interest in contributing to our species, however.

2024-06-07 01:34 UTC, Triogenix commented
So, I like this idea for organics, as I think it is interesting, and have cooked up a bit of lore about it, that I will contact you about. That said, I support what Noble said above, and would like to see this removed from shells before being merged.

2024-06-07 08:47 UTC, DreamySkrell commented
White blood changes reverted from shell IPCs, they bleed black oil as before.

2024-06-08 16:28 UTC, NonQueueingMatt requested changes
I don't think artificial blood should mechanically behave the same as normal blood - meaning that someone with artificial blood should need artificial blood added to their body, not normal blood. Otherwise you'd get weird inconsistencies like someone having 50% of their synthetic blood evaporated, have it replaced entirely with normal blood, and they'd still bleed only white.

2024-06-11 17:26 UTC, DreamySkrell commented
> I don't think artificial blood should mechanically behave the same as normal blood - meaning that someone with artificial blood should need artificial blood added to their body, not normal blood. Otherwise you'd get weird inconsistencies like someone having 50% of their synthetic blood evaporated, have it replaced entirely with normal blood, and they'd still bleed only white.

Addressed. Now synth blood is its own blood type, incompatible with normal red blood.

2024-06-11 17:52 UTC, DreamySkrell commented
Ready for review again.

2024-06-11 19:21 UTC, Geevies approved these changes

2024-06-14 01:06 UTC, FluffyGhoster commented on code/__DEFINES/color.dm
> +#define COLOR_SYNTH_BLOOD      "#D9F9FF" // for organics with synthetic blood substitute
DMDoc, not comments

2024-06-20 10:18 UTC, NonQueueingMatt approved these changes

2024-06-20 10:38 UTC, merged