Detective trenchcoat fix
Aurorastation/Aurora.3 pull request #19398
Opened 2024-06-09 13:19 UTC by BoomerThor

Fixes #18627

2024-06-09 14:01 UTC, BoomerThor commented
!bugfix

2024-06-09 14:01 UTC, BoomerThor commented
!review

2024-06-09 16:59 UTC, Geevies approved these changes

2024-06-09 21:03 UTC, FluffyGhoster requested changes

2024-06-09 21:03 UTC, FluffyGhoster commented on code/modules/clothing/suits/jobs.dm
> +	icon = 'icons/obj/item/clothing/suit/storage/toggle/trenchcoat.dmi'
Pointless assignment, the parent should have it already

2024-06-10 01:41 UTC, FluffyGhoster approved these changes

2024-06-10 12:07 UTC, merged