Hivenet aug tweaks
Aurorastation/Aurora.3 pull request #19404
Opened 2024-06-09 22:24 UTC by DreamySkrell

changes:
  - rscadd: "Hivenet aug preset messages tweaks and additions."
  - rscadd: "Hivenet aug loadout item cost lowered to 3, to be more in line with the other language augment."

2024-06-09 22:37 UTC, DreamySkrell commented
!review

2024-06-10 05:06 UTC, Arrow768 requested changes

2024-06-10 11:20 UTC, DreamySkrell commented on code/modules/client/preference_setup/loadout/items/augments.dm
> +	cost = 3
this change was removed/reverted

2024-06-10 11:34 UTC, Arrow768 approved these changes

2024-06-10 16:43 UTC, NonQueueingMatt approved these changes

2024-06-11 15:20 UTC, FluffyGhoster approved these changes

2024-06-13 00:19 UTC, merged