Ouerea Away Site Tweaks
Aurorastation/Aurora.3 pull request #19417
Opened 2024-06-10 23:04 UTC by lavillastrangiato

* Adds decorations and some extra gear to Ouerea away sites like the Skrase and the Sol Base.
* Also adds some extra belts and a better kitchen for the aquaculture farm.

2024-07-01 10:06 UTC, lavillastrangiato commented
!review

2024-07-08 05:55 UTC, courierbravo requested changes
Looks very good, only needs a couple tweaks.

There's a missing tile in the research lab.
![StrongDMM_g8YbFKcNEa](https://github.com/Aurorastation/Aurora.3/assets/73250577/0c49edcb-aff5-4d13-8fb8-827ae5848663)

There's some stray tiles on the mining building here
![StrongDMM_VcivI8s6Os](https://github.com/Aurorastation/Aurora.3/assets/73250577/92efec5a-bfcd-47c3-8d7e-f2a79252a69e)

And it looks like there's a stray stool/painted area on the ground in the dorm/dining area.
![StrongDMM_4PHuOay3ZC](https://github.com/Aurorastation/Aurora.3/assets/73250577/a0c3a1da-e4a9-412d-89cd-e96988d78f40)

Otherwise these look great.

2024-07-16 03:29 UTC, courierbravo approved these changes
Looks good to me.

2024-07-16 08:48 UTC, DreamySkrell approved these changes

2024-07-17 21:17 UTC, NonQueueingMatt approved these changes

2024-07-18 21:40 UTC, merged