Spiderbots can pilot Exosuits again
Aurorastation/Aurora.3 pull request #19415
Opened 2024-06-10 19:05 UTC by Ben10083

Spiderbots were blocked from piloting exosuits inadvertently. This restores that functionality

2024-06-10 19:06 UTC, Ben10083 commented
!review

2024-06-10 19:06 UTC, Ben10083 commented
!bugfix

2024-06-10 21:08 UTC, FluffyGhoster requested changes

2024-06-11 14:17 UTC, FluffyGhoster commented on code/modules/heavy_vehicle/mech_interaction.dm
> +			if((usr.mob_size >= MOB_SMALL && usr.mob_size <= 14) || HAS_TRAIT(usr, TRAIT_MECH_PILOT))
No, if you use the trait, use only the trait; assign to relevant mobs the mech_pilot trait and remove the mob size check

2024-09-30 18:44 UTC, closed without merging