Adds a colorable hood to the loadout.
Aurorastation/Aurora.3 pull request #19424
Opened 2024-06-11 18:10 UTC by ASmallCuteCat

Adds a colorable hood to the loadout. Tested with human, unathi, and tajara.

Sprites by ASmallCuteCat (aka Revenant1367)

2024-06-11 18:11 UTC, ASmallCuteCat commented
No idea how any of this works, flying by the seat of my pants here

!review

2024-06-12 12:00 UTC, Llywelwyn requested changes
not a dev, but
you'll need to get rid of the comments, and probably move the loadout datum up so it follows on after the other head items, but otherwise the code looks fine

2024-06-12 12:06 UTC, ASmallCuteCat commented on code/modules/client/preference_setup/loadout/items/head.dm
> +	flags = GEAR_HAS_NAME_SELECTION | GEAR_HAS_DESC_SELECTION | GEAR_HAS_COLOR_SELECTION
Code block moved, comments erased. Now to see if I can figure out how to update the github... :P

2024-06-16 12:03 UTC, ASmallCuteCat commented
!wip

HELP THE THING KEEPS TRYING TO DELETE AURORASTATION.DME

2024-06-16 12:05 UTC, closed without merging

2024-06-16 12:05 UTC, ASmallCuteCat commented
ok i'm killing this and trying again