Automated Waystation
Aurorastation/Aurora.3 pull request #19435
Opened 2024-06-12 12:23 UTC by Stev-the-third

Adds an Automated Waystation, an ASSN Department of Colonization sensor relay repurposed by the Coalition government to serve as a restpoint and refuelling station for weary travellers. 

![image](https://github.com/Aurorastation/Aurora.3/assets/61610777/0113c4d0-1cf9-4ae6-b795-ce8241bc4874)
I really should've finished this six months ago when I started.

2024-06-12 12:25 UTC, Stev-the-third commented
!review

2024-06-12 22:45 UTC, Stev-the-third commented
!wip

2024-06-12 22:45 UTC, Stev-the-third commented
I forgot to add a changelog, I'll add one soon

2024-06-13 09:45 UTC, Stev-the-third commented
!wip

2024-06-14 06:04 UTC, Stev-the-third commented
!review

2024-06-20 18:10 UTC, DreamySkrell commented on maps/away/away_site/automated_waystation/automated_waystation.dm
> +/area/automated_waystation/canteen
needs newlines between area definitions

2024-06-20 18:11 UTC, DreamySkrell commented
![image](https://github.com/Aurorastation/Aurora.3/assets/107256943/120a1af0-3214-4230-9399-8cc0f75f8aa8)
.dm file needs to be added to aurorastation.dme

2024-06-20 18:13 UTC, DreamySkrell commented
![image](https://github.com/Aurorastation/Aurora.3/assets/107256943/61ab78c0-b20e-434b-bd8d-cd6dc5163020)

scrubber pipe line should go to an empty canister, otherwise it's just going to go full quickly, and can't be 

supply pipe line here can't be refilled when emptied, needs either to just be an air canister, or keep the tank and add a canister port

2024-06-20 18:18 UTC, DreamySkrell commented
![image](https://github.com/Aurorastation/Aurora.3/assets/107256943/2a8e4968-e2c3-40f1-9a21-dc1e2627ea1f)
needs free space navpoints that are not attached to any catwalks
rename the current navpoints to "catwalk dock" or something to differentiate them from free space navpoints

2024-06-20 18:19 UTC, DreamySkrell commented
![image](https://github.com/Aurorastation/Aurora.3/assets/107256943/888ec776-6835-46bd-87ff-3858ad23f5ec)
dark blue overmap icon is going to be hard to see on the overmap
make it like light blue or something

2024-06-20 18:21 UTC, DreamySkrell commented
![image](https://github.com/Aurorastation/Aurora.3/assets/107256943/4f13caf1-1e31-44be-8e9e-17b7ddb872df)
apc not connected to wires

2024-06-20 18:22 UTC, DreamySkrell commented
![image](https://github.com/Aurorastation/Aurora.3/assets/107256943/bd785ead-8a3d-424a-87ac-d34834a6c821)
use `/obj/machinery/shipsensors/strong/relay`

2024-06-20 18:25 UTC, DreamySkrell commented on maps/away/away_site/automated_waystation/automated_waystation.dm
> +	sectors = list(ALL_COALITION_SECTORS)
this is effectively a different variant of the current sensor relay, and it is redundant if both spawn at the same time

so either:
- make this station guaranteed, and use the `ban_ruins` var on both to ban the other one (imo this is better, but make sure it actually works in game)
- make this station guaranteed, and blacklist the current sensor relay from spawning in the coc

2024-06-20 18:26 UTC, DreamySkrell requested changes
as above

2024-07-15 03:55 UTC, Stev-the-third commented
Closing this, since I want to prioritise other projects that will actually be seen within the next like year lmao. Will reopen whenever I get around to it.

2024-07-15 03:55 UTC, closed without merging