Cargo additions, bugfixes and changes
Aurorastation/Aurora.3 pull request #19438
Opened 2024-06-12 20:13 UTC by BoomerThor

Operation Managers and Hangar Techs were supposed to always have the Cargo Control program downloadable, but it was access-locked behind HOP (which has been changed to executive officer). I also gave the program the ability to run on laptops, so cargo techs actually have a reason to bring a laptop.

Fixes some cargo bounties that were bugged (including #17225) and removed some that cannot be fulfilled. Smoke grenades were removed from security, machinists can't print the Telecomms Traffic Control board, science can't print NVGs anymore, and there is no way in-game to produce monkey hide.

Aluminum, lead, and a couple of other materials miners can smelt don't have many use-cases in-game, so I gave them export values to justify acquiring them.

Let the cargo scanners beep for the soul.

2024-06-12 20:21 UTC, BoomerThor commented
!review

2024-06-14 14:21 UTC, NonQueueingMatt requested changes

2024-06-14 14:21 UTC, NonQueueingMatt commented on code/game/objects/structures/crates_lockers/closets.dm
> +		sleep(5)
Use a timer instead of a sleep

Adding beeps is also not a bugfix

2024-06-15 10:21 UTC, NonQueueingMatt requested changes

2024-06-15 10:21 UTC, NonQueueingMatt commented on code/modules/cargo/bounties/chef.dm
> +		return TRUE
checking the icon isn't an acceptable way to do this - icon files are prone to being changed and generally should never be used to check the state or type of an object

2024-06-15 10:21 UTC, NonQueueingMatt commented on code/modules/cargo/bounties/chef.dm
> +		return TRUE
checking the icon isn't an acceptable way to do this - icon files are prone to being changed and generally should never be used to check the state or type of an object

2024-06-15 10:21 UTC, NonQueueingMatt commented on code/modules/cargo/bounties/chef.dm
> +		return TRUE
checking the icon isn't an acceptable way to do this - icon files are prone to being changed and generally should never be used to check the state or type of an object

2024-06-16 12:17 UTC, Arrow768 approved these changes

2024-06-16 15:21 UTC, NonQueueingMatt approved these changes

2024-06-16 15:36 UTC, merged