Adds a Lii'kenka origin & citizenship
Aurorastation/Aurora.3 pull request #19437
Opened 2024-06-12 19:42 UTC by feartheblackout

![image](https://github.com/Aurorastation/Aurora.3/assets/59633984/52ed81ab-06c0-427f-845d-14ec1563b7b1)
![image](https://github.com/Aurorastation/Aurora.3/assets/59633984/7aaee2a9-73ad-489e-abfc-b276e2a7bdeb)
![image](https://github.com/Aurorastation/Aurora.3/assets/59633984/b44e16b2-7844-46cc-a85e-595779ce16f5)
Done at the request of @desvenlafaxine.

2024-06-12 19:42 UTC, feartheblackout commented
!review

2024-06-14 00:57 UTC, FluffyGhoster requested changes

2024-06-14 00:57 UTC, FluffyGhoster commented on code/controllers/subsystems/records.dm
> +/datum/controller/subsystem/records/proc/get_citizenship_record_name(var/target_citizenship)
DMDoc this, and mark it as `SHOULD_NOT_SLEEP(TRUE)`

2024-06-16 15:23 UTC, NonQueueingMatt approved these changes

2024-06-19 23:20 UTC, DreamySkrell approved these changes

2024-06-20 10:16 UTC, NonQueueingMatt approved these changes

2024-06-20 10:38 UTC, merged