Adds box of psionic receivers to the Research Director's locker.
Aurorastation/Aurora.3 pull request #19439
Opened 2024-06-12 20:20 UTC by lavillastrangiato

Title, so you can perform more weird unethical psionic experiments.

2024-06-12 20:20 UTC, lavillastrangiato commented
!review

2024-06-16 15:21 UTC, NonQueueingMatt approved these changes

2024-06-16 18:20 UTC, FluffyGhoster approved these changes

2024-06-17 08:30 UTC, DreamySkrell requested changes

2024-06-17 08:30 UTC, DreamySkrell commented on maps/sccv_horizon/sccv_horizon-2_deck_2.dmm
> +/obj/item/storage/box/psireceiver,
this should be added in code to `/obj/structure/closet/secure_closet/RD` and not just placed in the map in strongdmm

2024-06-19 07:54 UTC, DreamySkrell approved these changes

2024-06-19 09:39 UTC, merged