Buffs maglights + energy weapons force
Aurorastation/Aurora.3 pull request #19461
Opened 2024-06-14 22:18 UTC by listerla

Trying to bring both in line with this PR: https://github.com/Aurorastation/Aurora.3/pull/18708

Maglights have the same force as binoculars, multitools, etc - other formerly 5-force items. They are still outclassed by crowbars and guns in melee, so they shouldn't revert to being the default weapon of choice.

Energy weapons were not buffed in the above PR, so I've simply adjusted active_force by the formula above.

2024-06-14 22:18 UTC, listerla commented
!review

2024-06-15 08:32 UTC, Llywelwyn approved these changes
makes sense + code fine

2024-06-15 21:48 UTC, Geevies approved these changes

2024-06-20 10:15 UTC, NonQueueingMatt approved these changes

2024-06-23 12:05 UTC, NonQueueingMatt requested changes
Set the maglight force to 9 - we don't want it to be preferable or equal to other items.

2024-06-23 19:33 UTC, listerla commented
Done.

2024-06-24 10:26 UTC, merged