budgs loadout bloat - 6 new headwear
Aurorastation/Aurora.3 pull request #19490
Opened 2024-06-19 08:50 UTC by BulletBudgie

+Added colourable slouch hat, found in colourable hat selection.
+Added colourable sun visor, found in colourable hat selection.
+Added colourable paperboy cap, found in colourable hat selection.
+Added colourable legionnaire cap, found in colourable hat selection.
+Added colourable artist beret, found in loadout.
+Added colourable tight beanie, found in loadout, hides hair.

-Moved TCFL softcap from 'softcap selection' to 'tcfl hat selection'.

All sprites made by me.

2024-06-19 09:12 UTC, Arrow768 commented on code/modules/client/preference_setup/loadout/items/head.dm
> +	tcfl["softcap, tcfl"] = /obj/item/clothing/head/softcap/tcfl
I think the name would fit better as "tcfl softcap"

2024-06-20 18:03 UTC, DreamySkrell requested changes
![image](https://github.com/Aurorastation/Aurora.3/assets/107256943/a48e09ec-2dfc-40b9-804c-c6d6993a1c5b)
wrong dir and name
should be:
`html\changelogs\budg-19490.yml`

2024-06-24 10:33 UTC, DreamySkrell approved these changes

2024-06-26 10:13 UTC, NonQueueingMatt commented
!review

2024-06-26 10:13 UTC, NonQueueingMatt approved these changes

2024-06-26 11:29 UTC, merged