Adds the Dagamuir uniform as a Paramedic uniform option
Aurorastation/Aurora.3 pull request #19553
Opened 2024-06-26 22:14 UTC by feartheblackout

Title/changelog. Approval was acquired prior by @RustingWithYou

2024-06-26 22:14 UTC, feartheblackout commented
!review

2024-07-08 12:49 UTC, NonQueueingMatt approved these changes

2024-07-09 12:58 UTC, DreamySkrell requested changes

2024-07-09 12:59 UTC, DreamySkrell commented on code/modules/clothing/factions/pmcg.dm
> +	)
should not be under /security/ path either

2024-07-09 13:00 UTC, DreamySkrell commented on code/modules/clothing/factions/pmcg.dm
> +	)
it should be more like phalanx uniforms, where security and medical phalanx uniforms do differ

2024-07-09 13:42 UTC, feartheblackout commented on code/modules/clothing/factions/pmcg.dm
> +	)
Does that include a unique sprite as well in this case?

2024-07-11 13:27 UTC, DreamySkrell commented on code/modules/clothing/factions/pmcg.dm
> +	)
yes

2024-07-12 17:47 UTC, closed without merging