Trap Tweaks & Fixes (WIP)
Aurorastation/Aurora.3 pull request #19551
Opened 2024-06-26 19:22 UTC by Geevies

Draft PR for the Trap Tweaks & Fixes PR, which intends to make traps not bad, fun to use, and most importantly, not bad.

- [ ] Finish looking over the file and removing the bad.
- [ ] Clear out the TO-DO's I left in the file.
- [ ] Add ability to examine the item to figure out how to use the item.
- [ ] Test changes.

2024-06-29 11:17 UTC, Geevies commented
!review

2024-06-29 11:17 UTC, Geevies commented
This is ready for review, but I'd like a test merge just to let players test it out and see if they can catch any weird edge case bugs I missed during testing.

2024-06-30 03:03 UTC, Arrow768 approved these changes

2024-07-01 06:51 UTC, FluffyGhoster requested changes

2024-07-01 06:51 UTC, FluffyGhoster commented on code/game/objects/items/weapons/traps.dm
> +	user.visible_message("<b>[user]</b> begins freeing \the [buckled] from \the [src]...", SPAN_NOTICE("You carefully begin to free \the [buckled] from \the [src]..."), SPAN_NOTICE("You hear metal creak
SPAN_BOLD

2024-07-01 06:51 UTC, FluffyGhoster commented on code/game/objects/items/weapons/traps.dm
> +		user.visible_message("<b>[user]</b> frees \the [buckled] from \the [src].", SPAN_NOTICE("You free \the [buckled] from \the [src]."))
SPAN_BOLD

2024-07-01 06:51 UTC, FluffyGhoster commented on code/game/objects/items/weapons/traps.dm
> +	user.visible_message("<b>[user]</b> starts deploying \the [src]...", SPAN_NOTICE("You begin deploying \the [src]!"), SPAN_WARNING("You hear the slow creaking of a spring."))
SPAN_BOLD

2024-07-01 06:51 UTC, FluffyGhoster commented on code/game/objects/items/weapons/traps.dm
> +		user.visible_message("<b>[user]</b> deploys \the [src].", SPAN_WARNING("You deploy \the [src]!"), SPAN_WARNING("You hear a latch click loudly."))
SPAN_BOLD

2024-07-01 06:51 UTC, FluffyGhoster commented on code/game/objects/items/weapons/traps.dm
> +	user.visible_message("<b>[user]</b> starts disarming \the [src]...", SPAN_NOTICE("You begin disarming \the [src]..."), SPAN_WARNING("You hear a latch click followed by the slow creaking of a spring.
SPAN_BOLD

2024-07-01 06:51 UTC, FluffyGhoster commented on code/game/objects/items/weapons/traps.dm
> +		user.visible_message("<b>[user]</b> disarms \the [src]!", SPAN_NOTICE("You disarm \the [src]!"))
SPAN_BOLD

2024-07-01 06:51 UTC, FluffyGhoster commented on code/game/objects/items/weapons/traps.dm
> +		user.visible_message("<b>[user]</b> starts putting \the [capturing_mob] into \the [src].", SPAN_NOTICE("You start putting \the [capturing_mob] into \the [src]."))
SPAN_BOLD

2024-07-01 06:51 UTC, FluffyGhoster commented on code/game/objects/items/weapons/traps.dm
> +		user.visible_message("<b>[user]</b> starts [anchored ? "un" : "" ]securing \the [src]...", SPAN_NOTICE("You start [anchored ? "un" : "" ]securing \the [src]..."))
SPAN_BOLD

2024-07-01 06:51 UTC, FluffyGhoster commented on code/game/objects/items/weapons/traps.dm
> +			user.visible_message("<b>[user]</b> [anchored ? "" : "un" ]secures \the [src]!", SPAN_NOTICE("You [anchored ? "" : "un" ]secure \the [src]!"))
SPAN_BOLD

2024-07-01 06:51 UTC, FluffyGhoster commented on code/game/objects/items/weapons/traps.dm
> +	user.visible_message("<b>[user]</b> tries moving around \the [src] without triggering it.", SPAN_NOTICE("You try to carefully move around \the [src] without triggering it."))
SPAN_BOLD

2024-07-01 06:51 UTC, FluffyGhoster commented on code/game/objects/items/weapons/traps.dm
> +			user.visible_message("<b>[user]</b> successfully moves around \the [src] without triggering it.", SPAN_NOTICE("You successfully move around \the [src] without triggering it."))
SPAN_BOLD

2024-07-01 06:51 UTC, FluffyGhoster commented on code/game/objects/items/weapons/traps.dm
> +			user.visible_message("<b>[user]</b> starts adding metal bars to \the [src]...", SPAN_NOTICE("You start adding metal bars to \the [src]..."))
SPAN_BOLD

2024-07-01 06:51 UTC, FluffyGhoster commented on code/game/objects/items/weapons/traps.dm
> +			user.visible_message("<b>[user]</b> finishes constructing \the [new_trap].", SPAN_NOTICE("You finish constructing \the [new_trap]."))
SPAN_BOLD

2024-07-06 13:50 UTC, Geevies commented
!review

2024-07-08 12:53 UTC, NonQueueingMatt approved these changes

2024-07-09 16:03 UTC, merged