budgs loadout bloat - colorable flats
Aurorastation/Aurora.3 pull request #19555
Opened 2024-06-27 10:25 UTC by BulletBudgie

+Colorable flats, found in loadout

-Removes bloat code from tajara loadout

all sprites by me

2024-06-27 10:26 UTC, BulletBudgie commented
!review

2024-06-27 18:00 UTC, alsoandanswer requested changes
If you want to make tajaran dress flats recolorable you must do it for the normal dress flats as well since they are coded to be an in-tandem system - tajaran flats inherit majority from them and are modified on equip

2024-06-27 21:42 UTC, BulletBudgie commented
> If you want to make tajaran dress flats recolorable you must do it for the normal dress flats as well since they are coded to be an in-tandem system - tajaran flats inherit majority from them and are modified on equip

? im only doing the normal dress flats. the other bit is just removing vestigial code because, like you said, flats are modified on equip for tajara - making the xenowear selection unnecessary, changes arent needed.

2024-07-01 13:10 UTC, NonQueueingMatt requested changes

2024-07-01 13:10 UTC, NonQueueingMatt commented on code/modules/clothing/shoes/xeno/tajara.dm
> +// removed at request of cyb
remove this comment

2024-07-02 05:25 UTC, closed without merging