Adds skin presets for Vaurcae, based on brood colors from the wiki
Aurorastation/Aurora.3 pull request #19585
Opened 2024-07-05 00:13 UTC by feartheblackout

title

To-do: Figure out why allowing selectable skin color and skin color presets to coexist isn't working

2024-07-05 00:14 UTC, feartheblackout commented
!wip

2024-07-05 11:42 UTC, feartheblackout commented
!review

2024-07-11 19:39 UTC, Alberyk approved these changes

2024-07-17 21:16 UTC, NonQueueingMatt requested changes

2024-07-17 21:16 UTC, NonQueueingMatt commented on code/modules/client/preference_setup/general/03_body.dm
> +		if(has_flag(mob_species, HAS_SKIN_COLOR))
this is a useless check now, it's the same as the one above

2024-07-17 21:16 UTC, NonQueueingMatt commented on code/modules/client/preference_setup/general/03_body.dm
> +		if(has_flag(mob_species, HAS_SKIN_PRESET))
this is a useless check now, it's the same as the one above

2024-07-26 12:31 UTC, NonQueueingMatt approved these changes

2024-07-26 12:44 UTC, merged