Odyssey - IPC RnD Facility
Aurorastation/Aurora.3 pull request #19611
Opened 2024-07-09 19:44 UTC by DreamySkrell

wip

2024-07-09 19:44 UTC, DreamySkrell commented
!wip

2024-12-08 22:15 UTC, DreamySkrell commented
reopening to see tests and bot results

2025-01-20 23:33 UTC, DreamySkrell commented
!review

2025-01-21 02:54 UTC, FluffyGhoster commented on code/datums/scenarios/roles.dm
>  /singleton/role
ABSTRACT()?

2025-01-21 02:54 UTC, FluffyGhoster commented on code/game/machinery/computer/access_terminal.dm
> +	. = ..()
Pointless proc

2025-01-21 02:54 UTC, FluffyGhoster commented on code/game/machinery/teleporter.dm
> +	if(isemptylist(possible_pois))
This isn't a lazy list, you defined it above, so it shouldn't use this macro (that is just `!LAZYLEN()`)

2025-01-21 02:54 UTC, FluffyGhoster commented on code/game/machinery/teleporter.dm
> +	if(SSodyssey.scenario && SSodyssey.scenario.actor_accesses && !isemptylist(SSodyssey.scenario.actor_accesses))
Likewise, this isn't a lazy list

2025-01-21 02:54 UTC, FluffyGhoster commented on code/game/machinery/teleporter.dm
> +			var/choice = tgui_alert(usr,
Do not rely on usr, you get the mob as a proc parameter

2025-01-21 02:54 UTC, FluffyGhoster commented on code/game/machinery/teleporter.dm
> +			var/choice = tgui_alert(usr,
Do not rely on usr, you get the mob as a proc parameter

2025-01-21 02:54 UTC, FluffyGhoster commented on code/game/machinery/teleporter.dm
> +				return
This isn't sufficient, someone can close the tgui and this wouldn't match, despite the intention reasonably be to cancel

2025-01-21 02:54 UTC, FluffyGhoster commented on code/game/machinery/teleporter.dm
> +				return
This isn't sufficient, someone can close the tgui and this wouldn't match, despite the intention reasonably be to cancel

2025-01-21 02:54 UTC, FluffyGhoster commented on tgui/packages/tgui/interfaces/AccessTerminal.tsx
> +// data["id_accesses"] = held_card.access			// list(123)
Commented code

2025-02-06 09:46 UTC, DreamySkrell commented on code/datums/scenarios/roles.dm
>  /singleton/role
added

2025-02-06 09:46 UTC, DreamySkrell commented on code/game/machinery/computer/access_terminal.dm
> +	. = ..()
removed

2025-02-06 09:49 UTC, DreamySkrell commented on code/game/machinery/teleporter.dm
> +	if(isemptylist(possible_pois))
why not
`LAZYLEN` is just `length(L)`

what am I supposed to use to check if a list is empty if not `isemptylist()`

if this is ONLY for lazy lists then it should be documented there (it's not)

2025-02-06 09:49 UTC, DreamySkrell commented on code/game/machinery/teleporter.dm
> +	if(SSodyssey.scenario && SSodyssey.scenario.actor_accesses && !isemptylist(SSodyssey.scenario.actor_accesses))
same as above

2025-02-06 09:49 UTC, DreamySkrell commented on code/game/machinery/teleporter.dm
> +			var/choice = tgui_alert(usr,
done

2025-02-06 09:50 UTC, DreamySkrell commented on code/game/machinery/teleporter.dm
> +			var/choice = tgui_alert(usr,
done

2025-02-06 09:50 UTC, DreamySkrell commented on tgui/packages/tgui/interfaces/AccessTerminal.tsx
> +// data["id_accesses"] = held_card.access			// list(123)
removed

2025-02-06 09:52 UTC, DreamySkrell commented on code/game/machinery/teleporter.dm
> +				return
changed to `if(choice != "Ok")`

2025-02-06 09:52 UTC, DreamySkrell commented on code/game/machinery/teleporter.dm
> +				return
changed to if(choice != "Ok")

2025-02-06 10:07 UTC, DreamySkrell commented
!review

2025-02-06 15:54 UTC, FluffyGhoster commented on code/game/machinery/teleporter.dm
> +	if(isemptylist(possible_pois))
You should use lazylist macros to interact with lazylists, and not use them when not interacting with lazylists, hence this would be `!length(list)` if it isn't a lazylist (and in fact this macro would probably disappear at some point, because it's just an useless `!LAZYLEN()`, and doesn't even do what it says because it also applies if the list is null, not just empty, but that's another topic for another day)

2025-02-06 22:02 UTC, DreamySkrell commented on code/game/machinery/teleporter.dm
> +	if(isemptylist(possible_pois))
replaced with !length

2025-02-06 22:02 UTC, DreamySkrell commented on code/game/machinery/teleporter.dm
> +	if(SSodyssey.scenario && SSodyssey.scenario.actor_accesses && !isemptylist(SSodyssey.scenario.actor_accesses))
replaced with !length

2025-02-06 22:32 UTC, FluffyGhoster commented on .github/workflows/byond.yml
> -
Why was this changed? This ensures camera tags are unique, and shouldn't be removed

2025-02-06 22:43 UTC, FluffyGhoster commented on code/game/machinery/teleporter.dm
> +	if(SSodyssey.scenario && SSodyssey.scenario.actor_accesses && length(SSodyssey.scenario.actor_accesses))
```suggestion
	if(length(SSodyssey.scenario?.actor_accesses))
```

2025-02-06 22:43 UTC, FluffyGhoster commented on code/game/machinery/teleporter.dm
> +			var/datum/access/access_datum = access
```suggestion
		for(var/datum/access/access_datum as anything in SSodyssey.scenario.actor_accesses)
```

2025-02-06 22:43 UTC, FluffyGhoster commented on code/game/machinery/teleporter.dm
> +	if(SSodyssey.scenario && SSodyssey.scenario.radio_frequency_name)
```suggestion
	if(SSodyssey.scenario?.radio_frequency_name)
```

2025-02-06 22:43 UTC, FluffyGhoster commented on tools/dmm_scanner/scan_camera_ctags.py
> -import os
Don't delete this file, it is a test to ensure the cameras tags are unique, and should remain

2025-02-07 09:22 UTC, DreamySkrell commented on .github/workflows/byond.yml
> -
* this test does not respect camera networks (for example can't have camera tag "Security - Lobby" in a away site cause it'll fail cause horizon has that camera tag already)
* does not work with mapmanip (can't have multiple submap variants with the same camera tags, where only one submap is picked and inserted into the actual map)
* this is already checked in `/obj/machinery/camera/Initialize()` and should fail unit tests if two cameras in one network have the same tags (so it respects networks and works with mapmanip)

2025-02-07 09:25 UTC, DreamySkrell commented on code/game/machinery/computer/access_terminal.dm
> +/// This base type should not be used, but instead there should be subtypes that provide the available accesses.
marked abstract, removed last doc line

2025-02-07 09:26 UTC, DreamySkrell commented on code/game/machinery/computer/access_terminal.dm
> +/// Should return a list of datums.
changed to `/// Should return a list of `/datum/access`.`

2025-02-07 09:28 UTC, DreamySkrell commented on tools/dmm_scanner/scan_camera_ctags.py
> -import os
replied in another comment

2025-02-07 14:58 UTC, FluffyGhoster commented on .github/workflows/byond.yml
> -
- networks can be changed, the ctag is expected to be globally unique
- without a global check, it's impossible to ensure there's no duplicates because if mapmanip doesn't take the conflicting piece, then the test wouldn't fail, which means a PR can be merged where there's conflicting ctags, even on the same network
- the solution if something doesn't cover your newly introduced use case is to update it so it does, not to delete it

2025-02-07 22:24 UTC, DreamySkrell commented on .github/workflows/byond.yml
> -
* The ctag is expected to be unique in the network. If it's supposed to be globally unique, that means we can't have two maps that use short and simple names like "Security - Lobby".
* Impossible to ensure the correctness of that with mapmanip. And this is not a unique problem to cameras anyways - same thing could happen with different submaps where one has 2 APCs in a area, or whatever other problem like bad paths or vars.
* That's not the case here. I'm not just deleting a test cause I don't like it. But rather, there's no point in updating this python test, when there's already a working and correct check in dm code in camera init proc. No point in keeping two different ways to test the same thing, either.

And anyways what do you even propose I do here, if ctags are supposed to be globally unique? Let's say, I have two submap variants of a medbay. Am I supposed to use ctags in submap 1 like "medbay 1", "medbay 2", "medbay 3", and then in submap 2 start from 4, so "medbay 4", "medbay 5", "medbay 6"?

That's just confusing to the player, who will be asking what happened to the first 3 cameras if submap 2 is picked.

2025-02-07 22:38 UTC, FluffyGhoster commented on .github/workflows/byond.yml
> -
- correct, we cannot, because when they are merged (say a shuttle landing for example, or whatever other reason) then they would be conflicting
- one of the reasons i said having submaps done this way was a bad idea; glad we agree
- the "correct check in dm code" isn't correct, it only works on the same network, it's also an exponential growth compared to a linear scan that python does, ontop of slowing down initialization every round instead of just ensuring noone makes errors only when you should check it, which is before merging whenever possible; this is also not correct because if the mapmanip loads a version without the issue twice, this code would never notice it, and it would get merged only to then randomly fail in live and in a CI, it's beyond my comprehension how one could look at this and go "looks fine to me, nothing bad could happen" when it can and likely will fails in multiple, different, straightforward ways

You could position APCs, cameras and whatnot on the main map, not delete them when you do the submap substitution, and just overlay whatever changed ontop of it, for example; additionally, you could write some code in initalization that takes care of generating an unique ctag on loading, by eg. taking the area name and prepending an incremental number to the camera or what have you, you can also expand the script to account for submaps by scanning them according to the geometry of the insertion as specified in the config files and exclude overlapping results in mutually exclusive loads, there's various ways to solve the problem that doesn't involve YOLOing it

2025-02-08 10:56 UTC, DreamySkrell commented on .github/workflows/byond.yml
> -
* They would not be conflicting, cause they would be using different networks.
* I did not say it's a bad idea. We don't agree here, don't put words into my mouth.
* The check in dm code is correct.

2025-02-08 11:35 UTC, FluffyGhoster commented on .github/workflows/byond.yml
> -
- No, cameras could be merged in the same network, I just went over this
- We agree that it's "Impossible to ensure the correctness of that with mapmanip. And this is not a unique problem to cameras anyways - same thing could happen with different submaps where one has 2 APCs in a area, or whatever other problem like bad paths or vars". You said it. It just follows that it's not a good thing, unless you want to claim that the possibility to merge broken maps is somehow a good thing, you'd consequently have to agree it's a bad thing. Or just say you don't care, I guess
- It isn't, I have just explained how it fails in multiple ways, just pretending I didn't say anything and going "The check in dm code is correct" doesn't make it so

I proposed some possible solutions since you asked, whether you like them or not, it's an undeniable fact that as it stands, your PR would introduce issues and make the system less reliable, with some issues being undetectable. Not only that, you are actively removing safeties. I just need to indicate the presence of an issue, not give you a solution for it; you are the one proposing the change, it's on you to address the issues that are found, not to those that points them out, especially if they already gave you some solutions and you don't like them.

2025-02-09 21:14 UTC, Arrow768 requested changes

2025-02-09 21:14 UTC, Arrow768 commented on .github/workflows/byond.yml
> -
I believe the current implementation is fine.
The UTs fail if duplicate camera names are loaded.
Testing all possible submap combinations, would be better, but the risk of a duplicate cam existing is limited as only more experienced mappers will use submaps where that becomes a issue.

2025-02-10 15:34 UTC, FluffyGhoster commented on .github/workflows/byond.yml
> -
> I believe the current implementation in this pr (with the removed dmm scanner ut) is fine. The UTs fail if duplicate camera names are loaded. Testing all possible submap combinations, would be better, but the risk of a duplicate cam existing is limited as only more experienced mappers will use submaps where that becomes a issue.

No I don't, agree, even granting the first implementation requires a "more experienced mapper[s]", subsequent edits only require room-temperature IQ or above, opening the file and "colouring inside the lines" so to say, which is both something anyone can do, and as easy as copy pasting one section into another (in the same submap) or copy pasting the camera directly without changing the tag to make the error happen.

2025-02-11 08:37 UTC, DreamySkrell commented on code/game/machinery/teleporter.dm
> +				"Teleport Warning", list("Ok", "Cancel")
done

2025-02-11 08:37 UTC, DreamySkrell commented on code/game/machinery/teleporter.dm
> +				"Teleport Warning", list("Ok", "Cancel")
done

2025-02-21 19:32 UTC, Arrow768 approved these changes

2025-02-21 19:39 UTC, FluffyGhoster commented on maps/away/scenarios/enviro_testing_facility/enviro_testing_facility_scenario.dm
> +		"
https://github.com/Aurorastation/Aurora.3/blob/master/.github/guides/STYLE.md#text-variables

`Do not leave empty lines just to isolate the text, the text should start right after the " and end right before the ".`

2025-02-21 19:39 UTC, FluffyGhoster commented on maps/away/scenarios/enviro_testing_facility/enviro_testing_facility_scenario.dm
> +		"
https://github.com/Aurorastation/Aurora.3/blob/master/.github/guides/STYLE.md#text-variables

`Do not leave empty lines just to isolate the text, the text should start right after the " and end right before the ".`

2025-02-21 19:40 UTC, FluffyGhoster commented on maps/away/scenarios/enviro_testing_facility/enviro_testing_facility.dm
> +		"
https://github.com/Aurorastation/Aurora.3/blob/master/.github/guides/STYLE.md#text-variables

`Do not leave empty lines just to isolate the text, the text should start right after the " and end right before the ".`

2025-02-21 19:45 UTC, FluffyGhoster commented on code/game/machinery/computer/access_terminal.dm
> +		usr.drop_from_inventory(idcard, src)
Do not rely on `usr`, you have the mob passed in as a parameter (`user`)

2025-02-21 19:47 UTC, FluffyGhoster commented on code/game/machinery/computer/access_terminal.dm
> +					usr.put_in_hands(held_card)
Do not rely on `usr`, you have the mob as a var in the `datum/tgui/ui`

2025-02-21 19:47 UTC, FluffyGhoster commented on code/game/machinery/computer/access_terminal.dm
> +				var/obj/item/I = usr.get_active_hand()
Do not rely on `usr`, you have the mob as a var in the `datum/tgui/ui`

2025-02-21 19:51 UTC, FluffyGhoster commented on code/game/machinery/computer/access_terminal.dm
> +	var/obj/item/card/id/held_card
https://github.com/Aurorastation/Aurora.3/blob/master/.github/guides/STYLE.md#what-to-document

`All variables, procs and classes that do not have a clear name / signature must be documented using DMDoc.`

2025-02-21 19:56 UTC, FluffyGhoster commented on maps/away/scenarios/enviro_testing_facility/enviro_testing_facility.dm
> +#define NETWORK_ENVIRO_TESTING_FACILITY "Env-Test Facility Zoya"
Forgot one that it didn't took for some reason (maybe i forgot to save it)

https://github.com/Aurorastation/Aurora.3/blob/master/.github/guides/STYLE.md#undef-any-macros-you-create-unless-they-are-needed-elsewhere

`We do not want macros to leak outside their file, this will create odd dependencies that are based on the filenames. Thus, you should #undef any macro you make.`

`If you want more than one files to use macros, put them in somewhere as a file in __DEFINES. `

2025-02-23 18:47 UTC, DreamySkrell commented on maps/away/scenarios/enviro_testing_facility/enviro_testing_facility_scenario.dm
> +		"
https://github.com/Aurorastation/Aurora.3/pull/20514

2025-02-23 18:47 UTC, DreamySkrell commented on maps/away/scenarios/enviro_testing_facility/enviro_testing_facility_scenario.dm
> +		"
https://github.com/Aurorastation/Aurora.3/pull/20514

2025-02-23 18:47 UTC, DreamySkrell commented on maps/away/scenarios/enviro_testing_facility/enviro_testing_facility.dm
> +		"
https://github.com/Aurorastation/Aurora.3/pull/20514

2025-02-23 18:49 UTC, DreamySkrell commented on code/game/machinery/computer/access_terminal.dm
> +				var/obj/item/I = usr.get_active_hand()
replaced with `ui.user.`

2025-02-23 18:49 UTC, DreamySkrell commented on code/game/machinery/computer/access_terminal.dm
> +					usr.put_in_hands(held_card)
replaced with `ui.user.`

2025-02-23 18:50 UTC, DreamySkrell commented on code/game/machinery/computer/access_terminal.dm
> +		usr.drop_from_inventory(idcard, src)
replaced with `user.`

2025-02-23 18:51 UTC, DreamySkrell commented on code/game/machinery/computer/access_terminal.dm
> +	var/obj/item/card/id/held_card
it's pretty obvious what card this var is referring to but ok

2025-02-23 18:52 UTC, DreamySkrell commented on maps/away/scenarios/enviro_testing_facility/enviro_testing_facility.dm
> +#define NETWORK_ENVIRO_TESTING_FACILITY "Env-Test Facility Zoya"
removed the define

2025-03-02 18:34 UTC, FluffyGhoster requested changes
Last things missing before this PR is a-ok, code-wise

2025-03-02 18:34 UTC, FluffyGhoster commented on maps/away/scenarios/enviro_testing_facility/enviro_testing_facility.dm
> +	"
This isn't a very long text var with a lot of lines (even explicitly, as per https://github.com/Aurorastation/Aurora.3/pull/20514#issuecomment-2687984335 `it's not like someone is going to look at that and think four lines == very long`), use the correct style

2025-03-02 18:34 UTC, FluffyGhoster commented on maps/away/scenarios/enviro_testing_facility/enviro_testing_facility_scenario.dm
> +	"
These aren't a very long text vars with a lot of lines (even explicitly, as per https://github.com/Aurorastation/Aurora.3/pull/20514#issuecomment-2687984335 `it's not like someone is going to look at that and think four lines == very long`), use the correct style

2025-03-02 18:34 UTC, FluffyGhoster commented on maps/away/scenarios/enviro_testing_facility/enviro_testing_facility_markers.dm
> +
https://github.com/Aurorastation/Aurora.3/blob/master/.github/guides/STYLE.md#use-comments-where-possible-and-sensible

`Do not use comments to mark obvious things, like the start or end of a file, unless they document the content of the file.`

2025-03-02 18:34 UTC, FluffyGhoster commented on code/game/machinery/computer/access_terminal.dm
> +					ui.user.drop_from_inventory(I,src)
https://github.com/Aurorastation/Aurora.3/blob/master/.github/guides/STYLE.md#spacing


`Operators that should be separated by spaces [...] Argument separator operators like , (and ; when used in a forloop)`

```suggestion
					ui.user.drop_from_inventory(I, src)
```

2025-03-02 18:34 UTC, FluffyGhoster commented on code/game/objects/random/misc.dm
> +			for(var/i in 1 to i_max)
https://github.com/Aurorastation/Aurora.3/blob/master/.github/guides/STYLE.md#no-useless-variables-in-procs

`With few exceptions (mainly for readability), do not declare variables in procs that do not have any use [...] Exception to this would be _ in an interative loop, which by convention indicates a variable that is not important / to be ignored`

```suggestion
			for(var/_ in 1 to rand(1, 4))
```

2025-03-25 20:40 UTC, NonQueueingMatt approved these changes

2025-03-25 20:50 UTC, merged