Honor, fire, burn thy fear: Adds a simple animal knockout technique to the Kis-Khan martial art
Aurorastation/Aurora.3 pull request #19631
Opened 2024-07-13 18:51 UTC by feartheblackout

Implements a disarm technique to Kis-Khan that "knocks out" simple animals for a few seconds, allowing you to follow up with other attacks. This is because shriekers are easy to encounter in the Untouched Lands as a Kis-Khan master and are too difficult to get away from with Unathi sprint, making it easy to get overwhelmed by multiple of them, especially if you're in water. And dying to shriekers is, unfortunately, not badass as a martial arts master.

2024-07-13 18:51 UTC, feartheblackout commented
!review

2024-07-15 08:32 UTC, DreamySkrell approved these changes

2024-07-17 01:37 UTC, FluffyGhoster requested changes

2024-07-17 01:37 UTC, FluffyGhoster commented on code/modules/martial_arts/martial.dm
> +		A.visible_message("<b>\The [A]</b> [D.response_disarm] \the [D]")
SPAN_BOLD

2024-07-17 01:37 UTC, FluffyGhoster commented on code/modules/martial_arts/unathi.dm
> +		return 1
Condense into a single return at the end

2024-07-17 01:37 UTC, FluffyGhoster commented on code/modules/martial_arts/unathi.dm
> +		return 1
Condense into a single return at the end

2024-07-17 01:37 UTC, FluffyGhoster commented on code/modules/martial_arts/unathi.dm
> +		A.visible_message("<b>[A]</b> delivers a blow to \the <b>[D]</b>'s head, making [D.get_pronoun("him")] fall unconscious!")
SPAN_BOLD

2024-07-17 01:37 UTC, FluffyGhoster commented on code/modules/martial_arts/unathi.dm
> +		playsound(D.loc, /singleton/sound_category/punch_sound, 25, 1, -1)
This isn't an acceptable form of playsound, respect the header:

`playsound(get_turf(D), /singleton/sound_category/punch_sound, 25, TRUE, ONE_OF_THE_DEFINES_THAT_ENDS_WITH_SOUND_EXTRARANGE)`

(You can multiply/add/subtract from the extrarange define to fit)

2024-07-17 01:37 UTC, FluffyGhoster commented on code/modules/martial_arts/unathi.dm
> +		to_chat(A, SPAN_WARNING("\The <b>[D]</b> is already unconscious!"))
SPAN_BOLD

2024-07-26 12:29 UTC, NonQueueingMatt approved these changes

2024-07-27 08:41 UTC, Geevies approved these changes

2024-07-29 04:07 UTC, FluffyGhoster approved these changes

2024-08-02 10:51 UTC, merged