Adds mirror shade friend selection
Aurorastation/Aurora.3 pull request #19788
Opened 2024-08-13 22:53 UTC by AlaunusLux

This allows friends to be designated before casting the psi power mirror shade, so that you and another psychic psycho don't kill each other on accident.

2024-08-13 22:56 UTC, AlaunusLux commented
!review

2024-08-24 11:16 UTC, NonQueueingMatt requested changes

2024-08-24 11:16 UTC, NonQueueingMatt commented on code/modules/psionics/abilities/mirror_shade.dm
> +	var/list/mob/living/chosen_friends = list()
this list needs to be cleaned up in destroy

2024-09-15 00:04 UTC, NonQueueingMatt approved these changes

2024-09-15 17:00 UTC, Geevies approved these changes

2024-09-22 09:28 UTC, merged