Refactor /obj/screen to /atom/movable/screen
Aurorastation/Aurora.3 pull request #19852
Opened 2024-08-29 20:25 UTC by Generalcamo

Part of backend stuff required for #19188. Should probably be test merged.

2024-08-29 20:25 UTC, Generalcamo commented
!review

2024-08-30 02:00 UTC, FluffyGhoster requested changes

2024-08-30 02:00 UTC, FluffyGhoster commented on code/_onclick/hud/screen_objects.dm
>  	plane = HUD_PLANE
Unacidable isn't a valid var for this typepath

(See below because for some reason github doesn't let me select the specific line)

2024-08-30 04:08 UTC, FluffyGhoster approved these changes
As far as I see, just a typepath change

2024-09-07 11:11 UTC, Arrow768 approved these changes

2024-09-21 13:03 UTC, merged