Gadpathur Patrol Corvette Update
Aurorastation/Aurora.3 pull request #19933
Opened 2024-09-23 13:04 UTC by furrycactus

Largely just updates little bits on the Gadpathur Patrol Corvette to use more modern mapping standards - new airlock markers, no unsimulated shuttle floor, coloured shuttle window frames, and some redone pipes on the shuttle.

2024-09-24 04:02 UTC, furrycactus commented
!review

2024-09-28 19:27 UTC, hazelrat requested changes
![image](https://github.com/user-attachments/assets/0419c79c-a9b2-4e24-a0c8-8d12adf2b250)
There's a space turf underneath the CO2 tank that should be plating.

I'd also recommend using space/dynamic for the EVA areas rather than open turf, being as this map is only one Z-level with nothing underneath, but this isn't an essential change. Otherwise, this all looks good to me!

2024-09-29 02:31 UTC, hazelrat approved these changes

2024-09-29 15:42 UTC, NonQueueingMatt approved these changes

2024-09-29 16:13 UTC, merged