Fixes the Vaurca autoinhaler
Aurorastation/Aurora.3 pull request #20008
Opened 2024-10-06 05:02 UTC by hazelrat

This fixes the sprite of the special Vaurca phoron inhaler so it appears properly ingame. Adds general support for inhalers without overlays.

2024-10-06 05:04 UTC, hazelrat commented
!bugfix

2024-10-06 05:04 UTC, hazelrat commented
!review

2024-10-06 08:37 UTC, Geevies requested changes

2024-10-06 08:37 UTC, Geevies commented on code/modules/reagents/reagent_containers/inhaler.dm
> +	if(has_overlays == TRUE)
```suggestion
	if(has_overlays)
```

2024-10-07 17:51 UTC, Geevies approved these changes

2024-10-08 15:10 UTC, merged