Darkest Eclipse Holiday
Aurorastation/Aurora.3 pull request #20070
Opened 2024-10-17 14:19 UTC by Ben10083

https://forums.aurorastation.org/topic/2839-wwwadhomaichroniclecomnews/page/6/#comment-177901
> Astronomers have announced that on the day 31 of October, Raskara's anomalous orbit will cause a total eclipse with the two suns. This event is known as the Shi-rra Arr'Kahata, the Darkest Eclipse in folklore

Adds the darkest eclipse to holidays (just for this year).

2024-10-19 12:43 UTC, NonQueueingMatt requested changes

2024-10-19 12:43 UTC, NonQueueingMatt commented on html/changelogs/Ben10083 - Moon.yml
> +  - qol: "The Strange One darkens the sky on October 31st. https://imgur.com/wTZlA7I"
links here might cause some obscure problems; remove the imgur link

2024-10-24 21:55 UTC, hazelrat approved these changes

2024-10-24 22:19 UTC, NonQueueingMatt approved these changes

2024-10-24 22:29 UTC, merged