Custom Stickersheets
Aurorastation/Aurora.3 pull request #20076
Opened 2024-10-18 00:58 UTC by Ben10083

Adds custom stickersheets (you pick 4 stickers in loadout, each selection adds 3 stickers)

'None' and "Random' are not at the top of TGUI lists for content gear tweaks for QoL

2024-10-18 00:59 UTC, Ben10083 commented
!review

2024-10-28 16:55 UTC, hazelrat approved these changes

2024-10-29 00:41 UTC, FluffyGhoster requested changes

2024-10-29 00:41 UTC, FluffyGhoster commented on code/game/objects/items/weapons/storage/stickersheets.dm
> +var/list/stickersheet_stickers_ = typesof(/obj/item/sticker)
This needs to be a GLOB list, and have a DMDoc
Also, the name ends with an underscore, which it shouldn't

2024-10-29 00:41 UTC, FluffyGhoster commented on code/modules/client/preference_setup/loadout/items/toy.dm
> +/// Same as contents/tweak_item except it adds 3 of each item into the stickersheet (4 * 3 = 12)
This isn't a new proc and shouldn't use DMdoc

2024-10-29 00:41 UTC, FluffyGhoster commented on code/modules/client/preference_setup/loadout/items/toy.dm
> +	for(var/i = 1 to valid_contents.len)
Use lenght() instead of .len

2024-10-29 00:41 UTC, FluffyGhoster commented on code/game/objects/items/weapons/storage/stickersheets.dm
> +/proc/stickersheet_stickers()
DMDoc and why is this a global proc instead of being under /datum/gear/toy/stickersheet_custom?

2024-10-29 00:41 UTC, FluffyGhoster commented on code/game/objects/items/weapons/storage/stickersheets.dm
> +/proc/init_sticketsheet_stickers(var/list/stickers)
DMDoc and why is this a global proc instead of being under /datum/gear/toy/stickersheet_custom?

2024-10-29 00:41 UTC, FluffyGhoster commented on code/modules/client/preference_setup/loadout/items/toy.dm
> +			new path(sheet)
For loop

2024-10-30 14:51 UTC, Ben10083 commented
@FluffyGhoster Refactored with help from @nauticall, should resolve all requested changes

2024-11-04 18:52 UTC, NonQueueingMatt requested changes

2024-11-04 18:52 UTC, NonQueueingMatt commented on code/modules/client/preference_setup/loadout/items/toy.dm
> +	gear_tweaks += new /datum/gear_tweak/contents/stickersheet(stickersheet,stickersheet,stickersheet,stickersheet)
why is this getting the same argument 4 times

2024-11-05 18:28 UTC, NonQueueingMatt approved these changes

2024-11-05 18:39 UTC, merged