Sol ship gun addition and tweaks
Aurorastation/Aurora.3 pull request #20094
Opened 2024-10-22 00:53 UTC by TheDanseMacabre

Adds a new type of coilgun for use on Solarian-ish ships, the light coilgun, based off of the event-only Sol coilgun. Also replaces the SSRM's francisca with a goshawk autocannon, to make the ship more competitive with equivalent military factions.

This PR also nerfs the mining blaster, making the blast less powerful.

2024-10-22 00:54 UTC, TheDanseMacabre commented
!review

2024-11-03 23:04 UTC, FluffyGhoster commented
Merge master

2024-12-03 21:08 UTC, TheDanseMacabre commented
ready for review

2024-12-04 17:30 UTC, hazelrat requested changes
![image](https://github.com/user-attachments/assets/c62d2fab-30ed-4b43-be8e-575ce0550211)

Fourty shots for the coilgun seems very excessive, I'd lower it down to 20. Still a lot, so this is likely to outlast most other ships in ammunition, but not so many you can act like you have infinite shots. We probably want people feeling obligated to use the autocannon to clear rocks to save ammo on the bigger coilgun.

![image](https://github.com/user-attachments/assets/03550c3c-c92b-40e1-a7bf-9c0f920f5983)

These windows seem miscoloured, I'd recommend using /obj/effect/map_effect/window_spawner/full/shuttle/raider to make them fit the walls. The shuttle control console not matching the terminals around it looks unusual, please either make the terminals match the control console or vice versa - the TCAF ship has an example for the proper directory for the latter.

![image](https://github.com/user-attachments/assets/8de95862-7007-411e-9306-2a7aa55442a6)

Missing vent.

![image](https://github.com/user-attachments/assets/6f61cdff-47e3-40b1-ab0d-eb57ebd69494)

Missing vent and scrubber.

2024-12-04 17:30 UTC, hazelrat commented on code/modules/overmap/ship_weaponry/weaponry/light_coilgun.dm
> +	max_ammo = 4
My thought for the balance is to lower the maximum ammo from 4 to 2. I'd view the identity of coilguns as similar to the large single-shot cannons such as the lammergeier or longbow - it has extremely lethal projectiles, but low ammo capacity, so you need to make your shots count. High ammo capacities should be exclusive to automatic chemical guns like the grauwolf and francisca.

2024-12-04 17:38 UTC, hazelrat commented
![image](https://github.com/user-attachments/assets/12f502c4-93ae-430f-9c63-cc3aa6f4b374)

There's also a few turf passthroughs underneath the coilgun where I'd expect there to be floor turfs.

2024-12-04 17:41 UTC, hazelrat commented
![image](https://github.com/user-attachments/assets/fdd41cfe-af08-4a93-9539-803c13d70c84)
Disconnected stretch of piping under the grates.

2025-04-21 07:44 UTC, closed without merging