Jaws of life for atmos
Aurorastation/Aurora.3 pull request #20138
Opened 2024-11-03 14:56 UTC by FabianK3

### Introduction
This PR adds a hydraulic rescue tool (jaws of life) to the atmos locker room. The goal is to provide Atmospheric technicians the means to enter areas that they are needed in without knowing the airlock wiring or having access to insulated gloves. This places them in a better position for their emergency response duties. This also provides the opportunity for cross-department work towards paramedics and maybe security.

The idea raised from this suggestion/thread: [Reinforce Engineering's Division of Labor](https://forums.aurorastation.org/topic/21285-reinforce-engineerings-division-of-labor/)

### What has been changed?
- Added a jaws of life to the table in the atmos locker room.
- Added the functionality to force open powered airlocks that are not broken or bolted. Without this functionality the tool wouldn't serve its intended purpose.
- Added a couple of messages when using the tool for different actions for fluff.

2024-11-03 18:37 UTC, Generalcamo requested changes

2024-11-03 18:37 UTC, Generalcamo commented on maps/sccv_horizon/sccv_horizon.dmm
> +/obj/item/crowbar/robotic/jawsoflife,
Did you forget to commit this file?

2024-11-04 14:18 UTC, Generalcamo commented on maps/sccv_horizon/sccv_horizon.dmm
> +/obj/item/crowbar/robotic/jawsoflife,
Misread this, carry on

2024-11-04 14:18 UTC, Generalcamo approved these changes

2024-11-06 16:54 UTC, Geevies approved these changes

2024-11-07 04:57 UTC, FluffyGhoster commented on code/game/machinery/doors/airlock.dm
> +				SPAN_DANGER("[user.name] starts using the [tool] on the airlock's bolt cover!"),\
```suggestion
				SPAN_DANGER("[user] starts using the [tool] on the airlock's bolt cover!"),\
```

2024-11-07 04:57 UTC, FluffyGhoster commented on code/game/machinery/doors/airlock.dm
> +			user.visible_message(\
you don't need to make newlines like this, put the first span_danger in the same line and align the others below, and it should work

2024-11-07 04:57 UTC, FluffyGhoster commented on code/game/machinery/doors/airlock.dm
> +			user.visible_message(\
same as above

2024-11-07 04:57 UTC, FluffyGhoster commented on code/game/machinery/doors/airlock.dm
> +				SPAN_DANGER("[user.name] starts using the [tool] on the airlock's bolts!"),\
```suggestion
				SPAN_DANGER("[user] starts using the [tool] on the airlock's bolts!"),\
```

2024-11-09 01:04 UTC, FluffyGhoster approved these changes

2024-11-10 14:00 UTC, merged