First Aid Kits in First Aid Kit Lockers
Aurorastation/Aurora.3 pull request #20186
Opened 2024-11-19 22:54 UTC by OolongCow

White first aid wall lockers now consistently contain a basic first aid kit rather than mapper-placed basic supplies. Spawning moved to code rather than hand-placed items on the map. High-risk (even if only flavorfully) areas and areas far from any other kit/medical have had a wall locker added. Lockers using the same /obj for other purposes (usually blood lockers) have been swapped to use the medical/secure variant. Meant to accompany changes to basic first aid kit contents in #20187 

![image](https://github.com/user-attachments/assets/654bef98-42cb-4257-bbf5-83edbc3204b0)

![image](https://github.com/user-attachments/assets/70a6eafa-dd8b-4610-b4d8-f343ac6242de)

2024-11-19 23:11 UTC, OolongCow commented
!review

2024-11-20 08:31 UTC, hazelrat requested changes

2024-11-20 09:03 UTC, DreamySkrell requested changes

2024-11-20 09:03 UTC, DreamySkrell commented on code/game/objects/structures/crates_lockers/closets/walllocker.dm
> +	new /obj/item/storage/firstaid/regular
Requesting above changes.

Base closet/locker types should be empty, and there should be named subtypes that start with items.

2024-11-20 22:50 UTC, OolongCow commented on code/game/objects/structures/crates_lockers/closets/walllocker.dm
> +	new /obj/item/storage/firstaid/regular
Ah. I missed that.

2024-11-22 01:34 UTC, OolongCow commented on code/game/objects/structures/crates_lockers/closets/walllocker.dm
> +	new /obj/item/storage/firstaid/regular
Resolved in the new PR #20194

2024-11-22 01:35 UTC, OolongCow commented
Closing and moving to a new PR #20194  due to a branch name change causing my commits to stop appearing.

2024-11-22 01:35 UTC, closed without merging