AI Remote Control Fixes
Aurorastation/Aurora.3 pull request #20198
Opened 2024-11-26 03:35 UTC by Ben10083

Fixes https://github.com/Aurorastation/Aurora.3/issues/13267

Also adds QoL where pressing eject on remote controlled mechs exits remote control.

2024-11-26 03:36 UTC, Ben10083 commented
!bugfix

2024-11-29 16:51 UTC, Ben10083 commented
WIP until I can fix spiderbot radios

2024-11-29 16:51 UTC, Ben10083 commented
!wip

2024-11-29 19:14 UTC, Ben10083 commented
!review

2024-12-02 16:02 UTC, FluffyGhoster requested changes

2024-12-02 16:02 UTC, FluffyGhoster commented on code/controllers/subsystems/virtual_reality.dm
> +/datum/controller/subsystem/virtualreality/proc/bound_selection(var/user, var/network, var/return_list)
`return_list` seems useless here, you can always return the list as it doesn't seem you return anything else

2024-12-02 16:02 UTC, FluffyGhoster commented on code/controllers/subsystems/virtual_reality.dm
> +/datum/controller/subsystem/virtualreality/proc/mech_selection(var/user, var/network, var/return_list)
`return_list` seems useless here, you can always return the list as it doesn't seem you return anything else

2024-12-03 12:59 UTC, merged