New Dionae Loadout Items - Wave1
Aurorastation/Aurora.3 pull request #20209
Opened 2024-11-29 11:21 UTC by Yonnimer

Adds several new items to the Dionae loadout:
- Three sets of clothes and two hoods for voidtamers
- A jacket, cloak, two hats, and an undersuit for the ekane
- A narrows hardhat and jacket, as well as a slightly reworked jumpsuit (made chonk)
- New Eternal Robes, the old ones are remaining for now but may be reworked in the second wave of items
- Also removed some redundant rokz and serz items and the ships themselves, these may be reworkedin the future, but for now aren't in current lore.

More loadout items will ideally be coming soon for each factions in the coming weeks/months.

2024-11-29 11:22 UTC, Yonnimer commented
!review

2024-11-30 17:05 UTC, hazelrat requested changes
Some imperfect grammar, LGTM otherwise.

2024-11-30 17:05 UTC, hazelrat commented on code/modules/client/preference_setup/loadout/items/xeno/diona.dm
> +	description = "A jacket made of woven carp hide and adorned with golden, typically worn by various voidtamer-alligned factions.."
```suggestion
	description = "A jacket made of woven carp hide and adorned with gold, typically worn by various voidtamer-aligned factions."
```

2024-11-30 17:05 UTC, hazelrat commented on code/modules/client/preference_setup/loadout/items/xeno/diona.dm
> +	description = "A apron made of woven carp hide and adorned with golden, typically worn by various voidtamer-alligned factions.."
```suggestion
	description = "A apron made of woven carp hide and adorned with gold, typically worn by various voidtamer-aligned factions."
```

2024-11-30 17:05 UTC, hazelrat commented on code/modules/client/preference_setup/loadout/items/xeno/diona.dm
> +	description = "A vest made of woven carp hide and adorned with golden, typically worn by various voidtamer-alligned factions.."
```suggestion
	description = "A vest made of woven carp hide and adorned with gold, typically worn by various voidtamer-aligned factions."
```

2024-11-30 17:05 UTC, hazelrat commented on code/modules/clothing/head/xenos/diona.dm
> +	desc = "an exuberant hat adorned with colorful feathers across its surface. Despite the design, wearers will feel the heat of the sun greater than without."
```suggestion
	desc = "An exuberant hat adorned with colorful feathers across its surface. Despite the design, wearers will feel the heat of the sun greater than without."
```

2024-11-30 17:05 UTC, hazelrat commented on code/modules/clothing/head/xenos/diona.dm
> +	desc = "a simple hat adorned with colorful feathers across its surface. Despite the design, wearers will feel the heat of the sun greater than without."
```suggestion
	desc = "A simple hat adorned with colorful feathers across its surface. Despite the design, wearers will feel the heat of the sun greater than without."
```

2024-11-30 17:05 UTC, hazelrat commented on code/modules/clothing/head/xenos/diona.dm
> +	desc = "a hood made of aged and tanned carp hide, decorated with gold, pointed structures across all sides."
```suggestion
	desc = "A hood made of aged and tanned carp hide, decorated with gold, featuring pointed structures across all sides."
```

2024-11-30 17:05 UTC, hazelrat commented on code/modules/clothing/head/xenos/diona.dm
> +	desc = "a hood made of aged and tanned carp hide, decorated with gold, pointed structures across all sides. This one has an open visor, showing the wearer's face."
```suggestion
	desc = "A hood made of aged and tanned carp hide, decorated with gold, featuring pointed structures across all sides. This one has an open visor, showing the wearer's face."
```

2024-11-30 17:05 UTC, hazelrat commented on code/modules/clothing/head/xenos/diona.dm
> +	desc = "An old hardhat painted in Hephestus colors, fabric hanging off the sides to protect the wearer's ears."
```suggestion
	desc = "An old hard hat painted in Hephaestus colors, fabric hanging off the sides to protect the wearer's ears."
```

2024-11-30 17:05 UTC, hazelrat commented on code/modules/clothing/under/xenos/diona.dm
> +	desc = "A blue, seeming high-quality dress with a colorful strap of fabric running along it, typically seen by Dionae hailing from the Hieroaetherian Ekane."
```suggestion
	desc = "A blue, seemingly high-quality dress with a colorful strap of fabric running along it, typically seen by Dionae hailing from the Hieroaetherian Ekane."
```

2024-12-01 12:21 UTC, hazelrat approved these changes

2024-12-05 15:57 UTC, NonQueueingMatt approved these changes

2024-12-05 16:47 UTC, merged