Ship/Shuttle Terminal Access Checks
Aurorastation/Aurora.3 pull request #20227
Opened 2024-12-01 20:00 UTC by Ben10083

Ship consoles such as targeting and sensors now check for access.

Emagging a ship console disables access checks

Horizon shuttles given access requirements (bridge crew can access any ship)

Went through most offships and added access requirements, likely missed some however.

For access requirements, I only added them for helm control, targetting, and shuttle control consoles

2024-12-01 20:00 UTC, Ben10083 commented
!review

2024-12-04 21:24 UTC, DreamySkrell commented
I am conflicted

it makes sense that shuttles aren't just free for anyone to steal

but at the same time, ID requirement is very harsh, especially for offships or odyssey, cause
- there is no indication of what ID or access you need exactly
- you can't gain access without having the actual ID (without emag but that's antag gear)
- so if the pilot with access is gone then you are fucked and the shuttle will never be usable

2024-12-04 21:25 UTC, DreamySkrell requested changes
IMO, there should be some way to gain access to pilot the shuttle, that isn't emag

2024-12-04 21:55 UTC, FluffyGhoster commented
This seems superflous at best, the shuttle controls are already behind a door, if anything needs to be access restricted, it would be said door to access the cockpit, not the console itself?

2024-12-04 23:20 UTC, Ben10083 commented
> IMO, there should be some way to gain access to pilot the shuttle, that isn't emag something that the average offship or actor could do wire hacking maybe

Added method by using wirecutters. This means that antags (or anyone else) can use wirecutters and gain access after a lengthy period 
![image](https://github.com/user-attachments/assets/b184e2a5-5cdd-4af9-8267-9eb96042a0af)

2024-12-04 23:22 UTC, Ben10083 commented
> This seems superflous at best, the shuttle controls are already behind a door, if anything needs to be access restricted, it would be said door to access the cockpit, not the console itself?

not always possible, majority of shuttles even on the horizon dont have this protection (windoors can be quickly smashed on canary, spark and quark can be accessed via an airlock

2024-12-05 01:16 UTC, Ben10083 commented
Now in sections of 15 instead of needing 2 minutes uninterupted. Repairable with cabling
![image](https://github.com/user-attachments/assets/cbf00f8b-af32-4845-af66-f0b135d65b60)
![image](https://github.com/user-attachments/assets/9b112d24-2eb3-4722-81c1-8f068fd3ceac)

2024-12-12 15:40 UTC, DreamySkrell requested changes
.

2024-12-22 01:25 UTC, Arrow768 approved these changes

2024-12-22 01:29 UTC, Arrow768 commented
It's not ideal, but it's a reasonable first implementation.

My main issues with it are:
* Afaik repairing something ragged usually requires pulling/replacing the boards/ rebuild from scratch. (See airlocks)
* I am not a fan of introducing yet another "hacking" mechanic.
(Why not use the good old wires if it really needs to be hackable locally?)
* I am unsure if a remote unlock or just call-back would be a better idea instead of local hacking (skill issue)

2025-01-29 06:21 UTC, FluffyGhoster commented on code/modules/overmap/ships/computers/ship.dm
> +				playsound(src.loc, 'sound/items/Wirecutter.ogg', 30, 1)
```suggestion
				playsound(src.loc, 'sound/items/Wirecutter.ogg', 30, TRUE)
```

2025-01-29 06:21 UTC, FluffyGhoster commented on code/modules/overmap/ships/computers/ship.dm
> +						playsound(src.loc, 'sound/items/Deconstruct.ogg', 30, 1)
```suggestion
						playsound(src.loc, 'sound/items/Deconstruct.ogg', 30, TRUE)
```

2025-01-29 06:21 UTC, FluffyGhoster commented on code/modules/overmap/ships/computers/ship.dm
> +						to_chat(usr, SPAN_NOTICE("You replace some broken cabling of \the [src] <b>([(hotwire_progress / initial(hotwire_progress)) * 100]%)</b>."))
SPAN_BOLD

2025-01-29 06:21 UTC, FluffyGhoster commented on code/modules/overmap/ships/computers/ship.dm
> +		user.visible_message("<b>[user]</b> opens a panel underneath \the [src] and starts snipping wires...", SPAN_NOTICE("You open the maintenance panel and attempt to hotwire \the [src]..."))
SPAN_BOLD

2025-01-29 06:21 UTC, FluffyGhoster commented on code/modules/overmap/ships/computers/ship.dm
> +/obj/machinery/computer/ship/emag_act(var/remaining_charges, var/mob/user, var/hotwired = FALSE)
Respect the parent proc signature
`/atom/proc/emag_act(var/remaining_charges, var/mob/user, var/emag_source)`
You are not keeping the `emag_source` var

2025-01-29 06:21 UTC, FluffyGhoster commented on code/modules/shuttles/shuttle_console.dm
> +						playsound(src.loc, 'sound/items/Deconstruct.ogg', 30, 1)
```suggestion
						playsound(src.loc, 'sound/items/Deconstruct.ogg', 30, TRUE)
```

2025-01-29 06:21 UTC, FluffyGhoster commented on code/modules/shuttles/shuttle_console.dm
> +				playsound(src.loc, 'sound/items/Wirecutter.ogg', 30, 1)
```suggestion
				playsound(src.loc, 'sound/items/Wirecutter.ogg', 30, TRUE)
```

2025-01-29 06:21 UTC, FluffyGhoster commented on code/modules/shuttles/shuttle_console.dm
> +						to_chat(usr, SPAN_NOTICE("You replace some broken cabling of \the [src] <b>([(hotwire_progress / initial(hotwire_progress)) * 100]%)</b>."))
SPAN_BOLD

2025-01-29 06:21 UTC, FluffyGhoster commented on code/modules/shuttles/shuttle_console.dm
> +		user.visible_message("<b>[user]</b> opens a panel underneath \the [src] and starts snipping wires...", SPAN_NOTICE("You open the maintenance panel and attempt to hotwire \the [src]..."))
SPAN_BOLD

2025-01-29 06:21 UTC, FluffyGhoster commented on code/modules/shuttles/shuttle_console.dm
> +			. += SPAN_SUBTLE("The bottom panel appears open with wires hanging out. It can be repaired with additional cabling. <i>Current progress: [(hotwire_progress / initial(hotwire_progress)) * 100]%</i>
SPAN_ITALIC

2025-01-29 06:21 UTC, FluffyGhoster commented on code/modules/shuttles/shuttle_emergency.dm
> +/obj/machinery/computer/shuttle_control/emergency/emag_act(var/remaining_charges, var/mob/user, var/hotwired = FALSE)
Respect the parent proc signature
`/atom/proc/emag_act(var/remaining_charges, var/mob/user, var/emag_source)`
You are not keeping the `emag_source` var

2025-01-29 06:21 UTC, FluffyGhoster commented on code/modules/overmap/ships/computers/ship.dm
> +			. += SPAN_SUBTLE("The bottom panel appears open with wires hanging out. It can be repaired with additional cabling. <i>Current progress: [(hotwire_progress / initial(hotwire_progress)) * 100]%</i>
SPAN_ITALIC

2025-01-31 14:05 UTC, merged