Adds Additional Status and AI Panels
Aurorastation/Aurora.3 pull request #20220
Opened 2024-11-29 22:53 UTC by Ben10083

Title

Adds multiple new Status and AI panels across the vessel, with goal of having status panels at most high-traffic areas

2024-11-29 22:53 UTC, Ben10083 commented
!review

2024-11-30 17:21 UTC, hazelrat commented
![image](https://github.com/user-attachments/assets/c7310d86-7362-4b38-bba4-963b9eda7ce9)
Multiple displays in a single room seems excessive to me, especially considering the light fixtures will be awkwardly on top of their screens ingame?

2024-11-30 18:35 UTC, Ben10083 commented
>htTiW950xD-3XDqk4cyx_3OFIToa9Cl_IvHOVqYS-CE) Multiple displays in a single room seems excessive to me, especially considering the light fixtures will be awkwardly on top of their screens ingame?

Discused over discord, did a sweep through to deal with clipping issues

2024-11-30 21:26 UTC, hazelrat approved these changes

2024-12-04 19:44 UTC, DreamySkrell commented
![image](https://github.com/user-attachments/assets/1f75adb6-6f69-45a3-a07c-2532a0a7d488)
![image](https://github.com/user-attachments/assets/4b880561-a6b9-4a21-b8d8-e94eaa266039)
![image](https://github.com/user-attachments/assets/baa6f8f1-02b9-4de0-88ed-dbadf0cfe104)
![image](https://github.com/user-attachments/assets/6756f8d6-b343-4ad2-91f4-f0eb2a72038f)
![image](https://github.com/user-attachments/assets/fa78541e-056f-4f68-be48-f395ff74b209)
![image](https://github.com/user-attachments/assets/851fa232-4be4-443b-9f8b-4faba116e7cc)


There is still a ton of places that have overlapping/clipping wall-mountables

I see no point in spamming these status panels everywhere. They are huge and just don't look good, and they are not proper 3/4 with all the perspectives.

![image](https://github.com/user-attachments/assets/9d3ef195-5884-4200-9f29-a8717eaaf8cd)

like this just looks really bad

2024-12-04 19:47 UTC, DreamySkrell requested changes
as above, please fix all the clipping issues

And being just a dev, I have no power to deny this PR, but I do not like it (reasoning above)

2024-12-04 20:25 UTC, Ben10083 commented
> There is still a ton of places that have overlapping/clipping wall-mountables

(Ingame)
![image](https://github.com/user-attachments/assets/8ed43e44-9ecd-4631-bde8-6769cda505c3)
![image](https://github.com/user-attachments/assets/54631104-2dc4-4601-9a9f-ad10c6c4fcbd)
![image](https://github.com/user-attachments/assets/6f4a4c94-a993-481e-bc5c-435ac2f7758e)
![image](https://github.com/user-attachments/assets/667d84bb-e02f-464e-afb3-7b50b1ec272f)
![image](https://github.com/user-attachments/assets/6ee90589-0fa4-494b-add7-8d20b7aae9c1)

Did do another look around but overall seems good. 

as for sprite issue, I don't know enough about spritework to know how this sprite could be changed to fit 3/4 perspective better while not compromising the content.

The goal for the PR is that the status panels are very sparse and oftentimes not in areas people would see. I can see the argument for reducing some but we should have more

2024-12-04 20:25 UTC, Ben10083 commented
Also they seem fine in other directions

2024-12-04 21:47 UTC, DreamySkrell commented
They shouldn't look like they clip when looking at them in strongdmm/mapdiffbot, even if they look fine in game. It hurts readability.

2024-12-05 19:31 UTC, Ben10083 commented
> They shouldn't look like they clip when looking at them in strongdmm/mapdiffbot, even if they look fine in game. It hurts readability.
> 
> And I do not see why there should be multiple panels in the same areas, like the OM office or bridge entrance.

those multiple panels are supply panels, AI panels, status panels, etc etc. They are different

2025-02-16 03:36 UTC, closed without merging