Replace Social Credit Score with Social Compatability Index
Aurorastation/Aurora.3 pull request #20230
Opened 2024-12-02 23:49 UTC by Warbidon

🚨 BREAKING NEWS:  Our favorite dystopian frogs just got a little less...Chinese? Down with the Social Score Order, up with the new Social Compatability Index.

: )

2024-12-03 00:22 UTC, FluffyGhoster commented
This would need lore approval before it can be evaluated

2024-12-03 05:47 UTC, Ben10083 commented on code/modules/background/citizenship/skrell.dm
> +								"Encourage Federation citizens with low index rating to work to increase their index rating.")
```suggestion
								"Encourage Federation citizens with low index rating to work to increase their rating.")
```

2024-12-03 05:47 UTC, Ben10083 commented on code/modules/clothing/under/accessories/badges.dm
> +	. +=  SPAN_NOTICE("The passport displays the owner's social compatability index as: [credit_score].")
> credit_score

Maybe crtl f and swap it to `compat_index` or something

2024-12-04 00:25 UTC, Warbidon commented
Reasonably sure I got every single instance of social_credit_tweaks & credit_score and changed them to be more lore friendly.

2024-12-04 21:26 UTC, DreamySkrell approved these changes

2024-12-05 15:55 UTC, NonQueueingMatt commented
!review

2024-12-05 17:15 UTC, FluffyGhoster requested changes
Is the mispelling of "compat**i**bility" intentional per lore? It seems it's used inconsistently too, so I presume not?

2024-12-07 04:03 UTC, Warbidon commented
> Is the mispelling of "compat**i**bility" intentional per lore? It seems it's used inconsistently too, so I presume not?

I blame Brotendo for this as I copy pasted the word from their post, I don't actually know how to spell.
https://i.imgur.com/18BbRmX.png

2024-12-09 05:03 UTC, Warbidon reviewed
I think I made these changes correctly

2024-12-14 22:56 UTC, FluffyGhoster commented on code/modules/clothing/under/xenos/skrell.dm
> +	desc_extended = "The Nralakk Federation ranks its workers based on their social compatability index, and provides workwear based on said index: Ox are those who are within the Tertiary Numerical ban
`compatability`

2024-12-14 22:56 UTC, FluffyGhoster commented on code/modules/clothing/under/xenos/skrell.dm
> +	desc_extended = "The Nralakk Federation ranks its workers based on their social compatability index, and provides workwear based on said index: Ix are those who are low-ranked Secondary Numericals w
`compatability`

2024-12-14 22:56 UTC, FluffyGhoster commented on code/modules/clothing/under/xenos/skrell.dm
> +	desc_extended = "The Nralakk Federation ranks its workers based on their social compatability index, and provides workwear based on said index: Oqi are high-ibdexed Secondary Numericals or low-index
`compatability`

2024-12-14 22:56 UTC, FluffyGhoster commented on code/modules/clothing/under/xenos/skrell.dm
> +	desc_extended = "The Nralakk Federation ranks its workers based on their social compatability index, and provides workwear based on said index: Iqi are high-indexed Primary Numericals, and as such t
`compatability`

2024-12-14 22:56 UTC, FluffyGhoster commented on code/modules/clothing/under/xenos/skrell.dm
> +	desc_extended = "The Nralakk Federation ranks its workers based on their social compatability index, and provides workwear based on said index: Ox are those who are within the Tertiary Numerical ban
`compatability`

2024-12-14 22:56 UTC, FluffyGhoster commented on code/modules/clothing/under/xenos/skrell.dm
> +	desc_extended = "The Nralakk Federation ranks its workers based on their social compatability index, and provides workwear based on said index: Ix are those who are low-indexed Secondary Numericals
`compatability`

2024-12-14 22:56 UTC, FluffyGhoster commented on code/modules/clothing/under/xenos/skrell.dm
> +	desc_extended = "The Nralakk Federation ranks its workers based on their social compatability index, and provides workwear based on said index: Oqi are high-indexed Secondary Numericals or low-index
`compatability`

2024-12-14 22:56 UTC, FluffyGhoster commented on code/modules/clothing/under/xenos/skrell.dm
> +	desc_extended = "The Nralakk Federation ranks its workers based on their social compatability index, and provides workwear based on said index: Iqi are high-indexed Primary Numericals, and as such t
`compatability`

2024-12-18 03:43 UTC, Warbidon commented
gotcha, committed and changed, it should be good to go now? I don't know how anyone survives doing github changes.

2024-12-20 04:21 UTC, hazelrat approved these changes

2025-01-02 15:40 UTC, FluffyGhoster approved these changes

2025-01-04 00:26 UTC, merged