Flare Buff
Aurorastation/Aurora.3 pull request #20244
Opened 2024-12-10 14:46 UTC by Geevies

* Flares now burn brighter, longer, are smaller items (can bring more), and flare boxes now contain 12 of them, up from 4.

2024-12-10 16:24 UTC, hazelrat approved these changes

2024-12-10 18:16 UTC, alsoandanswer commented
This seems like a bit much for a cheap, disposable item, wouldn't it be better to have better flashlights and floodlights to set up instead?

2024-12-10 18:31 UTC, hazelrat commented
> This seems like a bit much for a cheap, disposable item, wouldn't it be better to have better flashlights and floodlights to set up instead?

I think we want flares to be decently strong for how important lighting is on dark odyssey maps like the Cryo Outpost. The more people can see the better, and handling flare lighting gives support roles on the expedition (service, operations, etc) something to do.

2024-12-10 22:07 UTC, alsoandanswer requested changes
They should be a different item entirely, then, like an "expeditionary flare" or something. These are balanced around the Horizon's corridors, rooms and spaces, compared to the expanses of an exoplanet.

2024-12-10 22:07 UTC, alsoandanswer commented on code/game/objects/items/weapons/storage/boxes.dm
> +	max_storage_space = 12
You should make a new "large box" variant instead, e.g. the large produce box used in the kitchen.

2024-12-10 22:08 UTC, alsoandanswer commented on code/game/objects/items/devices/lighting/flare.dm
> +	w_class = WEIGHT_CLASS_TINY
Don't buff the old flares, they're used for shitty emergency kits.

Make a new variant.

2024-12-12 17:49 UTC, hazelrat approved these changes
Same as Dreamy, I don't think I see flares getting enough usage as is to be convinced this would be a significant balance issue.

2024-12-18 14:39 UTC, OolongCow commented
The only time you would ever willingly bring flares at the moment is if you just don't have access to other options, because flares are just bad at their niche of being able to cover lots of tiles with temporary light. They are incredibly space-inefficient for no real reason and in the vast majority of cases there is zero advantage to not just drag floodlights with you. That is not a "nerf floodlights!" demand, but proof that what flares are SUPPOSED to be good for, they just aren't.

2024-12-28 18:55 UTC, merged