Odyssey Latejoin Intrepid Spawn
Aurorastation/Aurora.3 pull request #20299
Opened 2024-12-24 12:15 UTC by Geevies

* When latejoining, if it's an Odyssey round and the Intrepid is not in its hangar, the latejoiner is given the option of spawning directly onto the Intrepid.

![image](https://github.com/user-attachments/assets/83a7f40f-e7bc-464c-b29b-fcdd9cd07987)

2024-12-24 13:15 UTC, DreamySkrell requested changes
Requesting changes:
- Spawning on the Intrepid must not be allowed if the Intrepid is stolen or taken over by actors/antags/offships/whatever (or damaged and abandoned, or destroyed). We don't want horizon crew to still be spawning on the Intrepid then.

But also, I really don't like this, because:
- Requested changes above are basically impossible to implement. There is no way to check if the Horizon is actually in control of the Intrepid, and isn't stolen or taken hostage or whatever else.
- People selecting to spawn on the Intrepid have no way to check what gimmick or mission is it, and if they are interested in it, so they may spawn and have to go back up to Horizon.
- So the new spawning crew are: clueless about what is going on, and don't have any gear to actually participate in the expedition.

Alternatively:
- We could have it in rules that Intrepid cannot be fucked with by actors/antags/offships, while it is out on expedition. But I would really hate that, and I do not think it is a good idea for a lot of reasons.

2024-12-24 14:19 UTC, alsoandanswer commented
On the other hand... 

1. the Intrepid DOES have a Cryopod, so it is perfectly reasonable
2. players spawn with basically nothing, so they aren't in any antag-fighting capacity
3. I don't really condone this but people can just spectate a bit and then ahelp respawn.

I think this is a good idea, but to play it safe it could be locked behind an admin/mod command.

2024-12-24 16:52 UTC, Greenjoe12345 commented
> 1. the Intrepid DOES have a Cryopod, so it is perfectly reasonable

It feels a bit odd for (possibly multiple) people to be popping out of a shuttle's cryopod imo.

2024-12-24 20:00 UTC, DreamySkrell commented
>     2. players spawn with basically nothing, so they aren't in any antag-fighting capacity

(In case of actors/antags stealing the shuttle.) Even if the crew spawns there without any proper gear, it's still kinda ruining the gimmick, if the actors/antags suddenly get a bunch of fresh hostages that they have no idea what to do with.


>     3. I don't really condone this but people can just spectate a bit and then ahelp respawn.

People can do that, but they... don't have to. And spawn anyway, without knowing if Intrepid is safe to spawn in. It doesn't fix the issue at all.

2024-12-24 21:19 UTC, Ben10083 commented
Honestly not too sure how this PR can/should be implemented, like others say there are scenarios where Intrepid should be spawned in.

Most jobs dont HAVE the gear to respond to a mission at start (and shouldnt), and even if we ignore the fact they are going in blind where status of Intrepid is unknown...

1. why the hell does the Horizon even HAVE people doing that
2. What if the odyssey itself requires gear (EVA for example)
3. most of the time people woill likely want to 'gear up', so what then?


Overall, I do not believe this PR will be a positive, and will cause more issues than it solves, especially considering how we already have an acceptable solution ingame (teleporter)

2024-12-25 12:37 UTC, FlamingLily commented
I've floated this idea a couple of times but I feel like this would be a good place to go into them in detail. I generally agree that this isn't the way to go about tackling the root issue here: namely that latejoining in an odyssey round kind of sucks. Presently, there are three options:
* You don't participate
* You get ferried down on the Intrepid, which is unlikely to happen unless the Intrepid was doing repeat runs anyway (and still has the same issue of "what if the Intrepid was compromised")
* You get teleported down onto the Intrepid, which requires someone with access to babysit the teleporter for latejoins, basically, and additionally still kind of has the Intrepid problem. Still, this is easily the most accessible option of the three.

If we accept that the existing teleporter isn't enough to handle latejoins, due to the inconvenience, I think what might be an acceptable thing to streamline that process is TF2 teleporters (Yeah, pretty much functionally identical).

They'd consist of two machines, an entrance machine and an exit machine. If both are secured in place *and powered*, someone can enter the entrance machine to be teleported to the exit machine. Both are mobile, and can be set up anywhere there is power (But, it only has one target: the exit, unlike the main teleporter which is configurable). This would let command staff (it'd presumably be locked in the teleporter room at roundstart) set up the entrance in a public place, and the exit on the intrepid, and allow for ease of access to the Intrepid. HOWEVER, it'd also solve the problem of "What if the Intrepid was compromised", as the hijackers could just disable the thing. It'd also allow for more teleportation locations given enough prep time (Unless this isn't wanted, in which case I'm sure the exit could be made static on the intrepid)

2024-12-28 18:25 UTC, NonQueueingMatt commented
I'm going to have to deny this PR. I don't like teleportation mechanics - they break the atmosphere, other than generally feeling like half-solutions  and I really don't want Odyssey to become gamified with these kinds of things. Even CM doesn't teleport you down to the LZ.

2024-12-28 18:25 UTC, closed without merging