Name change for the friendly space carps
Aurorastation/Aurora.3 pull request #20301
Opened 2024-12-24 15:37 UTC by ASmallCuteCat

Changes the name of "tame space carp" to "domesticated space carp", to reflect what it says in their description.

(i also found out that there was an actual difference between 'tame' and 'domesticated'. the more you know)

2024-12-27 21:14 UTC, ASmallCuteCat commented
!review

2024-12-27 21:34 UTC, alsoandanswer requested changes
The description should be changed to tame rather than the other way around. A chicken is domesticated, a lion is tamed.

2024-12-27 21:39 UTC, ASmallCuteCat commented
> The description should be changed to tame rather than the other way around. A chicken is domesticated, a lion is tamed.

Easy change - though I should ask, since the science sampler has unique text for the non-bitey carps: I don't remember the exact wording, but the line goes something like "has genetic markers for docile behavior".

Should that line be changed/taken out as well? I can do a little re-writing so that there's some consistency between description, name, and science sampler text.

2024-12-27 21:45 UTC, alsoandanswer approved these changes
No, this is sufficient. Docile basically means non-aggressive, which is about its behavior rather than its relationship to man.

2024-12-27 21:46 UTC, alsoandanswer requested changes

2024-12-27 21:46 UTC, alsoandanswer commented on code/modules/mob/living/simple_animal/friendly/carp.dm
> +	name = "domesticated space carp"
```suggestion
	name = "tame space carp"
```

2024-12-27 21:46 UTC, alsoandanswer commented on code/modules/mob/living/simple_animal/friendly/carp.dm
>  	desc = "A domesticated, floating space carp. Careful around the teeth."
```suggestion
	desc = "A tame, floating space carp. Careful around the teeth."
```

2024-12-27 22:49 UTC, alsoandanswer approved these changes

2024-12-28 18:20 UTC, NonQueueingMatt approved these changes

2024-12-28 18:34 UTC, merged