Cargo Vaurca
Aurorastation/Aurora.3 pull request #9783
Opened 2020-08-25 15:42 UTC by Geevies

* Blank Vaurca Drones ordered from cargo now start with an active filter port, meaning they won't immediately start suffocating.
* Blank Vaurca Drones now start with the correct hive colour.
* C'thur is now one of the possible randomly generated hive names.

Note to maintainers: Blank Vaurca Drones' Item Data will have to be changed.

New description:
`A brain dead, generic vaurca drone.`
New path:
`/mob/living/carbon/human/type_a_cargo`

It's not vital, but at the moment, the access requirement for these is `47`, which is Science access. Sometimes, medical orders these to teach newbies how to do surgery on vaurca. Thus it would be nice to have it be `47` OR `5`, which is medical access.

2020-08-25 15:43 UTC, Geevies commented
!review

2020-08-25 15:45 UTC, Geevies commented
(Testing done prior to adding the C'thur as a possible hive)
![image](https://user-images.githubusercontent.com/22774890/91196673-bd474b00-e6fa-11ea-85b1-3ea195e43d24.png)

2020-08-25 15:52 UTC, mikomyazaki requested changes

2020-08-25 15:52 UTC, mikomyazaki commented on code/modules/mob/living/carbon/human/species/station/vaurca/vaurca_subspecies.dm
>  		"phoron reservoir"    = /obj/item/organ/vaurca/reservoir,
Why not do the reservoir too while we're doing defines?

2020-08-25 15:52 UTC, mikomyazaki commented on code/modules/mob/language/station.dm
> +	new_name += " [pick(list("Zo'ra","Zo'ra","Zo'ra","K'lax","C'thur"))]"
This should be a weighted list.

2020-08-25 16:07 UTC, Geevies commented
![image](https://user-images.githubusercontent.com/22774890/91199181-cb4a9b00-e6fd-11ea-9845-faa6ce7a39ed.png)

2020-08-25 16:09 UTC, mikomyazaki approved these changes

2020-08-30 14:35 UTC, Arrow768 requested changes

2020-08-30 14:35 UTC, Arrow768 commented on code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Toxins.dm
> +			var/obj/item/organ/vaurca/filtrationbit/F = H.internal_organs_by_name[BP_NEURAL_SOCKET]
filtration bit vs neural socket

2020-08-30 14:37 UTC, Arrow768 requested changes

2020-08-30 14:37 UTC, Arrow768 commented on code/modules/organs/subtypes/vaurca.dm
> +	organ_tag = BP_NEURAL_SOCKET
filtrationbit vs neural socket

2020-08-30 14:37 UTC, Arrow768 commented on code/modules/mob/living/carbon/human/species/station/vaurca/vaurca_subspecies.dm
> +		BP_NEURAL_SOCKET      = /obj/item/organ/vaurca/filtrationbit
filtrationbit vs neural socket

2020-08-30 14:37 UTC, Arrow768 commented on code/modules/mob/living/carbon/human/species/station/vaurca/vaurca.dm
> +		BP_NEURAL_SOCKET       = /obj/item/organ/vaurca/filtrationbit,
filtration bit vs neural socket

2020-08-30 14:37 UTC, Arrow768 commented on code/modules/mob/living/carbon/human/life.dm
> +			if(I.contaminated && !(isvaurca(src) && src.species.has_organ[BP_NEURAL_SOCKET]))
filtration bit vs neural socket

2020-08-30 14:38 UTC, Arrow768 commented on code/modules/mob/living/carbon/human/human_species.dm
> +/mob/living/carbon/human/type_a/Initialize(mapload, var/new_species = null)
Whats the purpose of that extra argument here (that is then never used)?

2020-08-30 14:44 UTC, Arrow768 approved these changes

2020-08-30 16:11 UTC, merged