Vaurca Consular Fix
Aurorastation/Aurora.3 pull request #9784
Opened 2020-08-25 16:37 UTC by Geevies

* Zo'rane vaurca can be Zo'ra Consular Officer Breeders again.
* Zo'ra Consulars now get filter ports instead of odd looking breath masks.

2020-08-25 16:37 UTC, Geevies commented
!bugfix

2020-08-25 16:37 UTC, Geevies commented
!review

2020-08-26 00:54 UTC, Arrow768 requested changes

2020-08-26 00:54 UTC, Arrow768 commented on html/changelogs/geeves-zora_consular.yml
> +author: ChangeMe
Travis fails due to that

2020-09-01 12:16 UTC, NonQueueingMatt approved these changes

2020-09-01 12:16 UTC, NonQueueingMatt commented on code/modules/background/citizenship/vaurca.dm
> +			qdel(H.wear_mask)
this qdel here is a bit questionable but i don't think there's any other way?

2020-09-15 09:41 UTC, merged