Woodmanbad
Aurorastation/Aurora.3 pull request #9786
Opened 2020-08-26 03:11 UTC by TheDanseMacabre

WIP. There's still some things that need to be sorted out and there are some balance considerations to think about, for example the amount of magazines security gets for their .45s (now .40s) may need to be changed, and I may need to mess around with the snowflake guns we have that use 10mm. 
All done in accordance with: https://docs.google.com/document/d/18-mDVbO1DGXNjOGBAJH2GSe92LjMbKkY-d6SDox7ENU/edit

2020-08-26 03:11 UTC, TheDanseMacabre commented
!wip

2020-08-26 21:00 UTC, Alberyk commented on code/modules/projectiles/guns/projectile/automatic.dm
> +	desc = "A protoype lightweight, fast firing gun. Uses .35 "Light" rounds."
```suggestion
	desc = "A protoype lightweight, fast firing gun. Uses .35\ "Light\" rounds."
```

2020-08-26 21:00 UTC, Alberyk commented on code/modules/projectiles/guns/projectile/automatic.dm
> +	desc = "A lightweight, fast firing gun. For when you want someone dead. Uses .40 "Standard" rounds."
```suggestion
	desc = "A lightweight, fast firing gun. For when you want someone dead. Uses .40 \"Standard\" rounds."
```

2020-08-26 21:00 UTC, Alberyk commented on code/modules/projectiles/guns/projectile/automatic.dm
> +	desc = "The C-20r is a lightweight and rapid firing SMG, for when you REALLY need someone dead. Uses .40 "Standard" rounds. Has a 'Scarborough Arms - Per falcis, per pravitas' buttstamp."
```suggestion
	desc = "The C-20r is a lightweight and rapid firing SMG, for when you REALLY need someone dead. Uses .40 \"Standard\" rounds. Has a 'Scarborough Arms - Per falcis, per pravitas' buttstamp."
```

2020-08-26 21:00 UTC, Alberyk commented on code/modules/projectiles/guns/projectile/automatic.dm
> +	desc = "The NI 550 Saber is a cheap self-defense weapon, mass-produced by Zavodskoi Interstellar for paramilitary and private use. Uses .35 "Light" rounds."
```suggestion
	desc = "The NI 550 Saber is a cheap self-defense weapon, mass-produced by Zavodskoi Interstellar for paramilitary and private use. Uses .35 \"Light\" rounds."
```

2020-08-26 21:00 UTC, Alberyk commented on code/modules/projectiles/guns/projectile/automatic.dm
> +	desc = "A durable, rugged looking automatic weapon of a make popular on the frontier worlds. Uses .315 "Rifle" rounds. It is unmarked."
```suggestion
	desc = "A durable, rugged looking automatic weapon of a make popular on the frontier worlds. Uses .315 \"Rifle\" rounds. It is unmarked."
```

2020-08-26 21:00 UTC, Alberyk commented on code/modules/projectiles/guns/projectile/automatic.dm
> +	desc_fluff = "The STS35 is a durable, reliable and cheap to buy fully automatic battle rifle with many licensed manufacturers across the galaxy. It comes in different versions and calibres, this one
```suggestion
	desc_fluff = "The STS35 is a durable, reliable and cheap to buy fully automatic battle rifle with many licensed manufacturers across the galaxy. It comes in different versions and calibres, this one uses .315 \"Rifle\" rounds. The manufacturer markings have been filed off."
```

2020-08-26 21:01 UTC, Alberyk commented on code/modules/projectiles/guns/projectile/automatic.dm
> +	desc = "A powerful battle rifle, the M469 is a highly accurate and highly outdated skirmishing firearm of Zavodskoi Instellar make which is chambered in .315 "Rifle" calibre."
```suggestion
	desc = "A powerful battle rifle, the M469 is a highly accurate and highly outdated skirmishing firearm of Zavodskoi Instellar make which is chambered in .315 \"Rifle\" calibre."
```

2020-08-26 21:01 UTC, Alberyk commented on code/modules/projectiles/guns/projectile/automatic.dm
> +	desc = "The Z8 Bulldog bullpup carbine, made by the now defunct Zendai Foundries. Uses .250 "Intermediate" rounds. Makes you feel like a space marine when you hold it."
```suggestion
	desc = "The Z8 Bulldog bullpup carbine, made by the now defunct Zendai Foundries. Uses .250 \"Intermediate\" rounds. Makes you feel like a space marine when you hold it."
```

2020-08-26 21:01 UTC, Alberyk commented on code/modules/projectiles/guns/projectile/automatic.dm
> +	desc = "A classic submachine gun, copied by the Tajara. Uses .40 "Standard" rounds."
```suggestion
	desc = "A classic submachine gun, copied by the Tajara. Uses .40 \"Standard\" rounds."
```

2020-08-26 21:01 UTC, Alberyk commented on code/modules/projectiles/guns/projectile/improvised.dm
> +	desc = "A common sight in an amateur's workshop, a simple yet effective assembly made to chamber and fire .40 "Standard" Rounds."
```suggestion
	desc = "A common sight in an amateur's workshop, a simple yet effective assembly made to chamber and fire .40 \"Standard\" Rounds."
```

2020-08-26 21:01 UTC, Alberyk commented on code/modules/projectiles/guns/projectile/improvised.dm
> +	desc = "An improvised automatic handgun. Uses .40 "Standard" rounds."
```suggestion
	desc = "An improvised automatic handgun. Uses .40 \"Standard\" rounds."
```

2020-08-26 21:01 UTC, Alberyk commented on code/modules/projectiles/guns/projectile/pistol.dm
> +	desc = "A cheap Martian knock-off of a truly ancient gun. Uses .40 "Standard" rounds."
```suggestion
	desc = "A cheap Martian knock-off of a truly ancient gun. Uses .40 \"Standard\" rounds."
```

2020-08-26 21:01 UTC, Alberyk commented on code/modules/projectiles/guns/projectile/pistol.dm
> +	desc = "A NanoTrasen designed sidearm, found among law enforcement and security forces. Uses .40 "Standard" rounds."
```suggestion
	desc = "A NanoTrasen designed sidearm, found among law enforcement and security forces. Uses .40 \"Standard\" rounds."
```

2020-08-26 21:02 UTC, Alberyk commented on code/modules/projectiles/guns/projectile/pistol.dm
> +	desc_fluff = "The NT Mk58 is a ballistic sidearm developed and produced by Nanotrasen. Bulky and heavy, the Mk58 is nonetheless used by security forces and law enforcement for its ease of use, low m
```suggestion
	desc_fluff = "The NT Mk58 is a ballistic sidearm developed and produced by Nanotrasen. Bulky and heavy, the Mk58 is nonetheless used by security forces and law enforcement for its ease of use, low maintenance requirement, longevity, reliability - and most of all, extremely inexpensive price tag. A trademark of Nanotrasen security forces. It uses .40 \"Standard\" rounds."
```

2020-08-26 21:02 UTC, Alberyk commented on code/modules/projectiles/guns/projectile/pistol.dm
> +	desc = "A NanoTrasen designed sidearm, found among law enforcement and security forces. It has a wooden grip. Uses .40 "Standard" rounds."
```suggestion
	desc = "A NanoTrasen designed sidearm, found among law enforcement and security forces. It has a wooden grip. Uses .40 \"Standard\" rounds."
```

2020-08-26 21:02 UTC, Alberyk commented on code/modules/projectiles/guns/projectile/pistol.dm
> +	desc_fluff = "The NT Mk58 is a ballistic sidearm developed and produced by Nanotrasen. Bulky and heavy, the Mk58 is nonetheless used by security forces and law enforcement for its ease of use, low m
```suggestion
	desc_fluff = "The NT Mk58 is a ballistic sidearm developed and produced by Nanotrasen. Bulky and heavy, the Mk58 is nonetheless used by security forces and law enforcement for its ease of use, low maintenance requirement, longevity, reliability - and most of all, extremely inexpensive price tag. A trademark of Nanotrasen security forces. This one has a faux wooden grip. It uses .40 \"Standard\" rounds."
```

2020-08-26 21:02 UTC, Alberyk commented on code/modules/projectiles/guns/projectile/pistol.dm
> +	desc = "The x9 tactical pistol is a lightweight fast firing handgun. Uses .40 "Standard" rounds."
```suggestion
	desc = "The x9 tactical pistol is a lightweight fast firing handgun. Uses .40 \"Standard\" rounds."
```

2020-08-26 21:02 UTC, Alberyk commented on code/modules/projectiles/guns/projectile/pistol.dm
> +	desc = "A Zavodskoi Interstellar Tanto .40, designed to compete with the NT Mk58. Uses .40 "Standard" rounds."
```suggestion
	desc = "A Zavodskoi Interstellar Tanto .40, designed to compete with the NT Mk58. Uses .40 \"Standard\" rounds."
```

2020-08-26 21:02 UTC, Alberyk commented on code/modules/projectiles/guns/projectile/pistol.dm
> +	desc = "A small, quiet, easily concealable gun. Uses .40 "Standard" rounds."
```suggestion
	desc = "A small, quiet, easily concealable gun. Uses .40 \"Standard\" rounds."
```

2020-08-26 21:02 UTC, Alberyk commented on code/modules/projectiles/guns/projectile/pistol.dm
> +	desc = "A compact .35 "Light" handgun, extremely popular all throughout human space."
```suggestion
	desc = "A compact .35 \"Light\" handgun, extremely popular all throughout human space."
```

2020-08-26 21:03 UTC, Alberyk commented on code/modules/projectiles/guns/projectile/pistol.dm
> +	desc = "A compact NanoTrasen designed sidearm, popular with law enforcement personnel for concealed carry purposes. It has a faux wooden grip. Uses .35 "Light" rounds."
```suggestion
	desc = "A compact NanoTrasen designed sidearm, popular with law enforcement personnel for concealed carry purposes. It has a faux wooden grip. Uses .35 \"Light\" rounds."
```

2020-08-26 21:03 UTC, Alberyk commented on code/modules/projectiles/guns/projectile/pistol.dm
> +	desc_fluff = "The NT Mk21 Blackjack is a ballistic sidearm developed and produced by Nanotrasen. Unlike the related Mk58, the Blackjack is a rather high quality piece - typically issued to higher ra
```suggestion
	desc_fluff = "The NT Mk21 Blackjack is a ballistic sidearm developed and produced by Nanotrasen. Unlike the related Mk58, the Blackjack is a rather high quality piece - typically issued to higher ranking law enforcement personnel, the Mk21 is compact and chambered in .35 caliber. With all the bells and whistles of a modern, quality police pistol, the Blackjack's main drawback is the notoriously nippy recoil - .35 \"Light\" in such a small package can be unpleasant for the average shooter."
```

2020-08-26 21:03 UTC, Alberyk commented on code/modules/projectiles/guns/projectile/pistol.dm
> +	desc = "The Leyon LCC Everyman is a small pistol that holds five shots and is loaded with a stripper clip, popular for self-defense on Mars. Uses .35 "Light" rounds."
```suggestion
	desc = "The Leyon LCC Everyman is a small pistol that holds five shots and is loaded with a stripper clip, popular for self-defense on Mars. Uses .35 \"Light\" rounds."
```

2020-08-26 21:03 UTC, Alberyk commented on code/modules/projectiles/guns/projectile/rifle.dm
> +	desc = "A cheap ballistic rifle often found in the hands of crooks and frontiersmen. Uses .315 "Rifle" rounds."
```suggestion
	desc = "A cheap ballistic rifle often found in the hands of crooks and frontiersmen. Uses .315 \"Rifle\" rounds."
```

2020-08-26 21:03 UTC, Alberyk commented on code/modules/projectiles/guns/projectile/rifle.dm
> +	desc = "A perfect, pristine replica of an ancient one-shot hand-cannon. This one has been modified to work almost like a bolt-action. Uses .250 "Intermediate" rounds."
```suggestion
	desc = "A perfect, pristine replica of an ancient one-shot hand-cannon. This one has been modified to work almost like a bolt-action. Uses .250 \"Intermediate\" rounds."
```

2020-08-26 21:04 UTC, Alberyk commented on code/modules/projectiles/guns/projectile/sniper.dm
> +	desc = "An old semi-automatic marksman rifle. Uses .315 "Rifle" rounds."
```suggestion
	desc = "An old semi-automatic marksman rifle. Uses .315 \"Rifle\" rounds."
```

2020-08-26 21:04 UTC, Alberyk commented on code/modules/projectiles/guns/projectile/sniper.dm
> +	desc = "A lightweight Neyland 'Ranger' used within the Sol Navy and Nanotrasen Emergency Response Teams. Equipped with a scope and designed for medium to long range combat, with moderate stopping po
```suggestion
	desc = "A lightweight Neyland 'Ranger' used within the Sol Navy and Nanotrasen Emergency Response Teams. Equipped with a scope and designed for medium to long range combat, with moderate stopping power. Chambered in .250 \"Intermediate\" rounds."
```

2020-08-27 01:44 UTC, TheDanseMacabre commented
!review

2020-08-27 08:48 UTC, fernerr reviewed
I heavily disagree with changing the blaster sprites to use an ugly blue furnishing that will blend in with the armor of the tcfl, and be a general downgrade. Guns need to be kept visible from their user, not everything needs to be turned boring and tacticool.

As one of the only factions that uses wood furnishings for their guns, it adds to their uniqueness and it fits with the theme of being a low budget militia using outdated weaponry in the first place. Plus, the legion are not the only users of blaster weaponry.

If you disagree with this assessment, you need to put up a forum thread and link it here, as this it not the place for that kind of back and forth.

2020-08-27 08:54 UTC, fernerr requested changes
I know it's a pain in the ass, but if you intend to change the names of ammunition like this, the paths themselves need to be changed too, for example:

 /obj/item/ammo_magazine/**c45** -> /obj/item/ammo_magazine/**c40**

And so on, for the sake of consistency and making it easy to find them in code.
If you run into map errors resulting from this, do let me know and I'll help out if needed.

2020-08-28 03:19 UTC, TheDanseMacabre commented
https://forums.aurorastation.org/topic/14814-feedback-thread-danses-gun-changes/

2020-08-28 09:31 UTC, Geevies requested changes

2020-08-28 09:31 UTC, Geevies commented on code/modules/projectiles/ammunition/boxes.dm
>  	caliber = ".45"
```suggestion
	caliber = ".40"
```

2020-08-28 09:31 UTC, Geevies commented on code/modules/projectiles/ammunition/boxes.dm
> +	max_ammo = 10
```suggestion
	max_ammo = 7
```

2020-08-28 09:31 UTC, Geevies commented on code/modules/projectiles/ammunition/boxes.dm
> +	max_ammo = 10
these already shred antags enough as-is

2020-08-28 09:31 UTC, Geevies commented on code/modules/projectiles/ammunition/boxes.dm
>  	caliber = ".45"
a bunch of these calibers didn't change, despite the names doing

2020-09-04 06:39 UTC, closed without merging