Add initial version of cargo order logging
Aurorastation/Aurora.3 pull request #9797
Opened 2020-08-26 22:11 UTC by Arrow768

Adds logging of cargo orders to the database.

TODO:

- [ ] Add character ids to cargo_order
- [ ] Testing

2020-08-28 18:26 UTC, Arrow768 commented
!review (Yes, I know that travis doesnt like the migration atm)

2020-08-29 18:07 UTC, mikomyazaki approved these changes

2020-08-30 12:25 UTC, skull132 requested changes

2020-08-30 12:25 UTC, skull132 commented on code/controllers/subsystems/cargo.dm
> +			if("[coi.ci.id]" in itemcount)
```suggestion
			if(!isnull(itemcount["[coi.ci.id]"]))
```
technically faster.

2020-08-30 12:25 UTC, skull132 commented on code/modules/modular_computers/file_system/programs/civilian/cargo_control.dm
> +	if(!istype(user))
`usr` is _always_ of type `mob`. The variable `user` is pointless and should probably be avoided.

2020-08-30 12:25 UTC, skull132 commented on code/modules/modular_computers/file_system/programs/civilian/cargo_delivery.dm
> +	var/obj/item/card/id/I = user.GetIdCard()
same here. You can just use `usr`.

2020-08-30 12:25 UTC, skull132 commented on code/modules/modular_computers/file_system/programs/civilian/cargo_order.dm
> +	var/obj/item/card/id/I = user.GetIdCard()
And here.

2020-08-30 12:25 UTC, skull132 commented on code/modules/shuttles/shuttle_console.dm
> +
This check is pointless.

2020-08-31 19:15 UTC, merged