Research Module Gripper Fix
Aurorastation/Aurora.3 pull request #9806
Opened 2020-08-27 22:49 UTC by WilliamMurdoch

This should now let the science gripper pick up exosuit remote control chips. Fixes issue #9805

2020-08-27 22:49 UTC, WilliamMurdoch commented
!review

2020-08-27 22:49 UTC, WilliamMurdoch commented
!bugfix

2020-08-27 23:04 UTC, fernerr requested changes
Unneccesary comma

2020-08-27 23:04 UTC, fernerr commented on code/modules/mob/living/silicon/robot/items/gripper.dm
> +		/obj/item/remote_mecha,
```suggestion
		/obj/item/remote_mecha
```

2020-08-27 23:47 UTC, fernerr approved these changes

2020-08-28 09:56 UTC, Geevies approved these changes

2020-08-28 10:07 UTC, merged