Bluespace turfs no longer emit light.
Aurorastation/Aurora.3 pull request #9840
Opened 2020-08-31 14:16 UTC by Hockaa

Removes the light_color, light_power, light_range and dynamic_lighting vars from bluespace turfs.
Removes update_lighting() proc from bluespace turf's initilize proc.

Requested by Geeves.

2020-08-31 14:17 UTC, Geevies approved these changes

2020-08-31 14:18 UTC, Geevies commented on code/game/turfs/space/transit.dm
>  /turf/space/transit/Initialize()
you can remove this part as well

2020-08-31 14:25 UTC, Hockaa commented
!review

2020-08-31 16:23 UTC, NonQueueingMatt approved these changes

2020-08-31 16:46 UTC, fernerr requested changes
I need a proper explanation of why this is being removed when I spent a lot of time in the new shuttle update getting this to work properly with all the shuttle edges. Lighting updates take a little bit on transporting to new areas, but I don't feel that is reason enough.

2020-09-01 04:25 UTC, fernerr approved these changes
Reason is startup lag, particularly for the lighting system. Might look into adding a less demanding version at some point.

2020-09-01 11:56 UTC, NonQueueingMatt commented
We can probably do something similiar by just finding every mob in the shuttle and applying a blue filter to their view @fernerr @Geevies

2020-09-03 14:58 UTC, merged