Replica Katana Missing Sprites Fix
Aurorastation/Aurora.3 pull request #9872
Opened 2020-09-03 18:55 UTC by Sparkyhotdog

Fixes #9870. As above, the sprites were missing and also unassigned.

### IC changelog

- bugfix: "Fixed the replica katana not having back, belt or in-hand sprites."

2020-09-03 18:55 UTC, Sparkyhotdog commented
!bugfix

2020-09-03 18:55 UTC, Sparkyhotdog commented
!review

2020-09-05 18:56 UTC, Snakebittenn approved these changes

2020-09-07 02:15 UTC, alsoandanswer approved these changes

2020-09-07 02:18 UTC, Alberyk requested changes

2020-09-07 13:40 UTC, Sparkyhotdog commented on code/game/objects/items/toys.dm
>  	icon = 'icons/obj/weapons.dmi'
The sprites are _ever so slightly_ different, and I wasn't certain if that was deliberate to distinguish from real and replica

2020-09-07 18:04 UTC, Alberyk approved these changes

2020-09-07 18:24 UTC, merged